ddnet/ddnet

src/base/system.c
Fixes most of the build for me on OSX 10.10.1 (still have to do CPLUS_INCLUDE_PATH=/opt/X11/include ./bam ...).
Hopefully wouldn't break build for older OSX versions, I have no way to test :/
=> fix mac os build

src/game/client/gameclient.cpp, src/game/client/gameclient.h
Sometimes the client will predict the wrong hook strength, and this is an attempt to correct that, by making the client detect if it has strong/weak.
It only attempts to detect weak/strong between the client and other players (I think it would be possible to detect it between every player, but it would be more complex and require more work). Also, since the detection works by looking at past interaction between you and other players, there is a small delay before the detection takes effect. This is slightly noticable the first time you hook another player, but after that the predicted hook strength should be correct until one of you respawns.
I didnt add a config flag for it and just made it activated when antiping_players is active (not sure if that is the best solution)
=> Client side prediction of weak/strong hook

src/engine/client/client.cpp, src/engine/client/fetcher.cpp, src/engine/fetcher.h
A HTTP download following a vanilla download caused the progress bar to overflow as libcurl sends old data to the callback in the beginning of the download for some reason.
Also fixed a Segmentation Fault when the task object is deleted without aborting first.
=> Fix progress bar overflow and Abort segfault

src/base/system.h
not sure if the right header but it works for me
cc @heinrich5991
=> fix missing size_t definition on mac

src/engine/shared/demo.cpp
Fixing some incorrectly interpreted demo chunks via an additional flag.
Probably not compatible with older client!
```
[12:41]	EastByte	I'm pretty sure there is a delta tickmarker of zero in the demo
[12:41]	EastByte	and this causes the demo player to read 4 more bytes for extended size
[12:42]	EastByte	by checking CHUNKTICKFLAG_KEYFRAME instead of deltatick==0 the demo works
[12:44]	BeaR_	will take a look later (:
[12:44]	EastByte	:3
[13:39]	BeaR_	hm looks like the same bug, which causes this segfault https://github.com/def-/ddnet/issues/140#
[13:41]	BeaR_	a tick delta of 0 would a possible
[13:41]	BeaR_	aChunk[0] = CHUNKTYPEFLAG_TICKMARKER | (Tick-m_LastTickMarker)
[13:41]	BeaR_	and checking for CHUNKMASK_TICK would result in tickdetla 0 for Tick-m_LastTickMarker == 0
[13:43]	BeaR_ …
```
=> Fix bug when reading reading chunks with a tick delta of 0

src/base/system.c
WinAPI MoveFile() allows moving running executables unlike libc rename().
=> Winapi MoveFile allows moving the client.

src/engine/client/backend_sdl.cpp, src/engine/client/graphics.cpp, src/engine/client/graphics.h, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h
This will *maybe* fix #177 or rather improves performance of `gfx_quads_as_triangles`. Should be hopefully now more or less equal to the standard approach.
Tests appreciated
Not sure how the quads should be converted into a triangle strip, using AMD gpu and splited the quad to fit the AMD driver
=> Reduce amount of drawcalls when using triangles instead of quads

src/game/client/gameclient.cpp, src/game/client/gameclient.h
This replaces the old m_LastSendInfo feature which was only working for the player. Now i cleaned this up. Following works for player and dummy:
When info like player name or skin color changes a variable will be set so after 1 second the client will check if the info changed or if it was filtered by the server spam filter. If it was filtered the info will be send again and after 1 second will be checked again if it changed. So if you change your name two times quickly the client will send the second name every second until it changed on the server.
=> resend player/dummy info that filtered the server

src/game/client/gameclient.cpp
With this code it seems like rocket fly with dummy is perfectly or at least much better predicted (with antiping enabled).
It works by running the collision code for each player in (approximately) the same order as the server does. It is only a modification of the hook strength prediction patch, and the difference is that it the previous code was only applied to Tick(), while this applies the code to Move() and Quantize() of the charactercore as well.
=> (antiping) improve prediction of collision between players

src/game/client/components/camera.cpp, src/game/client/components/camera.h, src/game/client/components/menus_settings.cpp, src/game/variables.h
Hi.
During my play time on (mostly) vanilla and DDRace I occasionaly need to have
further vision without enabling dynamic camera, which is now tedious and is
performed in menu only.
The feature I need is to toggle dynamic camera via binds to allow for quick
switches between extended and normal vision without harming my close-range aim
which happens when I always have dynamic camera on.
I have implemented this feature myself and so I would be grateful if you could
review the code and maybe accept it into your branch.
Dynamic camera can now be bound to key with this command: bind <key>
toggle_dynamic_camera.
For now I have concerns on whether I did it right expanding variables.h with
dyn cam variables, changing which seems to have little effect in game.
Thanks in advance!
=> [Feature Request] Add dynamic camera console toggle feature

src/game/client/components/menus_settings.cpp
Replace ad hoc solution to dynamic camera key binding with call to console
command.
Since #204 was introduced we have a console command to toggle dynamic camera.
=> Remove code duplication

src/game/client/components/menus_ingame.cpp
This fix handles the case when player is in blue team and can't press 'Join Red' because the button shares the same state variable with 'Spectate' button.
This fix probably follows the 'hack' introduced in 16106d8ee.
=> Fix bug with 'Join Red' and 'Spectate' buttons sharing same state variable

src/base/system.c, src/base/system.h
This not only makes `str_utf8_decode` a compliant parser, but also fixes an
issue where overlong encodings led to undetected line breaks.
Implemented as per https://encoding.spec.whatwg.org/#utf-8-decoder.
Audited the following files, checking whether the new semantics work with the
existing code:
- src/base/system.c
- src/engine/client/text.cpp
- src/game/client/components/chat.cpp
- src/game/server/gamecontext.cpp
They all check whether the string is at its end separately.
Fixes #229.
=> Error out on overlong UTF-8 sequences

src/engine/client/client.cpp, src/game/client/components/chat.cpp, src/game/client/components/chat.h
- Fixes chat highlighting in demo playback (using snap local id only)
- Makes add_demomarker working in all recorders
=> Fix Demo Playback Highlight and Demomarkers

src/game/client/components/camera.cpp, src/game/variables.h
This PR closes #250 
A feature I wanted too, but forgot to implement it eventually.
New config variable was introduced, g_Config.m_ClDynCamMousesens. If client sets this variable then it will be used as InpMousesens when client toggles dyncam.
Otherwise it's ignored.
=> Dyncam saves mousesens. Closes #250

src/game/server/entities/projectile.cpp
Ignore characters, which can't collide e.g different teams, in the intersection test for projectiles.
Should fix https://github.com/def-/ddnet/issues/286
=> Fix collision bug with weapon projectiles

src/base/system.c
Just moved the includes to outside of #ifdef UNIX.
=> Made fs_getmtime works for window.

src/game/server/gamecontext.cpp, src/tools/config_store.cpp
=> Fix config_store for old maps that don't contain MAPITEMTYPE_INFO

src/game/server/gamecontext.cpp, src/tools/config_store.cpp
It was just using a heuristic, comparing the first 24 bytes. Memory unsafety
for configs that were shorter than 24 bytes.
=> Fix settings compare

src/engine/shared/config_variables.h, src/game/server/entities/dragger.cpp
=> Added sv_dragger_range.

src/base/system.c
(I can't read. Constant is described in
https://encoding.spec.whatwg.org/#utf-8-decoder step 3 second case.)
=> Fix a constant in the UTF-8 decoder

src/engine/shared/config.cpp, src/engine/shared/config_variables.h
This is useful for having multiple configs to start your client with but keeping the original settings if you want to start your client without a config. For example my maprelease config looks like this:
cl_save_settings 0
gfx_screen_width 1440
gfx_screen_height 900
gfx_high_detail 1
gfx_texture_quality 1
cl_showhud 0
cl_showchat 0
cl_showkillmessages 0
ui_page 9
br_filter_exclude_types ",RUS,USA,CAN,CHN,CHL,BRA,ZAF,DDNet,Infection,iCTF,gCTF,Vanilla,zCatch,openFNG,Monster,Block,Bomb,Foot"
=> Added possibility to discard settings

bam.lua, src/osx/notification.m
should be working now even if Apple changes default directories again
(compilation broke for El Capitan (10.11))
=> fixed/improved objective-c++ includepath (mac osx only)

src/game/client/render_map.cpp, src/game/variables.h
Signed-off-by: rbmz <rbmz@users.noreply.github.com>
=> cl_text_entities (show/hide text in entities) for performance

src/engine/client.h, src/engine/client/client.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h
should fix: #174 
not sure why m_aInputs was used previously (btw only m_aData should have been copied from there)
=> better get dummyinput directly from CControls

src/game/server/teams.cpp
Also removed a "bug", the players killed each other recursively. This wasn't a problem before I added the messages though.
=> added chat msg to reveal killer of locked team

.gitignore, src/game/client/components/players.cpp
Fix wrong calculation of weapon Angle in demo player, more here: http://forum.ddnet.tw/viewtopic.php?f=45&t=2717
and
Add *.dll to .gitignore (for Windows)
=> Fix wrong calculation of weapon Angle in demo player

src/game/client/gameclient.cpp
Fixes #335 
The details of this PR are written in #335. The way I chose to solve the issue decouples statboard reset from the demo recording as it was suggested in the issue.
=> Reset statboard after a game restart

src/engine/server/register.cpp
https://www.teeworlds.com/forum/viewtopic.php?pid=116308
=> Fix vulnerability, see official teeworlds news

bam.lua, other/mysql/mysql.lua
This is required in order to compile DDNet-sql versions on mac.
Previously mysql-libs were compiled with libc++ but rest of DDNet with libstdc++ resulting in a crash every time the ddnet-server tried to establish a sql-connection.
This, however, required to bump the macosx-version-min to 10.7.
=> fixed mysql compiling on mac

src/engine/shared/datafile.cpp, src/game/client/components/skins.cpp
CDataFileReader::Open(): Check the return status of io_read()
before reading the buffer, to avoid reading uninitialized data
in case the file was shorter than a full header.
CSkins::SkinScan(): Check that the image is high enough.
=> Improve the handling of invalid skins.

src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/config_variables.h
Only allow 10 requests per second before falling back to smaller server
info responses.
=> Add DoS protection to server info requests

src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/player.cpp, src/game/server/player.h, src/game/variables.h
This is a new delay that specifies how many seconds you have to wait
before making your first vote. In case the server was only recently
filled (e.g. by a map change or if people start joining an empty
server), this delay is disabled (in the first case, because it's normal
to join after a map change, in the second case because you might have
joined the empty server to vote for a different map).
=> Add sv_join_vote_delay

src/engine/shared/config_variables.h, src/engine/shared/network.h, src/engine/shared/network_server.cpp
- Added ratelimit (sv_van_conn_per_second) which triggers when there are too many vanilla connection attempts within a second. Once it is triggered, fall back to 'dm1' instead of transferring the complete dummy map in order to reduce traffic (Antispoof related).
- Drop control packets with invalid size.
=> Antispoof: vanilla connection default map fallback

src/engine/server/server.cpp
Fixes map download for 0.6.4
Note:
- Not sure whether the vital flag has impact on map fast download (could cause many resends on packet loss)
- Also not sure why the vital flag (on normal map download) was removed in the first place @eeeee https://github.com/teeworlds/teeworlds/commit/ee2647de#diff-25bcc1bcfab43c7e0957ca2fa89fe34fL1255
=> Added vital flag for mapdata (includes fast download)

src/game/client/components/menus.cpp
It's useless on vanilla & co, isn't it?
=> Show ingame Ghost tab only on race servers

src/game/collision.cpp, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/layer_game.cpp, src/game/editor/layer_tiles.cpp, src/game/mapitems.cpp, src/game/mapitems.h
Prevent placing unused tiles in the editor, can be turned off with a new switch in the editor
=> Prevent placing unused tiles in the editor

src/game/collision.cpp
Client and server used to remove unused tiles from the map when loading it. I can't see any reason to do so. It removed some entities used by other gametypes which where then unable to see in the entities clear.
=> dont remove unused tiles

src/game/editor/layer_tiles.cpp, src/game/editor/popups.cpp
Moves _Hookthrough_ up and replaces the outdated term _Evil_ for teleport.
=> Re-ordered the Gametiles-menu

src/game/server/ddracechat.cpp
Doing `/top5 0` can cause some problems... [See this](http://imgur.com/LgtjbEc) for an example. Apart from that it just makes no sense :worried:
=> Forbid showing /top5 from rank 0 on

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/game/client/components/hud.cpp, src/game/client/components/killmessages.cpp, src/game/server/player.cpp, src/game/variables.h
- Renamed cl_showping to cl_showpred
- Now shows prediction time in ms.
- No server compile needed now. (works with all servers)
=> Fixed cl_showping (now cl_showpred)

src/game/editor/editor.cpp
If a tile layer was in game group and had a automapper the gametiles and automapper buttons used to overlap.
=> fix editor gametiles automapper overlap

src/engine/shared/fifo.cpp
Without this the fifo is not read on OS X.
=> always read fifo from start

src/game/client/components/chat.cpp
Like one would expect it; this behaves exactly the same as if you'd do CTRL+arrowkey in any other text input.
The cursor jumps to spaces, any special character and uppercase letters within camel-case words.
I always missed this feature when writing long chat messages and then needing to change a single word somewhere in the middle :)
=> Jump to special characters with CTRL+arrowkeys in chat input

src/engine/shared/network_server.cpp
Since only the client can initiate the secure session, there's basically
no reason to send this magic to clients which didn't advertise the
feature.
=> Also don't send the token magic to unsupported clients

src/game/server/entities/character.cpp
The new dummy map "Greed" kills the dummy without warning you before and just places unlock team tiles before, I feel like this is going to get more common now because of the unlock team tiles. Because I didn't notice that my team was unlocked with clear entities turned off I panicked when I saw my dummy out of the map and used `/lock` which locked my team again which was unlocked by the unlock team tiles. I think the same happened to Fňokurka oo7: https://forum.ddnet.tw/viewtopic.php?f=6&t=4&p=40318#p40318
=> Send chat message when team is unlocked by a tile

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
Firstly I have a target to do a mix of types for edition boxes PROPTYPE_INT_STEP(which allows you to click plus(+) and minus(-) only) and PROPTYPE_INT_SCROLL(which allows you to type number or scrolling it using mouse).
But I can`t found any to just not upgrade PROPTYPE_INT_STEP to new mixed bar which allows you to use both features.
=> PROPTYPE_INT_STEP mixed to PROPTYPE_INT_STEP + PROPTYPE_INT_SCROLL

src/engine/shared/network_conn.cpp
During the recent ddos attacks I realized that the client sends a disconnect message to the server when it doesn't recieve a message for the time set by the setting `conn_timeout`. Often that happened and despite there were no messages reaching the client for 15 seconds that disconnect message reached the server which stopped the timeout protection from working.
I'm still testing if this solves the problem, don't merge yet!
=> Don't send disconnect on timeout

configure.lua
Error message is:
configure.lua:6: bad argument #1 to 'setfenv' (number expected, got nil)
=> Hopefully fix a problem bam.lua that I don't see locally

src/engine/client/input.cpp, src/engine/client/input.h, src/engine/input.h, src/game/client/components/chat.cpp, src/game/client/components/console.cpp, src/game/client/components/menus.cpp, src/game/client/lineinput.cpp, src/game/client/lineinput.h
From my c-client
https://www.teeworlds.com/forum/viewtopic.php?id=10838
Added on-the-spot style IME support described at [here](https://wiki.libsdl.org/Tutorials/TextInput) in SDL2 documents
Note: Currently working perfectly with Windows and some specifically IME that designed for SDL2 on Linux. Cannot test on Mac OS.
=> Full Asian IME support.

src/game/server/entities/character.cpp, src/game/server/entities/character.h
Frozen tees in freezing tiles can move for one tick if they are unfrozen. However this only works sometimes due to some really weird mechanics the freezing code relies on. This commit ensures that the 1-tick unfreeze always works.
=> Reliable 1-tick unfreeze

src/engine/server.h, src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/config_variables.h, src/game/server/gamecontext.cpp
Basic implementation of a "DNS-based Blackhole List" resolver
Can be used to block ip-addresses that are flagged as malicious / spam by anti-spam companies (eg. NiX Spam, Spamhaus, SpamCop, ...).
Options:
- sv_dnsbl - enable/disable
- sv_dnsbl_host - host of DNSBL provider
- sv_dnsbl_key - optional auth key
- sv_dnsbl_vote - prevent voting by blacklisted addresses
- sv_dnsbl_ban - ban blacklisted addresses (Warning: client might be able to join before the ban is triggered)
The implementation is rather passive and can also be used as drop-in solution (can be enabled/disabled at runtime).
//edit:
- dnsbl_status added (dumps a list of all blacklisted clients currently connected to the server)
=> Basic DNSBL implementation

.gitignore
`.gitignore` used to exclude `/src/versionsrv` as well as `/src/mastersrv` from git.
=> Fix .gitignore excluding some src directories

src/base/system.c, src/base/system.h, src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/server/server.cpp, src/engine/shared/config_variables.h, src/game/client/components/menus_settings.cpp
This way, servers can no longer hijack the timeout codes of clients.
Timeout codes are generated from md5(seed + dummy + server address).
If `cl_timeout_seed` is set to the empty string, the old config options
are used instead.
=> Generate server-specific timeout codes

src/engine/client/client.cpp, src/game/client/gameclient.cpp
#529
disabling copy moves during connecting is better than during disconnecting, in case for example the copy moves key was accidentally pressed while the primary tee was beating the noobfilter
=> dummy copyMoves/hammer disabling when dummy connecting

src/engine/server/server.cpp, src/engine/server/server.h
This lets 0.6.4 clients connect to DDNet servers again. Instead of doing
our own resend logic, just always send `sv_map_window` packets ahead and
let the Teeworlds network deal with possible resends.
=> Add the VITAL flag to fastdownload packets

src/game/client/components/items.cpp
Float inaccuracy causing the laser to look weird on servers with high gameticks. Why wasn't this fixed before?
This PR changes the expression from `int + float - int` to `int - int + float`
=> Fix laser rendering on high gameticks

src/game/editor/popups.cpp
To avoid confusion with the behavior of the button. 
Previously I was sure, that this button will save map "Details" into map.
=> map details button name fix

src/engine/console.h, src/engine/shared/console.cpp, src/engine/shared/console.h, src/game/server/ddracechat.cpp, src/game/server/gamecontext.cpp, src/game/server/player.h
This prevents player name exploits due to tab completion of nicknames
that could result in unwanted commands being executed.
Print a deprecation message that is supposed to be removed in the
future.
=> Disallow usage of semicolons in chat commands

src/game/server/gamecontext.cpp
Timeout codes lead to deallocation of the player structure, the
semicolon code tried to access it, resulting in a segmentation fault.
=> Fix a crash with semicolon handling and timeout codes

src/game/client/components/maplayers.cpp
Adding this line in the code will save one Graphics()->ClipEnable call and the cost of trying to render all tiles/quads in this group.
=> Skip clipped groups that are outside the screen

src/game/client/components/statboard.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h
Right now the statboard is not reset when a player leaves. When another player enters the same slot before the round ends, he gets the stats of the previous player.
Besides that, the ingame time is reset when a player joins from spec but the Frags-value is not. So the FPM-value is completely wrong after a player has been in spec.
=> Statboard fix

src/game/client/components/chat.cpp
- Type something, hit ctrl+backspace and it will delete the word (works like ctrl+left)
=> ctrl + backspace support on chat (Fixes ddnet#515)

src/game/client/components/binds.cpp, src/game/client/components/binds.h
`bind_print` without any arguments now dumps all binds this effectively deprecates `dump_binds`.
=> Remove dump_binds. Let bind_print dump all. Fixes #634

CMakeLists.txt
@Learath2 Can you check whether that removes the warnings?
=> CMakeLists.txt: Check for _FORTIFY_SOURCE before defining it

scripts/hash_passwords.py
Usage:
```
$ python scripts/hash_passwords.py --new username admin password
auth_add_p username admin 9415aef5cc5043800377584cff32b90c 26fd308aad6b04f2
```
```
$ python scripts/hash_passwords.py autoexec.cfg
```
updates all instances of `auth_add` to `auth_add_p`.
```
$ python scripts/hash_passwords.py autoexec.cfg \
--new user1 admin password1 \
--new user2 admin password2
```
updates all instances of `auth_add` to `auth_add_p` and adds two new
users.
On Windows, you should be able to drag-and-drop your config file onto
this script and have it automatically updated (not tested).
=> Add a tool to hash new passwords or to update config files

src/engine/client/client.cpp, src/engine/server/authmanager.cpp
It was horribly broken before. :) Only the first password set via
`sv_rcon*_password` worked, and that only due to a bug in `AddHashKey`
-- `AddHashKey` incorrectly assumed that only key slots greater than 0
are valid, but 0 is valid too.
Fix default passwords on password removal, fix no admin password being
generated if you only had `sv_rcon_mod_password` or
`sv_rcon_helper_password` set. Add an assert that would have caught our
mistake.
=> Fix handling of default passwords

src/game/client/components/chat.cpp
=> Fix array subscript below array bounds

src/base/vmath.h
The refactoring can cause a gameplay change, laws of associativity like
`x * (1 / z) == (x * 1) / z` don't hold for floating point numbers.
=> Partially revert #681

src/game/client/components/maplayers.cpp, src/game/client/render.h, src/game/client/render_map.cpp
Could be faster if we just render 8 rectangles with a "death tile" texture, but we need 3D texture for that (see #675).
I can of course remove the blinking effect, but I think it's better to give a hint that those tiles are not really in the map
=> Fix #586 (display the killing clipping rectangle)

CMakeLists.txt
MinGW apparantly accepts this flag, but can't successfully link
afterwards.
=> Check if -fstack-protector-all works before using it

CMakeLists.txt, src/benchmarks/textrendering.cpp
This is a small and dirty benchmark. Please tell me if I should make it differently. I will revert it once we are done with this branch.
The benchmark print during 10 seconds a wheel of text (hello in different languages), with various sizes. After this time, the program quit (or crash...) and display the number of frame per sec:
```
[17-03-16 18:59:20][benchmark]: result: 158.791187 fps
``` 
Once we have an acceptable benchmark, we can try to improve the text render :)
=> Add benchmark for text rendering

src/game/client/components/menus_settings.cpp
Localized text can obviously be longer then the original...
=> Properly calculate the width. Fixes #699

src/game/client/components/menus_demo.cpp
The error of `0.01f` is arbitrarily chosen, should be fine for this case.
=> Fix a couple of problems with the demoviewer.

src/game/client/components/console.cpp
Didn't push this with the other one b/c wasn't sure if this is desired. Could also only reset in case of a password input. Or could overengineer it with saving the buffer to another place.
=> Reset input when server/map changes. Fixes #633

src/base/system.h, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser.h, src/engine/server/server.cpp, src/engine/server/server.h, src/engine/serverbrowser.h, src/engine/shared/network.cpp, src/engine/shared/network.h, src/engine/shared/network_client.cpp, src/engine/shared/network_server.cpp, src/engine/shared/packer.cpp, src/game/client/components/menus_browser.cpp, src/mastersrv/mastersrv.h
This means that we have a reliable and fast way to query for extended info,
while also not wasting network bandwidth.
The protocol is designed to be extensible, there's four bytes space for
encoding more request types (currently zeroed), and there's one string in each
response packet and one string for each player available (currently the empty
string).
The protocol itself has no problems with more than 64 players, although the
current client implementation will drop the player info after the 64th player,
because it uses a static array for storage.
Also fixes #130, the player list is just sorted each time new player info
arrives.
=> Introduce new, vanilla-compatible server info protocol (also known as: the solution to all problems)

src/engine/server/authmanager.cpp
The generated rcon password never triggers the `ConchainRconPasswordChange` and that's why it's not added to the auth keys.
This PR makes generated passwords work again.
=> Fix: Add generated rcon password as default auth key

src/game/client/components/chat.cpp
Wrongly assumed the old messages were cleared by `m_Time` being 0 but missed that `m_Show` overrides it.
=> Remove heart from on reset messages

src/game/editor/io.cpp
pLayer->m_Flags is not set properly at this point which leads to all layers being treated as normal Layers which then leads to them being saved in a wrong way that crashes the client/server on mapload.
I did not dig too deep into this, I hope someone else can have a look too. It, however, appears to be working now.
This was introduced by https://github.com/ddnet/ddnet/commit/3589ed0b0fe5f01e02697c43692e6159821e8656
=> Access the correct Flags variable for saving maplayers

src/game/client/components/players.cpp
Fixes #556 by not using the predicted position for drawing the hook when the player is paused.
=> Show correct hook position in pause

src/engine/client/client.cpp
Even if this might not the case I encountered it is possible to reach this state. It would cause the fetch thread to read a `delete`'d object.
Tested, does no harm to neither the fallback nor the actual download.
=> Take a blind stab at #718

src/game/client/components/binds.cpp
Restore old behavior around the bind's Get() function, return "" if
there is no bind. Fixes #730.
=> Fix crashbug in bind system

src/engine/server/server.cpp
People with non-administrator rights won't be able to see ips (mod, helper).
=> Don't show ips to non-administrators, Fixes #694

src/game/ddracecommands.h, src/game/server/ddracechat.cpp, src/game/server/ddracechat.h, src/game/server/ddracecommands.cpp, src/game/server/entities/character.cpp, src/game/server/entities/door.cpp, src/game/server/entities/dragger.cpp, src/game/server/entities/gun.cpp, src/game/server/entities/light.cpp, src/game/server/entities/pickup.cpp, src/game/server/entities/plasma.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontroller.cpp, src/game/server/gameworld.cpp, src/game/server/player.cpp, src/game/server/player.h, src/game/server/save.cpp, src/game/server/teams.cpp
Fixes some odd bugs about the pause system. Including `/pause` while `/spec`, vice-versa and `force_pause`.
Consequently fixes the vote "Move player to spectators".
First reported in #628.
=> Rework the pause system

src/game/client/components/broadcast.cpp
InfectionClass sends a lot of these messages, and they flood both the console and stdout with this client (but not with stock Teeworlds client)
=> Hide empty broadcast messages.

.gitignore, CMakeLists.txt, bam.lua, datasrc/compile.py, datasrc/datatypes.py, datasrc/network.py, src/base/tl/base.h, src/engine/client/client.cpp, src/engine/message.h, src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/global_uuid_manager.cpp, src/engine/shared/protocol.h, src/engine/shared/protocol_ex.cpp, src/engine/shared/protocol_ex.h, src/engine/shared/protocol_ex_msgs.h, src/engine/shared/snapshot.cpp, src/engine/shared/snapshot.h, src/engine/shared/uuid_manager.cpp, src/engine/shared/uuid_manager.h, src/engine/uuid.h, src/tools/uuid.cpp
This system can easily be extended by independent authors without
collisions, something the old system with plain increasing integers did
not allow.
Do this by utilizing the previously unused message code `NETMSG_NULL`
which has a value of 0.
=> Add protocol extension with UUIDs

src/engine/shared/uuid_manager.cpp
It didn't cause misprinted UUIDs because the string buffers had the
correct size.
=> Fix UUID formatting - the last field only has 12 hex digits

datasrc/compile.py, src/engine/shared/snapshot.cpp
The UUID objects accidently made it into the lists of object sizes.
Also fix a possible out-of-bounds read inherited from vanilla.
=> Fix unpacking of net events

src/engine/shared/storage.cpp
Previously, using drive-relative paths could be used to escape the
Teeworlds directory on Windows.
=> Use `str_find` from `src/base/system.h` and check for `C:` on Windows

src/engine/shared/console.cpp
It's quite unsettling that this works at all :/ Didn't we use to validate the arguments passed?
=> Add toggling for string options

src/base/system.c, src/base/system.h, src/engine/client/friends.cpp, src/engine/shared/config.cpp, src/engine/shared/console.cpp, src/game/client/components/binds.cpp
This also fixes a couple of potential buffer overflows. The affected
code is still buggy (doesn't do the right thing on potential buffer
overflow), but at least it won't result in crashes/out of bound writes
anymore.
=> Ensure null-termination in `str_escape`

.gitmodules
This saves some space on the user's file system. They can still update
to the full history of the binaries if they want, e.g. with
```
git fetch ---unshallow
```
(https://stackoverflow.com/a/17937889/870079)
=> Suggest a shallow clone of the library submodule

src/game/client/components/binds.cpp
Kill is already bound to K by default, binding it on home as well doesn't really have any purpose. (?)
Furthermore, the home key is right next to page up which is bound to toggling entities.
It is very easy to accidentally hit home instead of page up, which is highly frustrating.. therefore I suggest removing this duplicate binding.
=> Remove default bind for home key (kill)

CMakeLists.txt, src/base/system.c, src/base/system.h, src/engine/client/input.cpp, src/engine/client/input.h, src/engine/shared/datafile.cpp, src/engine/shared/kernel.cpp, src/engine/shared/network_server.cpp, src/game/client/components/menus.cpp, src/game/client/gameclient.h, src/game/localization.h, src/game/server/entities/character.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/tools/map_extract.cpp
Also annotate `dbg_msg`, `str_format` and `str_timestamp_ex` so that the
compiler can determine whether the format strings are correct.
Fix the compiler warnings generated by these extra warnings -- some of
them were security issues.
=> Enable `-Wextra` and `-Wformat=2`

README.md
If you cloned ddnet without libs, these instructions explain how to clone only the libs.
=> Add instructions to clone libs

src/engine/map.h, src/engine/shared/datafile.cpp, src/engine/shared/datafile.h, src/engine/shared/map.cpp, src/game/client/components/background.cpp, src/game/client/components/maplayers.cpp, src/game/collision.cpp, src/game/editor/io.cpp, src/game/server/gamecontext.cpp, src/tools/config_retrieve.cpp, src/tools/config_store.cpp, src/tools/map_replace_image.cpp, src/tools/map_resave.cpp
Also rename the old `GetDataSize` to `GetFileDataSize`. `GetDataSize`
now returns the actual data size, not the data size before
decompression.
=> Rename `GetUncompressedDataSize` to `GetDataSize`

CMakeLists.txt, src/game/client/components/ghost.cpp, src/game/client/components/ghost.h, src/game/client/components/menus.h, src/game/client/components/menus_ingame.cpp, src/game/client/components/race.cpp, src/game/client/components/race.h, src/game/client/components/race_demo.cpp, src/game/client/components/race_demo.h
On systems that use a language with comma as decimal-point character, the decimal places of the ghosts and race demos are dropped. The sscanf call stops when it reaches the dot used by the servers.
The time parsing functions are probably a bit more complicated then needed, but they are able to parse the chat messages of any ddnet, ddrace and race version I encountered.
Seconds are parsed up to the third decimal place.
=> Ghost and Race demo time extraction fix

.gitignore, .travis.yml, CMakeLists.txt
On Linux, `install` installs DDNet into the normal file system (root
rights required).
`package` tries to create an archive similar to today's release archives
and `package_source` tries to create a source archive similar to today's
source archives.
=> Add `install`, `package` and `package_source` targets to CMake

bam.lua
Im having some problems with compiling ddnet on some macOS machines. I figured out that the crypto library causes this problem. And it works fine without on all different macOS machines i tested it. I guess this lib isn't needed anyways so i suggest to remove it to make compiling a bit easier c:
=> removed crypto lib from bam.lua (macOS compile improvement)

src/game/client/components/players.cpp, src/game/gamecore.h
This reverts commit 03faa51e2898409d84260395fc59e7704f9a5f8d.
Dividing floats by zero isn't undefined behavior and results in +inf or
-inf depending on the sign of the first operand.
```
#include <math.h>
#include <stdio.h>
#define PRINT(x) printf("%s = %f", #x, x)
int main()
{
PRINT(1.0 / 0.0);
PRINT(-1.0 / 0.0);
PRINT(atanf(1.0 / 0.0));
PRINT(atanf(-1.0 / 0.0));
return 0;
}
```
prints
```
1.0 / 0.0 = inf
-1.0 / 0.0 = -inf
atanf(1.0 / 0.0) = 1.570796
atanf(-1.0 / 0.0) = -1.570796
```
The changed function was problematic for values like (0,1), (-1,0),
(0,-1) where it always returned an angle of 0°.
=> Revert "Don't divide by 0"

src/engine/client/client.cpp, src/engine/server/server.cpp, src/engine/shared/compression.cpp, src/engine/shared/compression.h, src/engine/shared/demo.cpp, src/game/client/components/ghost.cpp
The missing bounds check in the int packing functions makes it possible, to at least crash the client with prepared snapshots. Malicious demo files could also be a problem.
=> Made int packing functions safe

.gitignore
It is created in case you open the project "as a folder", using the
native CMake capabilities of MSVS 2017.
=> Add `.vs` directory that is created by MSVS 2017

src/engine/client/client.cpp, src/engine/client/fetcher.cpp, src/engine/client/fetcher.h, src/engine/client/updater.cpp, src/engine/fetcher.h
Use a `CJob` instead. Also kept fetcher as a separate interface but it might also fit in `IEngine` along with `HostLookup`
Appears to be working on Linux x86_64. Please test it on another platform before merging.
=> Get rid of unnecessary queue in CFetcher

CMakeLists.txt, src/base/system.c, src/base/system.h, src/engine/client/client.cpp, src/engine/server.h, src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/engine.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/test/aio.cpp, src/test/async.cpp, src/test/thread.cpp
The asynchronous output uses a writer thread for every file; the buffer is kept in a dynamically growing queue that is thread-safe due to the use of locks.
=> Add asynchronous output system and use it for teehistorian and `dbg_msg()`s

src/game/server/gamecontext.cpp
There was a missing check that allowed chat messages to be written to
disk.
=> teehistorian: Hide chat from teehistorian

.travis.yml, CMakeLists.txt, appveyor.yml, circle.yml, cmake/Download_GTest_CMakeLists.txt.in
Enable tests on Circle CI, macOS on Travis and Appveyor.
=> Add a flag `-DDOWNLOAD_GTEST` to automatically download and build GTest

src/engine/client/backend_sdl.cpp
Seems like putenv is not defined in mingw. (i couldn't compile the client without this, with mingw)
Heinrich prefers a better version so maybe don't merge yet.
=> MinGW putenv workaround

src/base/system.c
=> Fix `-Wtypedef-redefinition` for `struct ASYNCIO`

CMakeLists.txt, src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h
That fixes the AMD driver bug, and readjusts fullscreen resolutions, so that the opengl viewport can render non dpi scaled at fullscreen(only) (if dpi awareness isn't enabled, e.g. windows 7)
=> VBO deletion after VAO deletion & viewport adjustment for dpi scaled displays at fullscreen

src/game/client/components/maplayers.cpp
I just forgot to fix that, when i was changing the buffer creation.
It just prevents invalid tiles, e.g. speedup without force, to be drawn
=> Don't draw invalid tiles

.travis.yml
We now ship SDL2 via ddnet-libs, it's not needed anymore. Fixes #893.
=> Don't use Brew on Travis anymore

src/game/client/components/background.cpp
Currently the LastLoad variable might block the map(especially when the %current% is used) to be loaded, when you join a server.
That led to try rendering a non initialized map.
Also now it's checked if a map for %current% even is loaded.
=> Initialize m_LastLoad in constructor and reset it when a new map is loaded

bors.toml
This will hopefully allow the macOS system on Travis CI to finish.
=> Use a longer bors timeout

src/game/server/gamecontext.cpp
You now have to use `/mc;` instead of `/` if you want to bind multiple
commands to one key.
=> Remove deprecated multi commands

src/base/system.c, src/base/system.h, src/test/aio.cpp
Previously, e. g. it was possible that newlines are separated from the
printed line in `logger_file`.
=> Add manual locking to `ASYNCIO` for transacted writes

autoexec_server.cfg, src/game/ddracecommands.h, src/game/server/ddracecommands.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/player.cpp, src/game/server/player.h
This PR adds a RCON command called "moderate", which enables a active moderator mode for the caller, so this will happen if a vote kick/spec is made:
- Vote will last atleast x seconds defined by CGameContext::m_VoteCloseTime (35 seconds on ddnet, according to @heinrich5991) even if there is majority.
- If a active moderator votes, it will be a force vote.
- If the active moderator doesn't vote, it will pass normally
- This is only for kick and spec votes.
I also added `access_level moderate 1` to autoexec_server.cfg
If there are any spelling errors on the code tell me.
Maybe needs to be tested more.
=> Active moderator mode

src/test/thread.cpp
This was uncovered when I tried to run other code with ThreadSan, but it
only found this. :(
=> Add a missing call to `lock_wait` in test function

CMakeLists.txt
Warnings for GTest broke the build because GTest turns warnings into
errors, which is undesirable if GTest is just used as a dependency.
See also https://github.com/google/googletest/issues/1373.
=> Disable warnings for GTest

src/base/system.c
Since `aio_thread` was crashing with #964 on an address that we didn't hand to `io_write`, I hope that this was just a bug with concurrently writing to stdout on Windows, and not a bug in the `aio` stuff.
Fixes #914. Fixes #964.
=> Fix some bugs related to asynchronous IO

src/game/server/ddracecommands.cpp
This pr basically makes mutes show another output when there are no mutes and also makes muteid don't fail silently when the id is not valid.
=> Add more output to mutes and muteid

src/game/ddracecommands.h
I notice everything else didn't have `;` at end of line so i made all the macro calls follow the same style.
=> fix style in ddracecommands.h

src/game/client/components/maplayers.cpp, src/game/client/components/maplayers.h
Also saw that I haven't counted the foreground layers correctly, which caused even more allocation.
=> RAM usage reduction for map buffering and foreground layer count fix

src/engine/server.h, src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/teehistorian_ex_chunks.h, src/game/server/gamecontext.cpp, src/game/server/teehistorian.cpp, src/game/server/teehistorian.h, src/test/teehistorian.cpp
This allows to check moderator actions after-the-fact.
=> Record rcon authentication stuff into teehistorian

.gitignore
Sort the stuff alphabetically, add some comments, ignore stuff that can
appear in build directories, so we don't have to guess the build
directory's name.
=> Organize .gitignore and also ignore build dir stuff

README.md
This follows the recent change that glew, pnglite and wavpack can use
the system libraries now.
=> Update README.md instructions for installing dependencies

cmake/FindGLEW.cmake, cmake/FindZLIB.cmake, src/engine/client/sound.cpp
Of course `WavpackOpenFileInputEx` is subtly incompatible to
`WavpackOpenFileInputEx64` in that it requires the userdata for the main
steam to be nonnull.
Fixes #1041.
=> Fix crash on startup due to sound initialization 

.gitignore
This rule caused a couple of problems with Visual Studio.
=> Remove the blanket rules for files without extension

src/game/client/components/scoreboard.cpp
Max length nick + max length clan, still overlap incase `32 < PlayerCount < 40` couldn't really figure it out.
Probably should just rewrite this mess of offsets and lengths in a more legible way.
=> A little more space for clan name. Fixes #724

src/game/server/teams.cpp
For speedrunning alone in a team this "Everyone in your locked team was killed because '%s' %s."
is very annoying. So better only print it if more than 1 tee is in the team.
=> Remove teamkill message on solo teams

CMakeLists.txt, src/base/confusables.c, src/base/system.c, src/base/system.h, src/engine/server/server.cpp, src/engine/server/server.h, src/test/str.cpp
This uses the Unicode confusable data together with judging how close
two strings are by using the Levenshtein distance.
Adds the commands `name_ban`, `name_unban` and `name_bans`. Kicks
players who join using a banned name and doesn't allow ingame players to
change their names to the banned ones.
=> Add possibility to ban players by name

CMakeLists.txt
Previously, if using an out-of-source build directory, git would report
an error and no revision string would be added to the final executable.
=> Execute `git_revision.py` in the source directory

src/game/client/components/controls.cpp, src/game/variables.h
I  register some new command, which are cl_control_dummy, cl_dummy_jump, cl_dummy_fire and cl_dummy_hook, to make dummy more controlable.
if i want to contol my dummy to jump, 
first, press f1 in game, and use "cl_control_dummy 1",
second, use "bind mouse1 +toggle cl_dummy_jump 1 0".
finally, i can contol my dummy to jump by pressing left mouse button.
=>  Provide more controlable command for dummy 

src/engine/shared/config_variables.h, src/game/server/entities/character.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/player.h
The broadcast timer is marked as unimportant and it won't overwrite if there was another broadcast sent less than 6 seconds ago. So vanilla clients won't miss any important news c:
=> Add broadcast importance (fixes #669)

src/game/server/ddracechat.cpp, src/game/server/ddracechat.h, src/game/server/gamecontext.h, src/game/server/player.cpp, src/game/server/player.h, src/game/variables.h
- Adds the chat command /modhelp <message>
- It sends `Moderator help is requested by %s (ID: %d):\nproblem here...` to all authed clients.
- The command has a configurable delay to prevent spam, defaults to 60 seconds.
=> Add /modhelp chat command

data/languages/simplified_chinese.txt
“Manual” here should be translated to “手动” or "手动录制" but not "手册"。
=> Change the wrong translation of Simplified Chinese

src/base/system.c, src/base/system.h, src/engine/shared/engine.cpp
Imo very important fix. E.g. basically everytime a glyph is uploaded there is a potential risk. (the easiest way to reproduce it is enable threaded sound loading and start the client a few times)
It doesn't create the "allocation list" for realease mode and adds a mutex for the debug mode.
=> Make mem_alloc, mem_free thread safe (fixes #1087)

src/base/system.c
This reverts commit 8f291ce5284d97353252db6ec852236fed1a355e.
=> Revert "Don't use aio logging to stdout on Windows"

src/game/variables.h
Since dyncam is disabled by default:
these are default static values.
=> Fix default dyncam values

src/game/client/components/killmessages.cpp, src/game/client/components/scoreboard.cpp, src/game/client/render_map.cpp
To be clear, the entity text was meant to be a bit higher, so the text of the overlay is not overwritten("FROM", "CFROM")?
Because there was -4.f added to the y coordinate. Atleast it looks pretty much the same as the old renderer now.
=> Some text positioning

src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/network.h, src/engine/shared/network_server.cpp
The `Reset` parameter was only ever set to true, at the only call site.
=> Remove superfluous parameter from `CServer::NewClientNoAuthCallback`

src/game/client/gameclient.cpp
If the latest fire input and the current differ in any way it causes firing.
So if you switch dummy after hammerfly was used it causes a weaponfire.
This unwanted fireing caused many unlucky fails for me already.
So i swap the fire status on dummyswapping so the server doesn't see any difference even if hammerfly was used.
=> Fix unwanted dummy fire

src/game/client/components/console.cpp, src/game/client/components/console.h
For now they were just hardcodet on page up and down keys.
The new command allows it to bind it for example on the f-keys for laptop users.
=> Add commands for switching pages in console

src/game/server/ddracechat.cpp
It's named ConCredits and there are many people credited so i guess the plural is fitting better c;
=> Rename 'credit' -> 'credits'

src/base/system.c
This comes at the cost of one allocation per started thread. This should
be okay because we're about to invoke a syscall anyway.
=> Fix warning about incompatible function pointers

src/game/server/entities/character.cpp
When using jetpack, tees don't do pain emotes when they're supposed to (e.g. when they get hit by exploding bullets).
Notice how in the image below the tee doesn't have the pain emote.
=> Fix pain emote immunity with jetpack

CMakeLists.txt
The `Security` framework is now needed on all targets because we link
libcurl everywhere.
=> Fix Mac linking for cross-compilation

src/game/editor/editor.cpp
Previously, when you added an image to the map in the editor, it would
start off as embedded, i.e. included in the map file. This does not make
sense for vanilla images as every client has those.
That's why we now only mark non-vanilla images as external by default.
=> By default, don't embed vanilla images

data/editor/round_tiles.rules
The other DDNet rule adds these round corners which messes up the gametiles function.
So i decided to publish my own rule im happily using since years especially for my gores maps. But since its also usefull for other gametypes even non ddrace ones i called it the "Chiller" rule^^
I couldn't find a better name for the rule idk if someone has a problem with it.
=> Add new freeze automap rule

src/engine/client/client.cpp, src/game/client/components/items.cpp, src/game/client/gameclient.cpp, src/game/extrainfo.cpp, src/game/extrainfo.h
for some reason the client doesnt render extrainfo projectiles if the gamemode wasnt ddnet
=> fix projectiles not rendering on mods based on ddnet

src/game/server/gamecontext.cpp
I also thought about using a `` if (str_find(m_aVoteCommand, "set_team"))`` in front of the pause reset.
But then i thought its ok to unpause the VoteVictim every time.
I didn't test but i could belive that this can cause some unwanted unpause for a player with the id of the last VoteVictim on a server type vote for example. Thats why i also reset the ``m_VoteVictim`` to -1 to avoid this.
=> Fix votespec on /pause (Fixes #1193)

src/game/server/ddracechat.cpp
Might also just remove `/modhelp`. So far it has proven to be pretty useless without accounts.
=> Require DNSBL check on /modhelp

src/game/client/components/menus_settings.cpp, src/game/client/components/skins.cpp
Fixes #1216
Didn't work on making the panel underneath show only vanilla skins, but it might be doable as well.
=> Changing vanila skins option no longer requires restart

src/game/editor/auto_map.cpp, src/game/editor/auto_map.h
Fixes #837 
Took a while to guess the right `sscanf` usage (since it does not detect unmatched input past the last format specifier).
=> Allow entering automapper rule probability as percentage

src/game/editor/editor.cpp, src/game/editor/layer_tiles.cpp
Before is on the left, after is on the right.
=> Copy tile layer color to brush and picker

src/engine/client/backend_sdl.cpp, src/engine/client/graphics_threaded.cpp
Automatically creates the older context, if OGL3 isn't supported
=>  Properly reset context attributes, if OpenGL3 context failed to create

src/game/editor/editor.cpp, src/game/editor/layer_tiles.cpp
This is to improve visibility when working with nearly-transparent layers. It shouldn't cause problems when working with partly-transparent layers.
=> Don't copy alpha when coloring the brush

src/game/editor/auto_map.cpp, src/game/editor/auto_map.h
There is some weird bug caused by my last changes, looks like automapper is working only fine for tiles without rotation.
I'm not really sure why it doesn't work with -1, so I did some workaround.
=> Fix automapper bug

src/game/editor/auto_map.cpp, src/game/editor/auto_map.h
Pretty simple yet super effective: 
If index rule has any `Pos 0 0` for non-empty tile, then it is flagged to skip all the empty tiles. And vice versa.
In many cases it will significantly speed up the process, especially when using big automappers on huge maps.
=> Optimize automapper a bit

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
- shift+drag to select quads. Selection is additive
- left click on any empty space deselects all quads
- moving, resizing, rotating etc. works for every selected quad
- fixed resizing quads on grid and in properties. Vertices don't land on the same spot
=> Selecting multiple quads

src/game/client/components/particles.cpp
Else NaNs are created, when deviding through zero(TimePassed), resulting in paricles not rendered.
=> Don't update particles, if no time passed

src/engine/server/server.cpp, src/engine/server/server.h, src/engine/server/sql_server.cpp, src/engine/server/sql_server.h
See note in https://dev.mysql.com/doc/connector-cpp/1.1/en/connector-cpp-examples-connecting.html
> get_mysql_driver_instance() calls get_driver_instance(), which is not
> thread-safe. Either avoid invoking these methods from within multiple
> threads at once, or surround the calls with a mutex to prevent
> simultaneous execution in multiple threads.
=> Global lock for MySQL Connector's get_driver_instance (fixes #1131)

src/game/editor/editor.cpp
I don't know how I managed to get this wrong.
Fixes #1178.
=> Duh. Fix editor embedding vanilla images and not others

.gitignore, CMakeLists.txt, datasrc/compile.py, src/engine/shared/datafile.cpp, src/engine/shared/datafile.h, src/game/mapitems.h, src/game/mapitems_ex.cpp, src/game/mapitems_ex.h, src/game/mapitems_ex_types.h, src/test/datafile.cpp
This works by utilizing the good old UUIDs – this way we can make sure
that we don't clash with other people extending the map format.
=> Add support for extra map items in datafiles

CMakeLists.txt
FindPythonInterp is deprecated since CMake version 3.12. Use Python to
automatically detect Python 3 or 2.
=> CMakeLists.txt: Replace PythonInterp with Python

src/game/editor/layer_tiles.cpp
Not sure if this is the best fix as passing `m_Brush.m_lLayers[BrushIndex]` from `editor.cpp:L2627` is out of bounds access.  @bojidar-bg could you take a look?
=> Fix editor crash

src/game/editor/editor.cpp
It doesn't really make sense to me but @12pm pointed out they are switched around for tele.
=> Switch around the colors for used/unused envelopes

src/game/client/components/menus_browser.cpp, src/game/client/components/menus_settings.cpp
Since 2696ac134ce08accc9a0266ee525596222fff57, whether to include auto update related code should only control by macro CONF_AUTOUPDATE.
This commit should fix #1374
=> Fix crash when auto update is off

src/base/system.c, src/base/system.h, src/engine/client/client.cpp
Consoles in windows are "devices", outputting to them through stdout is handled horribly in msvcrt. Accessing it properly through WinApi seems to fix the issue. This also reverts #1385  as the fix there is broken on Win7, half-baked on Win8 and meh on Win10.
=> Handle the windows console properly

src/game/server/ddracechat.cpp
Currently pause or spec voted is totally useless if no vote is running. This pr allows to use the commands as normal pause if no vote is running. So only one bind is required and not two.
=> Allow to use pausevoted as normal pause

src/engine/client/backend_sdl.cpp
Anyone got a bug number or knows why this doesn't work in SDL2 right now? Or are we doing something wrong?
=> Disable borderless on Mac (fixes #1413)

src/engine/server/sql_server.cpp
Should help with some crashes
Still doesn't call thread_init
Still shares statements and connections between threads
=> More SQL fixes

src/engine/client/graphics_threaded.cpp, src/engine/client/text.cpp, src/engine/graphics.h
This probably fixes the text rendering issue for some people(where random characters where missing).
I still think it's a driver bug, relating to `GL_COMPRESSED_ALPHA_ARB`, which is deprecated in newer OpenGL versions(that's probably why it worked with OpenGL3.3 and not with the older one, because our OGL 3.3 implementation uses `GL_COMPRESSED_RED`, which replaced the above)
To be extra sure, i also looked up the causing function:
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glPixelStore.xhtml
but it clearly says it supports texture compression.
Anyway, i did not fix this by using `GL_COMPRESSED_RED`, because this is only core in newer OpenGL versions.
see:
https://www.khronos.org/registry/OpenGL/specs/gl/glspec20.pdf
(Table 3.18, which only lists *_ALPHA not *_RED)
I just …
=> Don't use compression for text rendering

man/DDNet-Server.6, man/DDNet.6, man/DDNet.adoc, man/DDNetServer.adoc, man/generate.sh
Fixes #1240 
I added a simple script to generate the man pages.
To edit the man pages in the future, you must edit the `.adoc` files and then run generate.sh
You need asciidoc package to generate the manpages.
`sudo apt install asciidoc`
http://asciidoc.org/
Writing plain troff is a pain in the ass.
=> Add man pages with asciidoc

src/game/server/gamecontext.cpp
This is meant to help with dealing with trolls on test server since everyone can log into rcon there.
Shouldn't cause any problems anywhere else, I think.
=> Allow vote-kicking players with same auth level

src/game/editor/editor.cpp
Fixes #1452.
Not sure if this is the best possible way to fix the issue.
=> Fix crash when painting tiles from a non-switch to a switch layer

src/engine/server.h, src/engine/server/server.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/player.cpp, src/game/server/player.h
Currently weapon input is applied immediately when it arrives at the server, while hook/movement inputs are buffered and not applied until the tick the client predicted them for. This pr makes the server use buffered inputs for weapons as well, to ensure that inputs are in sync, and delays weapon inputs by the same number of ticks as other inputs if the input arrives early.
The physics and timing of weapons should otherwise be unchanged (the code in server.cpp was a workaround in an attempt to achieve this).
This could perhaps make it easier to play with jitter, which currently makes the timing of things like rocket jumps to be off. Due to the desync it is also currently not possible to counteract this by increasing the input buffering / prediction time.
I've only tested this on a local …
=> Sync weapon input with other input

src/test/git_revision.cpp, src/test/name_ban.cpp
`EXPECT_*` allows the test to continue even in the case of failure. Use
this where it makes sense to continue.
=> Use `EXPECT_*` rather than `ASSERT_*` in tests

src/game/editor/layer_game.cpp, src/game/editor/layer_tiles.cpp
- Adds auto game tiles button to every layer that has parallax 100 and is offset by full tiles (fixes #1231)
- Creates tele layer for automapping teleporters if it didn't exist before
- Increases game/tele layer size to match the layer you are automapping from
=> Add auto game tiles to all possible layers, increase layer size if needed

src/game/editor/editor.cpp
Fixes a weird bug when pressing space while envelopes/server settings/undolist editor is active: https://cdn.discordapp.com/attachments/459282348597313536/542490038361915424/2019-02-06_00-41-24.mp4
=> Fix editor render glitch

src/game/client/components/scoreboard.cpp, src/game/variables.h
Old color was rgb = (0.78, 1.0, 0.8)
In hsl = (125°, 100%, 89%)
Converted to hex hsl:
H = 125° / 360° * 255 = 89 = 0x59
S = 100% = 0xFF
since the TW HSL color system fobids too dark colors it uses l = 0.5 + 0.5 * L/255
so L = (0.89 - 0.5) * 2 * 255 = 199 = 0xC7
So in total we get 0x59FFC7 = 5898183
(Someone should just make a web interface where you can punch in all TW color formats and get them interchanged....)
=> Make cl_authed_player_color modifiable

src/game/client/gameclient.cpp
As reported by jao on Discord:
22:26 jao @Learath2 client auth level needs to reset on server join or something
22:28 jao because other servers don't send it
=> Reset authed level in client

src/engine/shared/config_variables.h, src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp
And persist the result. Helps with the workflow described by Shyzo on
Discord:
> I mean after i press ctrl-f or fetch info. then i want to sort by marker (from ... to 0) and just delete every demo without a marker. either in a whole (not possible i think) or just one by one. but I think after deleting one demo the order of demos change again
> so i have to fetch info again, delete one. fetch info again. delete one
> and so on
=> Demo browser: Make Fetch Info a checkbox instead

src/base/system.c, src/base/system.h, src/test/str.cpp
As deducted from https://github.com/ddnet/ddnet/pull/1527
=> str_format: always return length of written string

src/game/editor/editor.h, src/game/editor/layer_tiles.cpp, src/game/mapitems.cpp, src/game/mapitems.h
Should be handy for mapping.
Can be disabled by activating unused tiles (don't think it's worth a separate toggle and if you want to do it, you're doing something unusal)
=> Don't rotate static game tiles and fix switch rotation

src/base/system.c
For example when closing client.
=> thread_sleep: ignore signal interruption

src/game/client/components/maplayers.cpp, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/layer_tiles.cpp, src/game/mapitems.cpp, src/game/mapitems.h
New brush draw mode that doesn't override existing tiles. Empty brush still acts as an eraser. Button and ctrl+d shortcut to toggle it.
=> Add non-destructive brush drawing

src/game/client/components/menus.cpp
Not the menu. Otherwise when opening the menu again the popup will reappear for one frame before disappearing.
=> Escape during popup: Only make popup disappear

src/engine/client/text.cpp
Instead show □ (white square, 0x25a1) as replacement character
The old behaviour was to continue when a glyph was missing, not load
the glyph and then instead fill the bitmap with random garbage that was
still in the buffer. Introduced by https://github.com/ddnet/ddnet/pull/1081
@Jupeyy
=> Fix text render when a glyph is missing (fixes #1543)

src/game/editor/popups.cpp
Partial manual cherrypick of https://github.com/teeworlds/teeworlds/commit/de82ad7a26d6ebb6029a6e60c619f8a310ea2ee6.
=> Allow editing texture UV offsets in Quad properties

src/test/str.cpp
On some architectures char can be unsigned, which makes g++
very unhappy.
error: narrowing conversion of '-128' from 'int' to 'char' inside { }
=> Fix negative numbers in char

src/game/server/score.h, src/game/server/score/file_score.cpp, src/game/server/score/file_score.h, src/game/server/score/sql_score.cpp, src/game/server/score/sql_score.h, src/game/server/teams.cpp, src/game/server/teams.h
The motivation is to have the exact same timestamp for every member
finishing in a team and the team rank as well. This makes the database
more consistent and tooling easier.
Will test now whether this actually works. Update: seems to work.
=> Make timestamp consistent in scores

src/game/client/components/menus_demo.cpp
otherwise it's uninitialized and then read, found by valgrind --tool=memcheck
=> Always initialize m_InfosLoaded

src/game/server/entities/laser.cpp, src/game/server/entities/projectile.cpp, src/game/variables.h
Need this for a map fix and doesn't hurt to have for grenades too I guess. Defaults are still the same
=> Add delete projectiles on death settings

src/game/server/save.cpp
Fix a bug where the solo state from the save doesn't get loaded properly.
I think it's the `CharacterCore` not being updated, but I'm not sure, nor do I have the setup to test it.
=> Fix solo bug

src/engine/server/server.cpp
```
$ grep -nr 'IConsole::OUTPUT_LEVEL_STANDARD, "server"' src/ | wc -l
31
$ grep -nr 'IConsole::OUTPUT_LEVEL_STANDARD, "Server"' src/ | wc -l
1
```
=> Fix inconsistant uppercase server in logs

src/engine/shared/config_variables.h, src/game/client/components/players.cpp, src/game/client/gameclient.cpp, src/game/client/prediction/entities/character.cpp, src/game/client/prediction/entities/character.h, src/game/client/prediction/entities/pickup.cpp, src/game/client/prediction/gameworld.h
Fixes freeze prediction with antiping off and stopper/speedup/super prediction on some servers, and adds prediction for weapon switches and gunfire animation (with antiping on). (some of the prediction code related to super still needs to be cleaned up)
It also includes a new setting for freeze prediction, cl_predict_freeze 2, that lets you keep a small amount of misprediction in freeze (equivalent to 30-40 ping) regardless of ping so that you still can see a little movement when frozen, in case someone wants that.
=> Some prediction fixes (fix #1680)

src/test/color.cpp
Previous execution time: 650 ms / 661 ms total (98%)
Now:                       3 ms /  15 ms total (20%)
=> Make Color.HRHConv test runtime more reasonable

src/game/client/components/binds.cpp
This patch checks if there are compound binds first, and only if there aren't it runs the non compound ones.
Not sure if this is a great fix but it'd help with issues like the one mentioned by @fokkonaut
=> Try to be more accomodating of old players

src/game/client/components/items.cpp, src/game/client/components/players.cpp, src/game/client/gameclient.cpp, src/game/client/prediction/entities/character.cpp, src/game/client/prediction/entities/character.h, src/game/client/prediction/entities/projectile.cpp, src/game/client/prediction/gameworld.cpp, src/game/client/prediction/gameworld.h
Fixes direction of ninja animation (#1707) and jerky hammer animation (#1709)
Also:
-Make ninjajetpack prediction work again
-Disable antiping for grenades with cl_predict 0
-Fix grenade prediction on fastcap (no collision with others)
-Improve grenade prediction on non-ddnet servers slightly by detecting who fired a projectile when possible
=> A few more prediction fixes

src/game/client/components/menus_demo.cpp
Should fix a bug reported in #1702
=> Ignore binds in slice save menu

src/game/client/gameclient.cpp
This caused lags due to too much output during gameplay, demo playback
and demo cutting.
Fixes #1643.
=> Remove item invalidation logging for unknown UUIDs

src/game/client/prediction/entities/character.cpp
Fix #1766.
Turns out the bug was not just in the rendering, but in the prediction itself (hooks were not predicted unless/until they grabbed on to something). I compared with an older client (and the old implementation) and this seems like it will restore the old behavior.
=> Fix prediction of non-grabbed hook

src/base/system.c, src/base/system.h, src/engine/shared/config.cpp, src/engine/shared/config.h, src/engine/shared/config_variables.h, src/engine/shared/console.cpp, src/game/client/components/menus_settings.cpp, src/game/client/gameclient.cpp, src/game/server/teehistorian.cpp, src/game/variables.h, src/test/teehistorian.cpp
Using the sign bit doesn't seem the safest.
C++11(4.7p3)
> If the destination type is signed, the value is unchanged if it can be represented in the destination type;
> otherwise, the value is implementation-defined.
and C99(6.3.1.3) seem to agree that the conversion from long to int is implementation-defined and thus could differ. I'm not really certain if it matters though, as it's rare to have an implementation that doesn't just discard the extra bits and within an implementation it's defined so atleast colors on one system will be consistent.
=> Store colors unsigned

src/game/server/entities/character.cpp, src/game/server/player.cpp, src/game/server/player.h
3 sec respawn is particularly annoying on dummy maps, when you hit a kill tile you have to wait 3 seconds for your dummy to respawn (or switch to dummy and press mouse1)
=> respawn is now instant, but rate limited to 3 sec unless player clicks mouse1

src/engine/shared/demo.cpp
Fixes corrupted demos if there is a different version of the current map in the maps/ folder.
Thanks to @archimede67 for initial research.
Who ever implemented that probably thought maps/ is a good source of truth because the user put a map intentionally there. It has no crc check tho.
Tested this fix with already downloaded maps and maps only present in maps/ folder. Worked fine.
Fixes a bug from the issue #1702 .
=> Prefer downloadedmaps over maps ( #1702 )

src/game/client/components/console.cpp
The code is a duplicate of https://github.com/ddnet/ddnet/blob/master/src/game/client/components/chat.cpp#L190.
I was thinking about a helper in CLineInput but since a console only has ctrl-delete and no ctrl-backspace. It would be a mess.
=> Add console word deletion/navigation (#1032)

src/game/server/player.cpp
The solo flag isn't currently being sent on these servers (only tunings for hook and collision), which causes grenades to mistakenly be predicted to collide with others (when client and server both use ddnetcharacter).
=> Set and send solo status on servers with sv_solo_server and sv_team 3

src/game/client/components/hud.cpp, src/game/client/components/hud.h, src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/variables.h
This reverts commit e8362f1727043e6c71bc994fe12e18bfcbe455c2, reversing
changes made to 0f99605ab1850ea7ca1f93e48654f59e8589294c.
Apparently people don't like "Digital Wellbeing"-like features @sirius1242
=> Revert "Merge pull request #1736 from sirius1242/master"

src/game/client/components/nameplates.cpp
`cl_show_others_alpha` needs to be applied to the outline aswell.
This also syncs up the `OtherTeam` with `CPlayers::IsOtherTeam`. In an ideal world, this function would be refactored somewhere else and used by the components.
=> Fix nameplate outline alpha

src/osxlaunch/client.m
This fixed 
`objc[52886]: Class SDLApplication is implemented in both /Users/learath2/Desktop/C/ddnet/ddnet-libs/sdl/mac/lib64/SDL2.framework/Versions/A/SDL2 (0x10c8ac680) and /Users/learath2/Desktop/C/ddnet/build/./DDNet (0x10c46c090). One of the two will be used. Which one is undefined.`
Not sure if this was an issue for anyone, but at least it doesn't break anything.
=> Fix small issue

src/game/server/teams.cpp
This has an unfortunate(?) consequence of causing tees that hit kill tiles and fall out of map respawn instantly. If this is undesirable the fix would be a little more complex, maybe implementing a delay to the spawn in `CPlayer` or reordering the entity list to force strong on the tee (by swapping with one of their teammates (this might have some undesirable effects aswell, not sure though)).
=> Force spawn order of teams. Fix #1828

.gitignore
compile_commands.json is used a lot for language servers
https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html
tags are generated from ctags
=> Ignore some more common files

src/engine/textrender.h, src/game/client/components/mapimages.cpp, src/game/client/components/mapimages.h
Closes https://github.com/ddnet/ddnet/issues/1721
Before:
Now:
It is done for "buffered" mode. Therefore, it works for OpenGL 3.3 only.
=> Centered entities text

src/engine/client/client.cpp
This fixes an issue I noticed with replays. When you change the map but you stay on the same server, the temporary demo file used to save replays isn't deleted since the map name has changed.
This adds a way that will delete every single demo file in tmp/ directory under demos/replays, so that no more temporary files are kept.
=> Fix keeping tmp files on map change

src/game/server/gamecontext.cpp, src/game/server/score/sql_score.cpp
0 star maps are a thing:
```
MariaDB [teeworlds]> select * from record_maps where stars = 0;
+-----------------+----------+--------+-------+----------------+---------------------+
| Map             | Server   | Points | Stars | Mapper         | Timestamp           |
+-----------------+----------+--------+-------+----------------+---------------------+
| CYO             | Moderate |      5 |     0 | =CuBe=         | 2015-07-31 13:35:00 |
| Flappy Bird     | Solo     |      0 |     0 | Saavik         | 2014-02-15 16:56:00 |
| NUT_short_race3 | DDmaX    |      0 |     0 | Zeta-Hoernchen | 2016-02-19 18:51:00 |
| NUT_short_race6 | DDmaX    |      0 |     0 | Zeta-Hoernchen | 2016-03-11 18:24:00 |
| NUT_short_race7 | DDmaX    |      0 |     0 | Zeta-Hoernchen | 2016-03-16 18:56:00 |
| …
```
=> Handle 0 star random map votes

src/engine/server.h, src/game/server/score/file_score.cpp, src/game/server/score/file_score.h
The filescore system did not handle map paths well that were an actual path and not just the mapname.
```
$ ./DDNet-Server 'sv_map "DDNetPP-maps/BlmapChill"'
[...]
[2019-09-15 13:29:44][filescore]: opening 'records/DDNetPP-maps-BlmapChill_record.dtb' for reading failed
$ ./DDNet-Server 'sv_map "DDNetPP-maps/BlmapChill"'
[...]
[2019-09-15 13:31:05][filescore]: opening 'records/BlmapChill_record.dtb' for reading failed
```
I called ```Server()->``` in a thread so please review thread safety before merge.
=> Fix filescore path

cmake/FindCurl.cmake
It's installed basically everywhere and just increases release size.
They're serious about backward compatibility and haven't had a breaking
change in ages.
=> Don't bundle libcurl for Linux

src/game/server/player.cpp, src/game/server/teams.cpp
Mimic old behavior of having a respawn tick > 0 ticks after current tick. 2 ticks later is still "instant enough".
The code below the change mentions strong spawning, so without deciphering it we simply give 2 extra ticks to make sure that it executes before spawning (2 instead of 1 so that it definitely executes for both primary and dummy).
=> Properly force spawn order of teams. Fix #1828

src/game/server/entity.cpp
There isn't really any sane behaviour here, so I just avoided the infinite loop.
You shouldn't be in the wall to begin with :P
=> Add a limit to GetNearestAirPos. Fix #1931

src/engine/client/backend_sdl.h
Fix by @heinrich5991
from the documentation of objc_msgSend in <objc/message.h>
```
/* Basic Messaging Primitives
*
* On some architectures, use objc_msgSend_stret for some struct return types.
* On some architectures, use objc_msgSend_fpret for some float return types.
* On some architectures, use objc_msgSend_fp2ret for some float return types.
*
* These functions must be cast to an appropriate function pointer type
* before being called.
*/
OBJC_EXPORT void
objc_msgSend(void /* id self, SEL op, ... */ )
OBJC_AVAILABLE(10.0, 2.0, 9.0, 1.0, 2.0);
OBJC_EXPORT void
objc_msgSendSuper(void /* struct objc_super *super, SEL op, ... */ )
OBJC_AVAILABLE(10.0, 2.0, 9.0, 1.0, 2.0);
```
=> Fix objc_msgSend() xcode11 error

src/game/client/components/players.cpp
Afk emote on your own dummy is pointless and annoying, esp on dummy maps.
=> Don't locally render your own dummy's afk emote. Other players will still see it

src/game/client/gameclient.cpp, src/game/variables.h
Idea by @ChillerDragon :
Only resets the active tee. So if you hold right and switch your
dummy keeps walking. But if you switch back you don't have
to press right twice to walk again.
Fix #1854
=> Add cl_dummy_resetonswitch 2

src/engine/server/server.cpp, src/engine/shared/demo.cpp
As reported by valgrind --tool=memcheck:
==344082== Conditional jump or move depends on uninitialised value(s)
==344082==    at 0x483BC85: strlen (vg_replace_strmem.c:461)
==344082==    by 0x5B9E61D: __vfprintf_internal (in /usr/lib/libc-2.30.so)
==344082==    by 0x5BB0409: __vsnprintf_internal (in /usr/lib/libc-2.30.so)
==344082==    by 0x222AE7: str_format (system.c:2350)
==344082==    by 0x2196AB: CStorage::GetPath(int, char const*, char*, unsigned int) (storage.cpp:274)
==344082==    by 0x219DDD: CStorage::RemoveFile(char const*, int) (storage.cpp:409)
==344082==    by 0x255D3C: CClient::DemoRecorder_Stop(int, bool) (client.cpp:3546)
==344082==    by 0x2569E7: CClient::ConchainReplays(IConsole::IResult*, void*, void (*)(IConsole::IResult*, void*), void*) (client.cpp:3727)
==344082== …
=> Fix uninitialized variable

src/game/client/gameclient.cpp, src/game/client/gameclient.h
I tried profiling DDNet with callgrind/valgrind and gprof, and a large amount of time seemed to be spent in Evolve in gameclient.cpp. By optimizing/memoizing the function, the percentage of total cpu time went from 50% to 2% in callgrind (the game would basically just freeze before the optimization), and a somewhat smaller difference for gprof. (I'm not sure how large the difference will be in practice, and running with a profiler might exaggerate the difference a bit)
This function is called if the client has an out-of-date character from the server, and advances the character to the current tick. However, in many cases the character doesn't  change between snapshots (for example, if a player is standing still the server will save bandwidth by not sending a new character every snapshot), …
=> Optimize character evolve

src/game/client/components/players.cpp
This allows you to still see other players signaling you with their hook coll when you have cl_show_hook_coll_always enabled.
=> Invert hook coll colors when using cl_show_hook_coll_always and +showhookcoll is pressed

src/base/color.h, src/game/client/components/chat.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/players.cpp
- SetAlpha should be called WithAlpha and only works for RGBA
- Fix type correctness of color_scale and introduce color_invert
- Nicer hook coll color handling in RenderPlayer
- Use CRTP to have type safe WithAlpha, otherwise this would compile:
`ColorHSLA = WithAlpha(ColorRGBA(1.0f, 1.0f, 1.0f));`
Follow-up to https://github.com/ddnet/ddnet/pull/1968
=> Clean up color handling a bit

src/game/editor/auto_map.cpp
In case of something like: INDEX 0 OR 1 all tiles need to be automapped.
=> Fix: automapper skips tiles when it shouldn't

README.md
I was told that that cmake failed on Crypto not found and installing libssl-dev solved the issue. Could not reproduce it tho.
When compiling ddnet7 with mysql. Might be a issue with ddnet7 only tho so not sure.
=> Add libssl-dev as dependency

src/game/client/components/players.cpp
Since we can go back in time in demo player
=> Only start showing emoticons after their start tick has passed (fixes #2025)

CMakeLists.txt
(cherry picked from commit cc2be456d4d95bb3196e8201a06ce19403dfc3c9)
=> Properly display hdiutil status in CMake

src/game/editor/editor.cpp
This fixes a problem in the editor server settings, if you were to press the del key in the editbox while having a command selected, it deletes it.
Now you can press that key in the editbox without any worry of deleting any selected command.
=> Fix del key removing commands while in editbox

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/message.h, src/engine/server.h, src/engine/server/server.cpp, src/engine/server/server.h, src/game/client/components/emoticon.cpp, src/game/client/gameclient.cpp
(cherry picked from commit https://github.com/teeworlds/teeworlds/commit/9023796d270b216c5859cc6b351a91a4656c58ec)
=> fixed faulty message id

scripts/languages/readme.txt, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/client/updater.cpp, src/engine/client/updater.h, src/engine/serverbrowser.h, src/engine/shared/config.cpp, src/engine/shared/config.h, src/game/server/gamecontext.cpp
to prevent race conditions with multiple clients running when saving maps, config on quit, during upgrade
=> use pid in file names of temporary files

cmake/FindCurl.cmake
This prevents accidental dependence on one specific version of
libcrypto.
=> Don't look for libcrypto if bundling libcurl

src/game/client/components/maplayers.h
This PR fixes build error while building DDNet for Fedora Rawhide.
Build error seems like this:
```
FAILED: CMakeFiles/DDNet.dir/src/game/client/components/background.cpp.o
/usr/bin/c++  -DCONF_OPENSSL -DCONF_WAVPACK_OPEN_FILE_INPUT_EX -DGLEW_STATIC -D_FORTIFY_SOURCE=2 -I/usr/include/freetype2 -I/usr/include/ogg -I/usr/include/opus -I/usr/include/SDL2 -I/usr/include/wavpack -Isrc -I../src -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -O2 -g -DNDEBUG   -fdiagnostics-color=always …
```
=> Fix build error for Fedora Rawhide

src/engine/client/video.cpp, src/engine/client/video.h, src/engine/shared/demo.cpp, src/engine/shared/video.h, src/game/client/gameclient.cpp, src/game/variables.h
This option default is open, which means video rendering will pause when demo playing pause, we can use this to:
- change player spec to
- check demo playing speed
- check playing progress
I think this is better.
There is a modification which make tee not transparent when playing demo from server with commit 5dab6e2e1, but if you don't like it, you can undo this modification.
=> Add option to pause video rendering when demo playing pause

src/game/server/entities/character.cpp
`m_Core.m_HookedPlayer` can be -1 if you get teleported the moment you'd
normally attach the hook.
=> Fix antibot crash

README.md
required for building ddnet on a fresh arch linux installation
(noticed while trying to build ddnet on the arch linux docker image)
=> added base-devel alphabetically to dependency list

src/engine/shared/config_variables.h, src/game/client/gameclient.cpp
Origin auto demo recording of ddnet will generate lots of demo files especially when playing in mods which have shorter rounds, such as infclass. I added a new option to open a new demo file only when connect to server (include map changing), this is disabled by default, and can use `cl_auto_demo_on_connect 1` to open. It works only when `cl_auto_demo_record` open.
=> Add an option to only start a new demo when connect while automatically record demos

src/engine/shared/demo.cpp, src/engine/shared/demo.h
Apparently there are maps out there with broken headers advertising the wrong map size. This allows demos to be recorded on those.
Example of such a map is `ctf4_old_d668e9fa_2f472051b26b6bffaa4af8990cf882cafd6364e00e1333b77762cb9911e49464.map`
Hosted on `Allround Network`
Reported by teini94 on discord
=> Fix demo recording with broken maps

src/game/server/antibot.cpp, src/game/server/antibot.h, src/game/server/gamecontext.cpp
The resource deallocation needs to happen in symmetry with the
allocation, otherwise we get unmatched dealloctions leading to crashes.
Allocations happened in `CAntibot::Init`, but it was not guaranteed that
this was called before the destructor.
=> Fix `AntibotDestroy` being called twice

src/game/server/antibot.cpp, src/game/server/antibot.h, src/game/server/gamecontext.cpp
I could not find an easy way to ensure that `AntibotDestroy` is only
being called once for each `AntibotInit` but still happening after all
the `CPlayer` destructors.
=> Fix the double-free of the antibot

src/engine/client/client.cpp, src/engine/client/video.cpp, src/engine/client/video.h, src/engine/shared/demo.cpp, src/engine/shared/video.h
Did some small modifications to console video start (using video_start command):
- Fix bug that demo can't play when demo pause and then use console video start.
- If demo playing paused when console video start, video rendering will not begin until video playing continue.
I think this will make experience of console video start more comfortable, you can pause demo playing and type video_start in console, quit console and continue demo playing, then console will not be rendered into video.
=> Fix bug about console video start

src/game/client/components/spectator.cpp, src/game/client/components/spectator.h
Spectates the tee closest to the one you are currently spectating.
This commit brought to you by COVID-19 lockdown boredom.
Fix #1793
=> Add spectate_closest

src/engine/shared/config_variables.h
because of common graphics issues. As suggested by Jupstar
=> Make gfx_resizable default to 0

src/engine/client/client.cpp
Just a small fix to let the client not try to get high fps, when it "thinks" it didn't render for a long time.
(is still affected by the SDL check "if window has input" at the cl_refresh_rate calculation, so not a 100% fix).
=> Change last render logic, when inactive

cmake/FindNotify.cmake
The LibNotify name is not used anywhere?
=> Fix CMake LibNotify warning (fixes #2141)

src/engine/client/client.cpp
In the game we already have highlighted text and sounds, we don't need to bother with notifications.
=> Don't push notification when active

.github/workflows/build.yaml
Currently seeing:
```
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/pthread.h:331:6: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
```
and
```
In file included from /Users/runner/runners/2.169.1/work/ddnet/ddnet/src/engine/client/backend_sdl.cpp:15:
/Applications/Xcode_11.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'signbit' in the global namespace
using ::signbit;
~~^
/Applications/Xcode_11.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:318:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
~~^
```
=> Fix macos github action

src/game/client/components/chat.cpp
The problem was that the string is empty after going through the trim, thus the main displaying loop doesn't run, but the sound still does. Verified that it works.
=> Fix empty sound (fixes #2163)

README.md
=> Add build-essential dependency to debian build instructions

src/game/editor/io.cpp
The reason is that we increased the sensitivity of the modified flag to
include adding layers and groups, and simply loading the map already
adds those, so every loaded map was considered modified.
=> Don't count freshly loaded map as modified (fixes #2178)

src/engine/server/server.cpp
I'm guessing this also caused #2149 
It just required a weird combination of players and name length to trigger (or max packet)...
=> Reserve bytes for the type and token

other/ddnet.appdata.xml
This tags required for [Flathub AppData Guidelines](https://github.com/flathub/flathub/wiki/AppData-Guidelines).
If watch this tags in [FreeDesktop AppStream Guidelines](https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html), `content_rating` tag is optional but `releases` tag required.
If you want to know a little bit more about `OARS`, watch [this](https://hughsie.github.io/oars/index.html).
=> Improve AppStream manifest

src/game/editor/editor.cpp
Encountered crash when checking out some old maps (e.g. [Demon_72eab2fd](https://heinrich5991.de/teeworlds/maps/maps/Demon_72eab2fd.map) from heinrich5991's map collection). Will now show "Invalid" in the label instead of crashing. "Invalid" is a bit long in comparison to the size of the label, but it shouldn't ever be encountered on a usual map.
=> boundary check on curve type label in editor, avoids client crash

src/game/server/save.cpp
I checked if the format string has changed with this c file: https://gist.github.com/Zwelf/12eb85c47e3ca0691db7710bec497bd6
```bash
$ gcc check.c 
$ ./a.out 
load string compare: 0
get string compare: 0
```
I also checked if the variable names matched with vim (by concatenating the lines with J) and the browser search functionality.
=> Break save/load string into multiple lines

src/game/editor/auto_map.cpp
```
src/game/editor/auto_map.h:47:9: warning: ‘*((void*)& NewConf +16)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
```
I don't think it's an actual problem
=> Silence GCC warning

src/game/server/ddracechat.cpp
If a person is attempting to enable practice mode for the *first time ever* (unfamiliar with it) and they're doing it with a dummy rather than a real player, the current message doesn't really explain the voting procedure very well. I for one expected to see an f3/f4 vote dialog and even filed a bug report on the matter (#2222). The current message does mention "/practice" but it didn't make me think "ok now I need to switch to my dummy and type /practice". For example when a person types "/map Epix" it doesn't then require everybody on the server to *also* type "/map Epix"..... in that case it uses the normal f3/f4 vote dialog.
=> clarified /practice voting instructions

src/game/editor/editor.cpp, src/game/editor/layer_quads.cpp, src/game/editor/layer_sounds.cpp, src/game/editor/layer_tiles.cpp
Still affects many values in editor, for example colors in tiles and quads.
Thanks to Pipou for report.
=> Don't clamp values that have no reasonable values

src/game/server/entities/character.cpp, src/game/server/entities/character.h
If you don't have a certain weapon in your last m_SavePos and you get a weapon and then use /r before touching the ground, currently it's bugged and you'll *appear* to have that weapon still out after you use /r.... except it doesn't fire. This is because weapons are saved/restored as of cacf17bd966e200523c8287991255c528f30c6ee
A map to test this buggy behavior is Aim 5.0; swing and get the sg and then use /r before you hit the ground. It will *appear* as though you still have the sg, but it won't fire.
=> Save active weapon with /rescue

src/game/client/prediction/gameworld.cpp
I haven't been able to find the exact source of the problem yet, but at least this seems to get rid of the segfault. The crash only happened with with recent versions of gcc and -O3 for me.
=> Workaround for client crash on predicted explosion

src/game/client/components/menus.cpp
@Jupeyy I'm not completely familiar with the text rendering code but I think it needs a large rework. The code isn't concise or easy to read, the interface is horrendous.
e.g. That `MaxWidth` parameter on `DoLabel` is an integer and it's used completely wrongly leading to a out of bounds read.
=> Fix out of bounds read

src/twping/twping.cpp
The timer ticks way faster on macOS leading to some insane pings :D
=> Consider time_freq()

src/engine/server/server.cpp
`GameServer()->OnShutdown(true);` (which would wait on running threads to exit)
wasn't called if an error occured in the server init. Therefore `CServer` was
freed before the init-thread finished executing, causing a use after free from
`CSqlConnector::ms_ppSqlReadServers` pointing to `CServer->m_apSqlReadServers`.
Fixes #2271 
Note that the server exits when creating tables failed. Since the tables are created by default, it has to be disabled explicitly (e.g. `add_sqlserver r teeworlds record teeworlds PASSWORD "localhost" 3306 0`) if the servers should start even when the database connection fails.
=> Fix segmentation fault when creating sql tables failed

src/engine/server/server.cpp, src/engine/shared/config_variables.h, src/engine/shared/network_server.cpp
In case of emergency, stops accepting 0.7 clients, registering on 0.7 masters and replying to 0.7 serverinfo requests.
=> Implement a switch for 0.7 compatibility

src/game/server/score/sql_score.cpp, src/game/server/teams.cpp
Only notify the player initiating /load about the error and don't send
'Loading initiated by ...' and 'Saving initiated by ...' messages resulting
in two messages per /load and /save.
Not sure if the old behavior is better or if we want to keep the new with sending two messages per /save and /load.
=> Restore old message behavior when using /load and /save

src/engine/server/server.cpp, src/engine/shared/network.h, src/engine/shared/network_conn.cpp, src/engine/shared/network_server.cpp, src/game/server/ddracechat.cpp
Turns out there is no way to influence `m_LocalClientID` anymore. Another thing changed for the sake of change.
Removing the check whether an `m_LocalClientID` has already been set allows 0.7 clients to reclaim their tees after clientinfo is resent. It should be fairly trivial for custom clients to send an extended message to enable timeout protection.
=> Disable timeout for 0.7 clients

src/game/server/gamecontext.cpp
This also renames `/r` to `/rescue` for them, but it's not that much of an issue as they have completion for it.
=> Fix command overlaps in 0.7

src/base/system.c
```
src/game/server/ddracecommands.cpp:743:39: warning: unknown conversion type character ‘l’ in format [-Wformat=]
743 |  str_format(aBuf, sizeof(aBuf), "%s-%lld-%s.save", pSelf->Server()->GetMapName(), time_get(), pSelf->Server()->GetAuthName(pResult->m_ClientID));
```
See https://sourceforge.net/p/mingw-w64/wiki2/gnu%20printf/
=> Fix str_format on mingw

src/game/server/player.cpp
Players need not have characters at all times
=> Check for a null CPlayer::m_pCharacter

src/game/gamecore.h
Since it won't write into invalid memory when Num > 0
=> Disable -Wstringop-overflow warning in IntsToStr

src/engine/server.h, src/engine/server/server.cpp, src/engine/server/server.h
This should let us get a quick idea of how many people are actually using the bridge.
Also adds the const qualification which could enable more optimization.
=> Log join type

src/game/server/teams.cpp
Noticed that team state wasn't sent to the client in some cases (when SetForceCharacterNewTeam is called directly), which I think this could happen if a team is unlocked between killing and respawning a player. Also added a CheckTeamFinished for that case.
=> Ensure that team state is always sent (fix #2315)

src/engine/client/http.cpp, src/engine/client/updater.cpp
just grew over 16 KB and thus updates failed. I still need to setup update5 server and will need to release a last release on update4 to have a seemless upgrade-path.
Update: https://update5.ddnet.tw/update.json is ready, 14.0.1 will still land on update4, then we switch to update5.
=> Allow any update.json size

src/game/server/score/sql_score.cpp
Fixes #2362, supersedes #2367 
I didn't change the /save message. There are already two different: "Use '/load %s' on %s to continue" and "Use '/load %s' to continue".
I think it would be better to add a NetMessage, this could also solve the problem of saving which team members were in the team.
>  I guess this can't be used to cheat anything?
Only if an instant rehook is necessary. Might be useful for rehooking an edge hook (but you still have to aim).
=> Restore old /save behavior

src/engine/shared/console.cpp
Missed this due to the the ability of calling `.Pack()` with default arguments :/
=> Fix color toggles

src/base/system.c
Fixes so that Firefox and other browsers wont output warnings
=> Suppress open_link output

src/engine/server/server.cpp
This reverts commit e69f747e5fc00ec19add95946055c7288ececb91.
Fixes `shutdown` on the initial command line which is also used on CI.
=> Revert "Don't run UpdateServerInfo if server isn't initialized yet"

src/game/server/player.cpp
Honestly, this isn't really the best fix, it'd probably be best to rate limit the query itself more harshly but this is how it behaved in the past before @Zwelf's rework.
=> Spam protection on /rank

src/game/server/teams.cpp
Fixes #2445 
vulnerable versions: 
* 506602d472c48821b6e7bb846b86431a113834a1..59a7e1f1873ad58b838cd3470d51b6ba84c02926~
* b99bbccd248437c928b25e32d40deaf98d8ef3ad..4186622d8750f4288be86b9064886a86c665c45d~
Problem was that `OnFinish` is only suited for team0 finishes, where `/practice` can't be enabled. Solo server finishes have to be handled like team finishes in CheckTeamFinished, which checks if `/practice` was enabled.
=> Fix storing finish on solo server with practice mode enabled

src/engine/server/server.cpp, src/engine/server/server.h
"./DDNet-Server shutdown" still works
=> Fix uninitialised values in sixup differently (fixes #2421)

src/engine/shared/config.cpp
As a consequence changed defaults in an update will be respected
instantly if the player hasn't changed the value.
=> Only write non-defaulted config values to settings_ddnet.cfg

src/game/client/component.h, src/game/client/gameclient.cpp, src/game/client/gameclient.h
Fixes warning:
[kernel]: failed to find interface with the name 'updater'
=> Don't request IUpdater interface when built without updater

src/game/collision.cpp
Probably related to #2487, was previously fixed and caused stoppers not to work.
```
src/game/collision.cpp:902:247: warning: bitwise or with non-zero value always evaluates to true [-Wtautological-bitwise-compare]
src/game/collision.cpp:891:252: warning: bitwise or with non-zero value always evaluates to true [-Wtautological-bitwise-compare]
src/game/collision.cpp:885:251: warning: bitwise or with non-zero value always evaluates to true [-Wtautological-bitwise-compare]
```
=> Fix compiler warning in stoppers without changing physics

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/game/client/gameclient.cpp, src/game/client/gameclient.h
- Fix a use-after-free when there are no new snapshots for the cl_dummy tee after the switch: #2499 .
- When one of the tees is hooked, cycling through them will no longer show phantom hook for the other tee: https://youtu.be/mxVT4pdyGnU.
- Dummy switch might happen a bit quicker since it doesn't depend on receiving new snapshots.
- Simplified code: m_LastDummy2 is no more.
=> Improved dummy switching

src/base/system.c, src/base/system.h, src/game/client/components/scoreboard.cpp, src/game/client/components/statboard.cpp, src/test/str.cpp
and rename to str_utf8_truncate since it's only used for utf8 strings
=> Fix utf8 handling in str_truncate (fixes #2533)

src/base/system.c
```
system.c:2325:2: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
for(int cursor = 0, pos = 0; pos <= truncation_len && cursor < dst_size && size != cursor; cursor = str_utf8_forward(src, cursor), pos++)
```
=> Satisfy old C standard

src/game/server/player.cpp
Timed out players kills entire team especially on t0 maps. So i just thought we can flag them as afk.
=> Flag afk when player timed-out

src/engine/shared/network_server.cpp
Theoretically, a regression test would be nice here, but we don't really
have the infrastructure…
This fixes a spoofing vulnerability.
=> Fix the same token being generated for each client

scripts/move_sqlite.py
Good that I looked over the script again. Additionally fixed that the script tell the user to delete too much after finishing the transfer. To clarify: the backup database `ddnet-server.sqlite` shouldn't be deleted.
Solves #2565
=> Improve sqlite transfer script

src/game/server/score.cpp
Can be reliable reproduced by finishing in this sequence:
1. A, B
2. A, C
3. B, C <- triggers error
Fixes #2568
=> Remove incorrect check when inserting team ranks

src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser.h, src/engine/shared/config_variables.h, src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp
Fixes #2633.
Did the sorting in groups of 100 ping, since that seemed more readable and less confusing.
Example:
=> Sort servers by a combination of players and ping as default

src/game/client/gameclient.cpp
since sometimes with dyncam it can be just at the border.
As reported by Lady Saavik
=> Send larger distance when zooming

src/engine/shared/config_variables.h
Proper fix would be https://github.com/Learath2/teeworlds/commit/7f594afc9be9b402263f18f866a8b59abb08cbe1
Would be great if someone could provide and test it.
=> Use borderless by default on Mac (fixes #2632)

src/game/server/entities/character.cpp
Fixes #2532 for newer client versions by checking if the player released fire in between presses instead of checking for autofire.
=> Fix permanent pain sound with dummy hammer in freeze

src/engine/client/backend_sdl.cpp
Sadly didn't see it earlier, old API still binds its samplers to textures directly.
Need this before steam release @def-
=> No sampler calls in old OpenGL API

src/base/system.c
Made sure everything from
https://en.wikipedia.org/wiki/Whitespace_character#Unicode is included
As reported by Im 'corneum
=> Forbid some more whitespace and whitespace-like characters

src/game/client/components/menus_browser.cpp
"Indicate map finish" is not responsive so it might be hard to figure out what does this toggle does for new players.
=> Refresh browser on "Indicate map finish" click

src/engine/server/register.cpp, src/engine/server/server.cpp, src/engine/shared/network.h, src/engine/shared/network_server.cpp
Due to a34c72530bd9b419b83dc3892a687f9ddda3964a we may see "[register]: ERROR: configure your firewall/nat to let through udp on port 0."
Reason: reading port data from configs but not from server object itself
I am new to server code, take a close look to changes please
=> Read server port from CNetServer but not from app config

src/engine/server.h, src/engine/server/server.cpp, src/engine/server/server.h, src/game/server/gamecontext.cpp
Official servers weren't affected because they didn't use the default of
`sv_port 0`.
=> Fix server port in teehistorian

src/engine/client/client.cpp
Was broken by the recent Steam name update.
=> Use the correct name for determining ranks

src/engine/client/serverbrowser.cpp
One from each country and so on instead of doing one country fully first
before moving to the next. This makes loading servers like Japan and AUS
much faster since they're at the back of the list. This also reduces the
peak number of packets sent to each IP at once.
=> Load serverbrowser more fairly

CMakeLists.txt
This allows building without rpath modifying on Linux which seems to be
needed for openSUSE packaging.
Fixes #2669.
=> Make steam_api dependency static on Linux non-Steam builds

src/game/client/components/menus_settings.cpp
Since people just randomly click it and then complain about bad looking graphics
=> Remove Quality Textures & Texture Compression from graphics menu (fixes #2676)

src/game/client/components/menus.cpp
Old OpenGL, 100% reproducible:
=> Set blend mode on background render

src/engine/client/client.cpp, src/engine/client/steam.cpp, src/engine/steam.h, src/steam/steam_api_flat.h, src/steam/steam_api_stub.cpp
Currently, this just shows the current map in the status. Might need
localization data in Steamworks to be available to work in languages
other than English.
CC #2642
=> Begin the groundwork to set a custom status on Steam

src/game/client/components/menus_settings.cpp
We don't have a way to query the default config value, except including the config_variables.h, do we?
=> Disabling 3.3 in settings tab should reset to version 3.0

src/game/editor/editor.cpp, src/game/editor/editor.h
```
Im 'corneumToday at 16:55
when i have a layer selected and rightclick on another one to change its properties, it doesnt switch to that layer. that hasnt always been this way and its throwing me off lately
especially because it still opens the menu for the other layer
```
=> Fix layers right click on item opens menu for previously selected (left clicked) item

src/game/client/components/nameplates.cpp, src/game/variables.h
Problem: when I play with a friend in team 0, and there are many players nearby, I cannot distinguish him due to nameplates overlapping. It's getting worse when they are in freeze.
Solution: Mark your teammate as "Friend" and setup "cl_nameplates_friendmark"
Result:
=> Add nameplates friend marks

src/engine/client/serverbrowser.cpp, src/game/client/components/menus_browser.cpp
The inconvenieces I discovered so far:
1. You got to write 999 to "disable" this filter
2. If you try to clear this field and then type 75 then the field will contain 750 because the last zero is bugged at this point
Those are fixed
What I would like to be fixed as well (not sure if I gona do this soon):
1. Update browser servers live without refreshing. You press refresh - you receives all the servers and then you should be able (but currently not) to filter them out without pressing on "Refresh" button again but just by changing the max ping value
=> allow empty max ping filter

src/engine/client/serverbrowser.cpp
Fixes all problems for #2620
Explanations of existed problems:
Lan has non expected servers because we were creating browser entry regardless token check
DDNet tab has ping 0 for servers as we weren`t rejecting previous refresh responses
=> Fix server responses handling in game browser

src/engine/client/text.cpp
Now that we have fallback fonts this makes sense.
=> Increase default font texture size

src/game/client/components/menus.cpp, src/game/client/components/menus_ingame.cpp
Deactivating menu while a popup is active causes the menu to never open again.
Reported by Anxton on discord.
=> Don't deactivate menu when a popup is active

src/game/client/components/camera.cpp, src/game/client/components/camera.h, src/game/client/components/maplayers.cpp
fixes #2766
Appearently the center of the camera can even go outside of the kill border(like even left from it)
I also notice that sometimes when zooming out, and then in again the zoom level gets negative(since the new smooth zoom)(atleast i see everything upside down for few frames)
These numerical unstableness makes me sweat a bit xd
=> Clamp kill border count

src/game/server/score.cpp
The slow query logs are full of this:
SET timestamp=1599419023;
LOCK TABLES record_teamrace WRITE, record_teamrace AS r WRITE;
Do we really need these lock? See also
https://dev.mysql.com/doc/refman/5.7/en/table-locking.html
> InnoDB tables use row-level locking so that multiple sessions and
> applications can read from and write to the same table simultaneously,
> without making each other wait or producing inconsistent results. For
> this storage engine, avoid using the LOCK TABLES statement, because it
> does not offer any extra protection, but instead reduces concurrency.
=> Don't lock SQL writes

src/base/system.c, src/base/system.h, src/engine/client/input.cpp, src/game/client/components/chat.cpp, src/game/client/components/menus.cpp, src/test/str.cpp
Currently this replaces `str_copy` text input and clipboard paste in chat. Many places may need the same treatments, like steam names.
Test string:
abcd今天是个好日子心想的事儿都能成今天是个好日子打开了家门咱迎春风今天是个好日子心想的事儿都能成今天是个好日子打开了家门咱迎春风今天是个好日子心想的事儿都能成今天是个好日子打
=> Add str_utf8_copy that trim broken utf8 sequence at the end.

src/game/editor/editor.cpp
As reported by Ravie on Discord. Tee is not drawn exactly in center.
=> Fix proof circle position in editor

src/game/client/gameclient.cpp
No reason to predict camera position in case when we just changed spectator.
But tbh I have not found a big reason to predict it at all.
=> Dont predict camera position on spectator changed

src/game/server/score.cpp
by ordering names in binary collation, consistent with C++ std::sort
Required since the official DDNet DB uses utf8mb4_general_ci default collation
=> Fix duplicate teamranks (fixes #2405)

src/game/client/components/menus_browser.cpp
Since DDNet has too many locations now. A scroll wheel would be even better for the future if someone wants to implement that.
=> Add some more space for Countries & Types

src/engine/client/client.cpp, src/engine/client/client.h
At the moment it only happens the next time you press refresh.
Before we had it so that it always reloaded once the ddnet info arrived,
causing a quick flickering and lots of packets having to be resent every
time someone pressed refresh, even if nothing changed.
The new approach combines the advantages of both without the
disadvantages. An even nicer way would be to compare the json objects,
so that news and version updates don't matter, but our json library
doesn't seem to support that.
=> Refresh server browser immediately when updated ddnet info arrived

.github/workflows/style.yml, scripts/fix_style.py
This allows the style checker to only look at the changes done in the
current branch, and not the other commits that were done in the base
branch.
=> Find the common ancestor for the style checking

src/engine/graphics.h
graphics.h:197:36: error: ‘uint8_t’ has not been declared
=> Fix compilation on MinGW Windows

src/engine/shared/websockets.cpp, src/engine/shared/websockets.h
In the last PR of websockets https://github.com/ddnet/ddnet/pull/2805 , It only support the websocket client in macOS and LinuxOS. And I add the Windows OS windows websockets client support in this PR.
It seem that netinet/in.h isn't used by websocket code so I remove it. After removed it I can successfully compile and run DDNet client and server in Linux too. If netinet/in.h have something usage I don't know, please tell me.
=> add windows websockets client support

src/game/client/components/menus.cpp
=> Make spacing in top menu buttons consistent, fit for 5:4

src/engine/client/client.cpp, src/engine/client/text.cpp, src/engine/textrender.h
Missing: Freeing the memory again. But not so important since we keep
the same fonts until end of process anyway in our case.
@QingGo Could you give this a try from the Github build artifacts? If not, I can provide you a nightly build.
=> Load fonts from memory (fixes #2810)

src/engine/client/graphics_threaded.cpp
Would be nicer, if the map loader would check the map for such things, but since the backend works with the image data and assumes its valid, this prevents crashes.
=> Don't allow zero/empty images(bcs malloc(0) and other things)

src/game/client/components/menus_ingame.cpp
Old: ![screenshot-20200917@090205](https://user-images.githubusercontent.com/2335377/93431529-882ab480-f8c4-11ea-8e56-dfe903a5ae06.png)
New: ![screenshot-20200917@090226](https://user-images.githubusercontent.com/2335377/93431538-8cef6880-f8c4-11ea-8946-449e7aa6dea7.png)
=> Fix spacing in kick-vote menu (center tees and text)

src/engine/shared/websockets.cpp
implement a simple version of inet_ntop by myself. I only check that it can work at MacOS. No way for me to check if it work at windows xp now.
=> fix websockets client link problem in xp

src/engine/client/serverbrowser.cpp, src/engine/shared/config_variables.h
As suggested by BannZay on Discord. We scale down when we notice that
no responses arrive. The idea is that player's internet has become
faster than when DDNet started, so increasing the default is ok.
=> Increase br_max_requests to 100

src/game/client/components/skins.cpp
Thanks alot to Spooky, with whom I painfully installed VS to find this crash.
Just use FindImpl on default, also added check if default exists, else return and abort the download.
To explain the crash:
e.g. Spooky used pinky as prefix:
it then tried pinky_x_spec, didnt found
it then tried pinky_default(bcs Find was used instead of FindImpl)
and then it always tried pinky_default, bcs the prefix was always added
=> Fix skin prefix search crash

src/game/client/components/menus_settings.cpp
fixes graphics bug when new skins are added, skins array is reallocated and we accessed freed memory
Thanks to Jupeyy & Learath2 for also looking into this
Screenshot of the bug for reference, reproduced by removing all skins in data/skins, opening skin menu, joining a full server and waiting a bit:
=> Reload skin menu when skin count changed

src/game/client/components/mapimages.cpp, src/game/client/components/mapimages.h
Fixes switch tile for unmasked ddnet
And ddnet mods send that they are a race and ddrace mod appearently?
Not very intuitive that ddnet is a superset of them, bcs tiles changed.
Waiting for a review from @fokkonaut
=> Add unmasked entities for all mods

src/game/editor/popups.cpp
before, `m_SoundEnvOffset` was always set to the same value as `m_PosEnvOffset`, due to wrong behavior in the ui.
=> properly set sound envelope offsets for sound sources

src/game/server/gamecontext.cpp
=> bugfix: laser_damage was removed from tunes of 0.7 protocol

src/engine/client/client.cpp
when reconnecting after server was full:
[2020-09-25 15:39:34][client]: offline error='This server is full'
Source and destination overlap in strncpy(0xd3328e2, 0xd3328e2, 255)
at 0x483DFDC: strncpy (vg_replace_strmem.c:550)
by 0x249180: str_copy (system.c:2328)
by 0x27E1F5: CClient::Connect(char const*, char const*) (client.cpp:707)
by 0x287864: CClient::Update() (client.cpp:2914)
by 0x28891B: CClient::Run() (client.cpp:3216)
by 0x28EDEC: main (client.cpp:4309)
=> Don't str_copy into string itself

src/game/client/gameclient.cpp
Since some users on Windows report window not being initially focussed. Reincarnation of https://github.com/ddnet/ddnet/pull/2897 but not for OSX
I think this doesn't hurt.
=> After initialization: Agressively try to grab window again

src/engine/server/server.cpp
The buffer size passed to `str_append` includes the null terminator.
=> Fix cutting of one character when showing ips in rcon

src/engine/server/server.cpp
Mistake was introduced in 7c31a15c93b34bd0557039ded65ea9456a72e33b
We didn't notice since official servers are SQL, except Block servers, and we just started moderating them a bit.
=> Fix show_ips on non-SQL servers

src/game/editor/editor.cpp
If a group is already selected, shift clicking the group didn't select the first layer.
Reported by mind on discord
=> Fix multiple layer selection for groups

src/game/editor/io.cpp
Note that the zlib compression still makes it non-deterministic across different machines/versions
=> initialize physics layer pointer, layer item version (partially fixes #2971)

src/engine/client/graphics_threaded.cpp, src/tools/dilate.cpp, src/tools/map_convert_07.cpp, src/tools/map_replace_image.cpp
and print a more telling error message
I'll check all our existing maps for failures now:
```
$ find . -iname '*.map' | while read i; do echo $i; map_extract $i > /dev/null; find . -iname '*.png' | while read j; do dilate $j; rm -- $j; done; done
```
For skins Soreu and the skin DB team is already taking care. (but I checked and the ones in Skin DB now can all be loaded without error)
=> Handle PNG read errors (fixes #2959)

src/game/client/components/menus_demo.cpp
to easily get the file instead of having to search for it in the file browser again. Complements #2946
=> Show File button in demo player

src/engine/shared/storage.cpp
@Learath2 Could you check if this can be extended to also find the DDNet-Server executable on Mac?
=> Determine binary dir independently of data dir (fixes #2891)

src/game/client/components/maplayers.cpp
time_get_microseconds() can potentially return big numbers (on my system it seems to be equal to uptime) and at some point float's precision is no longer enough for every 1/60th of a second.
I'm replacing it with LocalTime() - it's also available in the menu and it's counted from the start of the game.
I've tested menu and in-game animations.
=> Make menu background animations smoother

src/game/client/components/menus_settings.cpp
Can't tell if setting the hot item in gui invalidly can potentially break stuff, also a skin refresh button would make this useless anyway
=> Use skin pointer directly

src/game/client/components/menus_demo.cpp
As reported by Soreu, doesn't work on Windows (Can't open file warning
pops up)
This reverts commit 8efff70d884b819a1a8d1c8a445d56c9ce2d1f5e.
=> Revert "Show File button in demo player"

src/game/client/components/maplayers.cpp, src/game/client/components/maplayers.h, src/game/client/components/mapsounds.cpp, src/game/client/render.h, src/game/client/render_map.cpp, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/layer_sounds.cpp
fixes what is described in #2997
Old client animation when server time is huge:
[vid_old.zip](https://github.com/ddnet/ddnet/files/5322484/vid_old.zip)
client animation when server time is huge:
[vid_new.zip](https://github.com/ddnet/ddnet/files/5322486/vid_new.zip)
@Fireball-Teeworlds maybe u can try, if that fixes the stuff for u
=> Make animations more consistent with high float values

src/game/client/prediction/entities/laser.cpp
Correct me, if this is wrong, but only ddrace based mods cannot shot laser through itself.
Tested on vanilla, ictf and fng(with antiping on and prediction on)
=> Fix laser prediction for non ddrace mods

src/game/editor/io.cpp
If I'm not mistaken, loading a map without auto mappers, then saving would've caused uninitialized values to be written to the auto mappers of physics layers.
=> only load + save auto mappers for tile layers, not physics layers

src/game/client/components/menus_browser.cpp
or we end up with totally broken input boxes
As reported by Rezee:
=> Don't make width depend on localized text

src/engine/client/backend_sdl.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/sound.cpp, src/engine/client/text.cpp, src/engine/shared/dilate.cpp, src/game/client/components/flow.cpp, src/game/client/components/maplayers.cpp, src/game/collision.cpp, src/game/editor/io.cpp, src/game/editor/layer_tiles.cpp, src/game/server/ddracechat.cpp, src/game/server/entities/character.cpp, src/game/server/player.cpp, src/game/server/score.cpp, src/tools/dilate.cpp, src/tools/map_convert_07.cpp, src/tools/map_replace_image.cpp
> Multiplication result converted to larger type
> A multiplication result that is converted to a larger type can be a
> sign that the result can overflow the type converted from.
Example: https://github.com/ddnet/ddnet/security/code-scanning/17?query=ref%3Arefs%2Fheads%2Fmaster
=> Fix all Multiplication type alerts by CodeQL

src/game/client/components/players.cpp
Sometimes ppl become afk while they are chatting, which is cause fail especially on t0 maps.
=> Render afk emote instead of chat emote

src/game/client/components/menus.cpp
hopefully. For me "Show chat" didn't work, works now. For Дядя Женя
"Use sounds" was flickering, but can't reproduce
=> Fix button rendering in "Render demo"

src/game/client/components/menus_demo.cpp
Just to not rely on uninitialized values
=> Init date for demo dirs

src/engine/client/client.cpp
This reverts commit a6d2a35e11d6fa6e222b9d57ce2841e43066a766.
It's unclear how this should have fixed the mentioned bug.
=> Revert "Reset m_ServerCapabilities on Disconnect"

src/game/client/components/effects.cpp
the render info color is created the same way, just that it is allowed to be overritten for team colors
see OnNewSnapshot
and UpdateRenderInfo
=> Use renderinfo for player death effect

src/game/client/components/spectator.cpp
Old:
New:
Very small visual change but heart fits better now for >32 players.
=> Add box offset to align better on spec tab

cmake/FindSQLite3.cmake
For @panos' Haiku port: https://github.com/panos/ddnet
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> /boot/home/ddnet/SQLite3_INCLUDEDIR
@heinrich5991 thoughts?
=> Try to fix FindSQLite3.cmake

src/game/client/components/menus_settings.cpp
Old:
New:
Thanks to HamidReza for report
=> Make clan plates fit & only show when name plates enabled

src/game/client/components/hud.cpp
Fixes problem with too long strings because we display the score centered
Thanks to ExP for report:
Fixed:
=> Recreate score hud when any score changed

src/engine/client/graphics_threaded.h
This fixes #3084, seems to be enough to make all the data fit in the buffer again.
=> Don't waste bytes when we are already aligned

src/engine/client/serverbrowser.cpp
The only leaks reported by ASan that are allocated by us. There is one other by SDL and one by X11.
=> Fix 2 leaks in CServerBrowser

src/engine/shared/snapshot.cpp, src/engine/shared/snapshot.h
Same as https://github.com/teeworlds/teeworlds/commit/293209e7227c81e92b99c89890ebfdc264374a4a + https://github.com/teeworlds/teeworlds/pull/2684/commits/c87a7b438f08f83385f4e21d1c23a498a6fb4c55 in 0.7
=> Fix out of bounds access in snapshot delta handling

src/engine/client/backend_sdl.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/game/client/components/maplayers.cpp
Huge maps like back in time 2, will always "only" upload 2MB of data at once, and then wait for the graphics thread to finish building/copying the VRAM, this might increase performance a bit
=> Use pointer directly for tile layer building

src/game/client/components/menu_background.cpp
E.g. popups like "ddnet-info.json" failed will cause weird NaN glitches, bcs the impl relys on ChangePosition to clean movetime and animation start
=> Fix offline client that is not in menu

src/game/client/components/nameplates.cpp
Removes the unnecessary `SnapFindItem` (which is a linear search, ew)
=> Optimize nameplate rendering. Fix #3103

src/game/editor/editor.cpp
Not one ddnet map has a external map sound since there are none which would work that way
=> Embed map sounds by default

cmake/FindGLEW.cmake
This should fix the warnings when linking to glew on windows
=> Also compile glew.c with GLEW_STATIC

cmake/FindSQLite3.cmake
It only required fixing one weird CMake 2.8 oddity.
I guess we should merge this if we are keeping to claim 2.8 support.
=> Get CMake 2.8 working

src/game/client/components/mapimages.cpp
We dont need to `close` #3146
i think setting it to 0 makes no sense anyway the config to disable entities text is `cl_text_entities` not this one
=> Clamp font size to atleast 2 (fixes #3145)

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/game/client/components/camera.h, src/game/client/components/controls.h, src/game/client/components/hud.h, src/game/client/gameclient.h
Should make code more readable by explaining that the array is used for dummy. Also makes modders life easier if there is a need to scale up dummy count.
I left out two places that do not include client.h
https://github.com/ddnet/ddnet/blob/3be8a592e52a03e555b6aa29a8dea529797bb645/src/game/client/prediction/gameworld.h#L92
https://github.com/ddnet/ddnet/blob/3be8a592e52a03e555b6aa29a8dea529797bb645/src/game/gamecore.h#L212
Moving the enum to protocol.h for example is probably not nice.
=> Use NUM_DUMMYS for dummy array length

src/engine/client/backend_sdl.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/engine/shared/config_variables.h, src/game/client/render_map.cpp
fixes #3097
I added a TrianglesBeing/End() instead for ingame quads
Let me quickly explain why #177 failed.
In the screenshots of #177 you already see the problem
the driver can built a quad like:
or like:
or somehow it wants, but it will always do them as triangles
And thats why the ingame quads were basically flipped in the screenshots of #177
But this almost never matters.
Tiles are single colored, text is single colored, ui elements are single colored.
So it only matters for ingame quads probably, which specify the color of each edge
Also even if it would matter, we can simply change the quads to triangles now.
Pro:
- Generally less vertices upload
- Less vertices building on CPU side
Cons:
- nothing
=> Make gfx_quad_as_triangle 0 default

src/game/client/components/killmessages.cpp
As far as i can see this was only a problem in demo recorder, which activly seeks snapshots and does Tick() calls during the rendering
=> Killmessages should reset screen

src/engine/shared/config_variables.h, src/game/client/components/menus_settings.cpp
Makes it a bit easier to find, prefer it on a busy server. Also clarified the friend message toggle is for highlighting only.
=> Show option to disable system messages in settings

src/engine/client/backend_sdl.cpp
~Possibly `fixes` #3104~
Ravie can you test? 
Does not fix the issue.
[only affects gl 3.3]
Still is required, bcs that looks wrong
=> Fix texture create with multi units

src/engine/client/input.cpp, src/engine/client/input.h, src/engine/input.h, src/game/client/components/chat.cpp, src/game/client/components/console.cpp, src/game/client/components/menus.cpp, src/game/client/lineinput.cpp, src/game/client/lineinput.h
IME state fix closes #3185 and closes #3150 
DoEditBox update closes #3186, now cursor behave the same as chat where only one cursor (either the real one or the editing one) will be shown.
=> Fix IME state softlock under fcitx and macos + Update DoEditBox logic to be the same as chat

src/base/system.c
Taken from https://en.wikipedia.org/wiki/Whitespace_character#Non-space_blanks
Had to Hangul Jungseong Filler to that Wiki article as it was missing.
=> Add non-space blanks: Hangul Filler characters

src/game/client/components/menus.cpp, src/game/editor/editor.cpp
I think they create to much issues with the cursor
changed the thing in menus and editor, dunno if there are more editbox impl somewhere
=> Disable text alignment for editboxes

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/io.cpp
Right now it is impossible to have a working external sound. External
sounds render unusable the moment the map is saved and given to another
player. For the mapper it seems like everything is working since the
mapper has the sound file. For anyone else it simply won't work. Since
1. there is no use for it and
2. it adds unnecessary complexity and confusion, 
I propose removing it entirely.
None of the ddnet maps use external sounds, only 25 maps from the map archive have external sounds
Please have a look over the changed ui code.
=> Remove option to make map sounds external

src/game/client/components/chat.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/race_demo.cpp, src/game/editor/editor.cpp
=> Use str_truncate more often

src/tools/map_convert_07.cpp
Broken in https://github.com/ddnet/ddnet/commit/5c1b8cd2215275a95e8ce6bacc45c31b6c7a4c17#diff-17a71d0838a3f107d2baf573a0885c3b7727266b432a13836525737e83a81a58
Thanks to Jupstar for noticing
=> Fix map_convert_07

src/game/client/render.cpp
I don't know if it's ok to make 2 line changes PRs, but this one would make new method's values (added some days ago with Chat Visuals update) `CRenderTools::DrawRoundRectExt` easier to understand and safer for out of bounds exception.
=> DrawRoundRectEx easier for understanding, out of bounds safer

src/tools/map_convert_07.cpp
DDNet doesn't CMapItemTypeImage version 2, meaning it doesn't have
support yet for having rgb images in maps. Currently, trying that would result in
invalid map files.
=> 0.7 map converter - Stop embedding rgb images

src/engine/client/text.cpp
fixes #3205 in a bad way
looks ugly i know, i don't know a better solution rn. We are just hitting limitations of the impl
=> Always render line, if we already are on a new line

src/engine/client/text.cpp, src/engine/textrender.h, src/game/client/components/chat.cpp, src/game/client/components/chat.h
Very round:
bit round:
No rounding left:
No rounding at all:
old chat:
Just gave some examples so its easier to see what is nice
=> Some chat fixes

src/game/client/components/menus_ingame.cpp
I find "Call Vote" menu useless af right now, because it's simply impossible to read it. So when you want to call vote for a map you open website and find the one you want, after that making /map skipping the "Call Vote" menu completely. It's useful for calling for random map btw, but anyway too ugly to look at.
**OLD LOOK**
**NEW LOOK**
**NEW LOOK (RconAuted)**
Changed nothing, but row and text size + View rect size, because for some reason it was small for preserving space for RCON Auted users. Why?
Also changed the name of rect "Extended" to "RconExtension" to make it more clear what is it for.
Would be cool also to remove all that junk that is not actual votes from DDNet server vote list (finishers, average time) and merge it into one line with map's name.
=> Much more readable Call Vote menu and code

src/game/client/components/chat.cpp, src/game/client/components/chat.h
Fixes: https://github.com/ddnet/ddnet/issues/3215
Disables chat rendering completely if scoreboard is active. Too many issues with chat resizing when scoreboard was active, don't think it is so important to have cropped little box of chat with scoreboard at the same time for such cost.
Also fixed tee icon position in chat, because right now it was like on the below message.
**OLD**
**NEW**
=> Disable chat rendering when Scoreboard is active and fix tee icon pos [Fixes #3215]

src/game/server/player.cpp
People are clearly unhappy with this event, so let's revert it. On
servers I've set events 0 already.
This reverts commit ae90bdf3f9cf522b0fca5f3b690a624d319f04cf.
=> Revert "Show halloween skins only on Halloween"

src/game/client/components/chat.cpp, src/game/client/components/chat.h
with scoreboard:
without scoreboard still same:
=> Revert 75987a26cf2eec415f3fba0607e755a42ef85eab and don't align for scoreboard

src/game/client/components/binds.cpp
Just fixes https://github.com/ddnet/ddnet/issues/3182
Works as it used to work, but does not call for binds with no modifier when the same key was used already for modified bind
=> Fix overlapping of combined binds with modifiers [Fixes #3182]

src/game/editor/layer_sounds.cpp
If you append a map to another, all indices of it must be offset. This doesn't happen with the position envelope index of sound sources, meaning it would (if the original maps had at least one envelope) point to the wrong envelope.
=> Add m_PosEnv (of sound sources) as index that must be offset when appending a map

src/game/client/components/skins.cpp, src/game/client/components/skins.h
Beside that this was wrong anyway, i hoped i could atleast get the index from the sorted list insert, but that returns the last index in the list, instead of the new inserted index(just like rn), so just revert what I added in 8d6148b20b2cde94d8e1fbe0a0dcd0bd81e86acc
=> Fix skin index

src/game/client/components/debughud.cpp, src/game/client/components/debughud.h
Added a line at the bottom of the screen when cl_debug is 1
=> Added a Hint for Disabling Debug Mode

src/engine/client/text.cpp
=> Fix clang-tidy in text.cpp

src/game/server/ddracecommands.cpp
=> Kick-voting someone from team doesn't kill locked team (fixes #3207)

src/game/server/entities/dragger.cpp
How did this not blow up all day long for years?!
Found by UBSAN:
/home/teeworlds/src/master/src/game/server/entities/dragger.cpp:32:29: runtime error: member call on address 0x0000013319b8 which does not point to an object of type 'CCharacter'
0x0000013319b8: note: object has invalid vptr
00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
^~~~~~~~~~~~~~~~~~~~~~~
invalid vptr
#0 0x5501de in CDragger::Move() /home/teeworlds/src/master/src/game/server/entities/dragger.cpp:32:29
#1 0x5522c2 in CDragger::Tick() /home/teeworlds/src/master/src/game/server/entities/dragger.cpp:153:3
#2 0x5eb11e in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:261:11
#3 0x58d660 in CGameContext::OnTick() …
=> Initialize pointer in dragger

src/game/client/components/scoreboard.cpp, src/game/client/components/scoreboard.h
=> Scoreboard same line height and font size for each team (fixes #3216)

src/game/client/components/menus.cpp
=> "Connect to" popup: Don't disconnect on enter (fixes #3259)

src/game/client/components/scoreboard.cpp
Broken in https://github.com/ddnet/ddnet/pull/3251
Thanks to louis for report
=> Fix scoreboard on ddnet server

src/game/server/gamecontroller.cpp
As discovered by ASAN:
```
/home/teeworlds/src/master/src/game/server/gamecontroller.cpp:142:3: runtime error: index 65 out of bounds for type 'vec2 [64]'
#0 0x5de082 in IGameController::OnEntity(int, vector2_base<float>, int, int, int) /home/teeworlds/src/master/src/game/server/gamecontroller.cpp:142:3
#1 0x5c9f43 in CGameContext::OnInit() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:3291:20
#2 0x4ae3aa in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2473:20
#3 0x4c265d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3551:21
#4 0x7f400fedc09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
#5 0x451509 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x451509)
```
=> Don't access m_aaSpawnPoints out of bounds

src/engine/shared/config_variables.h, src/game/client/components/chat.cpp, src/game/client/components/menus_settings.cpp
=> cl_chat_tee + cl_chat_background => cl_chat_old (fixes #3106)

src/engine/client/text.cpp, src/game/editor/editor.cpp, src/game/editor/editor.h
Thanks to PopCorn181 for report
=> Fix ScaleFontSize with too long strings

src/game/client/components/menus_browser.cpp
Must be a 1 instead of -1, caused at 74515d4b959b5f0062440d813652b3059004d90c
=> Fix browser wrong alignment

src/game/server/gamecontroller.cpp
m_aNumSpawnPoints wasn't increased causing no spawn points to be loaded at all.
Also the maximum value it can have should be 64, not 64 - 1, bcs it's the upper limit, not the index.
=> Fix spawnpoints calculation

src/game/client/gameclient.cpp, src/game/gamecore.cpp
I believe this fixes #3043 and #2510, but I haven't tested it extensively yet (and I couldn't reproduce the bug for no-collision tiles)
Perhaps there should also be some further cleanups of the code, to avoid double bookkeeping of whether a character can collide/hook/hit others, as this easily leads to problems. For example: m_Hook/m_NoHookHit in CCharacterCore, m_Hit in CCharacter vs NoHammerHit (etc), and also fake tunings that in some cases are no longer required for ddnet clients.
=> Fix prediction of no hook/collision tile

src/game/client/components/chat.cpp, src/game/client/components/chat.h, src/game/client/components/ghost.cpp, src/game/client/components/killmessages.cpp, src/game/client/components/killmessages.h, src/game/client/components/menus_settings.cpp, src/game/client/components/players.cpp, src/game/client/components/skins.cpp, src/game/client/gameclient.cpp, src/game/client/render.cpp, src/game/client/render.h, src/game/client/skin.h
Finally i had time for this.
This addresses the problem with skin sizes( yes @Banana090 I care for you :* )
Finally a way to calculate skin sizes correctly:
**new**
old:
Maybe more obvious(left new, right old):
So we can center skins always.
Currently I only applied this to chat, but it should be used everywhere, where a skin is rendered(except the actual game skin)
- Scoreboard
- Skin selection
- and so on
@def- i'd really like to get this into this next release, because I know ppl with smaller skins will complain about the offset.
I'll test it a bit tomorrow, maybe others can test it too already.
=> Add skin metrics

src/engine/server/server.cpp
=> Fix invalid server-assigned utf8 names with (1) prefix (fixes #3269)

src/game/client/components/menus_browser.cpp
Fixes the wrong text calculation for playercount, ping, etc. as reported in #bugs on discord
=> Fix server browser columns

data/shader/prim.frag, data/shader/prim.vert, data/shader/primex.vert, data/shader/spritemulti.frag, data/shader/spritemulti.vert, data/shader/text.frag, data/shader/text.vert, src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h, src/engine/client/opengl_sl_program.h
Small refactoring for GL 3.3+ shaders.
Removes "if" checks where unneeded or CPU can calculate the result faster.
Also renames some uniforms to be consistent within all shaders.
=> Some shader refactoring

src/engine/server/databases/sqlite.cpp
=> Fix updating points on SQLite3 backend

src/game/client/components/skins.cpp, src/game/client/render.cpp, src/game/client/skin.h
beast.png has no body at all,
so for this skin we need to calculate the metrics with the outline.
Sadly comes with more overheat ofc
old:
new:
=> Respect outline in skin metrics

src/game/client/components/debughud.cpp
Since character doesn't exist then. Reported by murpi
Originally introduced in https://github.com/ddnet/ddnet/pull/2578
=> Don't crash with debug mode in demo

src/engine/server/server.cpp, src/engine/server/server.h
```
Direct leak of 566869 byte(s) in 1 object(s) allocated from:
#0 0x4f28e3 in __interceptor_malloc (/home/teeworlds/servers/DDNet-Server-asan+0x4f28e3)
#1 0x55b3c9 in CServer::LoadMap(char const*) /home/teeworlds/src/master/src/engine/server/server.cpp:2312:49
#2 0x55bfdd in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2351:6
#3 0x56add2 in main /home/teeworlds/src/master/src/engine/server/server.cpp:3553:21
#4 0x7f54401cd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
```
=> Fix memleak in CServer on instant shutdown

.gitignore
Before it was annoying to download sources and get stupid CMake errors about it.
=> Disallow to ignore src/mastersrv and src/twping

src/game/client/components/statboard.cpp
x coordinate advancing was missing for the "frags"
=> Fix statboard rendering

src/game/client/components/menus.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/editor/editor.cpp
Fix freezing with DoEditBox
Pretty small patch but seems to be working
Also removed the linewidth limit in DoEditBox to avoid multiline
fixes #3256
=> DoEditBox clamp cursor position

src/game/server/gamecontext.cpp
Caused by the hotfix for solo cheat
As reported by maggi323
=> Fix random map vote reason to set stars

src/base/system.c, src/base/system.h, src/engine/shared/network_conn.cpp
=> Allow utf8 ban reasons (fixes #3329)

src/game/server/entities/character.cpp
Required for map Taceht because of weapon tele interaction with jetpack
As requested by Cøke
=> Disable ninja jetpack when player has telegun

src/game/client/components/menus_demo.cpp
Multiple assets would be highlighted
Thanks to @Jupeyy for finding it
Bug introduced in https://github.com/ddnet/ddnet/pull/3304
=> Fix assets menu

src/engine/client/client.cpp, src/engine/client/client.h
More platform-independent than using libframetime: https://github.com/clbr/libframetime
Uses the same output format.
Made some commands use rest instead of string so you don't need quotes for the parameter.
=> Add benchmark command for pts

CMakeLists.txt, src/engine/shared/datafile.cpp, src/engine/shared/datafile.h, src/engine/shared/image_manipulation.cpp, src/engine/shared/image_manipulation.h, src/tools/map_optimize.cpp
Wrote a map optimizer(very aggressive, explain later why).
It reduces map sizes by ~40% (optimized the whole ddnet-maps repo and it was around 40% smaller afterwards)
Test and idea by mind, credits to him
What it does, and why I called it aggressive:
- It removes all unused tiles from embedded images
- It clears transparent pixels and dilates them as 2D array textures, instead of simple 2D textures.
- It uses zlibs best compression
So yeah, it changes the output map(keeps the source file working, output is in "out" dir), its not the same as before, it's a nice tool for optimizing size with a lot of embedded images as a final release, or when using higher resolution textures.
=> Map optimizer

src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/game/client/components/countryflags.cpp, src/game/client/components/mapimages.cpp, src/game/client/components/menu_background.cpp, src/game/client/components/menus.cpp, src/game/client/components/menus_settings_assets.cpp, src/game/client/components/skins.cpp, src/game/client/gameclient.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/editor/editor.cpp
This time tested with valgrind to find uninitialized memory(the one i found isnt critical)
=> Fix leaks, initialize everything in UI Element Rect

src/game/server/entities/character.cpp
Tested it now, and it seems that only the hook and collision off tiles were affected by this.
=> Fix prediction with global collision off tiles and tunings (fix #2510)

README.md
`brew cask install ddnet` is depreciated.
=> Update brew command

src/base/vmath.h, src/game/client/components/items.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/players.cpp, src/game/client/prediction/entities/character.cpp, src/game/server/entities/character.cpp, src/game/server/entities/laser.cpp, src/game/server/entities/projectile.cpp
Interestingly besides it found unused variables, this also found some "logic" errors, where vectors were used in `if`.
=> Fix vec_base constructors & remove useless operator

src/base/tl/threading.h, src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/engine/server/databases/connection_pool.cpp, src/engine/server/databases/connection_pool.h, src/engine/server/databases/mysql.cpp, src/engine/server/databases/mysql.h
Changed these old classes names to match our current standards.
=> Rename lock and semaphore classes to match current naming

src/engine/client/blocklist_driver.cpp
As reported by louis, who tested different drivers, since he still has the other bug: ALT + TAB makes the screen go black for 5seconds
=> Increase Intel driver blocklist range

src/game/server/teams.h
Resulting to race condition, since the main thread always thought that the
load/save thread already completed. Passing the shared_ptr by reference to
prevent a similar future bug to happen.
Fixes #3380
=> Fix storing load/save result in main thread without incrementing usage count

src/engine/server/databases/connection_pool.cpp, src/engine/server/databases/connection_pool.h, src/game/server/gamecontext.cpp, src/game/server/gamemodes/DDRace.cpp, src/game/server/player.cpp, src/game/server/score.cpp, src/game/server/score.h, src/game/server/teams.cpp
All database results are now derived from ISqlResult, to store the synchronization variable there. All accesses to results were changed in score.cpp (`s/pData->m_pResult/pResult/g`) causing a rather big diff. This was necessary, since the database worker has to access the result for each query to notify when a query is complete.
Fixes #3380
=> Synchronize database thread via atomic_bool instead of use_count from shared pointer

CMakeLists.txt
Add `-rdynamic` if supported by the linker.
Not all symbols being exported broke our builds recently, the antibot
library used `mem_comp` from the main binary but it wasn't exported,
leading to the following runtime error:
```
./DDRace64-Server_sql: symbol lookup error: /home/teeworlds/servers/libantibot.so: undefined symbol: mem_comp
```
=> Export all symbols from the main executable for the antibot

src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/client/input.cpp, src/engine/graphics.h, src/game/client/components/menus_settings.cpp
I actually wanted to fix the grabbing issue on Windows, but sadly couldn't fix it, while trying to fix it, i fixed the resizing stuff tho(tested with a vm on win10 and win7), also gfx_resizable 1 should be fine now with KDE too(couldn't reproduce that blackscreen bug anymore)
Tho I also want to share some things about the grabbing thing, maybe someone is interested in improving it:
I found out that disabling the console on windows and creating the window as fast as possible reduces the grabbing issues.
Even better was making the windows always on top so SDL doesn't call the grab when our window looses focus, while the IO stuff is blocking.
The code is really random but here are the things i tried(https://github.com/Jupeyy/ddnet/commit/c881720137ecdba7d766c8affef755c54a9b08ff)
=> Allow resizing on Windows too

src/game/editor/editor.cpp
=> Allow reordering in the settings editor

src/engine/client/graphics_threaded.cpp, src/engine/client/http.cpp, src/engine/client/http.h, src/game/client/components/skins.cpp, src/game/client/components/skins.h
Sorry for the trouble, seems to work.
=> Move PNG loading in SkinDL to fetch thread (fixes #3398)

src/engine/client/input.cpp
Extremely annoying bug fixed when you alt+tab from the game in SPEC mode, then open game window again and your screen was teleporting to somewhere nearby your position.
(https://cdn.discordapp.com/attachments/293493549758939136/789480934592217108/freecam-bug.gif)
Eventually fixes some other issues with relative mouse mode.
=> Fixed mouse jumping after losing focus

src/engine/server/server.cpp
Introduced in https://github.com/ddnet/ddnet/pull/3095/files?w=1
=> Don't print name change message when trying to change to banned name

src/game/server/entities/dragger.cpp
Still doesn't seem to work with different team and /showothers 1, but
maybe that has always been the case
=> Fix dragger being shown (fixes #3414)

src/game/server/gamecontext.cpp
=> Remove redundant check for pPlayer->m_IsReady

src/game/client/components/camera.cpp, src/game/variables.h
E.g. on current tournament map its really annoying to not see the whole map at once to get a feeling for the map size
=> Remove hardcoded zoom level

src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser.h, src/engine/serverbrowser.h
Don't sort the whole server browser everytime an entry is added, instead only sort it once per Update call.
I hope this will help a bit with wrong Ping display, bcs of the br_max_request thing.
However, it won't fix it completly, since new request will still alter its correctness
for testing: br_max_request 500 makes the effect more visible, then its highly noticable
=> Don't sort on entry adding

src/game/server/gamecontext.cpp
=> Only assign aOldName when we need it

src/engine/shared/demo.cpp, src/game/editor/io.cpp
Has a short diff to the original code before a4f13ed4a85a4a2b.
Supersedes #3353. Thanks for the idea, @timakro.
=> Alternative alternative fix for malloc of size 0

src/game/client/components/chat.cpp, src/game/client/components/chat.h
Probs we forgot it when we swapped from two configs to one
=> Replace unused chains in chat

src/game/client/components/particles.cpp, src/game/client/components/particles.h
Helps with maps like "The Dream"
view without whitespaces
=> Only render visible particles

src/game/server/save.cpp
Should fix #3144 again. Better name for the nonexistent game uuid appreciated, but would be fine the current one.
=> Fix use of uninitialized variable during /load of old saves

src/engine/client/backend_sdl.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/game/client/components/maplayers.cpp, src/game/client/render_map.cpp
@def- i mean u could test the fps diff, its quite huge
and if u really only have 50fps, others will only have 30fps xd
=> Don't render fully transparent quads

src/game/client/components/particles.cpp
Particle's achsis aligned bounding box can increase in size if the particle is rotating.
Even if the particle images are all "pretty" round and so it wouldn't matter for default particles,
its not correct and with a custom image it could break.
following #3441
Basically this:
=> Respect possible particle size increase, of worst case rotation

src/game/server/player.cpp
=> Fix server crash with too many items (fixes #3477)

src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp
Horizontal sliders stays the same
**THESE FIXES ARE TEMPORARY**
PR contains some shitty hotfixes which I'm planning to rework later. The reason of them being shitty is that the source code for it was shitty already, simple as it is. The whole list idea should be reworked in order to make the code more clearer and nicer. Will do later. Also I'm planning to make much better mouse scrolling for lists, not the crappy "teleporting" thing we have right now, so anyway I will back to the lists later.
Basically, I'm reworking all the UI tabs one by one.
Now I am making the new "Tee" tab, which will combine "Player" and "Tee" setting tabs in one. As well as include improved skin selector with much more clear view on skins and so on... And I need this list update for it.
"Tee" tab update turns out …
=> Better Sliders(V) / Lists

src/base/system.c, src/test/str.cpp
=> Fix centisecs rounding in str_time_float

src/game/client/components/scoreboard.cpp, src/game/editor/editor.cpp
=> Dynamically size scoreboard title

src/game/client/components/nameplates.cpp
off by default, cl_nameplates_strong 1 to enable
also shown in debug mode (ctrl-shift-d)
=> Indicate strength of hook in nameplates

src/game/server/teams.cpp
As reported by Polector on Discord
=> Reset practice after team saved and got killed

src/game/server/teams.cpp, src/game/server/teams.h
This function was never used and just disrupts the reading flow a bit.
=> Remove unused onChangeTeamState

src/game/client/components/controls.cpp
=> Freeview mouse moves faster when zoomed out (fixes #3459)

src/game/client/components/hud.cpp
Some maps kill you quickly and you can't see how good your last run was,
for example "Buckle Up".
=> Keep showing last checkpoint after kill

src/game/client/components/nameplates.cpp
=> Differentiate hook number by showing symbol

src/engine/server/databases/sqlite.cpp
https://www.sqlite.org/c3ref/expanded_sql.html
Fixes #3381
=> Fix memory leak in SQLite3 print statement

src/engine/client/client.cpp
Maybe this fixes https://github.com/ddnet/ddnet/issues/3508 ?
Hard to test things involving timeouts tho...
=> remove ddnet info tmp file always when quitting

src/engine/client/client.cpp
Noticed after #3505, thanks @fokkonaut.
=> Send the NETMSG_ITIS/NETMSG_IDONTKNOW from the correct connection

src/engine/server/server.cpp
Only send the logout packet if you're actually logged in.
Fixes #3490. Supersedes #3495.
=> Send logout packet after using timeout protection

src/base/system.c
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow
> Displays a window in its most recent size and position. This value is
> similar to SW_SHOWNORMAL, except that the window is not activated.
=> Run server in background on Windows (fixes #3525)

src/engine/client/http.cpp
by making libcurl handle the signal itself
See https://curl.se/libcurl/c/CURLOPT_NOSIGNAL.html
=> Prevent OpenSSL SIGPIPE (fixes #3513)

CMakeLists.txt, src/engine/shared/uuid_manager.cpp, src/engine/shared/uuid_manager.h, src/game/server/score.cpp, src/test/uuid.cpp
Previously, a save could possibly be loaded twice given enough latency
discrepancy between servers. The server only verified that it deleted
*some* save with the given password, not *the* save it is trying to
load. This is fixed by also checking the SaveID column that is random
and globally unique (except for the old NULLs). Since users can't create
new saves with NULL SaveID, these pose no problem.
Also change the default UUID for saves without save ID to something
nonzero, so we can't accidentally hit it due to a bug.
=> Fix a possible race in load code 

src/game/server/save.cpp, src/game/server/save.h, src/game/server/teams.cpp
Message is displayed when saving with an active hook
=> Inform player about possibility to keep the hook when loading

src/game/client/components/camera.cpp, src/game/client/components/camera.h
Allows to bind spectator camera positions. Can be used to write teleport binds for test server or quickly spectate specific spots of the map.
=> Add set_view camera position command

src/game/variables.h
Since our maps2.ddnet.tw doesn't work well for players in China
=> HTTP Map Download: Time out faster

src/engine/shared/config_variables.h
=> sv_reserved_slots: allow up to 64

src/game/server/entities/character.cpp
This reverts commit 28cf3b31bab7df4c94e9e7d8e53973dd62de7e5a.
=> Revert "rescue on freeze/dfreeze"

src/game/server/gamecontext.cpp, src/game/server/teehistorian.cpp
Previously the message was recorded when incoming. But the time when the input should apply wasn't recorded. Now inputs are recorded right before they get applied in the game world.
And record exact tick where load/save result is returned.
=> Fix input message position in teehistorian files

src/game/client/components/menus_settings.cpp
=> Fix sizing in graphics menu

src/game/server/player.cpp
Caused by a logic error in a comparison, comparing a client ID with a
DDNet version.
Fixes #3578.
=> Fix /pause not working

src/game/client/components/menus.cpp
fixes #3575 (edit: else issue is probably not closed -- Jupeyy)
=> Fix button presses after esc after color picker usage (fixes# 3575)

license.txt
Currently it sounds like its missing a license for "All content", because "The other fonts" should have been "The other files".
=> Fix license

datasrc/network.py, src/game/client/components/hud.cpp, src/game/client/components/scoreboard.cpp
Fix #3599.
(Forgot to check for both NETMSG_RECORD and NETMSG_RECORDLEGACY in one
place.)
=> Fix top time not being displayed on old servers

src/engine/client/updater.cpp
```
[2021-02-12 10:33:01][storage]: failed to rename: Z:\DDNet-15.2.5-win64/discord_game_sdk.dll -> Z:\DDNet-15.2.5-win64/discord_game_sdk.dll.old
[2021-02-12 10:33:01][storage]: failed to rename: Z:\DDNet-15.2.5-win64/discord_game_sdk.so -> Z:\DDNet-15.2.5-win64/discord_game_sdk.so.old
[2021-02-12 10:33:01][storage]: failed to rename: Z:\DDNet-15.2.5-win64/update/discord_game_sdk.so -> Z:\DDNet-15.2.5-win64/discord_game_sdk.so
[2021-02-12 10:33:01][updater]: replacing DDNet.exe
[2021-02-12 10:33:01][storage]: failed to remove: Z:\DDNet-15.2.5-win64/DDNet.old
[2021-02-12 10:33:01][updater]: replacing DDNet-Server.exe
[2021-02-12 10:33:01][storage]: failed to remove: Z:\DDNet-15.2.5-win64/DDNet-Server.old
```
=> Don't try to update .so files on Windows

src/game/client/components/chat.cpp, src/game/client/skin.h
It should always search all lines(reprod. by changing windows size, which causes text containers to reset, which then causes skins to be not refound, when skins actually changed)
=> Fix chat refind skins

src/game/ddracechat.h, src/game/server/score.cpp
=> Improve performance of /top5points query, remove negative /top5points since it makes no sense anyway

src/game/editor/editor.cpp
As reported by texnonik on Discord
=> Don't toggle Destructive in editor when pressing ctrl-shift-d

src/game/editor/layer_tiles.cpp
=> Prevent editor crash when setting image to None

src/game/server/score.cpp
For the first one, I'm not sure how this ever worked (the ranks did end up in the DB though). The other one was introduced by a rebase.
=> Fix errors introduced by the MySQL C API pull request

src/game/client/components/statboard.cpp
Current behavior is not showing it, so better than nothing.
Since FNG with over 16 players is quite a thing, its nice to have it working
=> Make statboard work with up to 32 players

src/game/server/score.cpp
Pull request #3630 started showing the countries where ranks are from,
but created a mismatch between the two queries, one selected
Time, Ago, Stamp
the other
Time, Ago, Stamp, Name, Server
but both tried accessing the server. Add Server to the former query and
swap Name and Server in the second query to fix the problem.
Fixes #3643.
=> Fix /times query by reordering fields

src/game/client/components/chat.cpp
=> Fix ": " being included in "*** : abc" server messages

src/engine/server/databases/mysql.cpp, src/game/server/score.cpp
Thanks to @Zwelf for help with debugging.
=> Fix two mistakes of the MySQL C API rewrite

src/base/system.c
Thanks to 拓真 on Discord for report
=> Don't leak memory on Windows in logger

src/game/server/score.cpp
The C API doesn't return 0.0f for NULL values, check for them
explicitly.
Fixes #3653.
=> Fix /mapinfo displaying a time when not having finished

src/engine/shared/config_variables.h, src/game/server/gamecontext.cpp
This adds a delay before one can chat. It should help mods in situations where people are spamming chat
=> Add initial delay to talking in chat

CMakeLists.txt, src/engine/client/client.cpp
=> Don't allocate the windows console default

scripts/dmg.py
```
Traceback (most recent call last):
File "/home/deen/isos/ddnet/ddnet-source/scripts/dmg.py", line 106, in <module>
main()
File "/home/deen/isos/ddnet/ddnet-source/scripts/dmg.py", line 103, in main
dmg.create(volume_name=args.volume_name, directory=args.directory, dmg=args.output, symlinks=symlinks)
File "/home/deen/isos/ddnet/ddnet-source/scripts/dmg.py", line 59, in create
self._create_hfs(hfs, volume_name, output_size)
File "/home/deen/isos/ddnet/ddnet-source/scripts/dmg.py", line 42, in _create_hfs
with open(hfs, 'wb') as f:
TypeError: expected str, bytes or os.PathLike object, not tuple
```
Not sure why it worked before, seems to have always been this way: https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp
> mkstemp() returns a tuple containing an OS-level handle to …
=> Fix dmg.py

src/engine/client/http.cpp
Our typical HTTPS answer is reduced by 85% by this. Our JSON seems to
compress really well.
=> Automatically use HTTPS compression if the server supports it

CMakeLists.txt
Need to wait for the artifacts to test, if this works, dont have VS currently
I wonder why VS doesnt output an error that WinMain isnt found :D
=> Tell MSVC that main is still entry

src/engine/server/server.cpp
=> Fix legacy serverinfo with reserved slots and num_players > 15 (fixes #3678)

src/engine/server/server.cpp
Caused by https://github.com/ddnet/ddnet/pull/3605
Found by ASAN:
```
==11628==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 64 byte(s) in 64 object(s) allocated from:
#0 0x4f36b3 in __interceptor_malloc (/home/teeworlds/servers/DDNet-Server-asan+0x4f36b3)
#1 0x5536a7 in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2362:31
#2 0x562408 in main /home/teeworlds/src/master/src/engine/server/server.cpp:3594:21
#3 0x7f6ee56d209a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
```
=> Free Client.m_PersistentData

src/engine/client/client.cpp, src/engine/client/friends.cpp, src/engine/client/ghost.cpp, src/engine/client/graphics_threaded.cpp, src/engine/console.h, src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/console.cpp, src/engine/shared/console.h, src/engine/shared/demo.cpp, src/engine/shared/econ.cpp, src/engine/shared/econ.h, src/game/client/components/binds.cpp, src/game/client/components/broadcast.cpp, src/game/client/components/chat.cpp, src/game/client/components/chat.h, src/game/client/components/console.cpp, src/game/client/components/console.h, src/game/client/components/motd.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
dunno how to trigger that echo chat, but rest looks fine i think
=> More colors from components in console

src/engine/server/server.cpp, src/engine/shared/netban.cpp
to show ban message more accurately when player gets globally banned
=> Increase max ban duration from 1 month to 1 year

src/game/server/score.cpp, src/game/server/score.h
**/top**
Updated /top to always show the global 5. Also, show the region's top 3 if no local users are represented.
- The same information from the previous /top5 is displayed keeping consistency. Extra information is displayed only when relevant. 
- Regional top will be displayed even less often now that it takes the top 5 entries into consideration - before it was the top 3. 
**/rank**
Suggestions were made to update the format of /rank. The one with the most consensus was the below.
=> Updates to /top and /rank

src/game/editor/editor.cpp
All external images should be vanilla images, since other images can't be loaded by other clients.
Also:
- all external images should be allowed to be embedded (for example for 0.7 compatibility)
- only embedded vanilla images should be allowed to become embedded again
This change focuses on enforcing those basic rules. Vanilla images are identified using only their name, this method was used to sort images into embedded/external upon adding them.
The only real change is that the editor will now only allow making an image external if it has a vanilla name.
The motivation of this change are:
- a few times I was sent maps I couldn't load properly because the mapper accidentally made some images external
- there are some DDNet maps with external images that are not vanilla images
=> Editor: only externalize images with vanilla names

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/game/client/components/controls.cpp, src/game/client/components/controls.h, src/game/client/gameclient.cpp, src/game/client/gameclient.h
It's works now for both on console/cfg and as bind. Also tried to fix annoying dummy hammer issue when reset dummy
=> Add dummy_reset and remove +resetdummy

src/game/client/components/menus_settings.cpp, src/game/client/skin.h
Broke x_ skins, caused by https://github.com/ddnet/ddnet/pull/3214
=> Different comparators for skins in UI (no case) and regular skins (with case)

src/engine/client/serverbrowser.cpp
With "Count playery only" and "Filter connecting players" both activated
=> No negative count in server browser

src/base/tl/algorithm.h
so that for example demos stay sorted the same way when sorting by demo
markers and removing a demo, otherwise they get totally reordered every
time.
as reported by Shyzo
=> Switch back to using a stable sort

src/game/client/components/menus_settings.cpp
=> Fix scrolling in controls settings with ui_scale < 100 (fixes #3727)

cmake/FindFFMPEG.cmake
Set CMake to search for 'x264' pkg-config file as well to fix for Arch Linux (at least).
Fixes #3739
=> Search for both x264 and libx264

src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h
=> Print GPU info into console

src/engine/client.h, src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/client/input.cpp, src/engine/graphics.h, src/engine/shared/config_variables.h, src/game/client/components/menus.h, src/game/client/components/menus_settings.cpp
Yeah no idea, without dropdown it looks weird xd, so more of an idea:
hopefully fixes #3571 by making it clear what borderless is intended to be(not fullscreen)
=> Differenciate better between window modes

src/engine/client/graphics_threaded.cpp
He wanted a more orange color :D
=> Different screenshot console color(by Ravie)

src/base/system.c
=> Detect hangul choseong filler character as whitespace (fixes #3752)

.github/workflows/build.yaml
CMake 3.20.0 ignores the next CLI parameter after --parallel. Fix that by
moving it to the end of the command line.
https://gitlab.kitware.com/cmake/cmake/-/issues/21966
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5936
It is meant to be fixed in CMake 3.20.1.
=> Work around CMake 3.20.0 bug, fix packaging on CI

src/game/server/score.cpp
With the MySQL C API, we need to distinguish between SQL statements that
return result sets and those that do not, UPDATE is one of those that
don't produce a result set.
Fixes #3725.
=> Fix team rank updating not working

src/game/client/components/hud.cpp, src/game/client/components/killmessages.cpp, src/game/client/components/menus_ingame.cpp
- hud score
- kill messages
- vote menu
- player list (ingame menu)
old:
new:
there would still be in the HUD settings and the emote wheel.
Guess both dont matter too much, emote wheel is not inside a box and has a really weird hitbox anyway
=> Center more tees

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_settings_assets.cpp
& reload current asset on reload button click
fixes #3706
=> Add console chain for assets

src/game/server/entities/character.cpp, src/game/server/teams.cpp
Removed the reset of external tees hooks on the specific teleport types. 
For issue #3766
=> Fixed hook being lost for specific teleports

src/engine/client/client.cpp
When for example using local console ``connect localhost`` while being in reconnect state. The timer will not be reset to 0. And maybe there are even other cases so make sure to never reconnect while being in game.
=> Fix auto reconnect while in game

CMakeLists.txt, src/base/system.c, src/test/netaddr.cpp
The port in the NETADDR struct was left uninitialized.
Add some tests to ensure behavior.
CC #3774 #3775
=> Fix parsing an IPv6 address without port

CMakeLists.txt, src/base/detect.h, src/base/system.c, src/base/system.h, src/engine/client/backend_sdl.cpp, src/engine/shared/storage.cpp
I initiated a port of ddnet and received a lot of help from the IRC in order to do so as seen in #2986. Unfortunately, my efforts went stale after one point. Fortunately, however, @threedeyes released a [set of patches for Teeworlds](https://github.com/haikuports/haikuports/blob/2ea72967cd2ab635a328ea82d686956769dd9ffc/games-action/teeworlds/patches/teeworlds-0.7.5.patchset). I decided to take down my repository with my own work and attempt to port Gerasim's work, which includes code for setting the directories that ddnet should use the same way one would do so in a Mac OS X-system in `src/base/system.c`, which was precisely the part where I got stuck in on my first attempt.
The changes have not been tested thoroughly yet and were the result of methodic copying and pasting.
=> Copied Teeworld patches for the Haiku operating system

src/engine/server/server.cpp
My server puts newly joined players in spectators despite sv_tornament_mode 0.
Seems like CClient::m_HasPersistentData is never initialized, and it was read as true (non 0) by chance (server.cpp:1477) and the server get to read more garbage in CClient::m_pPersistentData, then decided to put the player in spec.
- [*] Tested the change ingame
=> initialize CClient::m_HasPersistentData

src/game/client/gameclient.cpp
closes #3361
also made sure dummy gets the predicted airjump as well to sync up with local character because why not.
=> Fix Airjump for Antiping

src/game/client/components/items.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/client/prediction/entities/laser.cpp, src/game/client/prediction/entities/projectile.cpp, src/game/client/prediction/gameworld.cpp, src/game/client/prediction/gameworld.h, src/game/client/projectile_data.cpp, src/game/client/projectile_data.h
Video demo: https://cdn.discordapp.com/attachments/293493549758939136/834971531464671252/2021-04-23_09-57-35.mp4
(notice the speed difference between player's shotgun bullets and the bouncing ones)
Video demo2: https://cdn.discordapp.com/attachments/293493549758939136/834990657147764736/demotopleftisnew.mp4
(Right: before, Left: after)
Since TuneZones are known (baked into the map), and entities' position received are known. We have a pretty good reason, if the server is believed to make use of it (GAMEINFOFLAG_PREDICT_DDRACE_TILES), to make entities always reference TuneZone settings, even if they are not predicted. 
Introduced a new worldconfig, `m_UseTuneZones`, that ignores antiping settings and apply TuneZone where applicable if the server is believed to support TuneZone.
When …
=> Allow unpredicted TuneZone settings for projectiles and lasers

src/game/client/components/binds.cpp
This fixes the issues for the meanwhile, but I think I want to rewrite this. We are kind of wasting memory and it behaves really oddly with multiple binds that match the chord progression. The bug was introduced in #2675
Fixed #3771 for now. @fokkonaut please check
=> Fix composed binds involving F-keys

src/game/client/components/menus.cpp, src/game/client/components/menus_ingame.cpp
Putting a search string that doesnt find any server, or hold Up key while loading the client, or switching tabs can cause a crash, bcs the server list is empty, but input signals, it was changed
=> Fix serverbrowser crash

src/game/client/prediction/entities/character.cpp, src/game/server/entities/character.cpp, src/game/tuning.h
as requested by J$ON for new map with Genex
the current hammer_fire_delay is only used when no other tee has been
hit. In order not to change any existing behaviour I have added a new
tune for the case of hitting, instead of making the existing one control
both.
=> Add hammer_hit_fire_delay tune

src/game/client/gameclient.cpp, src/game/client/prediction/gameworld.cpp, src/game/client/prediction/gameworld.h
Missed a spot where the predicted world still returns current tuning.
closes #3799
=> Get rid of current tuning in predicted world

src/engine/client/text.cpp
Notice the game mode "DDRace" jumping/jittering while scrolling,
probably bcs it was near the next floating point (smth like 0.9999f) but rounded down:
https://user-images.githubusercontent.com/6654924/116807307-c06cc380-ab32-11eb-8076-fd8d8aeb5a09.mp4
=> Make pixel alignment numerical more robust

src/tools/map_optimize.cpp
This resulted in duplicate items, with the exact same id and type_id (and content, but id + type_id are supposed to be unique)
Credits to heinrich5991 for his feeling that the UUID index duplication could originate in this file.
=> [map_optimize] Fix duplication of ITEMTYPE_EX (uuid index) items

src/engine/shared/datafile.cpp, src/engine/shared/datafile.h, src/tools/map_convert_07.cpp, src/tools/map_optimize.cpp, src/tools/map_replace_image.cpp, src/tools/map_resave.cpp
As @Jupeyy correctly pointed out in #3803, the issue is in every single tool that resaves a map.
The only tool I haven't tested the fix with is map_replace_image, since I experienced other unrelated issues there.
=> [map tools] Fix duplicate uuid index in maps edited by tools

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_settings.cpp
Different approach to #3588
This is HSL aware, so clamping the light is easier/possible.
Also fixes #3576
=> Implement HSL sliders

src/engine/client/steam.cpp
instead of just ip address
Currently works: steam://run/412220//185.107.94.201:8337/
Should work with this PR: steam://run/412220//nld.ddnet.tw:8337/
I'm building a test build with Steam support to verify this works. Update: Verified that this works.
=> Steam: Support connecting to hostname

src/base/system.c, src/test/netaddr.cpp
https://tools.ietf.org/html/rfc5952#section-4
Also add some tests.
=> Compress IPv6 string representations according to RFC5952

CMakeLists.txt, src/base/tl/sorted_array.h, src/test/sorted_array.cpp
as TsFreddie pointed out, it asserts inside the array function back(), bcs the list is empty.
=> Only sort friends, if you got any

src/engine/client/backend/opengl/backend_opengl.cpp, src/engine/client/backend/opengl/backend_opengl.h, src/engine/client/backend/opengl/backend_opengl3.cpp, src/engine/client/backend/opengl/backend_opengl3.h, src/engine/client/backend_sdl.cpp
Especially with GL 3.3, which has a shutdown command implemented, it should only get called, if it actually created the the backend stuff.
=> Make init/shutdown when GL processor creation fails safer

src/engine/client/backend/opengl/backend_opengl.cpp, src/engine/client/blocklist_driver.cpp, src/engine/client/blocklist_driver.h, src/test/blocklist_driver.cpp
I also added, that the warning doesnt require to be displayed, as it currently won't help anyway to update the driver.
Should set all Intel users to OGL 2.0 default, they can ofc still manually change the setting as they want
=> Add Intel as vendor to the block list on windows

src/engine/shared/config_variables.h, src/game/client/components/menus_settings.cpp, src/game/client/components/players.cpp
=> Add hookcollision color changeable

src/game/client/components/skins.cpp
So metrics are correct even for edge cases and also the greyscale is accurate with edge cases.
e.g. this skin is valid from rendering perspective, but might cause inaccuracy bcs in greyscale the width wasnt respected correctly:
=> Differenciate between width and height for body part

src/game/client/components/menus_settings.cpp
Was still from the first version of the HSL sliders, which didn't had a border around the selector and made the alpha slider invisible(for menu colors slider), but thats not needed anymore(bcs borders are not transparent).
=> Remove alpha clamp

src/game/editor/editor.cpp
Do not overwrite the current map when saving as a new file
closed #1972
=> Make sure ctrl+shift+s works same as clicking UI

src/game/client/components/menus_demo.cpp
I assume shift is a common compose bind. So users might have bound
shift+scroll or shift+arrowkeys to something else and do not want to
change the playback speed while triggering that compose bind.
I have to admit this is something I personally need and I am not sure what the demand for it is.
But for example my zoom bind is shift+mousewheelup and shift+mousewheeldown and I change that a lot while watching demos but it keeps affecting the playback speed. Maybe someone else has a compose bind using the alt key I do not know. But this solves my issue :)
=> Add better support for compose binds in demo menu

src/game/client/prediction/entities/laser.cpp, src/game/client/prediction/entities/projectile.cpp, src/game/client/prediction/gameworld.cpp, src/game/client/prediction/gameworld.h, src/game/server/entities/dragger.cpp, src/game/server/entities/gun.cpp, src/game/server/entities/laser.cpp, src/game/server/entities/light.cpp, src/game/server/entities/plasma.cpp, src/game/server/entities/projectile.cpp, src/game/server/entity.h, src/game/server/gameworld.cpp, src/game/server/gameworld.h
Removed one indirection from entities destruction code and removed two related unused functions. I could change the access to `m_MarkedForDestroy` via `IsMarkedForDestroy()` and `MarkForDestroy()` if it is preferred (the previous code didn't use the functions).
=> Simplify entities destruction

src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/client/prediction/entities/character.cpp, src/game/client/prediction/entities/character.h, src/game/gamecore.cpp, src/game/gamecore.h, src/game/server/entities/character.cpp
*I might be totally insane for doing this.
*The effect is only truly noticeable if you have high ping AND dropping packets.*
*clang-tidy's warning doesn't seems to relate to anything I've changed*
Now characters will try to respect TuneZones when ~~evolving and~~ predicting (like projectiles do). Since it is really important to keep TuningList as accurate as possible, I made a TuningList update logic so we try our best to update tunings only for the correct TuneZone (instead of constantly shoving current tuning into TuningList)
And each CCharacterCore now has its own Tunings to avoid any characters influencing GameWorld's tuning. Some server code has to be updated accordingly. I checked the code path, didn't notice anything that would make our server behave differently.
And I guess I …
=> Respect TuneZone for characters

src/game/client/components/items.cpp, src/game/client/prediction/entities/pickup.cpp, src/game/client/prediction/entities/pickup.h
PrevPredictedWorld is copied more frequently than snapshots so the position of pickups isn't interpolated unless it is moved by movers which happens in predictedworld. So, fallback to the normal path if mover is not present would fix jittery motions of pickups in mods like monster.
=> Only predict pickup if affected by movers

src/engine/client/serverbrowser_ping_cache.cpp
Use `vector.data()` instead of `&vector[0]` to get access to the
underlying array.
Fixes #3850.
=> Fix (harmless) array OOB access when no pings were cached

src/engine/shared/memheap.cpp, src/engine/shared/memheap.h, src/game/server/gamecontext.cpp
Fixes alignment issues for `CVoteOptionServer`. I used a default parameter so everything should be (wastefully) aligned at the very least.
Maybe in the long term we can look to get rid of usages of memheap. Should be careful to not replace it with just malloc though since in many uses of the memheap we have it would cause a lot of fragmentation leading to (ithink) cache misses and wouldn't play along well with prefetch.
=> Fix alignment for CVoteOptionServer

src/engine/client/http.cpp, src/engine/client/http.h, src/engine/client/serverbrowser_http.cpp
As reported by fokkonaut on Discord. Not sure if we lose relevant
information.
Previously:
```
[2021-05-28 12:08:54][http]: http https://master2.ddnet.tw/ddnet/15/servers.json
[2021-05-28 12:08:55][http]: task done https://master2.ddnet.tw/ddnet/15/servers.json
[2021-05-28 12:08:55][http]: http https://master2.ddnet.tw/ddnet/15/servers.json
[2021-05-28 12:08:57][http]: task done https://master2.ddnet.tw/ddnet/15/servers.json
[2021-05-28 12:08:57][serverbrowse_http]: found master, url='https://master2.ddnet.tw/ddnet/15/servers.json' time=2437ms
[2021-05-28 12:08:57][http]: http https://master4.ddnet.tw/ddnet/15/servers.json
[2021-05-28 12:08:57][http]: task failed. libcurl error: Could not resolve host: master4.ddnet.tw
[2021-05-28 12:08:57][http]: http …
```
=> Reduce spamminess of http server browser

src/game/server/entities/character.cpp
Fixes #3880
I believe that it can be safely merged. I tried to see the difference, but I couldn't get a measureable difference with only Kill-Tiles and Stoppers.
All affected maps with number of death tiles in front layer (generated with Patigas twmap library):
```
"types/brutal/maps/Rogue World.map": 189
"types/brutal/maps/New World.map": 214
"types/brutal/maps/Flow Fever.map": 7
"types/brutal/maps/A Strange Dream.map": 372
"types/brutal/maps/Jungledread.map": 1253
"types/brutal/maps/Lobster Party.map": 19
"types/novice/maps/Tangerine.map": 354
"types/solo/maps/Vesper.map": 238
"types/ddmax/maps/Creative.map": 6
"types/dummy/maps/Juma.map": 1
"types/dummy/maps/Ulver.map": 15
"types/dummy/maps/NoTeleBro.map": 1
"types/dummy/maps/Gummy.map": 1
"types/dummy/maps/Cultist.map": 5 …
```
=> Fix inconsistent handling of death tile between front and game layer

src/game/client/components/controls.cpp, src/game/variables.h
1. Since the config didn't have a limit set, they could be negative, which directly caused bugs
2. If you set a min mouse distance, lets say 5, It can mathematically happen that you drag your mouse exactly so much that you hit the (0, 0) point and the if(.. < MinDistance) branch normalizes that point, which causes non restorable NaNs.
It's now safe, the min distance is later in code checked to be atleast 1, i "even" just made it safe enough, so there shouldn't be any change in behaviour:
https://github.com/ddnet/ddnet/blob/07ab4d53562cd81db27fa6e7f7cc2fa23a583e38/src/game/client/components/controls.cpp#L298-L304
Which casts the float to an int and checks the int, and this does not restore the mouse pos for NaNs, because nan to int is not 0
its some insanly high value int_max or smth
To …
=> Make mouse pos calculation more robust against NaNs

src/engine/shared/config_variables.h, src/game/client/components/countryflags.cpp
`https://github.com/teeworlds/teeworlds/issues/897`
this was the reason why it was ever implemented into teeworlds, but i guess this won't help alot with performance to run potatoworlds
just another random setting imo
=> Remove cl_load_country_flags

src/engine/client/client.cpp, src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser.h
Thanks to @Jupeyy for figuring out this bug.
Previously, the client would send the request for server info and the
server info ping packet with the same token, making the answer
indistinguishable from each other. Fix this by generating a token that
won't collide.
Fixes #3862.
=> Send server info request for ping with different token

src/game/client/components/menus_ingame.cpp
These two headers weren't translated.
=> Translate "Name" and "Time" header in ghost menu

src/engine/client/backend/opengl/backend_opengl.cpp
Makes sure to ignore framebuffer values.
This should be part of the next patch.
=> Force alpha values from glReadPixel to 255

src/engine/shared/config_variables.h
I missed this during the `serverlist_urls.cfg` →
`ddnet-serverlist-urls.cfg` rename.
=> Fix help text of cfg var to mention correct filename

.github/workflows/codeql-analysis.yaml
> 1 issue was detected with this workflow: git checkout HEAD^2 is no
> longer necessary. Please remove this step as Code Scanning recommends
> analyzing the merge commit for best results.
https://github.com/ddnet/ddnet/actions/runs/931568951
=> Don't use HEAD^2 in codeql anymore

src/engine/client/updater.cpp
=> Fix str comp parameter in updater

src/engine/client/http.cpp, src/engine/client/http.h, src/engine/client/serverbrowser_http.cpp, src/game/client/components/skins.cpp, src/game/client/components/skins.h
Use it for the "determine best masterserver" job, so that we can debug
failures.
=> Add a new failure log level to the HTTP module

src/engine/client/serverbrowser.cpp
=> Don't set cached pings for servers without info

src/game/editor/editor.cpp
I assume is the cause the cursor in editor often is gone, bcs when alt tab it moves the cursor based on uninitialized values
=> Init mouse diff floats in editor

src/game/server/ddracechat.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
Not sure if we should just allow them whenever someone is muted
Fixes #3929
=> Still allow lock/unlock/practice while sv_chat_initial_delay is set

data/languages/german.txt, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp
When a player wants to switch servers in-game, but needs to confirm the
action because of cl_confirm_disconnect, the game used to not actually
connect to the new server.
This adds a way to still connect to that server, after the player
confirms.
=> Fix: Switch servers after player confirmed POPUP_DISCONNECT

src/game/client/prediction/entities/character.cpp, src/game/client/prediction/entities/pickup.cpp, src/game/client/prediction/entities/projectile.cpp
I couldn't reproduce #3934, but I believe it was caused by uninitialized values in projectiles (m_Layer and m_Number), which should be fixed now. Also cleaned up the unused switch code (all except tiles with number 0).
=> Remove switch state from prediction, initialize m_Layer

src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
=> Avoid double free on m_pScore (fixes #3939)

src/game/editor/editor.cpp
So that you cannot use arrow keys in the edit box,
this was default behavior before(was accidentally removed by ui ex)
and for arrow up and down it wasn't implemented yet
=> Fix disallowing arrow keys in editor edit box

src/game/server/gamemodes/DDRace.cpp, src/game/server/save.cpp, src/game/server/save.h, src/game/server/teams.cpp, src/game/server/teams.h
Previously, tees could go around the start line on some maps, going
directly to the finish line while leaving one tee behind at the start.
By letting that sole tee start and kill itself, the team could be
directly at the finish at time 0:00.
Fix this by requiring every tee of a team to hit the start line before
being able to finish. Tees can still get some advantage by skipping the
start line, but it will no longer be a 0:00 finish.
=> Try to fix "start line skipping"

src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
checked runtime with valgrind, found one uninitialized value
=> Go back to constructor destructor

src/game/server/save.cpp
"\t" was missing for one variable.
=> Fix save codes (symptom: always jumping after load)

src/game/editor/editor.cpp
=> Fix out of bounds in editor render image

src/game/server/gamemodes/DDRace.cpp, src/game/server/teams.cpp
It has been happening to all teams. Send `CGameTeams::OnCharacterStart`
even if the team has already started.
=> Fix "tee hasn't hit the start line yet" error

src/game/client/components/menus.cpp
=> Fix pressing Home or End in server address field changes the selected server

src/engine/client/client.cpp
I think it should fix #3925.
Previously, the game stopped due to the fact that it was possible to turn on the selection by a random click, but if you disable the quick edit flags, then the selection can be made only by right-clicking the mouse and selecting an necessery option. 
The game will also stop, but after copying it will immediately continue, and this eliminates accidental pressing, that is, the person is fully responsible for his actions.
=> Disabling quick editing in the console

src/engine/client/client.cpp
(cherry picked from commit https://github.com/teeworlds/teeworlds/commit/009b072c340b778e0be4ee8eabd8522763233493)
Ok that was a weird cherry pick... 90% was already in :D
=> remove unused MenuTick, reuse existing m_LocalStartTime

src/engine/client/client.cpp
Fix https://github.com/teeworlds/teeworlds/issues/2645
The `Sv_ReadyToEnter` net message is only valid while we're still
loading stuff, it is used to signal that we can send the `ENTERGAME`
system message. Simply ignoring the server message while we're in the
wrong part of the state machine works.
(cherry picked from commit https://github.com/teeworlds/teeworlds/commit/a97f8a22dee3298c7c0ea7df9bc1733c2dd27a53)
=> Fix client use-after-free reported by mmmds

src/engine/client/client.cpp, src/engine/client/client.h
Closes https://github.com/teeworlds/teeworlds/issues/1058
(cherry picked from commit https://github.com/teeworlds/teeworlds/commit/bf61d41c49d92719e66df996fbb9c66df6a9f209)
No hard feelings from my side about the clamp. I am just hunting down em diffs to the upstream. But @heinrich5991 seemed a bit concerned [back in 2013](https://github.com/teeworlds/teeworlds/issues/1058#issuecomment-12178577)
Old:
New:
=> improved the debug graphs.

src/engine/client/client.cpp
@ChillerDragon  Seems to cause problems:
> Hussain wrote
> :last update+ beta
> my dummy stuck ( this second time)
> disconnect and connect again useless still stuck
> and disconnect server too
> have to restart the game
This reverts commit ce2f29b5f1e1925ac9292f29f7d498bd7da25aed.
=> Revert "Fix client use-after-free reported by mmmds"

src/game/client/components/menus_browser.cpp
I watched a live stream where someone struggled with this, not knowing
that right click has different functionality from left click, and had to
manually click on each entry to remove them all except one.
=> Make the country/type selection more intuitive

src/engine/client/backend/opengl/backend_opengl.cpp
For older OpenGL contexts
@Learath2 can you check this?
=> Use GL_ARRAY_BUFFER

src/engine/client/backend/opengl/backend_opengl.cpp, src/engine/client/backend_sdl.cpp, src/engine/shared/config_variables.h, src/game/client/components/menus_settings.cpp
- Save renderer & version string, so the fallback isn't portable between driver updates or system changes
- Only allow modern GL on modern systems(windows)
- Don't show modern GL in settings, if the driver is on the blocklist(this prevents Intel users from doing it, they can still force it over F1 console)
=> Make fallback stronger and safer

src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/client/prediction/entities/character.cpp
Prediction of freeze and other tiles in switch layer (for #3990)
=> Add prediction for switch tiles

src/engine/client/serverbrowser.cpp, src/engine/shared/serverinfo.cpp
This replaces remaining usages of `std::min` with `minimum`. Fixes build for me on Windows with Visual Studio 2015.
=> Use minimum instead of std::min

src/engine/shared/config_variables.h
The config variables are unused.
(First commit is also https://github.com/teeworlds/teeworlds/pull/2913)
=> Remove unused gfx_alphabits config variable and dead code

src/engine/client/backend_sdl.cpp
`SDL_SetWindowSize`'s documentation tells that `SDL_SetWindowDisplayMode` should be used to set the sizes of fullscreen windows. [SDL commit 72d812852023450b7c3850b8e87b63575df041ee](https://github.com/libsdl-org/SDL/commit/72d812852023450b7c3850b8e87b63575df041ee) changed `SDL_SetWindowSize`'s behavior so that it can no longer be used to set the screen resolution with windows that are created in fullscreen mode. `SDL_SetWindowDisplaymode` can be used instead when the window is fullscreen.
=> Fix fullscreen resolution setting on SDL 2.0.16

src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/client/input.cpp, src/engine/graphics.h, src/engine/shared/config_variables.h, src/game/client/components/menus_settings.cpp
Quick overview about the changes made
- Add refresh rate to fullscreen modes
- Show current resolution(on window mode for example update the resolution). Current behavior is, that the list index isn't updated -> see picture below
- Save current resolution, even on windowed mode
- Move get videomodes to main thread, like all window API(probably safer)
- Better window states updates, e.g. in maximized state it should remove maximize flag, when resized by the resolution list
And also update resolution when e.g. changing from fullscreen to windowed.
- No resolution list on desktop fullscreen, as this isn't intended anyway
windowed mode:
fullscreen:
=> Upgrade resolution list

src/game/server/ddracechat.cpp, src/game/server/teams.cpp, src/game/server/teams.h
In addition for #4005.
Now /team -1 forces player to first empty team.
=> Add /team -1

src/engine/client/serverbrowser_http.cpp
fixes #3951
by adding a state if no master was found
=> Add state if no master was found

src/engine/client/backend_sdl.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/input.cpp
This bug already existed in our current release, so its not related to some SDL update
=> Make fullscreen changes better (especially under windows)

src/base/system.cpp, src/base/system.h, src/engine/shared/storage.cpp, src/engine/storage.h, src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp, src/game/client/components/race_demo.cpp, src/game/client/components/race_demo.h
It was previously not possible to load a map or really any file with a filename containing unicode, e.g. german umlauts.
Now all filenames are converted from multibyte to widechar on windows, and the correct functions and structs (with the `W` suffix) are used consistently.
Some changes are made to synchronize ddnet's implementation with upstream (once https://github.com/teeworlds/teeworlds/pull/2936 has been merged there):
- The unused and not working `IOFLAG_RANDOM` is removed (on upstream ddnet's `IOFLAG_APPEND` is added instead).
- The `fs_listdir_info` function is renamed to `fs_listdir_fileinfo` and now using the parameter object `CFsFileInfo` that contains the filename, modified date and creation date, making it easier to add more properties in the future. …
=> Fix filesystem/IO with unicode filenames on windows

src/engine/shared/config_variables.h, src/game/client/components/menus_settings.cpp, src/game/client/components/players.cpp
cl_show_local_direction allows you to see your own key presses during the game.
I changed the statements so it will allow local player to have key press arrows (inside the game), and I added a statement for configs (settings), so if you have cl_show_local_direction enabled, it will render the directions (arrows) for the local player. (Also affects demos and videos, same as cl_show_direction)
=> Add cl_show_local_direction (fixes #3978)

src/engine/shared/config_variables.h
The maximum for cl_show_direction was supposed to be 2 but it looks like I forgot to change it in #4133  so if someone check show local player's key presses in DDNet settings (or do cl_show_direction 2), it will be reset to 1 next time the client launches.
=> Fix cl_show_direction wrong maximum

src/game/client/components/players.cpp
This condition is too complicated to understand I think...
```
src/game/client/components/players.cpp: In member function ‘void CPlayers::RenderPlayer(const CNetObj_Character*, const CNetObj_Character*, const CTeeRenderInfo*, int, float)’:
src/game/client/components/players.cpp:546:130: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
546 |         if(((!IVideo::Current() && (g_Config.m_ClShowDirection >= 1)) || (IVideo::Current() && g_Config.m_ClVideoShowDirection)) && ClientID >= 0 || DemoPlayer()->IsPlaying())
|            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
```
=> Fix parantheses warning

CMakeLists.txt, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded_null.h
This allows compiling the client without graphics backend and thus it
can run also in a non graphical enviornment
=> Add -DHEADLESS option to cmake (nulled gfx)

src/test/test.h
The variable isn't actually a path, just the test name formatted as file
name, so the 64 isn't actually too strict.
=> Remove a `#include <base/system.h>`

src/game/server/ddracechat.cpp, src/game/server/gamemodes/DDRace.cpp, src/game/server/teams.cpp, src/game/server/teams.h
This is to avoid players playing in unfinishable teams for a long time
if they don't understand the system messages.
Fixes #4088.
=> Kill unfinishable teams if they don't enter /practice within a minute

src/engine/shared/config_variables.h
Opinions? Someone on Discord just had the issue that a gameplay on FNG wasn't recorded. I think keeping the last 10 demos around isn't too expensive disk-wise.
=> Record last 10 demos by default

src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser.h, src/game/client/components/menus_browser.cpp
So there is always a list rendered(not the "Getting serverlist" string)
This isn't really finished.
The goal should be to also cache the server list to disk and load it, so there is never an empty list.
Also currently I just made the "Refresh" button say "(Fetching) Refresh" to be clear the list might change.
Personally i think greying out the list could be a way to show it "more elegant".
Anyway, didn't really test it, if somebody wants to test out, give feedback or even build upon this, just do it.
=> Update server list silently

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/shared/demo.cpp, src/engine/shared/demo.h, src/game/client/components/players.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h
It's still not 100% the same as with high bandwidth, but atleast animation wise it should look the same.
The client doesn't predict if an emote actually is triggered, so it still only triggeres them every second tick without high bandwidth.
~Since this changes demo playing quite a bit, it should defs be tested~(not really xd)
fixes #4156
=> Make emoticons smoother

src/base/detect.h, src/engine/client/backend_sdl.cpp, src/engine/client/notifications.cpp
- Haiku is Unix-like, but it still doesn't use libnotify.
- Haiku comes with its own sets of definitions for certain long variables. There's still a problem revolving around the variables, but I removed a duplicate, conflicting definition on the Haiku platform.
- Changed some definition-related logic in detect.h, because the gcc compiler in Haiku (version 8.3.0) complained about duplicate definitions. I chose to use 'unknown' rather than an empty string.
I think that I'm very close.
=> Further fixes for Haiku

src/engine/server/server.cpp
I knew that there is `str_hex()` in `system.h` and then I accidentally noticed `char aHex[] = "0123456789ABCDEF";` here in CServer.
Also, as I was there, I reduced the stack-allocated buffer size from 512 to the only needed 97 bytes.
I compiled the server and checked that it works as before this change.
However, I've not triggered/checked this debug message.
=> CServer::ProcessClientPacket(): Refactor the debug on unknown message received

src/game/server/teams.cpp
Thanks to @murpii for noticing the long line.
=> Split long system message into two lines

src/engine/client/client.cpp
=> Ensure a snap is evaluated before the world is rendered the first time

src/game/client/gameclient.cpp
Previously, the old game info persevered into the next server.
=> Clear game info on connect

src/game/client/gameclient.cpp
=> Update world config even if the local character is dead

src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h
Fixed typo 'Automic' --> 'Automatic' in graphics_threaded. I thought i made a comment on the PR (https://github.com/ddnet/ddnet/pull/4160), but seems like i didnt send it in the end.
=> Fixed typo in variable name

src/game/client/components/console.cpp, src/game/client/components/emoticon.cpp, src/game/client/components/menus.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/editor/editor.cpp
This adds the convenience method `CUI::MapScreen` from upstream.
=> Add CUI::MapScreen convenience method

src/engine/client/client.cpp, src/engine/client/graphics_threaded.cpp, src/game/client/components/menus.cpp, src/game/client/components/menus_settings.cpp
This changes all color instantiations to consistently use the constructor instead of an initializer list.
=> Use constructor consistently for colors

src/game/client/gameclient.cpp
=> Update default tune zone, when no local character is alive and tune zones don't exist

.github/workflows/build.yaml
Catches client crashes in the CI that happen on launch or connection to server
=> Run headless client in CI

src/engine/shared/config_variables.h
It was previously 4 per 20s which can cause problems with the default
reconnect delay of 5s when the server is full.
=> Set the maximum connection trials to 5 per 20s

src/engine/shared/config_variables.h, src/game/variables.h
with specific compile options or on specific builds
Also applies to https://ddnet.tw/settingscommands/
=> Add notes for settings only available

CMakeLists.txt
Undefined symbols for architecture x86_64:
"_SCDynamicStoreCopyProxies", referenced from:
_Curl_resolv in libcurl.a(libcurl_la-hostip.o)
ld: symbol(s) not found for architecture x86_64
=> Fix macOS build
