- src/engine/client/client.cpp
> Fallback to gameserver if LoadMap fails

- src/engine/client/fetcher.cpp
- src/engine/client/fetcher.h
- src/engine/fetcher.h
Fix formatting and a subtle bug.
> Fetcher Fix

- src/engine/client/client.cpp
This fixes the problem with the fallback.. Does look ugly...
> Fix for the crc fail fallback.

- src/engine/client/fetcher.cpp
> Follow 3xx Redirects

- src/engine/client/fetcher.cpp
- src/engine/client/fetcher.h
- src/engine/fetcher.h
Get rid of HTTPResponse which was an old experiment and don't use hardcoded storagetype.
> Some cleanup and a tiny fix.

- src/engine/client/client.cpp
- src/engine/client/fetcher.cpp
- src/engine/client/fetcher.h
- src/engine/fetcher.h
Not quite the prettiest of flowers up for advice.
> Escape the filenames.

- src/base/system.c
- src/base/system.h
- src/game/editor/auto_map.cpp
- src/game/editor/auto_map.h
every automapper that works in vanilla client will still work in ddnet client
btw. most of the line changes are just TAB's at the beginning of the lines
added OR
Pos 0 0 INDEX 5 OR 6
means that the tile will be replaced if its index is 5 or 6
added flag support for posrules
Pos 0 0 INDEX 3 YFLIP ROTATE
means that the tile will be replaced if its index is 3, it is yflipped, it is NOT xflipped, it is rotated
added NOTINDEX
Pos 0 0 NOTINDEX 7
means that the tile will be replaced if its index is not 7
added NewRun
if you use first rule 'two1' and then rule 'two2', it will be the same as just using rule 'single'
[two1]
Index 1
NoDefaultRule
Random 10
[two2]
Index 2
NoDefaultRule
Pos 1 1 INDEX 1
[single]
Index 1
NoDefaultRule
Random 10
NewRun
Index 2
NoDefaultRule
Pos 1 1 INDEX 1
> tons of automapper feautures

- bam.lua
- src/engine/external/md5/md5.c
- src/engine/external/md5/md5.h
we'll need that for the security token
> added free md5 implementation w/o deps

- src/game/client/components/menus_settings.cpp
Dont reintroduce removed buttons. Missed this while rebasing.
> Small revert

- src/game/client/components/menus_settings.cpp
Added a button but couldnt find a way to switch back to the serverbrowser screen. Should maybe do a popup...
> Add Perform Update to settings

- src/engine/shared/network.cpp
- src/engine/shared/network.h
- src/engine/shared/network_conn.cpp
- src/engine/shared/network_server.cpp
this one would need a lot of testing
> added security token to protocol

- src/engine/shared/network.h
- src/engine/shared/network_conn.cpp
- src/engine/shared/network_server.cpp
timeout protection code now transfers the token properly
> fix timeout protection with tokens

- src/engine/client/autoupdate.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_browser.cpp
- src/game/client/components/menus_settings.cpp
Prevent suprise restart. Fix small bug with executable swapping.
> Fix couple of stuff with Autoupdate

- src/game/client/components/menus_browser.cpp
Show current version if there is no update. Fix the progress bar glitch at 0%.
> Fix a couple of small problems

- bam.lua
- src/game/editor/editor.cpp
see http://forum.ddnet.tw/viewtopic.php?f=5&t=1235
> Now you can type values in editor

- src/game/editor/editor.cpp
just a few improvements, sorry for the wrong code format btw
> improved envelopeswitching and deleting

- src/engine/client/graphics.cpp
- src/engine/client/graphics_threaded.cpp
(conform with intel/nvidia drivers)
> Change the way quads are split into triangle splits

- src/game/editor/editor.cpp
fix: Text labels were displayed wrongly with some resolutions
added: mouseclick to exit valueselector
> Editor - minior fix and improvement

- src/game/server/ddracechat.cpp
- src/game/server/ddracechat.h
- src/game/server/entities/character.cpp
- src/game/server/entities/character.h
- src/game/server/gamecontext.h
- src/game/variables.h
use /r or /rescue to teleport yourself out of freeze if you are in freeze, does not work with super and deepfreeze
use sv_allow_rescue to enable the feature (disabled by default)
> added /r, /rescue: teleport yourself out of freeze

- src/engine/client.h
- src/engine/client/client.cpp
- src/engine/shared/network.h
Actually we should rework the multiclient (atleast the connecting process). But this should be acceptable for now.
> Fix dummy connect delay (Fullfill securitytoken handshake)

- src/engine/shared/netban.cpp
> hacky bans fix

- src/engine/shared/netban.cpp
> fix the fix

- src/game/client/components/camera.cpp
- src/game/client/components/statboard.cpp
- src/game/client/gameclient.cpp
- src/game/variables.h
This PR handles several bugs with statboard, including http://forum.ddnet.tw/viewtopic.php?f=5&t=1552.
This PR also adds configuration variable cl_default_mouse_max_distance which is used by players who are using different mouse_max_distance from standard 400 and want to use full power of dynamic camera bind.
> Bugfixes for statboard + default mouse max distance feature

- src/game/client/components/statboard.cpp
- src/game/client/gameclient.cpp
It's relevant for states in which new RoundStartTick is sent each second tick.
Also clean up of statboard code is added to this PR.
> Fix bug with constant demo autorecording. Fixes #213

- src/engine/shared/storage.cpp
> Create directory for statboard screenshots

- autoexec.cfg
- src/base/system.c
- src/base/system.h
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/engine/shared/network_server.cpp
This allows users to access the remote console if they forgot to set a password.
> Randomly generate rcon passwords on startup, if none is set.

- src/game/editor/editor.cpp
& also, avoid spamming m_brush.clear() (useless but, save power for our planet !!)
> Zooming will work as in game for editor using numpad.

- src/game/editor/editor.cpp
- src/game/editor/editor.h
The old color of the buttons RGBA/XYR/V were just random and not meaningful. I changed them to the colors of the envelope graphs.
> fixed envelope button color

- src/game/client/components/camera.cpp
- src/game/variables.h
Fixes #266.
At the current state it's only dyncam variables, I'm planning to update more names with further commits.
> Correct names in variables.h

- src/engine/client/client.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/gameclient.cpp
- src/game/variables.h
Fixes #266.
It should be all by now, sorry for the mess with closing/reopening the issue. I merely thought at start that sleeping was a better idea than investing 15 more minutes. :blush:
> Add prefix Cl to dummy and player variables

- bam.lua
- scripts/make_release.py
- src/game/client/components/chat.cpp
- src/osx/notification.h
- src/osx/notification.m
This is how it looks like now:
DDNet-icon is bouncing one time at bottom of screen:
> added Notifications for osx

- src/engine/external/json-parser/json.c
- src/engine/external/json-parser/json.h
Fix a problem with compilation on Windows using mingw. Fix was made by Savander.
> Fix debug compilation on Windows with MinGW.(by Savander)

- bam.lua
- scripts/download.py
See issue: #256
Created the python side of the download script. Someone else could create the lua side. @Henningstone would you like to do that?
> Download script

- src/game/client/components/chat.cpp
Highlighting messages of your own just doesn't make sense.
> Don't highlight your own messages.

- src/base/color.h
- src/base/system.c
- src/base/system.h
- src/game/client/ui.cpp
- src/game/client/ui.h
- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/popups.cpp
The UI handling of the picker is a bit ugly cause of the Active/HotItem UI system and the popup system. Debugging is pretty time consuming to correctly state the active UI item all the time, but atm it's working okish
Edit: here a quick preview \o/
> HSV color picker for quad points

- src/game/client/components/menus_browser.cpp
Fixed double clicking on friend when he was on the first server in server list.
> Fixed double clicking on friend when friend was on top server.

- src/base/system.c
- src/base/system.h
- src/engine/shared/config_variables.h
- src/engine/shared/storage.cpp
- src/engine/shared/storage.h
- src/engine/storage.h
- src/game/client/components/menus.h
- src/game/client/components/menus_browser.cpp
- src/game/client/components/menus_demo.cpp
- src/game/variables.h
> Sorting demos by name and date (Column listbox)

- src/engine/client/client.cpp
- src/engine/server/server.cpp
- src/engine/shared/network.cpp
- src/engine/shared/network.h
- src/engine/shared/network_conn.cpp
- src/game/server/entities/character.cpp
Prevents packet injection into non-tokenized network sessions using the ack and sequence number.
> 0.6.4 vital/sequence checking

- src/game/editor/editor.cpp
http://forum.ddnet.tw/viewtopic.php?f=5&t=2277
actually this is a bug of tw itself, I will create a pr for vanilla soon too
> fixed Envelopes-Bug

- src/game/client/components/menus_settings.cpp
Just a trivial fix, add please.
> Fix menu music playing ingame, closes #349

- src/game/client/components/maplayers.cpp
cc https://github.com/ddnet/ddnet/issues/304
> Fix duplicated rendering of the game layers and cleanup outdated code

- src/engine/server/server.cpp
- src/engine/server/server.h
- src/engine/shared/config_variables.h
Reload map when server is empty (1 = reload once, 2 = reload everytime server gets empty)
Tested it extensive.
> added sv_reload_when_empty

- datasrc/datatypes.py
> Fix some VS2015 compiler warnings

- src/engine/server/server.cpp
This bugfix prevents another kind of faking names.
> FIRST trim the name and THEN compare it to others !

- src/engine/server/server.cpp
> prevent serverlogspam

- src/game/server/gamecontext.cpp
> Fix length of vote reason display in chat

- src/game/collision.cpp
> fix hooktele on unhook, broke with new hookthrough

- src/game/editor/editor.h
- src/game/editor/layer_game.cpp
- src/game/editor/layer_tiles.cpp
> hookthrough shortcut now works for game and front

- src/game/server/entities/character.cpp
> disable deepfly patch applied at wrong position

- src/engine/client/input.cpp
- src/game/client/components/hud.cpp
- src/game/client/components/hud.h
- src/game/client/components/killmessages.cpp
- src/game/server/player.cpp
- src/game/variables.h
It's same as fps but shows the ping (i get the ping from scoreboard ping)
I'm learning how to code in "teeworlds" xD, timakro is helping me :)
> Added cl_showping

- src/engine/shared/network.h
- src/engine/shared/network_conn.cpp
- src/engine/shared/network_server.cpp
> Copy resendbuffer on timeout protection

- README.md
Wouldn't it be like some kind of dependency since you need it to compile?
> added bam in readme

- src/game/editor/editor.cpp
Requested in forum https://forum.ddnet.tw/viewtopic.php?f=48&t=3939#unread.
> Display tee position in editor proof

- src/game/editor/editor.cpp
- src/game/editor/editor.h
https://forum.ddnet.tw/viewtopic.php?f=48&t=4121
> editor map SearchBar added

- src/game/client/gameclient.cpp
> dCopyMoves disabling when Dummy disconnecting

- src/engine/client/client.cpp
fix bug that press ctrl+shift+e enter editor and cannot input anything.
fixed by TsFreddie
> Fix editor cannot input

- src/game/client/components/chat.cpp
TsFreddie told me how to fix it. Thanks to him.
> Fix lost first character when quickly input in chat

- src/engine/client.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/io.cpp
- src/game/editor/popups.cpp
Should be good feature for testing/mapping
Was suggested on [ddnet forum](https://forum.ddnet.tw/viewtopic.php?f=48&t=4121)
> Load Current Map button added

- src/game/client/components/emoticon.cpp
https://forum.ddnet.tw/viewtopic.php?f=45&t=4294&sid=62271958370950a3ce779ed3dae29374
> emoticon render fix

- data/languages/brazilian_portuguese.txt
Changes by Rafael Fontenelle, I don't know the language. Because he already contributed translations 2014 this should be fine to merge without review.
> Update Brazilian Portuguese translation, closes #564

- data/languages/korean.txt
Improvements and added translations
> More Korean translations

- src/engine/demo.h
- src/engine/shared/demo.cpp
- src/engine/shared/demo.h
- src/game/client/components/menus_demo.cpp
@PathosEthosLogos Does this fix your issue?
> Refactor demo speed setting, add 1.5x speed (fixes #568)

- src/game/client/components/ghost.cpp
- src/game/client/components/race_demo.cpp
> Fix buffer overflow in race recorder and ghost

- src/game/client/components/binds.cpp
- src/game/client/components/binds.h
Adds a new command "bind_print s[key]" which prints the command that is associated with the specified key.
> New command bind_print

- src/engine/shared/console.cpp
This one was bugging me for quite some time.....
> Fix horrible indent.

- other/freetype/freetype.lua
- src/engine/client/fetcher.cpp
- src/engine/client/updater.cpp
- src/game/client/components/background.h
- src/game/client/components/ghost.cpp
- src/game/client/components/mapimages.h
- src/game/client/components/maplayers.cpp
- src/game/client/components/maplayers.h
- src/game/client/components/menus.cpp
- src/game/client/components/race_demo.cpp
- src/game/client/components/race_demo.h
- src/game/client/lineinput.cpp
- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/popups.cpp
- src/game/layers.cpp
- src/game/server/entities/character.cpp
> Get rid of trailing whitespaces

- src/engine/client.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/engine/demo.h
- src/engine/shared/demo.cpp
- src/engine/shared/demo.h
- src/game/client/components/chat.cpp
- src/game/client/components/controls.cpp
- src/game/client/components/emoticon.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_demo.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/versionsrv/versionsrv.cpp
Sorry for the broken server :/
> Refactor dummy input and demo filtering

- src/engine/shared/config_variables.h
- src/game/client/components/chat.cpp
- src/game/client/components/menus_settings.cpp
This one uses U2665.
Alternative is U2764
> Put hearts before friends names. Closes #606

- src/game/client/components/chat.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
Should maybe standardize CalculateNameColor to all messages at some point
> Fix coloring of team chat. Fixes #648

- src/game/client/components/controls.cpp
- src/game/client/components/controls.h
- src/game/client/gameclient.cpp
> Fix dummy input reset

- src/base/system.c
- src/base/system.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/engine/server/authmanager.cpp
- src/engine/server/authmanager.h
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/game/client/components/console.cpp
- src/game/client/components/console.h
Turns out @heinrich5991 is hard to please /s
This time with salted&hashed passwords and ugly teeworlds braces :)
> New auth system for rcon.

- CMakeLists.txt
Problem was reported on IRC, in #teeworlds on Quakenet.
> CMakeLists.txt: Create the generated source directory

- src/engine/client/client.cpp
- src/engine/client/text.cpp
- src/engine/server/server.cpp
These are the warnings i found in windows
> Fix some warnings (Maybe fixes #643)

- src/game/client/components/chat.cpp
- src/game/client/components/chat.h
- src/game/client/components/menus_settings.cpp
> Just color the heart preserving team information. Fixes #606

- src/game/editor/io.cpp
This supersedes #514 by @CytraL.
> Completed the refactor

- src/game/client/components/chat.cpp
This is looking more and more horrible :(
> Forgot m_Friend isn't initialized, also align the messages

- src/base/vmath.h
Fixed a typo and refactored the normalize function
> Fix a typo and refactor the normalize function

- CMakeLists.txt
> Fix link order for the client libraries

- src/benchmarks/textrendering.cpp
This especially separates the first frame from the rest, because it
seems that the startup time is non-negligable.
> Add some more statistics to text rendering

- src/game/client/components/chat.cpp
Forgot long lines wrapped at all. Sorry :(
> Fix line width. Closes #687

- src/game/client/components/menus_browser.cpp
Surely fixes it but I can't thoroughly test it on my laptop without a mouse :/
> Handle double click on server browser correctly. Fixes #597

- .travis.yml
- cmake/FindFreetype.cmake
This will allow us to test on macOS in the future.
> Test on Travis CI

- src/game/server/ddracecommands.cpp
GetPlayerChar already does bound checking.
Thanks @SoMeRelax.
> Remove unnecessary check. Fixes #714

- src/engine/shared/config_variables.h
- src/game/client/components/motd.cpp
There you have your fix for #711
> Handle multi-line motd correctly in the console

- src/game/client/components/chat.cpp
Forgot to completely remove the old hack which broke alignment. Fixes the case involving the scoreboard reported in #723.
> Fix a case reported in #723

- src/game/client/components/binds.cpp
- src/game/client/components/binds.h
Binds can be of any size now :)
> Allow arbitrary length binds

- src/engine/client/friends.cpp
- src/game/client/components/menus_browser.cpp
Uses the short-circuiting of `&&` to only check if the hashes match.
> Strict checking for friends

- src/game/client/components/chat.cpp
Been running this for an hour or so haven't seen an overlap yet. Only fixing the line wrapping algorithm remains.
> Fix chat overlapping

- src/game/client/components/binds.cpp
> Revert "Missed a case. Fixes #730"

- .gitattributes
for more info consult:
https://github.com/github/linguist#using-gitattributes
> exclude external libs from github statistics

- src/game/server/gamecontext.cpp
Fix a small indentation mistake and some useless spaces.
> Fix indentation

- src/game/server/ddracechat.cpp
- src/game/server/ddracechat.h
- src/game/server/gamecontext.h
- src/game/server/teams.cpp
- src/game/server/teams.h
This reverts commit 99cc9d2c0b59ad5c79258568bb1cb02bf2de784f.
I'd really appreciate it if you drop a message before reverting something @def-. Not like I'll refuse to fix any problems :/
> Add the invite system back

- src/game/client/components/debughud.cpp
I was tempted to convert the number into 0->359 but I just left it in whatever format it's already in
> Add show angle in debug

- src/game/ddracecommands.h
- src/game/server/ddracecommands.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
Kick votes in teams now move players to team 0. Also the timeout is now applied to successful votes too.
> Fix vote spam

- src/engine/client.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/engine/shared/config_variables.h
- src/game/client/components/menus_settings.cpp
- src/game/client/components/statboard.cpp
- src/game/client/components/statboard.h
En-/Disable statboard being saved as csv
> CSV file instead of statboard screenshot

- src/engine/shared/config_variables.h
- src/game/server/ddracechat.cpp
- src/game/server/player.cpp
- src/game/server/player.h
- src/game/server/teams.cpp
> Add ratelimiting for /invite

- src/engine/server.h
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/game/server/save.cpp
- src/game/server/save.h
- src/game/server/score/sql_score.cpp
Compiles but couldn't test this as I have no desire to spend the rest of my year trying to setup a MySQL ddnet server :P Fixed some styling issues while at it.
Obsoletes #720
> Tees must be teamed up before loading

- src/game/server/player.cpp
Seems to work fine. Tested with two ddnet clients.
> /pause'd players stay in player list

- src/engine/server/server.cpp
- src/engine/server/server.h
ConStatus and ConDnsblStatus differ in only one line, merge them back into a single function with an extra bool arg
> remove ConDnsblStatus copypasta

- src/engine/shared/config_variables.h
> Update the range of sv_default_timer_type. Fixes #760

- autoexec_server.cfg
- src/game/server/player.h
- src/game/server/score/file_score.cpp
- src/game/server/score/sql_score.cpp
- src/game/server/teams.cpp
Updating slow times still doesn't work. But setting bad times works well without hacks.
> fixed scoreboard update for slow racers (less hacky)

- src/game/server/player.cpp
I tested this a bit. There surely has to be a better solution.
Can't really test it well with a laptop.
> Can't spectate yourself when /pause'd

- src/game/client/components/statboard.cpp
this fixes corrupted stat csvs as str_format does not work with same
source and destination
> use str_append for appending strings

- .travis.yml
- CMakeLists.txt
- appveyor.yml
This seems to be wanted by CMake, it results in never having to re-run
`cmake`.
See e.g. https://stackoverflow.com/a/18538444/870079.
> List all source files instead of globbing them in `CMakeLists.txt`

- CMakeLists.txt
Hopefully fixes the CMake MinGW build.
> Statically link standard libraries in MinGW for CMake

- CMakeLists.txt
- src/engine/shared/datafile.cpp
- src/game/editor/io.cpp
- src/game/server/gamecontext.cpp
- src/tools/config_retrieve.cpp
- src/tools/config_store.cpp
- src/tools/map_replace_image.cpp
- src/tools/map_resave.cpp
fixing map_resave tool by using the correct item and data sizes
(fixes [#843](https://github.com/ddnet/ddnet/issues/843))
> Fixing map_resave tool and add map_replace_image tool

- CMakeLists.txt
- src/engine/shared/storage.cpp
- src/engine/storage.h
- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/io.cpp
- src/test/strip_path_and_extension.cpp
- src/tools/map_replace_image.cpp
> Add testing; fix, rename and test the `CEditor::ExtractName` function

- .travis.yml
- src/test/strip_path_and_extension.cpp
Fix the style of our only test.
> Run tests on Travis on Linux

- README.md
> Add instructions to run tests in README

- src/engine/client/client.cpp
- src/engine/client/client.h
- src/engine/client/fetcher.cpp
- src/engine/client/fetcher.h
- src/engine/client/updater.cpp
- src/engine/client/updater.h
- src/engine/fetcher.h
Adds a proper interface for `CFetchTask` and fixes a use after delete.
> Clean up the fetcher interface

- src/game/server/gamecontext.cpp
> Fix a syntax error

- src/engine/client/serverbrowser.cpp
- src/engine/client/serverbrowser.h
This alleviates the risk for spoofed servers.
> Use a random token for serverbrowse requests

- src/game/client/components/console.cpp
Login on a server that requires a username then join one which doesn't, try logging in and confusion ensues :P
> Reset the username on disconnect

- CMakeLists.txt
Also sort stuff like the rest of the file.
> Don't copy files twice in `CMakeLists.txt`

- .travis.yml
- appveyor.yml
- circle.yml
Adds it to all CIs so it's consistent. Obsoletes #888
> Run the server on CI

- src/base/system.c
classical typo hehe... it is an typo word.
> fixed boardcast

- data/languages/german.txt
Here's my update for the German translation of the client.
I've already ran the `copy_fix` update string thingie. Have fun! :-)
> Update German translation (27 Oct 2017 UTC)

- src/engine/client/client.cpp
- src/engine/client/fetcher.cpp
- src/engine/client/fetcher.h
- src/engine/engine.h
- src/engine/shared/engine.cpp
- src/engine/shared/jobs.cpp
- src/engine/shared/jobs.h
Not sure if this is the best way to go about this, but it works :/
> Fix use-after-free

- CMakeLists.txt
- circle.yml
- src/base/system.c
- src/base/system.h
- src/engine/client/client.cpp
- src/engine/client/updater.cpp
Old CMake doesn't understand `CMAKE_CXX_STANDARD` and similar, add the
parameter directly.
>  Activate C++11 in old CMake as well

- src/engine/client/graphics_threaded.h
- src/game/client/components/maplayers.cpp
It's not needed in that place anyway.
> Don't use nonstandard `#pragma pack`

- CMakeLists.txt
- src/base/system.c
- src/base/system.h
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/engine/shared/config_variables.h
- src/test/teehistorian.cpp
- src/test/unix.cpp
We currently use that on some of the servers, thanks to @H-M-H for trying to upstream it.
> Add address logging server

- src/engine/shared/config_variables.h
- src/game/server/gamecontext.cpp
Add option to only allow authed clients to call votes.
RayB asked for it on discord.
> Add sv_rcon_vote. Fix punctuation.

- src/engine/client/client.cpp
the ``dbg_msg()`` func doesn't work until the
``IEngine *pEngine = CreateEngine("DDNet", Silent);`` line gets executed.
I used a bool to leave the code order untouched c:
> fixed rand init error message

- src/game/server/gamecontext.cpp
I forgot a single ! in https://github.com/ddnet/ddnet/pull/996 and it made all broke. Right now force votes don't work on ddnet servers, this fixes it. Tested
> Fix votes, merge ASAP

- README.md
- src/game/server/gamecontext.cpp
- src/game/server/player.cpp
- src/game/server/player.h
This can't get out of sync now.
>  Remove `CPlayer::m_Authed` 

- data/languages/simplified_chinese.txt
Countries should mean “国家” but not "次数"。
> Change the wrong translation of Chinese

- src/game/client/components/menus_settings.cpp
Remove "vanilla" dyncam toggle.
> Fix dyncam confusion. Closes #783

- data/languages/portuguese.txt
This very badly overflows, just "Information" should work fine in this context.
> Fix UI break on portuguese

- src/game/server/ddracechat.cpp
- src/game/server/ddracechat.h
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- Also fix /pause and /spec with name parameter a bit
- Move out common code between pause/spec
> Add /pausevoted and /specvoted

- .gitignore
> Ignore Build and Release

- src/game/server/ddracechat.h
> Fixed typo

- CMakeLists.txt
- src/base/system.c
- src/base/system.h
- src/engine/server/name_ban.cpp
- src/engine/server/name_ban.h
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/game/client/components/chat.cpp
- src/game/server/gamecontext.cpp
- src/test/name_ban.cpp
- src/test/str.cpp
Overlong nick names could be used to circumvent name bans.
> Fix a bug with name bans

- src/engine/client/graphics_threaded.cpp
- src/engine/client/graphics_threaded.h
- src/engine/client/text.cpp
- src/engine/graphics.h
- src/game/client/components/hud.cpp
- src/game/client/components/scoreboard.cpp
- src/game/client/components/spectator.cpp
I'd say keep the pr open a few days, so i can fix all the problems the players will collect.
> Some text related fixes (color, positining)

- src/game/server/ddracechat.cpp
It just prints out that you actually enabled/disabled it
> Add /showall message

- CMakeLists.txt
- src/game/mapbugs.cpp
- src/game/mapbugs.h
- src/game/mapbugs_list.h
- src/game/server/entities/projectile.cpp
- src/game/server/entities/projectile.h
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/test/mapbugs.cpp
Unfix the grenade bug for "Binary".
> Add infrastructure for preserving bugs

- src/game/ddracecommands.h
- src/game/server/ddracechat.h
current ddnet doesn't support the '/help showall' command.
This commit should fix that.
> Fix help for showall command

- src/game/server/player.cpp
> fix pause messages

- src/game/client/components/menus_browser.cpp
it loaded favourite servers into ddnet serverlist if you used add_favorite or remove_favorite
also ddnet has the favourites server browser while online so removed offline check
> fix server browser bug

- src/engine/client/client.cpp
- src/engine/client/client.h
https://github.com/ddnet/ddnet/pull/1149#issuecomment-397538132
fixes issues with connecting to servers with reserved slots
> send password to first connected server

- src/game/server/entities/character.cpp
https://cdn.discordapp.com/attachments/293493549758939136/461236206131478538/PainWeaponBug.gif
because I'm new to coding it took me 2 hours to find this bug. I spent a while looking at the POWERUP_ARMOR and RemoveNinja() code wondering why it didn't work.
this bug is funny to some players so maybe you don't want to fix it. i wont mind because it was a challange for me to find it
> fix Pain weapons bug

- src/engine/client/backend_sdl.cpp
fixed https://github.com/ddnet/ddnet/issues/1018
> Fixed hidpi resolution issue on macOS

- src/base/system.c
- src/base/system.h
- src/engine/shared/console.cpp
- src/engine/shared/storage.cpp
- src/game/client/components/menus_demo.cpp
- src/game/client/components/menus_ingame.cpp
- src/game/client/components/race_demo.cpp
- src/game/client/components/skins.cpp
- src/game/client/components/statboard.cpp
- src/game/editor/auto_map.cpp
- src/game/editor/editor.cpp
- src/game/server/gamecontext.cpp
- src/game/server/teams.cpp
- src/test/str.cpp
- src/tools/config_common.h
- src/tools/map_diff.cpp
Add tests, use these functions in the code base.
> Add `str_startswith` and `str_endswith`

- data/shader/bordertileline.vert
- data/shader/bordertilelinetex.vert
- src/engine/client/backend_sdl.cpp
- src/engine/client/graphics_threaded.cpp
- src/engine/client/graphics_threaded.h
- src/engine/client/opengl_sl_program.h
- src/engine/graphics.h
- src/game/client/components/maplayers.cpp
- src/game/client/components/maplayers.h
> Don't render all border tiles all the time

- bors.toml
Status report names have changed.
> Update bors.toml for CircleCI2

- src/game/client/gameclient.cpp
- src/game/collision.cpp
- src/game/collision.h
- src/game/gamecore.cpp
- src/game/gamecore.h
- src/game/mapbugs_list.h
- src/game/server/entities/character.cpp
What approach do we want to keep old maps speed-runnable?
> Revert stopper fix

- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/layer_tiles.cpp
In some cases (very dark color, etc.) it is impossible to see the tiles.
Closes #1285.
> Add a toggle button for brush coloring

- src/game/editor/layer_tiles.cpp
As reported by texnonik on Discord.
> Fix crash when filling selection on tele/switch/speedup layers

- CMakeLists.txt
> Debug mode should only be default if DEV is set, release otherwise

- src/game/editor/editor.cpp
> Fix #963 dragging quads

- src/game/editor/editor.cpp
- src/game/editor/editor.h
Hopefully I'm not leaking any memory. Couldn't verify on macOS due to the lack of proper debugging tools.
> Implement brush saving. Fix #1111

- src/engine/shared/http.cpp
Maybe closing the file earlier could work?
> Try closing the file earlier. Fix #1250

- src/engine/client/client.cpp
- src/engine/engine.h
- src/engine/server/server.cpp
- src/engine/shared/engine.cpp
This might help with long DNS timeouts.
> Use two threads for the server thread pool

- src/base/system.c
- src/base/system.h
- src/engine/server.h
- src/engine/server/register.cpp
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/engine/shared/network_conn.cpp
- src/engine/shared/network_server.cpp
- src/game/server/ddracecommands.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
DNSBL is to prevent annoyances. There is no one to annoy on an empty server.
> Ignore DNSBL on "empty" servers.

- CMakeLists.txt
This reverts commit c1523d9fc3fc5c63f21c151d63fc056c5e949bbb.
Fixes #1352.
> Revert "CMakeLists.txt: Replace PythonInterp with Python"

- src/game/editor/editor.cpp
- src/game/editor/editor.h
Address #1331 and also fix the scrollbar enabling when there isn't enough elements.
> Editor fixes

- src/game/editor/editor.cpp
- src/game/editor/editor.h
Thought I'd do this one as well while looking at the editor code.
> Mark unused envelopes

- src/engine/shared/network_server.cpp
This specifically affects 0.6.5. Just treat them the same way as those
without any data.
> Don't ignore CONNECT packets with data that we don't know

- src/game/client/components/maplayers.cpp
- src/game/client/components/maplayers.h
Just notice, that it only makes sense, if i split the minimum for width and height.
For OGL3.3 only
> Border corner minimum fix

- src/game/editor/auto_map.cpp
- src/game/editor/auto_map.h
- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/io.cpp
- src/game/editor/layer_tiles.cpp
- src/game/editor/popups.cpp
- src/game/mapitems_ex.h
- src/game/mapitems_ex_types.h
Also, put automapping config selection seperatelly from the automapper button.
Also, add seed parameter to the automapper.
<sup>~~Marked as WIP since I would like to save the selected automapper config and seed (and whether it should run automatically) in the .map file, but I'm not sure how it would be best to handle that. Input welcome.~~</sup>
> Add option to automatically run the automapper

- scripts/hash_passwords.py
Thanks to @bojidar-bg for noticing
> Fix output for usernames with double quotes and semicolons

- src/engine/client/client.cpp
Apparently this isn't a perfect solution as consoles are devices on windows for some reason. Hopefully it'll work for most if not all users :)
> Fix the beep. Fixes #985

- src/engine/shared/network.cpp
- src/engine/shared/network.h
- src/engine/shared/network_client.cpp
- src/engine/shared/network_server.cpp
> Don't decompress packets from unknown IPs

- cmake/FindMySQL.cmake
> Add mariadb_config in FindMySQL.cmake

- CMakeLists.txt
> CMakeLists.txt: Let compiler tell its arch

- README.md
Not useful, add if you want. :)
> Add status for a couple of repositories to README.md

- src/engine/server/server.cpp
Causes annoying error messages during map change & server start.
> Don't try to remove non-existing files

- src/game/editor/editor.h
- src/game/editor/popups.cpp
> Disable unused tiles only for DDNet entities

- src/game/editor/editor.cpp
> Fix broken game layer picker

- src/base/system.c
- src/base/system.h
- src/engine/shared/config_variables.h
- src/test/str.cpp
> Fix remaining issues from #1443

- CMakeLists.txt
Would've solved the problem in teeworlds/teeworlds#2039 faster.
(cherry picked from commit fbdc6d69be1410ec06aa2ffb43699333e04ab100)
> Add a notification when files are not sorted in CMake

- src/base/system.c
- src/base/system.h
- src/engine/client/serverbrowser.cpp
- src/game/server/score/file_score.cpp
- src/test/str.cpp
> Don't use strtok. Close #1468

- src/engine/server/name_ban.cpp
- src/engine/server/name_ban.h
- src/engine/server/server.cpp
- src/test/name_ban.cpp
> Add exact name ban option

- src/engine/client/sound.cpp
Someone should check if this works on Windows.
> Don't allow sound format changes, use preferred driver, print more debug info

- src/game/editor/editor.cpp
Adjusts font size a bit and truncates text if it overflows
> Fit image name in select button

- src/game/version.h
I guess we have enough for a new release. Will release later or tomorrow if no one complains.
Anyone want to write a changelog for https://ddnet.tw/downloads/ ?
> Version 11.9

- src/game/editor/editor.cpp
Forgot that sounds are a thing..
> Fit sound name in select button too

- README.md
> Document build arguments in README.md

- src/game/ddracecommands.h
- src/game/server/ddracecommands.cpp
- src/game/server/gamecontext.h
> Add vote_unmute and display on it chat (Fixes #1376)

- src/game/client/components/menus.cpp
in serverbrowser's search and exclude fields
> Fix alignment of x inside button

- src/game/client/components/menus.cpp
Not sure if we want to do this kind of cleanup
> Remove useless comments

- src/game/client/components/menus.cpp
> Fix rendering of checkbox x

- src/base/system.c
- src/base/system.h
- src/engine/client/backend_sdl.cpp
- src/engine/server/server.cpp
- src/engine/shared/jobs.cpp
- src/game/editor/editor.cpp
- src/game/server/score/file_score.cpp
- src/game/server/score/sql_score.cpp
- src/test/thread.cpp
I probably didn't catch all interesting locations, but it's a start.
> More error checking in system.c (fixes #1317)

- src/game/server/gamecontext.cpp
It's counterintuitive, and hence way too risky
> Don't enforce own votes when moderating

- .circleci/config.yml
> Store artifacts from CircleCI

- src/game/client/components/chat.cpp
- src/game/client/components/chat.h
Disadvantage: Always autocompletes DDNet commands, even if you're not on a DDNet server.
Advantage: Quick and simple.
> Autocomplete chat commands (fixes #1504)

- src/game/editor/editor.cpp
- src/game/editor/layer_quads.cpp
- src/game/editor/layer_sounds.cpp
- src/game/editor/layer_tiles.cpp
And don't paste default names into the edit field
> Default layer names to the selected image/sound

- src/engine/client.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/game/client/components/menus_settings.cpp
- src/game/client/gameclient.cpp
> Move out common font loading into method

- src/game/server/ddracechat.cpp
- src/game/server/ddracechat.h
- src/game/server/gamecontext.h
Still not implemented for file based servers of course.
As reported by Bleidd64 on Discord.
> Command completion for /times, /points and /top5points

- src/game/mapitems.cpp
> Validate game layer hookthrough shortcut

- src/game/client/components/hud.cpp
- src/game/client/components/maplayers.cpp
- src/game/client/components/nameplates.cpp
- src/game/client/render.cpp
- src/game/editor/editor.cpp
Noticed that after some time groups with a parallax different than 100 were incorrectly rendered in the editor
> Make world offset calculation more accurate

- src/engine/shared/config_variables.h
> Enable gun sound by default

- src/engine/client/client.cpp
- src/engine/editor.h
- src/game/client/components/chat.cpp
- src/game/editor/editor.cpp
- src/game/editor/editor.h
Not sure if this is a good way to display this
> Notify about chat mentions in editor

- src/game/client/components/controls.cpp
- src/game/variables.h
> cl_mouse_min_distance as requested by Makoyuri

- CMakeLists.txt
- src/base/hash.c
- src/base/hash.h
- src/base/hash_bundled.c
- src/base/hash_ctxt.h
- src/base/hash_openssl.c
- src/engine/client/client.cpp
- src/engine/client/serverbrowser.cpp
- src/engine/external/md5/md5.c
- src/engine/external/md5/md5.h
- src/engine/server/authmanager.cpp
- src/engine/server/authmanager.h
- src/engine/server/server.cpp
- src/engine/shared/network_server.cpp
- src/engine/shared/uuid_manager.cpp
- src/test/hash.cpp
> Use OpenSSL md5 if it is available

- src/game/server/save.cpp
by using a switch-case with fallthroughs, seems like the perfect use case.
> Remove some code duplication in CSaveTee::LoadString

- src/engine/client/http.cpp
- src/engine/client/http.h
- src/engine/client/updater.cpp
- src/engine/client/updater.h
Not sure if I caught all locations
> Handle FS failures while updating (fixes #1560)

- src/game/client/components/console.cpp
Im sure im not the only one who keeps pressing ctrl-a and ctrl-e in the teewoods console and nothing happens .-.
> Add emacs style ctrl-a ctrl-e navigation

- src/game/version.h
Will wait for:
- Enable dragging demo file into client to play it directly
- Explain game tiles and entities in editor (fixes #1600)
- Console command "color_from_rgb" (fixes #1581)
> Version 12.1

- src/game/server/score/file_score.cpp
It's written using STL strings and files intead of using system. Didn't change any of that because of the risk of breaking something unintentionally.
> Minor CFileScore improvements

- src/game/editor/editor.h
- src/game/editor/layer_tiles.cpp
> Fix non destructive drawing with hookthrough shortcut

- CMakeLists.txt
- src/engine/client/backend_sdl.cpp
- src/engine/client/client.cpp
- src/engine/client/graphics_threaded.cpp
- src/engine/client/http.cpp
- src/engine/client/text.cpp
- src/engine/server/server.cpp
- src/engine/shared/compression.cpp
- src/engine/shared/datafile.cpp
- src/engine/shared/jobs.h
- src/engine/shared/network_server.cpp
- src/engine/shared/snapshot.cpp
- src/game/client/components/background.cpp
- src/game/client/components/console.cpp
- src/game/client/components/mapimages.cpp
- src/game/client/components/maplayers.cpp
- src/game/client/components/maplayers.h
- src/game/client/components/menus_demo.cpp
- src/game/client/components/players.cpp
- src/game/client/components/scoreboard.cpp
- src/game/client/components/spectator.cpp
- src/game/client/lineinput.cpp
- src/game/editor/editor.cpp
- src/game/editor/popups.cpp
- src/game/server/score/sql_score.cpp
It's not supported in C and we only checked using a C compiler.
> Actually enable -Wuseless-cast

- src/game/server/ddracecommands.cpp
- src/game/server/gamecontext.h
Fix enum name for VOTE_MUTES break out earlier in mutes loop. And using goto to make the code more readable o.O
> Refactor mute and vote mute code

- src/base/system.c
- src/base/system.h
- src/game/client/components/statboard.cpp
- src/test/str.cpp
Some cleaning up, wasn't really insecure but at least this is more readable.
Reported by noby on Discord
> Clean statboard chat parsing a bit

- src/game/client/components/menus_demo.cpp
As reported here: https://forum.ddnet.tw/viewtopic.php?f=3&p=67807#p67807
> Disable demo shortcuts in console

- src/game/client/prediction/entities/character.cpp
- src/game/client/prediction/gameworld.cpp
Also removed the code in #1620 related to the ddnetcharacter freeze flags that will no longer be used.
> Fix #1668 and remove some code

- src/game/client/components/players.cpp
- src/game/client/gameclient.cpp
- src/game/gamecore.cpp
- src/game/server/ddracecommands.cpp
- src/game/server/entities/character.cpp
Fixed super prediction.
Fixed solo being weird when antiping is on.
Make the server-side character cores know about their character status.
> Use the DDNet Network Character

- datasrc/network.py
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/gamecore.cpp
- src/game/gamecore.h
- src/game/server/entities/character.cpp
I used -1 for deep frozen, and 0 for not frozen. Not really sure if this is the best way.
> Use freeze end tick instead of a flag. Fix #1659

- src/game/client/components/scoreboard.cpp
> Highlight same clan as dummy too

- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/gamecontroller.cpp
- src/game/server/gamecontroller.h
Removed vanilla code from gamecontext and gamecontroller. I didn't search for the code all over the place I just remember seing it there a lot. Also removed some empty lines. Wanted to do this for a long time :)
thought there is an reason it is there. But we have git and the vanilla repo so I don't see any point keeping it there.
> Remove unused vanilla code (closed #1658)

- CMakeLists.txt
- src/base/color.h
- src/base/math.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/game/client/components/effects.cpp
- src/game/client/components/ghost.cpp
- src/game/client/components/menus.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/components/players.cpp
- src/game/client/components/players.h
- src/game/client/components/scoreboard.cpp
- src/game/client/components/skins.cpp
- src/game/client/components/skins.h
- src/game/client/components/spectator.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/client/render.cpp
- src/game/client/render.h
- src/test/color.cpp
There were color functions everywhere, I tried cleaning it up a little. I still couldn't get the roundtrip from Hsl to Rgb to be exactly the same, but I think this is the best possible.
> Try working on colors a bit

- src/game/client/components/binds.cpp
- src/game/client/components/binds.h
- src/game/client/components/hud.cpp
- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_settings.cpp
- src/game/client/gameclient.cpp
- src/test/str.cpp
> Work on compound binds

- src/game/editor/layer_tiles.cpp
As reported by BannZay on Discord
> Fix FillSelection with no selected brush

- src/engine/server/server.cpp
> Persist show_ips setting on map changes

- src/game/server/gamecontext.cpp
Should help relieve some of the issues reported on discord.
> Don't check dnsbl when alone

- datasrc/network.py
- src/game/server/entities/character.cpp
- src/game/server/entities/character.h
- src/game/server/gameworld.cpp
Looked through character/core and tried to add those of the remaining variables that would be useful to have (as suggested in #1659). This adds flags for available weapons, strong/weak id, number of jumps, and the currently active tele checkpoint (which would be needed for tele prediction when/if it is added).
> Add some more fields to ddnetcharacter

- src/base/system.c
- src/game/client/components/menus.cpp
- src/test/str.cpp
Can't handle empty lines right now
> Render news without STL functions

- src/game/client/components/menus_settings.cpp
How this worked during testing is beyond me, maybe the debug build?
> UI ID's need to be unique

- src/game/client/components/menus_demo.cpp
> Show the correct button when paused

- src/engine/client/serverbrowser.cpp
Otherwise this filters all maps in all other tabs
> Explicitly filter finished maps

- src/engine/client/text.cpp
- src/game/client/components/mapimages.cpp
> fix crash on fontsize equal zero

- src/game/client/components/binds.cpp
The debug bind caused stroked binds to get stuck, this seems to fix it, needs more testing though.
Reported by `@Schulzer` on discord
> Fix sticky binds

- src/game/client/components/players.cpp
- src/game/client/components/players.h
I think this looks correct, but it'd be nice if one more person can take a look.
> Consistently determine OtherTeam

- src/engine/client/client.cpp
- src/engine/shared/serverbrowser.cpp
- src/game/client/components/camera.cpp
- src/game/client/components/emoticon.cpp
- src/game/client/components/items.cpp
- src/game/client/prediction/entities/projectile.cpp
- src/game/extrainfo.cpp
- src/game/extrainfo.h
fixes a few things that got broken for players using ddnet client in blockworlds
> fix particles, emote wheel, zoom and score for blockworlds

- src/engine/client/client.cpp
- src/game/client/components/items.cpp
- src/game/client/prediction/entities/projectile.cpp
- src/game/extrainfo.cpp
- src/game/extrainfo.h
Turns out this is right but with a catch, faster than vanilla projectiles get messed up.
@trml would you like to move the extrainfo bit up higher while at it?
> Rerevert #1187

- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/score.h
- src/game/server/score/file_score.cpp
- src/game/server/score/file_score.h
- src/game/server/score/sql_score.cpp
- src/game/server/score/sql_score.h
Revert this "once we get proper SQL code"™.
> Hack around the race condition in random maps selection

- src/game/client/components/console.cpp
- src/game/client/lineinput.cpp
- src/game/client/lineinput.h
Extends shortcuts from:
https://github.com/ddnet/ddnet/commit/e9f8bd42b7dd6d6b2553c19d785b1bf6f71a455a
> Add ctrl-u delete in client console

- src/game/client/components/players.cpp
- src/game/client/gameclient.cpp
Fixes #1758
- Made a rly small optimization.
- Fixed the bug from the issue.
> Fix hook col

- src/engine/server/server.cpp
- src/engine/server/server.h
- src/engine/shared/config_variables.h
- src/engine/shared/network.h
- src/engine/shared/network_server.cpp
Clean up code a bit, also allow larger values
> sv_server_info_per_second, sv_van_conn_per_second: allow 0 to disable

- src/game/version.h
I'd still like to get https://github.com/ddnet/ddnet/pull/1772 and https://github.com/ddnet/ddnet/pull/1781 in first.
> Version 12.5

- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/client/prediction/gameworld.cpp
- src/game/client/prediction/gameworld.h
Also a couple of other small fixes related to laser.
> Fix laser/shotgun prediction on solo servers

- src/game/client/components/console.cpp
- src/game/client/lineinput.cpp
- src/game/client/lineinput.h
Extends shortcuts from:
ed8a0b5eee8ed86ba53021e1799a3c40973f192c
e9f8bd42b7dd6d6b2553c19d785b1bf6f71a455a
> Add ctrl-k delete in client console

- src/base/color.h
- src/engine/shared/console.cpp
- src/game/client/components/menus_settings.cpp
> Fix toggle not working with colors

- src/game/client/components/effects.cpp
- src/game/client/components/effects.h
- src/game/client/components/items.cpp
- src/game/client/components/nameplates.cpp
- src/game/client/components/players.cpp
- src/game/client/components/players.h
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
Also moved IsOtherTeam to CGameClient, and used it to clean up nameplates.cpp a little.
> Apply ShowOthersAlpha to projectiles (fix #1595)

- src/game/client/components/camera.cpp
I forgot about the dyncam option, #1636.
> fix-ClDyncamMinDistance camera spawn

- src/engine/server/server.cpp
I think this is also fine for vanilla, but I can't get the vanilla client to work on mac to test it.
> Don't advertise the reserved slots. Fix #1808

- src/game/version.h
Blocked until @fokkonaut gets his change in.
> Version 12.6

- src/game/client/gameclient.cpp
> Reset m_Afk

- src/game/client/gameclient.cpp
> Fix skin reset

- src/base/math.h
- src/game/editor/editor.cpp
- src/game/editor/editor.h
Fix 1 bug, improve usability of angle selector.
> Editor speedup fixes

- src/engine/shared/config_variables.h
> Remove space at end of cfg description

- src/game/client/components/menus_settings.cpp
> Add show text entities button to settings

- src/game/client/components/scoreboard.cpp
I wasn't even sure if we should fix this tbh, but might aswell have the discussion here.
> Clamp ping to 999. Fix #1651

- src/game/server/entities/projectile.cpp
- src/game/server/entities/projectile.h
Just by looking at the code I think this is what was intended but only testing can make sure.
> Explode grenades twice at the end if they have lifespans. Fix #1559

- src/game/client/prediction/gameworld.cpp
- src/game/server/gameworld.cpp
This makes hitting yourself when shooting through other tees work
> Fix IntersectCharacter

- src/game/client/components/maplayers.cpp
I think this problem is solved, but this may be a little hack, I don't know the effect of this if-else condition.
> repair the problem that class selector appear when demo playing

- src/game/client/components/camera.cpp
I don't know if this makes it faster, probably not even noticable, but i like it more this way.
> Remove for loop in camera

- src/engine/client/serverbrowser.cpp
Servers under attack appear to be empty
> change filter logic

- src/engine/server.h
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/game/server/gamecontext.cpp
I'm not sure I like it but it works
> Cache serverinfo responses

- src/game/server/score/sql_score.cpp
also don't write out non-eligible records.
> Write out sql server prefix to failed_sql.sql

- src/base/vmath.h
- src/game/client/prediction/gameworld.cpp
- src/game/server/gameworld.cpp
for mapping stationary bullets
As requested by Im 'corneum.
> Support shotgun_speed 0

- CMakeLists.txt
- src/tools/map_convert_07.cpp
Fixes https://github.com/ddnet/ddnet7/issues/20
> Add map_convert_07 tool

- src/engine/shared/console.cpp
- src/game/client/components/menus_settings.cpp
After changing either of background colors in ddnet tab in settings and reopening the client, both become white.
> Fix: background colors being set to white

- src/engine/client/client.cpp
- src/engine/demo.h
- src/engine/shared/demo.cpp
- src/engine/shared/demo.h
- src/game/client/components/menus.h
- src/game/client/components/menus_demo.cpp
~~I think we should also store the SHA256 in the demo, but I'm not sure how to upgrade the demo format.~~
I also stored the SHA256 in the demo, but is this the right way to do it?
I smell endianness issues.
> Always try extracting map before fail. Fix #1886

- src/game/version.h
Waiting for https://github.com/ddnet/ddnet/pull/1998 and https://github.com/ddnet/ddnet/pull/1939
> Version 12.8

- src/engine/client/client.cpp
- src/engine/server/server.cpp
- src/engine/shared/demo.cpp
- src/engine/shared/demo.h
Since no one else was willing to fix it, I whipped up a quick patch. This isn't the correct way to do this though. We should probably add a function in storage to search for maps, so that things can't end up out of sync ever again.
> Fix demo bug

- scripts/generate_fake_curl.py
> Eliminate static libcurl dependency, second try

- src/game/editor/layer_tiles.cpp
> Modify envelope index when appending maps

- src/game/editor/editor.cpp
- src/game/editor/layer_tiles.cpp
- src/game/editor/popups.cpp
A dropdown would've worked better, but we don't have one
> Display envelope name in popups

- src/base/system.c
- src/base/system.h
- src/engine/client/client.cpp
- src/engine/server/server.cpp
> Strip spaces in browser (server name)

- src/base/system.c
- src/base/system.h
- src/game/server/ddracechat.cpp
src/game/server/ddracechat.cpp:623:39: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
> Fix GCC 9.2.0 compilation

- src/game/ddracecommands.h
- src/game/server/ddracecommands.cpp
- src/game/server/gamecontext.h
- src/game/server/save.cpp
- src/game/server/save.h
- src/game/server/score/sql_score.cpp
I'm not sure how much I like this but it should be helpful
> Implement dry saves

- .gitignore
- CMakeLists.txt
- src/antibot/antibot_data.h
- src/antibot/antibot_interface.h
- src/antibot/antibot_null.cpp
- src/game/collision.cpp
- src/game/collision.h
- src/game/server/antibot.cpp
- src/game/server/antibot.h
- src/game/server/ddracecommands.cpp
- src/game/server/entities/character.cpp
- src/game/server/entities/character.h
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/player.cpp
Support for this feature is turned off by default. This feature allows
to integrate with noby's anticheat feature.
> Add support for dynamically loading an antibot module

- src/engine/client/backend_sdl.cpp
- src/engine/client/http.cpp
- src/engine/client/text.cpp
Helped me a lot trying to debug some linking issues on macOS and I think it'll also be helpful to people that encounter weird errors like that one libcurl bug we couldn't figure out.
> Output library versions

- src/base/tl/algorithm.h
- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/layer_tiles.cpp
- src/game/editor/popups.cpp
> Allow editing multiple tile layer props

- src/game/client/components/hud.cpp
- src/game/client/components/hud.h
Shows best time of either dummy or main player depending on which is selected
> Fix cl_showrecord with dummy (fixes #2077)

- src/game/client/components/spectator.cpp
sry for the general refactor along with it xD
> Add spectate_closest now works when in Free-View

- src/game/version.h
I guess it's time for a new version even if we don't have any large
changes
> Version 13.0

- CMakeLists.txt
> Try to fix SDL2 hidapi rpath on MacOSX

- CMakeLists.txt
- src/engine/client/backend_sdl.cpp
> Drop glu dependency

- src/engine/client/client.cpp
Caused by https://github.com/ddnet/ddnet/pull/2119/
> Fix division by 0 (fixes #2131)

- .github/workflows/build.yaml
- bors.toml
> Don't fail bors on macOS CI

- src/engine/client/text.cpp
```
Jupstar ✪Today at 12:37
@Ryozuki your fixes in text.cpp create a infinite loop e.g. in the tee setting page
if(!Character)
break;
line 924
RyozukiToday at 12:46
oh
@Jupstar ✪ should i just remove that check?
Jupstar ✪Today at 12:50
well for now yes, that whole function is a big mess, so u probs would need to understand everything so it works correctly without the memory leak xD
```
> prevent endless loop

- cmake/FindNotify.cmake
Especially when only building server and not client
> Don't require notify on Linux

- src/game/server/save.cpp
As reported by Konsti, thanks to heinrich5991 for remembering #2086
> Don't load m_Ammo to fix loads (following #2086)

- src/game/server/score/sql_score.cpp
- src/game/server/score/sql_score.h
Just like for the kill message when in locked team, this just says to the team who initiated the save or the load.
Could not test it as i don't have SQL installed.
> Print name of requester when saving or loading team

- src/game/editor/io.cpp
write automapper version, was not initialized
> write automapper version, was not initialized

- src/game/client/prediction/entities/character.cpp
Just took the same code that we have on server side already
> Fix crash in prediction when touching switch tile with number 0 (fixes #2182)

- src/game/version.h
Waiting for: ~https://github.com/ddnet/ddnet/pull/2212~ ~https://github.com/ddnet/ddnet/pull/2202~ ~https://github.com/ddnet/ddnet/pull/2204~
> Version 13.2

- other/ddnet.appdata.xml
This PR just adds new version into the appdata manifest.
> Appdata: add new version

- src/game/server/ddracechat.cpp
- src/game/server/entities/character.cpp
- src/game/server/entities/character.h
- src/game/server/teams.cpp
- src/game/variables.h
Thanks to NANAMAR for report.
Update: tested, works.
> Practice mode fixes & improvements

- src/game/editor/layer_quads.cpp
- src/game/editor/layer_sounds.cpp
- src/game/editor/layer_tiles.cpp
Follow-up to https://github.com/ddnet/ddnet/pull/2186 by @BannZay 
Thanks to Cøke for notifying me
> Fix image/sound selection in editor

- other/ddnet.appdata.xml
- src/game/version.h
Waiting for https://github.com/ddnet/ddnet/pull/2226
> Version 13.2.1

- src/game/client/components/nameplates.cpp
- src/game/variables.h
> add cl_nameplates_ids

- src/game/tuning.h
These are only used in the client for prediction.
> Mark unused tunes as such

- src/game/client/prediction/entities/character.cpp
> Reset hook & collision in prediction after kill

- src/game/client/components/mapsounds.cpp
> Stop playing map sound when demo player is paused

- src/base/color.h
- src/engine/shared/console.cpp
- src/engine/shared/console.h
- src/game/client/components/effects.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/components/skins.h
- src/game/client/gameclient.cpp
- src/game/server/teeinfo.cpp
- src/game/server/teeinfo.h
This stateful color has been bothering me for a while. I tested this and it doesn't seem to break the colors but to avoid a repeat of the last time I'd appreciate it if a couple more brave souls try this.
> Remove ugly color hack

- src/engine/server/server.cpp
- src/engine/server/server.h
Preliminary testing suggests this works fine. Albeit it is not the prettiest thing ever.
> Sixup needs it's own maps

- src/base/system.c
- src/base/system.h
- src/game/client/components/menus.cpp
> Add Learn button which opens the ddnet wiki in the browser.

- src/game/server/gamecontext.cpp
Never assume how structures are laid out
> Fix votes called from 0.7

- src/game/server/player.cpp
- src/game/server/score/sql_score.cpp
- src/game/server/score/sql_score.h
and some small style and readability fixes in sql_score.
> Make PlayerResult messages an union variant

- src/base/system.c
> Open links in background (fixes #2292)

- src/game/client/components/menus.cpp
> Make the learn button fit (fixes #2293)

- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/player.cpp
- src/game/server/player.h
- src/game/server/score/sql_score.cpp
- src/game/server/score/sql_score.h
> Fix crash when player voting random_map leaves and vote passes

- src/engine/server/sql_string_helpers.h
- src/engine/shared/json.cpp
- src/game/server/save.cpp
error: ‘strcmp’ was not declared in this scope
> Use str_comp instead of strcmp

- src/game/server/ddracechat.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/player.cpp
- src/game/server/player.h
- src/game/server/teams.cpp
Mostly tested, couldn't test the diffs though as I don't have score set up. It looks good to me though.
> Use the 0.7 race features better

- src/game/editor/editor.cpp
instead of just in the layers view
> Make ctrl-s/ctrl-l etc work everywhere in editor (fixes #2302)

- src/tools/map_extract.cpp
> map_extract: Only access map info if it exists

- CMakeLists.txt
- src/engine/shared/csv.cpp
- src/engine/shared/csv.h
- src/game/client/components/chat.cpp
- src/game/client/components/chat.h
- src/test/csv.cpp
> Use proper CSV writing for save codes

- src/game/client/components/players.cpp
fixes https://github.com/ddnet/ddnet/issues/2341
> fix saying /spec show you as chatting

- src/game/server/score/sql_score.cpp
> Don't fail on empty teamtop5

- src/engine/shared/config_variables.h
after switching to non-videorecorder client
> Don't forget video recorder fps setting

- src/game/server/teams.cpp
- src/game/server/teams.h
- src/game/teamscore.cpp
- src/game/teamscore.h
> Keeping multiple states consistent is hard (fixes #2315)

- src/game/server/gamecontext.cpp
This felt a little verbose, but I couldn't really come up with any better. Maybe someone more crafty can figure out a cleaner way.
> Name change hack for 0.7. Close #2330

- src/game/server/gamecontext.cpp
> Ugly fix for SendChatTarget(-1...).

- other/ddnet.appdata.xml
- src/game/version.h
Waiting for https://github.com/ddnet/ddnet/pull/2303 https://github.com/ddnet/ddnet/pull/2301 https://github.com/ddnet/ddnet/pull/2296 https://github.com/ddnet/ddnet/pull/2295 https://github.com/ddnet/ddnet/pull/2294 https://github.com/ddnet/ddnet/pull/2280 https://github.com/ddnet/ddnet/pull/2279 https://github.com/ddnet/ddnet/pull/2242 and probably some sixup fixes by Learath2 :)
> Version 14.0

- datasrc/network.py
- src/game/client/components/nameplates.cpp
- src/game/client/components/players.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/server/player.cpp
Fixes https://github.com/ddnet/ddnet/issues/2344
> Fix /spec rendering

- datasrc/network.py
- src/game/client/components/ghost.cpp
- src/game/client/components/players.cpp
- src/game/client/components/players.h
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/server/player.cpp
Fixes https://github.com/ddnet/ddnet/issues/2360
> Fix /spec hook and moving SpecTees

- CMakeLists.txt
- src/engine/shared/config_variables.h
- src/game/server/ddracechat.cpp
- src/game/server/ddracecommands.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/gamemodes/DDRace.cpp
- src/game/server/gamemodes/DDRace.h
- src/game/server/player.cpp
- src/game/server/player.h
- src/game/server/score.cpp
- src/game/server/score.h
- src/game/server/score/file_score.cpp
- src/game/server/score/file_score.h
- src/game/server/score/sql_score.cpp
- src/game/server/score/sql_score.h
- src/game/server/teams.cpp
- src/game/server/teams.h
Behavior change:
* `sv_save_worse_scores` is respected on file based servers
Mainly a clean up after #2247, but helps #2298 too
> Make game less dependend on score backend

- other/ddnet.appdata.xml
- src/game/version.h
Waiting for #2363, #2358, #2356, #2331
> Learath2: Can you also wait for me to take a look at the spec char patch, I don't think we have to send all this extra state
> Version 14.0.1

- src/game/client/components/controls.cpp
@Learath2 you were the last to change this, would be nice if you could check if this is correct behaviour, i didn't find anything wrong :D
> Fix min mouse position for follow factor

- src/game/client/components/menus.h
- src/game/client/components/menus_settings.cpp
Tadaa, new feature in -200 lines :D
> Color Selector improvement + cleanup

- src/engine/client/text.cpp
- src/game/client/components/mapimages.cpp
Since we're not doing anything about them anyway, and I get them
spamming me on every client start.
> Get rid of the annoying font size warnings

- src/game/server/teams.h
Thanks to Lady Saavik for report
> Super team can't be saved/loaded

- src/base/system.c
- src/game/prng.cpp
- src/game/server/ddracecommands.cpp
It's not supported in MSVS. Fix #2407.
> Don't use %ll format

- datasrc/network.py
- src/game/client/gameclient.cpp
- src/game/client/render.cpp
- src/game/client/render.h
- src/game/server/entities/character.cpp
- src/game/server/gamecontext.cpp
- src/game/server/player.cpp
- src/game/server/player.h
and server adapts the visible distance to it
> Client tells server its zoom level (fixes #2087)

- src/game/client/components/nameplates.cpp
- src/game/client/components/players.cpp
- src/game/server/player.cpp
Fixes https://github.com/ddnet/ddnet/issues/2410
I also made it use the Alpha on specchars that are on another team.
> Fix showothers for specchar

- src/engine/server/server.cpp
- src/game/server/gamecontext.cpp
> Only SendChat to clients that exist. Initialize m_Sixup anyway

- datasrc/seven/compile.py
> Address C++14 defect(CWG1558)

- other/ddnet.appdata.xml
- src/game/version.h
> Version 14.1

- src/game/server/save.cpp
- src/game/server/save.h
Solves issue discussed in #2374. Also keeps direction and jump, which is evaluated when player is in /pause. Fire could be deleted, as it does not affect game play in any way.
>  Keep hook when loading 

- src/game/server/teams.cpp
> Fix reenabling practice mode after kill on solo server

- src/game/server/save.cpp
> Fix erroneous "unable to find all characters" message

- src/game/teamscore.cpp
- src/game/teamscore.h
> Moved include from teamscore.h to teamscore.cpp

- data/languages/spanish.txt
Translated from line 658 to line 1199. Finished what was left to translate in Spanish.
> Finished what was left to translate in Spanish

- data/languages/polish.txt
Fix1: Finished the last two missing translations.
Fix2: Fixed 1 empty translation.
> Update polish 07/07/20

- data/languages/spanish.txt
Little changes.
Fix1: Line 866 (V instead of v)
Fix2: Line 869 (O instead of o)
Fix3: Line 1190 ("Agarrar")
Fix4: Line 423 ("Apariencia" instead of HUD)
Fix5: Line 252 ("Mensaje del día" instead of MOTD)
> Update spanish 07/07/20

- data/languages/polish.txt
This reverts commit 8940b817774d2ed80c2845f42bd0ca2997236b4f.
> Revert "Update polish 07/07/20"

- src/game/client/components/camera.cpp
- src/game/variables.h
as requested on Discord by nils & fokkonaut
> Add cl_smooth_zoom_time

- src/game/server/player.cpp
> Set smaller default area for what distance to show

- autoexec_server.cfg
- src/engine/server/server.cpp
- src/engine/shared/config_variables.h
Same as https://github.com/ddnet/ddnet/pull/2419 but rebased so that you can actually look at the diff. @MikiGamer
> Find available port by MikiGamer

- src/base/hash_ctxt.h
- src/base/hash_libtomcrypt.c
- src/base/system.c
- src/engine/client/sound.cpp
- src/engine/client/video.cpp
- src/engine/client/video.h
- src/game/client/prediction/entities/projectile.cpp
- src/game/client/prediction/gameworld.cpp
- src/game/client/prediction/gameworld.h
- src/game/server/entities/character.cpp
- src/game/server/entities/laser.cpp
- src/game/server/entities/projectile.cpp
- src/game/server/eventhandler.cpp
- src/game/server/eventhandler.h
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/gamecontroller.h
- src/game/server/teams.cpp
- src/game/server/teams.h
src/game/client/prediction/gameworld.h:62:90: error: ‘int64_t’ has not been declared
62 |  void CreateExplosion(vec2 Pos, int Owner, int Weapon, bool NoDamage, int ActivatedTeam, int64_t Mask);
|                                                                                          ^~~~~~~
> Use (u)int64 from system.h instead of (u)int64_t from cstdint

- data/languages/dutch.txt
- data/languages/french.txt
- data/languages/hungarian.txt
- data/languages/persian.txt
Not sure if the missing empty lines inbetween matter, can fix later.
> Persian update by Quick

- src/engine/server/server.cpp
For legacy we sent the first packet once correctly, then the 2nd and 3rd
packet without the marker and token at the start, so they never worked.
For new 64 player serverinfo we sent all packets correctly but the 1st
packet twice.
Introduced in #1955.
> Fix legacy 64 player serverinfo, don't send duplicate packets (fixes #2495)

- src/game/server/ddracechat.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/player.cpp
I think this looks sane but I haven't tested it at all for idk how to even test this locally/alone
> Fix votes for sixup

- src/engine/client/text.cpp
- src/engine/textrender.h
- src/game/client/components/chat.cpp
- src/game/client/components/console.cpp
- src/game/client/components/debughud.cpp
- src/game/client/components/hud.cpp
- src/game/client/components/killmessages.cpp
- src/game/client/components/menus.cpp
- src/game/client/components/menus_browser.cpp
- src/game/client/components/menus_demo.cpp
- src/game/client/components/menus_ingame.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/components/motd.cpp
- src/game/client/components/nameplates.cpp
- src/game/client/components/scoreboard.cpp
- src/game/client/components/spectator.cpp
- src/game/client/components/statboard.cpp
- src/game/client/render_map.cpp
- src/game/client/ui.cpp
- src/game/editor/editor.cpp
- src/game/editor/layer_tiles.cpp
https://github.com/teeworlds/teeworlds/commit/1ca020ea195b079bcc26aee28774eb79bada9e87
https://github.com/teeworlds/teeworlds/commit/912442347daab055e007e40cbe38cf89ed8ce682
The first one fixes a stack-buffer-overflow in some UIs (closes #2511), the second one is just for consistent typing.
> Port some text.cpp fixes

- src/game/server/entities/character.cpp
I've restructured the code to make it easier to read.
There are two differences in it's behavior:
1. Hook sounds coming from sixup players are now only muted for the player themselves (using a mask) instead of being muted for everyone. This fixes at least one cause for #2508.
2. Mask for `COREEVENT_GROUND_JUMP` is now using `Asker` parameter to `TeamMask()`. I believe it was originally an oversight that this mask was different from the others. But the difference is barely noticeable: one case is when spectating a Tee that is in a solo part. Previously such Tee wouldn't be making ground jumping sounds.
https://github.com/ddnet/ddnet/blob/7e610f994428e5afeb77013ddbd725a4a8b3896b/src/game/server/teams.cpp#L405-L418
I've tested this with DDNet and Vanilla (0.7) clients.
> Fix sixup players not making sounds when hooking others

- src/engine/client/client.cpp
- src/engine/client/client.h
> Client: Support .map file drag-and-drop to open map in editor

- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
This looks like it works but I can't test it that well locally
> Fix more sixup vote issues

- src/game/client/components/menus_settings.cpp
> Add Client message color option in HUD setting

- other/ddnet.appdata.xml
- src/game/server/ddracechat.cpp
- src/game/version.h
Waiting for:
https://github.com/ddnet/ddnet/pull/2543
https://github.com/ddnet/ddnet/pull/2541
https://github.com/ddnet/ddnet/pull/2538
https://github.com/ddnet/ddnet/pull/2536
https://github.com/ddnet/ddnet/pull/2465
> Version 14.3

- CMakeLists.txt
- cmake/FindSQLite3.cmake
> Fix bundling SQLite3 on Mac

- data/languages/simplified_chinese.txt
- data/languages/traditional_chinese.txt
found some problems with chinese translation
> Pr chinese translation

- src/game/editor/editor.cpp
> Editor: Fix Left/right arrow keys when editing text

- src/game/server/score.cpp
> Fix team rank not updating after SQLite update

- src/game/client/components/controls.cpp
- src/game/client/components/controls.h
> Add +resetdummy

- src/game/server/save.cpp
- src/game/server/save.h
- src/game/server/teams.cpp
Fixes #2529  by reverting to the old /load mechanic.
> Allow switching weak/strong with saving and loading

- src/game/editor/editor.cpp
[valgrind2.txt](https://github.com/ddnet/ddnet/files/5081447/valgrind2.txt)
Still some more leaks left but mostly unrelated to map editor.
> Fix leak when loading map in editor (fixes #2573)

- src/game/collision.cpp
since it won't add up to anything anyway.
Hopefully doesn't break any physics.
> Optimization: Don't calculate with too small fraction

- other/ddnet.appdata.xml
- src/game/version.h
Waiting for: 
- https://github.com/ddnet/ddnet/pull/2582
- https://github.com/ddnet/ddnet/pull/2581
- https://github.com/ddnet/ddnet/pull/2579
- https://github.com/ddnet/ddnet/pull/2566
> Version 14.3.3

- other/ddnet.appdata.xml
- src/game/version.h
> Version 14.4

- src/base/math.h
Made math functions constexpr to allow some calculations to be performed in compile-time.
> Added constexpr to math functions

- src/game/variables.h
As voted in Discord, suggested by Lady Saavik
> Enable "Switch weapon on pickup" by default

- CMakeLists.txt
- src/base/dynamic.h
- src/engine/client.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/engine/client/steam.cpp
- src/engine/shared/config_variables.h
- src/engine/steam.h
- src/game/client/components/ghost.cpp
- src/game/client/components/menus.cpp
- src/game/client/components/menus_ingame.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/components/race_demo.cpp
- src/game/client/gameclient.cpp
- src/game/variables.h
- src/steam/steam_api_flat.h
- src/steam/steam_api_stub.cpp
> Use player name from the Steam API as fallback

- src/engine/client/updater.cpp
Since we now ship our first shared lib on Linux, libsteam_api.so
> Support Linux shared libs in autoupdater

- src/game/client/components/background.cpp
- src/game/client/components/mapimages.cpp
- src/game/client/components/mapimages.h
As reported.
Tested all possible contexts, hope this is right now
> Fix background map loading

- src/engine/client/client.cpp
Use alt-f4 or whatever your window manager wants instead.
> Remove panic quit button

- src/engine/client/backend_sdl.cpp
@Learath2 @thomasjahoda Could you test this with the build artifacts from Github builds, by putting the DDNet.exe into steam directory and launching DDNet from Steam?
> Try to fix input in Steam version on Windows (fixes #2645)

- src/game/server/gamecontext.cpp
Seems no one is willing to test this with me, it's rather safe though.
> Missed a vote case

- src/game/client/components/console.cpp
- src/game/client/components/menus.cpp
> Fix mouse interaction when game console is open

- src/game/editor/popups.cpp
> Fix map details layout

- src/game/client/components/menus_browser.cpp
Should have been in #2713. Late but handy change tho
> Refresh on ping filter changed

- src/engine/client/backend_sdl.cpp
This fixes compilation on Debian Stretch
> add #ifdef checks around GLEW_VERSION checking

- src/game/server/gamecontext.cpp
As reported by Dan_cao. Will provide client fixes too.
> Inform client about failure to join because of invalid utf8

- src/engine/client/text.cpp
- src/engine/textrender.h
> Fix Word Wrapping for Unicode Strings

- src/engine/client/backend_sdl.cpp
- src/engine/client/backend_sdl.h
> Fix texture destroy

- src/engine/server/server.cpp
Easier than expected, I wonder why I didn't do this at the start.
> Let 0.7 clients fastdownload too

- src/engine/shared/config_variables.h
Is there a reason not todo it?
The players, that want this enable it anyway
> Save cl_overlay_entities

- src/game/client/components/menus.cpp
Was accidentally removed in b1e98b598b390a02dcdec2e85553280463a5d893
> Add message popup again

- src/engine/client/backend_sdl.cpp
- src/engine/client/backend_sdl.h
- src/engine/shared/config_variables.h
If even that fails, I'm out of ideas
Checks all texture shaders, checks all functions used.
> More aggressive analysis & check 2.0 gl Functions that were used

- src/game/client/components/menus_ingame.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
Since they're running an old version of DDNet server
> Can't detect if paused on KoG, so don't show button

- src/engine/client/client.cpp
- src/engine/client/client.h
- src/engine/client/steam.cpp
- src/engine/steam.h
- src/steam/steam_api_flat.h
- src/steam/steam_api_stub.cpp
> Allow joining and inviting others via Steam friend list

- CMakeLists.txt
- cmake/FindFFMPEG.cmake
- src/engine/client/video.cpp
@heinrich5991 Maybe you want to take a look already?
> Bundle FFmpeg for everything

- src/game/server/score.cpp
Worst case seems to be same performance, best case 3 ms instead of 3 s previously
> Improve performance of /points

- CMakeLists.txt
Should make the build reproducible.
> Don't insert timestamps into PEs with MinGW

- src/game/client/components/menus.cpp
- src/game/client/components/menus_demo.cpp
> Fix some 5:4 rendering in demo menu & recorder menu

- README.md
as noticed by Андрей Рудой on Discord
> Put dependencies before installation instructions in README

- .clang-format
- .github/workflows/style.yml
- scripts/fix_style.py
This will help me not getting annoyed about code style.
> Add .clang-format; require it for pull requests

- src/engine/server/databases/connection.h
- src/engine/server/databases/mysql.cpp
- src/engine/server/databases/mysql.h
- src/engine/server/databases/sqlite.cpp
- src/engine/server/databases/sqlite.h
- src/game/server/score.cpp
This prints SQLite statements to the console. I tried to expand MySQL statements with the SQLite function as well, but this didn't work since it isn't valid SQLite syntax.
> Print sqlite statements

- src/game/client/components/skins.cpp
- src/game/client/components/skins.h
Small optimization but it could start mattering with #2733
> Don't search the sorted array linearly

- src/engine/client/graphics_threaded.cpp
- src/engine/client/graphics_threaded.h
- src/engine/graphics.h
- src/game/client/components/mapimages.cpp
- src/game/client/components/mapimages.h
- src/game/client/components/maplayers.cpp
- src/game/editor/layer_tiles.cpp
- src/game/mapitems.cpp
- src/game/mapitems.h
Thanks to @Jupeyy for the original pull request.
> Style-fixed version of #2784

- src/tools/config_common.h
Work on topmost directory only
> Allow to use config_retrieve on whole directory

- src/engine/client/text.cpp
- src/engine/textrender.h
- src/game/client/components/mapimages.cpp
fixes #2822
@BannZay wanna check?
> Fix entity text & improve Grow

- src/game/client/components/menus.cpp
> Add new icons for demo, home and server browser

- src/tools/map_convert_07.cpp
> map_convert_07: Check for width/height 0

- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_browser.cpp
- src/game/client/components/menus_demo.cpp
- src/game/client/components/menus_settings.cpp
Generally, would be nice to have very decent hover effects and decent colors.
I just tried for fun adding hover effects to menu tabs(red for the quit button),
hover effects for the server browser items
and color for search/exclude
I'm not an artist, it doesnt look good, if someone wants to overtake, he/she would be very welcome todo so
> [Idea] Add some decent hover effects and colors

- src/engine/server/server.cpp
- src/engine/server/server.h
Reduces the number of syscalls
> Server: Only recv new packets when we know they are waiting

- src/game/client/components/menus.h
- src/game/client/components/menus_start.cpp
- src/game/client/gameclient.cpp
> Kill server on quit

- src/game/client/components/menus_demo.cpp
You can't store the result of Localize in a static, it will be removed
by switching to another language.
Thanks to Jupeyy for report
> Fix localizing demo list

- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/popups.cpp
> Ask for confirmation before placing border tiles

- src/game/client/components/menus.cpp
- src/game/client/components/menus_browser.cpp
- Increase size of Name and Clan in adding friend fields
- Smaller Search and Exclude fields
- No more duplicate Search - Search - Search text
- Smaller Connect and Refresh buttons
- Search and Exclude no longer so dark
> Some browser improvements

- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/io.cpp
Since it's the most important layer
> Editor: Select game layer by default (fixes #2834)

- CMakeLists.txt
- src/engine/shared/config_variables.h
- src/engine/shared/dilate.cpp
- src/engine/shared/dilate.h
- src/game/editor/editor.cpp
- src/tools/dilate.cpp
editor dilate can be turned off.
about the threshold:
old:
new:
> Fix dilate alpha threshold & auto apply dilate on embedded texture in editor

- src/base/math.h
- src/game/editor/editor.cpp
- src/game/editor/layer_quads.cpp
- src/game/editor/popups.cpp
This fixes the issue with the Tex UV coords being complete garbage
> Use fixed point conversion consistently

- src/engine/client/http.cpp
- src/engine/client/http.h
- src/game/client/components/skins.cpp
since it's not really interesting for most players, as long as things work fine
> Don't log skin downloading progress

- src/engine/client/client.cpp
- src/engine/client/http.cpp
- src/engine/client/http.h
- src/engine/shared/storage.cpp
- src/game/client/components/skins.cpp
Especially skins were only deleted after they were requested again
> Remove failed downloaded files immediately

- other/ddnet.appdata.xml
- src/game/client/components/mapimages.cpp
- src/game/client/components/mapimages.h
- src/game/editor/popups.cpp
- src/game/version.h
Still needs to go through Release Candidate testing.
> Version 15.0.5

- src/engine/client/input.cpp
- src/engine/client/input.h
- src/engine/input.h
- src/game/client/components/chat.cpp
- src/game/client/components/chat.h
- src/game/client/components/console.cpp
- src/game/client/components/menus.cpp
Mainly solves the backspace problem where you were able to delete from chat and ime comps at the same time.
Also set the position of composition window
Need some testing from other languages' users.
Need https://github.com/ddnet/ddnet-libs/pull/14 to work on windows
> Set IME Window Position & Prevent Input from fighting with IME

- data/shader/pipeline.frag
- data/shader/pipeline.vert
- src/engine/client/backend_sdl.cpp
- src/engine/client/backend_sdl.h
- src/engine/client/graphics_threaded.cpp
- src/engine/client/graphics_threaded.h
- src/engine/graphics.h
- src/game/client/render_map.cpp
- src/game/editor/editor.cpp
- src/game/editor/io.cpp
- src/game/editor/layer_tiles.cpp
- src/game/editor/popups.cpp
Does not improve performance in editor!
> Add new renderer(as streamed vertices) for editor

- src/game/client/components/menus_settings.cpp
Even if players have cl_mouse_followfactor turned on
Alternative fix for #2761 since players keep reporting confusion about this
> Make sure turning dyncam off in settings works

- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/popups.cpp
It doesn't show a scrollbar when there aren't more than 5 rules.
> Add scrollbar to auto rules list, fixes #2514

- src/game/client/components/chat.cpp
> stop disabling textinput during connecting

- src/game/client/components/scoreboard.cpp
> Fix Score/Time alignment

- src/engine/client/serverbrowser.cpp
- src/engine/shared/config_variables.h
- src/game/client/components/menus_browser.cpp
> Remove pure server filters, add space for Countries/Types

- src/game/editor/editor.cpp
> Only auto dilate for transparent images

- src/game/editor/popups.cpp
This pr also doubles window size.
> Fix auto rules scrollbar bugs

- src/game/client/components/chat.cpp
- src/game/client/components/chat.h
May fix https://github.com/ddnet/ddnet/issues/259
Needs a bit more testing
> Join identical chat lines to prevent spam

- src/engine/client/backend_sdl.cpp
- src/engine/client/backend_sdl.h
- src/engine/shared/config_variables.h
For Ravie, and others that want the old renderer opengl 3.3 feeling back xd
> Allow specifying texture LOD BIAS

- src/game/client/components/chat.cpp
otherwise random lines will mistakenly show [2]
> Reset m_TimesRepeated on new line

- src/game/client/components/menus_browser.cpp
> Add clear button to server address field

- src/game/server/gamecontext.cpp
> fix for a SixUp vote creator id which wasn't set

- src/engine/shared/config_variables.h
- src/game/client/components/hud.cpp
- src/game/client/components/hud.h
I think .me' reported this to me 7 years ago and I've been noticing that they're wrong since then. Time to remove I guess, they don't seem useful anyway.
> Don't show wrong decisecs in game time in HUD

- src/game/client/components/menus.h
- src/game/client/components/menus_settings.cpp
As reported by abcqwerty on Discord
> Need to send info when updating skin in text field

- src/engine/shared/config_variables.h
- src/game/client/components/menus_settings.cpp
- src/game/client/components/sounds.cpp
- src/game/client/components/sounds.h
> Add Background music volume slider

- src/game/client/components/binds.cpp
@plsplsplslol ok from your side?
> Fix ctrl+shift+d moving tee (fixes #2930)

- datasrc/compile.py
- datasrc/seven/compile.py
- scripts/fix_style.py
> Fix autoformatting wrt. generated files

- src/game/editor/editor.cpp
Idk how I thought this ever worked. Fixes #2981
> Fix multiple layer editing

- data/languages/french.txt
> Update french translation

- CMakeLists.txt
- data/languages/index.txt
- data/languages/serbian_cyrillic.txt
This is adding Serbian Cyrillic translation and contain complete translation with latest strings.
by Veljko Radovanovic (VekiPro)
> Add Serbian Cyrillic translation

- src/game/client/components/binds.cpp
> Only ignore ctrl+shift for press, not release

- src/engine/server/server.cpp
- src/game/server/gamecontext.cpp
where it makes sense, means you don't need to quote strings for those
> Use rest instead of string in some commands

- src/game/client/components/menus_settings.cpp
- src/game/client/components/menus_settings_assets.cpp
- src/game/client/components/skins.cpp
- src/game/client/components/skins.h
> Add refresh button for skins, closes #2979

- src/engine/client/client.cpp
Reported by builder17 that on Vanilla server timeout code can get sent
> Reset m_ServerCapabilities on Disconnect

- src/base/tl/algorithm.h
- src/game/client/components/countryflags.h
- src/game/client/components/menus.h
- src/game/client/components/menus_settings.cpp
- src/game/client/components/skins.h
- src/game/editor/editor.h
- src/game/mapitems.h
Noticed, that its really slow, when you have alot of auto demos
> Use std::sort instead of bubble_sort

- src/engine/client/text.cpp
- src/engine/textrender.h
- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_browser.cpp
- src/game/client/components/menus_ingame.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/components/menus_settings_assets.cpp
- src/game/client/ui.cpp
- src/game/client/ui.h
- src/game/editor/editor.cpp
- src/game/editor/editor.h
i think the round borders create a bit of optical illusion, e.g. the "V" in edtior is only 1 pixel of, but looks like its completly left xd
i checked at few resolutions with gimp and only saw around 1 pixel margin of error, but go ahead and test yourself :D
> Text alignment

- src/game/client/components/spectator.cpp
> Show friends on spectate tab

- CMakeLists.txt
- datasrc/seven/compile.py
- datasrc/seven/content.py
- src/engine/client/graphics_threaded.cpp
- src/engine/client/graphics_threaded.h
- src/engine/graphics.h
- src/engine/sound.h
- src/game/client/components/damageind.cpp
- src/game/client/components/effects.cpp
- src/game/client/components/emoticon.cpp
- src/game/client/components/ghost.cpp
- src/game/client/components/ghost.h
- src/game/client/components/hud.cpp
- src/game/client/components/items.cpp
- src/game/client/components/killmessages.cpp
- src/game/client/components/menus_ingame.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/components/particles.cpp
- src/game/client/components/players.cpp
- src/game/client/components/scoreboard.cpp
- src/game/client/components/skins.cpp
- src/game/client/components/skins.h
- src/game/client/components/spectator.cpp
- src/game/client/components/statboard.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/client/render.cpp
- src/game/client/render.h
- src/game/client/skin.h
- src/game/editor/editor.cpp
fixes #2203 
Puh, something i always wanted todo.
Need to error read, bcs alot of copy paste.
Modulizes all images, so that all images are mipmap indepedent, without texeloffset problems
I also added the ninja bar analyzer for #2921
> Modulize skins, particles, emoticons and game

- src/game/variables.h
For ui_page makes no difference since we limited in code
For ui_settings_page assets page is now remembered
> Fix ui_page/ui_settings_page ranges

- src/engine/client/client.cpp
- src/engine/client/client.h
- src/game/editor/editor.cpp
Caught my eye while doing the integrity PR.
> Remove usages of qsort

- src/game/server/gamecontext.cpp
- src/game/server/player.cpp
- src/game/server/player.h
call vote, spectator mode, info change
> Consider as not-afk on emoticon, chat, vote,

- src/game/client/components/menus_demo.cpp
> Update demo browser on demo save

- src/engine/server/server.cpp
otherwise reason can be cut off
> increase buffer size for name_ban messages

- src/engine/shared/config_variables.h
- src/game/client/components/menus_settings.cpp
- src/game/client/components/sounds.cpp
- src/game/client/components/sounds.h
> Add GUI & Game sound volume sliders

- src/base/tl/algorithm.h
- src/base/tl/sorted_array.h
- src/engine/shared/uuid_manager.cpp
- src/engine/shared/uuid_manager.h
Already wrote that patch when i noticed its not about this, maybe we can use it, else nvm
> Optimize uuid lookup

- src/game/client/components/skins.cpp
> Fix skin load

- src/engine/client/text.cpp
created by 5ebabe2ece3d6b7628c01491445fbcea7b003f3c
> Reset renderflags directly after use

- src/engine/client/backend_sdl.cpp
- src/engine/client/graphics_threaded.h
Though I prefer this version I also made one keeping the old ugly pointer arithmetic https://github.com/Learath2/ddnet/commit/cb613561055957702eba43fc66fc5084f7c9f140
Feel  free to take whichever. Supersedes #3061
> Fix alignment issues in CCommandBuffer

- src/engine/client/backend_sdl.cpp
Mistakenly disabled in https://github.com/ddnet/ddnet/pull/1418
> Make initial borderless work again

- src/game/editor/io.cpp
Didn't check out the teeworlds source while setting the value the last time. teeworlds sets those values to 0.
> Set correct value on layer saving (which was recently uninitialized)

- src/game/client/components/menu_background.cpp
- src/game/client/components/menu_background.h
The vanilla code isnt really robust against short distances, hope this fixes almost all edge cases
> Make menu background camera impl more robust

- CMakeLists.txt
- src/engine/client.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/engine/client/ghost.cpp
- src/engine/client/ghost.h
- src/engine/ghost.h
- src/engine/server/server.cpp
- src/engine/shared/demo.cpp
- src/engine/shared/ghost.cpp
- src/engine/shared/ghost.h
- src/game/client/components/ghost.cpp
- src/game/client/components/menus_demo.cpp
- src/game/client/components/menus_ingame.cpp
- src/game/mapbugs.cpp
- src/game/mapbugs.h
- src/game/server/gamecontext.cpp
- src/test/mapbugs.cpp
Some places remain due to net/file format compatibility.
> Remove CRC in all possible places

- src/game/client/components/players.cpp
Its already increased by the for loop.
Might have made the hook shorter(for very very long hooks) the past 3 years xd
> Fix hookchains

- src/engine/client/text.cpp
- src/engine/textrender.h
- src/game/client/components/menus.cpp
Pls check if u like the new cusor and if it works now
fixes #3110
> Fix and change text cursor

- src/engine/client/backend_sdl.cpp
- src/engine/shared/config_variables.h
- src/game/client/components/menus_settings.cpp
If ppl see white textures its related to
#2125
and you need to revert it, bcs thats not fixable, there is no extension for GL_GENERATE_MIPMAP or smth
> Make GL 1.5 default

- src/engine/client/backend_sdl.cpp
- src/engine/shared/config_variables.h
- src/game/client/components/menus_settings.cpp
As discussed with Lerath2, we should try to debug
This reverts commit 537f47d11d8c637c36cb698f51ee654abff76e26.
> Revert "Make GL 1.5 default"

- src/game/server/player.cpp
Making use of the skin downloader.
Skin choice is based on your name, only active on October 31 and November 1 with events 1 in settings
> Show halloween skins only on Halloween

- src/game/server/player.cpp
Logic woopsie in https://github.com/ddnet/ddnet/pull/3116
> Fix halloween logic

- src/game/variables.h
> Disallow cl_text_entities_size 0 (fixes #3145)

- src/game/client/components/menus.cpp
Introduced in https://github.com/ddnet/ddnet/commit/186206d40c2fe65193832bf94389351515c179b8
> Fix out of bounds array access in DoEditBox

- src/engine/client/client.cpp
too aggressive, might just be bad internet at the moment
> Ignore ddnet-info.json dl failure again

- src/game/teamscore.h
> Fix out of bounds access in GetSolo

- src/game/editor/popups.cpp
> Editor: Fix selection of None value in auto rules (fixes #3013)

- src/engine/server/databases/mysql.cpp
- src/game/server/save.cpp
Fixes #2522, fixes #3144 and fixes second leak from #3134.
> Fix memory leak on team finish and read of uninitialized data

- src/engine/client/backend_sdl.cpp
- src/engine/client/graphics_threaded.cpp
- src/engine/client/graphics_threaded.h
- src/engine/client/text.cpp
- src/engine/graphics.h
- src/engine/shared/config_variables.h
- src/engine/textrender.h
- src/game/client/components/chat.cpp
- src/game/client/components/chat.h
- src/game/client/components/menus_settings.cpp
- src/game/client/gameclient.cpp
https://github.com/ddnet/ddnet/pull/3093
> Visual Chat Update

- src/engine/client/backend_sdl.cpp
- src/engine/shared/config_variables.h
If someone wants to try, you have to execute the client with a config that contains dbg_gfx 1
If opengl debug is supported it will show "Enabled OpenGL debug mode" in the console
> Add gfx debug

- src/base/vmath.h
- src/game/client/components/items.cpp
- src/game/client/components/players.cpp
- src/game/client/components/skins.cpp
- src/game/client/gameclient.cpp
- src/game/client/prediction/entities/character.cpp
- src/game/client/prediction/entities/character.h
- src/game/client/prediction/gameworld.cpp
- src/game/gamecore.cpp
- src/game/gamecore.h
- src/game/server/entities/character.cpp
- src/game/server/gameworld.cpp
The first three commits are safe
The ones i'll add later will be inside the gamecore, so might alter behaviour.
I'll see which ones are critical, but takes me some time
i fixed most in #3081
> Fix arithmentic problems

- README.md
Add installation info for binary. How to install from repositories and link to steam.
Documentation change only.
> Add installation info for binary.

- src/game/editor/editor.cpp
> Allow zooming in further in Editor

- src/game/client/components/camera.cpp
- src/game/client/components/menus_settings.cpp
- src/game/variables.h
closes #3096
Since nobody expressed any opinions, how about we get this in and see some reactions. it is off by default anyway.
> Smooth Camera

- src/game/client/gameclient.cpp
fixes #3173
Quickly tested it.
> Remove one particle component

- src/game/collision.cpp
Tested that one map from #bug channel
> Fix float loops

- src/engine/client/serverbrowser.cpp
> Fix combined player/ping sorting function

- README.md
To be linked from https://github.com/ddnet/ddnet/pull/3133
> Add memcheck/asan/ubsan to readme

- src/engine/client/text.cpp
- src/engine/serverbrowser.h
- src/engine/textrender.h
- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_browser.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/components/nameplates.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/client/render.cpp
- src/game/client/render.h
- src/game/client/ui.cpp
- src/game/client/ui.h
Build will fail bcs of clang-format,
i'll update this comment to explain.
> UI Elements

- src/base/system.c
- src/engine/client/backend_sdl.cpp
- src/engine/client/opengl_sl.cpp
- src/engine/client/opengl_sl_program.cpp
- src/engine/client/text.cpp
- src/engine/client/video.cpp
- src/game/client/gameclient.cpp
- src/game/server/gamecontext.cpp
> consistent formatting for dbg_msg

- autoexec_server.cfg
- src/game/client/gameclient.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
No need to tell new players how to manually add a vote or load a map from rcon
> Add add_map_votes command for easier local map testing

- src/base/system.c
- src/base/system.h
- src/game/client/components/hud.cpp
- src/game/client/components/menus_browser.cpp
- src/game/client/components/menus_demo.cpp
- src/game/client/components/menus_ingame.cpp
- src/game/client/components/scoreboard.cpp
- src/game/server/gamecontext.cpp
- src/game/server/score.cpp
- src/game/server/teams.cpp
- src/test/str.cpp
Will also look into #3140 and fix here.
> More hours (fixes #3140)

- src/tools/map_convert_07.cpp
> Use IntsToStr function from gamecore.h

- src/game/client/render.cpp
> Fix style in render.cpp

- src/engine/server/databases/connection.h
- src/engine/server/databases/mysql.h
- src/engine/server/databases/sqlite.h
- src/game/server/score.cpp
> Fix random_map and random_unfinished_map on SQLite server

- src/game/client/skin.h
> Sort skins without case (fixes #3213)

- bors.toml
> Make bors also look at clang-format & clang-tidy

- autoexec_server.cfg
> Fix grammar in autoexec_server.cfg (Credits to Blade)

- src/test/teehistorian.cpp
for `teehistorian-ddnetver-old@ddnet.tw`
> Fix UUID in test case comment

- CMakeLists.txt
- scripts/wordlist.py
- src/game/server/score.cpp
> Create fallback wordlist in sourcecode (fixes #3206)

- src/game/client/gameclient.cpp
> Fix network x_ check (thanks to Jupeyy)

- src/game/client/components/menus_browser.cpp
as suggested by HalfNoob on Discord
> Warn when connecting to new server with high gametime

- src/game/client/components/hud.cpp
- src/game/variables.h
> Add cl_showhud_timer option (requested by hussainx3)

- data/languages/czech.txt
> Add czech translation by eNJi

- .clang-tidy
- src/base/system.c
- src/engine/client/backend_sdl.cpp
- src/engine/client/keynames.h
- src/engine/client/opengl_sl.cpp
- src/engine/client/serverbrowser.cpp
- src/engine/client/text.cpp
- src/engine/graphics.h
- src/engine/server/databases/mysql.cpp
- src/engine/server/sql_string_helpers.cpp
- src/game/client/components/ghost.cpp
- src/game/client/components/ghost.h
- src/game/client/components/maplayers.cpp
- src/game/editor/editor.cpp
- src/game/editor/layer_game.cpp
- src/game/editor/layer_tiles.cpp
- src/game/server/entity.h
- src/game/server/gamecontext.cpp
- src/game/server/score.h
- src/game/server/teams.h
- src/tools/config_common.h
> Enable most clang-tidy bugprone-*, misc-*, performance-* checks

- src/engine/client/text.cpp
- src/engine/textrender.h
- src/game/client/ui.cpp
- src/game/client/ui.h
> Fix text color change

- src/engine/client/client.cpp
> play command: Only quit when demo exists (fixes #3283)

- src/game/server/entities/dragger.cpp
> Fix dragger logic

- data/languages/norwegian.txt
> Update Norwegian translation

- data/languages/simplified_chinese.txt
- data/languages/traditional_chinese.txt
Traditional Chinese has a large diff because I was trying to line it up with Simplified so I can check discrepancy.
> Chinese Translation Update

- CMakeLists.txt
- src/engine/client/backend_sdl.cpp
- src/engine/client/backend_sdl.h
- src/engine/client/blocklist_driver.cpp
- src/engine/client/blocklist_driver.h
- src/engine/client/graphics_threaded.cpp
- src/engine/client/graphics_threaded.h
- src/engine/shared/config_variables.h
- src/engine/warning.h
- src/test/blocklist_driver.cpp
Only briefly tested,
- the error message is bad
- the impl basically only works for the intel windows string, so its not really a generalized list
fixes #3234
> Add block list for drivers

- src/game/client/components/spectator.cpp
> Respect friend color in spectate mode ♥ too

- src/engine/client/client.cpp
- src/engine/shared/storage.cpp
> DemoRecorder: Only remove existing filenames

- .github/workflows/style.yml
- data/languages/danish.txt
- data/languages/dutch.txt
- data/languages/persian.txt
- data/languages/polish.txt
- data/languages/simplified_chinese.txt
- data/languages/traditional_chinese.txt
- data/languages/turkish.txt
- scripts/languages/copy_fix.py
- scripts/languages/readme.txt
- scripts/languages/twlang.py
- scripts/languages/update_all.py
> Check translations in github, check formatting strings, fix

- src/game/client/render_map.cpp
> Mod by zero

- src/engine/client/backend_sdl.cpp
- src/engine/client/backend_sdl.h
- src/engine/client/graphics_threaded.cpp
- src/engine/client/graphics_threaded.h
> Unlimited texture names

- src/game/client/components/items.cpp
@pure-luck-999 can you test, if this is already enough?
fixes #3323
>  Add ball effects, even for invalid projectiles

- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_browser.cpp
- src/game/client/components/menus_demo.cpp
- src/game/client/components/menus_ingame.cpp
Make keys work after searching in vote menu
Unify some duplicated code
> Improve list box behaviour, make it more consistent

- src/game/server/ddracechat.cpp
- src/game/server/entities/character.cpp
> Found some more times with mins, use hours for consistency

- src/game/client/components/menus.cpp
- src/game/client/components/menus_browser.cpp
- src/game/client/components/menus_demo.cpp
- src/game/client/components/menus_ingame.cpp
Caused by https://github.com/ddnet/ddnet/pull/3304/
> Fix scroll bar (fixes #3347)

- src/game/server/gamecontext.cpp
> fix typo "authroized"

- README.md
> Add benchmarking section to README

- src/game/server/player.cpp
- src/game/server/teams.h
> Check finish of team after player joins spectators

- src/game/server/gamecontext.cpp
> Remove annoying "added option" logging

- src/game/server/player.cpp
Got to get this in quickly, crashing in production servers.
> Check for m_pCharacter before accessing it (fixes #3372)

- src/game/client/components/killmessages.cpp
- src/game/client/components/killmessages.h
> Recreate kill messages if required

- src/game/client/components/killmessages.cpp
Fixes #3429
Also made it a bit safer by checking what the server sends
> Filter invalid kill messages

- src/game/client/components/voting.cpp
> Notify about vote when authed

- src/game/client/components/menus_browser.cpp
> Fix localization of version/game type/ping in server details

- src/game/server/gamecontext.cpp
> Keep veto right after joining dummy with lower ID (fixes #3404)

- src/game/client/components/binds.cpp
- src/game/client/components/menus_settings.cpp
> Add w as default bind for dummy hammer

- src/game/server/gamecontext.cpp
Reported by Lenah on Discord
Also allow IPs to change their vote when multiple players are connected, with 1 player it always worked.
Further broken by https://github.com/ddnet/ddnet/pull/3405
> Fix veto vote, simplified logic

- src/game/ddracecommands.h
- src/game/server/ddracecommands.cpp
- src/game/server/entities/character.cpp
- src/game/server/entities/character.h
- src/game/server/gamecontext.h
> Add (un)endless_hook command

- src/game/client/components/chat.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/components/scoreboard.cpp
> Improve some chat settings

- data/shader/quad.vert
- src/engine/client/backend_sdl.cpp
- src/engine/client/opengl_sl_program.h
> Fix quad shader

- src/game/client/components/maplayers.cpp
fixes #3454
@bretonium would you be so kind and test this quickly, if everything looks fine again? :D
> Readd round start tick to the calculation

- src/engine/shared/config_variables.h
> Same default map as in autoexec_server.cfg

- src/game/client/components/menus_browser.cpp
> Fix x of y servers

- data/languages/russian.txt
> Update russian translation

- src/game/editor/editor.cpp
> Make dragging quads in the editor more sensitive to small mouse deltas

- cmake/FindFFMPEG.cmake
> Fix linux build by reordering ffmpeg libs (fixes #3466)

- src/game/client/components/menus_demo.cpp
> Fix scrollbar going out of bounce (fixes #3416)

- src/game/server/gamecontext.cpp
> typo in gamecontext.cpp

- src/engine/shared/snapshot.cpp
> Fix client crash with too many items (fixes #3479)

- src/base/system.c
> Implement network statistics for recvmmsg

- CMakeLists.txt
- src/base/system.c
- src/base/system.h
- src/base/tl/threading.h
- src/engine/client/http.cpp
- src/engine/client/sound.cpp
- src/engine/client/updater.h
- src/engine/client/video.cpp
- src/engine/client/video.h
- src/engine/shared/jobs.h
https://clang.llvm.org/docs/ThreadSafetyAnalysis.html
> Add Thread Safety Analysis

- src/game/server/ddracechat.cpp
> Improve grammar when locking team (fixes #3467)

- src/game/client/components/menus_demo.cpp
> Fix up/down keys in demo browser

- src/game/client/prediction/entities/projectile.cpp
- src/game/client/prediction/entities/projectile.h
- src/game/client/prediction/entity.cpp
- src/game/client/prediction/entity.h
- src/game/client/prediction/gameworld.cpp
> No network clip in client prediction

- src/game/server/entities/character.cpp
- src/game/server/entities/character.h
- src/game/server/entity.cpp
- src/game/server/entity.h
- src/game/server/eventhandler.cpp
- src/game/server/eventhandler.h
> Make netclipping of entities and events respect shown distance (fixes #3420)

- src/engine/server/server.cpp
- [ x] Tested the change ingame
> show sixup in status

- src/engine/client/client.cpp
> Fix clang-style

- datasrc/network.py
> Work around Pylint import problem (fixes #3507)

- src/engine/server/server.cpp
> Also display DDNet version for 0.7 clients

- src/engine/server/databases/connection.h
- src/engine/server/databases/mysql.cpp
- src/engine/server/databases/mysql.h
- src/engine/server/databases/sqlite.cpp
- src/engine/server/databases/sqlite.h
- src/game/server/score.cpp
Do we want average too or just median?
> Display median time instead of average (fixes #3399)

- src/game/client/gameclient.h
> Don't predict input from the dummy when it's paused

- src/engine/server/databases/mysql.cpp
as reported by I.K.U on Discord
> Fix median calculation

- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/server/player.cpp
> Improve ClShowDistance a bit

- src/game/client/prediction/entities/pickup.cpp
- src/game/client/prediction/entities/projectile.cpp
- src/game/server/entities/gun.cpp
- src/game/server/entities/light.cpp
- src/game/server/entities/pickup.cpp
- src/game/server/entities/plasma.cpp
- src/game/server/entities/projectile.cpp
> Handle switch number 0

- src/game/client/components/menus.cpp
- src/test/str.cpp
- src/test/thread.cpp
> Fix crash on namechange (fixes #3444)

- src/game/server/player.cpp
> Fix condition for eye emote (fixes #3536)

- src/game/server/entities/character.cpp
Fixed all the merges and clang-format (hopefully)
> rescue on freeze/dfreeze (supersedes #3335)

- src/game/server/score.cpp
> rank/teamrank: Display how much better you are

- src/game/server/ddracechat.cpp
- src/game/server/teams.cpp
- src/game/server/teams.h
> Improve error messages when you can't join team

- src/game/client/components/menus_browser.cpp
> Reset filter: Refresh browser so that countries/types is also updated

- src/game/client/components/chat.cpp
> Don't highlight echo messages (fixes #3554)

- src/engine/client.h
- src/engine/client/client.cpp
which info2.ddnet.tw provides using a geolite db to provide a better
server for players in China
> Use map download url from info2.ddnet.tw (fixes #3546)

- src/game/client/components/chat.cpp
> Don't highlight us if we have no name (alternative fix for #3554)

- CMakeLists.txt
- data/languages/arabic.txt
- data/languages/index.txt
> Add Arabic language translation by .Yukki

- data/languages/polish.txt
Anonymously contributed, will need someone with Polish language to check
> Update Polish translation

- data/languages/dutch.txt
- data/languages/hungarian.txt
- data/languages/russian.txt
- data/languages/simplified_chinese.txt
- data/languages/traditional_chinese.txt
- data/languages/ukrainian.txt
- src/game/gamecore.h
> DDnet -> DDNet

- src/game/mapitems.cpp
> Disallow some more switch entities

- src/game/client/components/menus_settings.cpp
> Fix color picker positioning (fixes #3574)

- license.txt
> Update Copyright year in license.txt

- src/game/client/components/items.cpp
- src/game/client/gameclient.cpp
This also skips the actual physics prediction for the other teams (which could potentially reduce the cpu load very slightly on solo/dummy servers).
> Don't predict other teams

- CMakeLists.txt
> Add discord dylib on Mac

- src/game/server/score.cpp
> Inform player while loading when save exists, but they don't belong to the team
