ddnet/ddnet

src/game/server/ddracecommands.cpp
src/game/server/entities/character.cpp
src/game/server/save.cpp
src/game/server/save.h
src/game/server/score.cpp
src/game/server/teams.cpp

Rename save/load to conform to the code style

---

src/engine/shared/config_variables.h
src/game/client/gameclient.cpp

Remove gfx_show_warnings

---

src/game/server/score.cpp

/times: Show country rank is from

---

src/game/client/components/scoreboard.cpp

Dunno if its ok, i increased the scoreboard a bit, bcs its already pretty tight and i didnt want to decrease the space for name/clan
old:
new:
new with way too long names(clamps them as expected):
new with many players, uses full space on 5:4:
vanilla team(saves space by not using timestamp as score), but also uses nearly all space nowon 5:4:

Fix scoreboard overlapping

---

src/engine/shared/fifo.cpp
src/engine/shared/fifo.h

Helps with the official servers.

Remove fifo file on shutdown

---

src/game/server/gamecontext.cpp

Forgot to actually send Sv_RecordLegacy to old clients

---

scripts/dmg.py

Check out https://docs.python.org/3/library/tempfile.html#tempfile.mktemp

Fix Insecure temporary file

---

src/game/client/components/chat.cpp

Pressing "U" to show all chat messages and make a message to appear repeating while holding U, makes it to create 2 instances, bcs another Line is allocated, when not returning for the log.

Fix chat repeated messages

---

src/engine/shared/config_variables.h
src/game/server/gamecontext.cpp

Another tool that should help moderators

Add a way to block people from chatting on vpns

---

src/engine/shared/demo.cpp
src/game/editor/io.cpp

std::max -> maximum

---

src/game/server/player.cpp

Quick-fix for
https://github.com/ddnet/ddnet/pull/3669#issuecomment-794805243.
Probably breaks that feature a bit.

Don't bypass the anti-spam system

---

src/game/client/components/menus_settings.cpp
src/game/client/components/scoreboard.cpp
src/game/client/components/spectator.cpp

tee settings
scoreboard
spectator board

Center tees in more places

---

scripts/dmg.py

Retry hdiutil create if it fails (fixes #3711)

---

src/engine/shared/netban.h

Since we mostly use them for limited global bans

Banned for life -> Banned

---

src/game/server/score.cpp

Seems this was broken since the beginning, I wonder how we missed this one :)

Actually check all tees. Fixes #3697

---

src/game/editor/auto_map.cpp

Thanks to bojidar-bg for the way to fix, verified locally

Fix automapper crash (fixes #3675)

---

src/game/client/components/menus.cpp
src/game/client/components/menus.h
src/game/client/components/menus_ingame.cpp

Set search field active when opening vote menu ingame

---

src/game/variables.h

Clear up documentation of cl_dummy_control

---

src/game/server/teams.cpp

Please wait %d seconds

---

README.md

Add gmock as dependency to README

---

src/engine/shared/config_variables.h

Lower save/swap punishments

---

src/engine/client/backend_sdl.cpp
src/engine/client/client.cpp
src/engine/client/graphics_threaded.cpp
src/engine/client/graphics_threaded.h
src/engine/client/input.cpp
src/engine/shared/config_variables.h
src/game/client/components/menus_settings.cpp

Only remove windowed fullscreen and restore mouse focus loss behavior

---

src/game/server/teams.cpp

sv_swap_timeout <=

---

src/game/client/components/menus.h
src/game/client/components/menus_browser.cpp
src/game/client/components/menus_demo.cpp

Fix out of list clip clickable/hoverable items

---

src/engine/client/backend_sdl.cpp
src/engine/client/graphics_threaded.cpp
src/engine/client/graphics_threaded.h

so it doesnt add commands without rechecking if the command was actually added

Make AddCommand usage in graphics class safer

---

scripts/fix_style.py

Only use correct clang-format version

---

src/game/server/teams.cpp

Fix crash on test servers (fixes #3789)

---

src/game/server/player.cpp

because why not.
~~definitely not because this have been triggering my anxiety everytime I spawn out of nowhere like a ghost~~

Avoid SpawnEffect Being Clipped for Spawning Player

---

src/engine/client/video.cpp

av_init_packet is deprecated, use av_packet_alloc instead

---

src/engine/client/backend_sdl.cpp

This works on KDE without problems, he also tested on i3

Fix x11 notify by Maiski

---

src/game/client/prediction/gameworld.h
src/game/server/gameworld.h

Don't know why these are there

Remove a Dangling Declaration

---

src/game/client/components/menus_demo.cpp
src/game/client/components/menus_settings.cpp
src/game/client/components/menus_settings_assets.cpp
src/game/editor/editor.cpp

Found more than i thought, would probs worth it to check for editor ui too

Remove stack pointer in menus

---

src/game/server/entities/character.cpp
src/game/server/entities/door.cpp

Fix UB with super (fixes #3830)

---

src/engine/client/http.cpp

[http]: http -> [http]: fetching

---

src/game/server/gamecontroller.cpp

Better than not spawning at all

Use "occupado" spawn spots when nothing else is left

---

src/engine/docs/snapshots.txt

Fix a woopsie in snapshot docs

---

data/languages/hungarian.txt

Update hungarian.txt (by Boti.)

---

src/engine/input.h
src/game/client/components/menus.cpp
src/game/client/ui_ex.cpp
src/game/client/ui_ex.h
src/game/editor/editor.cpp

Add Input handling to UI Ex initialization

---

data/languages/french.txt

Couldn't test all the changes as i don't know where some of them appear :(

Updated french translation

---

data/languages/simplified_chinese.txt
data/languages/traditional_chinese.txt

Update chinese translations

---

data/languages/french.txt

@Chairn can you check them please?

Add French grammar improvements (by T tee)

---

src/game/client/components/menus_settings.cpp

Move hammer and pistol weapons (fixes #3872)

---

src/engine/client/client.cpp
src/engine/client/serverbrowser.cpp
src/engine/client/serverbrowser.h

Another missing commit.
Fixes #3875.
CC #3772 #3855

Fix crash in serverbrowser initialization

---

data/languages/japanese.txt
data/languages/simplified_chinese.txt
data/languages/traditional_chinese.txt

plus some fixes of Chinese strings that my friend found out while doing japanese translation

Update Japanese translation

---

src/base/system.c
src/engine/client/client.cpp
src/engine/client/video.cpp

Either we should delete str_length or we should use it. Feel free to downvote this pr if u think delete is the way to go.

Use str_length

---

src/engine/client/backend/opengl/backend_opengl.h
src/engine/client/client.cpp
src/engine/shared/snapshot.cpp

Remove unused variables

---

src/engine/client/serverbrowser_http.cpp

fixes #3856
@heinrich5991 can you check if this is ok, then we can also add it to the release

Don't refresh, if a job is already running

---

.github/workflows/build.yaml

No hurry to merge it, can wait until ~September I guess
https://github.com/actions/virtual-environments/issues/3287

Github Workflow Ubuntu 16.04 -> 18.04

---

data/languages/spanish.txt

Luminosidad is too long in Spanish

---

data/languages/russian.txt

 fix russian translation

---

bors.toml

Fix bors.toml for Ubuntu 18.04

---

src/engine/client/serverbrowser_http.cpp

Use time_get_microseconds in CChoseMaster's job

---

data/languages/index.txt

Add chuvash and greek into language index

---

src/engine/client/serverbrowser.cpp

sjon -> json

---

src/antibot/antibot_interface.h
src/antibot/antibot_null.cpp

Properly export antibot DLL symbols on Windows

---

src/game/server/gamecontext.cpp

Fixes the problem of people abusing the vote reason for spamming.
Fixes #3926.

Forbid votes while being muted

---

src/engine/client/serverbrowser.cpp
src/game/client/components/chat.cpp
src/game/client/components/menus_browser.cpp
src/game/client/components/menus_ingame.cpp
src/game/client/components/menus_settings.cpp
src/game/client/components/menus_settings_assets.cpp
src/game/editor/editor.cpp
src/game/server/gamecontext.cpp

Compare lower case strings respecting utf8 (fixes #3937)

---

src/engine/client/input.cpp

Reset relative mouse motion on toggle

---

data/languages/finnish.txt

Update Finnish translations

---

src/game/client/components/camera.cpp
src/game/client/components/camera.h

I guess no harm in adding this since it's such a trivial addition? If it's useful to someone might as well have it.
Closes #3923

Allow zooming to levels. Close #3923

---

src/game/client/components/menus.cpp
src/game/client/components/menus.h

Remove unused m_LastInput

---

src/base/system.cpp
src/test/netaddr.cpp

Stop accepting invalid ipv4's

---

src/base/math.h
src/game/client/components/damageind.cpp
src/game/client/components/effects.cpp
src/game/client/components/items.cpp
src/game/client/components/particles.cpp

(cherry picked from commit https://github.com/teeworlds/teeworlds/commit/5e4c7b66c555fa163ea46b960bbe7f5aed953ad1)
Get closer to upstream

math: Rename frandom() to random_float() to match with random_int()

---

src/game/server/ddracechat.cpp

Add /emote normal description (thanks to tela)

---

src/game/client/gameclient.cpp
src/game/client/prediction/entities/character.cpp
src/game/gamecore.cpp

Noticed by Anime.pdf on discord
Doesn't seem to break anything else unintendedly but I'd be more comfortable with it if @trml takes a look.

Populate jetpack field properly

---

src/game/client/components/chat.cpp

Disable chat sounds when recording without chat (fixes #3983)

---

src/game/client/projectile_data.cpp

Fix transparent shotgun bullets

---

src/game/server/entities/character.cpp
src/game/server/entities/character.h
src/game/server/entities/pickup.cpp

Fix collecting weapon in solo part not making any sound.

---

.github/workflows/codeql-analysis.yaml

Remove fetch-depth from CodeQL

---

src/game/server/entities/character.cpp

@ChillerDragon can you check if this fixes the issue?

Check for null. Fix #4090

---

src/game/client/components/camera.cpp

Allow floats arguments for zoom

---

src/game/server/gamecontext.cpp

log git revision hash to stdout/console

---

src/engine/shared/serverinfo.h

Only used client-side so no protocol change

Fix long maps not showing as finished (fixes #4092)

---

.github/workflows/style.yml
src/engine/client/backend/opengl/backend_opengl.cpp
src/engine/client/client.cpp

Use the style introduced by @def- in
https://github.com/ddnet/ddnet/commit/61e47422f62c8f0c7c4640b6bdeba82b819cc509
consistency :)

Use consistent case for error messages

---

src/engine/shared/config_variables.h

fix console name of GfxDesktopWidth

---

src/base/system.cpp
src/base/system.h
src/engine/client/client.cpp
src/engine/client/updater.cpp
src/engine/client/updater.h

Remove Windows XP code

---

src/game/server/entities/door.cpp
src/game/server/entities/door.h

Clean up CDoor

---

CMakeLists.txt

Bump GTest version so we don't have to patch it anymore

---

src/game/server/save.cpp
src/game/server/save.h
src/game/server/teams.cpp

Fix swap resets switches.

---

src/base/color.h
src/base/system.cpp
src/base/system.h
src/engine/shared/console.cpp

Add colors for console windows

---

src/game/client/component.h

I think this will make it easier for future people looking into this class.

document CComponent

---

src/game/editor/layer_tiles.cpp

Allow placing unused tiles from other layers (#fixes 3794)

---

Dockerfile

Update Dockerfile to debian11

---

src/game/client/components/chat.cpp
src/game/client/components/console.cpp
src/game/client/components/hud.cpp
src/game/client/components/mapsounds.cpp
src/game/client/components/voting.cpp
src/game/client/lineinput.cpp
src/game/client/lineinput.h
src/game/client/render.cpp
src/game/editor/editor.cpp
src/game/server/ddracechat.cpp
src/game/server/gamecontext.cpp
src/game/server/player.cpp
src/game/server/player.h
src/game/server/save.cpp
src/game/server/score.cpp
src/game/server/score.h

Some char array naming convention

---

src/engine/client/serverbrowser.cpp

Use `#include <>` instead of `#include ""` for non-relative includes

---

src/base/color.h
src/engine/client/graphics_threaded.cpp
src/engine/client/graphics_threaded.h
src/engine/client/graphics_threaded_null.h
src/engine/graphics.h
src/engine/textrender.h
src/game/client/components/countryflags.cpp
src/game/client/components/countryflags.h
src/game/client/components/damageind.cpp
src/game/client/components/hud.cpp
src/game/client/components/items.cpp
src/game/client/components/killmessages.cpp
src/game/client/components/menus.cpp
src/game/client/components/menus.h
src/game/client/components/menus_browser.cpp
src/game/client/components/particles.cpp
src/game/client/components/players.cpp
src/game/client/render.cpp
src/game/client/ui.cpp
src/game/client/ui.h

- QuadContainers mostly to be able to control the upload better. Decreases the number of buffer uploads to the GPU
- CUIElements to be easier to use

Minor refactoring: QuadContainers & UIElements

---

src/engine/client/input.cpp
src/engine/client/input.h
src/engine/client/text.cpp
src/engine/input.h
src/engine/textrender.h
src/game/client/components/console.cpp
src/game/client/components/console.h

The idea is taken from the implementation of this in ATH client

Copy ingame console like in ATH

---

src/engine/client/backend/opengl/backend_opengl.h
src/engine/client/text.cpp

Fix text upload call, make invalid calls visible

---

src/game/client/components/console.cpp

add ctrl+backspace for ingame console

---

src/game/client/gameclient.cpp

https://github.com/ddnet/ddnet/pull/3993

Fix nullptr when using Config() in components

---

CMakeLists.txt

ogg 1.3.4 -> 1.3.5
opus 1.3.1 (no update, but rebuilt)
opusfile 0.11 -> 0.12
SDL2 2.0.8/2.0.12 -> 2.0.16
sqlite3 3.32.3 -> 3.36.0
freetype 2.10.1 -> 2.11.0
curl 7.69.1 -> 7.79.0
ffmpeg 4.3.1 -> 4.4
websockets 4.1.1 -> 4.2

Update libs, add libpng 1.6.37

---

cmake/FindCurl.cmake

As reported by Jupeyy in https://github.com/ddnet/ddnet-libs/pull/17#issuecomment-933034244

Add zlib1.dll for curl, add pnglibconf.h

---

src/engine/client/graphics_threaded.cpp
src/engine/shared/config_variables.h

Always support resizing, remove gfx_resizable

---

src/engine/shared/config_variables.h

Update events description (fixes #4269)

---

src/game/server/alloc.h

This allocates characters dynamically so hopefully asan will point out the use-after-free.

Try to catch #4240 in action

---

src/game/server/entities/dragger.cpp
src/game/server/entities/dragger.h

Try to fix CDragger's heap-use-after-free (fixes #4277)

---

src/game/server/entities/gun.cpp

sv_plasma_per_sec 0 => disable firing

---

src/engine/client/graphics_threaded.cpp

Remove upper resolution bound

---

src/game/client/components/chat.cpp

Fix snd_chat and snd_team_chat (fixes #4302)

---

src/engine/client/graphics_threaded.cpp
src/tools/dilate.cpp
src/tools/map_convert_07.cpp
src/tools/map_extract.cpp
src/tools/map_replace_image.cpp

Support unicode filenames on windows with pnglite (fixes #4301)

---

src/game/client/ui_ex.cpp

Pr no selection on template

---

src/game/server/player.cpp

Fix DbgDummy check being at the wrong place

---

src/engine/server/databases/connection.h
src/engine/server/databases/mysql.cpp
src/engine/server/databases/sqlite.cpp

Comes in handy for my downstream

Add GetInt64

---

src/tools/map_extract.cpp

Fix map_extract

---

src/game/editor/editor.cpp

Use W, A, S, D to navigate in editor

---

src/game/server/alloc.h

Hopefully crash less with ASAN

---

src/game/server/entities/dragger.cpp

Moved network clipping as well as checks for snappingclient to the top of CDragger now, before allocating entityex (had forgotten about this in the last pr, so that it accidentally ended up snapping it for the 63 other teams).
Fixes #4360

Clip network first in CDragger

---

data/languages/french.txt

Are you sure that you want to disconnect and switch to a different server?
== Êtes vous sur de vouloir vous déconnecter et changer de serveur?
Refreshing...
== Actualisation...
Show local player's key presses
== Montrer les touches appuyées des autres joueurs
updated.

Update french.txt | DDNET: Sucre

---

data/languages/belarusian.txt
data/languages/bulgarian.txt
data/languages/catalan.txt
data/languages/chuvash.txt
data/languages/greek.txt
data/languages/korean.txt
data/languages/kyrgyz.txt
data/languages/persian.txt
data/languages/romanian.txt
data/languages/serbian.txt
data/languages/simplified_chinese.txt
data/languages/slovak.txt
data/languages/traditional_chinese.txt

Update Chinese translations (by cheeser0613)

---

data/languages/hungarian.txt

Update hungarian (by Cellegen)

---

data/languages/catalan.txt

full translate catalan

---

src/game/server/teams.cpp

/swap fix: swap started/finished information

---

src/game/server/gamecontext.cpp

Fix stack-buffer-overflow in Whisper (fixes #4400)

---

src/game/client/components/menus.cpp
src/game/client/components/menus.h
src/game/client/components/menus_browser.cpp
src/game/client/components/menus_demo.cpp
src/game/client/components/menus_ingame.cpp
src/game/client/components/menus_settings.cpp
src/game/client/ui.cpp
src/game/client/ui.h
src/game/client/ui_ex.cpp
src/game/client/ui_ex.h
src/game/editor/editor.cpp
src/game/editor/editor.h
src/game/editor/popups.cpp

- Change appearance of all scrollbars to be consistent with upstream.
- Change the large knob design that was used in some places to the flat design everywhere (except for color pickers).
- Add consistent margins around scrollbars.
- Implementing clicking on scrollbar rails to instantly change the value.
- Consolidate UI scrollbar functions from menus and editor in `CUIEx`.
- Various minor refactorings.

Synchronize with upstream and refactor UI scrollbars

---

data/languages/simplified_chinese.txt

Fixed a typo in simplified_chinese.txt

---

src/base/system.cpp
src/base/system.h
src/engine/client/client.cpp
src/engine/server/server.cpp
src/mastersrv/mastersrv.cpp
src/test/test.cpp
src/tools/config_common.h
src/tools/crapnet.cpp
src/tools/dilate.cpp
src/tools/dummy_map.cpp
src/tools/fake_server.cpp
src/tools/map_convert_07.cpp
src/tools/map_diff.cpp
src/tools/map_extract.cpp
src/tools/map_optimize.cpp
src/tools/map_replace_image.cpp
src/tools/map_resave.cpp
src/tools/packetgen.cpp
src/tools/unicode_confusables.cpp
src/tools/uuid.cpp
src/twping/twping.cpp

#4380 plus the proposed changes. Closes #4369.

Fix command line arguments with unicode on windows (without changing existing code)

---

.github/workflows/codeql-analysis.yaml
README.md

Update readme (fixes #4425)

---

CMakeLists.txt

Hopefully fix execution on Mac by fixing link to SDL

---

src/game/client/components/hud.cpp

Center timer in HUD (fixes #4438)

---

data/languages/ukrainian.txt

Update Ukrainian translation (by SwiatoslaW)

---

README.md

Add code formatting instructions

---

src/game/editor/editor.cpp
src/game/editor/editor.h

Fix leak in CLayerTiles::BrushGrab (fixes #4409)

---

src/engine/client/backend_sdl.cpp
src/engine/client/backend_sdl.h
src/engine/client/graphics_threaded.cpp
src/engine/client/graphics_threaded.h
src/engine/client/graphics_threaded_null.h
src/engine/client/input.cpp
src/engine/graphics.h
src/engine/shared/config_variables.h

after moving window to a screen with different dimensions than the
initial one

Fix text selection cursor position (fixes #4444)

---

CMakeLists.txt

Fix comment in CMakeLists.txt

---

src/engine/server/server.cpp

https://github.com/ddnet/ddnet/pull/4465 might have more side effects

Alternative fix for cut off names (fixes #4463)

---

src/game/client/components/binds.cpp
src/game/client/components/menus.cpp

 Fix normal binds (fixes #4477)

---

README.md

README.md: Sort dependencies alphabetically

---

src/test/score.cpp

Fix formatting in src/test/score.cpp

---

src/engine/client/client.cpp
src/engine/shared/config_variables.h

Actually remove gfx_asyncrender_old

---

src/engine/client/backend_sdl.cpp

Don't overwrite player-set refresh rate

---

src/game/server/scoreworker.cpp

Fix crash in GetSaves (fixes #4500)

---

src/game/server/gamecontext.cpp

Respect sv_chat_initial_delay (fixes #4496)

---

src/game/client/components/players.cpp

Center cl_show_direction (fixes #4495)

---

src/engine/client.h
src/engine/client/client.cpp
src/engine/client/client.h
src/game/client/gameclient.cpp

Fix run_on_join being run on normal player again (fixes #4494)

---

.gitignore

Add .a files to .gitignore

---

src/engine/client/client.cpp
src/engine/server/server.cpp

Display more relevant version numbers on command line (fixes #4511)

---

CMakeLists.txt
src/engine/server/sql_string_helpers.cpp
src/test/score.cpp

Insert current timestamp instead

Don't make score test depend on specific timestamp

---

README.md

Not sure it's interesting enough, but since I tried it out anyway.

Add mold linking instructions

---

src/game/editor/popups.cpp

Support enter and escape in editor when confirming save

---

src/engine/client/client.cpp
src/engine/client/client.h
src/engine/config.h
src/engine/shared/config.cpp
src/engine/shared/config.h

to reset specific config to default value

Implement "reset" command

---

src/game/client/components/menus.cpp

Use power button to quit (fixes #3786)

---

src/game/server/gamemodes/DDRace.cpp

Don't warn on solo server, where no team ranks should exist

---

data/languages/french.txt

Fix french typo

---

src/game/client/components/hud.cpp

Update score hud immediately when switching dummy

---

src/game/client/components/items.cpp

Fix bullet rendered through walls

---

src/game/client/components/voting.cpp

Allow multiple comands when adding vote in UI

---

src/game/server/gamecontext.cpp
src/game/server/player.cpp
src/game/server/player.h

As reported by MitakoKotomi in https://forum.ddnet.tw/viewtopic.php?f=118&p=70154

Default players to being afk on new map

---

src/engine/server/server.cpp

Code by Robyt3 taken from Teeworlds, added SIGTERM

Handle SIGINT and SIGTERM (fixes #4610)

---

src/game/client/component.h
src/game/client/components/ghost.cpp
src/game/client/components/ghost.h
src/game/client/components/menus.cpp
src/game/client/components/menus.h
src/game/client/components/race_demo.cpp
src/game/client/components/race_demo.h
src/game/client/gameclient.cpp

Shutdown components

---

src/engine/client/client.cpp

Forgot a part of the asyncrender revert

---

src/engine/client/client.cpp
src/game/client/gameclient.cpp

Fixes #4629.
CC @fokkonaut 
CC #4623

Fix two bugs introduced by the dummy refactoring in #4623

---

src/engine/client/client.cpp

Only record snapshot of the currently active tee

---

src/game/client/gameclient.cpp
src/game/server/teams.cpp
src/game/teamscore.cpp

Improve super prediction

---

.github/workflows/build.yaml

Try using Windows 2022 (fixes #4658)

---

src/engine/client.h
src/engine/client/backend_sdl.cpp
src/engine/client/backend_sdl.h
src/engine/client/client.cpp
src/engine/client/client.h
src/engine/client/graphics_threaded.cpp
src/engine/client/graphics_threaded.h
src/engine/client/graphics_threaded_null.h
src/engine/graphics.h
src/engine/shared/config_variables.h
src/game/client/components/menus_settings.cpp

Add windowed fullscreen ( a special case for Windows )

---

.github/workflows/build.yaml

since it seems not all github worflow servers are on VS17 yet

Fall back to Visual Studio 16

---

license.txt

Update Copyright year

---

src/game/client/prediction/gameworld.h
src/game/server/gameworld.h

Init m_pNextTraverseEntity

---

src/game/server/gamecontext.cpp

Init m_NonEmptySince

---

data/languages/portuguese.txt

Update Portuguese translations (by Rockus)

---

README.md
src/engine/client/backend/opengl/backend_opengl.cpp
src/engine/client/backend_sdl.cpp
src/engine/client/client.cpp

Add CentOS, RedHat, AlmaLinux instructions and fix build

---

src/base/system.cpp
src/base/system.h
src/engine/client/client.cpp
src/engine/server/server.cpp
src/test/test.cpp

Add secure_random_uninit

---

data/languages/brazilian_portuguese.txt
data/languages/catalan.txt
data/languages/german.txt
data/languages/russian.txt

Add localized wiki pages where there is some content at least

---

data/languages/french.txt

Added missing french translations

Updated french translations

---

src/engine/server/databases/sqlite.cpp

Better fix for sqlite3_expanded_sql

---

src/game/server/entities/character.cpp

Since you have visual indication already, as suggested by fokkonaut and
Konsti

No chat messages for live freeze

---

src/base/system.cpp
src/engine/client/backend_sdl.cpp
src/engine/server/databases/sqlite.cpp

Fix MinGW warnings (fixes #4731)

---

src/engine/client/backend_sdl.cpp
src/engine/client/backend_sdl.h

Give the condition waits proper conditions

---

data/languages/swedish.txt

Update and improve the Swedish translations

---

src/game/client/components/menus_demo.cpp

Fix listbox item double click behavior

---

README.md

I plan on documenting more stuff (in a manner that @heinrich5991 is fine with it) so i think it would be great to mention it on the readme.
The docs are regenerated every 30 minutes using latest master.

Add link to doxygen generated docs hosted on wiki.ddnet.tw

---

src/engine/client/client.cpp

Fix logging into rcon with dummy

---

src/base/system.cpp

See also https://no-color.org/

Support NO_COLOR environment variable

---

src/engine/server.h
src/engine/server/server.cpp
src/engine/shared/network_client.cpp
src/engine/shared/network_server.cpp
src/game/server/gamecontext.cpp

Don't try to send messages outside of sv_max_clients (fixes# 4750)

---

README.md

Fix test run instructions

---

src/game/teamscore.h

As requested here https://github.com/ddnet/ddnet/pull/4737#discussion_r810549223, I have assigned static values to the SV_TEAM enum and added a few "useful" comments
If these are too much or you want me to adjust something, feel free to comment.

SV_TEAM enum was labeled

---

src/engine/client/client.cpp

Remove some redundant variable, spell out the condition instead

---

src/base/system.cpp
src/base/system.h
src/engine/client/client.cpp
src/engine/server/server.cpp
src/engine/shared/econ.cpp
src/engine/shared/network.h
src/engine/shared/network_client.cpp
src/engine/shared/network_console.cpp
src/engine/shared/network_console_conn.cpp
src/engine/shared/network_server.cpp
src/mastersrv/mastersrv.cpp
src/tools/crapnet.cpp
src/tools/fake_server.cpp
src/twping/twping.cpp

In preparation to the proxy code, I refactored the network code a little, unifying its interface across operating systems and making our use of recvmmsg invisible to the caller.

Some network refactoring

---

data/languages/german.txt
src/game/client/components/menus_settings.cpp

Reported by Izanagi on Discord
Old:
New:

Fix some spacing in settings with German

---

src/engine/client/client.cpp
src/engine/client/http.cpp
src/engine/client/http.h

Use ipv4 for info2.ddnet.tw requests

---

src/game/client/components/menus.cpp
src/game/client/components/menus.h
src/game/client/components/menus_browser.cpp
src/game/client/components/menus_ingame.cpp
src/game/client/components/menus_settings.cpp
src/game/client/components/menus_settings_assets.cpp
src/game/client/ui.cpp
src/game/client/ui.h
src/game/client/ui_ex.cpp
src/game/editor/editor.cpp
src/game/editor/layer_tiles.cpp
src/game/editor/popups.cpp

Can defs still be improved.
Ignored for text input
Before:
After:

Menu auto font size

---

README.md

Add instructions for videorecorder being default (fixes #4804)

---

CMakeLists.txt

Recurse ENGINE_SHARED

---

src/game/client/components/menus_settings.cpp

Full size sound settings

---

src/game/server/ddracecommands.cpp

Don't mute for 0 seconds (fixes #4816)

---

src/base/system.cpp
src/base/system.h

Use system.h style for system.h

---

README.md

add link to https://wiki.ddnet.tw/wiki/Development on readme

---

data/languages/korean.txt
src/game/server/ddracechat.cpp

Update Korean language file (by 車魄)

---

src/game/client/components/effects.cpp

Fix player death effect color

---

.github/workflows/style.yml

Add vulkan libs, exclude pylint

---

src/game/server/gamecontext.cpp

Do not mute if spamprotection is off (closed #4816)

---

.gitignore

Ignore fifo files

---

src/game/editor/editor.h
src/game/editor/layer_tiles.cpp

This is a similar work that was carried out by @C0D3D3V on introducing enumeration rather than magic numbers.

Added direction enumeration for the editor

---

src/engine/client/backend_sdl.cpp
src/engine/client/backend_sdl.h

Fix Debian 9 compilation

---

data/languages/french.txt

Update French translations (by T tee)

---

data/languages/simplified_chinese.txt
data/languages/traditional_chinese.txt

Update Chinese translations by cheeser0613

---

README.md

Add note about gmock version (fixes #4853)

---

src/engine/client/backend/opengl/backend_opengl.cpp
src/engine/client/backend/opengl/backend_opengl3.cpp
src/engine/client/backend_sdl.cpp
src/engine/client/backend_sdl.h
src/engine/client/graphics_threaded.cpp
src/engine/client/graphics_threaded.h
src/engine/client/video.cpp
src/engine/client/video.h
src/engine/server/databases/connection_pool.cpp
src/engine/server/databases/connection_pool.h
src/game/client/components/controls.cpp
src/game/client/components/controls.h
src/game/client/components/maplayers.cpp
src/game/client/components/maplayers.h

Still training my regex fu :smile:

Format member variable's name correctly

---

src/game/client/components/menus_settings.cpp

Add dropdown icon

---

src/engine/client/backend/vulkan/backend_vulkan.cpp

Fix text texture name Texture -> TextureOutline

---

data/languages/simplified_chinese.txt
data/languages/traditional_chinese.txt

Update Chinese translations again

---

README.md

Add comment about generating ddnet-libs for WebAssembly in the README

---

data/languages/korean.txt

Update Korean translations by CHaBek

---

src/game/server/teams.cpp

Thanks to c0d3d3v for noticing

Fix team not started message (fixes #4884)

---

data/languages/simplified_chinese.txt

Update Simplified Chinese translations

---

src/game/server/scoreworker.cpp
src/test/score.cpp

Fixes #4810
Solution based on the suggestion from @def- .

Fix /top5 inconvenience / local ranking problem

---

data/languages/catalan.txt

update catalan translation

---

src/game/client/components/chat.cpp
src/game/client/components/chat.h

Fix whisper sending/receiving differentiation

---

src/engine/client/backend/vulkan/backend_vulkan.cpp

fixes #4891
@Chairn can you test if this is enough.
Also I'd like to open an issue on SDL2. So some minor questions:
Is libvulkan1.so installed on your system?
What does `vulkaninfo | grep driverID` show on your system?

Vk only allow asserts after initialization

---

src/game/client/components/ghost.cpp
src/game/client/components/menus_ingame.cpp
src/game/client/components/players.cpp

https://streamable.com/oquu51
reported by lomination 
fixes #4207 again

fix gohst transparency of hook hand and ninja skin

---

src/engine/client/video.cpp

 Fix container overflow in video renderer (fixes #4932)

---

src/engine/client/backend/vulkan/backend_vulkan.cpp

This fixes screenshots & demo->video rendering on some resolutions
@Chairn probs also for you since you probs interested ^^

Respect row pitch of temporary image

---

src/base/tl/algorithm.h

Remove unused bubble sort (finally)

---

src/game/server/alloc.h

Format global static variable name in macro

---

src/engine/client/backend/vulkan/backend_vulkan.cpp

Fix multi sampling

---

README.md

update new code docs location

---

src/engine/client/client.cpp
src/engine/server/server.cpp

Minor refactoring: Move/Merge variable declarations with assignments in CServer and CClient

---

src/game/editor/editor.cpp

Thanks to @c0d3d3v for debugging my left right weakness lmao.
I initially intended left click but that was conflicting with navigation already so I switched it. But not the description.

Its is not ctrl+leftclick but ctrl+rightclick

---

src/game/client/gameclient.cpp

fix pistol sounds for BW servers

---

src/game/server/entities/character.cpp

Shouldn't affect anything, but better safe than sorry.

Initialize CCharacter::m_NumInputs of game server

---

src/game/client/ui_ex.cpp

Unselect text after ctrl-u

---

src/engine/client/backend/vulkan/backend_vulkan.cpp
src/engine/graphics.h

Respect GPU type better

---

src/game/client/components/menus_settings.cpp

Inform about client restart when changing GPU

---

src/game/client/prediction/entities/character.cpp
src/game/server/entities/character.cpp

make super ignore livefreeze, fix #4973

---

src/engine/client/backend/vulkan/backend_vulkan.cpp

fix clamp of m_ThreadCount

---

scripts/move_sqlite.py

Fix move_sqlite (fixes #4902)

---

src/game/server/ddracechat.cpp

Enable swapping in team 0

---

.github/workflows/build.yaml
src/engine/server/databases/mysql.cpp

Add mysql to github workflow in ubuntu 20.04

---

src/base/math.h
src/game/client/components/menus_settings.cpp

Not sure if we want to, there are some easy functions like this we could
take from stdlib now

Use std::clamp

---

src/game/client/components/tooltips.cpp
src/game/client/components/tooltips.h

fix tooltips rendering when they shouldn't, fixes #5035

---

src/game/client/prediction/gameworld.cpp
src/game/gamecore.cpp
src/game/server/entities/character.cpp
src/game/server/entities/character.h
src/game/server/gameworld.cpp
src/game/server/teams.cpp

Needs more testing, but first test looks good
https://streamable.com/ypra11

do not release the hooks if you swap

---

src/game/server/ddracechat.cpp

Rules are chat responses too

---

src/engine/server/server.cpp
src/engine/server/server.h

fixes #4785 @ChillerDragon test pls, bcs i cannot reprod

Use dynamically allocated memory for the CacheChunk

---

src/test/teehistorian.cpp

Written this for #5032, might be helpful for others :)

Output corresponding array to EXPECTED in teehistorian test cases

---

src/engine/server/server.cpp

do not assert on entities without snap id

---

src/game/server/ddracechat.cpp

Fix /practice chat responses and a few others

---

src/game/client/components/menus.cpp
src/game/client/components/menus_browser.cpp
src/game/client/components/menus_demo.cpp
src/game/client/components/menus_ingame.cpp
src/game/client/ui.cpp
src/game/client/ui.h
src/game/client/ui_ex.cpp
src/game/editor/editor.cpp

Remove unused DoButtonLogic pText argument

---

src/game/client/components/tooltips.cpp

Thanks to cheeser0613 for report

Update tooltip text after changing language

---

src/game/client/components/menus_settings.cpp
src/game/client/gameclient.cpp
src/game/client/render.cpp
src/game/client/render.h
src/game/client/render_map.cpp
src/game/client/ui.h
src/game/editor/editor.cpp

Cleanup CRenderTools

---

src/game/server/ddracechat.cpp

Add Cellegen, srdante, Nouaa to credits

---

data/languages/french.txt

update french translations

---

src/game/editor/layer_quads.cpp
src/game/editor/layer_tiles.cpp

Refactoring: Use std::swap in editor

---

data/languages/dutch.txt

https://discord.com/channels/252358080522747904/293493549758939136/976214341139456020

Updated dutch language by Ronan

---

src/base/log.cpp

The `CWindowsConsoleLogger` uses `WriteConsoleW` which only works when the standard output handle is a console (`GetFileType` returns `FILE_TYPE_CHAR`).
When redirecting output into a file, `GetFileType` returns `FILE_TYPE_DISK`. For this case a `CWindowsFileLogger` is added that uses `WriteFile` instead. This works on raw bytes, so the UTF-8 encoded lines are written directly.
When pipeing output or when using custom terminals like Git Bash, `GetFileType` returns `FILE_TYPE_PIPE`. I can't find any documentation how to correctly interact with a pipe stdout handle. So in this case, `WriteFile` is also used, because it works for me with cmd, PowerShell and Git Bash.
Lastly, if the output device is unknown, the default `CLoggerAsync` without ANSI colors is used as fallback.
This fixes output …

Handle file/pipe stdout and add fallback on Windows

---

CMakeLists.txt

@Kaffeine lld is used on some systems, we also have instructions for mold in readme, both are faster than gold.

No gold preference (fixes #5136)

---

src/engine/server/databases/mysql.cpp

Add override in mysql code too (fixes #5139)

---

src/game/client/components/controls.cpp
src/game/client/gameclient.cpp
src/game/client/prediction/entities/character.cpp
src/game/client/prediction/gameworld.h
src/game/server/player.cpp

fixes #4653
- [?] Changed no physics that affect existing maps

keep input if chat is closed

---

src/game/client/components/menus_settings_assets.cpp

fixes #5168
should maybe next time test if everything still works before I let merge something big xD

fix HUD assets Tab

---

.gitignore

New tool from https://github.com/ddnet/ddnet/pull/5119

Ignore stun tool binary

---

src/game/client/components/maplayers.cpp
src/game/client/render.h
src/game/client/render_map.cpp
src/game/editor/editor.h

Add missing nanosecond conversions

---

src/engine/shared/http.h

Fix 0 byte malloc in register.cpp (fixes #5187)

---

scripts/parse_drmingw.sh

Don't assume script name/path

---

data/languages/dutch.txt

Update Dutch translations by Ronan

---

src/game/server/teams.cpp

Only record swap in teehistorian if active

---

src/game/client/components/console.cpp

Fix crash when graphics init failed (fixes #5237)

---

src/game/client/components/console.cpp
src/game/client/components/emoticon.cpp
src/game/client/components/menus.cpp
src/game/client/components/menus.h
src/game/client/components/spectator.cpp
src/game/client/gameclient.cpp
src/game/client/render.cpp
src/game/client/render.h
src/game/client/ui.cpp
src/game/client/ui.h
src/game/editor/editor.cpp

Refactoring: Move CMenus::UseMouseButtons to CUI::SetEnabled, extract CRenderTools::RenderCursor

---

src/base/color.h
src/game/editor/editor.cpp

Found with -Wcomma using clang.

Fix possible misuse of comma

---

data/autoexec_server.cfg
src/base/log.cpp
src/engine/shared/config_variables.h

Add loglevel config (fixes #5178, fixes #5174)

---

src/engine/shared/network_stun.cpp

Fix clamp in CStun::Update (fixes #5282)

---

.github/workflows/build.yaml
.github/workflows/clang-sanitizer.yml
memcheck.supp
scripts/integration_test.sh

Add valgrind to integration test

---

src/game/client/gameclient.cpp
src/game/client/gameclient.h

Refactoring: Replace CGameClient::CStack with std::vector<class CComponent *>

---

src/game/server/gamecontext.cpp

Log chat by default, put it onto `INFO` instead of `DEBUG` level

---

src/game/client/gameclient.cpp

Fix wrong iterator being used for inserting into vector

---

src/game/client/gameclient.cpp

Reported by kiwq#4737 on Discord.
This issue was revealed by the addition of a `std::set` into `CCharacterCore`, I'm unsure why the copy constructor of `std::set` didn't work. It might be a good idea to check and see if there is a further underlying issue @C0D3D3V.
<details>
<summary>Backtrace</summary>
```c++
#0  __gnu_cxx::new_allocator<std::_Rb_tree_node<int> >::construct<int, int const&> (this=0x7fffffff95e8, __p=0x555558935fd0) at /usr/include/c++/10.2/ext/new_allocator.h:150
No locals.
#1  0x0000555555831100 in std::allocator_traits<std::allocator<std::_Rb_tree_node<int> > >::construct<int, int const&> (__a=..., __p=0x555558935fd0)
at /usr/include/c++/10.2/bits/alloc_traits.h:512
No locals.
#2  0x00005555558306b7 in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, …
```

Avoid unnecessary copy leading to crash

---

src/game/server/gamecontext.cpp

Actually fix capital /WHISPER

---

src/game/client/components/freezebars.cpp
src/game/client/components/hud.cpp

fix pixel porridge in freeze and ninja bar

---

src/engine/server/server.cpp

Log rcon messages (fixes #5342)

---

src/base/log.cpp

Thanks to heinrich5991 for noticing: https://github.com/ddnet/ddnet/pull/5341#pullrequestreview-996061345

Don't write null byte

---

scripts/gen_keys.py
src/engine/client/input.cpp
src/engine/client/input.h
src/engine/input.h
src/game/client/gameclient.cpp

Almost done porting joystick support 🥁

Refactor engine input in preparation for joystick support

---

src/engine/shared/netban.cpp

I thought I had committed this for #5375, but forgot

Minor improvement for pagination

---

src/game/client/prediction/entities/laser.cpp
src/game/client/prediction/entities/laser.h
src/game/server/entities/laser.cpp
src/game/server/entities/laser.h

let lasers bounce with zero energy for one tick

---

src/game/client/prediction/entities/laser.h
src/game/server/entities/laser.h

change m_ZeroEnergyBounceInLastTick to bool

---

README.md

Update readme about ddnet-libs (fixes #5377)

---

src/game/server/scoreworker.cpp
src/test/score.cpp

/cptime fix

---

src/game/server/ddracechat.cpp

Some quality of life changes for practice
- Unfreezes when "rescued"
- Resets speed when teleporting

Some qol changes for practice

---

scripts/check_header_guards.py

Example:
Wrong header guard in src/game/bezier.h, is: #ifndef GAAME_BEZIER_H, should be: #ifndef GAME_BEZIER_H

Tell what has to be changed in check_header_guards.py

---

src/engine/shared/config_variables.h
src/game/server/player.cpp
src/game/server/player.h

It does the same job with: https://github.com/ddnet/ddnet/blob/425f07c03d30abc6b67a181b16d396acb320597c/src/game/server/gamecontroller.cpp#L48

Remove obsolete AfkTimer function

---

src/game/client/components/menus_settings.cpp
src/game/client/components/skins.cpp
src/game/variables.h

I think this was requested in the client too,
rn I dont get any skins, maybe cloudflare caching or smth. Will test the days or if someone can test it go ahead

Add community skin option to client

---

src/game/client/components/nameplates.cpp
src/game/variables.h

Remove `cl_nameplates_ha` and `cl_nameplates_ha_size`

---

src/mastersrv/src/addr.rs
src/mastersrv/src/main.rs

mastersrv: Small convenience function

---

src/game/client/components/menus_settings.cpp

Also set mouse settings to defaults

---

src/game/server/entities/door.cpp
src/game/server/entities/light.cpp

'*Char' -> '*pChr'

---

data/languages/polish.txt

Completed the translation of polish langauge (for now), fixed one translation, which wasn't correct (missing verb)

Added new translations + fixed current one

---

src/game/client/prediction/entities/character.cpp
src/game/server/entities/character.cpp
src/game/server/gamecontext.cpp
src/game/server/gameworld.cpp

Gender-neutral language

---

src/game/server/teams.cpp
src/game/server/teams.h

add penatly to the whole team

---

data/languages/brazilian_portuguese.txt

Update Brazilian Portuguese translation (supersedes #5304)

---

README.md

pnglite -> libpng in readme

---

src/engine/server/upnp.cpp

We should have a CI that builds the same cmake settings as this arch package
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ddnet-git

Fix build with -DUPNP=ON

---

README.md

Mention code browser in readme

---

scripts/integration_test.sh

integration test: print log diff for easier result check

---

README.md

Be upfront about completeness of the autogenerated code documentation

---

scripts/android/cmake_android.sh
scripts/android/files/build.gradle
scripts/android/files/gradle-wrapper.properties
src/base/log.cpp

- Video recorder off
- small fix in logger.cpp
Tested on Java-17

Fix Android build

---

src/engine/client/backend/opengl/backend_opengl.cpp

Add missing capability for GLES backend

---

src/game/client/components/skins.h

Abort skin downloads too (fixes #5505)

---

CMakeLists.txt
scripts/integration_test.sh

Also print out more of the diff
Should help with debugging sporadic failures like https://github.com/ddnet/ddnet/runs/7058704316?check_suite_focus=true

Don't register integration test servers

---

src/game/server/entities/character.cpp
src/game/server/gamemodes/DDRace.cpp

send our old server messages till we come up with a better way to tell the player some effects on him have changed. See https://github.com/ddnet/ddnet/issues/5510

revert to send server messages for now

---

data/languages/french.txt

Updated french language

---

src/base/hash_libtomcrypt.cpp
src/engine/client/client.cpp
src/engine/shared/config.cpp
src/engine/shared/huffman.cpp
src/game/client/components/chat.cpp
src/game/gamecore.h
src/game/mapbugs.cpp
src/game/server/ddracechat.cpp

Fix some unsafe define that can expand in an undesired way if used with some bitwise operator (very unlikely though)

Fix more unsafe define

---

src/engine/client/backend_sdl.cpp
src/engine/client/client.cpp
src/engine/shared/datafile.cpp
src/engine/shared/datafile.h
src/engine/shared/snapshot.cpp
src/engine/shared/snapshot.h

Minor tweaks to keep ODR across translation units

---

data/languages/german.txt

I updated the language file. Added new sentences and changed an existing one.

Updated german language file

---

src/game/client/components/hud.cpp

Use for-each loop in `CHud::ResetHudContainers` to reduce duplicate code

---

src/engine/client/text.cpp
src/engine/textrender.h
src/game/client/components/chat.cpp
src/game/client/components/chat.h
src/game/client/components/hud.cpp
src/game/client/components/killmessages.cpp
src/game/client/components/nameplates.cpp
src/game/client/ui.cpp

For #5143
Maybe it helps identifying the problem earlier, maybe not^^

(A bit) safer interface for text containers

---

src/game/client/components/menus_browser.cpp
src/game/client/components/tooltips.cpp
src/game/client/components/tooltips.h

Minor client refactorings

---

src/engine/client/backend_sdl.cpp
src/engine/client/client.cpp
src/engine/client/graphics_threaded.cpp
src/engine/client/input.cpp
src/engine/client/text.cpp
src/engine/gfx/image_loader.cpp
src/game/client/components/maplayers.cpp
src/game/editor/io.cpp
src/game/editor/layer_quads.cpp
src/test/bytes_be.cpp
src/test/compression.cpp
src/test/prng.cpp
src/test/score.cpp
src/test/secure_random.cpp
src/test/teehistorian.cpp

Fix minor clang-tidy 14 issues

---

src/base/system.cpp
src/engine/shared/storage.cpp
src/game/client/components/menus_start.cpp

Search in $PATH for server executable (fixes #5594)

---

src/game/client/components/menus.cpp

Fixed the alignment issues in Popups.
Examples:
Before
After
Its my first PR for actual code. Please indulge me. :) 
We still need to get rid of the "ExtraAlign" variable and only use TextWidth().
But somehow TextWidth() doesn't work properly in this case. 
Hopefully a more experienced collaborator can have a look at these lines:
https://github.com/ddnet/ddnet/pull/5615/commits/bbca48aa5b5a35e35d5174d26ff3dac5a96ff785#diff-3aebb8cc835bb888d687b51e9dcfc0cda5326d89fd1c97ff83d85c00b82ed116L1656-R1657

Fix Text Alignments in Popups

---

src/engine/shared/network.cpp
src/engine/shared/network.h

Minor refactoring of `CNetBase`

---

src/engine/client/favorites.cpp
src/game/client/components/menus_settings.cpp

Fix some variable names

---

src/game/client/components/chat.cpp
src/game/client/components/maplayers.cpp

Fix null pointer / out of bounds accesses in chat and maplayers

---

data/languages/russian.txt

Added missing translations and also made some of older text more consistent.

Russian Translation

---

src/game/editor/editor.cpp

Fix shift + left click in editor (fixes #5626)

---

src/base/hash_openssl.cpp
src/base/system.cpp
src/engine/client/text.cpp
src/engine/server.h

Strangely I didn't get all of the errors.

Fix clang-tidy 14 mingw issues (fixes #5612)

---

.github/workflows/style.yml
datasrc/compile.py
datasrc/crosscompile.py
datasrc/datatypes.py
datasrc/network.py
datasrc/seven/compile.py
datasrc/seven/datatypes.py
other/dmgsettings.py
scripts/check_header_guards.py
scripts/check_identifiers.py
scripts/checksum.py
scripts/extract_identifiers.py
scripts/fix_style.py
scripts/gen_keys.py
scripts/generate_fake_curl.py
scripts/generate_unicode_confusables_data.py
scripts/generate_unicode_tolower.py
scripts/git_revision.py
scripts/hash_passwords.py
scripts/import_file_score.py
scripts/languages/analyze.py
scripts/languages/copy_fix.py
scripts/languages/twlang.py
scripts/languages/update_all.py
scripts/move_sqlite.py
scripts/tw_api.py
scripts/unicode.py
scripts/wordlist.py

So far only done scripts directory, will do the rest if this is
considered good

Require Python 3.6 (f-strings) and fix pylints

---

src/game/server/gamecontroller.cpp

Fix rotating plasma by Robyt3 (fixes #5666)

---

src/game/editor/popups.cpp

See https://github.com/ddnet/ddnet/issues/5675#issuecomment-1200141378. Though I can't reproduce the UBSAN error with my compiler.

Fix accesses to vector with index -1 by adding static button IDs

---

src/engine/client/serverbrowser.cpp

Less code and i find it more clear :)

Use copy assignment rather than copy variable one by one

---

src/game/editor/layer_tiles.cpp

Fix editor image delete

---

src/engine/server.h

Add documentation for `IServer::GetClientVersion`

---

src/game/editor/editor.cpp

Fix shift-leftclick-drag with empty selection to delete (fixes #5705)

---

src/game/client/components/maplayers.cpp

Check fully transparent quads with negative alpha

---

src/game/client/components/binds.cpp
src/game/client/components/console.cpp
src/game/gamecore.cpp
src/game/server/gamecontext.cpp

Various minor refactorings cherry-picked from upstream

---

src/game/client/components/console.cpp

Use current backlog page instead of old (fixes #5719)

---

src/engine/client/client.cpp
src/engine/client/client.h
src/game/client/components/debughud.cpp

Various refactorings to `CGraph`. Most of them are cherry-picked from upstream.

Refactor `CGraph`

---

src/game/client/components/freezebars.cpp

small fix for #5729

---

src/game/editor/io.cpp

Minor refactoring of editor IO

---

data/languages/hungarian.txt

Update hungarian language file (by Cellegen)

---

scripts/integration_test.sh
src/engine/client/client.cpp
src/engine/server.h
src/engine/server/server.cpp
src/engine/server/server.h
src/engine/shared/demo.cpp
src/game/server/gamecontext.cpp

Various fixes for server demo recording and playback

---

data/languages/serbian.txt
data/languages/serbian_cyrillic.txt

Update serbian translation

---

scripts/integration_test.sh

This makes it easier to debug issues when they appear in the CI.
Closes #5684.

Always print warnings/failures in integration test

---

src/game/server/save.cpp

Clarify save message on team member in '/spec' mode

---

src/game/client/components/menus_settings.cpp

Refind skins after reload

---

src/engine/gfx/image_loader.cpp

else libpng will kill the thread on an error bcs it's a fatal error.
broken skin can be found in discord bugs channel weeb_okayu

Fix png error handling by setting jmpbuf

---

src/game/server/gamecontext.cpp
src/game/server/teams.cpp

First send message to team, then kill team (fixes #5721)

---

src/game/editor/editor.cpp

Fix hotkeys (scroll regions) not working in editor

---

src/game/editor/editor.cpp
src/game/editor/popups.cpp

Fix minor issues with editor value selectors

---

src/game/editor/popups.cpp

Refactor editor sound selection popup using `CScrollRegion`, minor refactoring

---

src/base/system.cpp

ShellExecute may load additional DLLs in the current context, which might change the FPU control word.
Another potential fix for #5744.
Sources:
- https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6457572
- https://web.archive.org/web/20070730055602/http://tolstoy.newcastle.edu.au/R/devel/06/02/4262.html
- http://www.delphigroups.info/2/d3/420953-2.html (only available in Google Cache for me)
- https://github.com/openjdk-mirror/jdk7u-jdk/blob/f4d80957e89a19a29bb9f9807d2a28351ed7f7df/src/windows/native/sun/windows/awt_Desktop.cpp#L46-L49

Save and restore FPU control word when calling ShellExecute

---

src/game/editor/popups.cpp

Fix editor layer image selection not working

---

src/engine/server/databases/connection.h
src/engine/server/databases/mysql.cpp
src/engine/server/server.cpp
src/engine/shared/config_variables.h
src/engine/shared/http.cpp
src/test/score.cpp

Add sv_sql_bindaddr (fixes #5830)

---

src/game/server/scoreworker.cpp

Improve message on failed load

---

src/base/lock_scope.h
src/tools/map_create_pixelart.cpp
src/tools/map_replace_area.cpp

Fix Clang 15 warnings (fixes #5548)

---

.github/pull_request_template.md

Tell new devs not to feel intimidated

---

src/engine/client/client.cpp
src/engine/client/sound.cpp
src/engine/client/sound.h
src/engine/graphics.h
src/engine/input.h
src/engine/kernel.h
src/engine/shared/kernel.cpp
src/engine/sound.h

Minor cleanup in preparation for the replacement I'll push for #5092.

Let CKernel clean-up. Use unused CSound::Shutdown

---

src/game/client/components/menus.cpp

Fix UI elements behind color picker background being selectable, refactor color picker

---

src/engine/shared/config_variables.h
src/game/client/components/menus_settings.cpp

Laser menu tweaks; Changed some default colors

---

src/engine/client/client.cpp
src/engine/shared/config_variables.h
src/game/client/components/menus_settings.cpp

Remove cl_http_map_download

---

data/languages/french.txt
data/languages/korean.txt
data/languages/portuguese.txt
data/languages/simplified_chinese.txt
data/languages/spanish.txt
data/languages/traditional_chinese.txt
data/languages/turkish.txt

Traditional Chinese links to Simplified Chinese wiki
Portuguese links to Brazilian Portuguese wiki
Rest is 1:1 match

Link to localized Wikis even if they are not complete

---

scripts/move_sqlite.py

https://github.com/techouse/sqlite3-to-mysql/
Better method than text file with manual seds

Update move_sqlite.py to use sqlite3mysql

---

src/game/editor/editor.cpp
src/game/editor/editor.h

Replace magic numbers with enum `EShowEnvelope`

---

data/autoexec_server.cfg
man/DDNet-Server.6
man/DDNet.6
src/engine/shared/config_variables.h
src/game/server/ddracechat.cpp
src/game/server/gamemodes/DDRace.cpp

Use ddnet.org on manpages

---

.github/workflows/build.yaml
README.md

Try code coverage (fixes #5873)

---

codecov.yml

Disable codecov comments in PRs

---

src/engine/shared/storage.cpp

Improve storage error handling, minor refactoring of storage

---

src/game/client/components/menus.cpp

Don't show home button ingame

---

.github/workflows/build.yaml

https://docs.codecov.com/docs/flags

Set coverage flags to separate coverage (fixes #5898)

---

src/engine/client/serverbrowser.cpp
src/engine/serverbrowser.h
src/engine/shared/config_variables.h
src/game/client/components/menus_browser.cpp

Support multiple values to search/exclude (fixes #4119)

---

src/game/client/components/menus_ingame.cpp

Don't overlap menu + debug messages (fixes #5914)

---

src/mastersrv/src/addr.rs

fix import on mastersrv

---

src/engine/docs/snapshots.txt

Grammer fix in snapshot doc "haven't" -> "hasn't"

---

src/engine/client.h
src/engine/client/client.cpp
src/engine/client/client.h
src/engine/docs/snapshots.txt
src/engine/shared/snapshot.cpp
src/engine/shared/snapshot.h
src/game/client/projectile_data.cpp

Incorporate const added in those upstream commits:
https://github.com/teeworlds/teeworlds/commit/d86d576217eeb843c822568f6b8f97ac852ac0d7
https://github.com/teeworlds/teeworlds/commit/e6b8518b49c353963af35efad8465d9066fb819e

Constify snap more (inspired by upstream)

---

src/engine/client/client.cpp
src/engine/client/discord.cpp
src/engine/client/serverbrowser.cpp
src/engine/client/serverbrowser.h
src/engine/client/steam.cpp
src/engine/discord.h
src/engine/steam.h
src/test/netaddr.cpp

Only announce servers using Steam/Discord integration which are registered

---

.gitmodules

Otherwise it downloads 250mb of data you probably don't want.

Make submodules shallow by default

---

README.md

Add note in README about how to convert shallow to full clone

---

README.md

add instructions for better git blame on readme

---

README.md

add gentoo to readme

---

README.md

Add even better blame instructions

---

README.md

Code blocks marked with indentation only work when there is an empty line before them.

Add line break in README to fix code block

---

src/game/server/gamecontext.cpp

Fix typo: https://github.com/ddnet/ddnet/blob/6c3d0e999b92b30b48ea1c220a03ff1495ce400b/src/game/mapbugs_list.h#L3

Fix example name in mapbug description

---

README.md

Sort dependencies alphabetically in README.md

---

src/game/variables.h

Fix duplicate description of cl_default_zoom_level

---

src/base/system.cpp

As `_control87` doesn't seem to be available for some MinGW compilers.
Closes #5969.

Use `fegetenv`/`fesetenv` instead of `_control87` on Windows

---

README.md

Tell the default value in README for flags

---

data/languages/brazilian_portuguese.txt

P.s.: please squash commits when merging.

Update Brazilian Portuguese translation 

---

src/game/client/components/voting.cpp

Should make it a bit clearer how to call a vote from F1

Improve callvote arguments by making them more specific

---

src/game/editor/editor.cpp
src/game/editor/popups.cpp

Fix Ctrl+F hotkey not checking for Ctrl key, minor improvement to tile details popup layout

---

.gitignore

chore(Gitignore): add ignore all folders cmake-build-* for Clion

---

.github/workflows/build.yaml

Fix dmgbuild issue by adding binary install directory to PATH (fixes #6005)

---

src/engine/editor.h
src/game/editor/editor.cpp
src/game/editor/editor.h
src/game/editor/io.cpp

Also append sounds when appending a map to another map

---

README.md
other/vim/ftdetect/ddnet-cfg.vim
other/vim/syntax/ddnet-cfg.vim

Example with the carbonfox theme:

add vim syntax files for config files

---

src/game/editor/editor.cpp

Fix height and margin of sound and image popups

---

src/engine/client/client.cpp
src/engine/server/main.cpp
src/engine/server/server.cpp

Write log and sqlite files to storage unless given as absolute path

---

src/engine/client/backend/opengl/backend_opengl.cpp
src/engine/client/input.cpp
src/game/client/components/console.cpp
src/game/client/components/menus_settings.cpp
src/game/client/prediction/entities/pickup.cpp
src/game/server/entities/dragger.cpp
src/game/server/entities/dragger_beam.cpp
src/game/server/entities/gun.cpp
src/game/server/entities/light.cpp
src/game/server/entities/pickup.cpp
src/game/server/gamecontext.cpp
src/test/compression.cpp

Use traditional casts instead of functional-style casts

---

src/engine/client/client.cpp
src/game/client/components/scoreboard.cpp

Minor refactoring of demo related code

---

src/game/client/prediction/entities/character.cpp
src/game/client/prediction/entities/pickup.cpp
src/game/client/prediction/entities/projectile.cpp
src/game/client/prediction/gameworld.cpp
src/game/server/entities/character.cpp
src/game/server/entities/dragger.cpp
src/game/server/entities/gun.cpp
src/game/server/entities/pickup.cpp
src/game/server/entities/projectile.cpp
src/game/server/gamecontext.cpp
src/game/server/gamecontroller.cpp

Fix CGun::Fire server crash (fixes #6023)

---

src/android/android_main.cpp
src/base/system.h
src/base/unicode/confusables.cpp
src/test/hash.cpp
src/test/str.cpp
src/test/thread.cpp

Add more tests for hashing, `CSemaphore` and utf8 confusables

---

other/vscode/ddnet.code-workspace

As discussed with @edg-l rust-analyzer is the extension to use

update workspace with better rust defaults

---

src/engine/client/client.cpp
src/engine/client/client.h

Remove // in ddnet:// url handler

---

.github/workflows/build.yaml
.github/workflows/codeql-analysis.yaml

Try using default MariaDB server version (fixes #6079)

---

other/vscode/ddnet-cmake-tools-kits.json
other/vscode/ddnet.code-workspace
src/engine/client/backend_sdl.cpp
src/engine/client/backend_sdl.h

Pr fix uninit

---

src/game/server/ddracechat.cpp

Add credits

---

src/engine/client/client.cpp
src/engine/client/client.h
src/engine/client/serverbrowser.cpp
src/engine/client/serverbrowser.h

Some refactorings from teeworlds/teeworlds#3090 and more.

Minor refactoring of `CServerBrowser`

---

src/engine/friends.h

Bump friends limit from 1024 to 4096 (fixes #6096)

---

src/engine/shared/netban.cpp
src/engine/shared/netban.h
src/game/editor/editor.cpp
src/game/editor/editor.h

Duplicate code was found with [Duplo](https://github.com/dlidstrom/Duplo).

Reduce duplicate code in editor and netban by extracting methods

---

scripts/move_sqlite.py

Adapt move_sqlite.py script to _backup tables

---

src/game/client/components/menus_settings.cpp

Add button that tells you how to save power

---

src/game/server/scoreworker.cpp

Fix updating teamranks

---

src/engine/server/server.cpp

Fix conflict resolution between #6013 and #5948

---

README.md

Remove duplicate `rust` mention from README Arch Linux packages

---

CMakeLists.txt
scripts/languages/twlang.py
src/engine/client/backend/backend_base.h
src/engine/client/backend/null/backend_null.cpp
src/engine/client/backend/null/backend_null.h
src/engine/client/backend/opengl/backend_opengl.cpp
src/engine/client/backend/opengl/backend_opengl.h
src/engine/client/backend/vulkan/backend_vulkan.cpp
src/engine/client/backend_sdl.cpp
src/engine/client/backend_sdl.h
src/engine/client/graphics_threaded.cpp
src/engine/client/graphics_threaded.h
src/engine/shared/localization.h
src/game/client/components/menus.cpp
src/game/client/components/menus_browser.cpp
src/game/client/components/menus_ingame.cpp

so it doesn't assert & shows a message box with the error and some tips
Trying to get more useful information visible to the user on asserts
("dsadsa" ofc testing string)
Haven't tested lot, it's lots of smaller changes to the code, hopefully didn't oversee smth^^

Improve error handling in vulkan

---

src/game/client/gameclient.cpp

Remove spammy log (thanks Skeith)

---

.gitignore

See https://www.sqlite.org/tempfiles.html

Also ignore sqlite-shm and sqlite-wal files

---

src/game/client/prediction/gameworld.cpp

Tho i didnt see a wrong prediction with hook which probably makes sense, it probs only affects weapons, as thats the main part the server code was updated for

Adjust no weak prediction to updated server code

---

.github/workflows/build.yaml

Fix macOS CI with existing 2to3 binary

---

.github/workflows/build.yaml
README.md

Instruct to use rustup/rustc-mozilla on older Debian/Ubuntu (fixes #6145)

---

src/game/client/components/menus_demo.cpp
src/game/client/components/menus_settings.cpp
src/game/client/components/menus_settings_assets.cpp

Add tooltips for the buttons that open directories and files

---

.gitignore
CMakeLists.txt
cmake/BuildVulkanShaders.cmake

Use CMake cache instead of extra file for shader compile, fix typos

---

src/mastersrv/README.md

Add README.md for the mastersrv, briefly explaining the setup

---

src/game/client/components/menus_browser.cpp

Render a slim bar below the server browser listbox to show the loading progression, instead of showing a percentage on the Refresh button, as suggested in https://github.com/ddnet/ddnet/pull/5878#issuecomment-1257227947.
The margin around the bottom status elements is removed to make more space and improve the alignment of the elements with the rest of the server browser.
https://user-images.githubusercontent.com/23437060/209000517-76fea4a1-e2d2-41de-b5af-1d907589e30e.mp4
(I used `br_max_requests 1` for this video and used a bind to activate `leak_ip_address_to_all_servers`)
Screenshot comparison for margins:
- Before: 
- After:

Render bar below server browser to show loading progression

---

src/game/editor/editor.cpp
src/game/editor/editor.h
src/game/editor/popups.cpp

Deactivate editor hotkeys while dialog or editbox is active, fix other minor issues

---

.github/workflows/build.yaml

Try to fix macOS CI failure again

---

.gitignore

Ignore .spv vulkan files for in-directory builds

---

src/engine/shared/http.cpp

Just quiet curl warnings for now

---

src/game/server/scoreworker.cpp

Should help with #6194. I don't have my mysql setup with me right now, so I can't check if I can find out what is going wrong. I'll see if I can do that tomorrow :)

Add more debug info to teamrace to figure out how duplicate ranks occur

---

other/bundle/client/Info.plist.in
src/engine/client/client.cpp
src/engine/client/input.cpp
src/engine/client/input.h
src/engine/input.h

Should work automatically on first time running client.
See https://hublog.hubmed.org/archives/001154

Automatically register ddnet:// url handler on macOS

---

src/game/server/scoreworker.cpp

Log whether deleting ranks from _backup tables fails due to locking issues in sqlite.

Log more errors in sql code

---

.github/workflows/clang-sanitizer.yml
src/base/system.cpp
src/test/net.cpp

Run C++ unit tests with sanitizers (fixes #6205)

---

src/engine/shared/snapshot.cpp
src/engine/shared/snapshot.h

Fix undefined behavior when unpacking snapshot deltas

---

src/game/server/teams.cpp
src/game/server/teams.h

Swap times should be per player, not per team (fixes #6155)

---

src/engine/client/serverbrowser.cpp
src/game/client/components/menus.h
src/game/client/components/menus_browser.cpp

Thanks to bencie for discussion

Implement exact matches in search and exclude strings

---

src/engine/client/backend/backend_base.h
src/engine/client/backend/vulkan/backend_vulkan.cpp
src/engine/client/backend_sdl.cpp

Less translations for vk errors from backend

---

src/engine/client/backend/vulkan/backend_vulkan.cpp

For integrated and discrete GPUs always prefer what comes first in the list

---

data/languages/russian.txt

Update russian.txt to incoming 16.7 update

---

data/languages/brazilian_portuguese.txt

Minor brazilian portuguese fix (by Akari)

---

src/base/system.h
src/base/vmath.h

Minor base refactoring

---

src/game/server/gameworld.cpp
src/game/server/gameworld.h
src/game/server/teams.cpp

Remove projectiles on team change

---

data/languages/french.txt

Add new french translations for 16.7

---

src/antibot/antibot_data.h
src/engine/server.h
src/engine/server/antibot.cpp
src/engine/server/server.cpp
src/engine/server/server.h

Hand the client IP addresses to the antibot module

---

src/engine/client/backend/vulkan/backend_vulkan.cpp

Missing parameter in error list

---

src/engine/client/client.cpp

Add forgotten call

---

src/game/editor/editor.cpp
src/game/editor/editor.h

Support longer file/folder names in editor

---

src/engine/server/server.cpp
src/game/server/gamecontext.cpp

Don't count (connecting) players for voting

---

src/game/editor/editor.cpp
src/game/editor/editor.h
src/game/editor/layer_tiles.cpp
src/game/editor/popups.cpp
src/game/mapitems.h

Minor cleanup of editor and mapitems

---

data/languages/persian.txt

Fix Persian language crash (fixes #6310)

---

CMakeLists.txt
src/base/system.cpp

Only use pthread_attr_set_qos_class_np if it's available

---

src/base/system.cpp
src/base/system.h
src/engine/client/client.cpp
src/engine/server/databases/connection_pool.cpp
src/game/client/components/statboard.cpp
src/game/collision.cpp
src/game/editor/editor.cpp
src/game/server/ddracechat.cpp
src/game/server/ddracecommands.cpp
src/game/server/entities/character.cpp
src/game/server/gamecontext.cpp
src/game/server/teehistorian.cpp

Use `str_copy` instead of `str_format`, minor fixes and refactoring

---

data/languages/persian.txt

Update Persian translations (by Quick)

---

src/engine/client/client.cpp

Fix wrong system name being used for logging client git revision

---

src/engine/client/graphics_threaded.cpp

Add error message when saving screenshot fails

---

src/game/editor/editor.cpp
src/game/editor/editor.h

Add a refresh button to the editor file browser

---

.github/workflows/build.yaml

Fix ubuntu workflow (fixes #6341)

---

src/base/system.cpp
src/base/system.h
src/engine/client/text.cpp
src/game/editor/io.cpp
src/tools/map_optimize.cpp

Minor refactoring of base `mem_*` functions

---

src/engine/client/text.cpp
src/engine/textrender.h
src/game/client/components/chat.cpp
src/game/client/components/console.cpp
src/game/client/components/debughud.cpp
src/game/client/components/hud.cpp
src/game/client/components/killmessages.cpp
src/game/client/components/menus.cpp
src/game/client/components/menus_browser.cpp
src/game/client/components/menus_demo.cpp
src/game/client/components/menus_ingame.cpp
src/game/client/components/menus_settings.cpp
src/game/client/components/menus_settings_assets.cpp
src/game/client/components/menus_start.cpp
src/game/client/components/motd.cpp
src/game/client/components/nameplates.cpp
src/game/client/components/scoreboard.cpp
src/game/client/components/spectator.cpp
src/game/client/components/statboard.cpp
src/game/client/components/tooltips.cpp
src/game/client/render_map.cpp
src/game/client/ui.cpp
src/game/editor/editor.cpp
src/game/editor/layer_tiles.cpp
src/game/editor/popups.cpp

Various refactoring of text render

---

.github/workflows/style.yml
src/engine/client/client.cpp
src/engine/server/databases/mysql.cpp
src/engine/shared/websockets.cpp
src/game/client/components/killmessages.cpp
src/game/server/gamecontext.cpp
src/game/server/gamecontext.h
src/game/server/save.cpp
src/test/score.cpp

Also verify that absolute imports are done using `#include <>` in CI.

Mark absolute #includes as absolute

---

src/game/server/gamecontext.cpp

Fix invalid json (partially fixes #6366)

---

.gitignore

The file is created when running gdb with ``set history save on``

Ignore .gdb_history

---

other/vim/syntax/ddnet-cfg.vim

vim syntax support comments (closed #6399)

---

README.md

Document vim and neovim syntax install

---

README.md

Remove note about it being neovim specific

---

src/game/editor/editor.cpp
src/game/editor/editor.h
src/game/editor/layer_tiles.cpp

Fix some potentially undefined editor member variables

---

src/base/system.cpp
src/base/system.h
src/game/client/components/menus.cpp
src/game/client/components/menus.h
src/game/client/components/menus_start.cpp

Refactor server process launching from client

---

src/game/editor/editor.cpp
src/game/editor/editor.h
src/game/editor/popups.cpp

Allow choosing envelopes by typing its ID.

use ValueSelector for envelope selection #3598

---

src/game/editor/editor.cpp

add show directory button in filedialog closes #6422

---

src/game/client/ui.cpp
src/game/editor/editor.cpp

Support holding shift for slow mouse with color pickers

---

src/base/system.cpp
src/base/system.h
src/game/editor/editor.cpp
src/game/editor/editor.h
src/game/editor/popups.cpp

When using Ctrl+S:
Closes #6430.

Show popups in editor when loading/saving file fails, fix minor issues with preview image

---

src/base/log.cpp

Reduces duplicate code. This also ensures that the log messages are properly zero-terminated and that they do not end with truncated unicode characters.

Use `str_format_v` for `log_log_impl`

---

src/game/editor/editor.cpp

Reveal selection when scrolling layer list with up/down arrow keys

---

data/languages/index.txt
scripts/languages/twlang.py
src/base/system.cpp
src/base/system.h
src/game/client/components/menus_settings.cpp
src/game/client/gameclient.cpp
src/game/localization.cpp
src/game/localization.h
src/test/os.cpp

Select language on first start based on user locale

---

src/tools/twping.cpp

Fix and improve twping tool

---

src/base/system.cpp

Reduce duplicate code by using loop and by merging implementation of `net_set_blocking` and `net_set_non_blocking`.

Refactor `net_set_blocking` and `net_set_non_blocking`

---

src/base/color.h

Replace usage of `fmodf` with `std::fmod`

---

src/game/server/ddracechat.cpp

Add new contributor

---

src/mastersrv/README.md

Apache `RequestHeader` needs the `headers` module

---

src/game/collision.cpp

Improve collision entity access error message

---

src/base/system.h
src/engine/textrender.h
src/game/client/components/menus.cpp
src/game/client/components/menus_browser.cpp
src/game/client/components/menus_demo.cpp
src/game/client/components/menus_ingame.cpp
src/game/client/components/menus_settings.cpp
src/game/client/components/menus_settings_assets.cpp
src/game/editor/editor.cpp
src/game/server/alloc.h

For readability and cleanliness inside the code.

Bring every Font Icon unicode into a namespace

---

src/game/client/components/menus_browser.cpp

Highlight 0XF game type

---

src/engine/client/text.cpp
src/engine/textrender.h
src/game/client/components/menus_settings.cpp
src/game/client/ui.cpp
src/game/client/ui.h

Screenshots:
- Motd:
- Before: 
- After:
- Skin (1920x1080):
- Before:
- After:
- Skin (1280x1024):
- Before:
- After:
- Message popup:
- Before:
- After:

Fix several issues with the text rendering

---

src/engine/client/text.cpp
src/engine/textrender.h
src/game/client/ui_listbox.cpp
src/game/client/ui_listbox.h

More preparation to port lineinput and IME from upstream.

More minor cleanup and enhancement of the text render

---

src/game/client/component.h
src/game/client/components/ghost.h
src/game/client/components/race_demo.h
src/game/client/gameclient.cpp

Waste some clock cycles on zero lines code removed :D
Downstream client maintainers will love it tho

Add OnNewSnapshot to component hooks

---

src/game/editor/editor.cpp
src/game/editor/editor.h
src/game/editor/popups.cpp

Reduce duplicate code. Make code more similar to upstream.

Refactor `CEditorMap::CMapInfo`

---

src/engine/client/input.cpp
src/engine/client/input.h
src/engine/input.h
src/game/client/component.h
src/game/client/components/binds.cpp
src/game/client/components/binds.h
src/game/client/components/chat.cpp
src/game/client/components/chat.h
src/game/client/components/console.cpp
src/game/client/components/console.h
src/game/client/components/menus.cpp
src/game/client/components/menus.h
src/game/client/components/menus_settings.cpp
src/game/client/components/motd.cpp
src/game/client/components/motd.h
src/game/client/gameclient.cpp
src/game/client/ui.cpp
src/game/client/ui.h
src/game/editor/editor.cpp

Minor refactoring of engine input

---

src/test/teehistorian.cpp

`CPacker` is simply used as a byte buffer in the teehistorian tests. When the number of UUIDs is increased (in the future or in downstream projects) the tests will start to fail due to the buffer size being limited to 2048 bytes. This is fixed by using an `std::vector<unsigned char>` instead.
Closes #6526.

Use dynamic size buffer in teehistorian tests instead of `CPacker`

---

src/game/server/entities/character.cpp

This fixes a bug where hook doesn't get predicted if a player has hook disabled, but can still be hooked by other players, which was reported on Discord.
It seems like this bug (and similar bugs) is caused by the client accidentally using the tuning for hook/collision instead of the flags in ddnetcharacter. By sending the correct tunings instead of the fake ones, the handling of tunezones becomes less complicated (and less bug-prone), as the client no longer needs to ignore the tunings for hook and collision (and similar) on ddnet servers.
I didn't test this with older clients yet, but tried to make sure that the conditions for sending the fake tunes are the same as they were before.

Don't send faketunes to new client versions, simplify code

---

src/game/client/components/menus_browser.cpp
src/game/client/components/menus_settings.cpp

Fix Ctrl+F not activating search box in browser and tee settings

---

src/game/editor/editor.cpp

potential fix for #6529

---

src/game/editor/editor.cpp
src/game/editor/editor.h

make envelope editor resizeable by dragging

---

src/game/editor/editor.cpp

Use `IsEntitiesLayer` to reduce duplicate code

---

src/game/client/components/hud.cpp
src/game/client/components/hud.h

Fix alpha fading in hud

---

src/base/log.cpp
src/base/system.cpp
src/base/system.h
src/engine/client/input.cpp
src/engine/shared/fifo.cpp
src/test/str.cpp

Add convenience functions to convert between UTF-8 encoded strings and wide character strings on Windows

---

src/engine/shared/packer.cpp
src/engine/shared/packer.h
src/test/packer.cpp

Add tests for `CPacker` error handling, fix minor bug, minor refactoring

---

src/engine/client/text.cpp
src/engine/textrender.h
src/game/client/components/chat.cpp
src/game/client/components/chat.h
src/game/client/components/hud.cpp
src/game/client/components/hud.h
src/game/client/components/killmessages.cpp
src/game/client/components/killmessages.h
src/game/client/components/menus.h
src/game/client/components/menus_ingame.cpp
src/game/client/components/motd.cpp
src/game/client/components/motd.h
src/game/client/components/nameplates.cpp
src/game/client/components/nameplates.h
src/game/client/ui.cpp
src/game/client/ui.h

Make text container index type-safe, add debug output of text container text on assertion

---

src/base/system.cpp
src/base/system.h
src/engine/client.h
src/engine/client/client.cpp
src/engine/client/client.h

Alternative to #6493. Closes #6482.

Show error message popup on assertion error in client and when client fails to launch

---

src/game/client/components/hud.cpp

Add missing HUD text container deletion

---

src/engine/client/client.cpp

Also print platform, game and OS version in assertion popup

---

.mailmap

add git mailmap, mapping same author email/names to the prefered/most used name

add git mailmap

---

src/engine/client/client.cpp
src/engine/client/client.h
src/engine/console.h
src/engine/server/main.cpp
src/engine/shared/console.cpp
src/engine/shared/console.h
src/engine/shared/storage.cpp
src/game/client/components/menus_start.cpp
src/game/editor/editor.cpp

Quit client when existing config file cannot be loaded, add `restart` command to client, properly uninitialize all client components

---

src/base/system.cpp
src/base/system.h
src/engine/shared/engine.cpp
src/test/os.cpp

Minor refactoring of `os_version_str`

---

src/engine/client/text.cpp
src/game/client/components/menu_background.cpp
src/game/localization.cpp

Fix client crash/hang when launching without data directory

---

src/test/score.cpp

add unit test for updating teamranks
fixes #6113

add unit test for updating teamranks

---

src/engine/map.h
src/engine/shared/datafile.cpp
src/engine/shared/datafile.h
src/engine/shared/map.cpp
src/engine/shared/map.h

Minor refactoring of map and datafile

---

src/game/client/components/menus.cpp

Minor refactoring of `CMenus::RenderLoading`

---

src/game/client/components/tooltips.cpp
src/game/client/components/tooltips.h

Support rendering tooltips with multiple lines of text, support overlapping tooltip activation rects, add alpha fade-in for tooltips 

---

src/engine/engine.h
src/engine/server/main.cpp
src/engine/shared/engine.cpp

Clean up CServerLogger (fixes #6598)

---

src/game/client/components/menus_browser.cpp

Slightly increase font size of friend name

---

src/game/client/components/menus.h
src/game/client/components/menus_browser.cpp

Via https://github.com/ddnet/ddnet/pull/6618/files#r1199072246
Thoughts?

Remove popup for unofficial servers

---

data/languages/russian.txt
data/languages/ukrainian.txt

Fixes for Russian and Ukrainian (by StormA)

---

data/languages/french.txt

@snailx3 @Chairn anyone want to review?

Update french translations (by Sukya)

---

src/game/server/entities/dragger.cpp
src/game/server/entities/dragger.h

Fix swapping with dragger beams (fixes #6597)

---

src/game/editor/editor.cpp
src/game/editor/editor.h
src/game/editor/layer_tiles.cpp
src/game/editor/popups.cpp

Changes requested.
closes #6609

Fix- Replaced usage of m_ProofBorders and m_MenuProofBorders with enum EProofBorder

---

src/engine/client.h
src/engine/client/client.cpp
src/engine/client/client.h
src/engine/client/graphics_threaded.cpp
src/engine/client/graphics_threaded.h
src/engine/graphics.h

Show GPU info (if available) in assert

---

src/engine/client/graphics_threaded.cpp

Minor cleanup of `CGraphics_Threaded::GetVideoModes`

---

src/game/client/components/menus.cpp
src/game/client/components/menus.h
src/game/client/ui.cpp
src/game/client/ui.h

Extract `CMenus::UpdateColors` and `CUI::DebugRender` functions to improve readability of `CMenus::OnRender`

---

src/game/client/components/menus.cpp

Fix escape not working in server browser and demo browser

---

CMakeLists.txt

Try linking to ntdll (fixes #6725)

---

src/engine/client/backend_sdl.cpp
src/engine/client/backend_sdl.h
src/engine/client/graphics_threaded.cpp
src/engine/client/graphics_threaded.h
src/engine/client/input.cpp
src/engine/client/input.h
src/engine/graphics.h
src/engine/input.h
src/game/client/components/menus.h
src/game/client/components/menus_settings.cpp
src/game/client/ui.cpp
src/game/client/ui.h
src/game/client/ui_scrollregion.cpp
src/game/client/ui_scrollregion.h
src/game/editor/editor.cpp
src/game/editor/popups.cpp

Screenshots:
- Controls settings:
- Before: 
- After: 
- Graphics settings (collapsed):
- Before: 
- After: 
- Graphics settings (expanded):
- Before: 
- After: 
- The maximum dropdown menu height is limited to 40% of the screen height. The content will begin to scroll if this is exceeded:
- If there is not enough space below the dropdown button to open the dropdown menu popup, then the popup opens to the top instead:

Improve selection popups and dropdown menus, add dropdown menus to select screen and active controller

---

src/game/client/components/menus_browser.cpp
src/game/client/components/menus_demo.cpp
src/game/client/components/menus_ingame.cpp
src/game/client/components/menus_settings.cpp

Use `DoLabel` instead of `Text`/`TextEx` in menus, other minor refactoring of menus

---

src/game/client/ui.cpp
src/game/client/ui.h

Minor refactoring of `CUI`

---

src/base/system.cpp
src/base/system.h
src/engine/client/client.cpp
src/engine/client/friends.cpp
src/engine/client/graphics_threaded.cpp
src/engine/client/serverbrowser.cpp
src/engine/client/serverbrowser.h
src/engine/client/text.cpp
src/engine/client/updater.cpp
src/engine/server/server.cpp
src/engine/serverbrowser.h
src/engine/shared/console.cpp
src/engine/shared/fifo.cpp
src/engine/shared/storage.cpp
src/game/client/components/binds.cpp
src/game/client/components/chat.cpp
src/game/client/components/console.cpp
src/game/client/components/menus.cpp
src/game/client/components/menus_browser.cpp
src/game/client/components/menus_demo.cpp
src/game/client/components/scoreboard.cpp
src/game/client/components/statboard.cpp
src/game/client/components/voting.cpp
src/game/server/gamecontext.cpp
src/game/server/save.cpp
src/game/server/scoreworker.cpp
src/game/server/teams.cpp
src/test/str.cpp
src/tools/config_common.h

Add templated `str_append` function for arrays with fixed size, add tests, ensure proper buffer size is used with DDNet server filter

---

src/game/client/components/menus.cpp
src/game/client/components/menus.h
src/game/client/components/menus_demo.cpp

Select new demo file after renaming and slicing demo, scroll to selected demo when sorting, refreshing etc.

---

src/game/client/components/binds.cpp

Fix bind crashes (fixes #6758)

---

data/languages/ukrainian.txt

Fix Ukrainian translation

---

src/game/server/ddracechat.cpp

Add new contributors for 17.1

---

data/languages/belarusian.txt

Update Belarusian translation

---

src/engine/client/sound.cpp
src/engine/client/sound.h

CSound: Initialize all members (fixes #6795)

---

src/game/client/components/menus_browser.cpp
src/game/client/ui.cpp
src/game/client/ui.h
src/game/editor/editor.cpp
src/game/editor/editor.h

For long editor texts (group name, layer name, image name, sound name, file names, tooltips) make use of the font scaling and ellipsis functionality implemented in `DoLabel` instead of implementing it separately in the editor.
Screenshots:
- File dialog:
- Before: 
- After: 
- Filename (top menu bar):
- Before:
- After: 
- Image name:
- Before: 
- After: 
- Layer name:
- Before: 
- After: 
- Image selection:
- Before:
- After:

Improve font scaling of long editor texts, improve ellipsis

---

scripts/integration_test.sh

Try to fix #6773 again

---

data/languages/brazilian_portuguese.txt

Can you squash it when merging?

Update Brazilian Portuguese translations

---

src/game/editor/editor.h
src/game/editor/layer_game.cpp
src/game/editor/layer_tiles.cpp

Fix hook-through not being fully removed when filling selection

---

data/skins/license.txt

Fix copyright for kitty_x_ninja (fixes #6830)

---

src/game/server/entities/character.cpp

Send KillMsg for started + unlocked teams

---

src/engine/client/graphics_threaded.cpp

When starting with `dbg_stress 1` the invalid texture was never actually getting loaded, which was causing the client to crash when using the Vulkan backend and starting with `dbg_stress 1`.
Additionally ensure that the invalid texture is 16x16 pixels large and loaded with the texture flags to support usage for tile rendering.
Closes #6504.

Fix invalid texture being invalid and causing crash with Vulkan

---

.github/workflows/clang-sanitizer.yml
.github/workflows/clang-tidy.yml
.github/workflows/rust.yml
.github/workflows/style.yml
bors.toml

Farewell, you've served use well.
CC #6558

Remove last traces of bors

---

.github/workflows/build.yml
.github/workflows/clang-sanitizer.yml
.github/workflows/clang-tidy.yml
.github/workflows/rust.yml
.github/workflows/style.yml

Don't run status checks on GitHub merge queue state twice

---

src/game/client/gameclient.cpp
src/game/client/gameclient.h

Use member instead of static variables in `CGameClient`

---

src/game/editor/editor.cpp

Fix editor modified state not updated for server settings changes

---

src/engine/client/client.cpp

Destroy engine before graphics (fixes #6857)

---

scripts/integration_test.sh

Increase wait times in integration test to reduce flakiness

---

.github/workflows/style.yml

This makes breakages like in #6863 less likely.

Use lock file for dependencies

---

src/game/editor/editor.cpp
src/game/editor/editor.h
src/game/editor/io.cpp
src/game/editor/layer_quads.cpp
src/game/editor/layer_sounds.cpp
src/game/editor/layer_tiles.cpp
src/game/editor/popups.cpp

For cleaner code with less global variables.

Use lambdas for editor index modify and sort functions

---

.mailmap

new email address

---

src/game/editor/editor.cpp

keep selection when moving layers, fixes #6787

---

src/game/client/components/camera.cpp

To avoid some debug/release whatever wonkieness

Init variables used by goto_switch and goto_tele

---

src/engine/client/backend/opengl/backend_opengl.cpp
src/engine/client/backend/opengl/backend_opengl3.cpp
src/engine/client/graphics_threaded.cpp
src/engine/client/graphics_threaded.h
src/engine/graphics.h
src/game/client/gameclient.cpp

Refactor graphics command buffer usage, texture index handling, misc.

---

src/game/client/components/console.cpp
src/game/client/components/console.h

Support selecting text in both consoles at the same time, refactoring

---

src/game/client/components/nameplates.cpp
src/game/client/components/players.cpp

This removes the delay from latency when activating aim line or viewing your own direction arrows.

Use local inputs for direction arrows and aim line toggle

---

src/game/client/components/mapimages.cpp

Fix "Multiplication result converted to larger type" alerts

---

CMakeLists.txt

https://cmake.org/cmake/help/latest/policy/CMP0148.html

Fix CMP0148

---

src/game/editor/editor.cpp

calculate zoom factor correctly for target zoom

---

src/engine/console.h
src/engine/shared/console.cpp
src/engine/shared/console.h
src/game/client/gameclient.cpp
src/game/server/gamecontext.cpp

Fixes #6921
@Robyt3 Can you test this?

Fix client crash in ResetServerGameSettings

---

src/game/editor/editor.cpp
src/game/editor/editor.h
src/game/editor/popups.cpp

This PR allows multiple selection in the envelope editor and (because I am bad at separating features) adds a context menu to envelope points.

Multiple selection in envelope editor

---

src/game/editor/editor.cpp

Add grid to envelope editor

---

CMakeLists.txt
cmake/BuildVulkanShaders.cmake
cmake/FindSSP.cmake

```
src/engine/client/backend/opengl/backend_opengl.cpp:1599: undefined reference to `__stack_chk_fail'
```
Still testing if this fixes the build. Edit: works

Fix build which broke in 3 different ways

---

src/game/editor/editor.cpp

add box selection to envelope editor

---

src/engine/client/text.cpp

Replace skyline-based texture atlas algorithm with a rectangle packing algorithm that tracks empty atlas sections using `std::vector`s. The algorithm is very loosely inspired by https://github.com/TeamHypersomnia/rectpack2D.
Increases texture atlas utilization from ~70% to ~90-94%, i.e. less space in the atlas is unused.
Decreases the computational time to find suitable free regions in the atlas by factor 40x-164x (depending on atlas dimension and utilization). In absolute numbers, the computational time necessary for a glyph being added to the atlas is decreased from 0.0556ms-0.4679ms to 0.0013ms-0.0051ms (depending on atlas dimension and utilization).
The memory usage for the texture atlas algorithm increases from a maximum of ~128 KB to a maximum of ~3 MB.
Benchmark results (every X …

Improve text rendering texture atlas utilization and performance

---

src/game/client/components/chat.cpp

don't send empty chat messages

---

src/game/client/components/console.cpp
src/game/client/components/console.h

fix too long console commands not rendering help

---

CMakeLists.txt
src/game/editor/component.cpp
src/game/editor/component.h
src/game/editor/editor.cpp
src/game/editor/editor.h
src/game/editor/layer_sounds.cpp
src/game/editor/layer_tiles.cpp
src/game/editor/map_view.cpp
src/game/editor/map_view.h
src/game/editor/popups.cpp
src/game/editor/smooth_value.cpp
src/game/editor/smooth_value.h

Refactor `CSmoothZoom` and introduce `CMapView`. I kept the changes to the editor code relatively small as the PR is quite big already. So in a future PR much of `DoMapEditor` and other things (like zooming with the mouse wheel) should be moved to this class.

Add CEditorComponent to moduralize editor

---

src/game/client/gameclient.cpp

Implements #7007, to summarize:
If all players, that are currently in view, are in the same team, when switching to multi-view it will now switch to those players. Previously, this only worked for players in team 0.
If players of differing teams are in view, it will still use the old "only team 0" behavior, which simply ignores players in teams.
- While there are some multi-view options, they don't really affect any of this

Allow automatic multi-view for players in a team

---

src/game/editor/editor.cpp

Scaling very small values is still slightly buggy especially if the point at zero is involved:

implement scaling for envelope editor

---

.github/workflows/build.yml
.github/workflows/clang-sanitizer.yml
.github/workflows/clang-tidy.yml
.github/workflows/codeql-analysis.yml
.github/workflows/rust.yml

CI: Cache Rust dependencies

---

src/game/server/scoreworker.h

fix CScorePlayerResult for visual c++ compiler

---

CMakeLists.txt
src/game/editor/component.cpp
src/game/editor/component.h
src/game/editor/editor.cpp
src/game/editor/editor.h
src/game/editor/io.cpp
src/game/editor/map_grid.cpp
src/game/editor/map_grid.h
src/game/editor/map_view.cpp
src/game/editor/map_view.h
src/game/editor/popups.cpp
src/game/editor/proof_mode.cpp
src/game/editor/proof_mode.h

Also extract more code into `CMapView` and extend the `CEditorComponent` interface.

Add `CProofMode` and `CMapGrid` component

---

src/game/editor/editor.cpp

reset operation status after creating envelope context menu
