ddnet/ddnet

src/game/server/ddracecommands.cpp
=> Fix wrong output for unmute

src/base/system.cpp
by making fs_rename work on Windows with Unicode chars
=> Try to fix unicode race demos (fixes #4192)

src/engine/client/text.cpp, src/engine/textrender.h, src/game/client/components/console.cpp, src/game/client/components/menus_browser.cpp, src/game/client/lineinput.cpp, src/game/client/lineinput.h, src/game/client/ui.cpp, src/game/client/ui.h, src/game/client/ui_ex.cpp, src/game/client/ui_ex.h
This changes the hotkey for "exclude" to CTRL + SHIFT + X, because else it collides with Cutting strings out of a selection
This is defs not perfect, it basically ignores keyboard keys that could also alter selection (e.g. shift + right) but i didnt want to break the IME stuff, bcs i don't understand it
=> Add basic selection support for ui ex edit boxes

src/base/system.cpp
Fixes `fs_removedir` and `fs_remove` to work with unicode names on Windows.
=> Fix fs_removedir and fs_remove with unicode on windows

src/antibot/antibot_null.cpp
0750ae0fbd79f66aedfbb7ff1092007ae69a6d9c was missing the function
prototypes that used `ANTIBOTAPI`.
=> Properly export antibot DLL symbols on Windows, this time for real

data/languages/french.txt, src/engine/shared/config_variables.h, src/game/client/components/killmessages.cpp, src/game/client/components/menus_settings.cpp, src/game/variables.h
Motivation: #4186
List of changes:
- Add options clKillMessageHighlightSelf, clKillMessageNormalColor, clKillMessageHighlightColor
- Rework HUD panel in settings
=> Add option to highlight self in kill messages

src/game/server/teams.cpp, src/game/server/teams.h
Restore behavior of 
https://github.com/ddnet/ddnet/commit/d6c344853a4904c27bea27187a50b086551b9050#diff-0bf5339794dfb6d6185b1d1898ca662f22ec5836094d8c40fa4ad7387a6f2df8L988-R1037
fixes #4240
=> Add exception id to TeamKill

src/engine/shared/compression.cpp
=> CVariableInt: Limit to 31 bits to fit into int (fixes #4280)

src/game/server/gamecontext.cpp
=> Fix heap-use-after-free in OnMessage (fixes #4279)

src/engine/client/text.cpp, src/game/client/ui_ex.cpp, src/game/client/ui_ex.h
Changing ui element by hot keys was not visible to DoEditBox, and thus didn't act like selection params were resetted
=> Reset selection, if gui element was changed outside of DoEditBox

src/base/system.cpp
Use the wide char variants of `getenv`, `_mkdir`, `_getcwd` and `chdir`.
Tested the change on upstream with japanese characters and german umlauts in username.
This should fix the issues with cyrillic username, I don't know if that "out of memory" from sqlite was also caused by an invalid appdata path (#4293).
`fs_chdir` is unused anyway but this also fixes it for completeness.
=> Fix fs_makedir, fs_storage_path, fs_getcwd and fs_chdir with unicode on windows

src/game/client/gameclient.cpp
described in #4317 but unrelated to the issue i think
=> Use delete[] for m_pSwitchers

src/engine/client/client.cpp
Most performance loss currently comes from the simple fact that lookupuuid is slow.
This addresses the problem by making sure its only called for net messages, that are extended anyway
@trml or @heinrich5991 can you check if that makes sense without breaking something?
=> Don't call uuid lookup, if the expected type isn't an uuid extended type anyway

src/base/system.h, src/engine/client/client.cpp
Doesn't overflow so quickly, if it overflows has deterministic behavior
at least.
=> Use uint64_t for network stats (fixes #4309)

src/engine/shared/linereader.cpp, src/engine/shared/linereader.h
If someone wants to look more closely, maybe there is a better fix
=> Don't access out of bounds in linereader (fixes #4308)

src/engine/client/client.cpp, src/engine/shared/snapshot.cpp, src/engine/shared/snapshot.h
Look up the internal type of the searched-for UUID type once, and then
just do integer comparisons to find the item.
CC #4300
=> Improve performance of `SnapFindItem` for extended item types

src/game/client/gameclient.cpp
Changed the sort calls to use a single comparison instead, which ended up looking at bit cleaner. (I believe the previous version didn't satisfy strict weak ordering)
I'm not able to reproduce #4317, but this hopefully fixes it. @Jupeyy can you test this?
=> Use valid sort comparator

src/game/client/components/skins.cpp
=> Escape skin name when downloading (fixes #4333)

src/game/client/components/menus_settings.cpp
=> Fix spacing in HUD settings for 5:4 resolution

src/game/client/components/items.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/server/gamecontroller.cpp
Makes the server send the switch state of other players while spectating others, otherwise the switch state of your own player (including when spectating in freeview).
Also changed the client a little to both handle situations where the server only sends one SWITCHSTATE netobject (then it just uses that team) or all (then it chooses the team that maintains the above behavior). I'm not sure if the latter would really be useful (but since the netobject contains a team it would be possible to do so).
=> Make laser doors show correctly when spectating other players

src/engine/client/steam.cpp
Untested, but I'm assuming this closes #4345.
The name "ｃａｇｅｎｔ󠀡" is 7 unicode codepoints (including an invisible one at the end) which convert to 22 bytes with UTF-8.
This does not fit the current buffer size of 16, resulting in a unicode codepoint getting cut off, which probably causes arbitrary behavior with text input.
Google search shows the maximum length of a Steam username should be 32 bytes. I set the new buffer size to 48 for null termination and additional leeway.
This also makes sure that the username from Steam API is copied while checking for complete codepoints, in case the maximum length of a Steam username is ever increased in the future.
=> Fix steam names being cut off inside utf8 codepoints

src/base/system.cpp
I don't know what the reason for https://github.com/teeworlds/teeworlds/commit/2a570196ef7dd66f475a3379b9cc5b6abf915e09 was, but this reverts it so files are opened case insensitively on Windows again. I assume it was done for consistency so file operations on all operating systems would be case sensitive, but then again I don't understand why it was only being applied when opening files for reading.
While NTFS is actually case sensitive, the normal Windows file API puts a case insensitive abstraction on top.
Previously, if you had multiple files with the same name but different capitalization it would open the file with the correct capitalization, in the unlikely case that you circumwented the file API to create those files. Now it opens the first one it finds non-deterministically, but …
=> Make opening files for reading on windows case insensitive (again)

src/engine/shared/demo.cpp, src/engine/shared/demo.h
Happens with demos cut from KoG
=> Try crc for maps if sha256 isn't available (fixes #4327)

src/base/system.cpp, src/base/system.h, src/engine/client/client.cpp, src/engine/client/ghost.cpp, src/engine/client/ghost.h, src/engine/demo.h, src/engine/shared/datafile.cpp, src/engine/shared/demo.cpp, src/engine/shared/demo.h, src/engine/shared/snapshot.cpp, src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp
Add `uint_to_bytes_be` and `bytes_be_to_uint` functions from upstream and use them where applicable to reduce duplicate code.
=> Add functions for packing/unpacking int/unsigned using char arrays

src/game/client/components/console.h
Can't even list all bot bans currently
=> Increase console backlog size from 64 KB to 1 MB

src/game/client/components/items.cpp, src/game/server/entities/door.cpp, src/game/server/entities/dragger.cpp, src/game/server/entities/gun.cpp, src/game/server/entities/light.cpp, src/game/server/entities/pickup.cpp
This drops sending entityex to old client versions, and for stationary pickups not in switch layer (since they don't benefit from entity ex for prediction).
It also slightly changes how m_StartTick is snapped for CLight and CGun when EntityEx is present (always sets it to 0, which could reduce network traffic slightly). However, this might cause misprediction (or invisible lights/guns) for clients who have already changed their version to 15.6, so can omit this part if wanted.
=> Small optimization of EntityEx snapping

src/engine/external/json-parser/json.h, src/engine/shared/serverinfo.cpp
Debian, Ubuntu, Fedora are using libjsonparser without our own changes,
thus we were doing garbage.
=> Fix serverinfo json parser to work with system libjsonparser (fixes #4202)

src/engine/server/databases/connection.h, src/engine/server/databases/mysql.cpp, src/engine/server/databases/sqlite.cpp
Comes in handy for my downstream
Follow up to https://github.com/ddnet/ddnet/pull/4334
Tested with sqlite3
=> Add sql BindInt64

CMakeLists.txt, src/base/system.cpp
Add `UNICODE` and `_UNICODE` defines on Windows and use either the A or the W variant of the Windows API methods explicitly where it was left unspecified.
I supposed this fixes `shell_execute` for unicode paths (e.g. username with unicode) and fixes debug logger output with unicode.
I renamed `logger_debugger` to `logger_win_debugger` to make it clear that it's only available on windows. 
I'm using the A-variant for `WSAStringToAddress` and `FormatMessage` because they don't really need to handle unicode, but there is probably a region specific winsock error message containing unicode.
Does not fix unicode commandline arguments.
=> Add UNICODE defines on windows, misc. unicode fixes

src/base/system.cpp
Fix opening user data folders with unicode username.
`str_format(aBuf, sizeof(aBuf), "start %s", link);` was without effect.
=> Fix open_link with unicode on windows

src/game/editor/editor.cpp
=> No wasd moving when dialog is open (fixes #4370)

src/base/system.cpp
I'll also fix all usages of WideCharToMultiByte and MultiByteToWideChar next, because the wrong buffer size is specified.
=> Fix unicode winsock error messages

src/base/system.cpp, src/base/system.h
- Fix buffers sizes when using `MultiByteToWideChar` and `WideCharToMultiByte`.
- input length is now always `-1`, as this will assume null-termination and also ensure it for the output
- output length is the number of array elements (and not the size in bytes as previously specified in some cases)
- Use `str_format` in `fs_storage_path` instead of platform specific functions for better maintainability.
- Implement `fs_is_dir` smarter by using `GetFileAttributesW` on Windows.
- Remove unused `fs_getmtime` that does not work with unicode on Windows in favor of the existing more generalized `fs_file_time`.
=> Fix incorrect/inconsistent buffer sizes, improve fs_is_dir, cleanup

src/game/editor/editor.cpp, src/game/editor/popups.cpp
As reported by louis:
> pressing enter while creating a new folder in the editor (while using
> "save as") does not create the folder but instead enters the selected
> folder in the background
=> Fix enter behavior when creating new folder in editor

src/game/client/ui.cpp, src/game/client/ui.h, src/game/editor/editor.cpp
As reported by louis:
> while saving a mapname while having the "Server Settings" tab open,
> pressing "m" while typing the mapname will unfocus the cursor from the
> mapname field onto the server settings field
=> Fix save typing when server settings are open in editor

src/game/server/save.cpp
It's possible that a map was saved with a different amount of switchers
than it has at the moment. Happened on Jao Shooter. I'll check with
mapper if they changed the number of switchers.
=> Don't access switchers out of bounds (fixes #4386)

src/base/system.cpp, src/base/system.h, src/game/client/components/chat.cpp, src/game/client/components/console.cpp, src/game/client/lineinput.cpp, src/game/client/lineinput.h, src/test/str.cpp
Various refactorings and cherry-picks to `CLineInput` from the upstream PR. No issues fixed except for `CLineInput::Add` (now named `Append`) not updating `m_NumChars` before.
=> Various text input refactorings

src/base/system.cpp, src/base/system.h
This removes the check for the null-terminator from the while loop, as this is also checked in `str_utf8_forward`, which returns an unchanged size in this case. The comparison `new_size != *size` was previously redundant for that reason.
Update comments and add some empty lines for consistency.
@heinrich5991
=> Update str_utf8_stats documentation, minor refactoring

src/game/client/components/items.cpp, src/game/client/projectile_data.cpp
and don't access out of scope on owner < 0
=> Sanitize owner data in client (fixes #4388)

src/engine/client/serverbrowser.cpp, src/engine/shared/config_variables.h, src/game/client/components/menus_browser.cpp
We had lots of cases of people having ping filter activated. Ping is now
too unreliable to actually filter by it. It can show an old super high
value and then you never see the location again.
=> Remove ping filter (fixes #4365)

src/engine/client/http.cpp
Thanks to @godwhoa for report and testing the workaround!
I can't test this since I can't reproduce, but @godwhoa wrote:
> With connection reuse: 5/10 runs resulted in a crash.
> Without connection reuse: 0/10 runs resulted in a crash.
=> Disable connection reuse in curl (fixes #4342)

src/base/system.cpp
`count` and `max_count` don't change after the check in the while loop.
=> Remove redundant *count >= max_count check

src/test/serverbrowser.cpp
```
==235823==ERROR: LeakSanitizer: detected memory leaks
Indirect leak of 65632 byte(s) in 1 object(s) allocated from:
#0 0x563636cc2fc9 in malloc (/media/ddnet/testrunner+0x37afc9)
#1 0x563636e0fd89 in CHeap::NewChunk() /media/ddnet/src/engine/shared/memheap.cpp:14:17
#2 0x563636e10aee in CHeap::Reset() /media/ddnet/src/engine/shared/memheap.cpp:63:2
#3 0x563636d954a5 in CConsole::CExecutionQueue::Reset() /media/ddnet/src/engine/shared/console.h:188:12
#4 0x563636d4a272 in CConsole::CConsole(int) /media/ddnet/src/engine/shared/console.cpp:937:19
#5 0x563636d88a98 in CreateConsole(int) /media/ddnet/src/engine/shared/console.cpp:1230:59
#6 0x563636fbe915 in ServerBrowser_PingCache_Test::TestBody() /media/ddnet/src/test/serverbrowser.cpp:13:23
#7 0x7f0a2f87fe26 in void …
```
=> test/serverbrowser: delete pConsole

src/game/client/ui_ex.cpp, src/game/client/ui_ex.h
The `CUIEx` constructor with arguments is unused and only the default constructor was used but hidden away in the header file therefore missing the initialization.
Closes #4408.
=> Fix initialization of CUIEx::m_MouseSlow

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings_assets.cpp, src/game/client/gameclient.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/client/ui_ex.cpp, src/game/client/ui_ex.h, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
Move duplicate `DoClearableEditBox` from menus and editor to `CUIEx`.
Various minor refactoring.
=> Various UI/input refactoring

src/game/server/ddracechat.cpp
As suggested by 冷落:
> I have a advice./swap need wait 30s,and often someone will say /swap
> within 30 seconds,but kept saying it would be muted
=> Swap: Don't spam-protect retrying with local messages only

src/engine/server/databases/connection_pool.cpp
Quick fix to loose less ranks. Further fixes incoming, but I've split this out, because it is easy to review and already helpful on its own. For #4424
=> Don't shutdown server when there are outstanding sql queries to be executed

src/engine/client/client.cpp, src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/config_variables.h, src/engine/shared/console.cpp, src/game/server/entity.cpp, src/game/server/entity.h
I added an extended kill message info (with killer assistant and mod-specific weapon id) and found a few bugs/mistakes in the current UUID implementation.
1. CUuidManager::RegisterName() mostly ignores the `ID` argument (totally ignored before https://github.com/ddnet/ddnet/pull/3053). Namely: it [add](https://github.com/ddnet/ddnet/blob/a39af83a421f8e1b26725dbbe04dfe131f8fc848/src/engine/shared/uuid_manager.cpp#L110) the names into m_aNames. But then in order to pack them, the manager uses [GetUuid](https://github.com/ddnet/ddnet/blob/a39af83a421f8e1b26725dbbe04dfe131f8fc848/src/engine/shared/uuid_manager.cpp#L162) which [picks](https://github.com/ddnet/ddnet/blob/a39af83a421f8e1b26725dbbe04dfe131f8fc848/src/engine/shared/uuid_manager.cpp#L120) the uuid at [ID - …
=> Fix UUID for demo playback, add a conf var to toggle console colors

src/game/client/ui_ex.cpp
Adopt the vanilla color scheme for scrollbars, making the rails white instead of black for increased visibility.
Fix the calculation of the handle size, so it is consistent with vanilla, making the handles slightly smaller compared to before.
Minor refactoring / style changes.
=> Adopt vanilla scrollbar colors and sizes, minor code style changes

src/test/datafile.cpp, src/test/serverbrowser.cpp
Why is the PingCache test failing now???
=> Try to use unique_ptr in tests so we can't forget to delete

src/game/client/ui_ex.cpp
The maximum scrollbar handle size was too small for small scrollbars.
AFAIK, the previous size did not directly affect ddnet client, as there are no scrollbars that small, but they might be used eventually.
See screenshots in https://github.com/teeworlds/teeworlds/pull/2995.
=> Increase scrollbar handle size for small scrollbars

src/engine/server/server.cpp, src/engine/server/server.h, src/game/server/gamecontext.cpp
Also still record client version on map changes into teehistorian.
Fixes #4445.
Thanks to @Kaffeine for noticing.
=> Don't clear client version on map change

src/engine/server.h, src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/console.h, src/game/server/gamecontext.cpp, src/game/server/gamecontroller.cpp
The main motivation is making it easier to take (and push) patches to/from `teeworlds`
I'm not that familiar with the code. Please let me know if this commit make sense or not:
https://github.com/teeworlds/teeworlds/pull/2594/commits/56900d7644c1f49aa6d085f57dd025a8f8416e5f
IIUC two other commits from https://github.com/teeworlds/teeworlds/pull/2594 are not relevant for DDNet (because we're reducing the CPU load differently).
=> Pull some more refactoring from the upstream

src/game/client/components/items.cpp, src/game/client/prediction/gameworld.cpp, src/game/server/entities/laser.cpp, src/game/server/entities/laser.h, src/game/server/entities/projectile.cpp, src/game/server/entities/projectile.h, src/game/server/entity.h, src/game/server/gameworld.cpp, src/game/server/gameworld.h, src/game/server/teams.cpp
Thanks to Soapy Sandwich for responsibly disclosing this issue.
https://user-images.githubusercontent.com/2335377/145693247-c5c1ab2e-6353-4a4a-afab-c73f2d7eebc1.mp4
/swap is currently disabled until this is merged.
=> Swap projectile owners when using /swap

CMakeLists.txt, src/base/system.cpp, src/base/system.h, src/engine/client/backend/opengl/opengl_sl.cpp, src/engine/client/client.cpp, src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser_http.cpp, src/engine/client/updater.cpp, src/engine/server/server.cpp, src/engine/shared/console.cpp, src/engine/shared/masterserver.cpp, src/engine/shared/storage.cpp, src/game/client/components/countryflags.cpp, src/game/client/components/menus_settings.cpp, src/game/editor/auto_map.cpp, src/game/localization.cpp, src/game/server/gamecontext.cpp, src/game/server/score.cpp, src/test/io.cpp, src/tools/config_store.cpp
=> Skip the UTF-8 BOM on all read text files

src/engine/client/client.cpp
1 second is too much, 1 frame of 60 fps is more than enough, dropping a whole frame when using 60fps as limit is already quite alot
=> Lower worst/best case frame time calculations

src/engine/shared/config_variables.h
=> Disable gfx_asyncrender_old on macOS (fixes #4435)

src/engine/shared/config_variables.h, src/game/client/components/players.cpp, src/game/variables.h
Currently to show your own key presses when recording you need
cl_video_showdirection 1 and cl_show_direction 2 which is kind of
unintuitive.
Also changed the name to be consistent with cl_show_direction
Thanks to hussainx3 for report.
=> Support cl_video_show_direction 2

src/game/client/prediction/entities/character.cpp, src/game/collision.cpp, src/game/collision.h, src/game/server/entities/character.cpp, src/game/server/entities/laser.cpp, src/game/server/entities/projectile.cpp
=> Make /rescue handle switch freeze too

src/base/system.cpp, src/base/system.h, src/engine/shared/uuid_manager.cpp
=> Revert "Let's not crash the client and server on dbg_assert"

src/base/system.cpp, src/base/system.h, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings_assets.cpp
=> Add open_file, works on macOS, safer, Add buttons to open settings file and config directory

src/engine/client/client.cpp, src/engine/client/client.h, src/engine/shared/config_variables.h, src/game/client/components/menus_settings.cpp
Normal timeout codes don't work anymore, new ones don't support adding commands at the end with ;
There was a discussion on Discord, multiple players asked me for this feature already.
It's only run on servers that support timeout codes.
=> Add cl_run_on_join to set command to execute when joining a server

src/base/system.cpp, src/base/system.h, src/engine/client/input.cpp, src/engine/client/steam.cpp, src/engine/client/text.cpp, src/engine/server/server.cpp, src/engine/shared/network_conn.cpp, src/game/client/components/chat.cpp, src/game/client/components/scoreboard.cpp, src/test/str.cpp
=> Don't create cut off UTF-8 sequences on string manipulation

src/game/editor/io.cpp
=> Use temporary file when saving editor file (fixes #4476)

src/engine/client/client.cpp
Tested by copying DDNet executable from package into Steam directory and running it via steam://run/412220//ger2.ddnet.tw:8001/ directly and when client is running already. (UI had another server selected)
=> Fix joining pw-protected server via Steam (fixes #4502)

src/engine/client/client.cpp, src/engine/client/updater.cpp, src/engine/shared/config.cpp, src/engine/shared/storage.cpp, src/engine/storage.h, src/game/client/components/skins.cpp, src/game/server/gamecontext.cpp, src/test/test.cpp
Not sure I prefer it, but now it's done. Any opinions?
=> Add IStorage::FormatTmpPath static method

src/engine/server/server.cpp, src/engine/server/server.h
Closes #3838. Reload the map when changing `sv_sixup`, so the server is never in a state where `sv_sixup` is enabled but no sixup map was loaded.
Log the "disabling 0.7 compatibility" message in the remote console so it's more obvious.
=> Reload map when changing sv_sixup

scripts/android/files/build.sh
```
In ./scripts/android/files/build.sh line 3:
[ x"$1" == x ] && {
^---^ SC2268 (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
Did you mean:
[ "$1" == "" ] && {
```
=> Fix local shellcheck warnings in android/files/build.sh

src/game/server/entities/character.h, src/game/server/teams.cpp
As reported by cheeser0613:
2player, 1die in freeze
swap 2 player by /swap
the other 1 also go die in freeze
/practice
one of them cant use /r
=> Swap: Also switch rescue tees for /r

src/engine/client/client.cpp, src/engine/shared/config_variables.h
As reported by Ryu
Verified with cl_port 12345; cl_dummy_port 12346:
=> Add cl(|_dummy|_contact)_port for ISPs that throttle specific ports

src/game/editor/io.cpp
Doesn't work on Windows, not so easy to overwrite a file already open in
editor. Not sure how our old approach works, but apparently it did
better than the new one. As reported by texnonik on Discord
This reverts commit e2084e1e9dff6f6e816ac63f02c49fb8ae9178b2.
=> Revert "Use temporary file when saving editor file (fixes #4476)"

src/engine/shared/config_variables.h, src/game/server/ddracechat.cpp, src/game/server/entities/character.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/gamemodes/DDRace.cpp, src/game/server/teams.cpp
to prevent too small teams counting as team finishes. You can still
finish with a team smaller than sv_min_team_size, but only get regular
ranks, not team ranks.
This will require going through all our maps and setting
sv_min_team_size in map config for maps intended for more than 2
players. We will also need to remove all teamranks with smaller teams
from official database.
=> Implement sv_min_team_size (fixes #3720)

CMakeLists.txt, src/engine/shared/compression.cpp, src/engine/shared/compression.h, src/test/compression.cpp
The last iteration in `CVariableInt::Unpack` is changed from
```cpp
*pInOut |= (*pSrc & (0x1F)) << (6 + 7 + 7 + 7);
```
to
```cpp
*pInOut |= (*pSrc & 0x0F) << (6 + 7 + 7 + 7);
```
which means the last iteration will unpack at most 4 more bits instead of 5, hence invalid left shifts by 27 places that could otherwise occur on this line are prevented (closes #3686). Now at most 31 bits are unpacked, in addition to the sign bit.
Tests are added to ensure correct functionality of all `CVariableInt` functions.
=> Fix invalid left shift in CVariableInt::Unpack, add tests for CVariableInt

src/engine/shared/packer.cpp, src/engine/shared/snapshot.cpp, src/test/compression.cpp
- Use `CVariableInt::MAX_BYTES_PACKED` in two more places.
- Fix order of arguments in a test case.
=> Fix argument order in test, use constant

src/base/tl/threading.h, src/engine/server/databases/connection_pool.cpp, src/engine/server/databases/mysql.cpp
Remaining changes for #4424. Improving sql write times during shutdown and slow mysql responses/timeouts. I still want to test this change, especially for the last commit. Might have time for testing this evening. Thoughts and feedback on this patchset welcome.
=> Pr sql fail fast

src/engine/client/backend_sdl.cpp
I can't really reproduce it:
Assertion failure at SDL_GetWindowFlags_REAL (/home/deen/isos/ddnet/debian6/root/mac64/SDL2-2.0.16/src/video/SDL_video.c:1905), triggered 1 time:
'window && window->magic == &_this->window_magic'
=> Try to fix SDL2 assertion failure (fixes #4434)

other/bundle/client/Info.plist.in
See https://developer.apple.com/documentation/bundleresources/information_property_list/nsprefersdisplaysafeareacompatibilitymode?language=objc
=> Explicitly disable notch area for fullscreen on macOS (fixes #4533)

src/game/client/components/menus_browser.cpp
as reported by Izanagi
Old:
New:
=> Add margin for ping in server browser

CMakeLists.txt, src/base/system.cpp, src/test/bytes_be.cpp
- Fix undefined/implementation-specific behavior due to right shift of negative number in `int_to_bytes_be` and `bytes_be_to_int`, by instead copying the bytes without using any bit arithmetic.
- Add tests for all four byte packing functions.
=> Fix undefined behavior in byte packing functions, add tests

CMakeLists.txt, cmake/CheckAtomic.cmake
Sometimes linking against libatomic is required for atomic ops, if
the platform doesn't support lock-free atomics.
=> Add CheckAtomic.cmake

src/engine/shared/config_variables.h
This reverts commit ee3509738528ddd78ea4dae27126a633b0e5486c.
=> Revert "Support 32bit color depth, default to it (fixes #4549)"

src/game/editor/editor.cpp
=> Editor: Don't react to server settings shortcuts when dialog is open

src/engine/server/server.cpp, src/engine/shared/snapshot.cpp
=> Don't crash when no ids are left (fixes #4565)

src/engine/client/client.cpp
otherwise they get stuck. Thanks to Skeith reproduction steps:
> Basically, to consistently reproduce the bug, you put your tee in
> freeze, then you connect your dummy right as the stars appear when
> frozen. It also happens with the stars that pop out when you shoot your
> pistol @deen
=> Always clear stars, also when entering dummy (fixes #4554)

src/base/tl/threading.h, src/engine/server/databases/connection_pool.cpp, src/engine/server/databases/connection_pool.h
Makes ddos situations more bearable during tournaments. Redo of #4429, but this time the tested version. I somehow mixed my two git environments (Laptop and PC) last time and some changes were missing from the PR last time (the initialization of the shutdown variable and m_count variable).
Changed the logic a bit from last time to only go into FailMode if the query fails on all database servers.
=> Fail database queries faster

src/engine/shared/snapshot.cpp
See https://github.com/teeworlds/teeworlds/issues/2643.
=> Fix OOB read in snapshot code reported by mmmds

src/engine/shared/config_variables.h
Doesn't help fully against the crashes, just makes them a bit less
likely. Causes VSync to have even more delay. Should find an alternative
(real) fix.
This reverts commit 7d8a142768b28ad36a7de12a19b6bf954e824d9a.
=> Revert "Disable gfx_asyncrender_old on macOS (fixes #4435)"

src/engine/client/graphics_threaded.cpp
Thanks to Jupeyy for the suggestion
Normally it crashes after a few seconds, tried moving window around, resizing, moving between screens like crazy and no crashes after 1-2 min.
=> Fix crash in macOS when moving screen (fixes #4435)

src/engine/client/client.cpp, src/engine/shared/snapshot.cpp, src/engine/shared/snapshot.h
The `Type` unpacked from the snapshot delta is stored in `m_SnapshotCurrent`, which is validated to be in range `0 - 0xffff`, but the arrays `m_aSnapshotDataUpdates` and `m_aSnapshotDataRate` being index with this are sized 1 too small with length `0xffff`. Hence, snapshot deltas with `Type == 0xffff` cause OOB accesses.
This is fixed by adding validation for `Type` to be in range `0 - CSnapshot::MAX_TYPE` (`0x7fff`) and changing the lengths of the arrays to `CSnapshot::MAX_TYPE + 1`. Validation for `ID` is also added to keep it in range `0 - 0xffff`.
This validation also prevents undefined behavior in subsequent `(Type << 16) | ID`.
Refactoring:
- Declare `CSnapshotDelta::UndiffItem` as `static` and add output parameter `int *pDataRate` as replacement for usage of member variables. …
=> Fix OOB access in CSnapshotDelta::UnpackDelta, cleanup

src/game/client/components/console.cpp, src/game/client/components/console.h
Hopefully fixes #4319
I can only imagine it happening bcs of resizing
=> Fix console line y offsets when resizing

src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/client/graphics_threaded_null.h, src/engine/client/input.cpp, src/engine/graphics.h, src/game/client/components/menus_settings.cpp
I noticed that the resize backend used the wrong macros `CONF_PLATFORM_WINDOWS` instead `CONF_FAMILY_WINDOWS`(windows seems to be the only one in detect.h that splits platform between 32bit and 64bit, maybe we should change that)
maybe this fixes #4351, because actually the workaround for windows was exactly inside the wrong macro to fix resizing in fullscreen.
I also split the resize functions, so its less confusing Resize (actively resize in the resolution list) vs GotResized (reported by SDL) and made some things a bit clearer
=> Fix windows macro and split the resize events

src/engine/shared/config_variables.h
=> Reduce default ambient volume to 30 (fixes #4567)

src/game/server/save.cpp
=> Fix rescue tee when swapping (fixes #4578)

src/game/editor/explanations.cpp
Thank @fokkonaut
Revert two lines to original.
Commit to be reverted:
https://github.com/ddnet/ddnet/commit/2017464282aa55fc21c90229a5acc3376ce5ecac#diff-6ecdf8a78005b8c2541e54e3532ebec8f3f4ef2ec69ba8a6a281ce4421562570
=> Revert LFREEZE-LUNFREEZE explanation on editor for Switch layer

src/engine/client/client.cpp, src/game/client/components/items.cpp, src/game/client/components/items.h, src/game/client/gameclient.cpp, src/game/server/entities/character.cpp
Aligns the code with vanilla, and cleans up things a bit
(same as [https://github.com/teeworlds/teeworlds/commit/329e6261f360bc9534a4212ad1214c37ddf997f4](url))
These were used to show projectiles a tick (or fraction of a tick) earlier than they otherwise would (and they were also sent without extrainfo since they didn't matter for prediction), so removing them would perhaps not make a noticeable difference. (and perhaps also less of a difference now since weapon input isn't applied before the start of a tick anymore).
=> Remove extra projectiles

src/engine/client/video.cpp, src/engine/client/video.h
```
src/engine/client/video.cpp:102:32: error: assigning to 'AVOutputFormat *' from 'const struct AVOutputFormat *' discards qualifiers
m_pFormat = m_pFormatContext->oformat;
~~~~~~~~~~~~~~~~~~^~~~~~~
src/engine/client/video.cpp:571:13: error: assigning to 'AVCodec *' from 'const AVCodec *' discards qualifiers
*ppCodec = avcodec_find_encoder(CodecId);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Fix compiler warning with new ffmpeg version (currently built from git)

src/engine/client/client.cpp, src/engine/client/input.cpp, src/engine/client/input.h, src/engine/input.h, src/game/client/components/menus_demo.cpp
This adopts the 0.7 way of handling double clicks, by checking `Event.button.clicks` of the `SDL_Event`. The double click is stored as a flag which is cleared when the `MouseDoubleClick()` function is called (d215c732062cbc73b9922ce270be70c36d00bb9d and 7977b46d36aee6e0eb4676ed1f9a14859d9f5408).
This reverts 72a6e20, as this hack is no longer required (closes #1745). Double clicking a friend in the friend list still works (#444) with both `gfx_asyncrender_old 0` and `1`.
Refactorings and minor fixes synchronizing with upstream:
- Only copy SDL keystate of _keyboard_ keys and mem_zero the rest to ensure out of bounds SDL keys don't trigger mouse keys.
- Rename variables and use SDL constants.
- Reduce unnecessary indentation.
=> Adopt upstream input (especially double click) handling, refactoring

src/base/system.cpp
=> Close find handle in fs_file_time on windows

src/game/client/components/menus_demo.cpp
Double clicking a folder in the demo browser may activate the current or a different item twice.
I assume it's a regression from #4607. Vanilla also had https://github.com/teeworlds/teeworlds/pull/1913/commits/37f288e211d7f7cab14d71655edc0ce3835c7c30 where I took the idea for this fix: the check is change so instead of `HotItem` (or `ActiveItem`) the activation of the underlying button is checked (here by `NewSelected >= 0`). So now the double click will only register when the mouse is _released_ for the second time. Previously both the second press and the release event where causing the double click to happen.
=> Fix double clicking on folders in demo browser

src/game/client/components/background.cpp, src/game/client/components/menu_background.cpp, src/game/client/gameclient.cpp, src/game/client/render.cpp, src/game/client/render.h, src/game/layers.cpp, src/game/layers.h
- Move `CRenderTools::RenderTilemapGenerateSkip` to `CLayers::InitTilemapSkip`, as it can be a private function in `CLayers`.
- Add missing `CLayers::NumLayers` accessor.
- Improve code style.
=> Refactoring: move RenderTilemapGenerateSkip to CLayers, Add CLayers::NumLayers

src/engine/textrender.h, src/game/client/components/hud.cpp, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings_assets.cpp, src/game/client/components/menus_start.cpp, src/game/client/components/voting.cpp, src/game/client/ui.cpp, src/game/client/ui_ex.cpp, src/game/editor/editor.cpp, src/game/editor/layer_tiles.cpp, src/game/editor/popups.cpp
Replaces the magic numbers -1/0/1 for left/center/right
Based on the work done in upstream:
@cinaera added alignment enums
https://github.com/teeworlds/teeworlds/commit/04ee8b20a1b3aa2239c791ac14c58ed95fe4a442
@TsFreddie renamed them
https://github.com/teeworlds/teeworlds/commit/67651e81227d1e5b2c4d53f169f49194a0d83aeb
=> Use ETextAlignment enum for UI

other/bundle/client/Info.plist.in, src/base/system.cpp, src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h
@Jupeyy didn't work, I thought maybe it's because it uses the E cores, not P cores.
=> Try to improve macos perf

src/test/score.cpp
=> Fix timestamp in record_maps in test (fixes #4631)

src/game/client/components/camera.cpp
Thanks to chillerdragon for noticing
=> Don't clamp "zoom" command, we already clamp in ChangeZoom

src/game/server/gamecontext.cpp, src/game/server/gamemodes/DDRace.cpp
=> Fix SendStartWarning() to only warn every 3 seconds

src/game/client/components/menus_settings.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/editor/editor.cpp
Add optional `Spacing` parameter to `CUIRect::HSplitMid` and `CUIRect::VSplitMid`.
Use the new parameter and the middle-split methods in some obvious cases.
=> Upstream refactoring: Add Spacing parameter to H/VSplitMid, use methods and parameter where easily possible

README.md, src/engine/client/client.cpp
=> Disallow start_video outside of video player (fixes #4642)

src/game/ddracechat.h, src/game/server/ddracechat.cpp, src/game/server/ddracecommands.cpp, src/game/server/gamecontext.h, src/game/server/teams.cpp
to another player or spectated location. Requires /practice mode
As suggested by Rockus on Discord
=> Add teleport/tp chat command to teleport yourself

src/base/system.cpp, src/base/system.h, src/engine/shared/config.cpp, src/test/io.cpp
Not sure if it helps, but now it only syncs the config file.
Would supersede #4407.
=> Lower chance of losing written files by syncing them to disk on close, my try

src/base/system.cpp
Optimize `fs_listdir` and `fs_listdir_fileinfo` by reducing nested calls to `fs_is_dir` (and subsequent additional system API calls).
- Windows: check file attributes in `WIN32_FIND_DATAW finddata` instead of calling WinAPI again.
- Others: check file type of `struct dirent *entry` instead of calling `stat`. The file type may not be available on all filesystems, so a call to `fs_is_dir` is used as fallback.
Tested on Windows and Ubuntu.
See #4652. This reduces additional overhead.
=> Reduce system API calls when listing directory contents

src/game/client/components/binds.cpp
Since we store the bind with malloc, we also need to use malloc here to
allow any size when saving the binds in config file
=> Support saving any size binds (fixes #4660)

src/game/server/entities/character.cpp, src/game/server/gamecontroller.cpp, src/game/server/gamecontroller.h, src/game/server/player.cpp
As suggested by Rockus, should help speedrunners who get followed by
other players
=> Make spawn position independent of players in other teams

CMakeLists.txt, src/engine/client/client.cpp, src/game/client/components/items.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/players.cpp
Due to an upstream bug, some projectiles were not rendered the demo playback.
Rephrasing my in-code comment: "The render timing is usually screwed during demo playback because `s_LastGameTickTime` depends on the system timer, while the other part `Client()->PrevGameTick()-pCurrent->m_StartTick)/(float)SERVER_TICK_SPEED` is virtually constant (for projectiles fired on the current game tick): `(x - (x+2)) / 50 = -0.04`
We have a strict comparison for the passed time being more than the time between ticks `if(CurtickStart > m_Info.m_CurrentTime)` in `CDemoPlayer::Update()` so on the practice the typical value of `s_LastGameTickTime` varies from 0.02386 to 0.03999 which leads to Ct from -0.00001 to -0.01614."
Round up those to 0.0 to fix missing rendering of the projectile.
My merged MR to …
=> Fix projectiles rendering during demo playback (+ few more small changes)

src/engine/client/serverbrowser_http.cpp
```
[2022-01-08 09:57:03][serverbrowse_http]: found master, url='https://master1.ddnet.tw/ddnet/15/servers.json' time=54ms
[2022-01-08 09:57:03][client]: disconnecting. reason='unknown'
[2022-01-08 09:57:03][http]: https://master2.ddnet.tw/ddnet/15/servers.json failed. libcurl error: Callback aborted
[2022-01-08 09:57:03][serverbrowse_http]: master chooser aborted
```
Not instantaneous but much faster, depends on how often curl calls the PROGRESSFUNCTION.
=> HTTP Serverbrowser: Quit faster (fixes #4563)

src/game/server/gamecontext.cpp
Was added by GreYFoX in some big merge commit
https://github.com/ddnet/ddnet/commit/f7f6058a92b0e6030bdee50fb38a4ac2f61e0b7a#diff-aba621fd6688d4086ab40e58808cc12fdf591fdedf0d6c58cde2312b68cea5e0R1737
=> Remove commented out OnEntity call

src/game/server/entities/laser.cpp, src/game/server/entities/laser.h, src/game/server/entities/projectile.cpp, src/game/server/entities/projectile.h
to prevent /teleporting back to start line and cheating
Any thoughts on whether to include this for 15.9? I'd say yes.
=> Always destroy bullets/lasers on kill when in practice team (fixes #4694)

src/engine/shared/snapshot.cpp
Fixes
```
src/engine/shared/snapshot.cpp:373:13: runtime error: signed integer overflow: 1661611014 * 4 cannot be represented in type 'int'
#0 0x56377a580246 in CSnapshotDelta::UnpackDelta(CSnapshot const*, CSnapshot*, void const*, int) src/engine/shared/snapshot.cpp:373
#1 0x563779c540d3 in CClient::ProcessServerPacket(CNetChunk*) src/engine/client/client.cpp:1465
#2 0x563779c5a5fc in CClient::PumpNetwork() src/engine/client/client.cpp:1599
#3 0x563779c622ce in CClient::Update() src/engine/client/client.cpp:1769
#4 0x563779c774d2 in CClient::Run() src/engine/client/client.cpp:2112
#5 0x563779c92c74 in main src/engine/client/client.cpp:2712
#6 0x7fbf393bb0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
#7 0x563779b0e15d in _start …
```
=> Fix integer overflow of snapshot delta item size

CMakeLists.txt
Because the good guy microsoft respects the old habit of using local codepages for source code in Asia.
(In china and japan MSVC defaults to treating the source code as GBK and SHIFT_JIS encoded still.)
=> CMake: Use /utf-8 for MSVC

src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h
Just a guess that there might stil be garbage in this array
=> Initialize m_aErrorString earlier (fixes #4707)

src/engine/client/client.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/input.cpp, src/engine/client/sound.cpp, src/engine/client/text.cpp, src/engine/client/video.cpp, src/engine/server/server.cpp, src/engine/shared/datafile.cpp, src/mastersrv/mastersrv.cpp, src/tools/crapnet.cpp, src/tools/unicode_confusables.cpp, src/twping/twping.cpp
I assume the `// ignore_convention` comments are obsolete as they are only used inconsistently and not being added in new code anymore. The script https://github.com/teeworlds/teeworlds/blob/master/scripts/refactor_count.py that checks for these annotations does not exist in ddnet.
=> Remove obsolete ignore_convention comment

src/engine/shared/config_variables.h, src/game/client/components/nameplates.cpp, src/game/client/components/nameplates.h, src/game/client/components/players.cpp, src/game/client/components/players.h
As described in [x](https://github.com/ddnet/ddnet/issues/4589) the arrows that show the key presses of the players are not visible in many situations, this is now my attempt to fix this by including the arrows in the nametags.
~~Also, I created a new option called `cl_show_direction_below` to show the arrows below the player. We can discuss whether this is useful, or whether it should simply be displayed as before only above the player.~~
https://streamable.com/czk2ht
See also https://github.com/ddnet/ddnet/issues/4589
=> Show key presses in nameplates

src/game/client/components/menus_settings.cpp
Fixes broken checkbox, occurs when cl_show_hook_coll_other is set to 2.
=> Fix broken checkbox

datasrc/compile.py, datasrc/datatypes.py, datasrc/network.py
See https://github.com/teeworlds/teeworlds/pull/2688.
Fixes 
```
/src/game/client/components/players.cpp:95:102: runtime error: index 552473416 out of bounds for type 'CCharacterInfo [64]'
#0 0x5575323d614b in CPlayers::RenderHook(CNetObj_Character const*, CNetObj_Character const*, CTeeRenderInfo const*, int, float) /src/game/client/components/players.cpp:95
#1 0x557532401969 in CPlayers::OnRender() /src/game/client/components/players.cpp:701
#2 0x5575324ec369 in CGameClient::OnRender() /src/game/client/gameclient.cpp:598
#3 0x557531bf1310 in CClient::Render() /src/engine/client/client.cpp:1179
#4 0x557531c42a48 in CClient::Run() /src/engine/client/client.cpp:3152
#5 0x557531ca0c1a in main /src/engine/client/client.cpp:4424
#6 0x7f6fc51340b2 in __libc_start_main …
```
=> Validate variables of the snap-item base class

src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/client/graphics_threaded_null.h, src/engine/graphics.h, src/game/client/components/skins.cpp, src/game/client/gameclient.cpp
[src/game/client/components/skins.cpp](https://github.com/ddnet/ddnet/compare/master...Chairn:pr_skin?expand=1#diff-ae0c2e268081e8cb36b27c928f0daa590313583f43469bd486e63140404f360d) is using some fixed step suitable for RGBA png but it can be given a RGB which surprisingly doesn't crash it. Anyway, RGB pictures cannot be used as skins:
=> Drop non RGBA image in skins

scripts/parse_drmingw.sh, src/base/system.cpp
Get module offset, so we can at least recover the DDNet.exe paths:
`Error occurred on Wednesday, February 23, 2022 at 20:34:57. (with offset 00007FF7C4A00000)`
(Address - Offset) + (Image-Base)
(ImageBase  = winedump -f DDNet.exe (image base: usually 0x140000000)
Tested on windows 64-bit
https://github.com/Jupeyy/drmingw/commit/08ab91c4897c04b5919d14fc2d7c215015d0fb94
ez download from github actions:
https://github.com/Jupeyy/drmingw/actions/runs/1889238377
=> Add module offset

src/game/client/components/players.cpp
Changed the data source for local player angle so it updates every frame instead of once per tick.
I tested and it's still accurate even when mouse position is very close to the center.
=> Update local hook collision line every frame. 

src/game/server/entities/character.cpp
I believe this is the correct solution to https://github.com/ddnet/ddnet/issues/4646. 
I think the only reason specteam was working is because the CanCollide check would return false for tees outside your team most of the time (since they don't collide). But when you are in solo then you can't collide with anyone, so you won't even be able to see your own team in freecam.
=> Fix specteam 1 not showing teammates while spectating/freecam in solo

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
A new way to slice quads that doesn't make mappers pull their hair out.
To use it, open the quad context menu and click the _Slice_ button, check out the tooltip for more instructions.
Snaps automatically to corners and edges if close enough or to grid.
=> Quad knife tool

src/engine/client.h, src/engine/client/client.h, src/game/client/components/menus.cpp
This just saved the secret server for BiT3 streaming, but still a bug ;)
=> Show correct server address when connecting

src/game/client/components/ghost.cpp
I tried to reproduce another bug (https://github.com/ddnet/ddnet/issues/4207) and I noticed that ghosts are not allowed to carry any other weapons except grenade launcher and pistol. This is no longer necessary since we have been using the general renderer for players for a long time. We don't create projectiles for Ghosts, but it's always been like that and doesn't look worse than before.
So now you can see at least when the tee was frozen (before he was as seen in the linked issue with pistol in the freeze and alive)
=> Allow the ghost to carry any weapon | fix #4207

src/game/client/components/hud.cpp
Fixes the server timer in the HUD showing 00:00 when the server time exceeds around 248 days.
Tested on "Vanilla Teeworlds Server - CTF":
Otherwise connecting to this server causes:
```
/src/game/client/components/hud.cpp:128:17: runtime error: signed integer overflow: 26254443 * 100 cannot be represented in type 'int'
#0 0x55c8b6722e7d in CHud::RenderGameTimer() /src/game/client/components/hud.cpp:128
#1 0x55c8b675cdfc in CHud::OnRender() /src/game/client/components/hud.cpp:855
#2 0x55c8b6babec7 in CGameClient::OnRender() /src/game/client/gameclient.cpp:598
#3 0x55c8b62b0330 in CClient::Render() /src/engine/client/client.cpp:1179
#4 0x55c8b6301a62 in CClient::Run() /src/engine/client/client.cpp:3155
#5 0x55c8b635fc34 in main /src/engine/client/client.cpp:4427
#6 0x7f581a6150b2 in …
```
=> Fix integer overflow in CHud when server time exceeds around 248 days

src/game/client/components/players.cpp
In principle https://github.com/ddnet/ddnet/issues/4207 has already been fixed with https://github.com/ddnet/ddnet/pull/4770
But I don't know if the bug has influence on another part. The faulty animation code is hereby fixed. The problem is that when you shoot with the Rifle or the Shotgun the Muzzle animation is executed. This manipulates Alpha, Alpha itself is actually redefined in the condition, but apparently it overwrites the Alpha used for RenderHand since it is in the same code block (from line 279 to 537).
=> fix Alpha of Muzzle

src/engine/client/client.cpp
Fixes #4332, fixes #1698, fixes #4394, fixes #3544
For whatever reason the servers send "dm1.map" as map always (even if its not loaded at all), resulting in trying to disconnect the dummy, because on 
`NETMSG_CON_READY` message the config var `m_ClDummy` gets set, making the process server packet think this is the main connection, which then handles the map load as a map change. (The code generally doesn't look very safe, ez to break with the dummy connection check)
I changed the check to actually check if the connection is not the dummy connection for a few packets now, where i thought it doesnt make sense that the dummy connection (should) ever handle them
=> Fix dummy connect on some vanilla servers

src/game/client/components/menus_settings.cpp, src/game/client/gameclient.cpp, src/game/gamecore.h, src/game/server/entities/character.cpp, src/game/server/entities/dragger.cpp, src/game/server/entities/plasma.cpp, src/game/server/gamecontext.cpp, src/game/server/gameworld.cpp, src/game/server/player.cpp, src/game/server/teams.cpp
This just improves the readability of the code. Also like my last enum I don't know if `src/game/gamecore.h` is the best place for the enum, but I think it fits in well.
A question about this, maybe one can answer me without much research. It is about the technical part. Why does `/showothers` only affect dummy or player but `cl_show_others` affects both.
=> Add enum for ShowOthers value

src/game/client/components/menus_browser.cpp
=> More space for players in server browser (fixes #4777)

src/engine/shared/compression.cpp, src/engine/shared/compression.h, src/engine/shared/packer.cpp, src/engine/shared/snapshot.cpp, src/test/compression.cpp
- Refactor `CVariableInt::Pack` some more according to upstream:
- avoid right shift of negative number
- rewrite loop smarter
- Add size parameters to `CVariableInt::Pack` and `CVariableInt::Unpack`. Adjust tests and add tests with too small buffer sizes.
=> Add size checks to CVariableInt::Pack and ::Unpack, refactoring

src/game/client/components/players.cpp, src/game/client/components/players.h
Does anyone else feel that the code here: https://github.com/ddnet/ddnet/blob/ff085a4545cbe58fb7e613fca7b7cb2071e31629/src/game/client/components/players.cpp#L660-L709 is somewhat obfuscated? I do not think that the compactness of the code at this point increases the readability :D
=> Refactoring of players OnRender function

src/engine/server.h, src/engine/server/server.h, src/game/server/entities/character.cpp, src/game/server/entities/door.cpp, src/game/server/entities/dragger.cpp, src/game/server/entities/gun.cpp, src/game/server/entities/laser.cpp, src/game/server/entities/light.cpp, src/game/server/entities/pickup.cpp, src/game/server/entities/plasma.cpp, src/game/server/entities/projectile.cpp, src/game/server/entity.cpp, src/game/server/eventhandler.cpp, src/game/server/gamecontroller.cpp, src/game/server/player.cpp
#Fixes #4781
I took the opportunity and directly refactored the code a bit, to be exact I replaced the -1 with the enum `SERVER_DEMO_CLIENT`, I can also change the identifier if we want to call it something else. Further I normalized the corresponding `>= 0` conditions to `!= SERVER_DEMO_CLIENT`.
=> fix 4781 and refactor of the client id for server demos

src/game/client/components/items.cpp, src/game/server/entities/character.cpp, src/game/server/entities/door.cpp, src/game/server/entities/dragger.cpp, src/game/server/entities/gun.cpp, src/game/server/entities/light.cpp, src/game/server/entities/pickup.cpp, src/game/server/entities/plasma.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontroller.cpp, src/game/server/gameworld.cpp, src/game/server/teams.cpp
In some places TEAM_SPECTATORS and SPEC_FREEVIEW were forgotten to be used instead of -1
=> use TEAM_SPECTATORS and SPEC_FREEVIEW instead of -1

src/base/color.h, src/engine/client/graphics_threaded_null.h, src/engine/client/input.h, src/engine/client/serverbrowser.h, src/engine/client/text.cpp, src/engine/server/databases/mysql.cpp, src/engine/server/databases/sqlite.cpp, src/engine/server/server.h, src/engine/shared/demo.h, src/engine/shared/network.h, src/engine/shared/snapshot.h, src/game/client/animstate.h, src/game/client/gameclient.h, src/game/client/prediction/entities/character.h, src/game/editor/editor.h, src/game/server/gamecontext.h, src/game/server/player.h, src/game/server/save.h
For consistency with upstream (https://github.com/teeworlds/teeworlds/pull/2840) and
> to fix warnings in some IDEs and code analyzers.
I didn't find an option for clang format/tidy to enforce this.
=> Remove unnecessary trailing semicolons after method declarations

src/engine/shared/config_variables.h
Multiple reports that BiT3 doesn't load with higher OpenGL
=> Set gfx_opengl_major 1 as default on 32bit x86

src/engine/shared/config_variables.h, src/game/client/components/menus_settings.cpp, src/game/client/components/players.cpp
I felt the hook line was too thin and hard to see sometimes. This adds a config and a setting slider to adjust the size. 
I made it so size 0 will render exactly the same as before so there is no change unless you increase the size. 
The size scales as you zoom in/out in order to prevent the hookline from shrinking and eventually disappearing, this is functionally the same as it worked before since it would always be exactly 1 pixel wide.
=> Make hook collision line size adjustable

src/game/client/components/binds.cpp
=> Don't print binds into F1 by default (fixes #4789)

.github/workflows/clang-tidy.yml
clang-tidy 10.0 -> 13.0
Should be green, checked locally on Arch with 13.0.1
=> Use newer ubuntu with higher clang-tidy version

CMakeLists.txt, src/base/system.cpp, src/base/system.h, src/engine/engine.h, src/engine/shared/assertion_logger.cpp, src/engine/shared/assertion_logger.h, src/engine/shared/engine.cpp, src/engine/shared/jobs.cpp, src/engine/shared/jobs.h
This is a concept to write the full log to disk(inclusive the assert message), when an assert occurs, so it is not lost when no terminal or logfile is present.
Remaining question is:
- Should we really keep the full log in memory, maybe a maximum count of lines?
=> Write log to disk on assert

src/game/server/entities/laser.cpp
I've found this bug in a different mod and fixed it. Then I've got idea to check if any of the upstreams (this and tw)is  affected and it turned out that this is already [fixed](https://github.com/teeworlds/teeworlds/commit/f3a1e68df912520381d978dc43c46d48370f6e1c) in teeworlds.
I've dropped my change and did cherry-pick to reduce the difference between codebases.
=> Fix laser clipping. Closes #2176

src/game/client/components/players.cpp
Was detected by missing hammer animation at very high ping by texnonik and bencie
=> fix bug that sneaked in during refactoring (in #4775)

src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings_assets.cpp, src/game/client/ui.h, src/game/client/ui_ex.cpp, src/game/client/ui_ex.h
Pressing CTRL+F should select the current search string, like basically every text editor and browser does
=> Auto select search string on hot key

src/engine/client/client.cpp, src/engine/client/client.h
As suggested by bencie
> suggestion: would it be possible to add an optional parameter to save_replay so you could define the demo's name? save_replay [length] [demo name]
=> Add optional save_replay parameter, filename

src/game/client/components/chat.cpp, src/game/client/components/chat.h
This should fix #659 or just improve the order of player names if you use automatic completion. 
So far it was so that first at the beginning of the name was searched for the input and then there was a second iteration through the alphabetically sorted list with names where the input does not appear at the beginning.
Now it is so that the position of the input in the name is used as an evaluation criterion to determine the position in the suggestion list. If the input is found at the beginning of the name, the score is 0 and the name is suggested first. If the input is found at position 6 in the name, the score is 6 and the name appears later in the suggestion list. If two names have the same score, the alphabetical sorting remains.
=>  Improvement of the automatic completion of player names in chat

src/tools/map_replace_image.cpp
Happy to see that map_replace_image has actually been useful to you as it was used as a base to code map_convert_07.
As stated here https://github.com/ddnet/ddnet7/issues/20, map_replace_image seems to somehow break the map, that is due to a bad check inside the last datareader loop (it is just checking NumItems instead NumData).
Seems like it was just a coincidence that the tool was correctly working on the map i was testing, but i was able to confirm the problem by trying different maps.
now it is fixed.
=> Fixed bad DataReader loop on map_replace_image

src/engine/client/sound.cpp
I don't know if there is an issue for this but I think we all know the sound bug at least since the release of Back in Time 3. Namely when you are in certain parts of a large map or as a spectator to the right edge of a large map then it comes to integer overflow and you hear all players in full volume (as if you would create the sounds yourself e.g. by your own shooting).
The integer overflow is even detected by our nice UndefinedBehaviorSanitizer:
And can look like this:
/home/daniel/Desktop/other_repos/ddnet/src/engine/client/sound.cpp:165:48: runtime error: signed integer overflow: -92336 * -92336 cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/daniel/Desktop/other_repos/ddnet/src/engine/client/sound.cpp:165:48 in 
This is triggered …
=> fix sound bug in back in time 3

data/languages/german.txt, src/game/client/components/menus.cpp
As reported by bencie on Discord
Old:
New:
=> Fix demo render menu

src/base/system.cpp, src/base/system.h, src/engine/client/serverbrowser.cpp, src/engine/server/server.cpp, src/game/client/components/chat.cpp, src/game/server/gamecontext.cpp, src/test/str.cpp
Gets rid of the more complex str_comp_nocase_num usage
=> Add str_startswith_nocase and str_endswith_nocase

src/base/system.cpp, src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/client.cpp
```
/home/deen/isos/ddnet/ddnet-source/src/engine/client/backend/vulkan/backend_vulkan.cpp: In member function ‘void CCommandProcessorFragment_Vulkan::VerboseAllocatedMemory(VkDeviceSize, size_t, CCommandProcessorFragment_Vulkan::EMemoryBlockUsage)’:
/home/deen/isos/ddnet/ddnet-source/src/engine/client/backend/vulkan/backend_vulkan.cpp:92:74: warning: unknown conversion type character ‘z’ in format [-Wformat=]
92 |                 dbg_msg("vulkan", "allocated chunk of memory with size: %zu for frame %zu (%s)", (size_t)Size, (size_t)m_CurImageIndex, pUsage);
|                                                                          ^
/home/deen/isos/ddnet/ddnet-source/src/engine/client/backend/vulkan/backend_vulkan.cpp:92:88: warning: unknown conversion type character ‘z’ in format …
```
=> Fix some Windows build warnings

src/game/server/scoreworker.cpp
Fixes #4815 
**What was changed:**
- All Rank columns name were scapped since MySQL 8.0 interprets the word "Rank" as a internal function or constant (A good practice would be if all column names were escaped).
- All group by have been modified to have all columns that need to be grouped, in order to respect the `ONLY_FULL_GROUP_BY` flag set by default on MySQL 8.0. On these group bys were also included the columns that are used in the `window`, since are also required by the same tag.
**What is missing on this pull request:**
- "Add a mysql installation in .github workflow so we test this in addition to mariadb, then we don't break it again so easily."
**The behavior of all queries remains the same.**
=> Fix queries for MySQL 8.0

.gitignore
`.cache` is for clangd
`vulkan_shaders_sha256.txt`
also added `build*/` for all build dirs. Is there any drawback why we don't do that, is it bad style to do that?
I have quite a lot of stuff in my build dirs
callgrind info and so on
fixes #4865
=> Add some files & dirs to .gitignore

src/engine/client/graphics_threaded.cpp, src/game/client/components/countryflags.cpp
thanks to @ChillerDragon for finding this
=> Check pTexName for nullptr, fix wrongly height->width

src/game/client/components/ghost.cpp, src/game/client/components/nameplates.cpp, src/game/client/components/players.cpp, src/game/client/components/players.h
It seems difficult to measure the fps from the ingame graph or fps counter so these numbers are from NVidia fps overlay
FPS on full multeasymap server, fullscreen, vulkan renderer
/showall 0 - 4500
/showall 1 - 2100
/showall 1 (after preventing offscreen render) - 4200
=> Don't render tees or nameplates offscreen

CMakeLists.txt, src/base/vmath.h, src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h, src/engine/server/authmanager.cpp, src/engine/server/authmanager.h, src/engine/shared/storage.cpp, src/game/bezier.h, src/game/client/ui.cpp, src/game/client/ui.h, src/test/datafile.cpp, src/test/score.cpp
Get rid of all the shadowing that was reported by both gcc and clang. How both compiler can not see the same though they include same headers is a mystery.
=> Renamed all shadowed/shadowing variables

src/base/color.h, src/base/system.cpp, src/game/client/components/debughud.cpp, src/game/client/components/items.cpp, src/game/client/components/maplayers.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/prediction/entities/projectile.cpp, src/game/editor/editor.cpp, src/game/gamecore.cpp, src/game/server/entities/projectile.cpp, src/game/server/gameworld.cpp, src/game/server/scoreworker.cpp
Double promotion occurs quite often when an operator is an hidden double, like constants written without the 'f' at the end. We might get a tiny micro improvement. Unfortunately, we can't do anything for all the double promotion occurring in printf like functions as it is the default for both C and C++.
Only this line might change physics:
https://github.com/ddnet/ddnet/commit/4d47fcda094c3452a5924aad8811fd6965362ee3#diff-d76009083687ba43c59dc7bb2c7357457c999c2eb9d913967d598e913c6fd01fR406
=> Fixed some useless double promotion

src/engine/shared/websockets.cpp
Currently when a client tries to connect using websocket it will throw a segmentation fault. This is happening because of the std::string is trying to convert a char array with empty values to string directly.
```
==2305850== Invalid write of size 8
==2305850==    at 0x48401E9: memcpy@GLIBC_2.2.5 (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==2305850==    by 0x1E762D: websocket_callback(lws*, lws_callback_reasons, void*, void*, unsigned long) (in /home/ploi/ddnet/build/DDNet-Server)
==2305850==    by 0x4C7FB98: ??? (in /usr/lib/x86_64-linux-gnu/libwebsockets.so.15)
==2305850==    by 0x4C82F61: ??? (in /usr/lib/x86_64-linux-gnu/libwebsockets.so.15)
==2305850==    by 0x4C83206: ??? (in /usr/lib/x86_64-linux-gnu/libwebsockets.so.15)
==2305850==    by 0x4C9B84B: …
```
=> Fix websocket crash on client connect

src/game/server/ddracechat.cpp, src/game/server/score.cpp, src/game/server/score.h, src/game/server/scoreworker.cpp
Fixes #4903
- I hadn't seen the `ShowPlayerTeamTop5` function in the `scoreworker` in the last pull request, because in the `score` it has the same name as TeamTop5. A name change was made to make it easier to differentiate the two and fixed it for MySQL 8.0. It is not necessary to make this name change in the tests, since the tests use the `scoreworker` class directly.
- Ranking queries showing the duplicated rank were fixed. for this context it is not applicable to use distinct, since the `distinct` in SQL always checks all columns at the same time.
I'm going to leave this pull request in draft because getting the Server column in the same query as the show top still doesn't sound right to me. I used `MAX()` to match the same behavior before the change made by #4849, but it still …
=> Fix SQL duplicated top and player team top 5

src/game/client/components/players.cpp
This reverts commit ccc23161f639bab498fcdbe9f2cd14d0ceffa89d.
Caused inaccuracies. I tried checking what calculations the server does,
but couldn't figure it out quickly. @sjrc6 
Reported by Zeral:
https://user-images.githubusercontent.com/2335377/160875760-e639c752-d2e1-4ace-b98f-772dce689186.mp4
=> Revert "Hook collision calculation each frame"

src/game/client/components/players.cpp
This reverts commit 36bfe24522f468b06af401a9e6ee352b47599451.
Tested and couldn't reproduce the original problem with this.
=> Revert "Revert "Update players.cpp"" (fixes #4926)

src/engine/shared/config_variables.h, src/game/client/components/menus_settings.cpp, src/game/client/components/players.cpp
Suggested by louis in https://github.com/ddnet/ddnet/issues/4928
=> Adjustable hook collision line alpha

src/game/client/lineinput.cpp, src/game/client/lineinput.h
by terminating string instead of assuming that rest of chars are \0, which was just luckily true before.
=> Fix IME issue (fixes #4888)

src/game/client/components/ghost.cpp
I also tested it with ghosts with version 5 from 2018, they now all have correct color :D also the skin gets downloaded, but you have to rejoin the server to see it 
https://user-images.githubusercontent.com/14315968/161345903-489d7a8f-9086-43e8-b34c-b485fc998eb4.mp4
=> fix color of ghost

src/engine/client/video.cpp
Guess we should still let eeetadam test this
=> Use fewer threads on 32-bit to save memory

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/game/client/components/menu_background.cpp, src/game/client/components/menu_background.h, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings_assets.cpp, src/game/client/components/race_demo.cpp, src/game/client/components/race_demo.h, src/game/client/components/skins.cpp, src/game/client/components/skins.h, src/game/client/components/sounds.cpp, src/game/client/gameclient.cpp
This will keep the DDNet window responsive, especially when loading the client the first time this is important, so that SDL2 events aren't lost.
Menu's RenderLoading allows up to 60 frames per second, so calling it too often cannot really happen.
For reloading (skins&assets) / demo loading etc. it only swaps to the render screen after half a second passed. Even if this might not be the nicest, it's still better than just freezing the window.
I hope this addresses issues from #4936
=> Keep DDNet window responsive for loading tasks

src/engine/client/backend/vulkan/backend_vulkan.cpp
```
src/engine/client/backend/vulkan/backend_vulkan.cpp:1422:108: error: no matching function for call to 'maximum(size_t&, VkDeviceSize)'
```
=> Fix linux x86 compilation

src/game/editor/editor.cpp
Caused by commit 8134f9fa5511b0729f44c620e64779fce3badf44
Reported by Silex on discord:
https://user-images.githubusercontent.com/6654924/161612015-a04d6479-ac37-465e-929f-2cf5b7264103.mp4
=> Fix missing renamed shadowed variable

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_settings.cpp, src/game/client/ui.cpp, src/game/client/ui.h
Related to #4212
Example rendering a label:
=> Add DoTooltip

src/game/server/ddracechat.cpp, src/game/server/save.cpp, src/game/server/teams.h
I hope this doesn't give a chance to cheat. We also reset practice when
killing a team, so loading can be considered as similar to killing?
=> Reset practice when loading team (fixes #4894)

.github/workflows/build.yaml
```
The following packages have unmet dependencies:
mariadb-server : Depends: mariadb-server-10.3 (>= 1:10.3.34-0ubuntu0.20.04.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
=> Try to fix linux github worker build

src/game/editor/editor.cpp, src/game/editor/editor.h
https://user-images.githubusercontent.com/20344300/162440855-c716f6ba-4828-4c4b-97d2-e8e3da3ab4ea.mp4
Ctrl+leftclick on a tile in the map to select the layer that has tiles placed there. Useful if there are a lot of overlapping layers. Or plenty of doodads layers for example.
=> Editor: ctrl+leftclick tile to select layer

src/base/math.h
See #4970:
```
/home/runner/work/ddnet/ddnet/src/base/math.h:50:11: runtime error: left shift of negative value -32
#0 0x198d955 in i2fx(int) /home/runner/work/ddnet/ddnet/src/base/math.h:50:11
#1 0x197ebdf in CLayerQuads::NewQuad(int, int, int, int) /home/runner/work/ddnet/ddnet/src/game/editor/layer_quads.cpp:47:22
#2 0x18ef8d3 in CEditor::Init() /home/runner/work/ddnet/ddnet/src/game/editor/editor.cpp:6360:18
#3 0xa8e5be in CClient::Run() /home/runner/work/ddnet/ddnet/src/engine/client/client.cpp:2917:13
#4 0xaf6726 in main /home/runner/work/ddnet/ddnet/src/engine/client/client.cpp:4458:11
#5 0x7fadd9e610b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
#6 0x43cefd in _start (/home/runner/work/ddnet/ddnet/san/DDNet+0x43cefd)
```
Upstream …
=> Fix undefined behavior in fixed point number conversion

src/game/client/components/players.cpp
@C0D3D3V Mentioned this issue in comments of previous PR
https://github.com/ddnet/ddnet/pull/4760#issuecomment-1094307657
If you use the bind which limits your cursor range for 45 degree angles and constantly push your cursor to the left it will cause the angle to be inaccurate.  <s> I believe this is because of NaNs from division by zero but I'm not totally sure. </s>.  The cursor gets moved away from 0,0 whenever we send an input but it's allowed to be there in between ticks which causes this issue. 
I just copied this fix from other places in the code that deal with the same issue.
https://user-images.githubusercontent.com/14315968/162629342-c8bdeea4-f06f-472f-94b3-e7cccd597eb8.mp4
=> fix local hookline direction when mouse is exactly centerered

src/engine/client/graphics_threaded.cpp
fixes #4981 
This `bug` should not create any uninitended behavior, since these values get reinitialized after the backend creation worked
=> Don't read from backend if Init failed

src/game/client/components/controls.cpp
fixes #4953
I think the 200 units or 6.25 blocks more should not bother anyone. 
under some circumstances, it will only move to x=1 (or in blocks 0.03) but this should be negligible.
=> allow freecam to center on world border

src/engine/client/client.cpp, src/engine/server/server.cpp, src/engine/shared/network_client.cpp, src/engine/shared/network_server.cpp
https://github.com/ddnet/ddnet/pull/4970
Fixes
```
Direct leak of 205848 byte(s) in 1 object(s) allocated from:
#0 0x4a200d in malloc (/home/runner/work/ddnet/ddnet/san/DDNet-Server+0x4a200d)
#1 0xc7fe3f in net_udp_create /home/runner/work/ddnet/ddnet/src/base/system.cpp:1640:41
#2 0xbf2d0b in CNetServer::Open(NETADDR, CNetBan*, int, int) /home/runner/work/ddnet/ddnet/src/engine/shared/network_server.cpp:55:13
#3 0x568cdc in CServer::Run() /home/runner/work/ddnet/ddnet/src/engine/server/server.cpp:2448:60
#4 0x5a922b in main /home/runner/work/ddnet/ddnet/src/engine/server/server.cpp:3718:21
#5 0x7ff75f52c0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
```
=> Close sockets

.github/workflows/clang-sanitizer.yml
Start server and headless client once and see if it gets some ubsan or asan hits.
The headless client might have less or different violations of the holy c++ standard but its the best way to get some client code runtime in the CI.
Related issue https://github.com/ddnet/ddnet/issues/3050
=> Add UBSan and ASan to CI

.github/workflows/clang-sanitizer.yml, README.md, bors.toml, ubsan.supp
=> Add sanitizer runs to bors too, ignore pnglite shift ubsan issue

src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h
For #4939
For the performance warnings refering `vkCmdClearAttachments` ignore them, because this function is only called when:
- clear color is changed(open/close editor, switch between entities) to directly flush a clear with the new color
- ~~a viewport is used that is "worse" than 5:4 (I don't really want to switch to non renderpass clear completly, since it *can* improve performance -- https://community.arm.com/arm-community-blogs/b/graphics-gaming-and-vr-blog/posts/vulkan-samples "Therefore, avoid using LOAD_OP_LOAD and vkCmdClearAttachments and use LOAD_OP_CLEAR or LOAD_OP_DONT_CARE whenever possible.")~~
thinking about it, maybe i can also drop this call now, since its dynamic viewport anyway
=> Better forced viewport handling

src/engine/client/graphics_threaded.cpp
wrong from
50f9aa88d334365f3225d5c0347920f9e750549e
=> Fix wrongly used viewport parameters

src/base/system.h, src/engine/client/demoedit.cpp, src/game/client/components/console.cpp, src/game/client/components/console.h, src/game/client/components/menus.cpp, src/game/editor/editor.cpp, src/game/server/gamecontext.cpp, src/game/server/player.cpp, src/game/server/player.h
Seems like it got introduced by means of the false friend "actual" ≠
"aktuell" = "current".
=> Rename `Act` → `Cur`, some "actual" → "current"

src/game/client/components/binds.cpp
Since ghost menu and browser use F5 already to refresh, and having a
bind on it, would cause both actions at once.
I believe it makes sense to have this special handling only for F5,
other F-keys don't have this problem since we don't use them in any
menus.
=> Ignore F5 key press when ingame menu is open

src/game/client/gameclient.cpp, src/game/client/gameclient.h
Reported by Konsti here: https://discord.com/channels/252358080522747904/293493549758939136/967073772836376586
I have tested the change on Justfly with my dummy :D since it is exactly the same interval as before it should not change any Physics.
=> fix dummy hammer interval, this became incorrect after a few days

src/engine/client/backend/opengl/backend_opengl.cpp, src/engine/client/backend/opengl/backend_opengl.h
Fixes these memory leaks on my system (default opengl 3.0.3 renderer debian 11)
```
Direct leak of 72 byte(s) in 1 object(s) allocated from:
#0 0x4eac0d in operator new(unsigned long) (/home/chiller/Desktop/git/ddnet/asan/DDNet+0x4eac0d)
#1 0x537ebc in CCommandProcessorFragment_OpenGL2::Cmd_Init(CCommandProcessorFragment_GLBase::SCommand_Init const*) /home/chiller/Desktop/git/ddnet/src/engine/client/backend/opengl/backend_opengl.cpp:1672:21
#2 0x51f4ed in CCommandProcessorFragment_OpenGL::RunCommand(CCommandBuffer::SCommand const*) /home/chiller/Desktop/git/ddnet/src/engine/client/backend/opengl/backend_opengl.cpp:1061:3
#3 0x9e9d5e in CCommandProcessor_SDL_GL::RunBuffer(CCommandBuffer*) /home/chiller/Desktop/git/ddnet/src/engine/client/backend_sdl.cpp:250:20
#4 0x9e57ab in …
```
=> Free some opengl2 pointers

src/game/client/components/players.cpp
I am not sure if there is a more elegant solution, the problem is that fmod in cpp does not return a positive value. maybe we can just use a mod function that always returns positive values.
=> fix WalkTime for negativ positions

src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/backend_sdl.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/engine/shared/config_variables.h, src/game/client/components/menus_settings.cpp
This allows changing FSAA under Vulkan without restarting the client
=> Allow onfly FSAA change under Vulkan

src/game/client/components/tooltips.cpp
=> Fix tooltip locations after window resize (fixes #5026)

src/engine/client/client.cpp, src/game/client/components/menus_settings.cpp, src/game/variables.h
Risky Feat suggested this idea to me, I also thought it was good so I implemented it. 
If you press one of the eyes in the settings it will change which eyes you get when you join a server.
It saves a separate variable for dummy/player.
It will also change your eyes anytime you press one of them, but only if you are playing as the same Tee whose eyes you are trying to change. If someone could figure out the best way to make it change the opposite Tees eyes as well that would be nice but I don't think it's necessary. 
It also changes the "Your Skin:" Tee eyes on the left if you have one selected. 
I had to change the cl_run_on_join code a bit, I tested and I don't think it should ever break anything but it might be good for someone to double check.
=> Add option to change default eyes when joining server

src/game/client/components/binds.cpp
I do not see any reason for these loops. Do I oversee something?
=> remove unnecessary loop over the possible modifier combinations

CMakeLists.txt, other/config_directory.bat, other/config_directory.sh, src/base/system.cpp, src/base/system.h, src/engine/client/client.cpp, src/engine/server/server.cpp, src/engine/shared/storage.cpp, src/engine/storage.h, src/mastersrv/main_mastersrv.cpp, src/tools/dummy_map.cpp, src/tools/map_convert_07.cpp, src/tools/map_optimize.cpp, src/tools/map_replace_image.cpp, src/tools/map_resave.cpp, storage.cfg
This way new players will get DDNet directory, old ones can switch
directory if they want, or keep using the old one.
If we ever enforce a switch in a future version, this will make it
easier since older DDNet versions will also support the DDNet directory
already.
=> Switch new players to DDNet config dir, support Teeworlds as fallback

src/game/client/prediction/entities/laser.cpp, src/game/server/entities/laser.cpp
I hope this kind of physic isn't used anywhere, I couldn't trigger it without being stuck in wall.
=> Don't allow infinite shotgun bounce (fixes #4809)

src/engine/shared/config_variables.h, src/game/client/gameclient.cpp
Since most of the predict code is only ddrace relevant anyway, I would suggest removing the cl_predict_ddrace option instead of checking if m_WorldConfig.m_PredictDDRace is set everywhere ddrace stuff is predicted. 
in case of conflicts with physics from other mods, the check on m_WorldConfig.m_PredictDDRace must however be implemented in the appropriate places (for example for the freeze and unfreeze functions). But since there are currently no conflicts apparently, this is sufficient for now.
fixes the bug I reported here: https://discord.com/channels/252358080522747904/293493549758939136/968114944878989363
@trml  what do you think about this?
=> remove cl_predict_ddrace

src/engine/shared/config_variables.h
=> Allow sv_show_others_default in map settings

src/engine/server/server.h
Not sure I like it, otherwise we have to edit Game City.
Maybe we should fail this in map editor already instead of allowing to
create a map which requires > MAX_IDS
=> Increase MAX_IDS to 32k (fixes #4723)

ubsan.supp
Since we have no control over this library
=> Ignore non-zero offset to null pointer in json.c (fixes #5031)

src/game/client/components/maplayers.cpp
Fixes the issue from cheeser0613 in discord, that showed a quad that shouldnt exists.
The quadoffset is only +1 if the current quad is fully transparent(this was added a while ago to improve performance of the firework background).
This affects OpenGL 3.3 & Vulkan and was introduced with the Vulkan change.
=> Fix wrong quad offset for (not caused by transparent) flushes

src/game/client/components/console.cpp
When going beyond the last page it was previously redrawn in a hacky way, which was also not updated to use the correct console colors, so the colors would flash white when holding the page up key.
The underlying fix is the same as on upstream https://github.com/teeworlds/teeworlds/pull/3063. The rendered page will only be changed after the log has already been rendered, to ensure that the page can be clamped correctly.
Closes #5040.
=> Fix flashing colors in console when scrolling up continuously

src/game/client/components/tooltips.cpp, src/game/client/components/tooltips.h
This reverts commit 4e3d5c562617913548ca6d3f61813200e292c962.
Should work again with clang++-7 and libc++-7. See
https://github.com/ddnet/ddnet-scripts/commit/2534d627ac47dc52af7fc5222d0ce5763b1c202e
So I discovered that clang 7 is available on Debian 9, and it claims to have full C++17 support.
=> Revert "Get rid of optional, not available on Debian9 build"

src/engine/client/client.cpp
fixes #5056
stop using the same buffer as dest and source.
=> Fix undefined behavior in default eyes string formating

src/engine/server/databases/connection_pool.cpp
Looks nicer IMO if you don't show the message if there's no actual
waiting.
=> Don't print the first "Waiting for score threads to complete"

src/game/client/components/menus.cpp, src/game/client/components/menus_demo.cpp, src/game/client/ui_ex.cpp
Improve demo slice popup:
- add more margins
- decrease font size of error message slightly
- correct handling of all allowed UI scale values:
- fix overlapping elements on some UI scales by laying out all CUIRects (except the buttons) from top to bottom
- make `New name:` label scaled
Refactoring:
- Use `CUI::Margin` instead of both `HMargin` and `VMargin`, when the margin value is identical.
- Pass 0 instead of CUIRect pointer in some cases where the value is never used, i.e. never read and overridden in the next line.
Before:
After:
Tested with `ui_scale 50/90/100/110/150`.
=> Improve demo slice popup, minor refactoring of UI/menus

src/game/server/ddracechat.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
Fixes #5052.
The problem seems to be that there are two different concepts tangled up
in console/logging. One is actual logging as in other programs. The
other is "responses to the user of the command that was just entered",
like for rcon or chat commands. This issue isn't fixed by this commit.
=> Only output messages intended for chat to the user of a chat command

src/game/client/components/menus_settings.cpp
suggested in https://github.com/ddnet/ddnet/issues/5057
works for player and dummy
=> Render tees in skin selector with default emote

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/client/ui_ex.cpp, src/game/editor/editor.cpp
Various CUI refactorings adapted from upstream:
- Support nesting CUI clipping/scrolling regions.
- Add `CUI::MouseHovered` which works like `MouseInside` and also ensures that the position is not clipped.
- This is used to refactor all scrolling lists, removing duplicate code that manually intersects the clipping rectangle.
- It's also used to make clipping of the key reader buttons in the controls settings list smoother, as the buttons were previously not rendered at all when clipped.
- Nesting other common UI elements (editboxes, pickers, scrollbars) in clipping regions is also possible now.
=> Support nesting CUI clipping regions and other UI elements, smooth clipping of controls settings list, refactoring

src/test/teehistorian.cpp
Looks cleaner now, e.g. for TeamPractice:
```
[ RUN      ] TeeHistorian.TeamPractice
pOutput = {
0x41, 0x00, 0x4a, 0x57, 0x92, 0x83, 0x4e, 0x81, 0xd1, 0x34
0xc9, 0xa2, 0x9b, 0xb5, 0xff, 0x25, 0xda, 0xc3, 0xbc, 0x02
0x17, 0x01, 0x41, 0x00, 0x4a, 0x57, 0x92, 0x83, 0x4e, 0x81
0xd1, 0x34, 0xc9, 0xa2, 0x9b, 0xb5, 0xff, 0x25, 0xda, 0xc3
0xbc, 0x02, 0x01, 0x01, 0x4a, 0x57, 0x92, 0x83, 0x4e, 0x81
0xd1, 0x34, 0xc9, 0xa2, 0x9b, 0xb5, 0xff, 0x25, 0xda, 0xc3
0xbc, 0x02, 0x17, 0x00, 0x40
}
[       OK ] TeeHistorian.TeamPractice (0 ms)
```
=> Enhance teehistorian test output a bit

src/engine/client/backend/vulkan/backend_vulkan.cpp
Most messages in the backend are warnings.
At least these two are send every time you minimize/maximize the window, so kinda annoying
=> Move create/destroy window ntf dbg_msg to log_debug

src/game/server/entities/character.cpp
```
src/game/server/entities/character.cpp: In member function ‘void CCharacter::SendZoneMsgs()’:
src/game/server/entities/character.cpp:2013:78: warning: the address of ‘CGameContext::m_aaZoneLeaveMsg’ will never be NULL [-Waddress]
2013 |         if(m_TuneZoneOld >= 0 && GameServer()->m_aaZoneLeaveMsg[m_TuneZoneOld])
|                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
In file included from src/game/server/entities/character.cpp:7:
src/game/server/gamecontext.h:179:14: note: ‘CGameContext::m_aaZoneLeaveMsg’ declared here
179 |         char m_aaZoneLeaveMsg[NUM_TUNEZONES][256];
|              ^~~~~~~~~~~~~~~~
src/game/server/entities/character.cpp:2028:53: warning: the address of ‘CGameContext::m_aaZoneEnterMsg’ will never be NULL [-Waddress]
2028 | …
```
=> Only print zone messages when there is one

src/game/teamscore.h
I could not find a way that an invalid client ID is used here, but
compiler warns anyway:
```
In member function ‘void CTeamsCore::SetSolo(int, bool)’,
inlined from ‘void CCharacter::SetSolo(bool)’ at src/game/client/prediction/entities/character.cpp:29:22,
inlined from ‘void CCharacter::HandleTiles(int)’ at src/game/client/prediction/entities/character.cpp:882:10:
src/game/teamscore.h:45:34: warning: array subscript [0, 63] is outside array bounds of ‘bool [64]’ [-Warray-bounds]
45 |                 m_IsSolo[ClientID] = Value;
|                 ~~~~~~~~~~~~~~~~~^
src/game/teamscore.h: In member function ‘void CCharacter::HandleTiles(int)’:
src/game/teamscore.h:27:14: note: while referencing ‘CTeamsCore::m_IsSolo’
27 |         bool m_IsSolo[MAX_CLIENTS];
|              ^~~~~~~~
```
=> Assert client id in SetSolo

src/engine/client/backend/vulkan/backend_vulkan.cpp
From https://github.com/SaschaWillems/vulkan.gpuinfo.org/blob/5c3986798afc39d736b825bf8a5fbf92b8d9ed49/includes/functions.php#L364
I dunno how reliable that is, but https://gpuinfo.org is quite good, so probs reliable enough for our needs :D
Similar to how OpenGL also prints the driver version in the GL_VERSION string. Can be quite useful and is easier for the end user
=> Add basic driver version parsing for Vulkan

data/autoexec_server.cfg
Since it clears out the randomly generated password
=> Don't reset rcon password on "Reset server" (fixes #5113)

src/engine/server/server.cpp
Fixes creating two teehistorian files. And probably increases performance :). Fixes #5121
=> Fix server loading map twice on startup

src/engine/shared/console.cpp
=> Fix /cmdlist output not being shown in chat

src/engine/client/client.cpp, src/game/client/components/statboard.cpp, src/game/client/components/statboard.h
The memory allocated in and returned by `ReplaceCommata` was never freed.
Likewise `m_pCSVstr` allocated in `FormatStats` was never freed.
This also fixes a stringop-overflow warning and that the allocated memory size was missing one byte for the zero terminator.
The `ReplaceCommata` method is now also used for the gametype and map. Although unlikely, commata can be used in gametype and map names, so this prevents invalid CSVs for those cases.
Refactoring: remove unnecessary copy of `pStr` into `aBuf`.
=> Fix memory leaks in auto stat CSV output, fix stringop-overflow warnings

CMakeLists.txt, src/game/client/components/maplayers.cpp
@Kaffeine 
Windows x86-64 with MinGW worked, previously:
```
-rwxr-xr-x 1 deen deen 755K May 15 11:38 config_retrieve.exe*
-rwxr-xr-x 1 deen deen 756K May 15 11:38 config_store.exe*
-rwxr-xr-x 1 deen deen 2.8M May 15 11:38 DDNet.exe*
-rwxr-xr-x 1 deen deen 2.1M May 15 11:38 DDNet-Server.exe*
-rwxr-xr-x 1 deen deen 761K May 15 11:38 dilate.exe*
-rwxr-xr-x 1 deen deen 763K May 15 11:38 map_convert_07.exe*
-rwxr-xr-x 1 deen deen 756K May 15 11:38 map_diff.exe*
-rwxr-xr-x 1 deen deen 761K May 15 11:38 map_extract.exe*
```
Now:
```
-rwxr-xr-x 1 deen deen 256K May 16 00:26 config_retrieve.exe*
-rwxr-xr-x 1 deen deen 282K May 16 00:26 config_store.exe*
-rwxr-xr-x 1 deen deen 2.8M May 16 00:26 DDNet.exe*
-rwxr-xr-x 1 deen deen 2.0M May 16 00:26 DDNet-Server.exe*
-rwxr-xr-x 1 deen deen 271K May 16 …
```
=> Fix IPO build problems

CMakeLists.txt, src/base/system.h, src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/shared/network.h, src/engine/shared/network_client.cpp, src/engine/shared/network_stun.cpp, src/engine/shared/stun.cpp, src/engine/shared/stun.h, src/game/client/components/menus.cpp, src/tools/stun.cpp
These diagnostics are supposed to guide the user to problem resolution.
They're displayed if no packet is received from the server within one
second of connecting.
No message if we don't have STUN servers.
"Trying to determine UDP connectivity..." if no answer has been received
from the STUN server yet and it hasn't timed out yet.
"UDP seems to be filtered." if the STUN request has timed out.
"UDP and TCP IP addresses seem to be different. Try disabling VPN,
proxy or network accelerators." if the STUN request has returned an IP
address different from the one obtained via HTTP from info2.ddnet.tw.
"No answer from server yet." otherwise, if the STUN request has returned
no interesting data, indicating that it's likely the game server's
fault.
=> Use STUN to determine UDP connectivity and show diagnostics

src/base/log.cpp, src/engine/client/client.cpp, src/engine/shared/config_variables.h, src/game/client/components/menus_settings.cpp
Alternative to #5154. 
Closes #5150.
If you want to open the client with a console window, instead create a new shortcut with the following target:
```
cmd /c "C:\path\to\your\DDNet.exe"
```
You can change the icon of the shortcut to the DDNet icon in the properties of the shortcut file.
=> Remove cl_show_console and -c / --console command line options, attach to existing console

src/game/client/prediction/entities/character.cpp, src/game/gamecore.cpp, src/game/server/entities/character.cpp
fixes #5167
- Add some more documentation to the code
- reverted early ground jump to keep old physics (I have not noticed it will allow the jump one tick earlier at the time I made the change)
=> Fix special Jumps for players with 0, 1 and -1 Jumps

src/engine/shared/console.cpp, src/engine/shared/console.h
Extract `CConsole::TraverseChain` (https://github.com/teeworlds/teeworlds/pull/2933).
Fix `toggle`/`+toggle` commands with commands which are chained multiple times.
=> Extract CConsole::TraverseChain, fix toggle with multiple chains

src/game/gamecore.cpp
Sorry I did make a mistake in #5172  I tricked myself, the code block I moved back down below the jumping physic (where it original was):
https://github.com/ddnet/ddnet/blob/79f377b1338728de8cde936e0b10d0a1946a00b4/src/game/gamecore.cpp#L216-L221
did not prevent instant ground jump, i somehow thought wrong and maybe combined it wrong with my new condition.
i tested everything again with 15.9.1 (and 16.0.3) and looked at the old code and noticed that it was allowed to make a ground jump directly in the same tick as you have contact with the ground. Therefore I revert this herewith (by fixing the condition)
xD is really a tricky thing to make changes at the gamecore, and keeping everything as it should be
Sorry!!
=> revert to ground jump at the same tick

src/engine/client/text.cpp, src/game/client/components/hud.cpp
=> Fix HUD rebase (thanks to bencie for report)

src/game/client/prediction/entities/character.cpp
reported by nori 
https://cdn.discordapp.com/attachments/293493549758939136/977531792389177364/recording.mp4
I have somehow made the condition wrong xD although I had written correctly in the PR what it should do.
also i noticed that teeworlds does not allow you to hold the hook while chatting, but we have allowed this since 2014....
=> Fix chat prediction

src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h
Apparently NVIDIA drivers don't fail on context creation if a unsupported FSAA count is used. (For me it does and automatically sets the FSAA sample to the first working FSAA number)
Desktop OpenGL has no way to query the amount of FSAA it supports, so I just clamp it to 8 for OpenGL for now, since the client always allowed these values.
Vulkan has a way to query it, and also uses it already. nouaa could only reproduce it with OpenGL setting FSAA to 64
GLES 3 [has a way to query max FSAA (GL_MAX_SAMPLES) ](https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glGet.xhtml) and the spec mentions minimum supported is 4. If context creation fails it should also directly try that, instead of iterating through many invalid fsaa samples(uneven numbers) -- (saw this in my log when it went …
=> Lower max allowed FSAA on OpenGL

CMakeLists.txt, src/base/vmath.h, src/engine/shared/demo.cpp, src/engine/shared/econ.cpp, src/engine/shared/econ.h, src/engine/shared/network_stun.cpp, src/game/client/components/menu_background.cpp, src/game/client/prediction/entities/laser.cpp, src/game/client/prediction/entity.cpp, src/game/server/entities/laser.cpp, src/game/server/save.cpp
Supersedes #5181 
Objects should be initialized fully, otherwise they are super easy to misuse and get weird undefined behavior that happens rarely.
=>  Fix pickups moving on their own (fixes #5137)

CMakeLists.txt
I'll still build the official builds with IPO=ON.
CC @Kaffeine
=> Disable IPO by default since it slows down linking a lot, Use better available linkers (mold > lld > gold > ld)

src/engine/server/server.cpp, src/engine/shared/http.cpp
Otherwise `curl_global_init` would be called from the first
`curl_easy_init`, but `curl_global_init` isn't threadsafe.
Fixes #5195.
=> Call `HttpInit` in server

src/game/client/components/console.cpp
Holding down the pos1 key will still make the console text flash though.
Fixing that would require to first calculate the total number of pages in a separate pass before rendering the current page.
=> Fix pos1 only scrolling up one page in console

src/game/server/entities/dragger_beam.cpp
=> do not snap dragger beam, if the target is out of reach

src/game/gamecore.cpp, src/game/gamecore.h
Reported by @Ясно Понятно 
on non ddnet server, this code gets run to detect strong-weak ids:
https://github.com/C0D3D3V/ddnet/blob/6a5673aa04c216948ce76de1a505c419d0715b1e/src/game/client/gameclient.cpp#L2540-L2541
which causes a crash because this CCharacterCore is not bound to a gameworld 
the check for m_pWorld failed because m_pWorld is full of random data
https://github.com/ddnet/ddnet/blob/ac15943e85b04f29fc8e85096222c5f6a85ac7f1/src/game/gamecore.cpp#L625
So I would also like to initialize it with a nullpointer
=> Fix crash because of hooks on non ddnet server

CMakeLists.txt, src/game/client/components/maplayers.cpp, src/macos/server.mm
```
ld64.lld: warning: /opt/homebrew/opt/freetype/lib/libfreetype.6.dylib has version 12.0.0, which is newer than target minimum of 11.0.0
ld64.lld: error: LC_DYLD_INFO_ONLY not found in /opt/homebrew/opt/freetype/lib/libfreetype.6.dylib
ld64.lld: warning: /usr/local/lib/libGLEW.2.2.0.dylib has version 12.0.0, which is newer than target minimum of 11.0.0
ld64.lld: error: LC_DYLD_INFO_ONLY not found in /usr/local/lib/libGLEW.2.2.0.dylib
ld64.lld: warning: /opt/homebrew/Cellar/wavpack/5.4.0/lib/libwavpack.dylib has version 12.0.0, which is newer than target minimum of 11.0.0
ld64.lld: error: LC_DYLD_INFO_ONLY not found in /opt/homebrew/Cellar/wavpack/5.4.0/lib/libwavpack.dylib
ld64.lld: warning: /opt/homebrew/Cellar/ffmpeg/5.0.1/lib/libavformat.59.dylib has version 12.0.0, which is newer …
```
=> macOS fixes

src/game/client/gameclient.cpp, src/game/gamecore.cpp
Fixes #5226
I tested it in a Windows VM.
@sjrc6 is it correct that `TempCore` is this way zero initialized, can you check that maybe in the debugger? I do not want to change the behaviour, even tho the core is read in two lines later with `TempCore.ReadCharacter(pCharacter);`
=> Fix windows crash

src/game/server/entities/dragger.cpp, src/game/server/entities/dragger_beam.cpp, src/game/server/entities/dragger_beam.h
The check whether a dragger is active, I somehow forgot in the dragger beams. Sorry! Actually, I should have noticed this during testing. But when I tested Fall into the Future today, it seemed strange to me (already at the first part). I should have noticed it when I tested it. I have compared that in any case with 15.9.1 and looked at the code again and saw that there the check is made every tick.
=> disable dragger beams soon, not only every 150ms

src/base/log.cpp
=> Don't enable colors when stdout is redirected to a file (fixes #5233)

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_settings.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/client/ui_ex.cpp, src/game/editor/editor.cpp, src/game/editor/popups.cpp
Port e98921593bf23886de32ffb2fce9b166a89d6c05 from upstream.
Closes #1884. I can consistently reproduce the locked up UI according to @Jupeyy's description and can confirm that this PR fixes this behavior:
>I think i found a way to reproduce it
> press left & right mouse click (hold them)
> press F5 (refresh)
> now you cannot click anything anymore
Minor refactoring: use `nullptr` instead of `0` for UI active item.
=> Add `CUI::CheckActiveItem`, preventing the UI from locking up

src/engine/client/video.cpp, src/engine/client/video.h
Fixes #5051
With the video recorder rework, start and ending video rendering waits for the graphics threads anyway, additionally we never skip a frame while videos are rendering, so these checks are not needed anymore.
Basically like this
Update (sets true) => frame starts(but is not finished)
=> next update (sets to true again, but video frame still not finished) => frame starts(but swap waits for last frame).. last frame sets to false => this frame is fast, but var is false => frame skipped
=> Don't ever skip any frame

src/engine/server/server.cpp, src/engine/server/server.h
fixes #5207
Not going to rewrite rn since it relies on normilization of the time.
Hope this is enough, floats probs struggle with time_freq and time differences being so huge
=> Use double for traffic calculations

src/game/client/components/menus.cpp, src/game/client/ui.cpp, src/game/client/ui.h
Fixes the following behavior:
1. Player is ingame and the ingame menu is opened with Esc
2. A mouse button is held down on one of the ingame menu buttons (e.g. the spectate button)
3. The ingame menu is closed without moving the mouse away from the button
4. The mouse button is released while ingame
5. The menu is opened again
- Current behavior: The hovered button is immediately activated, as soon as the menu opens, due to the released mouse state being handled as a click.
- Fixed behavior: The button is not activated. Instead another call to `FinishCheck` is added so it's also called when the menu is not active, to clear the active UI item in that case.
As well as the following:
1. The menu is closed while the mouse cursor is hovering over a button.
2. The mouse button is pressed and …
=> Fix ingame menu button behavior when holding mouse button

src/game/server/entities/character.cpp
The continuation  of removing mem_zero over CCharacterCore.
I have tested the server in a Windows VM -> no crash
=> fix windows server crash on client spawn

src/game/client/prediction/entities/laser.cpp, src/game/server/entities/laser.cpp
fixes #5258
bug got fixed by the math changes in https://github.com/ddnet/ddnet/commit/68bcd21eff9fbace8605eec8122f860499e03c21
This fix introduces a hard coded velocity that the player would get like before. (It could be that this has slightly other behaviour, because before the produced NaN values where converted to ints in CCharacterCore::Quantize (so some other logic may be confronted with the NaN values before), but it should most likely not be noticeable because it is fast enough)
We could now make this bug optional, by adding it to our mapbugs, or adding a server setting for it.
=> reintroduce shotgun bug

src/engine/shared/image_manipulation.cpp, src/engine/shared/image_manipulation.h, src/tools/map_optimize.cpp
Since it was removed from dilate's copy values, and also makes more sense anyway.
Images should always be identifiable by all visible pixels
=> Remove alpha threshold from map_optmize

src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/client/prediction/entities/character.cpp, src/game/client/prediction/entities/character.h, src/game/client/prediction/entities/pickup.cpp, src/game/client/prediction/entities/projectile.cpp, src/game/client/prediction/entity.h, src/game/client/prediction/gameworld.cpp
I looked over the remaining code for creating/removing entities in the prediction, and only ended up making some smaller changes:
- More consistent use of InsertEntity/RemoveEntity/Destroy
- Fixed one instance in gameclient.cpp where an entity was removed but not deleted (could potentially have been a memory leak)
- Removed some old code for retaining information about the characters after they left the snapshot (the client should only rely on the snapshot for prediction of players)
=> Cleanup prediction entity handling a little

src/engine/client/client.cpp, src/engine/shared/config_variables.h
Following user report that they set cl_port 1 and it didn't work
=> Prevent users from setting port 1-1023

CMakeLists.txt, src/base/log.cpp, src/engine/server/databases/mysql.cpp, src/engine/server/databases/sqlite.cpp, src/engine/server/server.cpp, src/engine/shared/assertion_logger.cpp, src/engine/shared/http.h
No idea why clang-tidy's modernize-... didn't work
=> Use std::make_unique (fixes #5166)

src/game/server/entities/dragger.cpp, src/game/server/entities/dragger_beam.cpp
fixes #5263
@bencie  could you please confirm it fixes the problem?
=> Execute the dragger_beam tick one tick earlier. And stop it one tick earlier

src/base/vmath.h, src/game/client/components/hud.cpp, src/game/client/components/players.cpp, src/game/client/gameclient.cpp, src/game/client/prediction/entities/character.cpp, src/game/client/prediction/entity.cpp, src/game/client/prediction/entity.h, src/game/client/prediction/gameworld.cpp, src/game/gamecore.cpp, src/game/gamecore.h, src/game/server/entities/character.cpp, src/game/server/entities/character.h, src/game/server/entities/dragger.cpp, src/game/server/entity.cpp, src/game/server/entity.h
Add `Collision()` getter to server CEntity to make it easier to sync the server and prediction implementations (e.g. `IsGrounded()` imps are now identical).
=> Introduce and use constexpr CCharacterCore::PhysicalSize

src/base/system.cpp
by returning nullpointer, as the calling functions expect
Broken in https://github.com/ddnet/ddnet/commit/471bb441a14af9502558cfc7203de96f72547e87
=> Handle failed socket creation (fixes #5267)

src/game/client/prediction/entities/character.cpp, src/game/gamecore.cpp, src/game/gamecore.h, src/game/server/entities/character.cpp, src/game/server/save.cpp
- remove duplicated variable for no collision and no hook
fixes https://github.com/ddnet/ddnet/issues/5279
https://youtu.be/3VM64OVNgYM
I chose the no variables because I found them more meaningful than the one without no. Furthermore, the initialisation with false corresponds to the standard initialisation.
=> fix swap does not swap no collision and no hook

src/engine/server/server.cpp, src/game/server/entities/character.cpp
Also map gets reloaded if the server tick overflows. We could add a warning, that the server reloads soon, or save all players and load them after map reload. But I think that is such a rare event, we can just reload the map without these nice things.
fixes #5170
we should check the following maps for cheated times:
- just every fly
- puzzle partners
- time shop
=> penalty tiles can be used to get a time of 00:00:01, this is fixed by letting the tees die, before that happens

CMakeLists.txt, src/base/math.h
This allows us to use `std::min`/`std::max`.
=> Work around Windows's definition of `min`/`max`

src/engine/server/server.cpp
The string comparison isn't actually done anymore, it's now done via a
boolean flag.
=> Remove outdated comment

.gitignore
Both file types are used in conjunction with the HTTPS master.
=> Add *.csv and *.json to .gitignore

src/engine/shared/network_stun.cpp
Log send errors with debug instead of error severity. They're normal in case a protocol stack isn't initialized supported by the host or if there's no route.
Don't periodically retry STUN if successful. Trying again for each connection establishment is enough. Previously, it
was re-requested every 10 minutes.
Fixes #5273.
=> Don't output as much in normal STUN behavior

src/base/log.cpp
- Remember initial console foreground and background color.
- Use the original background color with the message specific foreground color, so it looks better when the console background color isn't black.
- Restore the initial console foreground and background color on exit instead of leaving the color be whatever was last used.
- Add locks to ensure `Log`-calls from different threads don't overlap their output/color.
- Refactoring: Replace numbers with color constants defined in `wincon.h` (https://github.com/wine-mirror/wine/blob/4312d209232c701b0b78d9f8b463917c989005c5/include/wincon.h#L51-L67).
- Refactoring: Slightly reorder the `if`s and remove redundant checks which are ensured by the `else-if` structure.
=> Windows: Use current console background color, restore original color on exit, refactoring

datasrc/datatypes.py, datasrc/network.py, src/game/client/components/items.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/client/prediction/entities/character.cpp, src/game/client/prediction/entities/pickup.cpp, src/game/client/prediction/entities/projectile.cpp, src/game/client/prediction/entity.h, src/game/client/prediction/gameworld.cpp, src/game/client/prediction/gameworld.h, src/game/collision.cpp, src/game/collision.h, src/game/gamecore.cpp, src/game/gamecore.h, src/game/server/entities/character.cpp, src/game/server/entities/door.cpp, src/game/server/entities/dragger.cpp, src/game/server/entities/dragger_beam.cpp, src/game/server/entities/gun.cpp, src/game/server/entities/light.cpp, src/game/server/entities/pickup.cpp, src/game/server/entities/projectile.cpp, src/game/server/entity.h, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/gamecontroller.cpp, src/game/server/save.cpp, src/game/server/save.h, src/game/server/teams.cpp
This is an attempt to fix #4702, and also ended up being a more general attempt at predicting switch on/off tiles as well as timed switchers (with delay). A few things:
- Refactored the switch state array from CCollision to CGameCore (second commit)
The idea here was that CCollision holds information about the map that is immutable and there only exists one copy of it, while the switch state is mutable and would have both a predicted and non-predicted state in the client. While strictly not necessary, having it in the gamecore seems to represent the mutable state better and would be useful to avoid having to put the snapshot switch state back into the gameworld on each new prediction as well as to more easily keep track of the two copies.
A concern here is whether this could in any way …
=> Refactor switch state, add prediction of switch state toggles

src/game/server/gamecontext.cpp
Just figured out that my pr introduced a bug in switches set from map configs (not opening the correct switches). Sorry about that!
Thanks to Faulty for finding it!
=> Fix ConSwitchDoorOpen

src/engine/server/register.cpp, src/engine/server/register.h, src/engine/server/server.cpp, src/mastersrv/src/addr.rs, src/mastersrv/src/main.rs
Also delete it explicitly when `sv_register` is set to register via less
protocols.
On shutdown, wait at most 1 second for the masterserver to respond,
otherwise allow up to 15 seconds.
Fixes https://github.com/ddnet/ddnet/issues/5157.
=> Explicitly delete game server from list on shutdown

src/base/log.cpp
@ChillerDragon Can you test this?
=> Reset colors at end of line (fixes #5324)

CMakeLists.txt, src/base/lock_scope.h, src/base/system.cpp, src/base/tl/threading.h, src/engine/client/serverbrowser_http.cpp, src/engine/client/updater.cpp, src/engine/client/video.cpp, src/engine/server/register.cpp, src/engine/shared/jobs.cpp
Remove unused lock and scope in threading.h
Not sure if this is preferred
We could also try switching to std::mutex and lock_guard
=> Add CLockScope

src/game/client/components/hud.cpp
=> Let the names in the mini score hud overflow to the left

src/game/server/ddracechat.cpp
From my experience and seeing others play, this would be more convenient. Currently teleporting (while being frozen) to retry a part that doesn't have much space or a platform to stand on is a bit hard, often requiring the player to teleport quickly to a position in air multiple times till the character is unfrozen or teleporting to a different part till the character is ready to be put in the original part again. This can also save some time when practicing in general, and will make /tp feel more like /r. This was added only for the /tp command so it shouldn't affect other teleportation methods.
Something to note is that the character teleported into freeze will have the 1 tick unfreeze to jump or so, but it's practice mode so doesn't seem like something to consider.
=> Unfreeze character after teleporting in practice

src/tools/config_common.h, src/tools/config_retrieve.cpp, src/tools/config_store.cpp, src/tools/crapnet.cpp, src/tools/dilate.cpp, src/tools/dummy_map.cpp, src/tools/map_convert_07.cpp, src/tools/map_diff.cpp, src/tools/map_extract.cpp, src/tools/map_optimize.cpp, src/tools/map_replace_image.cpp, src/tools/map_resave.cpp
- Fix/improve variable names.
- Move variable declarations.
- ~~Use `class` instead of `struct` (https://github.com/ddnet/ddnet/issues/5297#issuecomment-1144250491).~~
- Use `nullptr` instead of `0`.
- Pass `nullptr` to `GetItem` when output value is unused.
- Add null-checks for storage.
- Add missing checks for layer type in `map_diff` tool.
=> Refactor tools

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/game/client/gameclient.cpp
Fixes #5307 by updating the prediction to use the new input handling from #5032, and also removed some now no longer used code.
=> Fix prediction input timing

src/base/log.cpp
=> Don't write aAnsi when it's not filled (fixes #5340)

src/game/editor/editor.cpp
Original fix by Ravie... updated to latest code
I do not really know how to trigger the bug, but for me adding and deleting sounds to the map, worked.... Since it is only the updated version from Ravie I think it works
@HiRavie maybe you can test it again
=> Fix deleting envelopes not updating sounds

src/base/log.cpp
Maybe closes #5322. I can't reproduce the crash. Can you try if this fixes it, @Chairn?
Looks like Windows 7 needs this parameter.
Alternative to #5331.
=> Pass output parameter to WriteFile that is required on Windows 7

src/engine/client/client.cpp
Bug reported on discord by Broso56 that dummy is wrongly predicted with deepfly (and when standing still).
Looked at it and found that it was caused by GetInput not returning the dummy input as intended. (Before my last pr a different getter was used, which didn't have that problem)
=> Fix input getter for dummy

src/base/log.cpp, src/base/system.cpp, src/base/system.h
=> Refactoring: Use MultiByteToWideChar instead of str_utf16le_encode

src/base/system.h, src/engine/client/client.cpp, src/engine/server/server.cpp, src/test/test.cpp, src/tools/config_common.h, src/tools/crapnet.cpp, src/tools/dilate.cpp, src/tools/dummy_map.cpp, src/tools/map_convert_07.cpp, src/tools/map_diff.cpp, src/tools/map_extract.cpp, src/tools/map_optimize.cpp, src/tools/map_replace_image.cpp, src/tools/map_resave.cpp, src/tools/packetgen.cpp, src/tools/stun.cpp, src/tools/unicode_confusables.cpp, src/tools/uuid.cpp, src/twping/twping.cpp
Use `CCmdlineFix` RAII wrapper to encapsulate `cmdline_fix` and `cmdline_free` handling. This fixes memory leaks when client/server/tools exit early, as `cmdline_free` was only called on the happy code path.
=> Extract CCmdlineFix to call cmdline_fix and cmdline_free automatically

src/game/editor/editor.h, src/game/editor/layer_tiles.cpp
There is still more duplicate code but it's tricky to extract.
=> Refactoring: Extract CLayerTiles::ShiftImpl, BrushFlipXImpl and BrushFlipYImpl to reduce duplicate code

src/engine/shared/config_variables.h, src/game/ddracechat.h, src/game/server/ddracechat.cpp, src/game/server/gamecontext.h, src/game/server/score.cpp, src/game/server/score.h, src/game/server/scoreworker.cpp, src/test/score.cpp
Even if you made a better finish without time cps before. Can happen now
that we add Time CPs to existing maps:
https://docs.google.com/spreadsheets/d/1yMMBLSbS2cOSYsbIMkDZpMLaV6k930mXj5yVZF0Uuaw/edit#gid=0
As suggested by snail
=> Get best Time Checkpoints back if map has one, add /timecp, remove sv_checkpoint_save

src/engine/client/client.cpp, src/engine/shared/netban.cpp
20 elements per page, we have too many bot bans
=> Paginate bans (partially fixes #3691)

src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings_assets.cpp, src/game/client/render.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/client/ui_ex.cpp, src/game/editor/popups.cpp, src/game/variables.h
- remove config variable `ui_scale`
- remove `CUI::Scale`
- remove `CUI::SetScale`
- remove `CUI::DoLabelScaled`
- remove `CUIRect::Scale`
- use `CUI::DoLabel` instead of `CUI::DoLabelScaled`
- remove usages of `CUI::Scale()` and `CUIRect::Scale()`, or use 1.0f instead
Closes #5062. Closes #5358. Closes #5390.
=> Remove `ui_scale`:

datasrc/seven/datatypes.py, src/engine/client.h, src/engine/client/client.h, src/engine/client/ghost.h, src/engine/client/updater.h, src/engine/graphics.h, src/engine/kernel.h, src/engine/shared/datafile.h, src/engine/shared/demo.h, src/engine/shared/network.h, src/engine/storage.h, src/engine/textrender.h, src/game/client/components/maplayers.h, src/game/client/components/menus.h, src/game/client/prediction/gameworld.h, src/game/client/ui.h, src/game/client/ui_ex.h, src/game/collision.h, src/game/editor/auto_map.cpp, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/io.cpp, src/game/editor/layer_quads.cpp, src/game/editor/layer_sounds.cpp, src/game/editor/layer_tiles.cpp, src/game/editor/popups.cpp, src/game/gamecore.h
There is currently `0`, `0x0`, `NULL` and `nullptr` mixed in the code.
The flag `-Wzero-as-null-pointer-constant` suggests to use `nullptr`. It is in a zillion places so I started with the editor.
=> Use nullptr in generated and editor

src/base/log.cpp, src/base/logger.h, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/server/server.cpp, src/engine/server/server.h
Lets the logger have its own loglevel, which is set by the server and client initially after loading the config and when the `loglevel` config variable changes.
The default logger loglevel is `LEVEL_INFO`, so this fixes the log output not working when the config is not initialized (in tools). Closes #5349. Supersedes #5350.
=> Add `log_set_loglevel` instead of depending on engine config

src/game/editor/editor.cpp
Fixes the editor crash. `CURSOR_NONE` is returned when the cursor was not moved. Closes #5418. Closes #5417.
=> Add missing `CursorType != IInput::CURSOR_NONE` check in editor

src/engine/client/client.cpp, src/engine/editor.h, src/game/editor/editor.cpp, src/game/editor/editor.h
Split `IEditor::UpdateAndEditor` into `OnUpdate` and `OnRender` and call the various input and UI methods in the same order as in the gameclient. This fixes the joystick input being slow in the editor. Closes #5422.
=> Separate editor update and render to fix slow joystick input

src/base/system.cpp, src/base/system.h, src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/client.cpp, src/engine/client/serverbrowser.cpp, src/engine/client/sound.cpp, src/engine/client/text.cpp, src/engine/client/updater.cpp, src/engine/server/server.cpp, src/engine/shared/storage.cpp, src/engine/storage.h, src/game/editor/editor.cpp, src/game/editor/io.cpp
- `io_read_all` reads all bytes from a file handle into a new buffer. It should only need one allocation per file in cases where the actual file size matches the expected file size. Otherwise it falls back to doubling the buffer size if the actual file size is larger than expected to avoid TOCTOU problems.
- `io_read_all_str` reads all bytes from a file handle into a new buffer and also ensures that the buffer is null-terminated and contains no other null-characters.
- `mem_has_null` is a utility used by `io_read_all_str` to ensure that no null-characters exist in the bytes read from the file.
- `IStorage::ReadFile` and `ReadFileStr` are storage wrappers around `io_read_all` and `io_read_all_str`
The system functions are the same as on upstream …
=> Add `io_read_all` and `io_read_all_str` to system, add `IStorage::ReadFile` and `ReadFileStr`

src/game/client/components/scoreboard.cpp, src/game/client/components/scoreboard.h
<s>do it using getgameinfo from gameclient introducting a new flag for ddrace</s>
use the same conditions as in the goalshudrender function, so don't render when empty
=> no-goalshud

src/engine/client/backend/vulkan/backend_vulkan.cpp
Oops, I tried to be smart with `reserve` instead of `resize` but of course that wouldn't set the actual size of the vector after I copy in the data. 
Closes #5442.
=> Fix shader code vector size not being updated after copy

src/game/editor/editor.cpp
Accumulate the mouse deltas and reset them at the end of the frame to fix editor panning being slowed down and value scrollers (layer width etc.) not working anymore.
Closes #5441.
And minor cleanup.
=> Fix editor value scrollers not working and panning being slow

src/engine/client/client.cpp, src/engine/client/input.cpp, src/engine/client/input.h, src/engine/input.h
Instead of closing the joysticks manually, use `SDL_QuitSubSystem(SDL_INIT_JOYSTICK)` to quit the entire subsystem, which will also close all joysticks correctly.
The engine input destructor is replaced with a `Shutdown` method so we can control when it is called, i.e. before calling `SDL_Quit`, which forcefully quits all subsystems.
`CJoystick::Close` is removed as we don't need to close joysticks manually anymore.
Closes #5452.
=> Fix segfault in `SDL_JoystickClose` on client quit

src/engine/client/discord.cpp
=> Move libpng libraries to expected name for macOS

src/game/client/components/console.cpp
Untested, but my hunch is that by not cutting off the last part the text
file will be correctly recognized as valid utf8
=> Try to fix dump_local_console (fixes #5488)

src/engine/shared/demo.cpp, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/render.cpp, src/game/client/render.h, src/game/editor/editor.cpp
I first tried adapting and using `CMenus::DoButton_Icon` like `DoIcon` on upstream to reduce duplicate code in the menus. Later I moved/renamed this method to `CRenderTools::RenderIcon`, to also use it in the editor.
Changes to demo list:
- Show the icons as part of the name column
- Improve spacing/centering of icons in columns
- Grey out icon if demo is not loaded or not valid
- Clamp the number of demo markers to valid range (I have an old version 3 demo that incorrectly shows more than a million markers otherwise, which would not fit the char buffer used for rendering the number)
The visual changes are mostly consistent with upstream. Upstream also renders demo icons in green when the demo has markers, but I don't see a good motivation for that especially with a separate markers …
=> Improve rendering of demo list icons, remove duplicate code

src/base/log.cpp, src/base/system.cpp, src/engine/client/input.cpp, src/engine/shared/websockets.cpp, src/game/server/player.cpp, src/game/server/save.cpp
We could even add implicit fallthrough warning, but it is triggered in external json.c
=> Use [[fallthrough]] attribute rather than comment

src/base/hash.h, src/base/hash_ctxt.h, src/engine/client/video.h, src/engine/shared/websockets.cpp, src/engine/sqlite.h, src/game/editor/editor.h
=> Remove useless typedef in c++

src/game/client/prediction/entity.cpp, src/game/client/prediction/entity.h, src/game/client/prediction/gameworld.cpp
Entities have a pointer to their parent entity. If the parent entity is freed first, then freeing the child will cause access to the already freed parent (at `pEnt->m_pParent->m_DestroyTick = GameTick();`).
This is fixed by adding a child pointer and clearing the child and parent pointers when either child or parent is freed.
I can consistently get the crash in `CGameWorld::RemoveEntity` with the integration test at fbfd938f326390048368bc169442c5e5ba2e42e5 (10/10 runs crashed). With these changes I get no crashes anymore (0/10 runs crashed).
Closes #5478. Closes #4317. Closes #4328. Closes #4390. Not sure about #3179.
=> Fix heap-use-after-free in `CGameWorld::RemoveEntity`

src/game/editor/editor.h, src/game/editor/layer_tiles.cpp
To prevent the color of all layers from being reset to zero when changing just the size.
Closes #3734.
=> Only apply size and color if changed, when editing multiple layers

scripts/integration_test.sh
Logging to file and to stdout might order differently
due to multiple threads
Should fix issues like these
```
[-] Error: logfile 'server.log' differs from stdout
--- server.log	2022-06-28 13:46:38.703149594 +0000
+++ stdout_server.txt	2022-06-28 13:46:38.703149594 +0000
@@ -150,8 +150,8 @@
[2022-06-28 13:46:30][sql]: SQLite statement: INSERT OR IGNORE INTO record_race(	Map, Name, Timestamp, Time, Server, 	cp1, cp2, cp3, cp4, cp5, cp6, cp7, cp8, cp9, cp10, cp11, cp12, cp13, 	cp14, cp15, cp16, cp17, cp18, cp19, cp20, cp21, cp22, cp23, cp24, cp25, 	GameID, DDNet7) VALUES ('coverage', 'client1', DATETIME('2022-06-28 13:46:30', 'utc'), 1.18, 'UNK', 	0.44, 0.52, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 	0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 	0.00, 0.00, 0.00, 0.00, 0.00, 0.00, …
```
=> Sort CI logs before diff to fix race condition

src/game/editor/editor.cpp
Port two fixes for the editor envelope preview from upstream:
1. Make it possible to edit the last envelope point.
2. Fix envelope points being moved incorrectly when grabbed with the mouse. Closes #1984.
=> Editor envelope preview: fix last point not being editable, fix movement of envelope points in Info mode (Ctrl+I)

datasrc/compile.py, datasrc/datatypes.py, datasrc/network.py, src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/server/server.cpp, src/engine/shared/packer.cpp, src/engine/shared/packer.h, src/engine/shared/snapshot.cpp, src/engine/shared/snapshot.h, src/game/client/components/freezebars.cpp, src/game/client/components/hud.cpp, src/game/client/components/players.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/client/prediction/entities/character.cpp, src/game/client/prediction/entities/character.h, src/game/client/prediction/gameworld.cpp, src/game/client/prediction/gameworld.h, src/game/gamecore.cpp, src/game/gamecore.h, src/game/server/entities/character.cpp, src/game/server/save.cpp, src/game/server/save.h, src/game/variables.h
- I also added the default value mechanic for Net Objects that have set `validate_size=False`
- I removed the ramp value from the snap, because currently all maps use the default tuning parameters for it
- I renamed `m_FreezeTick` to `m_FreezeStart` 
- Added Extended Net Objects to the debug HUD (Also added a Headline):
(out of range) is in the screenshot the old DDNetCharacterDisplayInfo
fixes #5455
=> Move ddnet character display info in ddnet character

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/game/client/components/maplayers.cpp, src/game/client/components/maplayers.h, src/game/client/components/menu_background.h, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings_assets.cpp, src/game/client/components/race_demo.cpp, src/game/client/components/skins.cpp, src/game/client/components/sounds.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h
Same as #4941 
It doesn't directly fix the issue described in #5478, it does however not trigger it anymore. it's still a bug in our code unrelated  to this. This just triggered the UB from the issue as  @ardadem confirmed, SDL received a SDL_QUIT (`[2022-06-23 20:26:31][test]: sdl closed my client, but why xd`)
Now we have a confirmed case that making the window unresponsive can create weird behavior. Similar to the other pr switch to a loading screen after 500ms (this time without menu background map tho, since the menu background map calls the same code).
We really need some fancy loading screen for such situations, even tho they are rare xD
=> Switch to loading screen, when map creation takes too long

src/game/client/components/menus_settings.cpp
just found a variable lasterOutlineColor instead of laserOutlineColor + double comment
=> fix typo and comment

src/engine/server.h, src/engine/server/server.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/player.cpp
=> Fix player input player flags translation with sixup, fix player flags output of `status` command

src/game/client/gameclient.cpp
I tested it on KOG and some other servers. Seems fine
I personally would have shown the new HUD also on old server. But I guess it is fine to show the old HUD on old servers.
If we decide for this solution... we can merge it also into 16.2 so that a HUD is shown on KoG servers
=> Fix HUD on KOG and do no longer show new DDRace HUD on old DDRace Servers

src/engine/client/client.cpp
=> Remove unused `#include <windows.h>` in engine client

src/game/client/components/skins.cpp, src/game/client/components/skins.h
=> Fix skindownload by only allowing move assignments

src/engine/client/client.cpp
=> Fix out of bounds read in checksum stuff

src/game/server/player.cpp, src/game/server/player.h
No matter if you use /timecp or rename
=> Only announce birthday once (fixes #5576)

src/engine/server/databases/mysql.cpp
=> Only MySQL >= 8.0.1 removed my_bool (fixes #5573)

src/base/color.h, src/base/vmath.h, src/engine/client/backend/opengl/backend_opengl.cpp, src/engine/client/backend/opengl/backend_opengl.h, src/engine/client/backend/opengl/backend_opengl3.cpp, src/engine/client/backend/opengl/backend_opengl3.h, src/engine/client/backend/opengl/opengl_sl_program.h, src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/client/text.cpp, src/engine/graphics.h, src/engine/textrender.h, src/game/client/components/chat.cpp, src/game/client/components/hud.cpp, src/game/client/components/killmessages.cpp, src/game/client/components/maplayers.cpp, src/game/client/components/maplayers.h, src/game/client/components/mapsounds.cpp, src/game/client/components/menus.h, src/game/client/components/nameplates.cpp, src/game/client/components/particles.cpp, src/game/client/render.h, src/game/client/render_map.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/layer_sounds.cpp, src/game/mapitems.h
I mostly touched the code in the graphic part for array of 2 floats into vec2.
For color, i replaced array of 4 floats with ColorRGBA where it made sense.
I had to change the logic order in `src/engine/client/graphics_threaded.cpp:1113` due to operator= from vec2 to vec3. I didn't see any visual change.
=> Replaced float array with appropriate struct (vec or color)

.gitlab-ci.yml, .gitlab/build.yml
Add a very simple CI for gitlab. This is for ddnet forks that are hosted on gitlab. They can quickly get started with a simple ddnet pipeline that checks the build. And can be extend by adding files in `.gitlab/*.yml` without getting git conflicts with this upstream repository.
=> Add basic extensible gitlab CI

src/game/client/gameclient.cpp, src/game/client/prediction/entities/character.cpp, src/game/gamecore.cpp, src/game/gamecore.h
Reverts this: https://github.com/ddnet/ddnet/commit/320e9e030f068ffa02f51d693c359ad1cd3266a9
I fist did that change to fix the weapon display in the new HUD. But it turned out that did not fix the Weapon display anyway (only partially on remote server but not local). And since we now have a better fix for the weapon display (by sending the correct weapon) we do no longer need to overwrite the predicted data.
rename ReadCharacterCore back to Read (Since we do not need ReadCharacter that I introduced)
fixes #5309 
probably fixes #5559 (I can still not reproduce)
=> Do not overwrite predicteded CharacterCore with Snap Data

src/game/client/components/hud.cpp
The bug was, if you spectate other players, the jump display and weapon display was broken.
Use for weapon and jump display now render information instead of the predicted data, so that these Displays are also correct if you spectate other players.
This is necessary since with https://github.com/ddnet/ddnet/pull/5592 this information is no longer present in the predicted character (if the character is not predicted)
=> Fix the HUD bug I intoduced with  #5592

src/engine/client/video.cpp
```
/home/deen/isos/ddnet/ddnet-source/src/engine/client/video.cpp:829:9: error: ‘c’ was not declared in this s
cope
829 |         c->thread_count = 1;
|         ^
```
=> Fix compilation in video.cpp

src/game/client/components/console.cpp, src/game/client/components/hud.cpp, src/game/client/components/menus.cpp, src/game/client/components/motd.cpp, src/game/client/components/scoreboard.cpp, src/game/client/components/spectator.cpp, src/game/client/components/statboard.cpp, src/game/client/render.cpp, src/game/client/render.h, src/game/client/ui.h, src/game/editor/layer_sounds.cpp
Mostly removing duplicate code and making the rectangle drawing methods easier to use.
Eventually I want to move the basic rectangle and circle drawing methods to `IGraphics`, as they are independent from the game code.
=> Refactor CRenderTools rectangle drawing

src/engine/client/client.cpp
The nonsensical index of `m_aNetClients` was introduced during my
rebasing of #5205.
Fixes #5618.
=> Fix UDP connectivity check

src/engine/shared/config_variables.h
To reenable quads for everyone who accidentally disabled it or has the
bind to accidentally disable them
=> Rename cl_show_quads -> cl_showquads

src/engine/client/client.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/gfx/image_loader.cpp, src/engine/gfx/image_loader.h, src/engine/graphics.h, src/tools/dilate.cpp, src/tools/map_convert_07.cpp, src/tools/map_replace_image.cpp
This allows a larger range of PNGs to be loaded while still maintaining
backward compatibility with older clients by annoying the user.
This warning can be enabled by the `warn-pnglite-incompatible-images`
key in the https://info2.ddnet.tw/info JSON, if the key is not there or
the JSON hasn't been obtained yet, the warning is disabled. Since the
JSON is cached across restarts, it'll be effective for initially loaded
images from the second start.
=> Warn about pnglite-incompatible PNGs on load

datasrc/datatypes.py, datasrc/seven/datatypes.py, src/engine/server.h, src/engine/server/server.cpp
Fix clang warning: Address of stack memory associated with local variable 'aBuf' is still referred to by the stack variable 'tmp' upon returning to the caller.  This will be a dangling reference [clang-analyzer-core.StackAddressEscape]
Mark the input parameters as const pointers and mark the protocol message `Pack` methods as const.
And remove a null check that only serves to hide programmer errors.
=> Move message copy inside `SendPackMsgTranslate`

src/engine/client/client.cpp, src/engine/shared/demo.h, src/game/client/components/items.cpp, src/game/client/components/menus.cpp, src/game/client/prediction/entity.h
The minor refactoring:
- https://github.com/ddnet/ddnet/commit/1f264a042ded7585c26dabac04e4823ee5b51b52 After DDNet tuning [re-introduced](8ef1f35f89d538372a346f4fbc9bedd67ff73195) as the default tuning for all maps and gametypes, I had to find another solution to use vanilla tuning at least for the mod I work on.
The mod maps are started with a prefix so I check the map name on demo playback to disable DDNet tuning for the mod demos.
I found that the map info was not set on demo loaded but it was easy to fix.
I hope you'll agree that this is the correct behavior and this might be useful for some other client features too (maybe we'll need this to show the map name during playback).
- prediction/entity API changes — I needed those to reuse server-side code for client-side (mod specific) …
=> Minor refactoring and a fix for a typo

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings_assets.cpp, src/game/client/components/menus_start.cpp, src/game/client/ui.h
Introduce ``CButtonContainer`` which is used for fading text in teeworlds. There is no fading text in ddnet yet.
This change allows introducing such fading buttons but the main motivation for this change is easier copy & pasting code from ddnet to teeworlds code base and vice versa.
=> Adapt upstreams CButtonContainer

src/game/server/teams.cpp
=> Fix shift with negative exponent in `TeamMask`

src/engine/client/client.cpp, src/engine/shared/demo.cpp, src/engine/shared/snapshot.cpp, src/engine/shared/snapshot.h
Add `CSnapshot::IsValid` to check if a snapshot unpacked from a snapshot delta or demo is valid:
- ensure number of items and data size are not negative
- ensure that the actual size of the snapshot matches the size derived from its member variables
- ensure item offsets are within the valid range
- ensure item sizes are not negative
Add `CSnapshot::TotalSize` and `CSnapshot::OffsetSize` utility functions.
Minor improvements to related error messages.
Fixes buffer overflow (see #5646):
```
==47744==ERROR: AddressSanitizer: global-buffer-overflow on address 0x558618e3767f at pc 0x558614b9bdfb bp 0x7ffe58a32cd0 sp 0x7ffe58a32cc0
READ of size 4 at 0x558618e3767f thread T0
0x558614b9bdfa in CSnapshotItem::Type() const src/engine/shared/snapshot.h:16
0x558615c3c911 in …
```
=> Validate snapshot size and member variables and demo snapshots

src/engine/client/client.cpp
If a duplicate snapshot is received (for the same tick), we add both to the SnapshotStorage and end up with the same snapshot as both Cur and Prev. This results in GameInfraTick returning "inf" and results in "NaN" downstream in a few places, getting the CollLine logic stuck.
Some debug info (tcpdump, gdb, perf): https://gist.github.com/Fireball-Teeworlds/ad0016d2551a2e4d4cb5691023493856
Apparently this doesn't really happen in the wild, unless you have a buggy network stack. In which case it happens frequently enough to pinpoint the issue :D
(fixes #5657)
=> Fix game freezing up on duplicate snapshot

cmake/FindPNG.cmake
```
dyld[41859]: Library not loaded: @rpath/libpng16.16.dylib
Referenced from: /Users/deen/Library/Application Support/Steam/steamapps/common/DDraceNetwork/ddnet/DDNet
Reason: tried: '/Users/deen/Library/Application Support/Steam/steamapps/common/DDraceNetwork/ddnet/../Frameworks/libpng16.16.dylib' (no such file), '/Users/deen/Library/Application Support/Steam/steamapps/common/DDraceNetwork/ddnet/../Frameworks/libpng16.16.dylib' (no such file), '/usr/local/lib/libpng16.16.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/libpng16.16.dylib' (no such file)
```
Fixes the nightly build on macOS so it starts again.
=> Bundle libpng16.16.dylib for macOS

src/game/editor/editor.cpp
By moving the calls to `KeyPress` from `CEditor::OnUpdate` to `OnRender`.
Closes #5669.
=> Fix tab and F10 keys working inconsistently in editor

src/engine/client/video.cpp
=> Fix deprecation warning in ffmpeg 5.1 (fixes #5681)

src/game/editor/editor.cpp
=> Reset selected quads when switching layers (fixes #5673)

src/engine/server.h, src/engine/server/server.cpp, src/engine/server/server.h, src/game/server/entities/character.cpp, src/game/server/entities/door.cpp, src/game/server/entities/dragger.cpp, src/game/server/entities/gun.cpp, src/game/server/entities/light.cpp, src/game/server/entities/pickup.cpp, src/game/server/entities/projectile.cpp, src/game/server/gamecontext.cpp, src/game/server/player.cpp
Some refactoring to reduce duplicate code and to remove includes.
=> Refactor `GetClientVersion`, remove many `version.h` includes, fix potential use of undefined value

src/game/editor/layer_tiles.cpp
1. Open any map, including an empty one.
2. Select a brush, e.g. size 2x2.
3. Shift click to repeat the brush over a larger area, e.g. 10x10.
4. This causes a buffer-overflow / crash with ASAN:
```
=================================================================
==4826==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6060000f5040 at pc 0x55db7d0aa743 bp 0x7fffe4e191f0 sp 0x7fffe4e191e0
READ of size 4 at 0x6060000f5040 thread T0
0 0x55db7d0aa742 in CLayerTiles::GetTile(int, int) src/game/editor/layer_tiles.cpp:50
1 0x55db7d0d23e1 in CLayerTiles::FillSelection(bool, CLayer*, CUIRect) src/game/editor/layer_tiles.cpp:437
2 0x55db7cf196e9 in CEditor::DoMapEditor(CUIRect) src/game/editor/editor.cpp:2641
3 0x55db7cfa7755 in CEditor::Render() src/game/editor/editor.cpp:5747
4 …
```
=> Fix buffer-overflow in editor on shift-clicking brush

src/engine/shared/snapshot.cpp
The previous hash function was heavily biased towards the hash buckets 64-79, making those buckets overflow faster, which results in snapshot CRC errors and lags.
Using the djb2 hash yields an almost even distribution over the entire range of values.
Source for djb2: http://www.cse.yorku.ca/~oz/hash.html
(we incidentally use the same implementation for `str_quickhash`)
Sample which compares the usage of hash buckets in the test map from #5454 with the old and new hash function: [SnapshotHash.csv](https://github.com/ddnet/ddnet/files/9285148/SnapshotHash.csv) (this table also differentiates between the source and target of the snapshot delta)
Closes #4379.
=> Use djb2 for snapshot item hashlist

src/engine/console.h, src/engine/shared/console.cpp, src/engine/shared/console.h, src/game/client/components/binds.cpp, src/game/client/components/binds.h, src/game/client/components/console.cpp, src/game/client/components/console.h, src/game/client/components/debughud.cpp, src/game/client/gameclient.cpp, src/game/gamecore.cpp, src/game/gamecore.h, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
- Rename commands that list things according to upstream so they are consistent and improve command descriptions:
- `dump_binds` -> `binds`
- `tune_dump` -> `tunes`
- `bans` (already named fittingly)
- `dump_(local|remote)_console` (named correctly, `dump` should be used when writing to a file)
- Add success/error messages to `dump_(local|remote)_console` and improve description.
- Print error when using incorrect tuning names like `tune xyz 123`.
- Extend `tune_reset` so a single tuning value can be reset to default. For example `tune_reset player_collision` will reset just the `player_collision` tuning, whereas `tune_reset` will reset all to defaults like before.
- Get the actual tuning value after setting it, as the value that was applied may differ due to overflow or rounding errors. …
=> Show console completion options for tunings, extend and rename commands according to upstream

src/game/client/components/console.cpp, src/game/client/components/console.h, src/game/client/ui.cpp, src/game/client/ui.h
More smoothly scroll selected console completion option into view.
See videos at https://github.com/teeworlds/teeworlds/pull/3054.
The smooth scrolling logic is extracted in `CUI::DoSmoothScrollLogic` so it can eventually be reused for smooth input scrolling (see https://github.com/teeworlds/teeworlds/pull/3150).
=> Smooth console completion scrolling

src/game/client/components/countryflags.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings_assets.cpp, src/game/client/components/menus_start.cpp
Also print the exact file/link that could not be opened.
=> Improve "couldn't open..." error messages by listing target

src/base/system.cpp
This functionality was lost in 082e26d5b
In my case I have a lot of symlinks in the maps folder (Downloads, ddnet-maps, map_archive)
On windows, I have neither tested this behavior before nor after this patch. Could someone maybe try it out there?
=> List symlinks in list_dir

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/layer_quads.cpp, src/game/editor/layer_sounds.cpp, src/game/editor/layer_tiles.cpp, src/game/editor/popups.cpp
Suggested by Pulsar a few years ago, I finally had the motivation to do it. We can now duplicate any non-special layer (tiles, quads and sounds) thanks to a button just above the delete button.
For each duplicated layers, all the necessary properties are duplicated, for example name, color, flags, etc.
For a tile layer, all the placed tiles are copied. Same goes for a sound layer, all sources are copied. And for the quads layer, all the quads are duplicated.
=> Editor: added the possibility to duplicate layers

src/base/system.cpp
On Windows, the check was incorrectly using logical or instead of bitwise or. Checking for the flag `FILE_ATTRIBUTE_REPARSE_POINT` is not necessary, as the `FILE_ATTRIBUTE_DIRECTORY` will correctly be set when the target of a symbolic link is a directory. This otherwise causes symbolic links to files to be incorrectly handled as directories.
On Linux, the minor performance optimization of using `entry->d_type` is reverted and `fs_is_dir` is used instead. This internally uses `stat`, which correctly returns the attributes for the symbolic link targets.
Closes #5752. Closes #5753.
=> Fix symlink handling of `fs_listdir`

src/game/client/components/menus.h, src/game/client/components/menus_settings.cpp, src/game/client/components/skins.cpp, src/game/client/skin.h
motivation: downloaded skins aren't resettet, e.g. if they failed before. config change -> resets everything
=> Auto refresh skins when changing related settings

CMakeLists.txt, src/base/system.cpp, src/base/system.h
This fixes links not opening for relative paths, as links like `file://temp/skins` cannot be resolved by the shell.
Closes #5746.
=> Make file link absolute, add `fs_is_relative_path`

src/base/system.cpp, src/base/system.h, src/engine/client/client.cpp
I can't reproduce the crash/hang from #5744, so I don't know if this fixes the issue.
=> Add `CWindowsComLifecycle` RAII wrapper for Windows COM library

src/base/system.cpp
```
ddnet/src/base/system.cpp: In function 'int byteval(const char*, unsigned char*)':
ddnet/src/base/system.cpp:3044:32: warning: declaration of 'byte' shadows a global declaration [-Wshadow]
3044 | static int byteval(const char *byte, unsigned char *dst)
|                    ~~~~~~~~~~~~^~~~
In file included from msys64/mingw64/include/objbase.h:8,
from ddnet/src/base/system.cpp:68:
msys64/mingw64/include/rpcndr.h:63:25: note: shadowed declaration is here
63 |   typedef unsigned char byte;
|                         ^~~~
ddnet/src/base/system.cpp: In function 'unsigned char str_byte_next(const char**)':
ddnet/src/base/system.cpp:3557:23: warning: declaration of 'byte' shadows a global declaration [-Wshadow]
3557 |         unsigned char byte = **ptr;
|                       ^~~~ …
```
=> Fix variable shadow warnings with MinGW

.github/workflows/style.yml
```
find src -name '*.h' | while read i; do grep -r -q $(basename $i) || (echo "Header file $i is unused" && exit 1); done                                                                                                                                                                                                        
^--^ SC2162 (info): read without -r will mangle backslashes.                                                                                                                                                                                                                                     
^------------^ SC2046 (warning): Quote this to prevent word splitting. …
```
=> Shellcheck Unused headers CI

src/engine/shared/config_variables.h, src/game/client/components/hud.cpp, src/game/client/components/maplayers.cpp, src/game/client/components/nameplates.cpp, src/game/client/render.cpp, src/game/client/render.h, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/io.cpp, src/game/editor/popups.cpp, src/game/layers.cpp, src/game/layers.h, src/game/mapitems.h, src/game/mapitems_ex.cpp, src/game/mapitems_ex.h, src/game/mapitems_ex_types.h
Currently we have parallax X and Y parameters that control how far away a layer feels. Currently it's only taken into account for camera moving sideways.
This pull request makes zoom behave as if the camera was moving closer or further away, taking into account the distance to the layer.
In order to provide flexibility, this behaviour is using a separate parallax value, similar to how we have separate values for X and Y. Para Zoom will default to the minimum of parallax X, Y, clamped to be between 0 and 100. This seems to look well on most maps.
This pull request also introduces two new features to the Editor:
* Controls for configuring per-group Para Zoom value. If Custom Zoom is set to No, Para Zoom will automatically keep following to the default value described above, so that people …
=> Add option for parallax-aware zoom

CMakeLists.txt, src/base/system.cpp, src/base/system.h, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/gameclient.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/client/ui_scrollregion.cpp, src/game/client/ui_scrollregion.h, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
This brings smooth scrolling from upstream to the following UI elements:
- ingame server info MOTD (supercedes #5704)
- Before:  ![motd old](https://user-images.githubusercontent.com/23437060/185678277-801982e2-f403-441f-af67-0b62ad8841c7.png)
- After:  ![motd new](https://user-images.githubusercontent.com/23437060/185678284-7e685a36-6a35-4cd2-8f9c-8f2b6e8acc61.png)
- controls settings
- Before: ![controls old](https://user-images.githubusercontent.com/23437060/185678351-bac742f6-77dd-4f6a-972d-c1fcff8bacf3.png)
- After:  ![controls new](https://user-images.githubusercontent.com/23437060/185678358-b59f538f-aa81-41ae-938f-bb8349ebf730.png)
- editor images popup
- Before:  ![layers-and-image-popup old](https://user-images.githubusercontent.com/23437060/185678396-c2bb1db9-fb83-4663-b1f5-4d6ce …
=> Port `CScrollRegion` from upstream and refactor MOTD, controls settings, editor images popup, editor layers/images/sounds lists

.gitignore, CMakeLists.txt, src/tools/map_create_pixelart.cpp
works as shown in screenshot below:
Usage: map_create_pixelart <image.png> <img_pixelsize> <input_map> <layergroup_id> <layer_id> <pos_x> <pos_y> <quad_pixelsize> <output_map> [optimize=0|1] [centralize=0|1]"
Notes: 
- use destination layer tiles as a reference for positions and pixels for sizes.
- set img_pixelsize to 0 to consider the largest possible size.
- set quad_pixelsize to 0 to consider the same value of img_pixelsize.
- if image.png has not a perfect pixelart grid, result might be unexpected (manually fix img_pixelsize to get it better or just fix the image, or enable optimize).
Options: 
- optimize tries to reduce the total number of quads, default: 1. (mappers say sometimes this is not useful, as they might want to add different envs/to per pixel)
- centralize places all …
=> Added map_create_pixelart tool

src/engine/server/server.cpp, src/engine/shared/websockets.cpp, src/tools/map_create_pixelart.cpp
```
/home/deen/isos/ddnet/ddnet-source/src/tools/map_create_pixelart.cpp: In function ‘int InsertPixelArtQuads(CQuad*, int&, const CImageInfo&, const int*, const int*, const bool*)’:
/home/deen/isos/ddnet/ddnet-source/src/tools/map_create_pixelart.cpp:110:9: error: ‘memset’ was not declared in this scope
110 |         memset(aVisitedPixels, 0, sizeof(bool) * Img.m_Height * Img.m_Width);
|         ^~~~~~
/home/deen/isos/ddnet/ddnet-source/src/tools/map_create_pixelart.cpp:8:1: note: ‘memset’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
7 | #include <game/mapitems.h>
+++ |+#include <cstring>
8 |
```
=> Fix memset compilation

src/engine/shared/demo.cpp, src/engine/shared/demo.h, src/game/client/components/menus_demo.cpp
Mostly from upstream https://github.com/teeworlds/teeworlds/pull/2904, with some more fixes and refactorings.
=> Add period/comma hotkeys to skip one tick forward/backward, various other improvements to demo skipping

src/game/client/components/spectator.cpp, src/game/client/gameclient.cpp
=> Deactivate "Follow" spectator mode in global server demos, fix free-view button state

src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp
Demo seeking was broken when the menu is not active due to a regression from #5777, as the ddnet demo is structured differently than upstream (early return when the menu is not active).
The automatic demo rewinding when a demo reaches its end was already broken before, due to this different structure.
=> Fix demo seeking and automatic demo rewind not working while the menu is not active

src/engine/demo.h, src/engine/shared/demo.cpp, src/engine/shared/demo.h, src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp, src/game/client/components/spectator.cpp
By updating and rendering the current tick again when changing the spectator mode while the demo playback is paused. Closes #1843.
Refactoring: Extract `IDemoPlayer::ETickOffset`, `IDemoPlayer::SeekTick` and `CMenus::DemoSeekTick`.
=> Allow spectator mode to be changed while demo is paused

src/game/client/components/chat.cpp, src/game/client/components/chat.h, src/game/client/components/killmessages.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/sounds.cpp, src/game/client/components/statboard.cpp, src/game/client/gameclient.cpp
=> Suppress more events while skipping in demos, reset specifics components before long skips in demo

src/engine/client/client.cpp, src/engine/console.h, src/engine/shared/console.cpp, src/engine/shared/console.h
=> Allow demo/map command line arguments to be relative paths, allow using `play` in command line

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_start.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/client/ui_scrollregion.cpp, src/game/editor/editor.cpp
Move hotkey/input handling from `CMenus` to `CUI`.
Using the `ConsumeHotkey` method ensures that each hotkey is only handled once.
By also handling the mouse scroll wheel as hotkeys, this fixes the scroll keys activating scroll regions while the controls binder is active. Closes #5790.
=> Port `CUI::ConsumeHotkey` from upstream

src/engine/client/keynames.h, src/engine/server/server.cpp, src/game/server/gamecontext.cpp, src/tools/map_create_pixelart.cpp
`memset` only worked with `CServer::CClient::STATE_EMPTY` by chance
because it is defined as 0.
=> Remove all references to memset

src/engine/shared/network_conn.cpp
Previously, close messages were entirely ignored during the connection
process, this meant that ban messages weren't shown to players. Instead,
they'd see the standard "no answer from server yet" message.
Fixes #5792.
=> Fix close messages not being shown when connecting

src/game/editor/editor.cpp, src/game/editor/popups.cpp
- Refactor editor automapper config list using `CScrollRegion`. Also fix some other minor issues with this list.
- Fix the currently selected item not being highlighted after opening the dialog.
- Remove static limit of 255 automapper rules, after which the editor previously caused out-of-bounds accesses, by using the address of the automapper config name as button ID.
- Before:  ![automapper old](https://user-images.githubusercontent.com/23437060/188277300-bd634c13-fb66-4348-abf4-9481e8fcaa3a.png)
- After: ![automapper new](https://user-images.githubusercontent.com/23437060/188277303-0cb94442-f35d-4c1e-bd81-7f56052cede6.png)
- Refactor editor server settings list using `CScrollRegion`.
- Before:  ![server_settings old](https://user-images.githubusercontent.com/23437060/188277264-8a0d16b5- …
=> Refactor editor server settings and automapper config lists using `CScrollRegion`

src/base/system.cpp, src/base/system.h, src/engine/shared/serverinfo.cpp, src/test/str.cpp
This simply treats server info as invalid if it contains control
characters in any string.
Fixes #5826.
=> Ignore server info with control characters

src/game/editor/editor.h, src/game/editor/layer_quads.cpp, src/game/editor/popups.cpp
Main purpose is to control quads z index, but i like how this can be used to reveal how many quads a layer has just by placing a new one.
Furthermore, it provides a way to reference quads, that's needed to make custom cli tools work on user selected quads.
=> Editor: Added "Order" button in quads popup

scripts/integration_test.sh, src/base/log.cpp
Remove square brackets to reduce the amount of space used.
Add log level indicator. The position between timestamp and system was
chosen because it is at a fixed position (unlike after the system) but
the log still remains naively sortable (which wouldn't happen if we were
to place it in front of the timestamp.
Before:
```
[2022-04-29 15:25:37][engine]: running on unix-linux-amd64
[2022-04-29 15:25:37][engine]: arch is little endian
[2022-04-29 15:25:37][storage]: added path '$USERDIR' ('/path/to/home/.teeworlds')
[2022-04-29 15:25:37][storage]: added path '$DATADIR' ('data')
[2022-04-29 15:25:37][storage]: added path '$CURRENTDIR' ('/path/to/ddnet')
[2022-04-29 15:25:37][host_lookup]: host='localhost' port=0 1
[2022-04-29 15:25:37][host_lookup]: host='localhost' port=0 2
[2022-04-29 …
```
=> Change log format

src/game/editor/editor.cpp
Automatically reloads the image from mapres folder based on its current name, that's just a quicker "replace" which is convenient while experimenting on image contents, some mappers asked for this.
note: image lookup is currently limited to the mapres root folder, no directory recursion has been implemented, this is an improvement that might be added in the future (even though in my understanding, organizing mapres into subfolders is not a very common practice, not even the "search" feature considers that).
=> Editor: Added reload button for image and sound popups

src/engine/client/client.cpp, src/engine/client/client.h, src/engine/server/server.cpp, src/engine/shared/config_variables.h, src/engine/shared/http.cpp, src/engine/shared/http.h
This allows every game server to provide its own HTTPS server for map
downloads. Since the ingame protocol for downloading map data is very
inefficient, this is desirable. Previously, only servers hosted by DDNet
could benefit from this.
Security concerns:
- Attackers can find out whether a given HTTPS GET request matches a
known answer.
This isn't deemed to be problematic as no cookies for authentication
are sent and only the whole response can be matched.
- Sending requests to honeypot URLs to get people in legal trouble.
This seems to be already possible with HTML image embeds, so it can't
be that bad™.
- Downloading huge files, filling up a player's disk. The players might
cancel when seeing huge files.
There's a generous limit of 1 GiB per map file.
- Downloading huge files …
=> Add HTTPS map download URL field for game servers

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
This feature was also suggested by Pulsar. It adds a button to go to a specified coordinate point by inputting x and y coordinates through a popup window:
The two number inputs are constrained between 0 and the width/height of the map (minus 1). When clicking "Go", it focuses the camera at the center of the tile at these coordinates.
=> Editor: added a goto button

src/engine/shared/http.cpp
This should help debugging the empty error messages we sometimes get on servers.
=> Also print the `CURLcode` on failed requests

CMakeLists.txt, src/base/system.cpp, src/test/net.cpp
Previously, the socket addresses were truncated as the `msg_namelen` field is both input **and** output: After receiving an IPv4 packet, the socket address field would be too short for an IPv6 address.
=> Fix receiving IPv6 packets after IPv4 ones on Linux

src/engine/server/register.cpp, src/engine/shared/http.cpp, src/engine/shared/http.h
This works around, i.e. fixes #5858 for curl versions < 7.77.0, as long
as the servers are only registered via IPv4 **OR** IPv6.
The bug that's being worked around is this:
https://github.com/curl/curl/commit/84d2839740ca78041ac7419d9aaeac55c1e1c729.
The bug makes curl reuse IPv6 connections when it is being requested to
connect via IPv4, making the registering fail. This commit works around
that by letting the server only register after having completely read
the config, so any `sv_register ipv4` should already be in effect.
Also stop server if started with old curl and incompatible `sv_register`.
=> Only start registering once the server is fully started

src/engine/client/client.cpp
=> Fix map file argument not opening editor with absolute paths

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_ingame.cpp
This might be not complete, but this adds the functionality to refresh the server browser list after disconnecting from a server, or after aborting joining a server.
This fixes issue #5863.
=> refresh serverbrowser when disconnecting / abort

src/base/system.cpp
=> Improve consistency and readability of Windows API usages by using less wrapper functions

src/game/client/components/menus_settings.cpp
This meant that only the first skin prefix button could be activated.
Regression from #5633.
=> Fix skin prefix button container being used for multiple buttons

src/game/client/components/menus.cpp
=> Move home button to very right so it is consistent with close button ingame (fixes #5881)

src/base/system.cpp, src/base/system.h, src/game/client/components/menus.h, src/game/editor/editor.h, src/test/str.cpp
See commit messages for most changes. See the following screenshots that show how sorting of maps and demos is changed.
Sorting with `str_comp_nocase`:
Sorting with `str_comp_filenames`, which is now also sorting case insensitive:
=> Add tests for various string functions, make `str_comp_filenames` case insensitive and use it again for sorting filenames

src/engine/shared/console.cpp
Pass the original string to the unknown command callback instead of the parsed command, as the latter ends at the first whitespace, which breaks for unknown commands (filenames) containing spaces.
Closes #5902.
=> Fix unknown command handler for filenames containing spaces

src/engine/shared/datafile.cpp
=> Less logging when loading maps on expected path

src/base/system.cpp, src/engine/shared/engine.cpp
=> Handle non-default Windows directory in `os_version_str`, print the operating system version on client/server launch

src/game/client/components/menus.cpp
Since it looks ugly overlaid over the other tabs
=> Only show ingame hint in Game tab

README.md
there is no `libx264-devel` in fedora repos, its `x264-devel` Also using `dnf` is better, i guess...
=> Fedora deps

other/config_directory.bat
fixes #5936
Tested scenarioses when either DDnet directory present or Teeworlds directory present, and nor of them.
=> Fix config_directory.bat (whitespaces in the path)

src/base/system.cpp, src/base/system.h, src/engine/client/client.cpp, src/engine/server/main.cpp
=> Initialize the Windows COM library on all threads, ensure Windows DDE conversations are finished in `open_link`

scripts/parse_drmingw.sh, src/base/system.cpp
Update Dr. Mingw (ExcHndl) to 0.9.8.
Use the new `ExcHndlSetLogFileNameW` function to set the exception log file name using wide characters, to support paths containing unicode.
It's not necessary to call `ExcHndlInit` explicitly after loading `exchndl.dll`, as the `DllMain` will already initialize the exception handler when the DLL is loaded. Module offsets are supported by upstream ExcHndl now, so we don't need to provide our own version that supplies the module offset to `ExcHndlInit` anymore. Upstream ExcHndl will also resolve the source code lines for addresses automatically, when the executable is build with debug information.
Handle the cases that the exception handling module cannot be loaded and that the `ExcHndlSetLogFileNameW` function cannot be found in the module.
Update …
=> Support unicode with ExcHndl, use upstream module offsets, handle errors

src/engine/client/client.cpp, src/engine/client/client.h, src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser.h, src/engine/serverbrowser.h, src/game/client/components/menus_browser.cpp, src/game/client/gameclient.cpp
=> Inline `Is(GameType)` functions and remove support for legacy 64 player info protocol

src/game/client/components/chat.cpp, src/game/client/components/ghost.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/players.cpp, src/game/client/components/skins.cpp, src/game/client/components/skins.h, src/game/client/gameclient.cpp, src/game/client/skin.h
most of the time it uses the index just to get the skin, downloaded skins change the index. Now its simply a heap object and downloaded skins load directly. Also the loading might be a bit faster bcs it had a loop lookup .Also O(1) lookup
not 100% tested. also fixes a bug with favorite skins hopefully
=> Get away from vector for skins

src/engine/shared/config_variables.h
Having it disabled opens up the server for attacks.
=> Enable antispoof for vanilla by default

src/android/android_main.cpp, src/base/hash.cpp, src/test/hash.cpp, src/tools/map_optimize.cpp
=> Add tests for too small/large `sha256_str` and `md5_str` buffers, minor refactoring

src/game/client/gameclient.cpp
As reported by @ChillerDragon on Discord.
=> Fix client crash when server does not send gameinfo

src/base/system.cpp
By moving the calling convention `APIENTRY`, which expands to `__stdcall`, inside the parenthesis.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2143	syntax error: missing ')' before '('	engine-shared	src\base\system.cpp	4242
Warning	C4229	anachronism used: modifiers on data are ignored	engine-shared	src\base\system.cpp	4242
Error	C2059	syntax error: ')'	engine-shared	src\base\system.cpp	4242
Error	C2059	syntax error: ')'	engine-shared	src\base\system.cpp	4242
Error	C3536	'exception_log_file_path_func': cannot be used before it is initialized	engine-shared	src\base\system.cpp	4246
Error	C2446	'==': no conversion from 'nullptr' to 'int'	engine-shared	src\base\system.cpp	4246
Error	C2064	term does not evaluate to a function taking 1 arguments	engine-shared …
```
=> Fix compilation with VS2022 with exception handling enabled

scripts/parse_drmingw.sh
The end anchor is removed from the grep RegEx, as it's not necessary and as it doesn't work on Linux systems when the crash log uses Windows line endings.
=> Fix `parse_drmingw.sh` not finding module offset on Linux systems

CMakeLists.txt
Previously warnings were generated because we were passing /MTd-like arguments twice, due to us and CMake 3.15+ adding these arguments: https://cmake.org/cmake/help/v3.25/policy/CMP0091.html.
This requires CMake 3.15 on Windows.
This fixes #5940.
=> Use CMake to configure static C stdlib on Windows

src/game/client/components/menus_settings.cpp
Just noticed that the menu button didnt work anymore, bcs we often use the pointer of the config vars or other variables for the pID ptr
and since i moved the m_aName up in the CSkin: pSkin(the ptr) and pSkin->GetName()(ptr to m_aName) returned the same ptr ( another UI element already use pSkin, our UI breaks bcs of that)
such a mess xDD
=> fix skin click ptr

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/layer_tiles.cpp
Add an option when the info button is selected, you can show the hexadecimal values for a tile rather than 1-255. This has some benefits, as it aligns in a perfect grid. Can help with making and test automappers.
=> Hex Values in the editor's info feature

src/base/system.cpp, src/tools/map_create_pixelart.cpp, src/tools/map_find_env.cpp, src/tools/map_replace_area.cpp
=> Avoid using `atoi`, `atof` and `atol` functions, use `str_copy` instead of `snprintf` to copy strings

src/engine/shared/console.cpp
=> Don't print max value when there is none (fixes #5953)

.pylintrc
I think we should disable this warning for unknown warnings so that old pylint versions keep working ok
=> Ignore useless pylint options (fixes #5950)

src/game/editor/editor.cpp
The crashes were already present before #5751.
=> Fix crashes in editor when scrolling with up/down keys on empty sounds/images lists

src/engine/client/client.cpp
When entering the editor with a custom bind (e.g. `bind e "cl_editor 1"`) or when opening it from the console while also immediately closing the console (e.g. with `cl_editor 1; toggle_local_console`), the IME state was not properly set to active, so SDL did not report any `SDL_TEXTINPUT` events, leading to editboxes in the editor not receiving any text.
The is fixed by always enabling the IME state when entering the editor, which was previously only done when using the Ctrl+Shift+E hotkey or coincidentally when the editor is activated while the IME is already active, i.e. when the menu or console is open.
Closes #5095.
And fix another minor issue that became apparent due to added debug messages while debugging the previous issue:
Previously the IME was not deactivated when the editor is …
=> Fix text input not working when entering editor with bind, fix IME not being deactivated when editor is closed

src/engine/shared/demo.cpp, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp
Crash reported by @teini94 on Discord.
=> Fix crash when cutting a demo opened from command line, various other demo menu fixes

.github/workflows/build.yaml, .github/workflows/clang-sanitizer.yml, .github/workflows/clang-tidy.yml, .github/workflows/codeql-analysis.yaml, .github/workflows/style.yml
The following warning is logged in the recent workflow runs:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
So, this pull request updates actions/checkout version to its latest release.
I haven't seen any warnings regarding CodeQL's actions but their code was updated to node.js since version 2.1.28 (see [this commit](https://github.com/github/codeql-action/commit/3d23aade469aa3ec77a29f1721762b1a06923bcc)).
Same for actions/upload-artifacts, available since version 3.1.1 (see [this commit](https://github.com/actions/upload-artifact/commit/2244c8200304ec9588bf9399eac622d9f …
=> Update GitHub actions versions

src/game/editor/popups.cpp
Large editor popups could be positioned outside of the screen area, when they could not be positioned below or to the right of the cursor without overflowing. This is fixed by making sure the popup does not overflow the top or left side of the screen after adjusting its position.
A small margin is also added so popups don't start or end immediately at the screen border.
Closes #5982.
=> Fix large editor popups being outside of screen, add margin

src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/graphics_threaded.cpp, src/game/client/components/binds.cpp, src/game/client/components/binds.h, src/game/client/components/chat.cpp, src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_settings.cpp, src/game/client/gameclient.cpp, src/game/editor/editor.cpp, src/game/server/gamecontext.cpp
Using `str_format(aBuf, sizeof(aBuf), "%s", pStr)` is equivalent to `str_copy(aBuf, pStr, sizeof(aBuf))`. Using `str_copy` is more readable and also more efficient as there is no overhead from parsing the format string and from passing varargs.
=> Use `str_copy` instead of `str_format` with format `"%s"`

src/base/log.cpp, src/base/system.cpp
=> Handle all `MultiByteToWideChar` and `WideCharToMultiByte` return values

src/game/editor/popups.cpp
It was possible to select tele number 0, speedup force 0 and switch number 0 in the layer details in the editor, because some of the bounds checks or calculations were not excluding the value 0. As placing those tiles with the value 0 in the editor is not possible and the tiles with this value are ignored by server and client, it also shouldn't be possible to select those values in the first place.
=> Fix incorrect minimum values for tele, speedup and switch layers

src/game/editor/editor.cpp
The hotkey Ctrl+A is already active universally in the editor to open and append a map to the current one. This collides with the hotkeys for opening the layer/tile details popup for tune, tele, speedup and switch layers, which is only active when a layer of said type is select. Pressing the hotkey in this context opens the popup and the append dialog at the same time, which is undesirable. Therefore the hotkey to open the layer/tile details is changed to Ctrl+T instead. This combination is currently unused and seems approriate, as the T could stand for "Tile details".
=> Change editor hotkey Ctrl+A to Ctrl+T for layer/tile details

src/test/jobs.cpp
Allow host resolving to fail, but still check its results if it succeeds.
=> Allow the test suite to run offline

src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/backend/vulkan/backend_vulkan.h
Since the vulkan loader drops support for useful extensions (or the extension loading process changed between 1.0 & 1.1, not sure) Which causes OBS not to work
lets wait for a response in 
`https://github.com/KhronosGroup/Vulkan-Loader/issues/1048`
tho
=> Switch to Vulkan 1.1

.gitignore, other/vscode/README.md, other/vscode/ddnet-cmake-tools-kits.json, other/vscode/ddnet.code-workspace
The workspace is completly optional and doesn't need to be used
It suggests fitting extensions, comes with preconfigured launch tasks (+ prebuild task). some settings useful for using clang-format, -DDEV=ON, mold as linker etc.
if windows is ok leaving out `.exe`, it should also work there i guess, but not tested.
=> Add an optional vscode workspace

src/test/packer.cpp
This is an effort to test the Integer packer code. It should hopefully also be useful as some kind of documentation for everyone trying to understand how ints are packed.
BTW github in my browser uses a weird angle for the slashes so it looks like this:
In my vscode it looks nice tho:
Or in vim. So I blame the github web preview font being broken:
=> Add tests for int packer

src/rust-bridge/test/build.rs
Detect that we're being run from rust-analyzer and don't link to C++ libraries in that case.
Fixes #6019.
=> Fix being run from rust-analyzer with a clean environment

src/game/editor/editor.cpp, src/game/editor/editor.h
I made this not as a completely final idea, but a step forward to an overall cleaner UI experience. New mappers would want to use the buttons more, and so we should it readable for those who do use them. I also fixed the zoom in/out buttons because a negative overflow is possible. If you zoom all the way in and hit the zoom in button, there wasn't a stopping point.
Old: 
New:
=> Change editor UI, fix an overflow bug.

src/engine/client/client.cpp, src/engine/client/client.h, src/game/server/gamecontext.cpp
=> Fix some strict-aliasing warnings and too large snapshot buffers

src/game/editor/editor.cpp
If any game layers are hidden, the hotkey will make them visible. Else, if all game layers are visible, the hotkey will hide all of them.
Closes #4109.
=> Add `Shift+G` editor hotkey to toggle visibility of game layers

src/game/editor/editor.cpp, src/game/editor/editor.h
Shifting left/right with a shift value greater than the layer's width crashed the game due to a heap-buffer-overflow.
Shifting up/down with a shift value greater or equal to half the layer's height did not correctly shift the entire layer.
The values of the enum constants `DIRECTION_*` are changed to consecutive numbers instead of exponents of two, as the directions cannot be combined together as flags.
Closes #6036.
=> Fix editor crash when shifting left/right, fix wrong up/down shifting

README.md
looks like in https://github.com/ddnet/ddnet/commit/07be2a7663f0fcc847d06c2ce649c35da9ce9970 cargo package for fedora wasn't added
=> add cargo for fedora

src/engine/client/client.cpp, src/engine/server/main.cpp, src/engine/server/server.cpp, src/engine/shared/demo.cpp, src/engine/shared/storage.cpp, src/engine/storage.h
The types are translated to `TYPE_ALL`/`TYPE_SAVE` respectively if a given path is relative and to `TYPE_ABSOLUTE` if a path is absolute.
These types are only supported with the `OpenFile`, `ReadFile`, `ReadFileStr` and `GetCompletePath` methods.
This reduces duplicate code when calling the methods.
=> Add `TYPE_ALL_OR_ABSOLUTE` and `TYPE_SAVE_OR_ABSOLUTE` storage types

src/game/client/components/menus_browser.cpp
Added friend counter, changed the alignment of player count indicator to better accommodate friend counter + line up with the "Players" text at the top of the tab
Fixes #5911
=> Add friend counter + Change alignment of player count text

src/engine/shared/demo.cpp
Demo seeking for percent positions and relative time was choppy, when the first and last ticks of the demo are very large but close together (e.g. with 1308908156 to 1308905658, which are close to integer limit). During the calculation of `WantedTick` both operands were promoted to `float`s, which caused the information of the smaller operand, i.e. the seeked percentage or relative time, to be mostly lost, so seeking was very inaccurate. This is fixed by rounding the `float` operand to `int` before adding it to another `int`.
=> Fix choppy demo seeking when start/end ticks are very large

src/game/client/components/menus_demo.cpp
Before, you could place an end slice before the beginning, creating a "zero second" demo, which doesn't play in client, and renders a corrupt file. I implemented a check where if the playhead is before the beginning slice, it won't place an end slice, and vice versa. 
I also added highlighting in between the slices, so that it's easier to see.
=> Fix invalid demo cutting, Add slice highlighting

src/game/editor/editor.cpp, src/game/editor/editor.h
Port the smooth zoom code from the ingame camera to the editor with some minor adjustments.
The smooth zoom animation time can be adjusted with the existing `cl_smooth_zoom_time` config variable.
Closes #2525.
=> Implement smooth zoom for editor

src/engine/shared/network.cpp
The client crashes when trying to unpack a packet that has the sixup flag set, as `CNetClient` does not pass pointers for the output parameters `pSecurityToken` and `pResponseToken` to `CNetBase::UnpackPacket`. Since the client does not handle sixup packets, checks are added to return an error and ignore the packet instead of crashing due to a null pointer access.
This was found by fuzzing the data returned by `net_udp_recv` with radamsa.
```
==6200==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f8d0fb8ba56 bp 0x7ffcbf67c7f0 sp 0x7ffcbf67c7a8 T0)
==6200==The signal is caused by a WRITE memory access.
==6200==Hint: address points to the zero page.
0 0x7f8d0fb8ba56  (/lib/x86_64-linux-gnu/libc.so.6+0xc4a56)
1 0x563a7e250fbe in mem_copy src/base/system.cpp:208
2 …
```
=> Fix client crash when unpacking a sixup packet

src/game/ddracecommands.h, src/game/server/ddracecommands.cpp, src/game/server/gamecontext.h
When vote muting a player, the message which notifies the player got send in team chat (should be chat_all) and a second message appeared in rcon. Furthermore you couldnt add a reason to vote mutes.
Fixed those issues.
=> Add reason to vote mute, fix vote mute

src/game/server/gamecontroller.h, src/game/server/gamemodes/DDRace.cpp, src/game/server/gamemodes/DDRace.h, src/game/server/teams.cpp
The state of teams was not reset when restarting a round with `restart`, which led to various issues (#5144):
- Switchers kept their previous state instead of being reset to the initial state after restarting.
- Teams that started racing sometimes could not be joined after restarting.
- Sometimes teams cannot finish a race after restarting. I cannot reproduce this issue, so I don't know if it's fixed by these changes.
=> Reset teams when restarting round

src/game/client/components/menus.cpp, src/game/client/components/menus.h
The key reader was displaying the old key for a frame. It now shows the new key immediately without flashing the old one after changing a bind.
Refactoring:
- The if-branches are restructured to be the same as on upstream.
- The function `GetKeyBindModifiersName` can be called without an additional check, because it returns an empty string when no modifier is pressed.
- The unused parameter `Checked` of the `DoButton_KeySelect` function is removed.
From teeworlds/teeworlds#2877.
=> Fix key reader text flashing for one frame, refactoring

src/engine/client/client.cpp, src/engine/shared/console.cpp, src/engine/shared/console.h
=> Fix stored commands using original callback instead of the chain, fix client crash when launching with `screenshot` command

src/game/client/components/camera.cpp
The cursor position was not correctly restored when exiting pause or spec, when the mouse was on the left side of the tee (x being negative).
This is caused by a calculation introduced in #1637 and #1830 that tries to ensure that the mouse can still be moved if it ends up inside the minimum mouse distance (`cl_mouse_min_distance` and `cl_dyncam_min_distance`). However, this did not consider that the x position can become negative, so the x position was also incorrectly changed when exiting pause.
This is fixed by reverting the changes, as this code has become obsolete and has been superseded by #2009 and #3884. The `CControls::ClampMousePos` function, which is called directly after restoring the position, already ensures that mouse is not stuck within the minimum mouse distance.
Closes …
=> Fix incorrect cursor position after exiting pause/spec

src/game/client/components/menus_demo.cpp
Aimed to add some more controls on the demo view bar:
Added tick step buttons and jump to next/prev marker buttons
Increased width of demo controls panel so it wasn't as cluttered
changed export cut icon to a common export icon instead of the camcorder icon
Centered the time multiplier between the buttons it was between
=> Add buttons+increased length on demo viewbar

src/game/client/components/menus_demo.cpp
Followup for #6060.
Before:
After:
=> Make sure components are reset and envelopes are updated when skipping in demo, fix demo name not being shown in demo player

src/game/editor/editor.cpp, src/game/editor/popups.cpp
When multiple quad points are selected, adjust the points' positions and texture U/V coordinates relatively instead of setting all points to the same value.
Closes #3359.
https://user-images.githubusercontent.com/23437060/205491450-569dd6f8-3f14-45dd-9bb5-4b0b7a0be790.mp4
=> Adjust quad point position and texture U/V relatively

src/base/system.cpp, src/engine/server/databases/connection.cpp, src/engine/server/databases/connection.h, src/engine/server/databases/connection_pool.cpp, src/engine/server/databases/connection_pool.h, src/engine/server/databases/mysql.cpp, src/engine/server/databases/sqlite.cpp, src/engine/server/server.cpp, src/game/server/score.cpp, src/game/server/scoreworker.cpp, src/game/server/scoreworker.h, src/test/score.cpp
Fixes #4424
* Immediately store all ranks/teamranks/saves in separate tabel (suffixed with `_backup`) in sqlite
* remove the rank if mysql succeeds
* move the rank to non-`_backup` table when failed
* loading save codes from non-`backup`-tables is still possible (mostly the reason for the backup table to exist: to prevent double loading)
* Immediately tell player how the backup save code will be on save failure
* It uses another thread (backup-thread) which goes through all changes first and writes ranks/teamranks/saves into the database
* Enables `WAL`-mode in sqlite, because of busy-errors during opening the files (we open it every time we process a new rank/...)
* Made database code more thread safe (especially adding new databases)
I mostly started appending commits. I can squash them …
=> Pr failsafe mysql

src/game/ddracecommands.h, src/game/server/ddracecommands.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
issue #5433 
Moderators can access the last x minutes of the chat activity.
Every entry beside server messages will show the player name, player ip and client who wrote the message / who disconnected so moderators can get the players ip after something happened in case he left already.
The current implementation has a 4 minute time slot, messages older than 4 minutes are not shown.
To limit the memory usage its limited atm to 256 log-entries. In case of more messages than 256 in 4 minutes (unlikely), the oldest messages are overwritten.
I keep this as a draft for a while, because its my first pr and I am sure there is some improvement i did not see (or to improve the wording)
=> Add logs for moderators (fixes #5433)

other/vscode/ddnet-cmake-tools-kits.json, other/vscode/ddnet.code-workspace
current is completely wrong, since it overwrites the cmake internal settings. and e.g. prevent `-g`
Now it should in worst case only overwrite custom settings by the user. but dunno how often u actually do that anyway inside a IDE
but if someone knows better I'm glad to hear it
=> Fix cmake args in workspace

src/engine/shared/network.cpp
=> Remove check for `pResponseToken`, which isn't used on this code path

src/game/client/components/menus_browser.cpp
Hi,
according to #6090, this isn't a big deal, is it? BW mode is pretty important and well known, so it would be cool to give it its own color!
**this has already been discussed by the BW team.**
=> Colorify BW gamemode

src/engine/server/databases/mysql.cpp
Found in #6050 that a 16 byte long name would be written, filling up the string entirely, no terminating '\0'
=> Null-terminate string returned by mysql

src/engine/server/databases/connection_pool.cpp
Fixes #6106
Seems like I didn't tested before whether the rank got removed in the successful path.
=> Remove successful queries from write backup

src/game/editor/editor.cpp, src/game/variables.h
Add `ed_smooth_zoom_time` option for smooth zooming in editor separate from the `cl_smooth_zoom_time` that's used for smooth zooming ingame, as some mappers seem to prefer unsmooth zooming in the editor but smooth zooming ingame.
=> Add separate option for smooth zooming in editor

src/engine/shared/demo.cpp, src/engine/shared/demo.h
When slicing a demo, also copy the demo markers that are within the sliced segment to the new demo.
This also fixes timeline markers not being added to replay demos, as the replay demos are always created by slicing.
Closes #6116.
=> Copy the demo timeline markers when slicing a demo

src/engine/client/client.cpp
When the client stops a replay demo and tries to remove the temporary file when being disconnected, it's not checked whether a recording of a replay demo has ever been started. In this case the filename is empty, which leads to the client trying to delete the user's directory, which will fail with an error message, as it's a folder and cannot be deleted with the function designed for deleting files.
This is fixed by calling the function `DemoRecorder_Stop` to delete the temporary demo file, as this function already makes sure that the filename is not empty.
=> Fix client attempting to delete user directory when stopping replay demo

src/engine/shared/config.h, src/engine/shared/config_variables.h, src/game/client/components/menus_settings.cpp
Maybe it wouldnt hurt to test it out very soon for nightly players already, since the path is rather small it should not conflict so often
Note: i added constexpr to config struct, bcs else i cannot cleanly read the default value for the configs.
Any complains e.g. move it to new struct now would be your time.
=> Minimal changes to default to Vulkan

scripts/move_sqlite.py
Fixes #6105
This change does some more stuff:
* change the filename to include the time with seconds to be able to run the script easier more often
* Fix that _backup tables are only moved after 1h and not immidiately in UTC+1
* Add a parameter to configure the number of minutes the backup
* Add parameter to change timestamps to be in localtime
* consider the timeout in num_transfer calculation
* remove rows in _backup tables to not print in them in the log
* rename tables to TABLES, because it is meant to be a constant
=> Improve move_sqlite script to adapt timezone

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/game/editor/editor.cpp, src/game/variables.h
=> Add separate `ed_limit_max_zoom_level` for editor, fix editor smooth zooming when joining/reloading game 

.github/workflows/build.yaml, CMakeLists.txt, src/engine/client/backend/vulkan/backend_vulkan.cpp
Issues found in the logs from https://github.com/ddnet/ddnet/issues/6145
=> Use %zu formatter for size_t, not PRIu64 (which is for uint64_t)

src/engine/client/input.cpp, src/engine/client/input.h, src/game/client/components/menus_settings.cpp
Handle the appropriate SDL events to open new joysticks when they are connected and remove joysticks when they are disconnected.
If the active joystick gets disconnected, then the first joystick in the list will be activated as a fallback.
If the previously activated joystick gets reconnected, it will be activated again automatically, as it is identified by the GUID stored in the configuration.
The stored joystick GUID is only updated when the user manually selects a new joystick in the controls settings or with the console.
Closes #6152.
=> Add support for hot-plugging gamecontrollers

src/game/client/components/camera.cpp, src/game/editor/editor.cpp
Ensure that the zoom level with smooth zooming does not exceed the target zoom level.
Closes #3747.
=> Fix smooth zooming overshooting the target zoom level

src/game/server/entities/character.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/player.cpp, src/game/server/player.h
=> Persist AFK state of players on map change, fix players always being considered AFK with `sv_max_afk_time 0 `

src/game/editor/editor.h, src/game/editor/popups.cpp
When using `UiClosePopupMenus` in a popup handler, the number of popups was first set to `0` and then decremented to `-1` due to the popup itself being closed, which causes the next popup to not open correctly and may also cause a crash due to an out-of-bounds access.
The `UiClosePopupMenus` function is adjusted so the number of open popups never goes below `0`.
Another check is added to ensure that `UI()->SetActiveItem(nullptr)` is only called when a popup is open, so the currently active item is not reset if no popup is open.
Duplicate code in `UiDoPopupMenu` is reduced by calling the `UiClosePopupMenus` function to only close the top-most popup.
This also fixes the same issue when a popup is closed by the popup handler and the escape key in the same frame, by only handling the escape …
=> Fix issues when closing multiple editor popups at the same time

cmake/CheckAtomic.cmake
Fix build on RISC-V (and other platforms that the original CheckAtomic.cmake may give false positive), since there are no sub-word atomics but larger ones like 32-bit and 64-bit.
Debian buildd logs: https://buildd.debian.org/status/fetch.php?pkg=ddnet&arch=riscv64&ver=16.4-1&stamp=1671449589&raw=0
See https://github.com/llvm/llvm-project/commit/cef85193b2cc1817ca43199a0ae9c6f25723997d for more information.
=> Fix CheckAtomic.cmake

src/base/log.cpp, src/base/system.cpp, src/test/str.cpp
This is supported on Windows
(https://docs.microsoft.com/en-us/cpp/c-runtime-library/printf-p-positional-parameters) and on POSIX, so basically everywhere.
Add some tests to verify that the target system does indeed support these positional parameters.
(cherry picked from commit ddd2b9319076efa81ca87e2f9582e328824f37db)
=> Allow translations to reorder string substitutions

CMakeLists.txt
Requested by Chairn, because the Rust tests are slow on their computer.
=> Add target `run_cxx_tests` to only run C++ tests

src/engine/client/serverbrowser.cpp
Thanks to bencie for reporting
=> Ignore connecting players in search terms when "Filter connecting players" is on

src/game/server/scoreworker.cpp
=> Fix teamranks not getting removed or moved out of _backup table

src/base/system.h, src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/client.cpp
Counter proposition to #6188. Redefines our own specifiers
=> Use own defines of format specifiers for MinGW (fixes #6187)

src/engine/client/client.cpp, src/engine/shared/demo.h
Each time the client disconnected or stopped a demo, it tried to delete the previous temporary replay file, which causes an error message "could not delete file" to be shown in the console.
This is prevented by clearing the current filename of the demo recorder after deleting the file.
=> Prevent temporary demo file from being deleted multiple times

src/game/client/prediction/entities/character.cpp, src/game/server/entities/character.cpp
Reasoning this change is correct:
* `OldPos` is set to `m_Pos` in line 260
* `m_Pos` is not modified in between line 260 and 272 (only `m_Core.m_Pos` gets modified)
* Therefore line 269 `Dir = m_Pos - OldPos` is always `vec2(0.0, 0.0)`.
* And line 271 `Center = OldPos + Dir * 0.5 = OldPos`.
So we can pass `OldPos` to `FindEntities` in line 272. Using `OldPos` here instead of `m_Pos` makes it clear, that we use the position before the move, even though `m_Pos` also still holds the old value.
=> Simplify ninja code

src/engine/demo.h, src/engine/shared/demo.cpp
Instead of using hardcoded tick offsets, use the current/previous/next tick values from the demo info.
This fixes seeking the next tick not working for demos where the difference between the current and the next tick was greater than 3.
=> Fix edge cases where demo tick seeking did not work

src/game/server/gamemodes/DDRace.cpp, src/game/server/gamemodes/DDRace.h, src/game/server/score.cpp, src/game/server/score.h, src/game/server/scoreworker.cpp, src/game/server/scoreworker.h, src/game/server/teams.cpp, src/test/score.cpp
by requesting the best time again when it initially failed. This is still not perfectly accurate since a player on another server can get a better time, which will not get updated when the current server had no database problems.
As reported by thekid36 on Discord:
> The best time shown on the scoreboard on the turkish server on a
> ddmax.Next map (mapname: 42) is 30min..while the best time should be 4
> min (it's correct on ger2 server)
So the way it works is that the best time is loaded from database when loading map. Additionally it gets updated when a new finish is done. If the initial load failed, but a finish with 30 min is done on the server, we get this result
=> Fix scoreboard showing wrong best time

src/base/system.cpp, src/base/system.h, src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/game/client/components/menus_settings.cpp
When launching the client on Windows, associate the protocol `ddnet` and the file extensions `.map` and `.demo` with the client executable.
See #6072.
=> Register protocol and file extensions on client launch on Windows

src/base/system.cpp, src/test/str.cpp
Actually, the two lines i deleted in #6206 were useful if first number is greater but second number is 0 prefixed.
=> Add some more test to str_comp_filenames and restore old behavior

src/base/system.cpp, src/base/system.h, src/engine/client/client.cpp, src/engine/shared/storage.cpp, src/engine/storage.h
Follow-up from #6199.
Adding version information to the executable (#6203) doesn't result in the name being shown in the Windows settings. There is a separate registry key where applications can register a readable name.
See: https://learn.microsoft.com/en-us/windows/win32/shell/app-registration
=> Register application separately to specify its displayed name

src/engine/shared/demo.cpp
When the demo recording is not stopped properly (e.g. client crashes during recording), the timeline markers and the demo length are not updated. The length is always set to zero when starting the recording, but uninitialized memory is written for the timeline markers, which causes these demos to likely show the maximum number of markers with some markers possibly being outside the ticks that the demo contains. This is fixed by initially setting all timeline marker data to zero when starting the recording.
=> Fix undefined demo timeline markers when recording is not stopped

CMakeLists.txt, README.md
To disable -D_FORTIFY_SOURCE=2 -fstack-protector-all, see https://bugs.gentoo.org/888875 for report. Default behavior is not changed.
=> Add -DSECURITY_COMPILER_FLAGS=OFF option

src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/server/teams.cpp
Closes #6168.
Not resetting the team when restarting requires too much effort for a feature that would only be active with the non-default `sv_rejoin_team_0 0` setting. If the `restart` command is used for testing a map or for tournaments, it would be easy enough as a workaround to create a bind to join a specific team after restarting, so I don't think this is necessary.
=> Fix more issues with the `restart` command

src/game/server/ddracecommands.cpp, src/game/server/entities/laser.h, src/game/server/entities/projectile.h, src/game/server/entity.h, src/game/server/gameworld.cpp, src/game/server/gameworld.h, src/game/server/save.cpp, src/game/server/save.h, src/game/server/score.cpp, src/game/server/scoreworker.h, src/game/server/teams.cpp
Restructured CSaveTeam a bit, because I also needed access to CGameWorld. I don't store pointer to IGameController in CSaveTeam anymore, because we pass CSaveTeam to the database thread. If it would be accessed there, it could cause a race conditions.
=> Remove projectiles on save and load

src/engine/client/serverbrowser.cpp, src/engine/serverbrowser.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_ingame.cpp
Add "Copy info" buttons to server browser and ingame menu to copy the server info of the selected/current server to the clipboard.
The margins around the server browser details are improved.
Closes #5440.
Screenshots:
- browser (old):
- browser (new):
- ingame:
=> Add ingame and browser buttons to copy server info to clipboard

src/game/client/prediction/entities/character.cpp, src/game/gamecore.cpp, src/game/server/entities/character.cpp
Remove unused `m_FreezeTime == -1` state
Reduces code complexity. Both `g_Config.m_SvFreezeDelay`[[1]] and `GetSwitchDelay(int Index)`[[2]] can only return non-negative numbers, therefore this is currently dead code and can be removed.
The last time it was possible to pass a negative number was removed in https://github.com/ddnet/ddnet/commit/561ce6466671397979ed77f0cbf368f93f33361f#diff-29ffe32916052e1066eed938021aadfeb29f855d7c63d9c1ca3350aceffb79f3L1624
[1]: https://github.com/ddnet/ddnet/blob/c8ea372d9851709c2fe4db7362bdc07d263079ff/src/engine/shared/config_variables.h#L213
[2]: https://github.com/ddnet/ddnet/blob/c8ea372d9851709c2fe4db7362bdc07d263079ff/src/game/mapitems.h#L467
=> Remove dead freeze code

CMakeLists.txt, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings_assets.cpp, src/game/client/components/menus_start.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/client/ui_listbox.cpp, src/game/client/ui_listbox.h, src/game/editor/editor.cpp, src/game/editor/editor.h
Replace existing listbox implementations (`CMenus::UiDoListbox*` and `HandleListInputs` functions) with `CListBox` from upstream.
Reimplement additional feature that was already present in ddnet: page up/down, home and end key handling.
Affects the following lists:
- server browser
- see screenshots for scoreboard
- server browser scoreboard
- before:
- after:
- server browser friends
- before:
- after:
- country / region selection popup (server browser filter)
- before:
- after:
- player skin list
- before:
- after:
- player country / region list
- before:
- after:
- theme list
- before:
- after:
- assets list
- before:
- after:
- graphics resolutions list
- before:
- after:
- dropdown menus (e.g. graphics fullscreen mode)
- see screenshots for graphics resolutions list
- ingame player …
=> Port `CListBox` from upstream, smooth scrolling for all lists

src/engine/shared/datafile.cpp
This was removed by @Robyt3 in commit 31533d5e2aaa3d071668285af72997d95d631e1c, but it is still used behind `#if defined(CONF_ARCH_ENDIAN_BIG)` at https://github.com/ddnet/ddnet/blob/master/src/engine/shared/datafile.cpp#L145-L147 resulting in:
https://buildd.debian.org/status/fetch.php?pkg=ddnet&arch=s390x&ver=16.4-1&stamp=1665528559&raw=0
```
/<<PKGBUILDDIR>>/src/engine/shared/datafile.cpp: In member function ‘bool CDataFileReader::Open(IStorage*, const char*, int)’:
/<<PKGBUILDDIR>>/src/engine/shared/datafile.cpp:202:56: error: ‘minimum’ was not declared in this scope
202 |         swap_endian(m_pDataFile->m_pData, sizeof(int), minimum(static_cast<unsigned>(Header.m_Swaplen), Size) / sizeof(int));
|                                                        ^~~~~~~
```
=> src/engine/shared/datafile.cpp: Re-add #include <base/math.h> for big endian

src/engine/serverbrowser.h, src/engine/shared/serverinfo.cpp, src/engine/shared/serverinfo.h, src/game/client/components/menus_browser.cpp
with #6240 we might get few more pixels for either flag or margin
=> Add skin to serverbrowser's scoreboard

src/game/client/components/menus_browser.cpp
The selected server browser entry was not being updated anymore when the server address input is changed manually by the user or when selecting an entry in the LAN server list and then switching back to the Internet list.
Regression from #6240.
=> Fix server browser selection not being updated based an address input

src/engine/shared/snapshot.cpp
Use a different error code for every return statement, so it's easier to determine why unpacking a delta failed.
The codes are grouped by the first digit of the error code:
- `-1xx`: not enough data to read
- `-2xx`: value is invalid
- `-3xx`: could not build snapshot item
=> Use distinct error return codes for `CSnapshotDelta::UnpackDelta`

src/game/client/ui_listbox.cpp
It was no longer possible to navigate listboxes (e.g. the server browser) by using keyboard hotkeys when no item is currently selected due to a regression from #6240.
Additionally, it was not possible even before #6240 to start navigating the server browser with the keyboard afer manually clearing the server address input, which is now possible as well.
=> Allow navigating listboxes when no item is currently selected

src/game/client/ui_scrollregion.cpp, src/game/variables.h
This variable adjusts the time for smooth scrolling of all scrollregions and listboxes in the menus and editor.
The value `0` disables smooth scrolling entirely.
=> Add `ui_smooth_scroll_time` variable to adjust smooth scrolling

src/engine/client/backend/vulkan/backend_vulkan.cpp
Since it seems a rather common problem:
=> Show current memory usage in assert too

src/engine/client/client.cpp, src/engine/shared/protocol_ex_msgs.h
One case was a ddnet.tw UUID's string being changed (but the UUID was not), and the other case is a ddnet.tw UUID's string being changed in one place but not in another in documentation.
Fixes the commit c479230d714725754c93e516e3cde7fb96aac0c8.
CC #5312
=> Fix ddnet.org change in UUIDs

src/base/color.h
As described in #5844, sometimes the color kept changing when activating a color picker.
By rounding the color components before packing them into an unsigned, the color only changes very little and only at most once when activating a color picker.
=> Make color pickers not change selected color as much

src/game/editor/editor.cpp
=> Clear editor file browser search term when entering folder

src/game/client/components/menus_demo.cpp
When hovering the demo seekbar, show a tooltip with the time at the hovered position.
=> Add tooltip to demo seekbar showing the currently hovered time

src/base/vmath.h
$ clang --version
Debian clang version 11.0.1-2
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Fixes this error
```
In file included from
/home/chiller/Desktop/git/ddnet/src/base/color.h:6: /home/chiller/Desktop/git/ddnet/src/base/vmath.h:141:38: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
constexpr inline vector2_base<float> direction(float angle)
^
/home/chiller/Desktop/git/ddnet/src/base/vmath.h:143:29: note: non-constexpr function 'cosf' cannot be used in a constant expression
return vector2_base<float>(cosf(angle), sinf(angle));
^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:62:1: note: declared here __MATHCALL_VEC (cos,, (_Mdouble_ __x));
^
/usr/include/math.h:266:3: note: expanded from macro '__MATHCALL_VEC' …
```
=> Fix build with clang on debian 11

src/game/client/components/menus_ingame.cpp
The tee and label were overlapping due to a regression from #6240.
=> Fix layout of kick/spec vote list items

src/engine/shared/snapshot.cpp, src/engine/shared/snapshot.h
As the integer overflow/underflow in `UndiffItem` can happen during normal gameplay, we should in this case neither ignore the snapshot delta nor show an error message.
Instead of depending on the particular compiler doing integer wrapping, when integer overflows or underflows occur, we make it part of the design, by casting to `unsigned`, which ensures that integer wrapping is being used.
=> Ensure integer wrapping instead of preventing overflow/underflow

src/engine/message.h, src/engine/shared/network.h, src/engine/shared/network_server.cpp
=> `CMsgPacker` doesn't know about message ID encoding

scripts/send_named_pipe.ps1, src/base/system.cpp, src/base/system.h, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/config_variables.h, src/engine/shared/fifo.cpp, src/engine/shared/fifo.h
Reimplement the Linux FIFO file server and client controls on Windows by using Named Pipes.
The DDNet server/client acts as a named pipe server and receives messages.
Messages can be posted to the named pipe server by connecting to it as a client.
The named pipe client can for instance be controlled from the command line with PowerShell.
The PowerShell script `scripts/send_named_pipe.ps1` is added for this purpose.
For example the PowerShell command `./send_named_pipe.ps1 "testpipe" "echo a"` sends the command `echo a` to the pipe named `testpipe`.
Multiple commands can be sent at the same time by separating them with semicolons or newlines.
=> Implement FIFO on Windows using Named Pipes

.clang-tidy, src/engine/client/backend/glsl_shader_compiler.cpp, src/engine/client/client.cpp, src/game/client/prediction/gameworld.cpp, src/game/server/gamecontroller.cpp, src/game/server/gameworld.cpp
Alternative to #6294
The only remaining problems are:
```
/home/deen/git/ddnet/src/engine/client/backend/glsl_shader_compiler.cpp:22:26: warning: unnecessary temporary object created while calling emplace_back [modernize-use-emplace]
m_vDefines.emplace_back(SGLSLCompilerDefine(DefineName, DefineValue));
^~~~~~~~~~~~~~~~~~~~                       ~
```
=> More minimal clang-tidy 15 run

src/engine/shared/config_variables.h
Otherwise falls back to OpenGL 1.5, since 3.0 is not supported
=> Use OpenGL 3.3 on macOS by default

src/base/system.cpp, src/base/system.h, src/engine/client/client.cpp, src/engine/shared/storage.cpp, src/engine/storage.h
Check if deleting the old map file or renaming the temporary downloaded map fails. If so, show an error message which indicates that the user should delete the map file manually.
Sometimes downloaded map files seem to end up with wrong permissions, ownership or with read-only flag set, which makes the client unable to delete them.
Closes #5825.
=> Show error message when downloaded map cannot be saved

.github/workflows/style.yml
Due to changes in wording of the error messages, some of the twmap-check-ddnet warnings were no longer suppressed.
Closes #6305.
=> Fix map check excluded warnings in CI

src/engine/client/client.cpp, src/engine/client/input.cpp, src/engine/client/input.h, src/engine/input.h
=> Increase relative joystick movement based on input update time, disable relative joystick when console is open or window not focused

src/game/editor/editor.cpp
The texture of the previous preview image was not unloaded before loading the texture of the new image.
The PNG data was never freed either. It's not necessary to keep this data loaded after loading the texture.
=> Fix memory leak of editor preview image texture and data

datasrc/datatypes.py, datasrc/seven/datatypes.py, src/engine/client.h, src/engine/client/client.cpp, src/engine/message.h, src/engine/server.h, src/game/client/gameclient.cpp, src/game/server/entities/character.cpp, src/game/server/entities/door.cpp, src/game/server/entities/dragger.cpp, src/game/server/entities/dragger_beam.cpp, src/game/server/entities/gun.cpp, src/game/server/entities/laser.cpp, src/game/server/entities/light.cpp, src/game/server/entities/pickup.cpp, src/game/server/entities/plasma.cpp, src/game/server/entities/projectile.cpp, src/game/server/eventhandler.h, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/gamecontroller.cpp, src/game/server/player.cpp
> What is the motivation for the changes of this pull request?
The idea is to simplify and refactor the game code step by step. This is the next step after a similar https://github.com/ddnet/ddnet/pull/5600
The key idea is that all those
```cpp
protocol7::CNetObj_SpectatorInfo *pSpectatorInfo = static_cast<protocol7::CNetObj_SpectatorInfo *>(Server()->SnapNewItem(NETOBJTYPE_SPECTATORINFO, m_ClientID, sizeof(protocol7::CNetObj_SpectatorInfo)));
```
are too verbose and error-prone.
We have the relation between `CNetObj_` classes and their corresponding `NETOBJTYPE_` so we can use it to remove most of the arguments and the cast.
With some small changes in the generated code (e.g. MsgID leveraged from NetMessage to NetObject) we can come to this:
```cpp
auto *pSpectatorInfo = …
```
=> IServer: Add SnapNewItem() template to simplify the API, do some small refactoring

CMakeLists.txt, src/engine/server/server.cpp, src/engine/shared/protocol7.h
The protocolglue allows using all network constants from 0.7 using the ``protocol7::`` prefix. Such as game messages snap objects etc. But system messages are still magic numbers.
=> Add 0.7 system message constants

src/base/system.cpp, src/base/system.h, src/engine/client/client.cpp, src/engine/client/ghost.cpp, src/engine/client/ghost.h, src/engine/demo.h, src/engine/server/register.cpp, src/engine/shared/datafile.cpp, src/engine/shared/demo.cpp, src/engine/shared/network_server.cpp, src/engine/shared/snapshot.cpp, src/game/client/components/menus.h, src/game/server/teehistorian.cpp, src/test/bytes_be.cpp
=> Remove `bytes_be_to_int` and `int_to_bytes_be`, static assert size of `int` and `unsigned`, refactoring

src/game/variables.h
I guess when you have a bad connection, it stays the same during several days, so it makes sense to save prediction margin
=> Add `CFGFLAG_SAVE` flag to save prediction margin (fixes #6332)

src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/client/text.cpp, src/engine/graphics.h, src/game/client/components/chat.cpp, src/game/client/components/hud.cpp, src/game/client/ui.cpp
Reduce duplicate code and improve correctness by passing indices of quad, buffer and text containers by reference and always setting them to `-1` after they are deleted.
Also check if index is `-1` before trying to delete it to reduce duplicate code when calling the methods.
=> Reset graphics container indices after deletion

src/base/system.cpp, src/base/system.h, src/engine/shared/config.cpp
Instead of returning the number of bytes written, which are platform specific, return `true` on success and `false` on failure, so no platform specific code is required when checking the result.
=> Simplify `io_write_newline` error handling

src/engine/client/client.cpp, src/engine/client/client.h, src/engine/shared/console.cpp, src/engine/shared/console.h
Move `reset` command from client to console, so it's also available on the server.
=> Add `reset` command to server

src/engine/client/text.cpp, src/engine/textrender.h, src/game/client/components/hud.cpp, src/game/client/components/nameplates.cpp
The `RecreateTextContainer` function calls `DeleteTextContainer` and then `CreateTextContainer`.
The arguments of `RecreateTextContainer` and `RecreateTextContainerSoft` are reordered so all functions take the text container as their first argument.
=> Use `RecreateTextContainer`, reorder parameters

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_settings.cpp
Align the color picker selection and reset buttons on the right side instead of the left side dependent on the label width.
Closes #6237.
The `UseCheckBox` argument is removed and instead `pCheckBoxValue != nullptr` is used.
=> Align color picker buttons on right side

src/game/client/components/chat.cpp, src/game/client/components/chat.h, src/game/client/components/menus_settings.cpp
=> Fix client crash when echoing client message to chat, use em dash for client messages in chat like on upstream

src/base/color.h, src/engine/console.rs, src/engine/shared/console.cpp
In addition to values in `$RGB` and `$RRGGBB` format, also support the `$RGBA` and `$RRGGBBAA` formats for color variables.
=> Support 4 and 8 digit RGBA color values in console

src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/game/client/components/console.cpp, src/game/client/components/menus_settings.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h
clearify difference between resize and window property change for resolution list
for: " Maybe we can at least fix this for 16.8 so the crash is no longer triggered by minimizing/maximizing and only by resizing." from https://github.com/ddnet/ddnet/pull/6358#issuecomment-1445046002
Only partially quickly tested.
=> Only call onresize events if actual size changed

src/game/client/ui_scrollregion.cpp, src/game/client/ui_scrollregion.h
Remember the maximum animation time when initiating a smooth scroll, so the smooth scrolling does not change erratically when `ui_smooth_scroll_time` is changed while smooth scrolling is in progress.
=> Fix erratic smooth scrolling when scroll time is changed

src/game/client/components/menus_ingame.cpp
The maximum width for the server info and game info text was too small, which previously didn't matter, because the manual newlines broke text wrapping in this case, but with the fix from #6353 this now causes the text to break after the colons already.
This is fixed by using the maximum available width for the text instead of a too small magic number (`250.0f`).
For completeness, the maximum width for the title texts is unset (`-1.0f`), because they should never wrap, which is consistent with the MOTD title text.
Before:
After:
=> Fix incorrect text wrapping in ingame server info

src/game/client/components/chat.cpp
The graphics are not initialised when `RebuildChat` is called by `ConchainChatOld`, which causes the client to crash if `cl_chat_old` is present in the user's config or used as a command line argument.
=> Fix client crash when `cl_chat_old` config is used

.github/workflows/style.yml
`warning: redirecting to https://gitlab.com/Patiga/twmap.git/`
=> Fix warning in CI when cloning twmap from GitLab

src/engine/server/main.cpp
before:
```
$ ./DDNet-Server 'logfile "invalid/path.txt"' | grep failed
2023-03-02 09:43:37 I client: failed to open 'invalid/path.txt' for logging
```
after:
```
$ ./DDNet-Server 'logfile "invalid/path.txt"' | grep failed
2023-03-02 09:43:55 I server: failed to open 'invalid/path.txt' for logging
```
:exploding_head:
=> Fix server logfile error message

src/game/editor/editor.cpp, src/game/editor/popups.cpp
=> Fix opening file in editor with enter not working after searching, disable editor file browser hotkeys while another popup is open

src/engine/client/client.cpp, src/engine/server/server.cpp
The client measures the time difference between
ping send and ping reply receive.
Without MSGFLAG_FLUSH the server keeps the chunk
until the next flush which makes the ping dependend on when the next flush happens.
Cherry-picked from teeworlds/teeworlds#3194.
=> Flush `NETMSG_PING` and `NETMSG_PING_REPLY`

src/game/editor/editor.cpp
Prevent editor popups (quad point, quad pivot, sound source) from being opened while the editor GUI is hidden. The opened popups would not be visible, which results in multiple identical popups being opened at the same time. This cannot happen while the GUI is shown, as the already opened popup takes focus so no second identical popup can be opened at the same time.
Additionally, all opened popups are now closed when the GUI is hidden. Otherwise this results in crashes, as the already opened popups reference the current layer and quad selection, which can change or become invalidated while the GUI is hidden.
Closes #6383.
=> Close editor popups and prevent popups from opening when GUI hidden

src/game/editor/editor.cpp
=> Revert editor changes to popup menus, so popup menus are shown also when GUI is hidden

src/game/editor/editor.cpp
The "Custom Zoom" property was not initialized when creating a new layer group, leading to the property editor not working correctly and an undefined value being saved to the map file.
=> Add missing default value for custom parallax zoom property

CMakeLists.txt
Seems to be needed only for MinGW/Unix Makefiles generator.
Note: ninja (and probably some other build systems) does not allow us to add extra `DDNet` target because it already builds a file with that name. At the same time, CMake alias targets are not propagated to Makefile.
=> CMake: Add targets to allow (previously available) build by exec name

src/tools/map_replace_area.cpp
Fixes the following error on Haiku:
```
~/ddnet/build> ninja
[5/8] Building CXX object CMakeFiles/m...a.dir/src/tools/map_replace_area.cpp.o
FAILED: CMakeFiles/map_replace_area.dir/src/tools/map_replace_area.cpp.o
/bin/c++ -DCONF_INFORM_UPDATE -DCONF_OPENSSL -DCONF_VIDEORECORDER -DGAME_RELEASE_VERSION=\"16.8\" -DGLEW_STATIC -I/boot/home/ddnet/build/src -I/boot/home/ddnet/src -I/boot/home/ddnet/src/ru>
/boot/home/ddnet/src/tools/map_replace_area.cpp: In function 'void SetExtendedArea(MapObject&)':
/boot/home/ddnet/src/tools/map_replace_area.cpp:502:33: error: 'memcpy' was not declared in this scope
502 |                                 memcpy(Ob.m_aaExtendedArea[i], aInspectedArea, sizeof(float[2]));
|                                 ^~~~~~ …
```
=> Replace leftover `memcpy` with `mem_copy`

src/engine/shared/websockets.cpp
Replace all remaining usages of `memcpy`.
=> Use `mem_copy` instead of `memcpy` for websockets

other/vim/syntax/ddnet-cfg.vim
=> Remove fatal space from vim syntax

src/engine/client/text.cpp, src/engine/textrender.h, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_ingame.cpp, src/game/client/components/motd.cpp, src/game/client/components/motd.h
Optimize MOTD rendering by caching the round rect and the text.
Use the correct text height based on the aligned font size instead of the original font size, to fix the discrepancy between the scrollable height and the text height. Closes #6346.
Screenshots:
- Tutorial, ingame:
- Before: 
- After:
- Multeasymap, ingame:
- Before: 
- After:
- Test server, ingame:
- Before: 
- After: 
- Long, ingame:
- Before: 
- After:
- Long, menu:
- Before: 
- After:
=> Use text and quad containers for MOTD rendering, fix MOTD height calculation

src/engine/client/video.cpp
=> Fix deprecation warning in ffmpeg 6 (fixes #6398)

src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h
Encoding the image as PNG and saving it to a file comprises the majority of the time when taking a screenshot.
To avoid the client freezing while a screenshot is being saved, this task is moved to a separate background thread.
=> Save screenshot in separate thread to avoid lags

scripts/parse_drmingw.sh
- Also handle newer Dr.Mingw trace format where relative addresses are already resolved, as some crash logs may not contain the list of module addresses and versions.
- Add more parameters to `addr2line` invocation to print addresses, pretty-print, print function names, demangle, and resolve inlined functions.
- Strip absolute prefix of source paths, so the paths all starts at `src/`, to improve readability.
=> Streamline `parse_drmingw.sh`

src/game/editor/editor.cpp
When pasting text containing multiple consecutive (back)slashes in the editor save dialog not all slashes where removed. For example with the text `/a//bb/\/ccc////dddd//\//`.
=> Fix slash removal when multiple slashes are pasted in editor

src/game/editor/editor.cpp, src/game/editor/editor.h
As suggested in #4508 it would be nice to have at least some basic sorting ability in the filedialog. This PR implements at least the two most important sorting criteria: filename and time modified. Also the time modified is now displayed.
At the moment the characters ▲ and ▼ are used to indicate the sorting direction. Maybe there is a nicer way to display this.
=> add sorting by name and time modified to filedialog

src/game/editor/layer_tiles.cpp
See #5908. As far as I can tell this function is only used in the popup, so this should not break anything.
=> ignore tiles that dont use ids in ContainsElementWithId

src/game/client/ui_scrollregion.cpp, src/game/client/ui_scrollregion.h
Add `ScrollRelative` function to initiate relative scrolling programmatically, to realise scroll regions that scroll when the mouse is being dragged at the edge.
Add `DoEdgeScrolling` to encapsulate all the necessary edge scrolling logic based on the position of the mouse. The edge scrolling starts at a fixed distance from the edges. The scrolling speed is dependent on the distance of the mouse from this border.
=> Extend `CScrollRegion` to support scrolling when mouse at edge

src/game/client/components/console.cpp
Don't add entered command to console history, if the last console history entry is identical to this command. For example, entering the commands `1`, `2`, `3`, `3`, `2`, `1` adds 5 entries to the history, i.e. only one entry for the command `3`.
=> Don't add duplicate consecutive commands to console history

src/game/client/components/menus_settings.cpp
When the tee color lighting is set to 0, the blood color was shown as black instead of the actual tee blood color. The blood color used ingame is already correct and now matches the color shown in the settings.
=> Fix incorrect tee blood color being shown in settings

scripts/git_revision.py
Use the `DDNET_GIT_SHORTREV_HASH` variable for this. This allows builds that do not use `git` to still have this kind of version information.
=> scripts/git_revision.py: Allow to pass in the git shortrev

src/game/server/entities/pickup.cpp
For 0.7 clients the client version is not `VERSION_NONE`, so `IsSixup` was never called for them, which leads to version 0.6 pickups being snapped for 0.7 clients. This causes snapshot CRC errors for the 0.7 clients, as the 0.6 and 0.7 pickup structs have different sizes.
Now the version is no longer checked before calling `IsSixup`, which is the case in all other locations where the function is called and was also the case before this bug was introduced by #6330.
=> Fix incorrect sixup detection when snapping pickups

src/engine/client/input.cpp
The console chain was broken due to `joystick_guid` being renamed to `inp_controller_guid`, so the active controller was not being updated when the GUID is changed via the console.
=> Fix console chain of `inp_controller_guid`

src/base/system.cpp, src/test/str.cpp
Some servers seem to allow times with millisecond precision, official DDNet doesn't, so never noticed this issue.
=> Round by millisecond, not centisecond (fixes #6453)

src/game/client/components/chat.cpp
Main and dummy tee cannot ping each other anymore. Other main and dummy tees can still ping your own main and dummy tees.
We must ensure to only use `m_aLocalIDs[1]` when the dummy is connected, as this ID is not updated when no dummy is connected, so it can refer to another client if you disconnect your dummy and another client subsequently takes its client ID.
Closes #3699.
=> Fix dummy tee being able to ping main tee in chat

src/engine/shared/storage.cpp, src/engine/storage.h, src/game/editor/editor.cpp
To delete files and empty folders from the user's save directory.
Only files and folders from the user's save directory can be deleted. Only empty folders can be deleted.
Error message popups are shown when the deletion fails.
Closes #6272.
Screenshots:
- ![screenshot_2023-03-25_16-54-58](https://user-images.githubusercontent.com/23437060/227728748-c13e7283-289f-47ee-a34b-c42407b5bd2b.png)
- ![screenshot_2023-03-25_16-55-05](https://user-images.githubusercontent.com/23437060/227728750-fb5246f1-35c2-4834-b71f-4e3b5782664f.png)
- ![screenshot_2023-03-25_16-55-26](https://user-images.githubusercontent.com/23437060/227728749-842a00d0-0dec-4671-aa1f-9d110defb0d4.png)
=> Add "Delete" button to editor file browser

src/game/client/components/menus.h, src/game/client/components/menus_settings.cpp, src/game/client/components/skins.cpp, src/game/client/components/skins.h
Adds a button for generating a random skin in tee settings. The logic generates handsome tees more often than not.
Intentionally didn't add a console command so it's not possible to make annoying skin change binds with this.
=> Add random skin button

src/game/client/components/motd.cpp
Seems like there are cases where the texture is not cleared when the MOTD background is rendered, so part of the font texture is used for the round rect.
=> Ensure texture is cleared when rendering MOTD background

src/engine/shared/http.cpp
It's possible for the HTTP request task to be aborted after the curl request has finished, so the returned `State` will be `HTTP_DONE` but `m_Abort` is `true`. The `State` never changes to `HTTP_ABORTED`, because the progress callback is not called after the HTTP request has completed.
This causes the client to crash when a skin download is aborted after the HTTP request finished but before the completion callback is called.
This is fixed by checking if `m_Abort` is `true` and setting the `State` to `HTTP_ABORTED` at the beginning of the completion callback.
Closes #3567.
=> Check if HTTP request task is aborted in completion callback

src/engine/client/client.cpp, src/engine/client/client.h
When connecting a dummy and then logging into rcon only the dummy is logged in. When disconnecting the dummy, the main client was not automatically logged in. When logging in with the main client and then connecting the dummy, the dummy was already authenticated automatically. Now the main client is also authenticated automatically when disconnecting an authenticated dummy.
This automatic authentication was also not working correctly if the login used a username, as only the password was stored. Now both username and password are stored to correctly authenticate the main or dummy client.
The stored username and password are completely cleared when disconnecting, so they are not stored in memory longer than necessary.
Closes #5586.
=> Fix rcon login when disconnecting dummy and when username used

src/engine/shared/config_variables.h, src/engine/shared/console.cpp
=> Fix `console_enable_colors` not being used, save `console_output_level` and `console_enable_colors` variables

src/game/client/prediction/entities/character.cpp, src/game/server/entities/character.cpp
Fixes #6464
This was regressed by #6246 by the wrong transformation of `if(!m_FreezeTime)` to `if(m_FreezeTime != 0)` instead of the correct `if(m_FreezeTime == 0)`.
And take additional measure to never set m_FreezeTime to a negative number in client prediction code.
=> Fix ninja not getting predicted

src/game/editor/editor.cpp
When dragging a layer up, the wrong layer is selected after. Should be merged before #6467.
=> update selected group correctly after dragging

src/game/client/components/effects.cpp
fixes [this](https://github.com/ddnet/ddnet/pull/6439/files/a9ef757475b628d16ea5226c9d628757775c6781#diff-7e0a2abd9e284b400b03e461e21bd5b789b83afa10478be5d01d222a7af2daa4R91)
and [this](https://github.com/ddnet/ddnet/pull/6439/files/a9ef757475b628d16ea5226c9d628757775c6781#diff-7e0a2abd9e284b400b03e461e21bd5b789b83afa10478be5d01d222a7af2daa4R209)
=> fix start size of freezing flakes particles

src/engine/client/client.cpp, src/engine/client/client.h, src/engine/server/server.cpp, src/engine/shared/econ.cpp
=> Quit when configured bindaddr cannot be resolved, quit client when failing to open network client for 25 times 

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
When an image/sound is readded, this reuses the `ReplaceImage/Sound` callback functions. The added error handling to prevent duplicate images/sounds was causing this to not work, as the image/sound being readded was already present. The implementation is separated from the callback functions and an additional parameter is added to toggle the duplicate name check.
Previously this was hard to notice, as the error message popup was not shown due to the top-most popup being closed immediately. This will be fixed separately by a larger refactoring, so a popup can close itself immediately after opening another popup without closing the child popup instead.
Closes #6500.
=> Fix image/sound readding broken by error messages

src/game/client/components/menus.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/tooltips.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/editor/editor.cpp, src/game/editor/popups.cpp
Move "Map details" button from editor file browser to file menu.
Decrease button spacing in editor file browser when screen width is low (4:3 and 5:4 resolutions).
Screenshots:
- File menu:
- Before: 
- After:
- File browser (800x600):
- Before:
- After:
- File browser (1280x1024):
- Before:
- After:
- File browser (1920x1080):
- Before:
- After:
=> Improve editor file browser button layout when screen width is low

src/game/client/components/menus.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/layer_game.cpp, src/game/editor/layer_quads.cpp, src/game/editor/layer_sounds.cpp, src/game/editor/layer_tiles.cpp, src/game/editor/popups.cpp
Support using editor popup rendering in game client.
Support unlimited number of popup menus instead of maximum of 8.
Fix non-active popups handling key events. Add `Active` parameter to popup function, so key events are only processed by the active (top-most) popup. Previously the "New folder" popup could be confirmed with enter while an error message is shown, which causes multiple error messages to stack.
Allow popups to close without closing their child popups. Previously a popup could not open another popup and close itself immediately afterwards, as this was causing the newly opened popup to be closed instead.
Support using return/enter keys to confirm binary choice popups and to close message popups for more convenient usage.
=> Move generic popup handling to UI (port from editor and upstream)

src/game/client/components/chat.cpp
The calculation of `m_LongestLineWidth` was adjusted in bf1e757581e7b37c7de493ae48b074ccb6a9eff5 so it's really the width of the line and not the X position of the end of the line. This caused the background rects of chat messages to be rendered incorrectly.
Screenshots:
- Normal
- Before: ![screenshot_2023-04-15_11-56-38](https://user-images.githubusercontent.com/23437060/232208095-cc2ace57-244e-4345-b489-36a4bb70b6a7.png)
- After: ![screenshot_2023-04-15_12-18-07](https://user-images.githubusercontent.com/23437060/232208119-cff59371-ef05-400f-9d32-8f9f335d05c4.png)
- With scoreboard open:
- Before: ![screenshot_2023-04-15_11-56-41](https://user-images.githubusercontent.com/23437060/232208257-6bb54471-d746-43f1-a248-98576183ae64.png)
- After: …
=> Fix incorrect chat background rect width calculation

CMakeLists.txt, src/base/system.cpp, src/base/system.h, src/engine/client/client.cpp, src/engine/client/input.cpp, src/engine/client/input.h, src/engine/client/text.cpp, src/engine/input.h, src/engine/textrender.h, src/game/client/components/chat.cpp, src/game/client/components/chat.h, src/game/client/components/console.cpp, src/game/client/components/console.h, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings_assets.cpp, src/game/client/gameclient.cpp, src/game/client/lineinput.cpp, src/game/client/lineinput.h, src/game/client/ui.cpp, src/game/client/ui.h, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp, src/test/str.cpp
Port the line input (UI edit boxes, chat, console) and Input Method Editor (IME) support from upstream. Closes #4397.
General
------------------------------
Fix issues with the text input. Closes #4346. Closes #4524.
Word skipping (when holding Ctrl) is overhauled to be consistent with the Windows / Firefox experience that I took as reference.
Improve usability by not blinking (i.e. always rendering) the caret shortly after is has been moved.
UI text input
------------------------------
https://user-images.githubusercontent.com/23437060/233841419-6648ea97-3ccd-464b-a4c5-e6e5b8dde01c.mp4
Fix inconsistent mouse-based left and right scrolling (closes #4347).
Support smooth left and right scrolling.
Chat
------------------------------ …
=> Port line input and IME support from 0.7

src/engine/client/input.cpp
Since we want to upgrade SDL version.
SDL fixed the bug on Windows that releasing the mouse while tabbing out directly refocuses the window, which broke desktop fullscreen (and maybe windowed fullscreen)
=> Fix input as the comments suggest for the next SDL version

src/game/client/components/maplayers.cpp, src/game/client/render_map.cpp, src/game/collision.cpp, src/game/collision.h, src/game/editor/editor.h, src/game/editor/io.cpp, src/game/editor/layer_tiles.cpp, src/game/mapitems.cpp, src/game/mapitems.h
=> Don't render switch number and delay for tiles where they are unused, ignore switch tiles that don't use number for free slot finder, refactoring

src/game/client/components/killmessages.cpp, src/game/client/components/killmessages.h
The client crashes when a team kill message specifies a team for which no client can be found. This can easily happen when the server sends an unknown team on purpose. It may also happen sporadically during normal gameplay, assuming a team is dissolved or the last team member leaves at the same time as the kill message is received.
The crash is fixed by not rendering any tee for these kill messages. The kill message text is always set depending on the team number in the team kill message, regardless of whether the team exists.
Closes #6533.
=> Fix client crash on team kill message with invalid team

src/engine/client/client.cpp
The `Disconnect` function did not fully clear all server data, because the client state was already set to offline manually before the function is called. This was causing inconsistent behavior when connecting to another server after being disconnected. For example, the client could get stuck at "getting game info" when connecting the next time.
=> Fix inconsistent client state after disconnecting with network error

src/engine/client/client.cpp, src/engine/server/main.cpp, src/engine/shared/assertion_logger.cpp
@def- what do you think, how hard would it be for the symbols uploaded to the website contain the same git hash in the name, so we could write a script that automatically finds the correct binary and creates a stack trace?
=> Add the DDNet git hash and "is steam" to the crash file

src/game/editor/editor.cpp, src/game/editor/editor.h
=> adjust corners of Button_Env

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/lineinput.h
=> Fix server password input not being activated automatically, always move cursor to end when selecting all text

src/game/client/components/broadcast.cpp, src/game/client/components/broadcast.h, src/game/client/components/hud.cpp
Before (centering):
After (centering):
Before (wrapping):
After (wrapping):
=> Broadcast: fade out in last second, wrap long text instead of stopping, fix horizontal centering

src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h, src/engine/client/client.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h
=> Only show assertion popup for assertions on main thread, destroy window before showing popup if graphics initialized 

src/engine/client/client.cpp
Fixes a issue where ddnet freezes on resize on macos
=> set SDL_MAC_OPENGL_ASYNC_DISPATCH sdl hint to fix macos resizing

src/game/client/components/hud.cpp, src/game/gamecore.cpp, src/game/server/entities/projectile.cpp
=> Replace usages of `atan2f` and `atan2` with `std::atan2`

src/game/client/components/damageind.cpp, src/game/client/components/damageind.h, src/game/client/components/effects.cpp, src/game/client/components/effects.h, src/game/client/components/items.cpp, src/game/client/components/nameplates.cpp, src/game/client/components/players.cpp, src/game/client/gameclient.cpp
There are some things like damage indicator, spawn particles, etc which we have no way to properly set alpha based on team/solo knowledge because they don't have any info about that. (to my knowledge)
Fixes #6520
=> Fix cl_show_others_alpha not used in places where it can be

src/engine/client/client.cpp
Register SDL for cleanup before creating the kernel and client, so SDL is shutdown after kernel and client. Otherwise the client may crash when shutting down after SDL is already shutdown.
Closes #6581.
=> Shutdown SDL after kernel and client

.github/workflows/clang-sanitizer.yml
The ASan/UBSan logs are currently only printed in the CI log when launching the client and server once.
Now the logs are also printed when the unit or integration tests fail due to a sanitizer crash.
A redundant definition of an environment variable is removed.
=> Show ASan/UBSan logs in CI also for unit and integration tests

src/engine/client/client.cpp, src/engine/client/client.h
When a client component (e.g. the menu or the console) disconnects the client, this immediately unloads the map data but the render call continues as normal. This causes all components rendered after this component to access invalid memory in place of the map, layers and collision data.
This is fixed by delaying the actual disconnecting until after the render call, to ensure that the map data can be safely unloaded.
Closes #6387. Closes #3179.
=> Delay disconnecting until after render call

src/engine/client/client.cpp
=> Fix check for changed `os_version_str` return value

src/game/editor/editor.cpp
The modified time was uninitialized for the editor file browser entry corresponding to the downloadedmaps-link. The time is never rendered for links, but the uninitialized time value was still passed to `str_timestamp_ex`, which results in an assertion error due to an incorrect time value being used when compiling with MSVC.
This is fixed by properly initializing the field and also by only calling `str_timestamp_ex` when the time value will be rendered.
Closes #6579.
=> Fix uninitialized field causing assertion error with MSVC

src/engine/client/client.cpp
Why did we allow connecting dummy in state pending? Maybe because state online did not match because the wrong enum was used?
```C++
int CNetClient::State()
{
if(m_Connection.State() == NET_CONNSTATE_ONLINE)
return NETSTATE_ONLINE;
if(m_Connection.State() == NET_CONNSTATE_OFFLINE)
return NETSTATE_OFFLINE;
return NETSTATE_CONNECTING;
}
```
We map from NET_CONNSTATE_  to NETSTATE_ so it should also be compared against NETSTATE_
=> Compare against correct enum in dummy connect

src/game/server/gamemodes/DDRace.cpp
not sure if this is the fix, but -9999 is wrong, and -1 is set on reset
=> try to fix broken score

src/engine/client/client.cpp, src/engine/client/client.h
This reverts commit 5c90fd2b8324bdbe89331bf1c819bca4b16f391a.
Delaying the disconnecting causes issues when the client automatically disconnects immediately before connecting to another server or starting demo playback.
It's not necessary to delay the disconnecting to deal with #6387, as #6589 is already enough. It's easier to revert this instead of rewriting the client so connecting and starting demo playback are also delayed.
Closes #6595.
=> Revert "Delay disconnecting until after render call"

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
The entities and unused buttons are now in a new "Settings" menu.
The border and goto buttons got moved to the "Tools" menu.
=> move some editor buttons into menus

src/engine/textrender.h, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp
Separate friends list into three groups, which can be expanded and collapsed: online players, online clanmates and offline friends.
Friends with the same name/clan are no longer grouped together. Instead, each individual player that is online and has name/clan matching a friend is shown in either the online players or online clanmates group. Friends for which no matching players are found are shown in the offline group.
Friends in the friend list can no longer be selected. Instead, left-clicking a friend selects the server that the friend is on. Double-clicking a friend joins the server that they are playing on.
Render small X button in top-right corner of every friend list entry to remove the respective friend instead of using one button that removes the selected friend.
Change "Add …
=> Port friends list UI from 0.7

src/game/server/player.cpp, src/game/server/player.h, src/game/server/scoreworker.cpp, src/game/server/scoreworker.h, src/game/server/teams.cpp, src/test/score.cpp
Fixes the time displayed, this time i tested it quite thoroughly, i could reproduce the wrong ordering in scoreboard and the time not updating before, and fixed it now.
The previous way also had a issue with times that ended up with a value of -1, which is fixed now too
=> fix timescore

src/game/ddracechat.h, src/game/server/ddracechat.cpp, src/game/server/gamecontext.h
Related: https://github.com/ddnet/ddnet/issues/6318#issuecomment-1498626132 and #2391
Unsolo is often needed especially in maps with death tiles and solo part spawns, undeep can also be useful for some parts.
Some notes:
- didn't use `CFGFLAG_SERVER` for the commands as it resulted in a conflict with the registered `unsolo` and `undeep` super team console commands, not entirely sure if that's okay
- `/help unsolo` and `/help undeep` will print the help text of the super team commands, not the new chat commands. The texts are currently the same, but it's still a sign of possible conflicts
- prevented `/unsolo` on solo servers by checking for `SV_TEAM_FORBIDDEN` and `SV_TEAM_FORCED_SOLO`, let me know if that's not enough (Tutorial map?)
- no server message is sent on `/unsolo` (as opposed …
=> Add /unsolo and /undeep practice commands

src/game/client/components/menus.h
=> Remove unused `CMenus::DoToolTip` declaration

src/engine/server/server.cpp, src/engine/shared/config_variables.h
=> Remove unused `sv_sql_bindaddr` config variable

src/game/client/components/hud.cpp
Crash from assertion error reported on Discord.
=> Fix use of invalid text container index for finish message HUD

src/game/client/components/menus_browser.cpp
=> Use different color for offline clanmates in friends list

src/game/editor/layer_tiles.cpp
=> Fix filling switch layer not setting switch number 0, clear unused switch/tele properties when filling selection

src/game/server/gamecontext.cpp
CClientMask has size MAX_CLIENTS, so it can't be used for super team
=> Fix crash with super (fixes #6654)

src/game/server/entities/dragger.cpp
There is another member variable `CDragger::m_aTargetIdInTeam` that contains for every team the client ID of the team member currently being dragged by this dragger.
The client IDs in this array also need to be swapped accordingly or the dragger will not switch target correctly when swapping.
Closes #5865.
=> Fix incorrect swapping with draggers

src/engine/client/backend_sdl.cpp, src/engine/shared/config_variables.h, src/game/client/components/menus_settings.cpp
Because it causes trouble with [newer SDL2 versions](https://github.com/libsdl-org/SDL/issues/7159)
Probably is also easier if we don't have to debug this, it's a hack anyway (teleporting the cursor).
=> Remove inp_mouseold config

src/game/client/lineinput.cpp
Also delete the lineinput selection when pressing backspace/delete and the key for skipping words (Ctrl/GUI key, Alt on macOS) is held. This is consistent with the behavior in other applications.
=> Delete selection with backspace/delete regardless of word mode

src/game/client/lineinput.cpp, src/game/client/lineinput.h
Check if the active line input was not rendered and deactivate it in that case.
This can happen e.g. when an input in the ingame menu is active and the menu is closed or when switching between menu and editor with an active input.
This was causing the IME candidate list to be rendered ingame after closing the menu. Closes #6666.
=> Ensure line inputs are deactivated when they are not rendered

src/game/client/components/killmessages.cpp
fixes #6662
This should fix the issue, I guess, by simply clearing the render info. I can't find an easy way to restore the original skins of the team members as we don't save their IDs.
I couldn't directly trigger the assert, but I could certainly see the skin getting invalid when killen the team and switch to "vanilla only skins". (Edit: When triggering it a few times I got the assert)
The code generally looks a bit hacky. Maybe the original author can refactor it a bit
=> Clear Victim Team render info on skin changes

src/engine/shared/snapshot.cpp
Cast `int`s to `unsigned` before subtracting to ensure that integer wrapping is being used instead of causing undefined behavior. Same as in `UndiffItem`.
```
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/master/src/base/math.h:16:40 in
src/master/src/engine/shared/snapshot.cpp:206:21: runtime error: signed integer overflow: 256 - -2147483648 cannot be represented in type 'int'
0 0x7650b7 in CSnapshotDelta::DiffItem(int const*, int const*, int*, int) src/master/src/engine/shared/snapshot.cpp:206:21
1 0x765cea in CSnapshotDelta::CreateDelta(CSnapshot*, CSnapshot*, void*) src/master/src/engine/shared/snapshot.cpp:323:7
2 0x51a0e2 in CServer::DoSnapshot() src/master/src/engine/server/server.cpp:964:36
3 0x537486 in CServer::Run() src/master/src/engine/server/server.cpp:2818:6
4 …
```
=> Fix undefined behavior in `CSnapshotDelta::DiffItem`

src/engine/textrender.h, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/ui.cpp, src/game/client/ui.h
Use less space for refresh and connect buttons to improve layout with 5:4 and 4:3 resolutions. Closes #5605. Closes #5878.
The "Refreshing..." text is replaced with combined refresh and ellipsis icons.
Alpha and saturation of the green color of the connect button are increased.
Move `CMenus::DoButtonMenu` to `CUI::DoButton_Menu`. Simplify usage by adding `SMenuButtonProperties` parameter object for all optional arguments. Remove unused `ColorHot` parameter.
Screenshots:
- Before:
- After:
- After (when refreshing):
=> Use icons for refresh and connect buttons, refactor `DoButtonMenu`

src/game/client/components/menus.cpp
Renaming a demo to the name of another demo would overwrite the target demo. Now an error message popup is shown instead to prevent this.
After a demo rename error popup is shown, return to the demo rename popup instead of closing the popup.
=> Show error instead of replacing existing demo when renaming

src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp, src/game/client/ui.cpp
Show begin time, end time and length of demo cut in popup.
Replace demo slice error/confirm messages with generic popups.
Improve layout. Remove unnecessary empty space.
Screenshots:
- Popup:
- Before:
- After:
- Error:
- Before:
- After:
- Confirm:
- Before:
- After:
=> Improve demo slice popup

src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp
=> Use X icon for demo close button, remove `DoButton_DemoPlayer`

src/engine/client/serverbrowser.cpp
I thought there was initially a strict weak ordering issue here but upon further inspection noticed it's fine.
However, people with negative score were getting sorted undeterministically, basically every unfinished tee was treated as equal since `!comp(a, b) && !comp(b, a)`. Sorting them by name was the intention.
I also got rid of the old `INT_MIN` "hack", it was only there to make the code shorter and it's no longer possible with the newly flipped sign without flipping it back on the client which is ugly.
Also made `ScoreKind` `const`, not sure if any compiler optimizes on that but why not? If we ever move to C++20 this could be a generic lambda instead where we can template `ScoreKind` and make sure it gets optimized properly.
Tidbit: I treated score 0 as a normal score, I'm not sure …
=> Fix ordering of unfinished/unconnected tees

src/engine/client/backend_sdl.cpp
Minimum SDL version 2.0.16 is required for `SDL_FlashWindow`. The SDL version schema changes after version 2.0.22 to 2.24.0 etc. (minor version is used instead of patchlevel) which was causing the condition that checks for minimum version 2.0.16 to not work correctly with newer SDL versions.
Closes #6687.
=> Fix flashing window not working with newer SDL versions

src/game/client/gameclient.cpp, src/game/client/prediction/gameworld.cpp, src/game/client/prediction/gameworld.h, src/game/server/gamecontroller.cpp
Fixes #6644 by sending switch state for team 0 on sv_solo_server 1 to match the team of the clients own character, and by not predicting other characters/entities when in solo.
=> Fix switch prediction on solo server

src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/config_variables.h
The password for the reserved slots keep getting leaked. Hopefully this will fix the issue.
=> Allow rcon users access to reserved slots

src/game/client/components/menus_browser.cpp
Otherwise the tab is completely empty when no server is selected.
=> Add "No server selected" message to server details

src/game/server/entities/dragger.cpp, src/game/server/entities/dragger.h, src/game/server/entities/dragger_beam.cpp
These are some things i noticed could be improved while attempting to add prediction for draggers:
Sets dragger owner to be the dragged player (this also means alpha will be applied).
It also ensures that the dragger that is sent for the players own team always has the same netobject id, and additionally that an idle dragger is always sent if no one in the players owns team is dragged (before it used to be that an idle dragger wasn't sent if _any_ player was dragged, including other teams visible to the player). The first one helps with keeping track of the dragger between snapshots (and simplifies prediction), while the second one ensures that a player still sees a dragger after show_other_alpha is applied to other teams.
Also fixes snapped order of to/from pos.
=> Improve snapping of draggers

src/engine/server/server.cpp
=> Allow `username:password` for reserved slots

src/engine/client/text.cpp, src/game/client/components/killmessages.cpp
Kill is a temporary variable, that's why the indices were dropped without notice
fixes #5143
also reverted the hacks.
i guess we can keep 493f47515c556472f3d009e18b47655e2f8ba9fb for now, it at least gives a hint to find such stuff
_**we should also release a new patch version with this**_
=> Fix killmessages might drop text container indices, if a killmsg was invalid

src/game/editor/editor.cpp, src/game/editor/editor.h
Same as for the envelope editor. Extract `RenderExtraEditorDragBar` function to reduce duplicate code.
Fix height being changed by repeated clicking on the draggable element by also resetting `s_Operation` when `Clicked` is `true`.
=> Make server settings editor height adjustable by dragging

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp, src/game/client/components/tooltips.cpp, src/game/client/components/tooltips.h
Allow dragging the demo player controls anywhere on the screen. The controls can't be moved outside of the screen. Round corners are automatically disabled when the controls are on the edge of the screen.
https://github.com/ddnet/ddnet/assets/23437060/72510c1f-4fd2-426b-a631-3a78db5f7b8b
=> Support dragging demo player controls to move them, fix minor related issues

src/game/client/components/menus.cpp
Popup menus should be closed before escape is used to navigate back to the start menu.
=> Handle escape to go to start menu after popup menus

src/game/client/ui.cpp
Prevent highlighting when edit box hovered but behind a popup menu.
=> Only highlight hovered edit boxes when they are the hot item

src/game/client/ui.cpp, src/game/client/ui.h
It was incorrectly checked for `UIElement.Rect(0)->m_Y != pRect->h`, so any UI rect using `m_HintCanChangePositionOrSize` would be updated every frame (although, no UI element currently uses this hint).
Additionally, checks for changed rounding size and corners are added so UI elements are updated when those are changed.
=> Fix UI element check with `m_HintCanChangePositionOrSize`

src/base/color.h, src/test/color.cpp
=> Fix `color_cast` between `ColorHSLA` and `ColorHSVA` losing alpha, add test

src/game/client/lineinput.cpp
Set input string if it's not identical to the real input string instead of comparing to the display string, which would be incorrect for hidden number inputs.
=> Use real instead of display string for number line inputs

src/base/system.cpp, src/base/system.h, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_settings.cpp, src/game/client/lineinput.cpp, src/game/client/lineinput.h, src/game/client/ui.cpp, src/game/client/ui.h, src/game/editor/editor.cpp, src/game/editor/editor.h
Use the popup system ported from the editor to reimplement the color picker popup.
- Before: 
- After:
Remove special handling necessary for the hard-coded color picker.
Add alpha support to the color picker popup.
Support locking mouse position when dragging value selectors also in menus (color pickers), which improves usability of value selectors. Previously this was only supported in the editor.
Replace large HSLA scrollbar color picker for UI color setting with inline color picker popup:
- Before:
- After:
=> Improve color picker popup in settings (use new popup system, add alpha support, support mouse locking)

src/game/server/gamecontext.cpp, src/game/variables.h
The server normally needs to be reloaded to spawn the debug dummies, so this code was not checking if a debug dummy player exists. Decreasing the number of debug dummies while the server is running also causes them to simply not be snapped instead of completely destroying them.
For debugging any number of dummies can be useful, so the maximum number of debug dummies is increased to the maximum number of clients.
See #6702.
=> Fix crash when enabling `dbg_dummies` on running server

src/game/client/components/countryflags.cpp, src/game/client/components/countryflags.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/scoreboard.cpp
Pass color by value instead of pointer to simplify usage.
Add separate function that accepts a country flag directly instead of an index.
=> Improve usage of `CCountryFlags::Render` function

src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_settings.cpp, src/game/client/ui_listbox.cpp, src/game/client/ui_listbox.h, src/game/client/ui_scrollregion.cpp, src/game/client/ui_scrollregion.h, src/game/editor/editor.cpp
Store the list box active state inside `CListBox` instead of tracking it separately with a pointer.
Allow activating list boxes by clicking the scrollbar. Previously it was only possible to activate list boxes by selecting an item.
Fix country selection list box in players settings not being deactivated properly when name/clan edit boxes are active, because wrong UI element IDs were being used.
Fix highlighting of menu tab buttons while popup open.
Fix highlighting of scroll region scroll bars while popup open.
=> Simplify list box activation handling, more highlighting fixes when popups are open

src/game/client/components/menus.cpp, src/game/client/components/menus_settings.cpp, src/game/client/ui.cpp, src/game/client/ui.h
Screenshots (not an exhaustive list):
- Controls settings:
- Before:
- After:
- Controls settings (5:4):
- Before:
- After:
- General settings:
- Before:
- After:
- Sound settings:
- Before:
- After:
- DDNet settings:
- Before:
- After:
=> Improve scrollbar option UI and settings, improve joystick settings UI especially on 5:4 and 4:3 resolutions 

src/game/server/player.cpp
The time of the last kick vote and the time of the last team change are initially in an undefined state, which causes the kick vote and team change to fail due to the delay incorrectly being applied.
Closes #6723.
=> Fix undefined player vote/team change time

src/game/client/animstate.cpp, src/game/client/animstate.h, src/game/client/components/chat.cpp, src/game/client/components/emoticon.cpp, src/game/client/components/hud.cpp, src/game/client/components/killmessages.cpp, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/players.cpp, src/game/client/components/players.h, src/game/client/components/scoreboard.cpp, src/game/client/components/spectator.cpp, src/game/client/components/statboard.cpp, src/game/client/render.cpp, src/game/client/render.h, src/game/client/skin.h
- Use `nullptr` instead of `0`.
- Remove dead code.
- Mark functions and pointers as `const` when possible.
- Remove unused argument of `CRenderTools::GetRenderTeeAnimScaleAndBaseSize` function.
- Copy tee render info when rendering emote wheel instead of modifying global render info.
- Fix names of static variables.
=> Minor refactoring of `CAnimState` and tee rendering functions

src/game/client/components/menus.cpp
The popup message has to be top- and not middle-aligned in some popups:
- First launch
- Existing player for nickname
- Warning
Likely a regression introduced by #6511.
Before:
After:
=> Fix top alignment of some popup messages

src/engine/shared/config_variables.h, src/game/server/entities/character.cpp, src/game/server/entities/character.h, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/player.cpp, src/game/server/player.h
The reason for this rather overcomplicated solution is, that emotes are send to other players all the time. But just sending it to nearby players only would not work as the emoticon does not track animation time.
So sending the emoticon later would restart the emote client side.
A different fix, which we obviously don't want, is breaking compability with all older clients and move the emoticon into the snapshot.
I also changed the config vars to use milliseconds instead of seconds. I did not use ticks, since ticks are not a clear enough time unit.
**It is not clear if this will fix all network lags, as there might be other packets that also are sent to all players globally**
global means:
send them less often than nearby, but still send them. this makes players that are close to you but …
=> Split emoticon sending into nearby and global players

src/game/editor/editor.cpp
=> Fix editor save dialog entries not selectable with mouse anymore

src/game/editor/auto_map.cpp, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/io.cpp, src/game/editor/layer_game.cpp, src/game/editor/layer_tiles.cpp, src/game/editor/popups.cpp
Use templated `str_copy` function in most cases to specify the correct buffer size.
Fixes two cases where the buffer size was hard-coded to a number.
Fix buffer size not being checked when copying auto mapper configuration name. Loading an auto mapper configuration with a name longer than 128 bytes could cause an out-of-bounds write.
Increase sizes of some text buffers that were potentially too small.
=> Refactor `str_copy` usages and buffer sizes in editor

src/game/editor/editor.cpp
This otherwise breaks file loading because the file extension is expected in this input buffer even when the input is not rendered.
Regression from #6736.
=> Don't remove the `.map` suffix in editor file dialog

src/base/system.cpp, src/base/system.h, src/engine/server/databases/connection_pool.cpp, src/engine/server/databases/connection_pool.h, src/engine/server/main.cpp
Otherwise the mysql thread can still be running in the background while we uninitialize it.
=> Run MysqlUninit later (fixes #6571)

src/game/editor/editor.cpp
=> Fix alignment of font icon buttons in editor, use font icon for editor proof mode selection button

src/game/client/lineinput.cpp
=> Fix uninitialized `CLineInput` member variables

src/engine/textrender.h, src/game/editor/editor.cpp
=> Show circle icon next to editor filename when there are unsaved changes, increase size of info in editor menu bar, show X/Y decimal places 
