src/base/system.cpp, src/base/system.h, src/game/editor/editor.cpp, src/test/fs.cpp
Which was causing the listbox selection to be cleared when activating the filename editbox, as the filename search expects names without the file extension.
Add `fs_split_file_extension` to separate filename and extension.
Add `fs_filename` to extract file/folder name from path. This commit is not required for this PR, but including it reduces conflicts with #6752 and #6763, which need this commit.
=> Fix editor save dialog filename showing file extension

src/game/editor/editor.cpp, src/game/editor/editor.h
=> Fix images/sounds not being loaded with correct file extension

src/engine/shared/datafile.cpp, src/engine/shared/datafile.h, src/engine/shared/storage.cpp, src/game/editor/auto_map.cpp, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/io.cpp, src/game/editor/layer_quads.cpp, src/game/editor/layer_sounds.cpp, src/game/editor/layer_tiles.cpp, src/game/editor/popups.cpp, src/game/variables.h
A copy of the map currently open in the editor is saved every 10 minutes to the `maps/auto` folder (interval configurable, see below). The automatically saved map uses the filename of the original map with an additional timestamp. Per map name 10 autosaves are kept in the `auto` folder before old autosaves will be deleted (number configurable, see below).
Add config variable `ed_autosave_interval` (0 - 240, default 10) to configure the interval in minutes at which a copy of the current editor map is automatically saved to the 'auto' folder.
Add config variable `ed_autosave_max` (0 - 1000, default 10) to configure the maximum number of autosaves that are kept per map name (0 = no limit).
Autosaving will not take place in the 5 seconds immediately after the map was last modified by the …
=> Autosave copy of current editor map periodically to `auto` folder, use separate thread to finish saving maps, add saving indicator

src/game/client/components/menus_demo.cpp
- Also skip to beginning and end when there are no demo markers. Previously the buttons to skip to the next/previous demo marker were skipping to the end/beginning respectively, if there is no next/previous marker, but only if there were any map markers. Now the button immediately skip to the beginning/end also when there are no demo markers at all.
- Fix demo seeking not working at beginning and end.
- Pause demo playback when skipping to end. It's otherwise inconvenient when the playback continues, as it will immediate rewind to the beginning when reaching the end.
- Allow right-clicking slice buttons to reset cut beginning/end.
=> Various minor demo player usability improvements

scripts/integration_test.sh
Seems like some CI workers don't have (virtual) sound cards
=> Increase waiting times for client in valigrind (fixes #6773)

CMakeLists.txt, src/base/color.cpp, src/base/color.h, src/base/system.cpp, src/base/system.h, src/engine/shared/console.cpp, src/game/client/ui.cpp, src/game/editor/editor.cpp
Remove the individual RGBA sliders for editor color pickers and only show one button that opens the color picker popup instead.
Decrease size of layer and point popups that previously had color properties which need less space now.
Support shift-rightclicking color picker buttons to copy the color to the clipboard in RRGGBBAA hex format.
Support shift-leftclicking color picker buttons to paste a color from the clipboard in RGB, RGBA, RRGGBB or RRGGBBAA format with optional leading `#` or `$`.
Screenshots:
- Before:
- After:
- After (color picker open):
Suggested by @HiRavie in https://github.com/ddnet/ddnet/pull/6743#issuecomment-1593886873, though it was easier and also looks better to me when the color picker button has exactly the same size as the other value selectors.
=> Remove individual RGBA sliders from editor color picker, add shift+rightclick/leftclick to copy/paste color in editor

src/engine/client/client.cpp
Notice i changed the check to > 0 microseconds.. The net wait cant handle nanos, busy waiting sounds bit overkill..
Notice also, i added a comment to the issue, which might be interesting before merging
fixes #6751
=> Continue sleeping, with `cl_refresh_rate` if packet waked client up

src/game/client/components/binds.cpp
This makes the 'bind' command optionally take only one argument, in which case it behaves like 'binds x'. This falls in line with how most popular games do it, and may prevent confusion in the future.
This introduces a tiny bit of duplication though, because I just copied the if statement from 'binds', but it should be fine.
=> Allow 'bind x' to be used like 'binds x'

src/game/client/components/menus_browser.cpp
The connect button had `5.0f` units less width, which was causing the corners of the refresh and connect buttons to look differently.
Screenshots:
- Before: 
- After:
=> Fix inconsistent size and corners of connect button

src/engine/client/client.h
=> Remove unused `GraphicsThread`/`GraphicsThreadProxy` declarations

src/game/client/prediction/entities/pickup.cpp
Radius was set to 0 before this, so pickups were sometimes not predicted.
=> Fix proximity radius of predicted pickups

src/game/server/ddracechat.cpp
Prevent swapping if either of the players is paused (i.e. their character is not in the gameworld), as this can cause them to be stuck in midair after swapping, which can be exploited to skip parts.
=> Prevent /swap with paused players

src/engine/client/client.cpp, src/engine/client/client.h, src/engine/server/server.cpp, src/engine/server/server.h, src/game/client/prediction/entities/character.cpp, src/game/client/prediction/gameworld.cpp, src/game/client/prediction/gameworld.h, src/game/client/race.cpp, src/game/collision.cpp, src/game/collision.h, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/io.cpp, src/game/server/entities/character.cpp, src/game/server/entities/light.cpp, src/game/server/gameworld.cpp, src/game/server/gameworld.h
Use `std::vector` in cases where elements are only inserted at the end of the collection.
Use `std::deque` in cases where elements are only inserted/deleted at the beginning/end of the collection.
Use `std::list` in the remaining single case where elements are being removed from arbitrary positions and added at either the beginning or the end of the collection.
Adjust variables names. Don't use separate prefix for `std::deque`s and `std::list`s, as they are only used very rarely. Closes #6779.
=> Use `std::vector` and `std::deque` instead of most `std::list`s

src/game/client/prediction/entities/character.cpp
This fixes a bug where ninja didn't get predicted when you fired a weapon right before picking it up and then tried to use ninja immediately afterwards
=> Fix wrongly calculated reload timer for ninja in prediction

src/game/editor/editor.cpp, src/game/editor/layer_tiles.cpp, src/game/editor/popups.cpp
Both are regressions in 17.1 and should be added to the release.
=> Fix height of layer popup when automapper properties shown, fix incorrect popup being closed when gametile popup used

src/game/editor/editor.cpp
The messages were previously rendered on top of the file dialog and popup menus.
=> Render editor pressed keys and saving message behind file dialog

src/engine/shared/storage.cpp, src/engine/storage.h, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/variables.h
Description in commits below. Screenshots/video:
- Storage location selection for demos:
- Storage location selection for maps:
- Link to "themes" folder:
- Video showing navigation between storages (`temp` is the save directory and `temp2`, `temp3` and `data` are other storages)
https://github.com/ddnet/ddnet/assets/23437060/5736d212-3848-44c2-aa81-7f2da9b98008
Closes #5496.
=> Ensure `ListDirectory/Info` entries are unique, support selecting storage location in demo browser and editor file browser

src/game/client/components/menus_browser.cpp
=> Fix online clan friends not being removable via UI

src/game/client/components/menus.cpp, src/game/client/components/menus.h
Closes #6806.
The message can contain a filename, so it should be large enough to contain that and the message itself.
Screenshots:
- Before: 
- After:
- Before (filename is truncated): 
- After (full filename is shown):
There is a separate issue with the text wrapping not working correctly with this long Unicode filename, which is causing the font size to decrease instead. See #6810.
=> Fix text alignment in large confirmation popups with long text, increase buffer size for generic popup message 

src/game/editor/layer_tiles.cpp
The brush passed to `FillSelection` can be `nullptr` when the selection is empty.
Regression from #6648.
Closes #6815.
=> Fix editor crash when filling entities layer with empty brush

src/game/client/components/hud.cpp, src/game/client/components/hud.h
The proper offset for the first available weapon is provided only for Hammer but sometimes (in some mods) the character has no hammer and the icons got a wrong left margin.
https://github.com/ddnet/ddnet/blob/83a2ad0e2482d39ff26fcf08c148b4ffeec05277/src/game/client/components/hud.cpp#L882-L895
Notice the `x -= 3;` in the hammer rendering branch. It fixes the `x` offset for this and further weapons but it works only if the character has a hammer (other weapons has no such line).
`-3` is specific for the hammer, we need different "first item" offsets for other weapons.
(the hammer offset is _correct_)
but if the character has no hammer then the things go _wrong_.
Shotgun/Grenade Launcher/Laser has just a small offset but the _wrong_ placement of katana indicator if very noticeable.
(no …
=> Fix HUD PlayerState weapons rendering

src/game/editor/editor.cpp, src/game/editor/popups.cpp
=> Fix editor crashes with quad point and other popup menus

src/game/client/gameclient.cpp
This makes the client connect to the server faster. It's especially noticeable on servers with a low ping.
Closes #6811.
=> Mark `NETMSGTYPE_CL_STARTINFO` as `MSGFLAG_FLUSH`

src/engine/client/client.cpp, src/engine/demo.h, src/engine/shared/datafile.cpp, src/engine/shared/datafile.h, src/engine/shared/demo.cpp, src/engine/shared/demo.h, src/game/client/components/menus.cpp, src/game/client/components/menus_demo.cpp, src/game/editor/io.cpp, src/game/server/gamecontext.cpp, src/game/variables.h, src/tools/map_resave.cpp
In this MR I want to address three issues with video recorder:
1. A bug: if I start a rendering with 0.25x speed and click on 'Increase the speed' during the rendering, I expect to get the next speed (0.5x) but as the speed index is not set (kept default `4`), the speed is boosted to 1.25x.
2. Usecase: I want to adjust the camera (change position, decrease zoom, etc) for the demos and I don't want to use extra video editor to cut the first frames with the unwanted camera moves/setups from the demo. I came to a simple solution: start the rendering pre-paused to do the needed adjustments before anything is added to the video.
3. NotABug: All recorded video files have double `.demo.mp4` extension which is ugly.
Probably I have to change something to fit DDNet codebase. E.g. I don't know if …
=> Improve demo (video) renderer UX

src/engine/client/text.cpp
Rewind one unicode codepoint instead of rewinding only one character (byte) when text does not fit.
Closes #6810.
Screenshots:
- Before: 
- After:
=> Fix text wrapping with long Unicode strings

src/game/editor/editor.h, src/game/editor/io.cpp
Add `CEditorMap::PerformSanityChecks` to perform additional sanity checks when loading a map in the editor.
In particular, the following is added: Check if there are any images with a width or height that is not divisible by 16 which are used in tile layers. Reset the image for these layers, to prevent crashes with some drivers.
Closes #6519.
Error message popup when loading the map linked in the issue (loading goes through, but this popup message is shown):
=> Perform sanity check and show errors when loading map in editor

src/game/client/components/menus_demo.cpp, src/game/client/ui_listbox.cpp, src/game/client/ui_listbox.h
Use separate columns for icons and spacing like in the server browser.
Always show scrollbar for more consistent layout.
Show ellipsis if filename is too long, also for the filename shown in the demo player.
Hide number of markers and length if the demo is invalid.
Screenshots:
- Browser:
- Before:
- After:
- Player:
- Before:
- After:
=> Improve demo browser layout

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp
Support deleting and renaming folders in the demo browser. Only empty folders can be deleted.
Ensure only files and folders in the save directory can be deleted and renamed.
Also check if a folder with a demo rename/render filename already exists.
Fix broken `m_DemolistSelectedIsDir` checks by using `m_vDemos[m_DemolistSelectedIndex].m_IsDir` instead.
Append `.mp4` file extension only internally instead of appending it to the render filename lineinput, as this causes the file extension to appear when rendering doesn't start due an error message.
Use more efficient `FileExists` instead of `FindFile` to check if rendered demo video file already exists.
Change popup preconditions to assertions.
=> Support deleting/renaming demo folders, improve demo popups

lsan.supp
The memory appears to be properly freed now, so this suppression is no longer necessary.
Keeping the empty suppressions file for the future is easier than removing it.
=> Remove obsolete leak sanitizer suppression

src/game/editor/editor.cpp, src/game/editor/editor.h
Previously the same message popup context was used for all error messages. While multiple message popups could be opened at the same time, the message would always be the same for all, as the same buffer was used for all popups.
This is fixed by creating and destroying the message popup contexts dynamically, so there can be any number of message popups with different messages. Additionally, if a popup with an identical message is already open, it will first be closed and then reopened at the new position, to prevent duplicate message popups.
=> Support showing multiple different error messages in editor

src/game/editor/editor.cpp, src/game/editor/editor.h
Replace `CEditor::m_EditBoxActive` which only works with editboxes created from the editor with `CLineInput::GetActiveInput` which also works for editboxes which are created by generic UI functions, e.g. the value selector editboxes of color pickers.
=> Fix editor hotkeys triggering while some editboxes are active

src/game/client/components/menus_browser.cpp, src/game/editor/editor.cpp
=> Fix enter not working in server browser when no server selected, fix enter not working in editor save dialog when no map selected

src/game/client/components/spectator.cpp, src/game/client/components/spectator.h, src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/variables.h
before:
after:
Edit: Thats the feedback i got from people. Hope its okay.
=> Improve Multi-View UX

src/game/editor/editor.cpp
Avoids quadpoints being moved when selected.
=> Fix quadpoint selection

src/base/system.cpp, src/base/system.h, src/game/client/components/menus_browser.cpp, src/test/str.cpp
By calculating the correct length of the string matched in the haystack using the added `end` parameter of `str_utf8_find_nocase`.
Closes #6850.
Add optional `end` output parameter to `str_utf8_find_nocase` which is set to a pointer into the haystack after the matched string.
This is necessary because there are pairs of matching upper case and lower case Unicode characters with different byte length (e.g. both `I` and `İ` map to `i`), so the byte length of the string matched in the haystack may not be identical to the length of the needle string.
=> Fix server browser filter highlighting of non-ASCII text

src/game/client/gameclient.cpp, src/game/client/gameclient.h
Delay showing the warning for ingame movement until the player has stopped moving while the editor is open, so the warning doesn't show immediately when the player performs an action (like jumping) and opens the editor shortly after.
Closes #6852.
=> Delay "Ingame moved" warning in editor

src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp
When first launching the client, keep the server list scrolled to the top instead of scrolling to the selected server.
Closes #6845.
=> Initially keep server list scrolled to the top

src/game/client/ui.cpp, src/game/client/ui.h
Otherwise this would cause issues when showing multiple confirm popups at the same time.
=> Use member instead of static variables for confirm popup buttons

.github/workflows/style.yml
```
error: failed to compile `twmap-tools v0.3.1 (/home/runner/work/ddnet/ddnet/twmap/twmap-tools)`, intermediate artifacts can be found at `/home/runner/work/ddnet/ddnet/twmap/target`
Caused by:
package `half v2.3.1` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.69.0
Either upgrade to rustc 1.70 or newer, or use
cargo update -p half@2.3.1 --precise ver
where `ver` is the latest version of `half` supporting rustc 1.69.0
```
=> Fix twmap installation in CI

src/game/server/ddracecommands.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
- Fixed a bug where the index was outside the bounds of the array
- Increased the log time to 10 minutes (600 seconds)
=> Fix bug, increase dump_log max seconds to 10min

src/base/math.h, src/engine/shared/datafile.cpp, src/engine/shared/datafile.h, src/engine/shared/map.cpp, src/engine/shared/map.h, src/game/client/components/mapimages.cpp, src/game/client/components/maplayers.cpp, src/game/client/render.h, src/game/client/render_map.cpp, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/io.cpp, src/game/editor/layer_tiles.cpp, src/game/editor/popups.cpp, src/game/mapitems.h, src/game/mapitems_ex_types.h, src/tools/map_convert_07.cpp, src/tools/map_extract.cpp, src/tools/map_optimize.cpp, src/tools/map_replace_image.cpp
Port map and editor support for `CURVETYPE_BEZIER` from upstream, i.e. support bezier curves with configurable in- and out-tangents for every envelope point.
The in- and out-tangents are represented by triangles and can be dragged in the envelope editor like the envelope points.
Support reading and writing the bezier information as a separate UUID-based map item. If the bezier information is not found, bezier will default to linear behavior. Old clients will still be able to read the new maps and ignore the unknown map item. The unknown curvetype will also be handled as linear by old clients.
Allow reading upstream maps that use `CMapItemEnvelope` version 3. On upstream, a different struct is used to store all envelope points including bezier information, which broke compatibility to old …
=> Support bezier envelope curves in maps and editor, forward compatiblity for upstream map item changes

src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/game/client/components/mapimages.cpp
They're essentially unused and not supporting them ingame probably allows to keep that part of the map format unused.
See https://github.com/ddnet/ddnet/pull/5737#issuecomment-1538284956 or https://github.com/teeworlds/teeworlds/issues/2812.
=> Don't support loading RGB images ingame

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/io.cpp
Write the map to a temporary file first. When the map was saved to the temporary file successfully, first delete the existing map file having the real filename, then rename the temporary file to the real filename.
If deleting or renaming fails, show an error message popup and log an error message to the console.
The implementation is consistent with the way temporary files are utilized by Microsoft Word, so this should work on Windows.
See: https://support.microsoft.com/en-us/topic/description-of-how-word-creates-temporary-files-66b112fb-d2c0-8f40-a0be-70a367cc4c85
Different from #4482, this first deletes the old map file before renaming the temporary file. Although it appears that renaming a file would also override the target file, it could be that this does not work on all systems. …
=> Use temporary file when saving editor map

src/game/client/components/maplayers.cpp, src/game/client/render.h, src/game/client/render_map.cpp
Add `CMapBasedEnvelopePointAccess::SetPointsRange` function so the start point and number of points that should be considered when using this envelope point storage can be configured. In the editor, this range always includes all points, as each envelope directly stores only its own points, so animations were rendered correctly there. However, all points are stored in one array when loading them from the map file (i.e. when rendering the map ingame), so the start point and number of points specified for the envelopes have to be considered when accessing their envelope points.
Closes #6886.
=> Fix ingame animations not using correct envelope points anymore

src/base/vmath.h, src/game/client/components/camera.cpp, src/game/client/components/camera.h
Set the clients view to a given teleporter or switch number
**TRIGGER WARNING**
~~The use of the keyword ``goto`` may offend some developers~~
UPDATE: This code is clean and can be red without caution.
Allows users to find teleporters and switchers by the index. If one wonders how to open a door or where a teleporter leads the user can lookup the id using entities and then run the console command ``goto_switch [id]``. Which will set the clients view port to the first occurrence it finds of that switcher in the map. If the command is run again it jumps to the next it finds. It also takes a second optional parameter which is the index of the occurrence to check so if one runs ``goto_switch 1 2`` it will set the view to the 2nd switcher of type 1 in the map it finds.
The user has to manually …
=> Add ``goto_switch`` and ``goto_tele``

src/game/client/ui.cpp, src/game/client/ui.h, src/game/editor/editor.cpp
Use `CLineInput::GetActiveInput` and `CLineInput::IsActive` instead for consistency.
The last active item pointer is now only tracked internally in `CUI` to deactivate the active line input when it's no longer used in the UI.
=> Remove usages of `CUI::LastActiveItem`

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
Selecting multiple quadpoints is currently a lot of work because the hitbox is small and you have to select them one at a time. This PR allows using the box-selection on all quadpoints to make it easier. To make this possible (and consistent with other controls) a few other changes had to be made. In particular:
- Shift + click now selects another quad basepoint. Before it allowed moving them, which is now ctrl + click.
- Rotation is now bound to R.
- Copying quads now works through ctrl + c / ctrl + v.
I havent tested it very much yet. Because of this and since there has not been any discussion on this, I am submitting this as a draft.
=> Selectable quadpoints

src/game/client/render_map.cpp
Use `double` instead of `int` to represent the time in milliseconds in envelope calculation.
This fixes step-ladder patterns appearing with bezier curves and artifacts appearing when two points are very close together in time.
Screenshots:
- Artifacts:
- Before:
- After:
- Bezier curves (minor difference already visible currently, will become more apparent with #6885):
- Before:
- After:
=> Fix inaccurate envelope calculation

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
When using "Save as" and "Save copy" set the default map name in the file dialog to the name of the current map.
=> Set default name when saving map under new name or as copy

src/game/editor/editor.cpp, src/game/editor/editor.h
This should make adjusting envelopes with many close envpoints easier.
At this point it is only a proof of concept, I just want to make sure that this is a wanted feature.
=> Zoomable envelope editor

CMakeLists.txt, src/engine/shared/jsonwriter.cpp, src/engine/shared/jsonwriter.h, src/test/jsonwriter.cpp, src/test/test.cpp, src/test/test.h
Port the `CJsonWriter` utility class from upstream, which makes outputting correct JSON easier.
Add `CJsonWriter` as an abstract class that can write to different outputs. Two implementations `CJsonFileWriter` (writes to a file) and `CJsonStringWriter` (writes to an `std::string`) are added. Upstream `CJsonWriter` can only write to files.
The same tests are added for both implementations. Duplicate code is avoided by using typed tests with two separate test fixtures.
=> Port JSON writer from upstream, improve testing

src/engine/textrender.h, src/game/client/ui_listbox.cpp, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/io.cpp
Screenshots:
- Envelope editor alignment and extra editor buttons:
- Before:
- After:
- Command editor (empty):
- Before:
- After:
- Command editor (with entries):
- Before:
- After:
=> Improve server settings editor and status bar, refactoring

CMakeLists.txt
This is basically as good, but also supported on MinGW.
=> Change to `-fstack-protector-strong` from `-fstack-protector-all`

src/game/editor/editor.cpp
=> improve envelope y offset on reset for small value ranges

src/game/editor/editor.cpp
This should hopefully finally fix #6855.
=> reset layer dragging status if no buttons were pressed

src/engine/shared/demo.cpp
=> Fix leak of map data when extracting map from demo fails

src/engine/client/graphics_threaded.cpp, src/engine/graphics.h
Rectangles with inverted round corners (`IGraphics::CORNER_I*`) are currently not used anywhere and also only supported when using `Draw4`.
They also feel clunky to use due to the inverted corners being drawn outside of the specified rectangle area.
Here is how the inverted round corners would look like (on color pickers because it's the only place where we use `Draw4`):
=> Remove inverted round rectangle corner drawing

src/engine/shared/datafile.cpp, src/engine/shared/datafile.h
Check if datafile data cannot be read entirely (according to the data size specified in the header) and check for decompression errors. In case of errors, let `GetData` return `nullptr` and `GetDataSize` return `0` for the respective index.
Internally the decompressed size is set to `-1` for data which failed to load, so loading of those data will not be attempted again because it would only fail again and can cause additional log messages.
=> Check for errors when reading and decompressing datafile data

src/game/editor/editor.cpp
Close to the origin zooming should maybe look a bit smoother although it should not change much. If you zoom far away from the origin it should now behave correctly. Previously it did not zoom to the mouse but shifted the view slightly.
=> improve offset adaption for envelope zoom

src/game/client/prediction/entities/character.cpp, src/game/collision.cpp, src/game/collision.h, src/game/gamecore.cpp, src/game/server/entities/character.cpp, src/game/tuning.h
implements `ground_elasticity_x` and `ground_elasticity_y`
Similar to https://github.com/teeworlds/teeworlds/pull/3136
~closes #5124~ implements the player bouncing part of this. Doesn't effect projectiles!
can be followed up by #5313 with a "slimey block", see [here](https://github.com/ddnet/ddnet/issues/5124#issuecomment-1140402547)
=> implement tuning values for elasticity

src/game/client/components/spectator.cpp, src/game/client/gameclient.cpp, src/game/variables.h
Fixed / added some things according to feedback from discord.
- Multi-View can not longer be activated again after already active
- Fix cl_multiview_use_freeview variable config
- Players who killed will be removed now from Multi-View even if the spec mode is not active
- Multi-View personal zoom will be reseted when enabling Multi-View
- Fix bug where a kill in a team will be taken into account
- Improve the solo player experience in Multi-View
=> Minor improvements to Multi-View

src/game/editor/editor.cpp, src/game/editor/editor.h
Draft to make quad point selection easier. To work properly this will need #6844. Since this change was inspired by blender the hitbox is currently quite big. If two points are within range the nearest one is chosen.
=> Make point selection easier

src/engine/console.h, src/engine/shared/console.cpp, src/engine/shared/console.h, src/game/client/gameclient.cpp, src/game/server/gamecontext.cpp
The old code looked pretty weird. It checked for `CFGFLAG_SERVER | CFGFLAG_GAME` being set above, and then used the passed-in parameter to find the command. I think it'd be better to just look for `CFGFLAG_GAME` and then find the command using `CFGFLAG_GAME`.
=> ResetServerGameSettings → ResetGameSettings, remove flag argument

src/engine/shared/jobs.cpp, src/engine/shared/jobs.h
Since they're not called anyway, they can go away.
=> Delete fishy-looking assignment operator/copy constructor of `IJob`

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/io.cpp, src/game/editor/layer_game.cpp, src/game/editor/layer_quads.cpp, src/game/editor/layer_sounds.cpp, src/game/editor/layer_tiles.cpp, src/game/editor/popups.cpp
Simplify memory management of groups, layers, images, sounds and envelopes by using `std::shared_ptr` for all of them.
Clear brush when creating a new map to prevent crash due to unloaded textures being used in tile layer. Closes #6935.
Also fix crash when restoring a saved brush after removing an image that is being used by it.
=> Use `std::shared_ptr` for editor resources, fix crashes with brush

src/engine/shared/jobs.cpp
`shared_ptr`s of `CServer::m_pDnsblLookup[ClientID]` are set, but not cleaned up when done. Therefore the Job is kept alive until the player disconnects and a new player joins on that slot. Currently this means that the full linked list of jobs is kept alive.
When the Job is overwritten with a new job, all the remaining objects in the list can be dropped. With enough jobs, that is causing a stack overflow in the destructor.
This patch fixes this overflow by making the lifetime independent of the previous Job. Jobs can get dropped after processing them, even when the previous job is still alive.
Fixes #6954
=> Fix stack overflow in destructor when dnsbl object is kept too long alive

src/game/client/gameclient.cpp, src/game/client/gameclient.h
When quitting or restarting the client, clear the screen and render a message "Quitting. Please wait…" or "Restarting. Please wait…" respectively.
Previously the last frame would keep getting shown while the client is busy with cleanup tasks. Rendering a final message before the client window stops being updated provides a cleaner user experience.
Screenshots:
- ![quitting](https://github.com/ddnet/ddnet/assets/23437060/190faceb-a5b9-4d66-89b4-d8710a4ad22d)
- ![restarting](https://github.com/ddnet/ddnet/assets/23437060/20ac90c0-e123-444c-a356-72405b2e56d1)
=> When quitting/restarting client clear screen and render message

src/base/system.cpp, src/base/system.h, src/engine/client/client.cpp, src/engine/client/serverbrowser_http.cpp, src/test/netaddr.cpp
Support master server address format in client
This still works
```    
$ ./DDNet "connect 127.0.0.1"
```
But now also this works
```
$ ./DDNet "connect tw-0.6+udp://ger10.ddnet.org:8303"
2023-07-16 14:07:50 I engine: running on unix-linux-amd64
2023-07-16 14:07:50 I client: starting...
2023-07-16 14:07:50 I client: version 17.1.1 on linux amd64
2023-07-16 14:07:50 I client: git revision hash: 7f100e262032b50d
2023-07-16 14:07:50 I client: connecting to 'tw-0.6+udp://ger10.ddnet.org:8303'
2023-07-16 14:07:50 I host_lookup: host='ger10.ddnet.org' port=8303 3
2023-07-16 14:07:51 I client: connected, sending info
```
This string still needs a catchy name. I called it "rich" format but that doesn't seem too optimal.
Also not too sure if the ``tw_protocol`` field in ``struct NETADDR`` should …
=> Support master server address format in client

src/game/server/gamecontext.cpp
The `Translate` function modifies the first argument, so the client ID keeps changing when the function is being used in a loop. Additionally, calling `Translate` manually is not necessary for messages, as client IDs in messages are already automatically translated when using `SendPackMsg`. Both faults can cause emoticons to appear on the wrong players when the emote spamprotection limits emotes to nearby players.
=> Fix emotes sometimes being shown for others tees

src/base/logger.h, src/base/system.cpp, src/base/system.h
Switch to using the Windows-specific `HANDLE` and Windows API functions instead of `FILE *` and standard library functions in all Windows IO function implementations.
Using `CreateFileW` instead of `_wfsopen` to open files is necessary, as only `CreateFileW` allows specifying all necessary sharing flags. The sharing flags `FILE_SHARE_READ` and `FILE_SHARE_WRITE` were previously already specified by using `_SH_DENYNO` with `_wfsopen`, but `FILE_SHARE_DELETE` can only be set when using `CreateFileW`. The flags are necessary so files which are in use by the game can still be opened by other processes. In particular, `FILE_SHARE_DELETE` allows deleting/renaming of open files, which was previously not possible. This was causing the smart editor saving process that renames files to fail if a …
=> Rework base IO functions on Windows using `HANDLE`

src/game/client/components/voting.cpp
The server does not allow adding more than `MAX_VOTE_OPTIONS` vote options, so the client will now also refuse to add more options than that.
Supersedes #6930.
=> Fix client crash with more than `MAX_VOTE_OPTIONS` vote options

src/game/client/components/camera.cpp
The check for `goto_switch` is added for completeness but not strictly necessary, as this is also checked in `GetSwitchNumber`.
=> Fix crash when using `goto_tele` in map without tele layer

src/engine/client/text.cpp
=> Fix textrender variables being uninitialized

src/engine/client/client.cpp, src/engine/client/client.h, src/game/client/components/debughud.cpp, src/game/client/components/items.cpp, src/game/client/gameclient.h, src/game/variables.h
See commit messages for details.
Screenshots:
- `dbg_tuning`:
- Before (`dbg_tuning 1`): ![tuning-full old](https://github.com/ddnet/ddnet/assets/23437060/b69a7861-ea71-4b43-b62c-8d03e6125490)
- After (`dbg_tuning 1`, only showing changed parameters): ![tuning-compact new](https://github.com/ddnet/ddnet/assets/23437060/5e8fbdc5-1952-468b-853f-7080ed08c54a)
- After (`dbg_tuning 2`, showing all parameters and the velramp graphs): ![tuning-full new](https://github.com/ddnet/ddnet/assets/23437060/0d31a072-e042-4dce-9eb2-c82e35ed00a5)
- `debug`:
- Before: ![debug old](https://github.com/ddnet/ddnet/assets/23437060/455fce0e-a2b8-482d-99b2-43e261f24951)
- After: ![debug new](https://github.com/ddnet/ddnet/assets/23437060/ecaead20-e661-4c23-988f-e08f44bb67b7)
- `dbg_graphs`:
- Before: ![graphs …
=> Improve `dbg_tuning` and other debug HUD, use textrender for debug graphs

src/game/client/components/menus_settings.cpp
=> Use `Localizable` instead of `Localize` inside comment

src/game/editor/editor.cpp
Also now round is used to convert the mouse position to fixed precision time which places the added point closer to the mouse. Fixes #6986.
=> Disallow adding overlapping envelope points

src/game/editor/editor.cpp
When multiple envelope points could be selected, switch the order such that the one that is visible is selected first.
The mouse is hovering the second point in both pictures.
Before:
After:
=> Switch order in which envelope points are selected

src/game/editor/editor.cpp, src/game/editor/editor.h
When two envelope points overlap it can happen that the hidden one will be marked as hot. Then neither can be selected. Fixes #6989.
=> Ignore hidden channels when selecting envelopes

src/game/server/player.cpp, src/game/server/scoreworker.cpp
Using `/timecp` with a player name that has no time on the current map incorrectly cleared the player score/time causing it to not be shown in the scoreboard anymore.
In `LoadPlayerData` exactly the `LIMIT 1` clause was getting truncated from the query due to the buffer size being insufficient. Depending on the length of the table name prefix the query could have been truncated at any other position resulting in syntax errors.
In `ShowTeamTop5` the buffer size is increased because it could cause truncation with a longer than default table name prefix.
=> Fix scoreboard time being reset when using `/timecp`, fix SQL query buffer sizes being too small

src/game/client/components/camera.cpp
cl_smooth_zoom_time 0
was causing problems. Idk exactly why such big zoom jumps are creating problems (grey background), but this should fix it
=> Fix smooth zoom with zero causing problems with multiview

src/game/server/scoreworker.cpp
The `INSERT INTO` query could be truncated when using a longer table name prefix.
=> Increase another SQL query buffer size

other/bundle/client/Info.plist.in, other/bundle/server/Info.plist.in
When building app, info.plist at the app bundle will have CFBundleExecutable key empty, this didnt cause major problems, but actually would cause "DDNet-Server" being run instead of "DDNet-Server-Launcher", and the server app will stay jumping on the dock forever.
=> Minimal fix for macOS info.plist

src/engine/client/text.cpp, src/game/client/gameclient.cpp, src/game/client/ui.cpp, src/game/client/ui.h
Fix text containers rendering broken text after the language is changed, as this cleared the glyph atlas without clearing the references to the glyph positions in the text containers. Now `OnWindowResize` is also called on language change to reset all text containers.
However, the glyph atlas is not cleared on normal window resize anymore, because this seems to be unnecessary.
=> Reset text containers on language change

src/engine/server/databases/connection_pool.cpp, src/engine/server/databases/connection_pool.h
This now calls OnShutdown twice in the successful case and once in the error cases. Easier than explicitly calling OnShutdown in each potential error location.
=> Shut down db connection pool (fixes #7036)

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp, src/game/variables.h
Contributes to https://github.com/ddnet/ddnet/issues/7044
=> Remove cl_video_pause_on_start; reset the pause option on popup opened

src/game/client/components/background.cpp, src/game/client/components/background.h, src/game/client/components/menu_background.cpp, src/game/client/components/menus.cpp, src/game/client/components/menus_settings.cpp
Add a button to manually reload the entities background map instead of automatically reloading it when it's changed. As the background map was only reloaded every 10 seconds, sometimes changing the background map quickly had no effect.
Improve the layout of the DDNet settings menu. Align labels and UI elements and reduce unused empty space.
Screenshots:
- 1920x1080:
- Before: 
- After: 
- 1280x1024:
- Before: 
- After:
=> Add button to reload entities background, improve DDNet menu layout

src/game/editor/editor.cpp
It was not actually necessary to clear the brushes to prevent the crashes. The crashes were fixed by not storing the texture handles for the layers anymore.
Closes #7024.
=> Don't clear saved brushes when loading another map

src/engine/server/databases/connection.h, src/engine/server/databases/mysql.cpp, src/engine/server/databases/sqlite.cpp
When connecting to the SQLite database fails, e.g. because the `.sqlite` file is corrupted, the server would crash with the assertion "Tried connecting while the connection is in use" when a player joins and performs any action.
This is fixed by resetting the use-flag when connecting to the SQLite database fails, which is the same behavior as for the MySQL database connection.
=> Fix assertion failure when SQLite connection fails, Remove unused `IDbConnection::Copy`

CMakeLists.txt, src/base/system.cpp, src/base/system.h, src/engine/server/server.cpp, src/engine/server/upnp.cpp, src/engine/shared/console.cpp, src/engine/shared/jsonwriter.cpp, src/game/client/components/debughud.cpp, src/game/client/components/hud.cpp, src/game/client/components/mapimages.cpp, src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/nameplates.cpp, src/game/client/components/scoreboard.cpp, src/game/client/components/statboard.cpp, src/game/client/components/voting.cpp, src/game/client/lineinput.cpp, src/game/client/render_map.cpp, src/game/editor/editor.cpp, src/game/editor/layer_tiles.cpp, src/game/server/gamecontext.cpp
Add more efficient function for formatting integer values as strings.
A benchmark shows that using this function is significantly faster than using `str_format`. It is faster by a factor of 220 with Clang 15.0 O2 (https://quick-bench.com/q/BlNoLnlyqxipf4jvsFTUxKMHDJU) and by a factor of 11 with GCC 12.2 O2 (https://quick-bench.com/q/Fxf9lDCTqXBF4pIa_IyZ5R0IqYg).
This increases FPS in the editor by ~25% when many numbers are rendered for switch/tele/speedup/tune layers or with "Show Info" being enabled.
The additional static analysis for `std::to_chars` revealed that the wrong size was used in `CHud` for `aScoreTeam[TEAM_RED]` and `aScoreTeam[TEAM_BLUE]`.
This requires incrementing the macOS deployment target from 10.13 to 10.15.
=> Add `str_from_int` function

src/base/color.h, src/engine/shared/config_variables.h, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp
Render a pause/play icon in the center of the screen when pausing/unpausing while the menu is not active.
The icon fades in and out over 0.5 seconds and slightly increases in size over that time.
When starting demo rendering with initial pause, the pause indicator is rendered continuous until playback is first started, to ensure that the initial pause state is communicated clearly to the user. The initial pause indicator is not included in the rendered demo, but pausing and unpausing later during demo rendering will cause it to be included in the video, same as other UI elements. Closes #7044.
The config variable `cl_demo_show_pause` (`0/1`, default `1`) is added to hide the pause indicator entirely, for example to render a demo with multiple pauses without the indicator.
The pause …
=> Show indicator when pausing/unpausing in demo player

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/explanations.cpp
Use `enum`. Organize explanations in separate functions for DDNet, FNG and Vanilla.
Cherry-picked from #7054.
*Add the GET parameter `w=1` to the URL to view a much shorter diff.*
=> Refactor editor entities layer explanations

src/game/editor/popups.cpp
=> clamp value-range for color envelopes in popups

src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/server/gamecontext.h, src/game/server/gamecontroller.h
CGameClient::OnPredict() says "don't predict anything if we are paused" and yet we predict different stuff based on CGameClient::Predict() result which leads to flickering here and there (e.g. for projectiles and characters).
Steps to reproduce:
1. Check 'AntiPing' in the settings
2. Join a server
3. Pause the round (`rcon pause_game`)
Expected result: The game is paused and characters, projectiles and other entities do not move (until the server moves them)
Actual result: The game says it's paused but everything (except the player character) is shaking / jumping back and forth.
The actual fix is:
```diff
--- src/game/client/gameclient.cpp
+++ src/game/client/gameclient.cpp
@@ -757,7 +757,7 @@ bool CGameClient::Predict() const
if(m_Snap.m_pGameInfoObj)
{
- …
```
=> CGameClient::Predict: Disable prediction if the game is paused 

other/vscode/README.md, other/vscode/ddnet.code-workspace, other/vscode/lldbinit.py
This will automatically free your mouse when a breakpoint is hit under x11, using LLDB
I also added it to the workspace so it works out of the box there.
If you prefer to manually do it, or not use the workspace, here are the steps:
_Note:! this only works with LLDB rn.. theoretically it should be ez to add support for GDB similary like this, but i rarely use GDB so i dunno how it works there ;)_
<details> 
<summary>Setup xdotool manually to free the mouse on breakpoint hit </summary>
- install xdotool package
- execute or let lldb execute this at the start of debugging:
```
command source ${env:HOME}/.lldbinit
```
- in `~/.lldbinit`:
```
target stop-hook add --one-liner "command script import  ~/lldbinit.py"
```
- in `~/lldbinit.py` (no dot!):
```py
#!/usr/bin/python
import os …
```
=> Automatically release the mouse for x11, when breakpoint is hit

src/game/server/gamecontext.cpp
This allows the antibot to start pushing data into teehistorian immediately.
=> Notify antibot of round start after initializing teehistorian

CMakeLists.txt, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp, src/game/editor/tileart.cpp
Generate tilelayers and color maps from an image. This could be useful for all sorts of things from importing shapes like circles to creating maps like pokemon gen 1. For each 255 colors one color map and layer is generated and the tiles are set accordingly.
Maybe some warnings should be added if the image is big or there are many colors.
=> Add pixelart tool to editor

src/engine/client/client.cpp, src/engine/editor.h, src/game/editor/editor.h, src/game/editor/io.cpp, src/game/editor/popups.cpp
=> Add warning for unsaved editor changes when dragging a map file into the game

src/engine/server/register.cpp
It makes no sense to try to register server to IPv6, when it's not enabled.
=> Don't register to ipv6 when sv_ipv4only is enabled. (fixes #7091)

src/game/client/components/menus_demo.cpp
This fixes the sorting of demos which I accidentally broke after implementing demo searching (#7069).
=> Fix demo sorting

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h
The log message is otherwise shown multiple times when starting the client.
Now it's only shown when the `record` command is used manually, i.e. not for automatically recorded demos anymore.
=> Hide `client is not online` log message except when using `record`

src/game/client/lineinput.cpp
When the text cursor/selection mode is set to calculate, values of `-1` are used when the selection is empty. These values were not being handled anymore due to a regression from #7028. This was causing the selection to be set to the last position instead, which was causing text to subsequently be inserted there instead of at the cursor position.
An assertion is added to ensure that the selection cannot be desynchronized from the cursor position anymore.
Closes #7099.
=> Fix lineinput selection getting desynchronized from cursor

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/localization.cpp, src/game/localization.h
This makes it more obvious where text is localized. This class was also broken for localized strings with context, since the member variable `m_ContextHash` was uninitialized.
=> Remove `CLocConstString`

src/game/client/ui.cpp, src/game/client/ui.h, src/game/client/ui_rect.h, src/game/editor/editor.cpp
Saving indicator in the editor:
https://github.com/ddnet/ddnet/assets/23437060/a71197a0-cdaa-4fc1-a28b-94e195c337f6
Supports indeterminate progress (spinning) and determinate progress (showing a percentage):
https://github.com/ddnet/ddnet/assets/23437060/345469c7-a17a-4147-af8f-d3a6225918f9
Could eventually also be used when assets are being loaded in the background (#6727) or to visualize the remaining callvote time.
=> Add progress spinner to UI, show progress spinner while saving map in editor

src/game/client/components/menus.cpp
Reported by Jurai!.
Screenshots:
- Before:
- After:
=> Truncate IP with ellipsis in connecting popup

scripts/send_named_pipe.ps1, src/engine/shared/fifo.cpp
Use `WaitForPipeDrain` to deterministically wait for the pipe to drain instead of using `Start-Sleep`.
Use `Dispose` instead of `Close` to properly flush and close the pipe stream.
Add error handling for connection timeout and I/O errors.
Handle `ERROR_BROKEN_PIPE` separately when peeking at pipe, as this happens when the pipe is disconnected immediately after connecting it or after reading the previous message.
Don't ignore `ERROR_BAD_PIPE` anymore, as the pipe should never be in a disconnected (i.e. bad) state at this point of the function.
=> Improve Windows pipe (FIFO) support

src/engine/client/backend/backend_base.cpp, src/engine/client/backend/backend_base.h, src/engine/client/backend/null/backend_null.h, src/engine/client/backend/opengl/backend_opengl.cpp, src/engine/client/backend/opengl/backend_opengl.h, src/engine/client/backend/opengl/backend_opengl3.cpp, src/engine/client/backend/opengl/backend_opengl3.h, src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/client.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/client/text.cpp, src/engine/client/video.cpp, src/engine/graphics.h, src/engine/textrender.h, src/game/client/components/countryflags.cpp, src/game/client/components/mapimages.cpp, src/game/client/components/mapimages.h, src/game/client/components/menus.cpp, src/game/client/gameclient.cpp, src/game/editor/editor.cpp, src/game/editor/mapitems/map_io.cpp, src/game/editor/popups.cpp, src/game/editor/tileart.cpp, src/tools/map_convert_07.cpp, src/tools/map_create_pixelart.cpp, src/tools/map_replace_image.cpp
Use `enum EImageFormat` type for image format literals and variables.
Add `PixelSize` function to get the number of bytes/color channels per pixel for a specified image format.
Remove unused store format argument of texture loading functions. All textures are automatically being stored as RGBA, so the argument was unused. Also remove the therefore unused `FORMAT_AUTO`.
Rename variables consistently to `PixelSize` and use `size_t`, instead of mixing different names like `BPP` and `ColorChannelCount`.
Validate image format loaded from maps using `CImageInfo::ImageFormatFromInt`. Add `FORMAT_ERROR` to represent invalid formats.
Remove redundant `PixelSize` parameter from graphics backends and commands, which can be derived from the texture format.
Fix memory leak when RGB image data is being …
=> Add `CImageInfo::PixelSize` function, use `enum EImageFormat`

src/game/client/components/menus_settings.cpp
For some tooltips, the associated UI element ID was not being set as hot item, which is required for tooltips.
The tooltip for the "Dummy settings" checkbox was only present on the tee settings page but not on the player settings page.
Closes #7107.
=> Fix some menus tooltips not working anymore

src/engine/client/text.cpp, src/engine/shared/console.cpp, src/game/client/components/console.cpp
Don't truncate console lines at 255 bytes anymore. Especially lines containing many Unicode characters would be adversely affected by this limitation.
Instead, truncate console lines after 10 wrapped lines are rendered. Rendering too many lines at once currently breaks the console scrolling. Rendering an ellipsis is currently not possible when rendering text with a maximum line count.
Increase buffer sizes to handle long (esp. invalid) command inputs.
Closes #7132.
Check if maximum number of lines has been reached before starting a new line, to prevent the text cursor from reporting the wrong number of lines and text height in that case.
Screenshots (maximum number of character `m` was used as command):
- Before:
- After:
=> Support longer lines being rendered in console, fix incorrect text height when maximum number of lines specified

src/engine/server/server.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
If the player slots update the 0.7 clients have to be informed about it. Otherwise the client can block the join button if the outdated playerslots are filled already.
If there are no free in game slots (for example ``sv_spectator_slots 64``) and a 0.7 client joins it gets this setting and blocks the join button on the client side. If then the slots free up (for example ``sv_spectator_slots 60``) the client still thinks there are 0 in game slots and the user can not click the join button.
Currently 0.7 clients have to reconnect if they want to join the game after the in game slots got increased.
Closes https://github.com/ZillyInsta/ddnet-insta/issues/13
=> Fix 0.7 clients not being able to join after slot change

src/game/client/components/menus_settings.cpp
Currently you have to click back into the countryflag list to be able to scroll again.
=> Allow countryflag scrolling in player settings while name/clan input selected

CMakeLists.txt
We don't have any own C source files anymore.
=> Don't compile `.h.in`, remove C compiler flags

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
Some refactorings are kept and rotation being bound to `R` is also not reverted.
=> revert change to quad selection (resolves #7025)

src/game/client/components/menus_browser.cpp
The clan argument is optional when using `add_friend` and `remove_friend`.
=> Fix friendlist update conchain not working with optional argument

datasrc/network.py, src/game/client/components/players.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h
The mod I maintain ([infclass](https://github.com/infclass/teeworlds-infclassR)) has different player classes, and (as in many other games) the classes have unique skins — it is critical to differentiate the classes.
One of the classes is `ninja` which has stun (freeze) grenades. I'd like to use the `CNetObj_DDNetCharacter::FreezeEnd` to show the freeze bars and enable better prediction but by default DDNet client shows ninja skin for frozen characters and it totally ruins infclass gameplay:
I already maintain a DDNet [client fork](https://github.com/infclass/infclass-client) with 100+ infclass-specific commits (fixes/features) but of course I'd prefer to have DDNet client be capable for all of this stuff so ultimately I can archive the fork and work on infclass server and on DDNet client …
=> Mod Support: Add NINJA_SKIN_FOR_FROZEN game info flag

src/engine/client/backend/opengl/backend_opengl.cpp, src/engine/client/backend/opengl/backend_opengl3.cpp
fixes #7151
One of the disadvantages of OpenGL being a global state machine ^^ (we only update it if a render command comes in)
=> Disable scissor for clearing the framebuffer

src/game/editor/mapitems/layer_tiles.cpp
For example, `20⨯10` instead of `20,10`.
This is the "vector" symbol, which makes the most sense in this context.
Before:
After:
=> Render editor brush selection size with `⨯` instead of `,`

src/game/client/lineinput.cpp
When the buffer of a lineinput is modified externally, the cursor offset and selection are not updated, which causes them to be rendered wrong and also causes the assertion error "Selection and cursor offset got desynchronized" when changing the selection of a lineinput.
=> Fix desynced lineinput cursor/selection on external buffer change

src/game/client/ui.cpp, src/game/client/ui.h
Reduce the space reserved for the label by the space for the dropdown icon instead of rendering the label behind the icon.
This is more noticeable with smaller dropdown menu buttons, which will be used in the future.
Screenshots:
- Before: 
- After:
=> Improve dropdown menu button label alignment

src/game/client/components/chat.cpp, src/game/client/components/ghost.cpp, src/game/client/components/killmessages.cpp, src/game/client/gameclient.cpp
tested ingame by trying to reproduce (so not 100% fix), but seems logical to me
fixes #7165
=> Make skin refind cleanup bit more aggressive

src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
This is actually helpful for forks and modding: some mods customize votes, some customize the processing of `NETMSGTYPE_CL_SAY`, etc.
It is hard to track what is going on in this method, and sometimes it is even harder to merge changes here.
This MR is hard to rebase and I'd appreciate a quick (like: before other MRs touching this area) response. :eyes: 
<s>**Note: I can't fix the code style for this MR, this is why I asked for #7033 ("please update clang-format").**</s>
Edit: Oh, what!? It failed in my repo and I gave up. Now it goes :heavy_check_mark: here :exploding_head:
=> Server: Split the huge CGameContext::OnMessage()

CMakeLists.txt
This allows the version.h.in file to show up in IDEs.
This reverts commit db5f28e65ac7b5dbe61614be208d704d820226c3.
=> Revert "`.h.in` aren't compiled"

.github/workflows/build.yml, .github/workflows/clang-sanitizer.yml, .github/workflows/clang-tidy.yml, .github/workflows/codeql-analysis.yml, .github/workflows/rust.yml
Thanks to @Robyt3 for the solution.
https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/timeout.20investigation https://github.com/serde-rs/serde/issues/2577
https://github.com/dtolnay/rust-toolchain/pull/94
=> Hopefully fix intermittent CI failures

src/game/client/components/chat.cpp, src/game/client/components/killmessages.cpp, src/game/client/components/nameplates.cpp, src/game/client/components/scoreboard.cpp, src/game/client/components/spectator.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h
The DDTeam colors were previously generated in HSL by taking the team index and multiplying it by 360/64° to calculate the hue, which results in team colors being evenly distributed over the entire color range like a rainbow. However, this causes colors of adjacent teams to be very similar and therefore hard to distinguish.
Now, the hue is calculated by multiplying the team index with the golden angle (~137.50776°) and taking the modulo 360° of that. Due to the properties of the golden angle, this can generate never repeating sequences of unique colors where the adjacent colors are very distinct.
Duplicate code is reduced by adding the `CGameClient::GetDDTeamColor` function.
Screenshots:
- Before: 
- After: 
- Comparison: 
- Comparison (all in one row): 
- Comparison (sorted by color, …
=> Use golden angle to generate unique, distinct DDTeam colors

src/game/editor/editor.cpp
Fixes shortcuts used for rotation of quads and zooming in the envelope editor being triggered when a dialog is open.
=> Prevent some editor shortcuts when a dialog is open

src/game/client/components/menus_ingame.cpp
- Remove unnecessary variable `Page`.
- Use `IGraphics::CORNER_NONE` instead of `0` and instead of the inconsistent-looking `CORNER_BR` for the KoG-button.
- Simplify UI rect layout.
Screenshots:
- Before: 
- After:
=> Minor refactoring of ingame server browser

src/engine/textrender.h, src/game/client/components/menus_demo.cpp
Make the skipping duration adjustable with a dropdown menu. The dropdown menu includes the durations 1s, 5s, 10s, 30s, 1m, 5m and 10m. The default duration is 5s. Skipping durations longer than the current demo are not shown. The dropdown menu is only shown if two or more durations would be shown.
Add buttons for skipping the duration, which was previously only possible with the hotkeys.
Add Ctrl+Left/Right hotkeys for skipping to chapters.
Add Shift+Left/Right hotkeys for adjusting the skipping time.
The Left/Right arrow keys and the J/L keys work identically for all hotkeys now.
Ignore ctrl, shift and alt keys for demo speed changes with the mouse wheel, to better support actions like zooming being bound to alt+mousewheel etc.
Also handle keypad enter key for play/pause like the normal …
=> Overhaul demo player skipping UI and UX

CMakeLists.txt, src/game/alloc.h, src/game/client/prediction/entities/character.cpp, src/game/client/prediction/entity.h, src/game/client/prediction/gameworld.cpp, src/game/client/prediction/gameworld.h, src/game/gamecore.cpp, src/game/gamecore.h, src/game/server/entities/character.cpp, src/game/server/entities/laser.cpp, src/game/server/entities/projectile.cpp, src/game/server/entity.h, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/gameworld.cpp, src/game/server/gameworld.h, src/game/server/player.h, src/game/server/save.cpp
- https://github.com/ddnet/ddnet/pull/7136/commits/90ae9e6f6268e5b621f7c23c88541cdf313766c5 is needed to make all references to `m_HookedPlayer` go via setter (or getter) and enforce `CCharacterCore::m_AttachedPlayers` update (I had a code which accessed `m_HookedPlayer` directly and it continued to compile even though now we must use the setter).
- https://github.com/ddnet/ddnet/pull/7136/commits/fc42d003e63b899e784b8762362c98141c743959 is needed to force CCharacter(s) use the setter (the classes still had direct access otherwise).
- https://github.com/ddnet/ddnet/pull/7136/commits/68f3beaa35bfb343dbe2e9bed40766f8575733cd is a server-side cleanup for shared CGameWorld. The players mapping has nothing to do with the GameWorld logic, and the move allows to drop GameWorld dependence on …
=> Refactor some core classes (step 1/xxx to shared CGameWorld)

src/game/editor/editor.cpp
A lot nicer and also lessens the effects of #5844 in the editor.
=> Use colour pack functions for editor

src/game/client/components/menus_browser.cpp, src/game/client/ui_listbox.cpp, src/game/client/ui_listbox.h, src/game/client/ui_scrollregion.cpp, src/game/client/ui_scrollregion.h
Remove `Is` from the getter names for the same reason that removing `Get` from the name is preferred. The word `Is` was inconsistently used as a prefix in `CScrollRegion` but as an infix in `CListBox`.
=> Consistently name `CScrollRegion` and `CListBox` getters

src/base/system.cpp, src/base/system.h
The return value is unused and always 0, as the function fails with an assertion instead of returning an error value.
=> Remove unnecessary return value of `net_init`

src/engine/textrender.h, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/ui_listbox.cpp, src/game/client/ui_listbox.h
Move the "Filter", "Info" and "Friends" tabs to the top, above the tab content. Use icons instead of text for the tabs. Use animator to animate the tabs on mouse-over. Closes #6613.
Make spacings, corners and font sizes used in the filter, details and friends tabs more consistent.
Remove some unnecessary dark UI rect backgrounds.
Improve alignment of the number of friends with the heart icon for entries in the server list.
Improve layout of countries and types filters. Make the filters scrollable when there are many entries.
Refactor most of the server browser in preparation for replacing the DDNet and KoG tabs with a community filter, which will work like the countries and types filters. Split rendering of different server browser sections into multiple functions to improve readability. …
=> Overhaul server browser filter, details and friends tabs

src/game/server/teams.cpp
Currently when swapping this happens. I personally can't see why it was done like this.
```
1: /swap 2
3: /swap 4
Wait 30 seconds
1: /swap 2 // swaps
3: /swap 4 // creates a new swap request
```
=> Fix everyones swap getting reset when someone swaps

src/engine/client/serverbrowser.cpp, src/engine/serverbrowser.h, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp
New UI elements were being created for every server info after refreshing the server list. At the same time, old UI elements were not being deleted when the server info objects are deleted. The use of `mutable` for this purpose was also rather unclean.
Now, a separate `std::vector` of UI elements is kept for all server browser entries, instead of associating the UI elements directly with the server info.
=> Fix memory leak of server browser entry UI elements

src/game/editor/popups.cpp
=> check if quadpoint is selected and not if quad is selected

src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser.h, src/engine/serverbrowser.h, src/engine/shared/serverinfo.cpp, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp
Replace existing hard-coded support for two "networks" with support for a dynamic list of "communities" which are indexed by a string-ID, though right now the DDNet and KoG communities are still hard-coded. The communities now also support an arbitrary number of associated countries, types and servers. This is a refactoring to prepare for getting the list of communities dynamically from the server and removing the DDNet and KoG tabs from the serverbrowser.
=> Support dynamic list of "communities" in engine serverbrowser, refactoring

src/engine/client/backend/vulkan/backend_vulkan.cpp
fixes the leak part in #7205
but not the killmsg stuff
=> Decrease descriptor pool's current size when descriptor is freed

datasrc/network.py, src/game/client/components/items.cpp, src/game/client/laser_data.cpp, src/game/client/laser_data.h, src/game/client/prediction/gameworld.cpp, src/game/server/entities/door.cpp, src/game/server/entities/dragger.cpp, src/game/server/entities/dragger_beam.cpp, src/game/server/entities/gun.cpp, src/game/server/entities/light.cpp, src/game/server/gamecontext.cpp
Fixes #7155.
Is based on #7200, but adds a flag NO_PREDICT to `DDNetLaser` that can be used by mods to tell the client not to predict it (this also disables the client-side blinking effect in switch layer), while `StartTick` is handled independently (-1 is sent to let the client decide it for non-player lasers).
=> Add prediction flag and custom starttick to ddnetlaser

src/engine/client/client.cpp, src/engine/client/client.h
It now resizes the screen when changing `gfx_screen_height`, `gfx_screen_width` or `gfx_screen_refresh_rate`. Closes #7215
=> Add console chain for screen resolution commands.

src/engine/serverbrowser.h, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/ui.cpp
Fix highlighted text of server browser entries not being refresh correctly when switching tabs.
This also reduces lag when switching tabs, as the UI elements for all tabs are now cached and don't need to be recreated when switching.
Regression from #7203.
=> Track UI elements separately for each server browser tab

src/game/client/components/hud.cpp, src/game/client/components/players.h
Respect the intratick when displaying the player position, speed and angle, to fix this information always being shown for the next tick. See #6417. This does not resolve the issue yet, as there are more HUD and player elements that need to make use of the intratick.
=> Fix 1-tick delay of player position, speed, angle HUD

src/game/ddracechat.h, src/game/server/ddracechat.cpp, src/game/server/entities/character.h, src/game/server/gamecontext.h
Adds `/lasttp` which will teleport you to the last position you did `/tp` to. Closes #6318
=> Add /lasttp

src/engine/client/input.cpp
We need to call `SDL_PumpEvents()` to ensure that we have the latest keyboard, mouse and joystick state before we use it.
See:
- https://wiki.libsdl.org/SDL2/SDL_GetKeyboardState
- https://wiki.libsdl.org/SDL3/SDL_GetMouseState#code-examples
Closes #7052.
=> Fix double-click handling with `gfx_asyncrender_old 0`

src/engine/server/authmanager.cpp, src/engine/server/authmanager.h, src/engine/server/server.cpp
When using `auth_remove`, the key indices for the default helper, mod and admin passwords were not properly adjusted, causing the wrong passwords to be used for the username-less logins.
The key indices for connected clients were also not properly adjusted, causing the wrong identity to be shown for currently authenticated clients when using the `status` command.
Closes #6427.
=> Correctly update auth keys when using `auth_remove`

src/engine/client/client.cpp, src/engine/serverbrowser.h, src/engine/shared/serverinfo.cpp, src/engine/shared/serverinfo.h, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp
This update shows if your friend is AFK in a server without you having to go in to find out. It will only show this inside the friends list. To make this work, I had to add a check for the "afk" key from server,json to the CServerInfo::CClient scripting.
Before:
After:
=> Show if your friend is AFK through friends list

src/base/system.cpp, src/base/system.h, src/game/client/components/menus_start.cpp
Fixes 1. of #6403
> The menu button should be updated to reflect whether the server is still running. For example the server may have been shut down manually with shutdown or it may have failed to start entirely due to the map missing or another issue.
=> Detect if server started from client is no longer running

src/game/editor/editor.cpp
I added buttons for zooming in and out in the envelope editor.  You can hold shift while clicking to switch between zooming horizontally and vertically. `NumPad+`, `NumPad+` and `NumPad-` now also zoom the envelope editor if it's hovered. Closes #6936
=> Add numpad shortcuts and button for zooming in envelope editor

src/engine/demo.h, src/engine/shared/demo.cpp
Previously, if the demo header strings did not contain zero-termination, the client would render the strings and any following non-zero memory from the demo header.
Now, demos will not be loaded, if any string in the header is not zero-terminated or not valid UTF-8.
=> Ensure strings in demo header are zero-terminated and valid UTF-8

src/engine/shared/config_variables.h, src/game/server/ddracecommands.cpp
Remove `sv_suicide_penalty`. It seems to have been replaced by `sv_kill_delay`, but was never removed.
=> Remove unused config, `sv_suicide_penalty`

src/game/client/components/controls.cpp
Instead of limiting the radius to the size of the game layer, it now instead extends all the way to kill-tile border. Mainly because sometimes a player is outside the game layer or you need to teleport high up in the sky to practice a part.
Before:
https://github.com/ddnet/ddnet/assets/141338449/22b6feba-c007-4b6d-8207-a6a06fd03fac
After:
https://github.com/ddnet/ddnet/assets/141338449/f83d2e20-ed7d-4c15-911b-0a7e942b0baa
=> Increase freeview radius to kill tile border

src/engine/server/register.cpp
Fixed so that `sv_register_extra`, `sv_register_url` and `sv_ipv4only` all call `OnConfigChange` when changed.
=> Configs used in Register OnConfigChange should have Conchain

src/game/gamecore.cpp, src/game/server/entities/character.cpp
Dead reckoning has been broken for quite some time now due to a Reset call clearing out past state in an unintended way. (#7170) 
This is my proposed replacement for #7171
=> Fix dead reckoning

src/base/system.cpp
This mostly reverts #6937 by making our `IOHANDLE` effectively `FILE *` on all systems again. We still use `CreateFileW` to open a `HANDLE` initially so we can specify the necessary flag so the file can be moved/deleted while open, which we can't do with the `FILE *` based `fopen` functions on Windows. This brings back the automatic I/O buffering on Windows, causing significantly less system calls when saving files. Closes #7226.
=> Use `FILE *` on Windows again, only use `HANDLE` for opening

src/engine/client/backend/opengl/backend_opengl.cpp, src/engine/client/backend/opengl/backend_opengl3.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h
Simplify the handling of free texture indices by using `-1` only for indices which are currently in use, whereas the size of the vector is now used to indicate the last free index. Otherwise the assertions incorrectly detect the last texture index always being in use because `-1` was used for both states.
Ensure OpenGL texture index vectors are large enough, in the unlikely case that the wanted texture slot is larger than twice the size of the original texture vector.
=> Add assertion when double-freeing texture index, ensure OpenGL texture vectors are large enough

src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
Adds `votes` command, which lists votes along with their description and command. it's paginated with 20 votes per page. Closes #7160
=> Add votes command to rcon

src/engine/client/client.cpp, src/engine/server/server.cpp, src/engine/shared/snapshot.cpp, src/engine/shared/snapshot.h
Instead of keeping track of a permanently empty `CSnapshot` object in client and server separately, add `CSnapshot::EmptySnapshot` to access a singleton empty `CSnapshot`.
Mark pointer parameters of snapshot functions as `const` when possible.
=> Add `CSnapshot::EmptySnapshot`, mark pointer arguments as `const`

other/bundle/client/Info.plist.in
This change allows the client to use the Gamemode feature from macOS 14 by specifying the app category at Info.plist.
=> Make Gamemode get enabled when playing DDNet in macOS 14

src/game/server/player.cpp
Otherwise player will show as AFK in the server list until `ExpireServerInfo()` would be called, e.g. when someone else joins.
=> Expire server info when changing `m_Afk`

other/manifest/client.manifest.in
We previously only defined compatibility with Windows Vista and 7. Now we define compatibility with Windows Vista - 11, which is what we currently support.
This means that Windows 8 - 11 will no longer try to run the client in a compatibility mode for Windows 7 applications. This should effectively not change anything, as we don't directly use any of the [components that function differently depending on the compatibility information](https://learn.microsoft.com/en-us/windows/compatibility/application-executable-manifest#manifestation).
=> Add flags for compatibility with Windows 8 - 11

src/engine/client/client.cpp, src/engine/client/client.h, src/engine/client/graphics_threaded.cpp, src/engine/client/sound.cpp, src/engine/shared/config_variables.h, src/game/server/gamecontroller.cpp
Using `dbg_stress 1` now only does the following (in debug build):
- Randomly send inputs.
- Randomly send chat messages.
- Randomly connect/disconnect to server configured with `dbg_stress_server` (`localhost` by default).
Previously it also did the following, which is not useful for this debugging feature and only complicates the code unnecessarily:
- Cause images and sounds not to be loaded.
- Render only every tenth frame.
- Always use inactive graphics refresh rate.
Using `dbg_stress 1` on a server made clients always auto-join team 0 and nothing else, which is not useful on its own for stress testing.
=> Limit effects of `dbg_stress` to features useful for debugging, remove remains of `dbg_stress` from server 

src/game/server/ddracecommands.cpp
rcon tele didn't previously unfreeze nor reset speed
now it should
=> Quality of life ; rcon tele small changes

src/game/server/entities/character.cpp
I missed the fact that the world does not stay `nullptr` should have tested more thoroughly.
=> Fix the fix to dead reckoning

src/game/client/ui.cpp, src/game/client/ui.h
Refresh UI label text containers when the glyph count of the read-cursor has changed.
Regression from #7203.
=> Fix mangled highlighted text in server browser

src/engine/shared/config_variables.h, src/game/client/components/menus_settings.cpp, src/game/client/components/nameplates.cpp, src/game/variables.h
Splits `cl_show_direction` into `cl_show_direction_other` and `cl_show_direction_own` allowing players to toggle them independently. 
`cl_show_direction_own` shows dummy keypresses as well (doesnt work in playback)
=> Ability to show local keypresses only

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
Only embedded images are allowed to be exported, but also embedded vanilla images.
=> add export image button

src/game/client/components/chat.cpp, src/game/client/components/chat.h, src/game/client/lineinput.cpp, src/game/client/lineinput.h, src/game/variables.h
Made for the top1 teeworlds tiktoker [teeworldseasy](https://www.twitch.tv/teeworldseasy). Who is live 24/7 and occasionally leaking his save password.
https://github.com/ddnet/ddnet/assets/20344300/cd357d64-50f2-484b-9264-2a6f1c1b0c1b
https://www.youtube.com/shorts/mPZ_zhz1Pew
=> Add streamer mode to avoid leaks

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
As suggested in #7176.
- Export button is now available for sounds.
- Filename is now by default the assets name
- Use `dbg_assert` for `Invalid image format`
=> Add export button to sounds

src/game/client/components/menus_browser.cpp
The server list was being resorted every frame when the server details of a favorite server were being rendered, which was causing the FPS to drop by a factor of 5.
=> Fix large FPS drop rendering server details of favorite server

src/engine/shared/serverinfo.cpp
Otherwise will servers that don't send it be considered invalid and not shown in the browser.
=> Make IsAfk attribute optional

src/engine/client/client.cpp
This line shouldn't be here. It causes really weird issues on Non-DDNet servers.
=> Don't run `GET_INT` on afk attribute in `ProcessServerInfo`

src/game/client/components/nameplates.cpp
Now you would be able to see which keys your dummy is holding while in freeze.
=> Use `m_aInputData` for dummy in `cl_show_direction`

data/autoexec_server.cfg
Deleted `sv_score_folder` and `sv_rank_cheats` from `autoexec_server.cg`. As both of them don't exist.
=> Remove unused commands from `autoexec_server.cfg`

src/game/server/player.cpp
Currently it's only sent if the scoreboard is open. This will cause the ping shown in the "Server info" tab not to be updated. So, if you have never opened the scoreboard before. It would just show 0
=> Send the player's latency if a menu is open

src/game/server/ddracechat.cpp, src/game/server/entities/character.h, src/game/server/player.h
It's now moved to `player.h` so it's persistent after death and only reset when the map changes. Which makes it way nicer to use.
=>  Don't reset `/lasttp` position on death

src/game/client/components/menus.cpp, src/game/client/components/menus.h
Remove unnecessary check for duplicate menu images. Listing directories with the storage now prevents duplicates, so this additional check is not needed anymore.
Ensure menu images are in RGBA format.
Ensure menu image names are not truncated.
Minor code format improvements.
=> Refactor menu image scan

src/game/client/components/ghost.cpp, src/game/client/components/ghost.h, src/game/client/components/killmessages.cpp, src/game/client/components/killmessages.h, src/game/client/components/players.cpp, src/game/client/components/players.h, src/game/client/gameclient.cpp, src/game/client/render.h
At least with the method I described in https://github.com/ddnet/ddnet/issues/7205#issuecomment-1742842164, I cannot reproduce the assertion anymore. It previously happened in several components. In particular, this assertion also happened when rendering players and the HUD, for which the only explanation was that the gameclient render info was already wrong, which is fixed by 96ef1fbc88d21966c581176afab71ed5dca69004.
Closes #6882. Closes #7205.
=> Fix crashes when rendering tees after skins are updated

src/game/server/ddracechat.cpp, src/game/server/ddracecommands.cpp
`tele` and `/tp` will now teleport the player to their cursor if they aren't paused or used one of the optional arguments.
https://github.com/ddnet/ddnet/assets/141338449/8a217199-c13d-47fc-a077-3b4360afe3f4
=> Teleport the player to their cursor if they aren't in pause

src/game/server/ddracechat.cpp, src/game/server/teams.cpp
Before:
After:
:warning:  **Breaks chat parsers.**
=> Teeworlds style name quoting for team joins

src/engine/shared/datafile.h, src/engine/shared/map.cpp, src/game/editor/editor.cpp, src/game/editor/mapitems/map_io.cpp
When `IMap::Load` fails, other components will continue to use the old map. However, if `IMap::Load` failed after the map was already successfully read with the datafile reader then other components kept their pointers to the old, invalid datafile reader items and data, causing random crashes in collision code. This is fixed by using a separate datafile reader to read the new map and only applying the datafile reader globally when loading was entirely successfully.
An error message is added for the case that a map has an unsupported version, which is currently the only case where a map can fail to load after the datafile was read successfully.
In particular, the block maps `blmapPepe`, `blmapV5` and `blmapDT-UPTU` did not have a version map item and were fixed separately.
Closes #7218. …
=> Ensure current map is not corrupted when loading another fails

src/game/server/entities/character.cpp
I was fooled by the tuning line in the constructor of `CWorldCore`. The tunings are supposed to be what vanilla clients can know, not what ddnet clients can know.
=> Fix the fix to the fix to dead reckoning

src/game/client/components/players.cpp
Previously it would always show the same angle if you were paused but then it would snap back to the actual angle when you exited pause.
Before:
https://github.com/ddnet/ddnet/assets/141338449/57c910a5-9f17-42e2-8ed3-c948d2228561
After:
https://github.com/ddnet/ddnet/assets/141338449/88b02156-0330-40cc-b494-12dd02ea3de0
=> Don't use mouse position for angle if paused.

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
If you only need many points on one specific channel it is currently hard to have simpler interpolations on the other channels. This should make it a bit easier to work with envelopes with many points. This is just a prototype, any ideas or alternatives are welcome.
=> implement project-onto operation for envelopes

src/game/server/entities/character.cpp
I really hope this is the final version of this. I made 5 test maps with different combinations of tunezones and tunes, played through 2 maps, didn't notice any oddity. Prediction is just so confusing, don't think I'll ever be touching it again :cold_sweat:
=> Vanilla tunings should be used for reckoning

src/game/editor/editor.cpp, src/game/editor/editor.h
Currently when you want to use `str_format` for the tooltip you have to create a buffer for it. But when setting the tooltip from other classes this becomes a bit problematic, because the buffer still has to be part of `CEditor` to avoid nullptr exceptions.
=> store editor tooltip in optional string

src/game/client/components/menus.cpp
The popup to show the completed demo rendering was also shown when the demo to be rendered could not be loaded or if the demo render popup was cancelled. Now the popup is only shown when the demo rendering was successful.
The layout of the popup is made consistent with other message popups. Long text is wrapped over multiple lines instead of decreasing the font size.
=> Fix demo render complete popup opening on error, improve layout

src/game/client/components/menus_demo.cpp
When using the demo filter and the selected demo name does not match any visible demo item, temporarily reset the selected demo index instead of keeping an incorrect demo index. This makes the behavior consistent with the server browser.
=> Fix selected demo index being desynced with selected demo name

src/base/system.cpp
See https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw#remarks
=> Fix leak of command line arguments on Windows

.clang-tidy, src/base/log.cpp, src/base/system.cpp, src/engine/client/client.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/serverbrowser_http.cpp, src/engine/client/serverbrowser_ping_cache.cpp, src/engine/client/steam.cpp, src/engine/server/databases/sqlite.cpp, src/engine/server/register.cpp, src/engine/shared/jsonwriter.cpp, src/engine/shared/kernel.cpp, src/game/client/components/menus_settings.cpp, src/game/editor/editor.cpp, src/game/editor/mapitems/layer_quads.cpp, src/game/editor/mapitems/layer_sounds.cpp, src/game/editor/mapitems/layer_tiles.cpp, src/game/editor/popups.cpp, src/game/server/gamecontext.cpp, src/game/server/gamemodes/DDRace.cpp, src/tools/map_replace_area.cpp
Fix additional clang-tidy errors that are found when running the current checks with clang-tidy 16.
Remove some obsolete suppressions and fix the errors instead.
=> Fix additional clang-tidy 16 errors, remove some obsolete suppressions

src/engine/shared/config_variables.h, src/engine/textrender.h, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp, src/game/client/ui_rect.cpp, src/game/client/ui_rect.h
Improve layout of demo browser buttons, search and checkbox. Use icons for most buttons. Decrease size of UI elements.
Move demo details from below the file browser to a side panel on the right, which is the same size as the server browser side panel. Use ellipsis to truncate the SHA256 instead of rendering only half of it with reduced font size. Show "map not included" instead of "0.00 KiB" for the map size of demos that don't include a map.
Remove the "Markers" column, as it is not very useful to see for all demos and sort by.
Closes #7275.
Screenshots:
- Before (1920x1080):
- After (1920x1080):
- Before (1280x1024):
- After (1280x1024):
=> Overhaul demo browser UI

CMakeLists.txt, src/game/editor/component.cpp, src/game/editor/component.h, src/game/editor/editor_object.cpp, src/game/editor/editor_object.h
This class is slightly more light-weight than a `CEditorComponent` and its naming makes it more natural to inherit for envelope points, proof-mode positions etc.
=> Add `CEditorObject` class

src/game/client/components/menus_browser.cpp
=> server info: show clanmates in different color

src/game/server/teams.cpp
Now it will only disable practice when using `kill`, I only added this to `SV_TEAM_FORCED_SOLO` because it's already possible to keep practice on death in team by not touching the startline. Closes #7304
https://github.com/ddnet/ddnet/assets/141338449/eb795d8f-0f37-4353-ae2e-79448b607150
=> Don't disable practice on death.

src/game/client/components/menus_settings.cpp
It will now automatically set the zoom to what you adjusted it to in settings. Previously you would have reconnect or run `zoom`, which is quite confusing for new players.
https://github.com/ddnet/ddnet/assets/141338449/f29b1cb0-23b9-47c8-bb4e-a853639c5f8d
=> Reset zoom when adjusting default zoom in settings

src/engine/textrender.h, src/game/editor/editor.cpp
The editor now has three icons for switching between the different modes instead of having one button that would cycle through the modes. Closes #7313.
=> Use icons for editor mode switching.

src/game/client/components/menus_settings.cpp
"Regular background color" setting is now moved to background instead of miscellaneous. Also made the capitalization correct.
"Entities Background color" -> "Entities background color"
"Regular Background Color" -> "Regular background color"
Before,
After,
=> Move "Regular background color" setting to background

src/game/editor/mapitems/map_io.cpp
The entire `CEditorImage` was being overwritten when loading external images, which was causing the already loaded image name to be cleared, due to the changed order of operations (regression from #7008). This is fixed by using `CImageInfo` to load the image and only copying the relevant members to the `CEditorImage`.
=> Fix names of external images not being loaded in editor

src/game/server/teams.cpp
Previously if you did `/save` on a solo server or one with teams disabled. It would announce the team the ID is in. But if it was ID 0, it would announce that everyone died :D Now it will just send killmsg of the player name instead of a team.
=> Don't announce team killed if it's a solo server.

src/engine/client/notifications.cpp
Seen in https://forum.ddnet.org/viewtopic.php?p=71604
=> Make sure notification object exists

src/engine/shared/console.cpp
Previously it would show the max length with the '\0' included, which makes the help text kinda misleading. I wasn't able to find a way to do this with the previous macro method of doing it.
I guess #5523 would also be pretty easy to fix if we start using `str_format` to build the help string.
=> Show correct max length in help text for `MACRO_CONFIG_STR`

src/game/server/ddracecommands.cpp
The wrong team variable was read.
=> Fix save_dry command

src/base/system.cpp, src/engine/client/input.cpp, src/engine/client/text.cpp, src/engine/gfx/image_manipulation.cpp, src/game/mapbugs.cpp
The TODO in the `Dilate` function is removed, as the code already appears to be safe without additional checks. The variable `k` is at most `(w * h - 1) * BPP`, as `ix` and `iy` are clamped to maximum `w - 1` and `h - 1` respectively. Because `p < BPP - 1` the index `k + p` is therefore always valid for the buffers. (The caller must ensure that the source and destination buffers are of size `w * h * BPP`.)
=> Remove obsolete clang-tidy `NOLINT` comments

src/game/client/components/menus.cpp
The filename editbox and buttons of the demo render popup were rendered excessively large on Android. While too small buttons could be an issue with smaller screens, this should not be implemented solely this popup, if Android support is revived in the future, as it makes the UI layout code harder to maintain.
Screenshots: 
- Before (assuming Android-specific layout was used):
- After (same as on other systems):
=> Remove Android-specific layout code for demo render popup

src/game/client/components/menus.cpp
Screenshots:
- Before (16:9):
- Before (5:4):
- After (16:9):
- After (5:4):
=> Improve layout of demo render popup on 5:4 resolutions

src/game/client/components/menus_demo.cpp
There is no reason to slice a demo while currently rendering it and it may cause issues because multiple demo players would access the same `IVideo` instance.
=> Disable demo slice button while demo is being rendered

src/engine/shared/demo.cpp
Previously all sliced demos used type "client", even if the original demo had type "server". Now the type of the original demo is copied when slicing.
=> Preserve demo type when slicing

src/engine/client/client.cpp, src/engine/shared/demo.cpp, src/engine/shared/demo.h
Use member instead of static variables for demo player snapshot data. The static variables would otherwise cause issues when multiple demo players are playing at the same time, especially demo players used in background jobs for replay demo slicing. This hopefully closes #7068.
Previously all demo players checked `IVideo::Current` to render a video, which would cause issues when rendering a demo while a demo slicing background job is running. Now video rendering can be toggled for each demo player individually and is only enabled for the main demo player.
=> Use member variables for demo player snapshot data, enable use of video recording for each demo player individually

.github/workflows/style.yml, scripts/check_unused_header_files.py
As the shell script is pretty slow, taking roughly 84 seconds in the CI, whereas the equivalent Python script takes only 1 second.
=> Rewrite unused header style check shell script in Python

src/tools/map_diff.cpp, src/tools/map_extract.cpp
The map version was only checked if the version item is present, which is different from how client and editor load maps. Now a missing version item is considered an unsupported version. Additional log messages are also added to the tools.
=> Fix map version checks in map_diff and map_extract tools

src/engine/client/input.cpp, src/engine/client/input.h
Avoid using a global variable for last mouse position on Android.
=> Replace static variables in `MouseRelative` with member variable

src/game/client/gameclient.cpp
The player info snapshot item (`CNetObj_PlayerInfo`) has its own `m_ClientID` member variable in addition to the generic snapshot item ID. The snapshot item ID was only used to set `m_Snap.m_LocalClientID` but without being checked for invalid values. Now it is checked that both IDs are identical and only `m_ClientID` is used consistently.
=> Fix client crash on player info snapshot item with invalid ID

src/base/system.cpp, src/base/system.h, src/engine/client/client.cpp, src/engine/demo.h, src/engine/shared/demo.cpp, src/engine/shared/demo.h, src/engine/warning.h, src/game/client/components/menus.cpp, src/game/client/components/menus_demo.cpp, src/game/client/gameclient.cpp
The demo linked in #7349 is now considered invalid and fails to load.
Demos which were simply truncated due to the client crashing during the recording can usually still be opened but the playback will be stopped entirely when an error is encountered reading the demo until the end.
=> Validate ticks when reading demo chunk headers, check for all file errors in demo player, show demo error popup

src/game/client/lineinput.cpp
Previously, the IME candidate window was aligned with the top-right corner of the text bounding box (when rendering the text until the caret offset). This does not work correctly for text spanning multiple lines, causing the IME candidate window to be displayed at the X position of the longest line instead. Additionally, text clipping in the chat was not considered, as `CLineInput` is not aware of the clipping implemented in `CChat`, causing the IME candidate window to be moved up too far.
This is fixed by getting the correct rendered position of the caret offset using `m_CursorRenderedPosition`. Vertical alignment is also changed so only one line of text is considered, which makes the behavior more consistent with Windows' native IME candidate window and avoids larger changes in …
=> Improve positioning of IME candidate window for multi-line text

src/engine/client/client.cpp, src/engine/editor.h, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
When leaving the editor pause any sound preview that is playing.
When playing a file dialog sound preview pause the toolbar sound preview if it's playing.
When switching selected sound stop the previous sound preview if it's playing.
**File dialog**
Unload (stop) the sound of the preview when:
- closing file dialog using `Cancel`
- closing file dialog using `escape`
- adding selected sound using `Add`
- saving selected sound using `Save` (when exporting)
- replacing selected sound using `Replace` (when replacing)
closes #7256
=> Editor: stop/pause sound previews

src/game/client/components/menus_settings.cpp
Previously you were able to set `cl_hook_coll_size` to 100, if you changed it via settings. But the max value for the setting itself is 20.
=> Use correct max value for "Hook collision width" setting

src/game/client/components/menus.cpp, src/game/client/components/menus_demo.cpp
Use `m_aCurrentDemoSelectionName` and `m_DemolistStorageType` for the demo render popup instead of using `m_DemolistSelectedIndex`, which can be invalid when the demo render popup is not opened from the demo browser.
Closes #7347.
=> Fix crash when directly rendering demo after slicing, fix demo slice confirmation popup not being shown anymore

src/game/client/components/mapsounds.cpp, src/game/editor/popups.cpp
The sound layer previously had the "Detail" property, and if enabled would make the sound not play if `gfx_high_detail` was disabled. Which makes no sense, as GFX has nothing to do with sounds.
=> Remove "Detail" from sound layers.

CMakeLists.txt, src/tools/demo_extract_chat.cpp
This adds `demo_extract_chat` which can be used to extract chat/broadcast from demo. Output is printed to stdout.
Example output:
```
chat: *** 'nameless tee' entered and joined the game
chat: nameless tee: Hello!
broadcast: Welcome!
teamchat: brainless tee: Hello team!
whisper: -> nameless tee: Hi!
```
Closes #7361
=> Add new tool `demo_extract_chat`

src/engine/shared/demo.cpp
Check whether the demo file has been closed due to a playback error when calling `DoTick` in loops, to prevent crashes on operating systems with assertions for correct C library usage. On Windows, `warning: Invalid parameter passed to C runtime function` was printed to the debug console in this case.
See https://github.com/ddnet/ddnet/pull/7369#issuecomment-1779766832.
=> Fix use of closed demo file when playback stopped due to error

src/game/client/components/menu_background.cpp, src/game/client/components/menus.cpp, src/game/client/components/menus_settings.cpp
Only consider `STATE_ONLINE` and `STATE_DEMOPLAYBACK` as ingame.
Closes #7178.
=> Fix incorrect menu behavior when quitting/restarting

src/engine/shared/config_variables.h, src/game/server/scoreworker.cpp, src/test/score.cpp
This adds the ability to disable the printing of regional rankings in `/top5` and `/rank`. Most servers aren't split across multiple regions which leads to the `/top5` being effectively printed twice.
`sv_regional_rankings 1` (default)
`sv_regional_rankings 0`
=> Add option to disable printing of regional rankings.

src/game/client/components/console.cpp, src/game/client/components/console.h
Add auto completions for commands that take a command/config as their first argument.
https://github.com/ddnet/ddnet/assets/141338449/6b025409-724e-49db-a568-f8886f14ed53
=> Add argument completion for `reset`, `toggle`, `access_level`

src/engine/client/ghost.cpp, src/engine/shared/config_variables.h, src/game/client/components/ghost.cpp, src/game/client/components/ghost.h, src/game/client/components/menus.h, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/players.cpp
This tries to improve and fix some issues of the current ghost system. Changes done: 
- Option to always save ghost even if it wasn't a personal record.
- Increase max active ghosts from 8 to 256.
- Option to disable ghost map checking by hash. Enabled by default, as DDNet maps keep changing.
- Separate option to configure opacity instead of using `cl_show_others_alpha`
- Button to enable/deactivate all ghosts.
- A column showing the date when the ghost was done.
- Some UI changes. Use icon for refresh button, a button to open the ghost directory.
The new config options are `cl_race_ghost_strict_map`, `cl_race_ghost_save_best`, `cl_race_ghost_alpha`
With these new changes, you could create pretty cool clips like this one. With a whopping 256 ghosts. …
=> Various improvements to ghosts

src/base/system.cpp, src/base/system.h, src/game/client/components/menu_background.cpp, src/game/client/components/skins.cpp, src/game/server/player.cpp
Add easter, halloween and xmas to `enum ETimeSeason` and `time_season` function. This unifies the logic for detecting these events and seasons in one function. This allows adding support for special easter, halloween and xmas theme maps in the future. The `localtime` function is not used outside `system.c` anymore. The code for detecting easter is taken from upstream.
=> Add event dates to `time_season`: easter, halloween, xmas

src/engine/client/ghost.cpp, src/engine/shared/config_variables.h, src/game/client/components/menus_settings.cpp, src/game/client/gameclient.cpp
- Make ghosts be rendered before players, as suggested in #7378
- Remove redundant map check when loading ghosts, as it's already checked a few lines above.
- Better description for `cl_race_ghost_strict_map`
=> Small fixes to ghosts

src/game/client/components/killmessages.cpp
As `cl_showpred` isn't shown in demos anymore after #7261.
Before
After
=> Align kill messages properly in demos when using `cl_showpred`

src/game/server/entities/character.cpp
Fixes double jump effect not being rendered for other players.
This bug only affected 0.7 clients on ddnet servers.
=> Add sixup server triggered events translation

src/engine/shared/config_variables.h
Added the information wished for in. #7229 ^>^
Changed `Sound buffer size` to `Sound buffer size (may cause delay if large)`.
=> Altered `snd_buffer_size` description. Fixes #7229

src/game/client/components/maplayers.cpp, src/game/client/render.cpp, src/game/client/render.h, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/mapitems/layer_group.cpp, src/game/editor/mapitems/layer_group.h, src/game/editor/mapitems/map.cpp, src/game/editor/mapitems/map_io.cpp, src/game/editor/popups.cpp, src/game/layers.cpp, src/game/layers.h, src/game/mapitems_ex.cpp, src/game/mapitems_ex.h, src/game/mapitems_ex_types.h
Parallax Zoom improves the appearance of maps visually when zooming. Contrary to initial tests, it does not interfere with certain map locations, such as the shop on the map Timeshop.
The default value appears to be correct for all existing maps.
The value in the map file is non-trivial to manage, and provides little benefit. See #6196 for further discussion.
Interesting could be if there are more maps nowadays, which set custom values. And then also if those maps use the value correctly.
The opinion of mappers would also be interesting.
I can see this customizability coming back in some shape or form, but as of now, I don't see a reason for this to be integrated into the map file.
On the other hand, it does have downsides like side effects on modification and nudging mappers into editing …
=> Remove Parallax Zoom from map file

src/game/server/entities/character.cpp, src/game/server/scoreworker.h, src/game/server/teams.cpp
Previously demos recorded with `sv_player_demo_record 1` would abruptly end as soonest the player hit the finish line. It now delays the end by 1 second. Closes #5775
https://github.com/ddnet/ddnet/assets/141338449/9e14a5a8-546a-41f9-8bad-209a83beed5b
=> Delay server race demo ending by 1 second.

src/game/client/components/ghost.cpp, src/game/client/components/menus_ingame.cpp
Previously the wrong ghost would be shown/loaded when finishing a run that's worse than your best time. Closes #7387
=> Fix incorrect ghost being loaded with `cl_race_ghost_save_best`

src/game/server/gamecontext.cpp, src/game/server/player.cpp, src/game/server/player.h
I broke it in #7262, because I thought `SetAfk` would just set `m_Afk`. The original function is now renamed to `SetInitialAfk` which is more representative of what it does. As reported by @0xfaulty in the original PR.
=> Fix afk timer not working.

src/game/server/scoreworker.cpp, src/test/score.cpp
This resurrects the underline under the top 5 list when using  `sv_regional_rankings 0`.
Fixes #7395.
Demonstaration:
=> Added back underline for `sv_regional_rankings 0`.

src/game/client/components/mapimages.cpp, src/game/client/components/mapsounds.cpp
The image name is only required for external images. For embedded images it was only used in log messages. This fixes rendering with various maps that have embedded images with invalid names.
Show a warning popup when a map image or sound cannot be loaded for any reason. Only one generic warning popup is shown for images and sounds individually.
See #7397.
=> Allow loading embedded images without valid image name, show warning popup when map image/sound cannot be loaded

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/game/client/components/mapimages.cpp, src/game/client/components/mapsounds.cpp, src/game/client/components/menus_start.cpp
Using `CMenus::PopupWarning` will immediately set the popup and override the current warning, which can hide warnings when multiple are shown at the same time. Now all warnings are added to the queue with `IClient::AddWarning`.
=> Add gameclient warnings to queue instead of overriding others

src/game/client/components/menus_browser.cpp
Friends/Clanmates in the info tab are now shown in their "afk" colours as well. While non-friends that are AFK are just shown with EMOTE_BLINK. Closes #7312
=> Show AFK status in info tab

src/engine/shared/datafile.cpp, src/engine/shared/datafile.h
Previously, the client would crash with an assertion when writing more than 1024 items, 1024 data items or 64 extended item types to a map file. This arbitrary limitation is removed by using `std::vector`s, so much larger maps can be written. This was only a limitation when writing map files. Old clients can correctly read the map files having more items/data but will crash when the map is saved in the editor.
=> Support writing maps with more items/data

src/game/client/components/menus.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/editor/editor.cpp
Add buttons for selecting the color mode (RGBA, HSVA, HSLA) in color picker popups in menu and editor. Previously, the color picker popups always showed the color components in HSVA. Now the mode can be switched so the components are shown in either RGBA or HSLA. The hex color code is always RGBA, same as before.
In the editor, the RGBA mode is used per default, to prevent any loss of information due to color conversions, as the map format stores RGBA values. In the menus, the HSVA mode is the default, same as before, although the config actually stores HSLA values.
The HSVA color picker controls (1D slider for hue, 2D picker for saturation and value) are still shown for all modes.
As many color conversions as possible are avoided by only converting between color formats when necessary. …
=> Add mode selection to color picker popups (RGBA, HSVA, HSLA)

src/base/system.cpp, src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h
After the error message popup is shown for graphics assertions, the client window was destroyed but the process was not terminated properly. Now the graphics assertion error is handled like a normal assertion error, as those are also shown in an error message popup and correctly cause the client to break into the debugger or terminate.
However, calling `dbg_assert` while already owning the lock that `WaitForIdle` waits on will cause a deadlock, so error handling must be delayed until after the lock is released.
The buffer size for assertion messages is increased, as it was not sufficient for some graphics assertions.
The `ICommandProcessor::GetError` and `ICommandProcessor::GetWarning` functions are marked as `const`.
=> Fix client not quitting after graphics assertion

src/game/editor/editor.cpp
=> Use correct corners for brush rotation buttons.

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/explanations.cpp
The failing assertion is removed because users can add custom entities images besides the predefined ones.
Reported by Mr.Gh0s7 on Discord.
=> Fix editor crash when showing explanation for custom entities

CMakeLists.txt, src/base/math.h, src/test/math.cpp
Round to nearest integer instead of truncating in `f2fx` to ensure correct round-trip with `fx2f`.
Add test to ensure correct round-trip with maximum `0.0005f` absolute error.
=> Fix inaccurate envelope point value rounding

src/game/editor/editor.cpp
When using ctrl+s to test the current envelope it should not activate the scale mode. This causes unexpected envelope changes on ctrl+s based envelope fine tuning testing.
Here a video of me showcasing the issue. I pressed ctrl+s to save the map and it started moving the envelope.
https://github.com/ddnet/ddnet/assets/20344300/0623b0ff-ae3f-4e6f-afbd-48db57ab9235
=> Do not scale envelopes on ctrl+s

src/engine/client/client.cpp, src/engine/config.h, src/engine/shared/config.cpp, src/engine/shared/config.h
This fixes `Allow client to still save settings that it doesn't know about.` from #6660. Previously if you were to use a different client such as Tater-Client which shares the same config file as DDNet, the settings used from Tater-Client would be lost if you were to launch up DDNet again.
=> Save unknown commands from `settings_ddnet.cfg`

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
Simplify selecting envelope point colors by showing a color picker button that opens a color picker popup to change the color of the selected envelope point. The existing editbox to change only the selected channel's value is kept, as the color picker popup does not support the same precision to specify the individual color channel values.
Closes #7317.
=> Show color picker button for color envelope points

src/game/client/components/camera.cpp
To a limit that fits to the biggest maps
the zoom limit doesn't matter perf wise anymore, maybe we could also remove it for newer backends, but on the other hand, who knows what floating point weirdness comes into play if u zoom out insanely far ^^
=> Increase max zoom limit

src/game/server/ddracechat.cpp, src/game/server/player.h
Previously it only saved the position, it now saves the entire character and behaves more like `/rescue`. Closes #7441, Closes #7339.
https://github.com/ddnet/ddnet/assets/141338449/821cbe33-634b-43a3-9a21-e6fca0f9adc1
=> Save entire character with `/lasttp`.

src/game/server/gamecontext.cpp
When the `CGameContext::SendChatTeam` function is used to send a chat message to all members of a DDTeam (e.g. on completed /swap chat command), it was not checked whether the target players are online but only whether they belong to the specified team according to the teams core. However, the default team for unconnected/cleared players is 0 in the teams core, which is the same for players in team 0, so chat messages were being sent to client IDs not corresponding to connected clients when chat messages where supposed to be sent to players in team 0. This was causing the server to crash with the assertion error "erroneous client id" specifically when the server is started with `sv_max_clients` being less than the default, maximum 64.
Closes #7450.
=> Fix server crash on DDTeam message with lower `sv_max_clients`

src/game/editor/editor.cpp
https://github.com/ddnet/ddnet/issues/7435
Now escape and right click should behave the same and fixes issue
=> Use Escape to cancel OP_SCALE envelope

src/tools/demo_extract_chat.cpp
Changed `Usage: demo_extract_chat [demo_filename]` to `Usage: demo_extract_chat <demo_filename>`.
`[ ]` are used for optional arguments, but `demo_filename` is a required argument.
=> Correct usage of `demo_extract_chat` tool.

src/game/editor/editor.cpp
After deleting a file `m_FileDialogFileNameInput` wasnt getting updated making it impossible to open the newly selected file.
=> Update `m_FileDialogFileNameInput` when deleting a file

src/game/client/components/menus_settings.cpp
It now updates the scaling of "text entities" when changing the size from settings. Previously it didn't nothing, and would only update when you restarted your game.
https://github.com/ddnet/ddnet/assets/141338449/8d841a76-e183-40dc-8408-7946cc0b3c9f
=> Set size of text when changing slider of `cl_text_entities_size`.

src/game/client/components/binds.cpp
Previously, if you tried to use `bind` or `binds` with a key written in captial  letters. e.g. `bind A +left`, it would give `key A not found`. It's now treated as case-insensitive instead.
=> Make KEY argument case-insensitive

src/game/editor/editor.cpp
The check for multiple storage locations was using the base path from the previous invocation of the file dialog instead of using the new base path.
Closes #7463.
=> Fix parent folder not being shown in editor file browser, fix typo

src/game/client/components/chat.cpp, src/game/client/components/chat.h
Sometimes you can write a long message and accidentally press either UP or DOWN arrow and loose all the text you were writing. This PR fixes that issue by preventing the input to be cleared when pressing DOWN arrow and saving the current input when pressing the UP arrow.
=> Save current chat input when pressing UP. Prevent input clearing when pressing DOWN

src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp
The community icon data loaded in background jobs was previously not freed when the client is quit before the community icon data is processed.
=> Fix leak of community icons when jobs not finished

src/game/client/gameclient.cpp
The client tries to execute all commands from maps, but this usually leads to tons of spam in the local console. Commands that aren't found are now no longer printed, as well as the "tune" message. Closes #4144 ?
=> Don't print "tunes"/unknown commands from maps.

src/base/log.cpp
Now it's also possible to use `dbg_assert` without/before having set a global logger.
=> Fix `nullptr` access on `dbg_assert` with no global logger

src/game/editor/map_grid.cpp, src/game/editor/map_grid.h
=> Fix map grid factor always being shown as 1

src/base/system.cpp, src/engine/shared/storage.cpp
On Unix, the encoding of filenames is unspecified, although UTF-8 is likely used in most cases. Detecting and converting from several possible encodings to UTF-8 would be too much effort, considering that most systems already use UTF-8 per default. Therefore, any filenames which are not valid UTF-8 will be ignored when listing directories with `fs_listdir(_fileinfo)`, `fs_storage_path` will fail if the storage location is not valid UTF-8 and `fs_getcwd` will fail if the current working directory is not valid UTF-8. Paths specified in `storage.cfg` must also be valid UTF-8.
On Windows, we already ensure that all filenames are converted to UTF-8.
=> Ensure filenames are valid UTF-8 on Unix

src/game/client/components/console.cpp, src/game/gamecore.cpp, src/game/gamecore.h
=> Make gamecore.h not depend on console

src/engine/shared/ringbuffer.cpp, src/game/client/components/console.cpp, src/game/client/components/console.h
Previously, the client would hang due to recursive usage of the console backlog lock when a log line is printed via the logger functions while already owning the backlog lock. This could happen when the text render causes log messages to be printed while the console backlog is rendered.
This is fixed by introducing a separate pending backlog to which new log lines are initially added and which is protected by a lock. The pending backlog entries are pumped into the normal backlog before the normal backlog is used, so accesses to the normal backlog do not need to be locked anymore. This means the console backlog lock is not owned when calling any functions that could print log messages, which should prevent the dead lock.
=> Fix dead lock when printing log entry while rendering console line

src/game/server/gamecontroller.cpp, src/game/server/gamecontroller.h, src/game/server/gamemodes/DDRace.cpp, src/game/server/gamemodes/DDRace.h
When creating a non ddrace controller and it uses `IGameController::GetMaskForPlayerWorldEvent` it will crash:
```
#0  0x00007ffff72ac83c in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff725c668 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff72444b8 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff749ca6f in __gnu_cxx::__verbose_terminate_handler () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#4  0x00007ffff74b011c in __cxxabiv1::__terminate (handler=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#5  0x00007ffff74b0189 in std::terminate () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#6  0x00007ffff74b03ed in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x7ffff766c0e8 <typeinfo for …
```
=> Fix crash in mod controller

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser.h, src/engine/serverbrowser.h, src/game/client/components/menus_browser.cpp
Previously:
```json
{
"ddnet": {
"name": "DDraceNetwork",
"servers-key": "servers",
"ranks-key": "maps",
"icon-sha256": "162313eeb954e34495ad03066fee1418ed3c963e76cc83dff993e1c7856c742b"
}
}
```
Now:
```json
{
"ddnet": {
"name": "DDraceNetwork",
"icon": {
"sha256": "162313eeb954e34495ad03066fee1418ed3c963e76cc83dff993e1c7856c742b",
"url": "https://info.ddnet.org/icons/ddnet.png"
},
"ranks": [
…
],
"servers": {
…
}
}
}
```
Special case `ddnet` to look for the `servers`, `maps` in the top-level and `kog` to look for `servers-kog` in the top-level.
=> Add icon URL, remove `servers-key`/`ranks-key` from community JSON

src/game/client/gameclient.cpp
Don't zoom below `cl_default_zoom` unless the player desires to.
closes #7331
=> multi-view: dont zoom below `cl_default_zoom`

src/base/system.h
Fix compilation with MinGW due to `memset` call added to `system.h` in #6256.
=> Add missing `<cstring>` include for `memset` to `system.h`

src/game/server/ddracechat.cpp, src/game/server/ddracecommands.cpp, src/game/server/gamecontroller.cpp, src/game/server/gamecontroller.h, src/game/server/gamemodes/DDRace.cpp, src/game/server/gamemodes/DDRace.h, src/game/server/score.cpp
Gets rid of more CGameControllerDDRace casts.
Those did not show up during compile time only during runtime of another active controller when asan is active.
=> Move `m_pLoadBestTimeResult` to `IGameController`

src/engine/client/serverbrowser.cpp, src/game/client/components/menus_browser.cpp
Ensure that community/country/type filters do not exclude all allowed elements, which can happen when a previously selected community is not available anymore or when arbitrary community filter values are set with the console.
Also update server browser filtering/sorting when changing the community/country/type filter config variables with the console.
Clean the filter config variables when they are changed instead of only when the community filter is rendered.
Closes #7494.
=> Prevent community filters excluding all elements, fix server browser update on community filter change via console

src/game/client/components/camera.cpp, src/game/client/components/controls.cpp, src/game/client/components/damageind.cpp, src/game/client/components/menu_background.cpp, src/game/client/components/menu_background.h, src/game/client/components/particles.h, src/game/client/components/spectator.cpp, src/game/client/prediction/entities/laser.cpp, src/game/client/prediction/entities/laser.h, src/game/client/ui_scrollregion.cpp, src/game/client/ui_scrollregion.h, src/game/editor/editor.h, src/game/gamecore.cpp, src/game/gamecore.h, src/game/server/entities/character.h, src/game/server/entities/dragger.cpp, src/game/server/entities/gun.cpp, src/game/server/entities/laser.cpp, src/game/server/entities/light.cpp, src/game/server/entities/pickup.cpp, src/game/server/gameworld.cpp
Due to #6256, vec2 members used in physics calculation are no longer initialized to 0. This PR fixes that.
Small cleanup to remove unused members (write only)
=> Init vec2 members to 0 and small cleanup

src/engine/client/client.cpp, src/engine/client/smooth_time.cpp, src/engine/client/smooth_time.h
This also simplifies the code a bit, and further separates ping calculations from the the margin (e.g. so it does not count towards ping spikes calculated in CSmoothTime).
=> Make prediction margin take effect instantanously

src/game/server/ddracechat.cpp, src/game/server/ddracecommands.cpp
Previously teleporting to cursor wasn't accurate when not using zoom 10. Closes #7510.
=> Account for zoom when teleporting to cursor.

src/engine/server.h, src/engine/server/server.cpp, src/engine/server/server.h, src/game/editor/editor.h, src/test/score.cpp
Both are equivalent. Seems to already be used consistently for all other types.
=> Use `const char *` instead of `char const *` consistently

src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/gfx/image_loader.cpp, src/engine/gfx/image_loader.h, src/engine/graphics.h, src/tools/map_replace_image.cpp
Greyscale images with alpha channel (i.e. channel count = 2) were incorrectly handled as RGBA images, causing the client to crash when loading such images. Now the images can successfully be loaded with the image loader, but the client still only supports loading RGB and RGBA images like before.
=> Handle all color channel counts in image loader, refactoring

src/engine/server/server.cpp, src/engine/server/server.h, src/game/server/gamecontext.cpp, src/game/server/gamecontroller.cpp, src/game/server/player.cpp, src/game/variables.h
Call expected server callback functions to simulate clients dynamically connecting and disconnecting when changing the `dbg_dummies` variable. This makes the debug dummies more useful for debugging. Previously, the debug dummies were considered invalid clients, whereas they are now considered to be ingame, so they should behave mostly like real clients being connected to the server. The debug dummies also have correct client names now, e.g. "Debug dummy 42".
The game server code is cleaned up by moving all special handling for debug dummies to the engine server function `CServer::UpdateDebugDummies`.
The left/right direction inputs for debug dummies are now properly added to the client input array, so their input handling should be consistent with normal clients, which fixes some …
=> Dynamically connect/disconnect debug dummies, cleanup

src/game/gamecore.cpp, src/game/server/entities/character.cpp
This fixes the hook going invisible issue reported on Discord, and potentially reintroduces the UB fixed in 6680ec388cb8b71f9fa73223d3af9d37148bd26a, however I could not reproduce the UB anymore using ubsan :/
Lesson learned, don't try to be smart :upside_down_face:
=> Revert the mess-chain #7247. Apply #7171

src/engine/server/server.cpp, src/engine/server/server.h
Also fix normal clients being disconnected/controlled like debug dummies.
Closes #7523.
=> Ensure debug dummies are not included in server info

src/engine/shared/console.cpp
We are only using int game settings at the moment so these bugs/fixes shouldn't have any effect on existing maps.
=> Fix string and color game settings not being reset correctly

src/game/client/components/statboard.cpp
It will now increase deaths/suicides when a team dies in the `+statboard`.
=> Count deaths in statboard from `KILLMSGTEAM`

src/game/server/gamecontroller.cpp, src/game/server/player.cpp
Previously it set the race precision value to 0, meaning there was no decimals in time values for 0.7.
Before
After
=> Set correct race precision value for 0.7

src/game/client/components/ghost.cpp, src/game/client/components/race_demo.cpp, src/game/client/gameclient.cpp
There is a lot of behavior that rely on `KILLMSG`, but that wasn't accounted for when `KILLMSGTEAM` was added. The following is now fixed when a team dies.
- Auto demo recording is now stopped.
- Ghosts are now stopped.
- Prediction not being reset.
=> More fixes to `KILLMSGTEAM`

src/engine/client.h, src/engine/client/client.cpp, src/engine/server.h, src/engine/server/server.cpp, src/game/client/components/items.cpp, src/game/client/components/killmessages.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/players.cpp, src/game/client/gameclient.cpp, src/game/client/prediction/gameworld.cpp, src/game/client/prediction/gameworld.h, src/game/gamecore.h, src/game/server/entities/character.cpp, src/game/server/teehistorian.cpp, src/game/tuning.h
Tried to replace the magic value `50` for tick speed with `SERVER_TICK_SPEED` or `GameTickSpeed()`/`TickSpeed()` where possible.
=> Replace `50` with `SERVER_TICK_SPEED` or `TickSpeed()`

src/game/client/components/chat.cpp
It now adds quotes around names when auto completing a name in a command. Ported from 0.7 (teeworlds/teeworlds#2585).
https://github.com/ddnet/ddnet/assets/141338449/a5e4881a-b8e7-42d9-a036-0eff79b5326a
=> Quote names with spaces when auto completing names in commands.

src/game/editor/popups.cpp
Previously it would just grey out the "Yes" button, but if you were to click "No". It was possible to enable it again. Which shouldn't be possible as "Allow unused" is only supported for "DDNet" entities
Before
After
=> Hide "Allow unused" button when not using "DDNet" entities.

src/engine/server.h, src/engine/server/name_ban.cpp, src/engine/server/name_ban.h, src/engine/server/server.cpp, src/engine/server/server.h, src/game/server/gamecontext.cpp, src/test/name_ban.cpp
Apply the name bans system also to player clans, meaning players joining with banned clan names are kicked and changing the clan to a banned name while ingame has no effect.
Additionally, trim UTF-8 whitespace from beginning and end of clan. This was already done for player names but not for clans.
Closes #7516.
Unify all code for name bans in new class `CNameBans` in the existing `name_ban.cpp/h` files. The previously global function `IsNameBanned` is now the member function `CNameBans::IsBanned`. The existing name ban tests are extended for the `CNameBans` class.
Move `CNameBan` constructor definition to source file to avoid including `system.h` in the header file. Use `bool` instead of `int` for `m_IsSubstring`. Reorder `CNameBan` constructor arguments and remove unnecessary default …
=> Also apply name bans to clans, trim space from clans, refactor name bans, move code to separate class `CNameBans`

src/engine/shared/config_variables.h, src/game/client/components/chat.cpp, src/game/client/components/chat.h, src/game/client/components/menus_settings.cpp
Closes #7531. To make this work, I had to refactor the code that does chat preview. I also made sure to always have some minimal ratio between chat font size and chat width so that we don't have a 5 character wide chat possible. This should also work when `cl_chat_old` is set to `1`.
https://github.com/ddnet/ddnet/assets/13364635/310d75ba-c38d-4773-96eb-c02debb00616
=> Added possibility to edit chat size and width

.github/workflows/build.yml
The old default version causes linking errors for the tests in the non-fancy Linux CI, i.e. with Ubuntu 20.04.
=> Remove unnecessary `rustup default 1.48.0` in non-fancy Linux CI

src/engine/client/client.cpp, src/engine/shared/http.cpp, src/engine/shared/http.h, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp
Add `CHttpRequest::ExpectSha256` function to specify expected SHA256 for HTTP downloads. If the download completes with a different SHA256 hash than expected, then the download fails and the file is deleted.
Closes #7485.
=> Check SHA256 of downloaded maps and community icons

src/game/client/components/controls.cpp, src/game/ddracechat.h, src/game/server/ddracechat.cpp, src/game/server/ddracecommands.cpp, src/game/server/gamecontext.h
`TargetX` and `TargetY` are now scaled by the zoom level.
The tele cursor behaviour is now also moved `/tc` and `/telecursor`.
=> Scale `TargetX` and `TargetY` by zoom level.

src/engine/client/client.cpp, src/engine/config.h, src/engine/console.h, src/engine/server/main.cpp, src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/config.cpp, src/engine/shared/config.h, src/engine/shared/console.cpp, src/engine/shared/console.h, src/game/client/components/console.cpp, src/game/client/components/console.h, src/game/client/gameclient.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/teehistorian.cpp
Move all code for handling of config variables from console to config manager. The console no longer depends on the config manager, instead the config manager now depends on the console.
Add `struct`s to manage config variables of different types (int, color and string). The config manager now keeps a list of all config variables, so usage of the preprocessor can be avoided except for code to initially create all config variables. Additionally, a separate list of just the game config variables (config variables with `CFGFLAG_GAME`) is kept to optimize the `ResetGameSettings` function, as this function is called whenever connecting to a server and should be fast. Previously, this function was even less efficient because it preformed a linear search for every individual game config variable …
=> Refactor config manager, move config variable handling

src/engine/client/client.cpp, src/engine/server/server.cpp
Added check if demo recorder is already active. Closes #7568.
=> Added check if demo recorder is already active.

src/base/system.cpp, src/base/system.h, src/engine/client/input.cpp, src/test/str.cpp
Add stricter error handling when converting between UTF-16 (wide characters) and UTF-8 (multi-byte) on Windows.
The `windows_wide_to_utf8` function now returns an `std::optional`, which will be empty if the argument contains invalid UTF-16. Files/folders with names containing invalid UTF-16 are now ignored on Windows. It was previously not possible to use these files either, as converting their names to UTF-8 changed the invalid codepoints to unicode replacement characters.
The `windows_utf8_to_wide` function now fails with an assertion error if the argument contains invalid UTF-8, as this should never happen.
Closes #7486.
=> Check for invalid unicode in filenames etc. on Windows

src/engine/server.h, src/engine/server/server.cpp, src/engine/server/server.h, src/game/server/gamecontext.cpp
Previously if you did `DDNet-Server "record a; shutdown"`. You would get the following assert `src/engine/shared/demo.cpp(47): Demo recorder was not stopped`. 
It now stops any recording demos on shutdown.
=> Stop all recording of server demos on shutdown.

src/engine/client/client.cpp, src/engine/kernel.h, src/engine/server/main.cpp, src/engine/shared/kernel.cpp
Support registering arbitrary number of interfaces with `IKernel` instead at most 32.
Assert when incorrect arguments are passed to `IKernel` functions instead of returning a `bool`, which was not being handled in all cases. These functions are not expected to fail expect on programming errors.
Consistently order and format creation and registration of kernel interfaces in client and server.
=> Support arbitrary number of kernel interfaces, assert on errors

src/engine/client/client.cpp, src/engine/server/server.cpp, src/engine/shared/packer.cpp
Ensure all packets are unpacked correctly before using the unpacked data.
Ensure strings are valid UTF-8 in `CUnpacker::GetString`.
_Add the GET parameter `w=1` to the URL for a small diff excluding indentation changes._
=> Add missing unpacker error checks for server and client packets

datasrc/network.py, src/engine/shared/config_variables.h
Setting a vote timeout longer than 60 seconds with `sv_vote_time` caused the vote network messages to be discarded with the error message `weird message 'Sv_VoteSet' (15), failed on 'm_Timeout'` by the client, as the protocol did not allow longer vote timeouts.
This changes the protocol so the vote timeout can be any positive integer although for now the maximum `sv_vote_time` value is changed back to 60 again to preserve compatibility with old clients.
Closes #7583.
=> Fix votes with timeout over 60 seconds not being shown in client

src/game/client/ui.cpp
The popup menu render function can open/close other popups, which may resize the vector of popup menus and thus invalidate the current popup menu variable before the popup is closed. We therefore store the popup UI element ID in a separate variable to avoid the access to the potentially invalidated popup menu variable after the popup menu is rendered.
Also prevent invalidated popup menu from being rendered for one frame after it is closed by clicking outside.
Closes #7565.
=> Fix heap-use-after-free when popup opens another popup

src/game/editor/editor.cpp
The invalid sound index is `-1` but the check in the editor for the sound preview assumed it was `0`. We should use a type-safe wrapper to avoid this in the future, like for texture handles.
=> Fix incorrect sound index usage for editor sound preview

src/base/system.cpp
=> Avoid setting `IP_TOS` on IPv6 sockets on Windows, fix incorrect error code logged in socket warnings

src/base/detect.h, src/engine/shared/engine.cpp
We support little and big endian but not PDP endian (Middle-endian).
Define endianness as string `CONF_ARCH_ENDIAN_STRING` to avoid conditional compilation when printing endianness.
=> Add compile time errors for unsupported endianness

src/game/server/player.cpp
The variable `Id` is translated for old clients and is not guranteed to be the real id. While `m_ClientID` is the real ID. That can also be used to index the CServer::m_aClients[] array to get the authed state.
closed #7599
Fixes
```
valgrind ./DDNet-Server "dbg_dummies 1"
[..]
2023-12-07 18:01:33 I chat: *** 'Debug dummy 1' entered and joined the
game
==75634== Conditional jump or move depends on uninitialised value(s)
==75634==    at 0x2DAA83: CVariableInt::Pack(unsigned char*, int, int)
(compression.cpp:17)
==75634==    by 0x2DAD79: CVariableInt::Compress(void const*, int,
void*, int) (compression.cpp:98)
==75634==    by 0x23EC50: CServer::DoSnapshot() (server.cpp:1046)
==75634==    by 0x247D2D: CServer::Run() (server.cpp:2994)
==75634==    by 0x230173: main (main.cpp:193)
==75634== …
```
=> Use real ClientID to lookup authed state

other/manifest/client.manifest.in
This reverts commit 744434be833971ead2de5d10e8abcd4056922339.
Potentially causing https://discord.com/channels/252358080522747904/757720336274948198/1175913806703108246
Will wait for feedback from this build before marking as ready (and potentially releasing a .1 release): https://discord.com/channels/252358080522747904/757720336274948198/1175933063730053160
=> Revert "Add flags for compatibility with Windows 8 - 11"

src/engine/client/text.cpp, src/engine/textrender.h, src/game/client/components/chat.cpp, src/game/client/components/console.cpp, src/game/client/components/console.h, src/game/client/lineinput.cpp, src/game/client/lineinput.h, src/game/client/ui.cpp
Based on @furo321's work (#7340).
I attempted to fix the bugs in this PR, the big thing is that now we can scroll line by line no matter if the console entry is multiline or not. For that, I had to basically add the ability to use a `LineSpacing` parameter to render the text in order to keep things consistent for 1 line entries and multiline entries.
I've tested it on multiple different resolutions and it seems to work quite well.
https://github.com/ddnet/ddnet/assets/13364635/4a77901f-cf39-4722-9b76-1181fd7abfe8
=> Add ability to scroll in console. Remove pages.

src/engine/shared/config.cpp
Prevent potential dead lock when using `/map` chat command in combination with Teehistorian. Closes #7619. I could not reproduce the issue on Windows though.
This also means resetting game settings should actually be efficient now, because it only involves iterating over all game settings and directly resetting their value.
=> Avoid using console to reset game settings

src/game/editor/editor.cpp
Fix too large rounding for some editor color picker buttons.
Screenshots (the color has alpha=100, so the incorrect border is visible in the before screenshot):
- Before:
- After:
=> Consistent rounding of editor value/color picker buttons

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings_assets.cpp, src/game/client/components/menus_start.cpp
Show localized text "Press a key…" instead of "???" while waiting for a key to be pressed.
Render button with green background while waiting for a key to be pressed.
Inline unnecessary `DoButton_KeySelect` function.
Fix names of static variables.
Screenshots:
- Before: 
- After:
=> Improve key reader button

src/game/client/components/chat.cpp
Moved reseting chat input history entry to `DisableMode()`. Currently it is not being reset when pressing Escape, which I believe is not intended.
=> Reset history entry along with chat input when using Escape

src/game/client/components/chat.cpp, src/game/client/components/console.cpp, src/game/client/lineinput.cpp, src/game/client/lineinput.h, src/game/editor/editor.cpp, src/game/editor/mapitems/layer_tiles.cpp, src/game/editor/popups.cpp
=> Fix editor modified state not being updated properly

src/game/editor/mapitems/layer_tiles.cpp, src/game/layers.cpp
Fixes #6778:
- Prevent editing the color of entities layers when selecting multiple tiles to edit and pressing "Commit" in the editor
- Ensure a white color for entities layers when loading map layers
=> Fix colorable entities layers

src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings_assets.cpp
Added for ghosts tab, previously only `F5` was possible.
Added for skins, and assets tab.
=> Support `F5` and `Modifer` + `R` for refresh where possible.

src/game/client/components/menus_settings.cpp
Not even terminal fans want to do colors in the console
=> Add ui setting for cl_authed_player_color

src/game/client/components/controls.cpp
Don't scale TargetX and TargetY by zoom when in spectator, as it completely breaks ShowDistance and `/tp`. Closes #7569.
=> Don't scale TargetXY by zoom when in spectator.

src/game/client/ui.cpp
Fix an issue where pressing escape while a lineinput was focused would not close the current popup in editor (reported by @furo321).
(Bug introduced by #7626)
=> Fix escape key not working when lineinput is focused

src/game/client/components/menus_settings.cpp
https://github.com/ddnet/ddnet/pull/7630#issuecomment-1850804027
=> Set correct colour for authed colour reset button

src/game/server/gamecontext.cpp, src/game/server/gamecontroller.cpp, src/game/server/gamecontroller.h, src/game/server/player.cpp, src/game/server/player.h
Now `CGameContext` no longer assumes the `IGameController` declined the team join due to slots.
This enables custom gametypes to disallow joining the game if the player died, an active tournament is running or the player is not logged in yet. And then the controller can print the correct error message accordingly.
=> Move chat message into CanJoinTeam()

src/game/client/components/menus_ingame.cpp
=> Add small margin to callvote label

datasrc/network.py, src/game/client/components/chat.cpp, src/game/client/components/chat.h, src/game/server/gamecontext.cpp
This adds `Sv_CommandInfo` and `Sv_CommandInfoRemove` from 0.7, which can be used to send all the available chat commands. These commands are then used for the tab completion in chat instead of using the hard-coded DDRace commands (it will still use them, if the server doesn't send any `Sv_CommandInfo` netmsgs).
Closes #7524
=> Add `Sv_CommandInfo` netmsg for autocompletion of chat commands.

src/game/server/gamecontext.cpp
Fixes printing of invalid strings when joining a team.
=> Don't broadcast error if `CanJoinTeam` returned true

src/game/client/components/chat.cpp, src/game/client/components/console.cpp, src/game/client/lineinput.cpp, src/game/client/ui.cpp
Fix Ctrl+C not working to copy text in console when the command input already contains text, as the changed flag was never reset properly.
Fix scroll position of UI editboxes not being updated when moving cursor without changing text.
Fix lineinput selection change being detected as content change, causing the editor modified state to be set incorrectly.
Fix cursor blinking not being disabled correctly after changing text without changing cursor position.
Regressions from #7626. And an additional fix for #6906.
=> Fix various lineinput issues/regressions

src/engine/shared/config_variables.h, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
Closes #6062.
This PR adds two quality of life features to quad, one of which has been requested in that issue.
1. Add the ability to preserve drag axis while holding shift. Works with entire quads or individual points.
https://github.com/ddnet/ddnet/assets/13364635/2a50eba3-54b0-4a8f-9f09-b835db322de3
2. Add the ability to align/snap points/quads to other points/quads. While dragging there is also an option to display the bounding box of the quad to better see how it can be snapped/aligned.
https://github.com/ddnet/ddnet/assets/13364635/344504f9-5181-4015-a7ca-489b3c7a0a86
This aims to make working with quads better as it allows to easily snap and align quads to each other. If one does not want that feature, they can simply disable it from the settings popup.
=> Editor: Add QoL features for quads

src/engine/client/client.cpp
Also specified that the parameter is optional and checked if any other commands suffer from the same problem, but didn't find any.
=> Use rest of string parameter for `save_replay`

src/engine/shared/config_variables.h
Server variables are currently not saved.
=> Remove `CFGFLAG_SAVE` when `CFGFLAG_SERVER` used

CMakeLists.txt, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/client/notifications.cpp, src/engine/client/notifications.h, src/engine/notifications.h, src/macos/notifications.mm
Add a proper kernel interface `INotifications` for the notifications component instead of using a C style interface.
Add parameter for the application name when initializing notifications to avoid hardcoding the application name.
The implementation for macOS is kept in Objective-C and a TODO is added, as the API we are currently using appears to be deprecated.
=> Add `INotifications` kernel interface

src/game/client/components/chat.cpp, src/game/client/components/console.cpp
```
/home/user/Development/ddnet/src/game/client/components/chat.cpp:1221:24: warning: use of bitwise '|' with boolean operands [-Wbitwise-instead-of-logical]
const bool Changed = m_Input.WasChanged() | m_Input.WasCursorChanged();
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
||
/home/user/Development/ddnet/src/game/client/components/chat.cpp:1221:24: note: cast one or both operands to int to silence this warning
/home/user/Development/ddnet/src/game/client/components/console.cpp:974:24: warning: use of bitwise '|' with boolean operands [-Wbitwise-instead-of-logical]
const bool Changed = pConsole->m_Input.WasChanged() | pConsole->m_Input.WasCursorChanged();
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|| …
```
=> Fix clang warning `-Wbitwise-instead-of-logical`

src/game/client/components/console.cpp
As it makes no sense to allow the user to cycle through the command history while in the rcon login prompt.
=> Disable cycling through command history when logging in to rcon.

data/shader/tile_border.frag, data/shader/vulkan/tile_border.frag, src/engine/client/backend/glsl_shader_compiler.cpp
fixes #7670
- for vulkan, which supports the `sample` qualifier this means it's basically using super sampling. which is more accurate, but more expensive. it allows multiple samples to pass and each sample will get the exact fragment input variables interpolated.
- for opengl it uses `centroid` which will cause basically cause the pixel to shift it's center if the center is outside but a sample is inside a fragment. This shifted center is the same for all samples tho, so at least a tiny bit less accurate than `sample`
I'll ready this pr tomorrow, so i still have a day to think about it
=> Fix multi sampling accuracy

src/game/editor/editor.cpp, src/game/editor/editor_actions.cpp
=> Clamp volume envelopes between 0.0f and 1.0f

src/game/client/components/console.cpp
The selection is only cleared because it would be incorrect after scrolling, but it doesn't need to be cleared if the scroll position does not change, e.g. when pressing Home while already at the top of the backlog.
=> Clear console selection only when scroll position is changed

src/game/server/ddracechat.cpp
Fixes people being able to join team on solo servers.
=> Add missing return statements to `AttemptJoinTeam`

src/game/client/components/mapsounds.cpp, src/game/editor/mapitems/map_io.cpp, src/game/mapitems.h, src/tools/map_extract.cpp
Do not use the `CMapItemSound::m_SoundDataSize` value as it is redundant. This value could also be incorrect because it can be freely set by the map creator (tool).
Instead, use the map/datafile function `GetDataSize` to get the true size of the sound data in the file.
The `m_SoundDataSize` value is still written to map files for compatibility with old versions.
=> Use `GetDataSize` instead of `CMapItemSound::m_SoundDataSize`

src/game/client/components/console.cpp
The current mouse-based console selection was not being adjusted anymore when new lines are added to the console, as the `m_NewLineCounter` variable was decremented to `0` before the relevant check for `m_NewLineCounter > 0`.
=> Fix console selection not adjusted anymore when entries added

src/game/client/components/console.cpp
The selection in console should not change position when new entries are printed while keeping scroll position (when console is scrolled up by at least 1 line).
Also decrease `m_NewLineCounter` by the entry line count.
Before:
https://github.com/ddnet/ddnet/assets/13364635/96cf638c-e864-429f-af92-cd3ab35f5600
After:
https://github.com/ddnet/ddnet/assets/13364635/90b9a8c8-686c-4826-8911-3fb7413e3b39
=> Fix console selection being moved when keeping scroll offset

src/engine/client/graphics_threaded.cpp
Only calculate `CurIndex` value once outside of loop instead of calculating it every iteration.
=> Avoid duplicate calculation in `QuadsTex3DDrawTL`

src/tools/map_convert_07.cpp, src/tools/map_create_pixelart.cpp, src/tools/map_optimize.cpp, src/tools/map_replace_area.cpp, src/tools/map_replace_image.cpp, src/tools/map_resave.cpp
All `map_*` tools were crashing with the assertion `Invalid type` when used on maps that contain unknown UUID-based map items. When the UUID cannot be resolved, the type `-1` is returned by the `GetItem` function. The assertion predates UUID map items, so this crash has likely existed since the introduction of UUID map items. The editor was not affected and has instead always discarded map items that it does not support. The tools will now also discard map items with unknown UUIDs.
See #7669.
=> Fix map tools crashing on maps with unknown UUID-based map items

src/game/editor/editor.cpp, src/game/editor/editor_object.cpp, src/game/editor/editor_object.h
Also, small changes to `CEditorObject`.
Previously only `CMapView` methods were used, but we should instead use the components methods by iterating over them in case we add more in the future.
=> Use `CEditorComponent` methods instead of only `CMapView`

src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h
Reduce duplicate code.
Replace `clampf` function with `NormalizeColorComponent` function that convert color component from `float` to `unsigned char`.
Use `size_t` instead of `int`.
=> Refactor graphics `SetColor` functions

src/engine/client/text.cpp, src/engine/textrender.h, src/game/client/components/console.cpp
Consider line spacing to belong to the previous line when calculating and rendering text selection. Instead of handling spacing between entries separately in the console, also include line spacing for the last line in the height calculation. Pixel align the line spacing in addition to the font size, as previously some gaps between the entries were larger than others due to missing pixel alignment. This allows rendering the text selection in the console smoothly without any gaps between the console entries/lines.
Closes #7617.
Screenshots:
- Single line:
- Before:
- After:
- Multi line:
- Before:
- After:
=> Improve text line spacing and console text selection

src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/storage.cpp, src/game/server/gamecontext.cpp
1. Fix `sv_auto_demo_record 1` not starting recording of auto demo. Closes #7573
2. Don't use the same demo recorder for manual and auto demos.
3. Change path of server auto demos from `demos/auto` to `demos/auto/server`. Also match the filenames to be the same as the client auto demos. `autorecord_(date)` -> `(current map)_(date)`
=> A few fixes and improvements to server-side auto demos.

src/engine/shared/filecollection.cpp, src/engine/shared/filecollection.h
- Use existing functions from `system.h`
- Use sorting from `<algorithm>`
- Don't recall `ListDirectory` for every removal, which caused the client to hang previously with a lot of files. Closes #4227
=> Rework `CFileCollection`.

src/engine/client/backend/vulkan/backend_vulkan.cpp
According to the Vulkan specification, the struct `VkBufferImageCopy` is used only for `vkCmdCopyBufferToImage` and `vkCmdCopyImageToBuffer`. The variable `Region` is only initialized but not passed to either of those functions.
=> Remove unused `VkBufferImageCopy Region` variable

src/engine/client/backend/vulkan/backend_vulkan.cpp
The parameter is always set to `false` so the code is unused.
=> Remove unused `FlipImgData` parameter from Vulkan backend

src/game/editor/popups.cpp
Remove checks that aren't supposed to be there.
=> Remove checks when drawing quads QoL buttons

src/game/client/components/chat.cpp, src/game/client/components/hud.cpp, src/game/client/components/infomessages.cpp, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/players.cpp, src/game/client/components/scoreboard.cpp, src/game/client/components/spectator.cpp, src/game/client/components/statboard.cpp, src/game/client/gameclient.cpp, src/game/client/render.cpp, src/game/client/render.h
Now when we have https://github.com/ddnet/ddnet/pull/7653 merged, we need to have `const` on methods which clang-tidy detects as 'could be const'.
In [0.7 client support PR](https://github.com/ddnet/ddnet/pull/5949), `CRenderTools::RenderTee()` is duplicated for 0.7 skins rendering, and clang-tidy sees `RenderTee7()` as "should be const". The suggested changes needed to mark `RenderTee()` as `const`now to have no contradictions in the methods later in https://github.com/ddnet/ddnet/pull/5949/files#diff-8401b3d39d57b7e0c9d540a626658289a82e032f74607e089be360638cb51839R135
The second commit adds Skin6 info reset to later 1) also reset Skin7, and then 2) use the Skin6/7 to decide what skin to use.
I want to add optional 0.7 skins use on per-player basis for DDNet extended protocol, and the …
=> RenderTools: Add const/static method qualifiers

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
Closes #5400.
This PR adds two things:
- A way to easily change tele, switch and tune numbers of the current brush by using shift+scroll up/down to adjust the numbers by `1`/`-1`:
https://github.com/ddnet/ddnet/assets/13364635/8c7ddf0d-d4ef-4be3-9aa6-0e1c5825d01c
- A way to set tele and switch numbers to the next free number of the respective layer by using `ctrl+f` while having a brush selected:
https://github.com/ddnet/ddnet/assets/13364635/985491c4-0980-4c82-86af-98adc04c80c5
=> Editor: add shortcut to adjust special tiles numbers

src/game/client/render_map.cpp
When setting `cl_text_entities_size` to a value higher than `60`/`70`, the text could be very hard to read when many tele tiles are next to each other.
Now, the text is contained within each individual tele tile to improve readability while trying to match `cl_text_entities_size`. This means for large number (for example `255`), the text will be smaller than for small numbers (for example `8`). The text is also centered.
Before:
- `cl_text_entities_size`: `60`
- `cl_text_entities_size`: `100`
After:
- `cl_text_entities_size`: `60`
- `cl_text_entities_size`: `100`
=> Editor: improve text rendering inside tele tiles

src/game/client/components/controls.cpp
Fixes #5077 
Let's say you have this bind:
```bind x +toggle cl_dummy_hammer 1 0```
and you set ```cl_dummy_control``` to ```1```.
When you press the bind i mentioned above, and then release, the dummy will hammer where he is looking (not at you). So, in total, there will be two hammers. One hammer when you press down the button and the dummy hammers towards you, and then another hammer when you release the button and the dummy hammers where he is looking.
This fixes it, and also makes sure it does not conflict with ```cl_dummy_copy_moves``` (as if it is enabled and ```cl_dummy_control``` is enabled, the dummy will not copy fire, hook, or jump) so I made sure it keeps this functionality as it's pretty cool.
This does not fix any other bugs yet, maybe I will fix those in the future but …
=> Fix automatic hammer on release when cl_dummy_control is set to 1

src/game/client/render_map.cpp
The text color was previously set and reset for every individual number being rendered for non-empty tele, speedup, switch and tune tiles. The color is the same for all tiles from each entities layer, so most of these `TextColor` calls are unnecessary. Now the text color is only set and reset once when rendering each entities layer.
=> Improve performance when rendering map overlay texts

src/game/editor/auto_map.cpp
`CAutoMapper` only needs `CLayerTiles` which has been moved to `layer_tiles.h`.
=> Only include `layer_tiles.h` in `auto_map.cpp`

src/game/editor/editor.cpp, src/game/editor/editor.h
Closes #7029.
Allows paning outside initial containers for both envelope editor and map view.
This also adds infinite panning where you are no longer constrained to the bounds of your screen.
https://github.com/ddnet/ddnet/assets/13364635/1eb4d8d4-3f3c-4b86-8c0f-9c0a98520110
Works by using a variable to keep track of the current panned container and doing the panning logic outside of the initial `IsInside` check.
=> Editor: allow panning outside initial container

src/engine/client/graphics_threaded.cpp, src/game/client/ui.cpp
When normalizing color components in the engine graphics, round the components to the nearest integer instead of rounding down. Otherwise the color that is rendered in color pickers may be off by 1 in any of its RGB components from the color that the color picker displays as text (hex string and individual components). The slightly incorrect color can be confirmed by creating a screenshot or otherwise reading the backbuffer (planned editor pipette feature).
This should not change map rendering, since maps already store quantized RGBA values on which the rounding mode should have no effect. It may however slightly change appearance of colors in all other places (at most +1 in every RGB component).
The individual color components were rounded down when being displayed on their own in color …
=> Fix color rendering being inconsistent with displayed color values, fix slightly incorrect color components shown in color pickers 

src/game/client/components/maplayers.cpp, src/game/client/render_map.cpp, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/editor_props.cpp, src/game/editor/mapitems/layer_tele.cpp, src/game/editor/mapitems/layer_tele.h, src/game/editor/mapitems/layer_tiles.cpp, src/game/editor/popups.cpp, src/game/mapitems.cpp, src/game/mapitems.h
Closes #2384.
This PR adds differentiation between normal teles and checkpoint teles by using two variables instead of one.
It also changes the "Tele" popup to display both numbers, and the logic to find a used tele tile has been changed to check for checkpoint tiles only or exclude checkpoint tiles.
I'm a bit unsure if we really want this. I tried to understand the initial issue as best as I could, but this is maybe not the wanted solution.
https://github.com/ddnet/ddnet/assets/13364635/e01b32b3-cd19-48e5-a3d3-584933bb761f
=> Editor: differentiate between normal and checkpoint teles

src/game/client/components/console.cpp, src/game/client/components/console.h
Allows autocompletion of specific argument instead of the first argument only.
Useful for the command `tune_zone` for example.
https://github.com/ddnet/ddnet/assets/13364635/43fb42a6-2e6b-409b-84dc-f92c0fd9b9a7
=> Refactor argument autocompletion in console

src/game/editor/editor.cpp, src/game/editor/mapitems/image.cpp, src/game/editor/mapitems/image.h
Fix broken editor append (fixes #7625).
Check for image data when image names are identical. In such case, appended image is renamed until its name is unique.
=> Editor: improve append (fixes #7625)

src/game/editor/editor.cpp
#7726 broke selection in editor. This should fix it.
=> Fix broken selection in editor

src/game/editor/editor.cpp
Clear layers from context before adding any layer, preventing layers from being kept in the vector until only a single layer is selected. Fixes #4978.
=> Editor: fix duplicate layers in popup layer context

src/engine/client/text.cpp
Render one quad for each line of the text selection instead of rendering one quad per selected character.
This increases the average FPS when the console is open and all text is selected by around 10% (from around 849 to around 943 FPS) (on my machine, in release mode).
=> More efficient text selection rendering

src/game/editor/popups.cpp
#7393 broke the group position/offset properties by unintentionally removing the minus sign used when changing the group position to the new value. This PR adds them back, fixing this particular issue.
=> Editor: fix group position properties not working correctly

src/engine/textrender.h, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/map_grid.cpp, src/game/editor/map_grid.h, src/game/editor/popups.cpp
Add dropdown menus for changing animation and grid settings (i.e. animation speed and grid size) instead of conditionally showing more buttons for this directly in the menu bar. This frees up space in the menu bar, which is currently full on 5:4 resolutions.
The icons previously used for the default animation/grid buttons are now used for the main buttons that toggle animation/grid instead of using text.
Support setting lower animation speeds with the plus and minus buttons by adjusting the step size when the animation speed is low.
Support setting arbitrary animation speed by text input.
Screenshots:
- Anim/grid disabled:
- Before:
- After:
- Anim/grid enabled:
- Before:
- After (anim popup):
- After (grid popup):
=> Improve editor toolbar anim and grid buttons, add dropdowns

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_settings.cpp
In addition to the warning message a button will be shown allowing for easy restart.
=> Add restart button for when game needs to restart to apply settings

src/game/client/ui.cpp, src/game/editor/editor.cpp
Ensure that the UI mouse position stays inside the UI screen rect. Previously, the mouse was not considered to be inside the UI screen when all the way at the right or bottom edge. This caused the map editor tooltip to not be shown when the mouse is all the way at the right side of the map editor view. This is a cleaner fix for #4553 which reverts the previous workaround from #6423.
=> Fix mouse being outside of UI screen on right and bottom edges

src/engine/server.h, src/game/server/teams.cpp
Fixes 0.7 players not being able to receive finishes done by players on 0.6 (and vice-versa).
=> Use 0.7 translation layer for `Sv_RaceFinish` netmessage.

src/engine/client/sound.cpp, src/engine/client/sound.h
Replace linear search for free sample index with free list. This brings sound sample index allocation down to constant complexity independent of the number of allocated sounds. On average the time to allocate sound samples is reduced by around 75% (843µs down to 223µs). For perspective, the time to load all default sounds on client launch is reduced by around 15ms (although this does not significantly affect launch time due to threaded loading).
=> Optimize allocation of sound sample indices, add missing sound lock usage

src/game/server/entities/character.cpp
If you were to enter a tune_zone that has `hammer_duration` with a value above `1.25f`, `m_HookTick` becomes negative. Which leads to 0.7 clients dropping the `CNetObj_CharacterCore` message, because it only accepts values between `0` and `int_max`. So, I just decided to clamp it at 0 if it's negative when sending it to 0.7 clients. Closes #3915
https://github.com/ddnet/ddnet/assets/141338449/2fa8986a-94aa-41ab-b65d-57110166627a
=> Fix players on 0.7 becoming invisible when `m_HookTick` is negative.

src/engine/external/json-parser/json.c
~~1 liner~~
Warning:
cast from pointer to integer of different size
fixed by pulling latest upstream of json-parser : https://github.com/json-parser/json-parser
=> change cast of pointer to uintptr_t

src/game/editor/editor.cpp
It is a rather small change but I think this looks way better.
Before:
https://github.com/ddnet/ddnet/assets/13364635/680555db-1fcc-4d3c-88ec-a84afae269fc
After:
https://github.com/ddnet/ddnet/assets/13364635/d73d3aea-dbb7-4006-8335-4506b5d3f3d0
=> Editor: fix input corners when editing value selector

src/game/server/eventhandler.cpp
Does not fix any bug as far as I know. Just gets rid of the weirdness that uninitialized static memory is cast to a struct where only half of the fields are set. I tested it and my 0.7 client receives 0 for all values either way.
=> Explicitly set all 0.7 dmg event fields

src/game/client/components/menus_ingame.cpp
The selection in the kickvote/specvote menu was reset to the first player when the previously selected player leaves or if the filter string does not match it. Now the selection is cleared in these cases, to prevent players from accidentally starting kickvotes/specvotes on the wrong player.
Remove unnecessary `static` variable. Improve readability by not nesting post-increment in another statement.
=> Fix wrong selection in vote menu when selected player leaves

src/engine/client/client.cpp
Unset the assertion handler before shutting down the kernel (including graphics) and client. Otherwise the assertion handler itself crashes when assertion errors happen after the graphics/client have been destroyed.
=> Fix crash in assertion handler after client/graphics destroyed

CMakeLists.txt, src/base/system.cpp, src/base/system.h, src/engine/shared/filecollection.cpp, src/engine/shared/filecollection.h, src/test/timestamp.cpp
When working on editor related features and having a debugger attached, I often got an exception after a few minutes of having it open. I then found out that this happened consistantly when the editor tried to autosave a new map.
This is likely due to #7712 which changed how timestamps work. The issue is the computed timestamp in `CFileCollection` which is not a UNIX timestamp, so using it with a method that takes a UNIX timestamp throws an error.
In this PR I fixed this issue by introducing a new system method `timestamp_from_str` to parse a time string into a valid UNIX timestamp that can then be used with the method `str_timestamp_ex` (that previously caused the exception). I have also added a few tests for that specific method.
One issue is that I had to use C++ specific methods such …
=> Fix crash on editor autosave, add system method `timestamp_from_str`

src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/game/client/components/countryflags.cpp, src/game/client/components/mapimages.cpp, src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp, src/game/editor/editor.cpp
Add separate `IGraphics::LoadTextureRawMove` function with non-`const` `void *pData` argument in addition to existing `LoadTextureRaw` function with `const void *pData` argument. The former function takes ownership of the data and avoids copying the texture data into an additional buffer, if the texture data is already in RGBA format. Non-RGBA texture data always needs to be converted and therefore also copied.
The `LoadTextureRaw` function is split into smaller functions to share common code with the `LoadTextureRawMove` function. Alternatively to this, a flag `TEXLOAD_MOVE_DATA` could have been added to the existing `LoadTextureRaw` function, which would have required the use of `const_cast` to free the texture data.
=> Avoid copying texture memory when possible

src/game/editor/explanations.cpp
The kill tile can also be used in the front layer and works as expected.
=> Fix missing editor explanation for kill tile in front layer

src/base/system.cpp, src/test/io.cpp
Files were not being truncated on Windows anymore when using `io_open` with `IOFLAG_WRITE` due to a regression from #7254. Instead, the existing file contents were kept and the file pointer was set to the beginning of the file.
This caused broken demo files to be created (#7349) when recording a shorter demo with the same filename as an existing longer demo. It also caused the map tools to produce maps with additional junk data at the end, if an existing map is overridden by a smaller map.
This is fixed by using the creation disposition `CREATE_ALWAYS` instead of `OPEN_EXISTING` with [`CreateFileW`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew), which ensures that a file is always created and truncated.
A regression test case is added, which fails …
=> Fix files not being truncated when opening for writing on Windows

src/engine/shared/datafile.cpp, src/engine/shared/datafile.h, src/tools/map_convert_07.cpp, src/tools/map_create_pixelart.cpp, src/tools/map_optimize.cpp, src/tools/map_replace_area.cpp, src/tools/map_replace_image.cpp, src/tools/map_resave.cpp
Adapt the `CDataFileReader::GetItem` function so it optionally also returns a `CUuid` for UUID-based map items, including for items with unknown UUIDs where the item type will be `-1`. Adapt the `CDataFileWriter::AddItem` function so it optionally also accepts a `CUuid` which will be used if the item type is `-1`.
The additional checks for invalid map item types in the map tools are removed again and instead the new UUID parameters are used so map items with unknown UUIDs are written back to maps correctly.
Closes #7701.
=> Propagate unknown UUID-based map items in map tools

src/game/client/components/players.cpp
Don't use mouse position for drawing hook collision line when paused. Applies the same fix from #7294 to hook collision line as well.
Before
After
=> Fix hook collision line being incorrect while paused.

src/engine/client/client.cpp, src/engine/shared/config.cpp
Screenshots:
- Before: 
- After:
=> Improve error messages when saving settings fails

scripts/fix_style.py
On Windows the paths contains `\` which is different from the used path separator in the script `/`, being used for files to ignore for example. It means that those ignore files wouldn't match any of the collected paths when running the script on Windows, which lead to having those files being clang formatted when they should be ignored.
This PR simply replaces the windows path separator `\` with `/` so that everything involving path comparison should work properly.
=> `fix_style.py`: replace windows path separator with `/`

src/engine/client/serverbrowser.cpp
The server community was only initialized when receiving server info. This caused servers for which no server info is received to be hidden when using the community filter. Now the community filter also works correctly for servers for which no ordinary server info is received, by initializing the community already when adding server entries to the list.
Closes #7776.
=> Fix community not set for servers with missing server info

src/engine/shared/datafile.cpp, src/engine/shared/datafile.h, src/game/client/gameclient.cpp, src/tools/dummy_map.cpp, src/tools/map_optimize.cpp
By adding `CDataFileWriter::ECompressionLevel` to replace usage of zlib internal compression levels in the `CDataFileWriter` API.
=> Avoid including `zlib.h` in header file

src/tools/dummy_map.cpp
The SHA256 was being calculated over a pointer to the map data and random following memory instead of over the data itself.
=> Fix incorrect SHA256 logged in `dummy_map` tool

src/engine/shared/config_variables.h
Everything above 255 seems to be clamped somewhere else. At least go max.
```
./DDNet-Server "sv_welcome xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxY"
```
=> Increase sv_welcome to 256

src/engine/client/client.cpp
The `IClient::Disconnect` function is always called at the beginning of the `IClient::Connect` function. The `IClient::Disconnect` function calls `IClient::DisconnectWithReason`, if the client is not already offline, which performs cleanup of temporary commands and demo recorders already, so the same cleanup in the `Connect` function is unnecessary. An assertion is added to ensure that the client was properly disconnected before connecting. Connecting while the client is already quitting or restarting is now prevented, as the client state cannot be changed once set to quitting or restarting.
=> Remove duplicate cleanup when connecting

src/engine/client/client.cpp, src/engine/client/serverbrowser.cpp, src/game/client/components/spectator.cpp, src/test/jsonwriter.cpp
Consistently use `std::numeric_limits` instead of `INT_MIN` and `INT_MAX`.
=> Include `limits` instead of `climits`

src/engine/client/text.cpp
The `CTextCursor::m_LineCount` variable is only updated after the cursor is rendered. For calculating the selection quads we need to check `LineCount` instead, which is updated while the cursor is being rendered. Regression from #7733.
=> Fix multi-line text selection not rendered correctly anymore

src/engine/client/backend/opengl/backend_opengl.cpp, src/engine/client/backend/opengl/backend_opengl.h, src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/engine/textrender.h, src/game/editor/editor.cpp, src/game/editor/editor.h
Add color palette with up to 8 colors to editor toolbar. The palette colors work like regular color picker buttons, so they open a color picker popup on click and the value can be copied and pasted with Ctrl+Right click and Ctrl+Left click respectively. Less palette colors are shown when not enough space is available (with 5:4 resolutions).
Add color pipette which allows selecting any color displayed on the screen. Selecting a color with the pipette adds the new color to the palette and shifts the other colors to the right. The selected color is also copied to the clipboard immediately. The hotkey Ctrl+Shift+C is added to toggle the color pipette, which allows using the color pipette in popups and dialogs.
The implement this, the function `IGraphics::ReadPixel` and the command …
=> Add color palette and pipette to editor

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/editor_actions.cpp, src/game/editor/editor_actions.h, src/game/editor/editor_history.cpp, src/game/editor/editor_history.h, src/game/editor/editor_trackers.cpp, src/game/editor/editor_trackers.h, src/game/editor/popups.cpp
Fixed crash when runing tool 'Remove unused envelopes' and trying to undo the addition of an envelope (fixes #7738).
Fixed issues where undo/redo would not work properly when changing a layer's order or group property.
Added missing action for changing the position of a sound source.
I don't know if there are any more problems, so feel free to open an issue when you encounter a crash/unexpected behavior while using the feature.
=> Fix multiple editor undo/redo issues

CMakeLists.txt, src/base/system.h, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser.h, src/engine/client/serverbrowser_http.cpp, src/engine/client/serverbrowser_http.h, src/engine/client/updater.cpp, src/engine/client/updater.h, src/engine/http.h, src/engine/server/register.cpp, src/engine/server/register.h, src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/http.cpp, src/engine/shared/http.h, src/game/client/component.cpp, src/game/client/component.h, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/components/skins.cpp, src/game/client/components/skins.h, src/game/client/gameclient.cpp, src/game/client/gameclient.h
This rebases and partially rewrites #5842. Tested very roughly
I still am not the biggest fan but this is the best I can do without going far too deep into a jobs rewrite: 
- This iteration uses the approach in #5092 as we talked about on Discord so the `IJob` interface is lost.
- Another issue is that this isn't a real engine interface but just pretends to be one so I can easily get pointers to it around the code. This can be mitigated by either designing a proper interface for `IHttpRequest` or by passing `CHttp` around everywhere like in #5092
- Finally one might want to rework the concurrency aids from `std` with our own ones, I'm far too tired of messing around with this PR to care about that.
@heinrich5991 you specifically should take a look at `CHttpRequest::Wait()`, the way I …
=> Use curl-multi. Supersedes #5842

src/game/editor/editor.cpp
Add tooltip when drawing tele brush (tele numbers adjust). 
Add tooltips when dragging quad points (alignment).
I think these are needed since those features are quite "hidden".
=> Editor: add tooltips to recent features

src/game/editor/editor.cpp
Center the resize (V/H) cursors on the mouse position instead of aligning the top-left with the mouse position. This feels better to use and is consistent with the behavior for example on Windows.
Before:
https://github.com/ddnet/ddnet/assets/23437060/5e446cd3-6c9a-42f9-9b0e-4ff3988507ef
After:
https://github.com/ddnet/ddnet/assets/23437060/d0d49c68-9160-4dd0-aab9-950d574254e5
=> Improve alignment of editor resize cursors

src/engine/client/warning.cpp, src/engine/warning.h
For some warnings a random title instead of the default title was shown because it was not initialized.
=> Fix warning title being uninitialized in some cases

src/game/server/teams.cpp
Solves #4205 (Is there a variable to check if team had cheated before? Player can disable super and continue to receive this annoying message)
=> Don't warn about unfinishable map for super team

src/engine/textrender.h, src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp
Free up space for up to three more server browser tabs of the same size (on 5:4 resolutions), i.e. tabs for configurable communities.
Remove the additional server browser icon tab on the right side. Remove the purely visual Demo and News tabs which were only shown when the respective page is already active. Instead, always show all server browser tabs when offline.
Use yellow-orange star icon to mark favorite servers in the server browser instead of using the heart icon. The heart icon is now only used for servers with friends.
Tweak color of the star icon used for skin favorites so it's slightly more orange instead of pure yellow.
Screenshots:
- 16:9:
- Before:
- After:
- 5:4:
- Before: 
- After: 
- Star:
- Before: 
- After:
=> Use icons for Internet, LAN and Favorites server browser tabs, use star icon for favorite servers

src/engine/client/client.cpp, src/engine/client/graph.cpp, src/engine/client/graph.h, src/engine/shared/ringbuffer.cpp, src/engine/shared/ringbuffer.h, src/game/client/components/debughud.cpp, src/game/client/components/debughud.h
Store X value (time) for all graph entries in addition to the Y value (FPS, prediction margin etc.). The `CGraph::Add` function adds values to the graph at the current time. The `CGraph::InsertAt` function allows specifying arbitrary X values, as long as the values are inserted in increasing order.
The entries are kept in a ringbuffer and old entries are recycled when it's full. The size of the ringbuffer is configurable for each graph, as the FPS graph needs significantly more buffer because values are added more often.
The scrolling speed of the graphs is fixed by specifying the maximum size of the window of values which should be displayed. For this purpose, a parameter is added to the `CGraph::Scale` function to specify the size of the window which should be rendered in the …
=> Add time scale to debug graphs for constant scrolling speed

src/game/editor/map_grid.cpp
Sometimes a smaller grid is useful. Now it goes up to 1/8 tile on max zoom in.
=> Allow finer editor grid

src/game/collision.cpp
When handling door and laser entities, all 8 adjacent tiles are checked for laser modifier tiles. When handling laser entities, the 8 tiles one further out are also checked for laser modifier tiles. If either of those 16 tiles is outside the map bounds, an error message was printed and the tiles are ignored. The error message is removed because it's unnecessary and misleading. Placing entities near or on the map border is not known to cause any issues.
Closes #7759.
=> Remove unnecessary check for entities close to map border

src/engine/shared/http.cpp
closed #7823
```
$ DDNet-Server "sv_register 1"
```
behind nat with errors looks like this
https://logs.zillyhuhn.com/?url=https://paste.zillyhuhn.com/M9
and a successful register looks like this
https://logs.zillyhuhn.com/?url=https://paste.zillyhuhn.com/Hy
```
$ DDNet-Server "sv_register 1;dbg_curl 1"
```
successful register looks like this
https://logs.zillyhuhn.com/?url=https://paste.zillyhuhn.com/k8
=> Only log http requests if ``dbg_curl 1``

src/base/log.cpp, src/tools/map_diff.cpp
Use [virtual terminal processing](https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) for Windows console output when possible, using the existing async logger. Fallback to the old Windows logger when virtual terminal processing is not available. Do not set any logger when there is no console/file/pipe to output to.
This adds support for 24 bit RGB colors using ANSI escape codes (when Terminal emulator supports it) instead of only supporting 16 fixed colors.
Use the existing async logger also on Windows by converting the console standard output handle to an IOHANDLE. Avoid converting console output to UTF-16 by changing the console output codepage to UTF-8 and outputting that directly. Overall, this reduces the time until the loading screen first appears …
=> Improve Windows logger, add virtual terminal support

src/engine/client/updater.cpp, src/engine/shared/http.cpp, src/engine/shared/http.h, src/game/client/components/skins.cpp, src/game/client/components/skins.h
Ensure that the `CHttpRequest::OnCompletion` function has finished before updating the state which is visible to other threads. Otherwise, threads may try to access the result of a completed HTTP request, before the result has been initialized/updated in the `OnCompletion` function.
Fixes warning due to invalid texture width/height being shown for downloaded skins, because the texture was loaded before the image data was initialized. Closes #7818.
Regression from #7683. Before this, the `OnCompletion` function could also modify the HTTP request's state, which was used to check if loading the skin PNG failed. Instead of doing this, a separate check is added for the skin download task to check that the PNG was loaded successfully.
=> Finish `CHttpRequest::OnCompletion` before updating `State()`

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/demo.h, src/engine/server/server.cpp, src/engine/shared/demo.cpp, src/engine/shared/demo.h, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp
To simplify the usage of the demo recorder, parameters are added to the `IDemoRecorder::Stop` function to control whether the demo file is removed or renamed when stopping the recording.
Ensure demo files of the replay recorder are always removed (except on crashes). The temporary replay demos were previously not removed when being disconnected from a server.
Fix auto demos being stopped and restarted when enabling replays in the settings menu. Now only the replay recorder is stopped/started when necessary.
Fix replay recorder being restarted when setting `cl_replay` variable with console without changing the value.
Remove unnecessary `CClient::m_ButtonRender` variable. Demo rendering is already stopped correctly when reaching the end of the demo without this additional variable.
Remove …
=> Refactor demo recorder usage

src/game/client/prediction/entities/character.cpp, src/game/client/prediction/entities/character.h, src/game/client/prediction/entities/dragger.cpp, src/game/client/prediction/entities/laser.cpp, src/game/client/prediction/gameworld.cpp, src/game/server/ddracechat.cpp, src/game/server/ddracecommands.cpp, src/game/server/entities/character.cpp, src/game/server/entities/character.h, src/game/server/entities/dragger_beam.cpp, src/game/server/entities/laser.cpp, src/game/server/gameworld.cpp
Instead of leaking the m_MoveRestrictions to all classes which needs to adjust the Character velocity, add a setter which takes into account those restrictions.
The shotgun bug replication requires an access to the Velocity without the restrictions applied (so we have to have this dirty setter).
Hide the implementation details behind setters to prevent bugprone access and code duplication.
Fix incapsulation and get rid of the logic duplication which should be replicated whenever we need to adjust the Character velocity.
```
Temp = pHit->Core()->m_Vel + normalize(pOwnerChar->Core()->m_Pos - HitPos) * Strength;
pHit->Core()->m_Vel = ClampVel(pHit->m_MoveRestrictions, Temp);
```
If we'd have more entities (and there are mods with many more of them) we'd have to take extra care to always take …
=> Character: Fix m_MoveRestrictions and m_Core incapsulation

src/engine/client/serverbrowser.cpp, src/game/client/components/menus_browser.cpp
Instead of cleaning the countries/types filters based on all available communities' countries/types, only consider the countries/types of currently selected communities. Ensure countries/types are always cleaned when updating the server browser filter in the UI. This fixes that countries/types which are not available for the selected communities were still affecting the server filtering, causing no servers to be shown in some cases.
Closes #7847.
=> Fix countries/types filters excluding all servers

src/engine/client.h, src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/game/client/components/menus_settings.cpp
The `bool AllowResizing` parameter is only passed to other `SetWindowParams` functions but never used in the end, as whether or not resizing is allowed is separately determined based on the value of the `int FullscreenMode` parameter.
=> Remove unused parameter of `SetWindowParams` function

src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp
Render an additional "Reset filter" button below the "No servers match your filter criteria" message to make it more obvious for new players how to restore the original view of servers, especially when the filter tab is not currently selected.
Screenshots:
- Before: 
- After:
=> Show extra "Reset filter" button when no servers match filter

src/game/client/components/infomessages.cpp
This stores info messages even if kill/finish messages aren't enabled. This was the case previously, but I'm not sure why I changed it in #7515.
=> Store info messages even if they aren't enabled

src/base/system.cpp, src/base/system.h, src/engine/client/client.cpp, src/game/client/components/menus_start.cpp
Add parameter to `shell_execute` to either start the process in the foreground or background on Windows. Previously, all processes were started in the background, because this is desired when starting the server from the client. However, this causes the graphics initialization to fail when restarting the client after updating or with the `restart` command when using Vulkan with windowed and windowed fullscreen mode.
Closes #6578.
=> Ensure client window is maximized and active after restarting, refactoring

src/game/server/teeinfo.cpp
It seems that the original mapping based on datasrc before https://github.com/teeworlds/teeworlds/pull/2692. Also bluekitty had wrong feet color (check [bluekitty.json](https://github.com/teeworlds/teeworlds/blob/master/datasrc/skins/bluekitty.json): `feet` hue in the json is different from that of `hands` but in TeeInfo mapping we had identical colors).
The idea is to later use those mapping to leverage 0.7 skins for DDNet protocol.
Note: maybe we'd want to use the same `.json` files instead of hardcoded skins info but `CSkins` is a part of the game/client and I'd postpone such refactoring (not to say that [0.7 skins](https://github.com/ddnet/ddnet/pull/5949) are not finished yet).
The immediate effect is fixed kitty skins for 0.7 vanilla client, though for me it is rather a side effect. …
=> TeeInfo: Fix blue and limekitty eyes and feet 0.6 -> 0.7 mapping

src/engine/shared/demo.cpp
When there are too many demo markers already or when the previous demo marker is too close.
=> Show error messages in console when `add_demomarker` fails

src/game/server/gamecontext.cpp
We already check for valid UTF-8 while unpacking strings.
=> Remove redundant UTF-8 checks

src/engine/shared/console.cpp
It will now print an error message if you try use a testing command without having `sv_test_cmds` enabled.
=> Add a error message for when testing commands aren't allowed

src/engine/client/updater.cpp, src/engine/client/updater.h
I have no idea how this broke, the only file included before the macros were defined didn't change at all nor did the files that it includes. Baffling. This means sadly 18.0.2 will have to be a manual update
=> Fix updater issue. Close #7867

src/game/editor/popups.cpp
clang 14.0.6 shows this:
```
[ 98%] Building CXX object CMakeFiles/game-client.dir/src/game/generated/client_data7.cpp.o
In file included from /usr/include/c++/12/bits/stl_tempbuf.h:60,
from /usr/include/c++/12/bits/stl_algo.h:61,
from /usr/include/c++/12/algorithm:61,
from /home/chiller/Desktop/git/ddnet/src/base/math.h:6,
from /home/chiller/Desktop/git/ddnet/src/base/color.h:5,
from /home/chiller/Desktop/git/ddnet/src/game/editor/popups.cpp:4:
In function ‘void std::_Construct(_Tp*, _Args&& ...) [with _Tp = CEditorActionTileChanges; _Args = {CEditor*&, int&, int&, const char (&)[20], map<int, map<int, STileStateChange, less<int>, allocator<pair<const int, STileStateChange> > >, less<int>, allocator<pair<const int, map<int, STileStateChange, less<int>, allocator<pair<const int, …
```
=> Fix clang warning and UB when there is no game layer

datasrc/seven/network.py
Missed in https://github.com/ddnet/ddnet/pull/7768
My bad I should have caught that. Got lost when [#7762](https://github.com/ddnet/ddnet/pull/7762/commits) got replaced.
In 0.7 the value -1 is used for m_HookedPlayer. So this too strict validation broke https://github.com/ddnet/ddnet/pull/5949
=> Fix 0.7 validation range of m_HookedPlayer in character snap items

src/game/server/gamecontext.cpp
Closed https://github.com/ZillyInsta/ddnet-insta/issues/91
=> Fix 0.7 armor being snapped as health

src/engine/client/client.cpp, src/engine/server/main.cpp, src/engine/server/server.cpp
Use error log level for error messages. Use info log level explicitly instead of using `dbg_msg`.
Log time taken for initialization in trace level message.
=> Improve client/server launch log messages

src/game/client/components/menus_settings.cpp
+ Don't randomize colors if UseCustomColor is false
+ Use all instead of only vanilla skins when randomizing
=> CMenus::RandomSkin() adjustments

src/engine/shared/console.cpp
=> Tell the user about `/cmdlist` when using an unknown chat command.

src/game/server/gamecontext.h, src/game/server/teams.cpp
- Allow joining started teams that have practice enabled.
- Don't print this message when the team is already in practice
- Remove unused `ConAccept` function, which I forgot to remove in #7662
=> Small improvements to practice 

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_settings.cpp
The client will now refresh the skins when changing `cl_skin_download_url`, `cl_skin_community_download_url`, `cl_download_skins`, `cl_download_community_skins` and `cl_vanilla_skins_only` just like it does when doing it from settings.
=> Add console chain for refreshing skins

src/mastersrv/Cargo.lock, src/mastersrv/Cargo.toml, src/mastersrv/src/main.rs
You should generally not send a `charset=*` parameter for `Content-Type: application/json` because no parameters are defined for it: https://datatracker.ietf.org/doc/html/rfc7158#section-11.
Fixes #6955.
=> Accept `charset=*` in `Content-Type` for masterserver

src/game/client/component.h, src/game/client/components/chat.cpp, src/game/client/components/chat.h, src/game/client/components/ghost.cpp, src/game/client/components/ghost.h, src/game/client/components/infomessages.cpp, src/game/client/components/infomessages.h, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_settings.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h
Add `CGameClient::RefreshSkins` function to refresh skins. This function reloads all skins by calling `CSkins::Refresh` and then notifies all gameclient components about the skins being refreshed by calling the new `CComponent::OnRefreshSkins` function, so the components can properly invalidate their current skin texture handles. The existing `RefindSkins` functions are changed to `OnRefreshSkins`.
Additionally, `OnRefreshSkins` is overridden in `CMenus` to set the flag so the skin list will be updated before it is rendered the next time, to fix the client crashing when changing skin related config variables via the console. Closes #7891.
=> Refactor skin refreshing in gameclient, fix crash in skin settings

src/game/editor/popups.cpp
Check selected quad index when rendering quad popup. Fixes #7904.
=> Editor: fix crash when changing layer with UP or DOWN while quad popup is opened

src/game/client/components/players.cpp
Fixes hook collision line being slightly incorrect when aiming in the middle of the screen. Bug from #7512
Before
https://github.com/ddnet/ddnet/assets/141338449/27cebaa6-295a-419b-92b7-b0caddc05c0f
After
https://github.com/ddnet/ddnet/assets/141338449/51770b42-4d8b-40a8-bb57-54edd9e9f681
=> Scale angles using MousePos with zoom

src/game/editor/editor.cpp
As suggested here, https://github.com/ddnet/ddnet/issues/7905#issuecomment-1924670295. I believe a toggle button makes more sense, as they are easier to hit and fits in more with the editor UI.
Before
After
=> Use toggle button instead of checkbox for "Sync envelope button".

src/engine/server/databases/connection.cpp, src/engine/server/databases/connection.h
`MAX_NAME_LENGTH` includes space for `\0`, which doesn't need to be accounted for in SQL. So, the correct size would be 15 instead of 16. I also checked if there is any names in the official database that is more than 15 characters, but there is not.
```
sqlite> SELECT MAX(LENGTH(name)) FROM race;
MAX(LENGTH(name))
-----------------
15
```
=> Set correct size of name column in SQL table

src/game/client/components/menus.cpp
Previously the labels would get squished even though a lot of space was available.
Before:
After:
=> Allocate more space for `DoLine_ColorPicker` label

src/game/client/ui_rect.h
I know the @note ``` reads cursed. But I really needed that example in there to ensure someone who never used or saw a call to Draw() can start using it just by looking at the doc hint. I also wanted it to display properly new lined and highlighted as code in both doxyygen and vscode. I played with markdown. \code{.cpp} and multi line code snippets.
This is the only way I found to achieve full syntax highlight including clickable links to ColorRGBA in doxygen. While also having it split on multiple lines and properly shown as a code snippet in vscode.
=> Add doc comment for CUIRect::Draw()

src/game/editor/editor.cpp
Offset was already supported but parallax was ignored. Now it looks at offset and parallax when ctrl+right clicking a tile.
While extensively testing it I found another limitation. Partial tiles are not always selected correctly when there is some offsetting and parallaxing happening. It only checks one tile at a time and that after doing ``/ 32``. So it selects by tile and not by pixel and the casting might lose the correct offset. This is not too bad because it only happens when the user clicks on the edge of a tile and offset or para is used. As long as the user clicks somewhat in the center it should all work smoothly. Especially since tiles are usually grouped together this should work in most cases. But supporting pixel based selection would still be a nice improvement for another …
=> Add parallax to layer selector (closed #7612)

src/game/client/components/console.cpp
The console while now keep your scrolling position during text selection. Previously your selection would jump all over the place if people were typing.
Before
https://github.com/ddnet/ddnet/assets/141338449/3af742de-8cd1-48da-9a2d-56319045d3ca
After
https://github.com/ddnet/ddnet/assets/141338449/919ba33a-04dd-47b8-93ca-b02ea5238f40
=> Keep console scrolling position during text selection

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/mapitems/layer_tele.cpp, src/game/editor/mapitems/layer_tele.h, src/game/editor/popups.cpp
This allows mappers to find teles by number.
Partially fixed #2194
https://github.com/ddnet/ddnet/assets/20344300/f2f27b72-f7d4-40e3-8c48-034240f0856f
I copy pasted the code from camera.cpp
https://github.com/ddnet/ddnet/blob/c09f1e133f0303fbe99bd67d1a2097a91b93e843/src/game/client/components/camera.cpp#L303-L355
Would love to share it somehow. But did not find a good way. Also when this is merged I will probably follow up with the same thing for switchers to fully close #2194
=> Add "View" button to tele drop down in editor

src/engine/client/serverbrowser.cpp
Because of incorrect index/size math, two favorite communities were removed when exceeding the maximum number of three favorite communities instead of only one. The check can be simplified because the maximum number of favorite communities can never be exceeded, so at most the first element needs to be removed from the vector.
Closes #7935.
=> Fix and simplify check for maximum number of favorite communities

src/engine/client/client.cpp, src/engine/shared/http.cpp, src/engine/shared/http.h
Add assertions to ensure that the HTTP request result data and SHA256 are available when getting them instead of returning `nullptr` and `SHA256_ZEROED` when they are not.
Rename `CHttpRequest::Sha256` function to `ResultSha256`.
=> Ensure correct HTTP request state when getting result

src/game/server/ddracechat.cpp, src/game/server/gamecontext.cpp
Previously, /tpxy only worked with ints, as well as negative numbers not working. With this change, you can teleport to any float coordinate, as well as negative coordinate, including being able to tp relatively in the negative direction which was previously broken as well, only being able to teleport down or right.
=> Fix /tpxy parameter bug

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/shared/config.cpp, src/game/client/components/menus.h, src/game/client/gameclient.cpp, src/game/client/gameclient.h
Instead of preventing the client from quitting/restarting while a warning is shown in the menus, add warnings that should be shown after quitting/restarting (i.e. the warning when the config could not be saved) to a separate list and show these warnings using an OS message box after the client has been closed. Otherwise, the client is prevented from closing if a warning is shown without being automatically hidden, which causes the client to hang indefinitely in the CI.
The message boxes for warnings must be shown after the client has already been completely shutdown, otherwise the regular shutdown with the Vulkan backend crashes because showing the message box has already partially deinitialized the backend.
The quitting/restarting client state is now checked after updating the FIFO …
=> Show warnings after client close instead of preventing quitting

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/game/client/components/menus.cpp
Simplify code by using generic warning system instead of hard-coding the warning.
=> Use generic client warning for failed sound init

src/game/server/ddracecommands.cpp
Fixes rcon left and rcon right, which were non functional because of this bug
=> Fix broken parameter in MoveCharacter

src/game/server/gamecontroller.cpp
For consistency between 0.6 and 0.7 clients, also show kill messages for 0.7 clients, now that DDNet client also supports finish messages.
Closes #5623.
=> Show kill messages also for sixup clients

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/mapitems/layer_switch.cpp, src/game/editor/mapitems/layer_switch.h, src/game/editor/popups.cpp
This allows mappers to find switchers by number.
#7931 is still not finished. Because it also demands shift+n functionality which is not yet implemented.
Works the same as #7929 just for switch instead of tele.
=> Add "View" button to switch drop down in editor

src/game/editor/editor.cpp, src/game/editor/editor.h
- Fix quad grid snapping
- Prevent placing brush when panning editor view
Thanks to texnonik for reporting these on Discord.
=> Editor: fix several quads related issues

src/game/editor/editor_history.cpp, src/game/editor/editor_history.h, src/game/editor/mapitems/layer_tiles.cpp, src/game/editor/mapitems/layer_tiles.h
Fixes #7959.
This was caused by calls to `FlagModified` each frame, mainly when changing the color property. However, changing the color of a tiles layer does not affect the automapper, so it should not be ran when having the auto button enabled. This PR fixes those problems by only calling `FlagModified` when changing a property that may affect the automapper (width, height, shift, image and automapper config).
Also, I added more cases for undoing auto automap: changing any of the properties mentioned earlier now cause an action to be recorded, which was not the case before so you could change a property that would run the automapper and undoing was a bit broken.
=> Editor: fix FPS drop when editing tiles layer properties

src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings_assets.cpp
Adds a flag search bar to the Player tab, so you can filter flags. Also resized every search bar in the settings to be the same width, in the Player, Tee, Assets tabs.
=> Add flag search

src/game/client/ui.h
Henlo :wave: I am learning the ui code a bit and got so used to passing local variable CUIRect references as argument to the .Draw() and split calls. So I did the same with ``DoEditBox()`` and it segfaulted into my face :panda_face:.
```
Thread 1 "DDNet" received signal SIGSEGV, Segmentation fault.
str_byte_next (ptr=0x7fffffffac90) at /home/chiller/Desktop/git/ddnet/src/base/system.cpp:3847
3847            unsigned char byte_value = **ptr;
(gdb) bt
#0  str_byte_next(char const**) (ptr=0x7fffffffac90) at /home/chiller/Desktop/git/ddnet/src/base/system.cpp:3847
#1  0x000055555625550a in str_utf8_decode(char const**) (ptr=0x7fffffffac90) at /home/chiller/Desktop/git/ddnet/src/base/system.cpp:3867
#2  0x00005555562556c5 in str_utf8_stats(char const*, unsigned long, unsigned long, unsigned …
```
=> Document `DoEditBox()`

src/engine/client/serverbrowser.cpp, src/game/client/components/menus_browser.cpp
Add a country "none" with tee flag (code `-1`) and a type "None" for all servers without community.
Previously, the country and type for these servers was unset and their handling special-cased, so any non-empty country/type filter would exclude servers without country/type information. Now individual countries/types can be excluded without also excluding all servers without community.
Closes #7961.
=> Add placeholder country/type for servers without community, fix filter excluding all items when right-clicking the only entry

src/engine/server.h, src/engine/server/server.cpp, src/engine/server/server.h, src/game/server/gamecontext.cpp
Instead of sending the message from the first client which is not ingame, choose the first client which is fully empty, to make it less likely that the message is sent from a currently connecting client.
=> Make it less likely that antibot message is sent from random tees

src/base/system.h
Add/update doxygen comments for all `shell_*`, `os_*`, `secure_*`, `cmdline_*`, `windows_*` and related functions.
Move `open_link` and `open_file` declarations to shell group, to the same relative position as their function definitions.
=> Document all shell, OS, secure random and related functions

src/game/editor/editor.cpp, src/game/editor/editor.h
Expose UI element ID for the main map editor as member variable so the select layer by tile funtionality can correctly be enabled when the map editor is the hot item.
=> Cleanup select layer UI element handling

src/game/client/components/mapimages.cpp, src/game/client/components/mapimages.h
=> Fix entities textures not being built for non-DDNet/DDRace types, fix assertion due to double-free of transparent texture 

src/game/editor/editor.cpp
I do not know why shift was locked on WASD. If that is conflicting with something else then it is bad.
The speed 128 feels a bit more natural as an increase. But 200 is more useful to get some distances done. Otherwise it has a hard time competing with mouse dragging speed.
=> [editor] Increase WASD pan speed when holding down shift

CMakeLists.txt, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/layer_selector.cpp, src/game/editor/layer_selector.h
Alternative for https://github.com/ddnet/ddnet/pull/7954
I did not like the complexity of #7954 at all. It was 3 callbacks and one of them gets called for every tile. Working with that was not nice. So I decided to go with one vector that can just be red by everyone who needs it. I like it from a developer experience now. But I hate the performance. It is iterating over all tiles in all layers every tick and pushing the ones under the cursor in some vector. I still get similar cpu/ram usage stats than before on my laptop. But there has to be a more performant way of achieving the same thing. Maybe not using a vector and use a statically allocated fixed size array of size 64 instead. And just drop support for hovering more than 64 overlapping tiles. Or calling that code less often. Only …
=> [vector] Move select layer to editor component

src/game/editor/editor.cpp
Fix logic for preferring grid over quad snapping.
The previous logic was not correct, which would make snapping to the grid impossible in some cases.
=> Editor: fix quad snapping when grid is enabled

src/engine/shared/console.cpp
=> Don't tell user about `/cmdlist` in rcon when using an unknown command.

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/game/client/components/console.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/voting.cpp, src/game/client/components/voting.h
Screenshots:
- Vote options:
- Remote console:
=> Render loading message/indicator for vote options and rcon commands

src/game/server/ddracecommands.cpp
Just for convenience during testing, using rcon undeep should unfreeze you instead of making you wait 3 seconds to get unfrozen after getting undeeped.
=> Unfreeze on rcon undeep

src/engine/client/serverbrowser.cpp
Add mandatory Boolean attribute `has_finishes` to every community info, which specifies whether finishes can be shown for the community, regardless of whether any finishes are currently available for the player.
The community info must be adjusted when/before merging this, by adding the attribute `has_finishes` to every community object, with the value `true` for DDNet and `false` for all other communities.
Closes #7957.
=> Add `has_finishes` attribute to community info

src/engine/shared/http.cpp
The function `curl_easy_setopt` expects a `CURL *`, but `pHandle` is a `void *`.
=> Fix incorrect variable used in Android-specific code

src/engine/shared/config_variables.h, src/game/client/components/infomessages.cpp
`cl_chat_teamcolors` will  now be enabled by default, I don't see why it is disabled by default? `cl_nameplates_teamcolors` is enabled by default, so why shouldn't this be?
I also removed the `cl_chat_teamcolors` check from info messages, as it's not related to chat at all.
=> Small fixes to `cl_chat_teamcolors`

src/game/client/components/menus_ingame.cpp
If the own ghost is the last element in the vector and deleted due to using the `cl_race_ghost_save_best 1` setting then the following accesses with index `Own` were out-of-bounds. Closes #8003.
=> Fix client crash if `cl_race_ghost_save_best 1` deletes last ghost

src/game/client/components/menus_settings.cpp
Use consistent margins for all settings pages and titles (except the Appearance settings, which will be covered in the future).
Fix checkbox UI element ID variable `s_LowerRefreshRate` not being `static`.
Improve readability of layout code.
Screenshots:
- Before: 
- After:
=> Improve layout of General settings page, refactoring

src/game/client/components/mapimages.cpp
Instead of only building the switch entities when the server uses the DDNet/DDrace type. Fix switch entities not being shown anymore on servers which do not mask entities. Regression from #7979.
=> Always build switch entities layer when map has switch layer

src/base/color.h, src/game/client/components/maplayers.cpp, src/game/client/components/maplayers.h, src/game/client/components/mapsounds.cpp, src/game/client/render.h, src/game/client/render_map.cpp, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/mapitems/envelope.cpp, src/game/editor/mapitems/envelope.h, src/game/editor/mapitems/layer_sounds.cpp, src/game/editor/mapitems/layer_tiles.cpp, src/game/editor/mapitems/map_io.cpp, src/game/editor/popups.cpp
Call `EnvelopeEval` functions directly instead of passing them and their arguments to `CRenderTools::RenderTilemap` and `CRenderTools::RenderTileRectangle`.
Only evaluate color envelopes for tiles layers once instead of separately for the opaque and transparent passes.
Only evaluate relevant number of envelope channels instead of always evaluating all channels.
Avoid unnecessary calculations by only evaluating position envelopes for quads which are not fully transparent.
Fully ignore layer color and envelope color for entities layers, as these cannot be specified in the editor and should not be changeable.
Remove duplicate and insufficient checks for invalid envelope index before calling `EnvelopeEval`. Instead, set the correct default for all channels before calling `EnvelopeEval` and …
=> Improve envelope evaluation and validation

src/game/client/components/chat.cpp
Previously if you did `/WHISP` and then tab, it wouldn't autocomplete to `/whisper`. This PR fixes that.
=> Make chat commands completion case-insenstive

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/serverbrowser_http.cpp, src/engine/engine.h, src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/engine.cpp, src/engine/shared/host_lookup.cpp, src/engine/shared/jobs.cpp, src/engine/shared/jobs.h, src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp, src/game/client/components/sounds.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/editor/editor.cpp, src/test/jobs.cpp, src/test/serverbrowser.cpp
Add `IJob::Abortable(bool)` function which jobs can call to specify whether they can be aborted. Jobs are not abortable per default. Abortable jobs may have their state set to `IJob::STATE_ABORTED` at any point if the job was aborted. The job state should be checked periodically in the `IJob::Run` function and the job should terminate at the earliest, safe opportunity when aborted. Scheduled jobs which are not abortable are guaranteed to fully complete before the job pool is shut down. However, if the job pool is already shutting down, no additional jobs will be enqueue anymore and abortable jobs will immediately be aborted.
In particular, the sound loading, community icon loading, master chooser and host lookup jobs are specified as being abortable. Conversely, the jobs saving replay …
=> Allow background jobs to be aborted, refactoring

src/engine/client/client.cpp, src/engine/server/server.cpp
Matching the requester allows "reliable" and "unreliable" pings. "Reliable" pings suffer from re-sends, thus might not accurately reflect the latency, "unreliable" pings might not arrive at all.
=> Respond to pings sent as vital messages with vital pongs

src/game/client/render_map.cpp, src/game/editor/editor.cpp
Closes #8005.
Screenshots:
- Example 1:
- Before:
- After: 
- Example 2 (you can see the missing first line segment here):
- Before:
- After: 
- Example 3 (you can see what "to the point where evaluation of bezier curves goes completely wrong in some cases" means):
- Before:
- After:
=> Various fixes for envelope and bezier evaluation

CMakeLists.txt, src/base/log.cpp, src/base/system.cpp, src/engine/client/client.cpp, src/engine/client/input.cpp, src/engine/server/main.cpp, src/engine/shared/fifo.cpp, src/engine/shared/http.cpp
Instead of defining the macro `WIN32_LEAN_AND_MEAN` and sometimes also the macro `_WIN32_WINNT` in each file that directly or indirectly includes `<windows.h>`, only define these macros once consistently in `CMakeLists.txt`.
Also define `NTDDI_VERSION`, which is the new macro to specify the minimum Windows version starting with Windows Vista. This macro needs to be defined in addition to old `_WIN32_WINNT` macro, according to the documentation.
See https://learn.microsoft.com/en-us/windows/win32/winprog/using-the-windows-headers
=> Define Windows header macros only once in `CMakeLists.txt`

src/game/client/components/menus.cpp, src/game/client/components/menus.h
Improve readability of the `CMenus::Render` function by extracting the code for rendering the fullscreen popups into a separate function.
*Note the diff is significantly shorter when ignoring whitespace.*
=> Extract `CMenus::RenderPopupFullscreen` function

src/game/server/gamecontext.cpp
According to the config description `sv_emotional_tees -1` should disable eye change completely but since `-1` evaluates to `true` that was not the case.
=> fix incorrect usage of `SvEmotionalTees`

src/game/client/components/background.cpp
Lets users input their entities background map without the .map file extension. Works with both cl_background_entities, and the input box in settings, DDNet tab.
=> Let users pick background entities map without file extensions

src/game/client/components/mapimages.cpp, src/game/client/components/mapimages.h
Only building the switch entities layer when the current map has a switch layer (#8011) also does not work, because the entities textures are cached for each type and not reloaded unless the entities are changed manually. First joining a server with a map that does not have a switch layer will cause the textures for the type of that server to be built without the switch entities layer, so the switch entities texture will be missing when joining a server of that type with a map that does have a switch layer.
Instead, the switch entities layer textures are always built now, so the cached entities textures are can be used on all maps of the respective server type. This is expected to slightly increase the total memory usage after joining multiple servers of different types. As before, tiles …
=> Always build switch entities layers

src/engine/client/client.cpp, src/engine/client/client.h
- Rename parameter `s` to `State`.
- Only print debug message if new state is different from old state.
- Reduce indentation.
=> Minor refactoring of `CClient::SetState`

src/engine/client/backend/vulkan/backend_vulkan.cpp
When image blitting is supported by the Vulkan backend, the color picker was reading incorrect pixel values, because the offset positions for the blitting region are the positions of the top-left and bottom-right corners, but instead the top-left offset and size (width, height) were passed as arguments.
Closes #8040.
=> Fix editor color picker when Vulkan image blitting used

src/game/editor/editor.cpp, src/game/editor/popups.cpp
The color selection should only be shown for normal envelope points but not for bezier control points, because it always changes the previously selected normal envelope point. This caused the client to crash when right-clicking a bezier control point when no normal envelope point was previously selected.
Closes #8020.
=> Fix editor crash when right-clicking bezier control points

src/base/system.cpp, src/base/system.h
Assert on failures in all `thread_*` and `sphore_*` functions on all operating systems instead of only printing log messages on Unix, as these functions are only expected to fail when used with incorrect arguments or in some cases when a dead-lock is detected.
On macOS, `sphore_wait` was not correctly calling `sem_wait` in a loop to repeat the wait operation if it is interrupted by a signal.
On Windows, the AIO tests were failing with the additional assertions. The maximum count that semaphores on Windows could be incremented to was previously, arbitrarily limited to 10000, which was causing the `ReleaseSemaphore` call to fail as the AIO semaphore is signaled 65536 times (for each write operation) in multiple of the AIO tests.
=> Add assertions to all thread and semaphore functions

src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser.h, src/engine/serverbrowser.h, src/game/client/components/menus_browser.cpp
Allows sorting by number of friends by taking it out of the players column and making it a separate friends column. 
The header uses white friend mark icon to save space. The overall proportions are roughly same as before.
When there are same number of friends on the servers it sorts by number of players instead.
Before:
After:
=> Add sorting by number of friends to the server browser

src/game/server/gamecontext.cpp
Previously:
```
2024-03-03 12:17:40 I git-revision: 885ae7ecaee4f1f7
2024-03-03 12:17:40 I server: version 18.0.3 on linux amd64
2024-03-03 12:17:40 I server: git revision hash: 885ae7ecaee4f1f7
```
=> Don't show the git revision twice in server log

src/engine/client/client.cpp, src/game/client/gameclient.cpp
Followup for #7919.
Prevent the `tune_zone` command from being shown and used in the local console, which could cause issues with prediction, by only registering it as a game setting but not as a client command. The command callback is still correctly called when map settings are loaded in the `CGameClient::LoadMapSettings` function.
=> Remove remaining hard-coded server commands from client-side, hide `tune_zone` command in local console

src/game/server/teams.cpp
=> Fix practice mode not resetting after disconnect on solo servers

src/engine/shared/http.cpp, src/engine/shared/http.h
Fix HTTP client effectively shutting down by entering the `ERROR` state when a request cannot be added. Now only the invalid request is aborted immediately. The `ERROR` state is now only entered when a curl function fails in a way where recovery is not possible.
Fix occasional deadlock when HTTP client is shutting down after entering the `ERROR` state, by also immediately aborting new requests when the HTTP client is already in the `ERROR` state.
Remove unused `CHttp::EState::STOPPING`.
=> Fix HTTP client shutdown and deadlock on request error

src/game/client/components/console.cpp
Show completion options for key names for all bind commands (`bind`, `binds`, `bind_reset`) in the local console.
At the moment this only works for completing the first key name but not for composite binds that use `+`, which would work differently than other console argument completion.
Unnamed keys (starting with `&`) are not shown as completion options.
Refactor console argument completion to reduce duplicate code.
=> Show completion options for bind key names in console

src/engine/client/backend/backend_base.cpp, src/engine/client/backend/backend_base.h, src/engine/client/backend/opengl/backend_opengl.cpp, src/engine/client/backend/opengl/backend_opengl.h, src/engine/client/backend/opengl/backend_opengl3.cpp, src/engine/client/backend/opengl/backend_opengl3.h, src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/client/text.cpp, src/engine/gfx/image_manipulation.cpp, src/engine/gfx/image_manipulation.h, src/engine/graphics.h, src/engine/textrender.h, src/game/client/components/mapimages.cpp, src/game/client/components/mapimages.h, src/game/editor/editor.cpp, src/game/editor/mapitems/image.cpp, src/game/editor/mapitems/map_io.cpp, src/game/editor/tileart.cpp, src/tools/dilate.cpp, src/tools/map_create_pixelart.cpp
Previously, usage of `void *`, `unsigned char *` and `uint8_t *` was mixed in various places for pointers to raw image data and the pointers ended up being cast to `uint8_t *` at some point anyway. Now only `uint8_t *` is used consistently, which improves type safety and readability. Casts to `uint8_t *` are now only necessary when using `malloc` or when reading data from a map.
=> Use `uint8_t *` consistently for raw image data

src/engine/shared/network_console_conn.cpp
`CNetConsole` will now ignore received lines containing invalid UTF-8 codepoints. Previously, it was possible to crash the server on Windows with Econ commands like `exec <invalid UTF-8>`.
=> Ensure commands executed via Econ are valid UTF-8

CMakeLists.txt, src/game/client/components/ghost.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/editor/mapitems/map_io.cpp, src/game/gamecore.cpp, src/game/gamecore.h, src/game/server/teeinfo.cpp, src/test/str.cpp, src/tools/demo_extract_chat.cpp, src/tools/map_convert_07.cpp, src/tools/map_diff.cpp, src/tools/map_find_env.cpp, src/tools/map_replace_area.cpp
Add strict validation for `StrToInts` function. Because this function should only be used with trusted internal strings, assertions are added to ensure that the string is not truncated. Some buffer sizes are adjusted accordingly, so truncation cannot happen.
Add less strict validation for `IntsToStr` function. An additional argument specifying the size of the output buffer is added to assert that the size of the output buffer is sufficient. However, because this function is used to decode data sent by the server and read from maps and ghosts, invalid input data should never result in crashes or invalid UTF-8 strings. The function will now unpack an empty string and return `false`, if the string contains invalid UTF-8.
The inline definition of the functions is not wanted, because it …
=> Add validation for `StrToInts` and `IntsToStr`

src/engine/client/serverbrowser.cpp, src/engine/server/server.cpp, src/engine/serverbrowser.h, src/engine/shared/config_variables.h, src/engine/shared/serverinfo.cpp, src/engine/shared/serverinfo.h, src/game/client/components/menus_browser.cpp
Adds `br_filter_login`, which filters out servers that requires an account to play (e.g. Kog's [A] servers). The filter is enabled by default. The filter works by reading the `requires_login` boolean property from the server's info object.
Closes #8024
=> Add a `No login required` filter

src/game/server/ddracechat.cpp, src/game/server/entities/character.cpp, src/game/server/player.cpp, src/game/server/score.cpp, src/game/server/score.h, src/game/server/scoreworker.cpp, src/game/server/scoreworker.h
Fixed the command not working without having a finish on the map.
Added appropriate chat responses since it was rather confusing to use.
=> Improve `/timecp` chat command

src/engine/client/client.cpp
This is the only sane thing we can do, the server will have changed its map and we can't pretend to still be on the old one.
Also inform HTTP map download of the map size.
=> Disconnect when we get map change with invalid parameters

src/game/client/lineinput.h, src/game/client/ui.cpp, src/game/client/ui.h, src/game/client/ui_listbox.cpp, src/game/client/ui_scrollregion.cpp, src/game/client/ui_scrollregion.h
Support scrolling all scroll regions with the mouse wheel also while popup menus are open. Support overlapping scroll regions by always scrolling the top-most hovered scroll region on mouse wheel events.
The hot scroll region is now tracked separated by `CUi`, as tracking the IDs of all UI elements which are contained in scroll regions is not feasible. The separate active state for scroll regions is therefore unnecessary.
It's still necessary to disable `CListBox`es when popup menus are open, to ensure that only one list box consumes the key events.
Closes #8087. Supersedes #8090.
=> Support overlapping scroll regions, always allow mouse scrolling

src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser_http.cpp, src/engine/client/serverbrowser_http.h, src/engine/shared/http.cpp, src/engine/shared/http.h
Prefer masters with newer server lists, and try re-selecting the chosen master if the result is older than 5 minutes.
=> Take serverlist age into account when choosing master

src/game/collision.cpp, src/game/collision.h, src/game/gamecore.cpp, src/game/gamecore.h, src/game/server/ddracecommands.cpp, src/game/server/entities/character.cpp, src/game/server/entities/character.h, src/game/server/entities/laser.cpp, src/game/server/entities/projectile.cpp, src/game/server/gamecontroller.cpp, src/game/server/gamecontroller.h
Woah there cowboy! I know how this looks like. Breaking physics? Adding crash bugs? Increasing client startup time??
While trying to implement shift+n to see the previous teleporter in the editor I noticed how broken my old code is.
This thing seems to skip some tele tiles it should find #6887. Also the code is looping through the entire map which is not performant enough for live tele tracing which is needed for #2415. Also the weird loop makes it super messy to step forward and backward which is needed for #7931.
Having an indexed map seems like something that belongs into collision anyway and not into the game controller.
This also gives the client access to it. It does not use it yet. So for now its useless memory and cpu usage on client boot. Which I do not like. I was thinking of …
=> Move tele vector init from gamecontroller to collision

src/engine/client/serverbrowser_http.cpp
The `unknown address` log message got printed very often because many servers have 0.6 and 0.7 addresses but only 0.6 addresses are considered valid by the client.
See https://github.com/ddnet/ddnet/pull/8099#discussion_r1525420552.
=> Comment out verbose serverbrowser HTTP log message, fix typo in serverbrowser HTTP log context

src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/game/client/components/mapimages.cpp, src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp, src/game/client/components/skins.cpp, src/game/client/gameclient.cpp, src/game/editor/editor.cpp, src/game/editor/popups.cpp, src/game/editor/tileart.cpp
The engine graphics do not need to be involved with freeing image data.
The `Free` function now also ensures that all other member variables are cleared when freeing the image data.
=> Replace `IGraphics::FreePNG` with `CImageInfo::Free`

src/game/server/ddracechat.cpp
`eyeemote` will keep its setting after death, so I'm not sure what that part is supposed to mean.
=> Remove `(until you die)` part from `/eyeemote off`

src/engine/client/serverbrowser_http.cpp
We're not allowed to look at `ResultAgeSeconds` when the state is `EHttpState::ERROR`.
Fixes #8107.
=> Fix crash when the serverlist request fails

src/game/client/components/menus_settings.cpp, src/game/client/ui.cpp
=> Fix replacement of `UI` with `Ui` in strings

src/game/client/components/nameplates.cpp
Fixes strong indicator not showing above:
- players in different team or solo
- all players when paused
Additionally strong indicator is now shown from perspective of locked on player as described in #7704
closes #7704
=> `ClNameplatesStrong` improvements

src/game/client/ui_listbox.cpp, src/game/client/ui_listbox.h, src/game/editor/editor.cpp, src/game/editor/popups.cpp
Fixes #8116.
Also supports navigating in selection popups (image, automapper and sound) with `UP` and `DOWN` arrow keys.
=> [Editor] Fix crash when trying to select autorule with arrow keys

src/game/editor/mapitems/map_io.cpp
In the editor, currently if you create new quads and sounds layers or have quads and sounds layers that are empty and then save the map, it will not save those empty layers. This then leads to missing layers and you can wonder where they went. I don't think this is needed (and it surprised me when I discovered this), as we can optimize the map if we need to to clear any empty layers afterwards but not while saving in the editor.
Now it will correctly save those layers as well.
=> Editor: allow saving empty quads & sounds layers

src/game/editor/mapitems/layer_tiles.cpp
`Result` was not the correct variable to use to index the operation names array, instead it should be what is returned from the selection popup.
Fixes #8135.
=> [Editor] Fix crash when constructing some game tiles

src/game/server/entities/character.cpp, src/game/server/entities/character.h
The freezebar would previously be incorrect after returning from pause. The bar would countdown, but at a slower speed. Cherrypicked fix from #6724
Before
https://github.com/ddnet/ddnet/assets/141338449/1416a5bc-f138-4b75-9d5c-76f12670f118
After
https://github.com/ddnet/ddnet/assets/141338449/0480a4bc-f8af-4a6b-9ace-bcee7c676994
=> Fix freeze bar not being correct after returning from pause

src/base/system.cpp, src/base/system.h
The function `fs_makedir_rec_for` for recursively creating folders did not handle paths containing backslashes correctly and only created folders after every occurrence of a regular slash. This could cause the recursive folder creation to fail when a parent folder is not created before the child folder. For example when recursively creating folders for the path `D:\Games/DDNet\downloadedskins`, the `DDNet` folder was not being created because this path segment does not end in a forward slash. Now, backslashes are handled the same as regular slashes, which is consistent with the other filesystem functions.
Additionally, the function tried to create folders for drive letters on Windows (e.g. `C:` and `D:`). Trying to create a system drive as a folder will fail due to access being denied, …
=> Fix recursive folder creation with mixed slashes and drive letters

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_start.cpp
Split menu rendering explicitly by client state. This makes the code more readable by not mixing code for rendering different states together as much and fixes issues where the menu was being rendered inconsistently for one frame when the state is changed, at the cost of some additional duplicated code.
The fullscreen popups shown when in the connecting and loading client states are now hard-coded for these states, instead of being mixed together with the other fullscreen popups, which can be shown when offline, ingame or during demo playback.
As a side effect of rendering the demo controls like the regular menu, the UI color will now also affect the demo controls menu background.
Move `CBackground::ChangePosition` calls inside functions to reduce duplicate code and improve readability. …
=> Refactor client state handling in menus

scripts/parse_drmingw.sh
Use `objdump` instead of `winedump` to determine the image base address of the executable file, as `winedump` is not easily available on Windows.
It should be enough to install the `binutils` package (containing `addr2line` and `objdump`) from a package manager to use the script now.
=> Make `parse_drmingw.sh` script also useable on Windows with MSYS2

src/game/client/gameclient.cpp
Instead of only resetting the tuning for either one which is currently active.
=> Reset tuning of dummy and main when disconnecting

src/game/client/components/console.cpp
The rcon username requirement was not reset correctly when disconnecting from a server while connecting/loading, at which point the `NETMSG_RCONTYPE` message has already been received.
Closes #4170.
=> Fix rcon username not reset when disconnecting while connecting

src/game/client/components/chat.cpp, src/game/client/components/controls.cpp, src/game/client/components/damageind.cpp, src/game/client/components/debughud.cpp, src/game/client/components/emoticon.cpp, src/game/client/components/freezebars.cpp, src/game/client/components/ghost.cpp, src/game/client/components/hud.cpp, src/game/client/components/infomessages.cpp, src/game/client/components/motd.cpp, src/game/client/components/nameplates.cpp, src/game/client/components/players.cpp, src/game/client/components/scoreboard.cpp, src/game/client/components/spectator.cpp, src/game/client/components/statboard.cpp
Skip rendering various client components (players, ghosts, nameplates, HUD etc.) while not ingame to improve performance. This increases FPS when rendering the start menu by around 300-400 both in debug and release builds.
This also fixes potential crashes when components using the map data where rendered while the client is loading a new map.
=> Improve performance when rendering menus

src/game/client/components/menus_settings.cpp
Use consistent margins for all settings pages and titles.
Fix chat preview overlapping with the restart warning.
Simplify layout code. Remove array of `CButtonContainer`s with arbitrary size and use individual variables instead.
Remove unnecessary, inconsistent margin at the top of all settings menus.
Reserve space for restart message and button only when necessary, so more height is available for settings menus per default.
Improve vertical alignment of restart message and button with settings menus.
Ensure consistent margin on all sides of settings menus.
Screenshots:
- HUD
- Before:
- After:
- Chat
- Before:
- After:
- Name Plate
- Before:
- After:
- Hook Collisions
- Before:
- After:
- Info Messages
- Before:
- After:
- Laser
- Before:
- After:
- Chat (with restart message)
- Before: …
=> Improve layout of Appearance settings, overall settings menus and restart message 

src/engine/shared/config_variables.h, src/engine/shared/econ.cpp
Previously it wasn't very clear that `ec_password` is required to be set for econ to work. I've now updated the description of it and now also print a message when you only set `ec_port`.
> econ: ec_password is required to be set for econ to be enabled.
=> Specify that `ec_password` is required to be set for econ to be enabled

src/engine/client/discord.cpp
There seems to be an issue with `clear_activity` in the version of discord game sdk that we are using: `ResponseError { code: InvalidPayload, message: "child \"activity\" fails because [child \"supported_platforms\" fails because [\"supported_platforms\" must contain at least 1 items]]" }`
closes #8180
=> Show Discord activity when offline

src/engine/client.h, src/engine/client/client.cpp, src/game/client/projectile_data.cpp
Adding the snap to the demo is the last usage of `pTmpBuffer3` all prior usages of it copy the data if needed.
So we can edit it in place. No need to copy it into a new buffer.
=> Remove demo snap buffer and mem copy

src/game/server/ddracechat.cpp, src/game/server/entities/character.cpp, src/game/server/gamecontext.h, src/game/server/gamemodes/DDRace.cpp, src/game/server/save.cpp, src/game/server/score.cpp, src/game/server/teams.cpp, src/game/server/teams.h
Maybe more of a concept?
Not sure if this is too hacky and can't guarantee this doesn't break things.
Adds `/mode` that can enable teams to behave like team 0 with the added benefit of being able to manage it with `/lock` and `/invite`.
Tested with possible configurations such as `sv_team`, `sv_max_team_size`, `sv_min_team_size`, `sv_solo_server`.
Teams in "team 0 mode" can't use `/save`,  `/load` or `/practice`.
Closes #7380 
Very little showcase:
https://github.com/ddnet/ddnet/assets/121701317/ea2b848a-0af4-4b97-a769-890901a9ef42
=> Add `/mode` allowing teams to behave like team 0

src/game/server/ddracechat.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
The rebase of #7521 made the `/flock` command not be added. I've also changed any previous mentions of `team 0 mode` to `flock mode` and also added an explanation of what `flock mode` does.
=> Fix broken rebase of `ConFlock`, rename previous remains of `team 0 mode`

CMakeLists.txt
I just ran into https://github.com/google/googletest/issues/4206 and realized that it is fixed on the main branch and google also recommends to use the main branch.
From their readme
> GoogleTest now follows the Abseil Live at Head philosophy. We
> recommend updating to the latest commit in the main branch as often as
> possible. We do publish occasional semantic versions, tagged with
> v${major}.${minor}.${patch} (e.g. v1.14.0).
https://github.com/google/googletest/blob/3d73dee972d0db344bda9b659836612aba6a3564/README.md#live-at-head
=> Update gtest to current main branch

src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser.h, src/engine/serverbrowser.h, src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_start.cpp
For the internet/favorite tabs, instead of combining the country/type filters of all communities in one view, track the country/type filters separately for these tabs using the new, reserved community name `all`. This should make the filters less confusing to use, as changing the country/type filters in one tab will not influence the other tabs anymore. Though the country/type filters of the internet and favorite tabs are still combined, as this is also the case for the community filter.
However, this made it possible to select country/type filters that exclude all servers, by first excluding some countries/types and then changing the selected communities so all selectable countries/types are excluded. To prevent this, the filters will now include all countries/types, if they would …
=> Track country/type filters separately for internet/favorites tabs

src/game/server/ddracechat.cpp
=> Prevent enabling `/team0mode` while practice mode is active

src/engine/shared/config_variables.h
Since we have https://github.com/ddnet/ddnet/pull/8199 now
=> Enable team0mode by default again

src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/client/prediction/gameworld.h
Previously, when connecting to servers repeatedly, the local tee would appear at the position it had on the previous server for a short time when joining.
This (and potentially other bugs) are fixed by clearing all game related `CGameClient` member variables in the `OnReset` function. Additionally, the `OnReset` function is now used in the `OnInit` function to ensure everything is initialized correctly when starting the client and to avoid duplicating the code.
In particular, this bug was limited to use of `cl_predict 1`, because the predicted gameworlds were not being reset when disconnecting, causing the predicted world and character from the previous server to be used. This bug was introduced in version 15.6, which added the predicted gameworlds in #1620. Closes #4339.
=> Fix tee briefly appearing at previous position when joining

src/game/client/components/menus.cpp, src/game/client/components/menus_demo.cpp
The demo player needs to be rendered also when the menu is inactive, to handle the hotkeys for controlling the demo player and to render the play/pause and speed indicators.
Closes #8208.
The popup menus are already rendered in the `CMenus::Render` function, also for the demo player since #8156.
=> Fix demo player hotkeys not working when menu is inactive, fix duplicated rendering of popup menus in demo player

src/game/editor/mapitems/layer_tiles.cpp
Fixed bug where these first buttons wouldn't place any tiles. Most likely caused by #8136
=> Fix bug where certain tiles would not work in `Game tiles` menu

src/game/server/scoreworker.cpp
It would previously fail with `Unknown column 'hasCP' in 'where clause'` on MySQL/MariaDB, but worked fine with SQLite. The query has now been updated to work with both. Closes #8214
=> Fix `/timecp` not working with MySQL

src/game/server/ddracechat.cpp, src/game/server/ddracecommands.cpp, src/game/server/entities/character.cpp, src/game/server/entities/character.h
I have honestly no idea if thats the right approach and I'm uncertain about what other adjustments might be necessary.
I'm currently in a hotel on a rainy day, and I decided to test a map for fun. I noticed a minor inconvenience: the only way to regain the double jump (after it's been used up) is by landing or using the /r command. However, using /r isn't always ideal, especially if a platform is far away. Take a look at the videos for more details.
https://github.com/ddnet/ddnet/assets/60477660/fc129c9e-5c54-4ae5-9ae7-01210dcb7a5b
https://github.com/ddnet/ddnet/assets/60477660/23349624-94ab-47b9-9e60-158b5645c5a7
=> Refresh air jumps after teleporting

src/engine/client/client.cpp
Clear current server info when playing demos to ensure that the score kind (points, time) is detected correctly. Previously, when playing a demo with points score kind and `cl_demo_assume_race 0`, the score was not shown as points when the last server that the client connected to had a race gametype.
Move the implementation for `cl_demo_assume_race` together with the rest of the demo server info initialization in the `CClient::DemoPlayer_Play` function.
=> Fix incorrect score kind in demos depending on last server

src/game/client/components/menus_browser.cpp
I'm not sure if this was intended but no variation makes it easier to read.
Before:
After:
=> Fix alignment of labels in friends list

src/game/server/score.cpp
It's not necessary, because you can get back to the position anyway.
=> Disallow `/save` on teams with practice enabled

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_start.cpp, src/game/client/components/nameplates.cpp, src/game/client/components/nameplates.h, src/game/client/gameclient.cpp
Use the gameclient to access other components instead.
=> Remove unnecessary client component variables and setters

src/game/server/entities/character.cpp
The purpose of this condition is to only update the freeze time every 50 ticks so the freeze bar keeps being refilled after one second when standing in freeze, but it incorrectly prevented freeze from being applied during the first 50 ticks after the map has been loaded. Now, freeze is also applied if not currently frozen, so the behavior directly after changing the map is identical to subsequent respawns.
=> Fix freeze not working during first 50 server ticks

src/game/server/ddracechat.cpp, src/game/server/score.cpp
Also require that practice mode is disabled for `/load` to reduce possible side effects.
Follow up on #8220
=> Disallow activating /practice while save is in progress and improve messaging for when `/save`/`/load` command does nothing

src/engine/client/client.cpp, src/engine/client/client.h, src/engine/client/video.cpp
Add optional filename argument to `start_video` command, to start recording to a video file with a specific filename, instead of always using the current timestamp.
Add log messages to `start_video` and `stop_video` commands to indicate success and errors.
Make the `CClient::StartVideo` function non-`static` and reduce duplicate code in the `Con_StartVideo` function.
Determine the video filename outside of the `CVideo` constructor, same as for demos.
=> Add optional name argument to `start_video` command, improve descriptions of demo-related console commands, refactoring 

src/game/client/components/players.cpp
Fix out-of-bounds accesses when rendering ghost players, which use the client ID `-2`. This was causing the hook collision line of ghost players to be affected by real players, which is not correct, as ghosts do not interact with other characters.
Closes #8239.
=> Fix OOB accesses rendering ghosts, fix ghost hook collision line

src/engine/shared/ringbuffer.cpp, src/engine/shared/ringbuffer.h, src/game/client/components/console.cpp
Fix backlog corruption in `CConsole::PumpBacklogPending` when many backlog entries are allocated at the same time. When allocating many entries from the `m_Backlog` ringbuffer at the same time, the first entries being allocated may already have been recycled again, so the pointers to them being stored in the temporary vector of new backlog entries were pointing arbitrarily into the ringbuffer data, which could cause corruption of the structural and user data of the ringbuffer. Now, we iterate over the entire backlog and only update uninitialized entries instead of storing the new entries separately.
This was sometimes caught as a misaligned access with UBSan:
```
src/engine/shared/ringbuffer.cpp:160:14: runtime error: member access within misaligned address 0x00014126f4df for type 'struct …
```
=> Fix potential client crash and console not keeping scrolling position when console backlog is full

data/languages/turkish.txt
"Kill" is translated as "intihar et" by the other translators. "İntihar et" means "suicide".
1. Not using the word "intihar et" because of its meaning is more accurate.
2. In game, "intihar et" causes the font getting smaller and it does not fit in the box. (https://prnt.sc/4hxQlZdoN1MS)
Using "öl" would be better instead of "intihar et" because it fits in the box better and it keeps the original meaning more.
---
The word "Name" is translated as "Takma ad", which means nickname. It causes a mistranslation by showing up above the server's name. (https://prnt.sc/1NUC5_5qR_H8)
In this scenario, using "sunucu ismi" which means "server name" would fit better.
---
Even the word "Website" means "internet sitesi" in Turkish, it does not fit in the box and can cause the font getting smaller so it …
=> Update Turkish translations for 18.2 (by Gokturk)

src/engine/shared/snapshot.cpp, src/engine/shared/snapshot.h
There is already a DebugDump() method for snapshots but there was none for deltas yet. I wrote this to debug an issue I was facing that only happend after the delta was unpacked so I wanted to see what was in the delta.
The method is unused and supposed to be patched in while debugging. For example like this
```diff
diff --git a/src/engine/client/client.cpp b/src/engine/client/client.cpp
index 79a19a65b..ce0be00b8 100644
--- a/src/engine/client/client.cpp
+++ b/src/engine/client/client.cpp
@@ -1757,6 +1757,9 @@ void CClient::ProcessServerPacket(CNetChunk *pPacket, int Conn, bool Dummy)
DeltaSize = IntSize;
}
+
+                                       m_SnapshotDelta.DebugDumpDelta(pDeltaData, DeltaSize);
+
// unpack delta
const int SnapSize = m_SnapshotDelta.UnpackDelta(pDeltaShot, …
```
=> Add delta debug dump

src/engine/shared/snapshot.cpp
=> Fix warning because of incorrect format argument for `size_t`

src/engine/client/sound.cpp, src/game/editor/editor.cpp, src/game/editor/mapitems/sound.h
#8262 is not fixed entirely by this, as I could not reproduce the assertion and the potential race condition is not prevented yet.
=> Fix crashes and memory leaks related to editor map sounds and opus file decoding, refactoring

src/game/server/gamecontext.cpp
The command confusingly assumed the empty string if no argument was passed.
=> Make `change_map` parameter non-optional

src/engine/client/backend_sdl.cpp, src/engine/client/client.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/game/client/components/menus_settings.cpp
=> Revert screen mode config variables when change not accepted, update screen index config variable after moving window 

src/base/log.cpp, src/base/logger.h, src/engine/client/client.cpp, src/engine/server/main.cpp
Fix leak of pending future logger log messages if the future logger is not set, in particular when the `logfile` config variable is not set or the file could not be opened, by setting a logger that discards all log messages in this case.
Closes #8265.
=> Add no-op logger to fix leak of `CFutureLogger` pending messages

src/engine/client/client.cpp, src/game/client/components/menus.cpp
Always use the server address from the network client to reconnect to the correct server after being disconnected due to wrong password. The password popup is only shown after being disconnected, so the server address of the network client should always the address of the server which the client should reconnect to with the password. Using `ui_server_address` was causing the wrong address to be used after being redirected to another server and if the config variable is changed while the password popup is open.
Closes #8260.
=> Fix wrong server address used in password popup when redirected, minor refactoring

src/engine/shared/snapshot.cpp
The problem was that the ddnet ex items would be registered when the snapshot builder was initialized. So it checked which ddnet ex items have been used already and then register those uuids. But then all new ddnet ex items that will be added to this snap are not registered. This way the registration is always lacking one snap behind. This could cause some nasty to debug off by one snap errors that are also rare because this only happens for ddnet ex items that were not used by the server before.
=> Fix ddnet ex snap item registration (closed #8271)

src/engine/client/backend/backend_base.cpp, src/engine/client/backend/backend_base.h, src/engine/client/backend/opengl/backend_opengl.cpp, src/engine/client/backend/opengl/backend_opengl3.cpp, src/engine/client/backend/vulkan/backend_vulkan.cpp
Use `ResizeImage` function directly instead.
=> Remove `CCommandProcessorFragment_GLBase::Resize` delegate

src/game/server/entities/character.cpp, src/game/server/entities/character.h, src/game/server/entity.h, src/game/server/gamecontext.cpp, src/game/server/gameworld.cpp, src/game/server/gameworld.h
Relevant upstream commit:
https://github.com/teeworlds/teeworlds/commit/d2924b5ad6982945da5f2db299d964133a3e5e63
Closes https://github.com/ChillerDragon/ddnet/issues/7
The snap item [obj_character](https://chillerdragon.github.io/teeworlds-protocol/07/snap_items.html#obj_character) contains a field called m_TriggeredEvents
It is responsible for effects and sounds. Those flags are set in the gamecore. So if the servers gamecore ticks twice and resets the flags before a snap is sent the client misses the information. Which is not too big of a problem since the client has his own gamecore running (prediction) which also sets those flags. But it is still wrong and teeworlds does always include the triggered events in the snap.
So this commit fixes it using the same approach as teeworlds. By …
=> Make sixup TriggeredEvents reliable

src/game/client/ui_rect.cpp
=> Remove useless operation in CUIRect SplitMid

.clang-tidy, src/base/.clang-tidy, src/tools/.clang-tidy
For now it is only checking local variables. There are also member/private/protected/parameter/global and so on variables. There are a lot of exceptions to show 0 warnings on the current code base which has a bunch of style violations when it comes to short variables. And also the hungarian like teeworlds variable prefixes ``p*`` ``a*`` etc are violating strict camel case. Clang tidy has support for hungarian notation. And it is also quite configurable. You can choose your own prefix for all types. But I did not manage to reorder the prefixes or remove prefixes. So it would try to prefix all integeres with ``i`` and all bools with ``b`` and use ``pa_`` instead of ``ap_``. So I went with strict camel case instead and allowed our hungarian prefixes and the short variables.
This would close …
=> Enforce UpperCamelCase for local variables

src/game/server/gamecontext.cpp
When using the `remove_vote` command, the entire heap of vote options is allocated again without the entry being removed. This allocation was not considering the required alignment for `CVoteOptionServer` objects and potentially wasting space by aligning with `alignof(std::max_align_t)`. When allocating the entries with the `add_vote` command, the alignment is already specified correctly.
=> Fix alignment of vote option heap entries with `remove_vote`

src/game/client/gameclient.cpp, src/game/collision.cpp, src/game/collision.h, src/game/layers.cpp, src/game/layers.h, src/game/server/gamecontext.cpp
Ensure that the `CCollision` and `CLayers` instances do not keep any pointers to the map data after the map has been unloaded.
=> Also unload collision and layers when unloading map

src/engine/shared/console.cpp
Fixes this clang-tidy 19 warning
```
/home/chiller/Desktop/git/ddnet/src/engine/shared/console.cpp:739:2: error: static member accessed through instance [readability-static-accessed-through-instance,-warnings-as-errors]
739 |         pConsole->ConCommandStatus(&Result, pConsole);
|         ^~~~~~~~~~
|         CConsole::
```
=> Don't access static ConCommandStatus with a member

src/engine/server/register.cpp, src/engine/shared/network.cpp, src/engine/shared/network.h, src/engine/shared/network_conn.cpp, src/engine/shared/network_server.cpp
Previously, it was handled inconsistently on big-endian machines and caused connection failures.
=> Use network tokens in big-endian byte order consistently

src/game/client/components/effects.cpp
Nudge the initial position for explosions' smoke particles slightly towards the edge of the closest non-solid tile, if it would otherwise be inside a solid tile, so the smoke particles do not get stuck inside solid tiles on explosion events happening at the edges of tiles but slightly inside them. The physical position of the explosion event is unchanged, so this does not affect physics. The explosion sprite is still rendered at the physical position of the explosion, to preserve the apprearance.
Comparison screenshots:
- Before (several smoke particles could bunch of at the center of the explosion depending on the exact position):
- After:
Comparison videos:
- Before:
https://github.com/ddnet/ddnet/assets/23437060/a8cc59df-12ca-4105-837e-4ee43e66237a
- After: …
=> Fix smoke particles sometimes being stuck inside solid tiles

.clang-tidy
It already used to enforce camel case for variables defined in methods.
It now also enforces camel case for local constants, class members, class methods, class names, struct names, method parameters.
It also enforces a m_ prefix for class member and a C/S prefix for class and struct names.
There are a bunch of exceptions with ignore regexes to make it pass on the current code base without any changes.
The most crazy one is that structs starting with `C` or `S` are okay. There are just too many structs in the code that start with `C` instead of `S`. And it seems like clang tries to apply class and struct prefixes to structs. So it would try to enforce `CSClassName`. That could be smoothed out when we decide that we want to use classes instead of structs in the future …
=> Enforce more styling with clang tidy

src/game/server/ddracechat.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
Some people wanted the ability to give themselves weapons within practice mode without having to teleport to the location of the weapon on the map. This allows them to do so by typing something like `/grenade` in the game chat (as long as they're in a team with practice mode enabled).
Note that with the way things are currently being done, there's no clean way for me to "wrap" the callbacks used in the rcon commands cleanly. Currently there has to be a duplicate function for every command that we want to wrap. If you have any ideas on how to reduce the amount of boilerplate please let me know.
Closes #8092
=> Add chat commands for toggling weapons in practice mode

src/game/client/components/mapimages.cpp, src/game/editor/mapitems/map_io.cpp, src/game/mapitems.h, src/tools/map_extract.cpp
Cherry-picked from https://github.com/teeworlds/teeworlds/pull/2822.
CC https://github.com/teeworlds/teeworlds/issues/2812
CC https://github.com/teeworlds/teeworlds/issues/962
Since DDNet never saved these kinds of images, this should cause no issues.
=> Remove RGB images from the map file format

src/game/client/components/menus.h
This reverts commit f319ed239ad27ceda928b9bcd399ca6c6379c88b.
Initializing these variables with junk data doesn't seem to be an improvement over not initializing them. It hides potential Valgrind warnings about data accesses to uninitialized memory though.
https://github.com/ddnet/ddnet/pull/8309/commits/f319ed239ad27ceda928b9bcd399ca6c6379c88b#r1590801501
=> Revert "Initialize all ghost item member (Closed #8297)"

src/engine/shared/network_server.cpp
They're also read as big-endian integers now.
Thanks to @ChillerDragon for noticing.
Fixes #8330.
=> Fix 0.7 tokens after #8322

src/base/system.cpp, src/base/system.h, src/engine/shared/netban.cpp, src/engine/shared/netban.h
closes: #8303 
this expects all systems to correctly handle int64_t
from heinrich:
>  Simply changing the return type and places where it's used to int64_t should work. Most systems today will have 64-bit time_t.
=> Change type from int to int64_t

scripts/integration_test.sh
Try to fix `database is locked` CI error with `.timeout`. Not sure if it fixes the error, as I have no way of reproducing it. Closes #8325
=> Set sqlite3 `.timeout` in `integration_test.sh`

src/engine/graphics.h
=> Remove unused `CImageInfo::ImageFormatFromInt`

src/game/client/components/menus_settings.cpp
The controller name is also shown if there is only exactly one controller connected, but the height was not increased for the additional row.
Screenshots:
- Before: 
- After:
=> Fix height of controller settings with exactly 1 controller

src/game/client/components/menus_demo.cpp
The tooltip was not shown if the seekbar is the active item, i.e. when the first mouse button is held down and the seekbar is currently updating the demo player.
The seekbar is immediately activated if the mouse button is held while moving the mouse over the seekbar, which is inconsistent with the general `DoButtonLogic` behavior. This is problematic on Android, where the first mouse button is always pressed while the mouse is being moved, causing the seekbar to steal focus immediately when hovered.
=> Fix demo seekbar tooltip not shown while seekbar is active, fix demo seekbar being activated by held button press

src/engine/client/backend/vulkan/backend_vulkan.cpp
fixes #8328
I was able to reproduce #8328 by simply faking the swapchain image count
```cpp
uint32_t ImgNumber = VKCapabilities.minImageCount + 1 + rand() % 5;
```
in `GetNumberOfSwapImages`.
For sync objects I decided that they should not be dependent on the frame count directly anyway.
For vulkan cleanup simply take the swapchain count as parameter instead of relying on the cached one (since that is overwritten when recreating the swapchain).
Also minor refactoring.
=> Fix segfault when swapchain images change (e.g. toggling Vsync)

src/engine/shared/config_variables.h, src/game/client/components/chat.cpp, src/game/client/components/menus_settings.cpp
useful for people and especially streamers who don't want to receive messages by people not in their team
=> add option to show only messages by team members

src/tools/map_create_pixelart.cpp
Currently, it stores too much (probably uninitialized) data in the quad layer.
=> Fix off-by-one error in map_create_pixelart

scripts/languages/copy_fix.py
Always initialize the variables `local` and `supported` instead of initializing them conditionally, to fix the false-positive `possibly-used-before-assignment` pylint detection.
Closes #8369.
=> Fix `possibly-used-before-assignment` in `copy_fix.py`

src/engine/client/backend/opengl/backend_opengl.cpp, src/engine/client/backend/opengl/backend_opengl.h, src/engine/client/backend/opengl/backend_opengl3.cpp, src/engine/client/backend/opengl/backend_opengl3.h, src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h
The graphics backends only support the RGBA format with the `SCommand_Texture_Create` and `SCommand_Texture_Update` commands, so the `TexFormatToOpenGLFormat`, `TextureFormatToVulkanFormat` and `TexFormatToNewOpenGLFormat` functions and the command member variables for the format are unnecessary. The `TexFormatToNewOpenGLFormat` function was unused.
=> Remove redundant graphics backend functions returning RGBA format

scripts/parse_drmingw.sh
Example output before this change:
```
Module offset: 0x00007FF7C8DE0000
Image base: 0x0000000140000000
0x0000000772cb5efc: ?? ??:0
0x000000077cd5c3e8: ?? ??:0
0x000000075d063cc3: ?? ??:0
0x000000075d2a3d61: ?? ??:0
0x000000075d0b7fde: ?? ??:0
0x000000075d2a5f18: ?? ??:0
0x000000075d2a6809: ?? ??:0
0x000000075d0b8140: ?? ??:0
0x000000075cf9d41b: ?? ??:0
0x000000014034b4c7: CCommandProcessorFragment_Vulkan::WaitFrame() at src/engine/client/backend/vulkan/backend_vulkan.cpp:2341
0x000000014034a1a5: CCommandProcessorFragment_Vulkan::NextFrame() at src/engine/client/backend/vulkan/backend_vulkan.cpp:2501
0x000000014032d5b6: CCommandProcessorFragment_Vulkan::RunCommand(CCommandBuffer::SCommand const*) at src/engine/client/backend/vulkan/backend_vulkan.cpp:6473
0x000000014001a7e6: …
```
=> Also print external module/symbol names in `parse_drmingw.sh`

src/engine/client/client.cpp, src/engine/client/input.cpp, src/engine/client/input.h
Translate the Android back-button to the escape-key, so it can be used to navigate back in menus, open/close the ingame menu, close the editor etc.
Trap the Android back button by setting the `SDL_ANDROID_TRAP_BACK_BUTTON` hint, so it can be handled in our code reliably instead of letting the system handle it.
Interpret fast repeated presses of the back-button (3 times within 1 second) as a quit-event, so the app can be quit cleanly and quickly without using the UI. The client settings are otherwise not saved if the app is closed by minimizing it using the home button and waiting for the OS to kill it or by discarding it in the recent apps view.
=> Translate back-button to escape-key on Android, quit if Android back-button is pressed 3 times within 1 second 

src/engine/client/backend/opengl/backend_opengl.cpp, src/engine/client/backend/opengl/backend_opengl3.cpp, src/engine/client/backend/opengl/backend_opengl3.h, src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/client.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/game/client/components/maplayers.cpp, src/game/client/gameclient.cpp, src/game/editor/editor.cpp
Always use black color to clear the window with all graphics backends, instead of using `cl_background_color` or `cl_background_entities_color`, respectively, as the clear color. The respective map background color is rendered using a quad in `CMapLayers` instead, so this should not affect appearance of maps. This does not have any noticeable effect on FPS. Previously, the unused part of the window (when it is resized smaller than 5:4 aspect ratio), was colored using the map background color, whereas now it will be cleared black consistently.
The color parameters of the `IGraphics::Clear` function and of the `SCommand_Clear` command are removed, as we always expect the screen to be cleared black now.
The parameter `ForceClearNow` of the `IGraphics::Clear` function was already unused …
=> Always clear window with black color instead of background color

scripts/android/files/AndroidManifest.xml, src/engine/client/client.cpp
Always force landscape orientation to be used for the game on Android.
Hide the title bar so it is not shown when starting the game. There is also a bug with SDL currently that leads to the title bar and status bar being shown permanently after minimizing and reopening the app, which is alleviated by hiding the title bar.
=> Force landscape orientation and hide title bar on Android

src/engine/client/backend/opengl/backend_opengl.cpp, src/engine/client/backend/opengl/backend_opengl3.cpp, src/engine/client/backend/opengl/backend_opengl3.h, src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/client.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/game/client/components/maplayers.cpp, src/game/client/gameclient.cpp, src/game/editor/editor.cpp
This reverts commit caa062c88c4a103513c1728648acba344e1db93d (#8374).
As this decreased FPS and caused the background quad to be rendered twice when using a map background in entities mode.
=> Revert "Always clear window with black color instead of background color

src/engine/client/client.cpp, src/engine/client/serverbrowser.cpp, src/engine/shared/config_variables.h, src/game/client/components/hud.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/scoreboard.cpp
Time score will now always be used for any game with the flag `GAMEINFOFLAG_TIMESCORE` set in the `CNetObj_GameInfoEx` object. If the flag is not set, points score is used instead.
Backwards compatibility for old demos, that were recorded without this net object and flag, is removed. For old demos, points score is always assumed now.
Closes #6700.
=> Remove `cl_ddrace_scoreboard` and `cl_demo_assume_race` settings

.clang-tidy
Fixes clang issues being detected in interface classes such as `class IJob`
Fixes the following clangd error:
``Invalid case style for class 'IJob' (fix available)``
=> Whitelist class names starting with I

src/base/system.cpp
It seems there is a problem with ECon, where the server somehow tries to bind to wrong IPv6 address, making the bind fail. This PR allows ECon to succeed if at least one of the two sockets (IPv4 or IPv6) could be opened.
I did some preliminary debugging and found that default bind address (localhost) at some point got properly resolved to `::1`, but when trying to bind to it, the address seems wrong. I guess it somehow got mangled up before the actual bind call. This needs some further debugging to be resolved, but it should not prevent ECon from working at all, so I changed the code accordingly.
=> Allow econ to succeed, even if ipv6 econ fails to bind to socket

CMakeLists.txt, src/base/system.cpp, src/base/system.h, src/engine/server/server.cpp, src/engine/server/upnp.cpp, src/engine/shared/console.cpp, src/engine/shared/jsonwriter.cpp, src/game/client/components/debughud.cpp, src/game/client/components/hud.cpp, src/game/client/components/mapimages.cpp, src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/nameplates.cpp, src/game/client/components/scoreboard.cpp, src/game/client/components/statboard.cpp, src/game/client/components/voting.cpp, src/game/client/lineinput.cpp, src/game/client/render_map.cpp, src/game/editor/editor.cpp, src/game/editor/editor_props.cpp, src/game/editor/mapitems/layer_tiles.cpp, src/game/server/gamecontext.cpp
This would make the function `str_from_int` unnecessary, at least user-facing.
Advantage: User doesn't have to care about `str_from_int`/`str_format` distinction.
Disadvantage: We're adding some template programming to `system.h`, potentially slowing all compilation.
=> Optimize `str_format(…, …, "%d", …)` using templates

src/base/system.cpp
Remove unnecessary `fs_is_dir` check in the `fs_chdir` function. The `SetCurrentDirectoryW` and `chdir` functions would already include such necessary checks anyway.
Assert that `GetCurrentDirectoryW` was successful instead of logging an error message. This function should only potentially fail if the current working directory was changed by another thread between the two calls, which should not happen in our code.
=> Minor refactoring of `fs_chdir` and `fs_getcwd` functions

scripts/android/cmake_android.sh, scripts/android/files/build.gradle, scripts/android/files/build.sh, scripts/android/files/java/org/ddnet/client/NativeMain.java, scripts/android/files/proguard-rules.pro, scripts/compile_libs/cmake_lib_compile.sh, scripts/compile_libs/gen_libs.sh
See commit messages. Follow-up for #8334.
SDK 19 is the lowest API level support by SDL2 because it is the lowest API level supported by the latest NDK toolchain. According to https://www.composables.com/tools/distribution-chart this should cover virtually all Android devices.
=> Further clean up and improve the Android building scripts, lower minimum target API to 19

scripts/android/files/AndroidManifest.xml, src/android/android_main.cpp, src/android/android_main.h, src/engine/client/client.cpp, src/engine/shared/storage.cpp
Split the user storage location and the data folder in the app specific external storage in the folders `data` and `user` instead of writing the user setting directly to the external storage.
Remove unnecessary storage permissions. The client only accesses files in its own external storage location, hence these permissions are not necessary for Android API 19 and higher, which is always given as we only target API 19 and higher.
Only unpack changed assets when their hash in the integrity index is different instead of unpacking all assets again, so the app starts faster after updates. Avoid unpacking the entire integrity index file unless it changed, by initially reading only the first hash directly from the asset, so the app starts faster when the data is up-to-date.
Add error handling …
=> Improve Android storage usage, faster launch, remove permissions

src/base/system.h, src/tools/stun.cpp, src/tools/twping.cpp
=> Ensure return value of `secure_random_init` is always checked

src/game/client/components/menus.cpp
Since the key reader will intercept the next input, the other UI elements should not react to the hovered mouse.
=> Prevent UI elements from being hovered while key reader is active

src/engine/server/databases/connection_pool.cpp, src/game/client/components/hud.cpp, src/game/client/components/nameplates.cpp, src/game/editor/mapitems/layer_tiles.cpp, src/game/server/gamecontext.cpp
=> Consistently use `str_copy` instead of `mem_copy` for strings

src/game/client/components/camera.cpp, src/game/client/components/camera.h, src/game/collision.cpp, src/game/collision.h
I noticed that on the current master the `goto_tele` feature was skipping one tele.
https://github.com/ddnet/ddnet/assets/20344300/afface81-7199-4419-be2a-9e80d8ada79b
I did not want to debug the code because it looked so complex. So I refactored it and it also fixed the bug. As you can see it now finds one more tele in the same map:
https://github.com/ddnet/ddnet/assets/20344300/49dc9ed3-d1f6-43db-a80a-9ca71d86b6b2
Also the performance should be much better. Since now the worst case is only iterating as many times as there are teleporters of that type in the map. Before in the worst case it would iterate over every single tile in the tele layer (including empty tiles).
=> Fix `goto_tele` not finding all teleporters

datasrc/network.py, src/game/client/components/effects.cpp, src/game/client/components/effects.h, src/game/client/gameclient.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/teams.cpp
Some fun confetti particles whenever a tee finishes.
Not entirely sure on best practice for creating new particle effects / net events so please let me know.
Also I'm not the best at visuals so perhaps someone can find a better 'confetti-like' particle generator.
https://github.com/ddnet/ddnet/assets/69405348/cb5accc3-1cd0-4925-9435-1ef26eef3679
=> Add confetti particles on finish

src/game/client/gameclient.cpp, src/game/localization.cpp
Ignore language file config variable being set initially in the conchain (i.e. when `GlobalTime` still returns zero) and check whether the value changed before reloading the language.
Fix crash when reading a translation file that ends unexpectedly after a context line.
Make error messages about malformed translation files more detailed.
Fix incorrect line numbers in the error message because context lines were not counted.
Use `log_error` for error messages.
=> Fix language file being loaded twice when starting, improve error handling for invalid translation files 

src/game/server/entities/character.cpp, src/game/server/entities/character.h
**This does not fix any issues in ddnet as far as I know. Because ddnet code removed all round based code.**
Currently the per tee demos are only stopped when a character dies. But the Reset() method in the gameworld destroys characters without killing them.
This allows to do world resets without calling gamecontext shutdown while sv_player_demo_record is active. Which is nice for round based game modes.
```C++
void CGameWorld::Reset()
{
// reset all entities
for(auto *pEnt : m_apFirstEntityTypes)
for(; pEnt;)
{
m_pNextTraverseEntity = pEnt->m_pNextTypeEntity;
pEnt->Reset();
pEnt = m_pNextTraverseEntity;
}
RemoveEntities();
GameServer()->m_pController->OnReset();
RemoveEntities();
m_ResetRequested = false;
GameServer()->CreateAllEntities(false);
}
```
=> Stop demo when gameworld is reset

src/game/client/components/menus_settings.cpp
See #8436 for details
Now the "Tee" tab name in settings is localisable:
(translation is not included in the PR!)
=> Make "Tee" tab name localisable

src/engine/client/input.cpp, src/engine/client/input.h, src/engine/input.h, src/game/client/component.cpp, src/game/client/component.h, src/game/client/components/voting.cpp, src/game/client/components/voting.h, src/game/client/gameclient.cpp, src/game/editor/editor.cpp, src/game/editor/editor.h
Add `IInput::ConsumeEvents` function accepting a consumer `std::function` to replace the duplicate usage of the `IInput::NumEvents`, `IInput::GetEvent` and `IInput::IsEventValid` functions.
Use an `std::vector` to store the current input events to support any number of input events per client update instead of at most 32.
Use full `uint32_t` range for input counter instead of only using the range 0..0xFFFF. If the range is artificially reduced, then this can result in inputs being handled multiple times with high refresh rates, so the increased range should add future proofing for extremely fast devices.
Split `CInput::AddEvent` function into `CInput::AddKeyEvent` and `CInput::AddTextEvent` functions for readability and to make it easier to add additional input events (i.e. touch events). …
=> Refactor client input event handling

src/game/client/components/menus_demo.cpp
The `.demo` extension is supposed to be removed from the target filename when slicing demos, but anything after the last dot was being removed instead, e.g. `test.abc.def` was incorrectly replaced with `test.abc`.
=> Fix wrong file extension being removed in demo cut popup

src/game/client/gameclient.cpp
=> Fix Ok-button of warning popup not being localized

src/game/client/ui.cpp, src/game/client/ui.h, src/game/client/ui_rect.cpp, src/game/client/ui_rect.h, src/game/editor/editor.cpp, src/game/editor/editor.h
Remove separate handling of UI mouse position and delta in the editor and use the UI directly for this like in the gameclient. Raw cursor movements are redirected to the UI with the `CUi::OnCursorMove` function. The editor separately updates its world positions and delta after the mouse position was changed. The mouse world position for the editor is passed to the UI with the `CUi::Update` funtion as before, whereas the world position is unused in the gameclient.
Use `vec2`s for mouse positions and deltas instead of two separate floats.
=> Unify editor UI mouse handling with `CUi`

src/game/client/gameclient.cpp, src/game/client/gameclient.h
Assume every server that does not have ddnet or race in its gametype to be a pvp server. This allows spectators to follow multiple players during a fng/ctf/gctf/ictf round.
Related issue #7509
https://github.com/ddnet/ddnet/assets/20344300/5032b46d-87cc-493e-9b5d-2ba981090f14
=> Keep respawned players in multi view list on pvp servers

src/game/localization.cpp
The trailing `]` was not being removed from the context anymore due to an off-by-one error introduced in #8430. Closes #8464.
=> Fix wrong context value being used for translation lookup

src/game/client/ui.cpp, src/game/client/ui.h, src/game/editor/editor.cpp, src/game/editor/editor_props.cpp, src/game/editor/mapitems/layer_quads.cpp, src/game/editor/mapitems/layer_sounds.cpp, src/game/editor/mapitems/layer_tiles.cpp, src/game/editor/popups.cpp
Make value selector behavior consistent with the generic button logic. Consistently check for completed mouse clicks on the value selector UI element instead of handling some mouse down and mouse up events separately. Fix text mode being activated when moving the mouse over value selectors with held down mouse button. Fix text mode being deactivated immediately when the mouse leaves text area while holding down the mouse button, which is inconvenient when selecting text. Remove unnecessary usage of `CUi::MouseButtonReleased` function.
Support double-clicking value selectors to enter text edit mode in addition to right-clicking. This feels more intuitive to use and also makes it usable without a second mouse button.
Select all text when entering text mode also in the editor, which was …
=> Consistent value selector behavior, support double-clicking

src/game/client/components/console.cpp
The percentage of received console commands was not being shown with the progress spinner because the variable `ProgressProps` was not passed to the `RenderProgressSpinner` function.
=> Fix percentage not being used for console command progress spinner

src/game/client/components/menus_demo.cpp
=> Fix demo seekbar tooltip not showing correct hovered time

CMakeLists.txt, src/game/gamecore.cpp
We assume that `char` is `signed` in various places in the code. In particular, the `Str.StrToInts` test will fail when `char` is not `signed` and names containing special characters will be displayed incorrectly on servers.
Therefore, the compiler flag `-fsigned-char` is set unconditionally instead of only for ARM and ARM64, as we expect `char` to be `signed` on all architectures.
A static assertion is added to ensure at compile time that `char` is `signed` independently from the flag added in `CMakeLists.txt`.
This is necessary at least for ARM, ARM64, PPC, PPC64, and PPC64LE. According to some sources, `char` may also be `unsigned` by default when compiling for Android, although this could not be confirmed with the current Android NDK using Clang.
For the PowerPC architectures, …
=> Force default `char` to be `signed` on all architectures

src/game/client/ui.cpp, src/game/client/ui.h
Fix button logic being stuck when holding mouse button on UI elements with button logic in the menus/editor, switching between menus and editor with Ctrl+Shift+E, then using a UI element with button logic in the editor/menus and switching back.
Fix value selector text mode of color picker popups being deactivated when switching between menus and editor while the color picker popup is open in both.
Only update progress spinners once per frame in `CUi::Update` to ensure consistent rotation speed. Progress spinners in menus and editor now rotate independently.
In general, all `static` non-`const` variables in `CUi` are replaced with member variables, as the `static` variables are shared between the two `CUi` instances of the menus and the editor, causing the above issues.
=> Fix UI issues when switching between menus and editor

src/game/client/components/menus_ingame.cpp
The ddnet buttons kill and pause do not fit in anymore if there is also a join red/blue button.
This commit fixes that by overflowing the buttons into a second row if there is not enough space anymore.
It makes use of the previously unused variable ButtonBar2.
Related prior work https://github.com/ddnet/ddnet/pull/2720
https://github.com/ddnet/ddnet/assets/20344300/775ac460-d70e-4945-a2d6-a713b66df928
https://github.com/ddnet/ddnet/assets/20344300/03fc0075-31d5-4938-8dc2-36f1cc6c41a1
=> Fix in game menu buttons overlapping on team based gametypes

src/game/server/entities/character.cpp
The `CGameControllerDDRace::HandleCharacterTiles` function can kill the tee if the conditions for starting the race are not satisfied when touching a start tile. In this case, no further tiles should be handled in the `CCharacter::HandleTiles` function, else the effects of those tiles being handled may incorrectly be applied after the tee has respawned.
=> Fix tiles being handled in same tick for dead tees in some cases

src/game/editor/popups.cpp
Hello & Greetings, 
Upon opening the editor I have found an issue with the wording and ran this buy multiple of my friend. although the functionality of this button works as intended. 
I found that  the previous button labeled: "readd" was heavily confusing, with me first thinking it read, "Read", then a friend suggesting perhaps it meant "Re-add" so a word like Reload is clear and easy to understand and defines what the function of the button does.
=> Readd is not a word, Reload makes more sense and is easier readablility.

src/engine/client/input.cpp, src/engine/client/input.h, src/engine/input.h, src/game/client/components/menus_browser.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/client/ui_listbox.cpp, src/game/client/ui_listbox.h, src/game/editor/editor.cpp
Instead of relying on SDL to determine when a click is a double-click, implement double-click handling specifically for the UI, as double-clicks are only supposed to be used there. This allows us to ensure that double-clicks only activate UI elements if both clicks were performed on the same UI element. Previously, only the position of the second click was considered, so UI element would incorrectly activate when double-clicking close to them as long as the second click starts and ends on them.
Implementing double-clicking handling separately is also necessary to support double-clicking in the UI with touch events, as SDL does not provide the double-click information for touch events.
The newly added `CUi::DoDoubleClickLogic` function should be called after a UI element has been clicked. …
=> Move double-click handling from engine input to UI, improve envelope editor double-click handling 

src/game/client/components/console.cpp, src/game/client/components/console.h
Avoid the `int Type` parameter by making `CGameConsole::Dump` a member function of `CGameConsole::CInstance`.
Use `log_*` functions instead of `IConsole` for logging.
=> Move `CGameConsole::Dump` function to `CGameConsole::CInstance`

src/game/client/components/hud.cpp
=> Remove `Spectate` label from HUD, show `Following {player}` instead

src/game/editor/editor_server_settings.cpp
Fixes #8485. I don't know if it's the way it has to be done but it works xd. Also I added an else statement which clears the text input it the last command was deleted.
=> Correct arguments highlighting after removing entry

data/languages/belarusian.txt, data/languages/polish.txt
This pr fixes translation files. These 2 files had missing `[Graphics error]` context and because of this python script was destroying the translations. For example https://github.com/ddnet/ddnet/commit/2498d392dbf1ef496e647f8bdbbb406e22f7fe62#diff-3edb39080aa69131efe333703ea6a07b9a8556c8e82674d24c276ee7e0599ffe Also I added a few translation which were removed by script.
=> Add context to translations & add removed translations

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_start.cpp
When changing `ui_page` via the console while the start menu is active, the browser tab was not refreshed when clicking the Play-button, leading to the old server list being shown for the new browser tab.
After starting/stopping the local server from the main menu, refresh the LAN tab on its next activation, so it immediately shows/hides the started/stopped server without needing a manual refresh.
This is not a perfect solution, as the server would not show up when activating the LAN tab immediately after starting the server, because the server needs some time before it will respond to server info requests, but this works well enough unless the hotkeys are used.
=> Fix browser not refreshing if `ui_page` is changed in start menu, refresh LAN tab after starting/stopping local server

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_start.cpp, src/game/client/gameclient.cpp, src/game/client/ui.cpp, src/game/client/ui.h
Screenshots:
- Loading screen:
- Before: ![image](https://github.com/ddnet/ddnet/assets/23437060/aac62bc1-a83d-4bf2-b596-db07cd4647e9)
- After: ![image](https://github.com/ddnet/ddnet/assets/23437060/68b5e493-8bd4-4d1a-aece-45a43d1acacb)
- Updating:
- Before:
- After:
=> Refactor client loading and loading screen, fix progress bar alignment when updating

CMakeLists.txt, src/test/snapshot.cpp
If there are too many snap items with too high values the crc will overflow. If that overflow differs from client to server the client will drop the snapshot and it will cause lags. This test case should help staying compatible with other implementations such as the one from teeworlds which does not use an unsigned int but a regular int. And it also helps spot this rare issue faster on machines where `unsigned int` has a different size than 4 byte.
=> Add tests for snapshot crc overflow

src/game/client/gameclient.cpp
=> Extract `GenerateTimeoutCode` function to reduce duplicate code, avoid magic numbers for generating timeout code

src/engine/server/server.cpp, src/engine/shared/config_variables.h, src/engine/shared/netban.cpp, src/engine/shared/netban.h, src/engine/shared/network_conn.cpp
Add `sv_dnsbl_ban_reason` config variable with size 128 to specify the ban reason for `sv_dnsbl_ban`.
Increase the maximum size for ban reasons on the server from 64 to 128 to support this new config variable. Adjust buffer sizes for formatting ban messages accordingly.
Additionally, increase the size of the buffer for unpacking the connection closed message from 128 to 256. Due to this limitation, old clients will see truncated disconnect messages if the entire message is longer than 127, which can now happen with long ban reasons as the ban message additionally contains the duration (e.g. `You have been banned for 10 minutes (Reason)`).
Closes #8518.
=> Add `sv_dnsbl_ban_reason`, increase maximum ban reason length

src/android/android_main.cpp, src/base/system.cpp, src/base/system.h, src/engine/client/backend/opengl/opengl_sl.cpp, src/engine/client/serverbrowser_http.cpp, src/engine/server/server.cpp, src/engine/shared/console.cpp, src/engine/shared/linereader.cpp, src/engine/shared/linereader.h, src/engine/shared/storage.cpp, src/game/client/components/countryflags.cpp, src/game/editor/auto_map.cpp, src/game/localization.cpp, src/game/server/gamecontext.cpp, src/game/server/score.cpp, src/test/io.cpp, src/test/linereader.cpp, src/tools/config_store.cpp
Read the entire file into memory immediately when the line reader is initialized instead of using a fixed size buffer of size 32769, which leads to broken line reading for larger files (closes #8431).
Replace the `CLineReader::Init` function with the `CLineReader::OpenFile` function, which additionally checks whether the file contains any null bytes (indicates that the file is likely not a text file).
As the file will be read into memory entirely in the `OpenFile` function, is can also be closed immediately, since using the `io_read_all_str` function should ensure that nothing more can be read from the file. This also simplifies the usage of the `CLineReader` class, as manually closing the file is inconvenient and error-prone. In fact, the file handle for the `ddnet-serverlist-urls.cfg` …
=> Rewrite and fix line reader, read entire file into memory

src/game/editor/editor.cpp
Add a question mark-button next to the x-button to open the Wiki page https://wiki.ddnet.org/wiki/Mapping in the default web browser. The link is localized so translators can replace it with the respective translated Wiki pages. The hotkey F1 is also added to activate this button.
=> Add button and F1 hotkey in editor to open Wiki page for editor

src/game/client/components/scoreboard.cpp, src/game/client/components/scoreboard.h
Scoreboard title
- In teamplay, color the title background red/blue for the respective teams (like in 0.7).
- In teamplay, swap the score location for the blue team, so the scores line up in the center (like in 0.7).
- Use textrender ellipsis instead of cutting the title string manually and potentially creating broken UTF-8.
Game over title
- Render the game over message in the color of the winning team (or yellow in case of draws).
- Adjust size and spacing of the message to prevent overlap.
Player list
- Add player list size variant for 17-24 players with two columns of up to 12 players. This previously used the variant for 32 players.
Goals
- Use textrender for alignment and properly center the time limit goal.
- Change localization text from `Round` to `Round %d/%d` so the numbers and …
=> Various improvements to scoreboard rendering, refactoring

src/mastersrv/Cargo.lock, src/mastersrv/Cargo.toml, src/mastersrv/src/locations.rs, src/mastersrv/src/main.rs
This also makes GeoIP data more precise than our current state, from `eu` to `eu:de` for Germany, i.e. adding country codes for all countries and not only for China.
https://git.ipfire.org/?p=location/libloc.git
Current location data can be obtained from https://location.ipfire.org/databases/1/location.db.xz.
=> mastersrv: Use `libloc` instead of our own CSV format for GeoIP

Cargo.toml
Fixes the following warning
> warning: some crates are on edition 2021 which defaults to resolver = "2", but virtual workspaces default to resolver = "1"
note: to keep the current resolver, specify workspace.resolver = "1" in the workspace root’s manifest
note: to use the edition 2021 resolver, specify workspace.resolver = "2" in the workspace root’s manifest
=> fix resolver version warning for workspaces in rust

src/engine/shared/map.cpp
Cherry-picked from https://github.com/teeworlds/teeworlds/pull/2076/commits/d25869626a8cfbdd320929ba93ce73abed1402ce
Thanks to Charly Reux for notifying us.
=> Fix integer overflow when computing tilemap size

src/base/system.cpp, src/base/system.h, src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/game/client/components/menus.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings_assets.cpp, src/game/client/components/menus_start.cpp, src/game/editor/editor.cpp
Opening links and files with the `open_link` and `open_file` functions does not work on Android, as the `open_link` function uses `fork` which is not supported on Android. This also seems to cause a strange bug where client networking partially breaks. Currently, after trying to open any link, connecting to servers is not possible anymore but the server browser still works, with the connection getting stuck randomly in the connecting/loading state.
SDL implements URL opening, including of file URIs, with the `SDL_OpenURL` function for most systems including Android. However, using `SDL_OpenURL` for all systems has several downsides:
1. The `SDL_OpenURL` function is only available since SDL 2.0.14, in particular not for the Ubuntu 20 CI runner. Hence, we would either have to conditionally …
=> Use `SDL_OpenURL` to open links and files on Android
