ddnet/ddnet

data/languages/serbian.txt
=> Update Serbian translation (by Jurai!)

data/languages/ukrainian.txt
=> Update Ukrainian translation (by Jurai!)

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_demo.cpp
https://github.com/ddnet/ddnet/assets/141338449/9be8b1bc-168f-458e-a9d7-488844fef917
=> Add a searchbar for demos.

src/game/editor/editor.cpp, src/game/editor/map_grid.cpp, src/game/editor/map_view.cpp, src/game/editor/map_view.h, src/game/editor/proof_mode.cpp
These were suggested in #7017.
=> improve code style in proofmode, mapgrid and mapview

src/engine/server.h, src/engine/server/server.cpp, src/engine/server/server.h, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/teehistorian.cpp, src/game/server/teehistorian.h, src/test/teehistorian.cpp
This allows to trace a complete server execution.
=> Record previous game ID in teehistorian

src/engine/client/backend/opengl/backend_opengl.cpp, src/engine/client/backend/opengl/backend_opengl.h, src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/client.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/shared/config_variables.h, src/game/client/components/mapimages.cpp, src/game/client/components/menus_settings_assets.cpp, src/game/variables.h
=> Remove `gfx_finish` config variable, remove `dbg_hitch` config variable, improve config variable descriptions, add missing descriptions

data/languages/swedish.txt
=> Update Swedish translations

src/game/client/components/menus_browser.cpp
=> Disable server browser hotkeys when popup menu is open

src/game/client/components/chat.cpp
=> Fix chat history disappearing with `cl_showchat 1`

CMakeLists.txt, src/engine/graphics.h, src/game/editor/auto_map.cpp, src/game/editor/auto_map.h, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/mapitems/image.cpp, src/game/editor/mapitems/image.h, src/game/editor/mapitems/layer_quads.cpp, src/game/editor/mapitems/layer_tiles.cpp, src/game/editor/mapitems/map.cpp, src/game/editor/mapitems/map_io.cpp, src/game/editor/mapitems/sound.cpp, src/game/editor/mapitems/sound.h, src/game/editor/popups.cpp, src/game/editor/tileart.cpp
Creating a separate PR for every change will be a bit tedious, so I split the changes by commits instead. I hope this is fine. Also I'm not sure how many commits can reasonably be included in a PR.
=> Refactor editor mapitems

src/engine/gfx/image_loader.cpp
=> Minor refactoring of the image loader

src/game/client/components/camera.cpp, src/game/client/gameclient.cpp
see comment https://github.com/ddnet/ddnet/issues/7113#issuecomment-1703857445
=> Remove setting default zoom after leaving multiview, fixes #7113

src/mastersrv/src/main.rs
Instead of going through `String`.
=> mastersrv: Go to `RawValue` directly

datasrc/network.py, src/game/client/components/hud.cpp, src/game/client/components/voting.cpp, src/game/server/gamecontext.cpp
Color the "Vote yes" or "Vote no" text depending on which you have voted on.
=> Color vote if you have voted f3 or f4.

src/game/client/components/menus_demo.cpp
=> Don't include .demo in demo slice input

src/engine/client/client.cpp, src/engine/client/client.h, src/engine/shared/config_variables.h
=> Increase password size limit from 32 to 128

data/languages/swedish.txt
=> Update Swedish translations for 17.3

.github/workflows/style.yml
Since the style workflow also uses cargo, we should also set the property `CARGO_HTTP_MULTIPLEXING: false` to hopefully fix the spurious network errors.
See #7173.
=> Also apply Cargo CI workaround to style workflow

src/game/client/components/menus_settings.cpp
=> Chat preview respect cl_show_chat_friends

data/languages/turkish.txt
=> Update Turkish translations for 17.3

src/engine/client/client.cpp, src/engine/client/sound.cpp, src/engine/client/sound.h, src/engine/shared/video.h, src/engine/sound.h
=> Replace most global variables in engine sound with member variables, various other refactoring of engine sound

src/game/server/gamecontext.cpp
It will now inform the user about `sv_chat_initial_delay` when joining or trying to send a message. Closes #5067
=> Use a different message when muted by sv_chat_initial_delay

src/game/server/ddracechat.cpp
=> Add ability to swap without a name when team only has 2 players.

src/game/client/components/mapsounds.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_settings.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h
To `Foreground` and `Background` respectively.
=> Rename variables containing `ForeGround` and `BackGround`

src/game/client/component.cpp, src/game/client/component.h, src/game/client/components/binds.cpp, src/game/client/components/menus.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h
=> Add `IConfigManager` getter to `CGameClient` and `CComponent`

src/game/client/components/hud.cpp
=> Don't show cl_showpred in demos

src/engine/client/client.cpp, src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser.h, src/engine/serverbrowser.h, src/engine/shared/serverinfo.cpp, src/engine/shared/serverinfo.h, src/game/client/components/menus_browser.cpp
=> Various refactoring of the engine server browser, remove game includes from engine, minor performance improvement

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
=> revert quad selection correctly fixes #7248

src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser.h, src/engine/serverbrowser.h, src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp
=> Improve performance of menus checker background, improve server browser performance

src/engine/client.h, src/engine/client/client.h, src/game/client/components/menus.cpp
=> Encapsulate/move `IClient` member variables

src/engine/map.h, src/engine/shared/datafile.cpp, src/engine/shared/datafile.h, src/engine/shared/map.cpp, src/engine/shared/map.h, src/game/client/components/mapimages.cpp, src/game/client/components/mapsounds.cpp, src/game/editor/mapitems/map_io.cpp, src/test/datafile.cpp, src/tools/map_convert_07.cpp, src/tools/map_extract.cpp, src/tools/map_replace_image.cpp
=> Add functions for reading/writing strings from/to datafile, minor refactoring of datafile/map reader

src/engine/gfx/image_loader.cpp
The wrong color channel count was being used for loading images that use an indexed color palette, which was causing the loading to fail with the error "bytes in row incorrect". Now the correct color channel count is retrieved using the libpng API.
Closes #7157.
=> Fix images using indexed color palette not being loadable

src/game/editor/component.cpp, src/game/editor/component.h
=> store only pointer to editor in CEditorComponent

CMakeLists.txt, src/game/client/render.h, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/mapitems/envelope.cpp, src/game/editor/mapitems/envelope.h
=> Refactor `CEnvelope` class

src/engine/client/sound.cpp, src/engine/client/sound.h, src/engine/sound.h, src/game/editor/editor.cpp, src/game/editor/editor.h
Adds a seekbar that makes it easier to preview longer audio files.
Not really sure how to make it look.
=> Enhance editor toolbar sounds

CMakeLists.txt, datasrc/compile.py, datasrc/content.py, datasrc/seven/compile.py, datasrc/seven/content.py, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/game/client/render.cpp, src/game/client/render.h
=> Extract client 'six' data types and use them for 'seven' data

src/engine/demo.h, src/engine/shared/demo.cpp, src/engine/shared/demo.h
=> Refactor engine demo editor, minor refactoring of demo recorder/player

CMakeLists.txt, src/base/system.h, src/test/swap_endian.cpp
=> Add tests and documentation for `swap_endian` function

src/base/system.cpp, src/engine/client/client.cpp, src/engine/server/main.cpp, src/engine/shared/jobs.cpp, src/engine/shared/jobs.h
=> Minor refactoring of engine jobpool

src/engine/client/client.cpp, src/engine/demo.h, src/engine/server/server.cpp, src/engine/shared/demo.cpp, src/engine/shared/demo.h
=> Refactor engine demo player and recorder

CMakeLists.txt, src/engine/client/client.h, src/engine/engine.h, src/engine/server/server.cpp, src/engine/shared/engine.cpp, src/engine/shared/host_lookup.cpp, src/engine/shared/host_lookup.h, src/game/client/components/console.cpp, src/test/jobs.cpp
=> Move `CHostLookup` to separate compilation unit and encapsulate member variables

src/engine/client/client.cpp, src/engine/client/client.h, src/engine/shared/config_variables.h
=> Bump maximum server password length from 128 to 256, refactoring

src/engine/shared/datafile.cpp, src/engine/shared/datafile.h, src/game/server/gamecontext.cpp, src/tools/config_store.cpp
=> Add more assertions to datafile writer, refactoring

src/game/ddracecommands.h, src/game/server/ddracecommands.cpp, src/game/server/gamecontext.h
=> Add `freeze`/`unfreeze` testing commands

src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/game/client/components/mapimages.cpp, src/game/client/components/menu_background.cpp, src/game/client/components/menu_background.h, src/game/client/components/menus.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings_assets.cpp
=> Fix flashing black screen when loading menu themes, fix some textures being loaded without mipmaps, refactoring

README.md
=> Changes python -> python3 for Debian dependency

src/game/client/components/menus_demo.cpp, src/game/editor/editor.cpp
=> Hide `"Show directory"` when `"All combined"` selected

data/languages/swedish.txt
=> Update Swedish translations for 17.4

src/game/server/ddracechat.cpp
=> Add new contributors to credits

data/languages/ukrainian.txt
=> Update ukrainian.txt 17.4

data/languages/belarusian.txt
=> Update Belarusian translation for 17.4

src/game/server/ddracecommands.cpp, src/game/server/entities/laser.cpp, src/game/server/entities/projectile.cpp, src/game/server/gamecontroller.cpp, src/game/server/gamecontroller.h, src/game/server/gamemodes/DDRace.cpp, src/game/server/gamemodes/DDRace.h
=> Move m_TeleOuts from ddr controller to game controller

src/game/server/gamecontext.cpp
- Removed duplicate rate-limit mechanism.
- Don't set `m_Last_KickVote` if there was an error while calling vote.
- Fix bug where seconds in `There's a %d second wait time` would be wrong.
=> Fix some issues with `sv_vote_kick_delay`.

src/engine/client/serverbrowser.cpp
=> Fix inverted community parsing conditions

src/game/editor/editor.cpp
To fix issue  #7399 that appending maps in editor may duplicate images
=> Appending in editor checks for duplicate images

CMakeLists.txt, src/game/server/gamecontext.cpp, src/game/server/gamemodes/mod.cpp, src/game/server/gamemodes/mod.h, src/game/variables.h
Closes: https://github.com/ddnet/ddnet/issues/7127
Depends on: https://github.com/ddnet/ddnet/pull/7471 https://github.com/ddnet/ddnet/pull/7464
=> Add sv_gametype and sample mod

src/game/server/player.cpp, src/game/server/player.h
Allows to write this
```C++
for(const CPlayer *pPlayer : GameServer()->m_apPlayers)
{
if(!pPlayer)
continue;
if(!pPlayer->GetCharacter())
continue;
// your code that does not change the character state
}
```
=> Overload GetCharacter with const version

.github/workflows/build.yml
> [2023-01-12T17:25:29.471Z] ['error'] There was an error running the uploader: No gcov files found
Broken in https://github.com/ddnet/ddnet/pull/5599 because the cmake-init-env overwrites outside env variables
=> Try to fix code coverage upload (fixes #6277)

codecov.yml
=> coverage: Don't complain on PRs (fixes #7497)

src/antibot/antibot_data.h, src/engine/server/antibot.cpp, src/engine/server/antibot.h
=> Allow antibot to kick people

codecov.yml
=> codecov: Also disable annotations (fixes #7498)

src/engine/client/updater.cpp, src/game/server/ddracechat.cpp, src/game/server/ddracecommands.cpp, src/game/server/gamecontext.cpp
=> replace `sizeof x` with `sizeof(x)`

codecov.yml
=> Also set Codecov target for patch to 0%

.gitignore
=> Add `demo_extract_chat` to .gitignore.

src/engine/shared/packer.cpp
=> Minor improvements to `CPacker` and `CUnpacker`

.github/workflows/build.yml
Seen in https://github.com/ddnet/ddnet/actions/runs/6969106161/job/18964960431
```
Error: No such keg: /usr/local/Cellar/python@3.10
```
=> Fix macOS CI

src/game/client/components/console.cpp
Cherry-pick of https://github.com/teeworlds/teeworlds/pull/3185
- yes, see the original PR
=> Show previous commands in the console's scrollback buffer

src/engine/console.h, src/engine/shared/console.h, src/game/server/score.cpp
=> Minor refactoring of `IConsole`

src/engine/client/serverbrowser.cpp, src/engine/shared/console.h, src/engine/shared/memheap.cpp, src/engine/shared/memheap.h, src/game/client/components/voting.cpp
=> Refactor `CHeap`

src/game/client/components/menus_ingame.cpp
=> Fix alignment of buttons in vote menu.

src/engine/antibot.h, src/engine/client.h, src/engine/config.h, src/engine/console.h, src/engine/demo.h, src/engine/discord.h, src/engine/editor.h, src/engine/engine.h, src/engine/favorites.h, src/engine/friends.h, src/engine/ghost.h, src/engine/graphics.h, src/engine/input.h, src/engine/kernel.h, src/engine/map.h, src/engine/server.h, src/engine/serverbrowser.h, src/engine/sound.h, src/engine/steam.h, src/engine/storage.h, src/engine/textrender.h, src/engine/updater.h, src/game/client/components/background.h, src/game/client/components/menu_background.h
=> Remove unused `ver` parameter of `MACRO_INTERFACE`

src/engine/client/client.cpp, src/engine/server/server.cpp, src/engine/shared/snapshot.cpp, src/engine/shared/snapshot.h
=> Various minor refactoring of snapshot-related code

src/engine/shared/snapshot.cpp
Previously, only one buffer was allocated to store each snapshot holder structure, the snapshot data and alternative snapshot data. This prevents tools like ASAN from detecting some invalid accesses, e.g. to the snapshot holder structure by underflowing the snapshot data pointer. Now three separate allocations are used instead. This hopefully helps debugging #2677.
=> Separate snapshot storage holder and snap data allocations

src/game/editor/editor.cpp
=> Fix envelope scaling being triggered in name input.

datasrc/compile.py, datasrc/network.py, datasrc/seven/compile.py, datasrc/seven/network.py, src/engine/server.h, src/engine/server/authmanager.cpp, src/game/gamecore.cpp, src/game/server/teehistorian.cpp
=> Remove `#include <system.h>` from one more header

src/engine/shared/engine.cpp
=> Ensure network log files are closed when shutting down engine

src/engine/client/backend/backend_base.h, src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h
closes #5874
CMD is already Cmd(?)
=> changed GFX → Gfx

src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/gamecontroller.cpp
Feels more organized to not do this wall of switcher code in the CGameController snap
=> Move switcher snapping code to own method

src/engine/client/text.cpp, src/engine/textrender.h, src/game/client/components/console.cpp, src/game/client/components/console.h, src/game/client/ui.cpp
Closes #5815. Highlights all occurrences in red.
https://github.com/ddnet/ddnet/assets/13364635/359932d5-f3e8-4578-bc2b-1542556ed441
------
Old demo:
https://github.com/ddnet/ddnet/assets/13364635/cf681e87-6afb-462c-9b2a-e4eec2afac4b
=> Added search in console (ctrl+f)

src/engine/shared/http.cpp
=> Disable CURL_LOCK_DATA_CONNECT (fixes #7636)

src/engine/client/discord.cpp
```
/home/deen/isos/ddnet/ddnet-source/src/engine/client/discord.cpp: In member function ‘bool CDiscord::Init(FDiscordCreate)’: /home/deen/isos/ddnet/ddnet-source/src/engine/client/discord.cpp:39:17: error: ‘mem_zero’ was not declared in this scope
39 |                 mem_zero(&m_ActivityEvents, sizeof(m_ActivityEvents));
|                 ^~~~~~~~
```
=> Fix discord build

src/game/server/gamecontext.cpp
=> Returning `false` commits you to setting a message

src/game/client/components/players.cpp
https://github.com/ddnet/ddnet/assets/141338449/48742571-42b6-455f-9b74-5408f49984f3
=> Render the tee being spectated after everyone else.

src/game/client/components/menus_settings.cpp
=> Add ui setting cl_same_clan_color

src/game/ddracechat.h, src/game/server/ddracechat.cpp, src/game/server/gamecontext.h
This adds `/join r[player]` which can be used to join a specified player's team.
Closes #3878
=> Add `/join [player]`

src/tools/demo_extract_chat.cpp
Replace unnecessary `gameclient.h` include with more specific includes.
Fix storage creation error message not being logged as the logger was initialized after checking for the failed storage creation. However, in this case we want to avoid non-error log messages so the tool's output is only the extracted demo chat, except in error cases.
Rename `Process` function to `ExtractDemoChat` and make it `static` to avoid exporting it.
Use `log_error` instead of `dbg_msg`.
=> Minor refactoring of `demo_extract_chat` tool

src/tools/map_resave.cpp
Add log messages for errors and success.
Extract function `ResaveMap`.
Ensure reader is closed when writer could not be opened.
=> Refactor `map_resave` tool

src/game/client/components/menus_settings.cpp
=> add ui setting for cl_show_local_time_always

src/engine/shared/config_variables.h
=> Improve vote config variable descriptions and value range

src/game/server/gamecontext.cpp, src/game/server/gamecontroller.h, src/game/server/player.cpp
=> report the ddrace team to master instead of the normal team

src/game/server/gamecontext.cpp
See https://github.com/ddnet/ddnet/pull/7687#discussion_r1435186538.
Also fix some help texts starting with a lowercase character.
=> Fix wrong value type for some map settings in `gamecontext.cpp`

src/game/client/components/menus_settings.cpp, src/game/client/skin.h
=> Check for valid favorite skin name, minor refactoring

src/game/client/components/mapsounds.cpp, src/game/client/components/mapsounds.h, src/game/editor/popups.cpp
=> Revert removal of "Detail" from sound layers.

src/game/client/components/console.cpp
Fixes #7700. Was also the case for local console.
=> Fix infinite console scroll

src/game/editor/editor.cpp
=> Support `Ctrl + Shift + Z` as editor redo hotkey.

src/game/editor/mapitems/layer_front.cpp, src/game/editor/mapitems/layer_game.cpp, src/game/editor/mapitems/layer_speedup.cpp, src/game/editor/mapitems/layer_switch.cpp, src/game/editor/mapitems/layer_tele.cpp, src/game/editor/mapitems/layer_tiles.cpp, src/game/editor/mapitems/layer_tiles.h, src/game/editor/mapitems/layer_tune.cpp
=> Show unused tiles warning popup for all entities layer

src/game/client/components/menus_settings.cpp
Add tabs to player and tee settings pages to switch between player (main) and dummy settings instead of using a checkbox for this, to improve the usability.
Improve layout of tee settings page, especially with 5:4 resolutions, where the eye selector previously overlapped with other UI elements. Decrease size of eye selector and make better use of empty space overall. Use more space for skin selector instead of showing empty space when "Use custom colors" is disabled.
Show favorite skin buttons also when hovering list items to make it easier to discover the feature. Add small highlight color to favorite skin buttons when hovering them.
Screenshots:
- Player settings:
- Before: 
- After: 
- Tee settings:
- With custom color:
- Before: 
- After: 
- Without custom colors:
- Before:
- After:
- …
=> Improve player and tee settings menus

.github/workflows/build.yml
=> Set MSRV to Rust 1.63.0

datasrc/compile.py, datasrc/datatypes.py, datasrc/seven/compile.py, datasrc/seven/datatypes.py
=> Refactor code around inherited net objects, add it to 0.7 code

src/engine/client/text.cpp
=> Improve text outlines

src/game/server/player.cpp
This fixes #7755 and #5781
Same code is used here, for the same reasons: https://github.com/ddnet/ddnet/blob/495290e0b2c38029a7913db0945e7ea9e944551d/src/game/server/player.cpp#L722-L737
=> Fix AFK when timing out

CMakeLists.txt
Fixes https://github.com/ddnet/ddnet/issues/7775
=> CMake: Re-configure the project on version.h changed

src/game/client/components/chat.cpp
=> Various minor refactoring of chat rendering, fix chat background size

src/game/editor/editor.cpp
I think this broke some time ago, currently we can no longer move the points of all selected quads when moving any points, it only applies to the selected quad. I don't think this was intended, which is why I made this PR to restore that functionality.
It also works with quad points alignment/snapping that I made some time ago as well.
Before:
https://github.com/ddnet/ddnet/assets/13364635/652957ae-b848-4e88-8313-2033b08c51f4
After:
https://github.com/ddnet/ddnet/assets/13364635/734f1e3d-4583-47bd-86be-22ccf0e83fee
=> Restore ability to move/edit points of all selected quads

data/languages/swedish.txt
=> Update Swedish translations for 18.0

src/game/server/player.cpp
https://github.com/ZillyInsta/ddnet-insta/issues/85
=> Report team changes to master when teams are on

src/game/client/components/menus_settings.cpp
=> moved nameplates from hud -> nameplates

src/base/system.cpp
On Windows, the result of the `localtime` function is thread-local, hence our uses of this function are already thread-safe.
On non-Windows, the `localtime` function is potentially not thread-safe, so the reentrant `localtime_r` function is used instead with a thread-local buffer for the result.
Closes #7788.
=> Ensure uses of `localtime` function are thread-safe

src/engine/client/client.cpp, src/engine/client/serverbrowser_http.cpp, src/engine/client/updater.cpp, src/engine/server/register.cpp, src/engine/shared/http.cpp, src/engine/shared/http.h, src/game/client/components/menus_browser.cpp, src/game/client/components/skins.cpp, src/game/client/components/skins.h
Following up https://github.com/ddnet/ddnet/pull/7838#discussion_r1460999318
=> Make http states a enum class and use it across the codebase

src/game/editor/editor_actions.cpp, src/game/editor/editor_actions.h, src/game/editor/mapitems/layer_tiles.cpp, src/game/editor/popups.cpp
=> Editor: made "Clean up game tiles" undoable

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings_assets.cpp, src/game/editor/editor_props.cpp
=> Various minor refactoring of menus

src/game/client/components/hud.cpp, src/game/client/components/voting.cpp, src/game/client/components/voting.h
Reduce height and empty space and make margins consistent. Slightly increase width for better round corner drawing and to support longer vote descriptions.
Auto-scale description and reason labels and show ellipsis if they don't fit.
Show circular progress indicator for remaining vote time.
Screenshots:
- Before:
- After:
=> Improve voting HUD, refactoring

src/game/client/components/menus_settings.cpp
=> Fix inconsistencies in appearance settings

README.md
=> readme: dont assume number of threads when using make

src/engine/shared/config_variables.h
=> Set max limit for `sv_port` and `ec_port` to 65535

license.txt
=> Update license year to 2024

src/game/client/components/menus_settings.cpp
=> Name plate appearance tab cleanup

src/engine/client/client.cpp, src/engine/client/client.h, src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser.h, src/engine/serverbrowser.h, src/engine/shared/http.cpp, src/engine/shared/http.h, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp
=> Write DDNet info file only when it changed, initialize HTTP later on client launch, show message box on error, refactoring

src/game/client/components/infomessages.cpp, src/game/client/components/infomessages.h, src/game/client/components/skins.cpp, src/game/client/render.h, src/game/client/skin.h
=> Refactor `CInfoMessages`

src/engine/client/client.cpp, src/engine/client/serverbrowser_http.cpp, src/engine/shared/http.cpp, src/engine/shared/http.h
=> Quit client faster by aborting HTTP requests earlier, other HTTP fixes

src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp
=> Add tooltips for all icon-based menu and browser tabs

src/engine/shared/http.cpp
Immediately cancel new HTTP requests instead of enqueuing them when already shutting down `CHttp`. Otherwise, `CChooseMaster` may wait forever for HTTP requests to be completed while the client is shutting down, if `CHttp` was shutdown while `CChooseMaster` is not waiting for an existing HTTP request.
Not directly caused by #7962, but it made it more likely to happen.
Closes #7980.
=> Abort new HTTP requests immediately when shutting down `CHttp`

src/game/editor/editor.cpp
Reset dragging operation when the dragged button has been unset and reset dragged button when operation has been reset, to prevent the editor from being stuck in either of two inconsistent states. This could be reproduced easily by clicking very quickly while moving the mouse up and down over the groups/layers list.
Do not call `CheckActiveItem` on a UI element (the dragged button) which might not be in view, as this prevents the UI from detecting the invalid active item, when groups/layers are dragged very far and quickly outside the scrollregion.
Closes #6855.
=> Fix editor UI locking up when dragging groups/layers quickly

src/game/client/components/console.cpp
=> Minor refactoring of console rendering

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/editor_props.cpp, src/game/editor/editor_ui.h, src/game/editor/popups.cpp
Screenshots:
- Before: 
- After:
=> Refactor editor button functions: replace/remove `DoButton_File`, `DoButton_ButtonDec/Inc` and `DoButton_Menu`

src/game/client/components/hud.cpp, src/game/client/components/infomessages.cpp
=> Don't show fps during demo render

src/game/server/gamemodes/DDRace.cpp
=> Expire team invites on player disconnect

src/engine/server.h, src/engine/server/server.cpp, src/engine/server/server.h, src/game/server/gamecontext.cpp
Makes it clearer to me, didn't know what an empty client is supposed to be.
CC #7968
=> `ClientEmpty` → `ClientSlotEmpty`

src/game/client/ui.h
=> Add return value docs to `DoEditBox*`

src/game/client/components/skins.cpp, src/game/client/components/skins.h
=> Validate skin names when loading, refactor skin loading

data/languages/ukrainian.txt
=> Minor fixes in ukrainian translation

.github/workflows/build.yml, .github/workflows/clang-sanitizer.yml, .github/workflows/clang-tidy.yml, .github/workflows/codeql-analysis.yml, .github/workflows/rust.yml, .github/workflows/style.yml, Cargo.toml, src/base/Cargo.toml, src/engine/Cargo.toml, src/engine/shared/Cargo.toml, src/masterping/Cargo.toml, src/mastersrv/Cargo.toml, src/rust-bridge/test/Cargo.toml
=> update ci actions, update rust edition to 2021 since our MSRV covers it

src/game/server/ddracechat.cpp
=> Make chat command arguments case-insensitive when possible

data/languages/swedish.txt
=> Update Swedish translations for 18.1

src/game/server/teeinfo.h
=> Fix client crash due to truncated skin name

.github/workflows/build.yml
=> Try to fix python macOS issue

data/languages/czech.txt
=> Update Czech translations

src/engine/server/register.cpp, src/engine/shared/http.cpp, src/engine/shared/http.h
Allows people to see why masterserver registering failed.
=> Show error from masterserver in console

src/engine/shared/jobs.cpp
We want to change the state of the job from `STATE_QUEUED` to `STATE_RUNNING`, but not from `STATE_ABORTED`. Previously, the code usedd `exchange` to change the state and compared non-atomically afterwards. This led to `STATE_ABORTED` being replaced by `STATE_RUNNING` in a race. With `compare_exchange_strong`, this can no longer happen.
Fixes #8044.
=> Fix race conditions in job state handling

src/engine/shared/fifo.cpp, src/engine/shared/fifo.h
=> Ensure commands executed via FIFO are valid UTF-8

src/game/editor/editor.cpp
=> Editor: Make embedded image popup bigger at all times

src/engine/shared/config.h, src/game/server/ddracechat.cpp, src/game/server/gamecontext.cpp
=> List all practice commands when enabling `/practice`

data/languages/slovak.txt
=> Update Slovak translations

CMakeLists.txt, data/languages/estonian.txt, data/languages/index.txt
=> Add Estonian translation (by Cammo)

data/languages/estonian.txt
=> Estonian fixes (by Cammo)

.github/workflows/clang-sanitizer.yml
=> Try older Ubuntu version for clang sanitizer

src/game/client/components/menus.cpp
=> Support clicking line color picker label to toggle checkbox

src/game/client/components/mapimages.cpp
=> Various refactoring of `CMapImages`

src/engine/shared/config.cpp, src/engine/shared/linereader.cpp, src/test/linereader.cpp
=> Ensure line reader only returns lines which are valid UTF-8, refactoring

data/languages/russian.txt
=> Typo in russian.txt

data/languages/german.txt
=> Translate Entities in german.txt

src/engine/client/serverbrowser.cpp
=> serverbrowser: communities->servers instead of communities->icon->servers

src/game/client/components/menus_settings.cpp
=> Include more options in appearance settings

src/game/client/gameclient.cpp
To reduce duplicate code and ensure all members are reset.
=> Use `CTeeRenderInfo::Reset`

src/game/client/components/menus_settings.cpp
=> Fix more variable names (`GPU` -> `Gpu`, `ID` -> `Id`)

data/languages/german.txt
it seems odd that we are translating this, but i kept jupster's style `AntiPing -> Anti-Ping` for now.
=> german.txt fix

src/engine/client/client.h, src/engine/client/input.h, src/engine/http.h, src/game/client/components/broadcast.h, src/game/client/components/countryflags.h, src/game/client/components/effects.h, src/game/client/components/emoticon.h, src/game/client/components/hud.h, src/game/client/components/infomessages.h, src/game/client/components/motd.h, src/game/client/components/nameplates.h, src/game/client/components/particles.h, src/game/client/components/spectator.h, src/game/editor/editor_history.h
Some header files were using types that depend on includes but those files were not included. This practically works during the compile process because they are included in the right order. But is theoretically bad style. It can cause unexpected compile errors on reordering includes. It breaks IDE environments (neovim + clangd for example). Also those missing includes break https://github.com/ddnet/ddnet/pull/8151.
```
$ clang-tidy src/game/client/components/emoticon.h -p build-camel/
410 warnings and 2 errors generated.
Error while processing /home/chiller/Desktop/git/ddnet/src/game/client/components/emoticon.h.
/home/chiller/Desktop/git/ddnet/src/game/client/components/emoticon.h:17:29: error: incomplete type 'IConsole' named in nested name specifier [clang-diagnostic-error]
17 | …
```
=> Add missing includes

README.md
Provide a convenient way to install and update ddnet on windows.
=> add windows installation with scoop

src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/client/text.cpp, src/engine/graphics.h, src/engine/textrender.h, src/game/client/components/countryflags.cpp, src/game/client/components/mapimages.cpp, src/game/client/components/mapimages.h, src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp, src/game/editor/editor.cpp, src/game/editor/mapitems/map_io.cpp, src/game/editor/tileart.cpp, src/tools/map_convert_07.cpp, src/tools/map_replace_image.cpp
=> Pass arguments as `CImageInfo` to graphics functions, add `CImageInfo::DataSize` convenience function

src/engine/shared/jobs.cpp
maybe we should do a patch release? i cant reproduce if it fixes it locally tho cuz i have no gcc 14
=> include algorithm in jobs.cpp, try to fix #8159

src/engine/client.h, src/engine/client/client.cpp, src/game/client/components/menus.cpp, src/game/client/gameclient.cpp
As this can take a few seconds for large demos.
=> Render loading popup also while loading demo files

CMakeLists.txt
=> Add `-fsigned-char` by default for ARM systems

src/game/client/components/menus_settings.cpp
=> Remove unused `CTextCursor` variable

src/game/client/components/menus_settings.cpp, src/game/client/ui.cpp, src/game/client/ui.h
Reduce duplicate code when using the `CUi::DoScrollbarOption` function.
=> Let `CUi::DoScrollbarOption` return `true` if value changed

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_settings.cpp
=> Add console chain for `ClBackgroundEntities`

src/game/server/gamecontext.cpp
=> Fix typo in `/team0mode` description

README.md
This PR updates the DDNet build instructions to properly describe basic build instructions for all IDEs, not just Visual Studio using MSVC, aswell as hand-holding when using visual studio code to get started.
=> update readme on building with MSVC on windows

data/languages/estonian.txt
=> Update Estonian translations by Cammo

src/engine/client/client.cpp
=> Various minor cleanup of `CClient`

datasrc/network.py, datasrc/seven/network.py
=> Change type of `m_HookTick` to `NetIntAny`

src/game/server/gamecontext.h
Probably slipped in during rebase of https://github.com/ddnet/ddnet/pull/7521.
=> Remove unused `ConMode` function

src/base/log.cpp
`GetConsoleMode` can fail with `ERROR_INVALID_HANDLE` when redirecting output to `nul`, which is considered a character file but cannot be used as a console.
=> Fix assertion on Windows when redirecting console output to `nul`

src/engine/client/client.cpp
Fix game times and prediction not being updated when only exactly two snapshots have been received, due to the conditions `m_aReceivedSnapshots[...] >= 3`. These specific condition are not necessary and replaced with simpler checks whether the current snapshot is set. Some duplicate nested conditions are also removed.
Pump the network first in `CClient::Update` before updating anything else, to ensure that snapshots are received from the network client before the game times and prediction are being updated based on the current snapshots.
Fix current and previous game tick always being `0` on the first call of `IGameClient::OnNewSnapshot` when two snapshot have been received. Now, the game ticks are properly initialized from the two initial snapshots.
Fix old inputs sometimes being used in …
=> Fix prediction errors and incorrect rendering after changing map

src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/gfx/image_loader.cpp, src/engine/gfx/image_loader.h, src/engine/graphics.h, src/game/client/components/countryflags.cpp, src/game/client/components/mapimages.cpp, src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp, src/game/client/components/skins.cpp, src/game/client/components/skins.h, src/game/client/gameclient.cpp, src/game/editor/editor.cpp, src/game/editor/editor_actions.cpp, src/game/editor/mapitems/map_io.cpp, src/game/editor/tileart.cpp, src/tools/dilate.cpp, src/tools/map_convert_07.cpp, src/tools/map_create_pixelart.cpp, src/tools/map_extract.cpp, src/tools/map_replace_image.cpp
Preparation for larger refactoring of the image loading/saving.
=> Change `PNG` in function names to `Png`, pass `CImageInfo` by reference to `IGraphics::LoadPng`

data/languages/swedish.txt
=> Update Swedish translations for 18.2

data/languages/estonian.txt
=> Update Estonian translations (by Cammo)

data/languages/czech.txt, data/languages/slovak.txt
=> Update Czech and Slovak translations for 18.2

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/shared/network.h
=> Various refactoring of client/dummy connecting

data/languages/turkish.txt
Update Turkish translations for 18.2
=> Update Turkish translations for 18.2 (by Gokturk)

CMakeLists.txt, data/languages/azerbaijanese.txt
Translation process is not ended yet. Not translated areas are filled with Turkish translation for now, Azerbaijanese and Turkish are 75-80% similar and they have a lot of words in common. People from Azerbaijan can understand Turkish I'll continue it when I have time.
=> Add Azerbaijanese translation (by Gokturk)

data/languages/azerbaijanese.txt, data/languages/belarusian.txt, data/languages/index.txt, data/languages/turkish.txt
=> Add Azerbaijanese translation

.github/workflows/build.yml
=> Remove unused gcov flags

data/languages/turkish.txt
=> Update Turkish translations

src/game/client/components/chat.cpp
=> Use LineAuthor variable to cleanup chat code

src/engine/client/graphics_threaded.cpp, src/engine/gfx/image_loader.cpp, src/engine/gfx/image_loader.h, src/engine/graphics.h, src/game/client/components/menus.cpp, src/game/client/components/menus_browser.cpp, src/game/client/components/skins.cpp, src/game/editor/mapitems/image.cpp, src/game/editor/mapitems/map_io.cpp, src/game/editor/tileart.cpp, src/tools/map_create_pixelart.cpp
=> Use `size_t` for `CImageInfo::m_Width` and `m_Height`

data/languages/finnish.txt
The Finnish translations were incomplete, causing some user interface elements to fall back on the English default. This pull request aims to provide a fully localized experience for Finnish users.
Please note that builds and other checks will be run for your change. Don't feel intimidated by failures in some of the checks. If you can't resolve them yourself, experienced developers can also help resolve them before merging your pull request.
=> Finnish language file update

src/engine/client/text.cpp
=> Always update text cursor y (closed #8282)

README.md
re-added and updated building with Visual Studio.
[reason](https://github.com/ddnet/ddnet/pull/8195#issuecomment-2088560288)
=> fix up readme on building with MSVC (Visual Studio)

src/tools/.clang-tidy, src/tools/map_find_env.cpp, src/tools/map_replace_area.cpp
Fixes https://github.com/ddnet/ddnet/pull/8151#discussion_r1586357561
=> Remove tools camel case style exception

src/game/client/components/menus_settings.cpp, src/game/client/components/skins.cpp, src/game/client/skin.h
Closed https://github.com/ddnet/ddnet/issues/8300
=> Improve skin name validation error message (Closed #8300)

src/engine/client/client.cpp, src/engine/client/sound.h, src/engine/client/video.cpp, src/engine/client/video.h, src/engine/demo.h, src/engine/shared/demo.h, src/engine/shared/video.h, src/engine/sound.h, src/game/client/components/menus.cpp, src/game/client/components/menus_demo.cpp
=> Video recorder: improve error handling and log messages, fix crashes, refactoring

scripts/integration_test.sh
=> Increase rcon command delay in integration test

src/engine/shared/demo.cpp, src/engine/shared/demo.h
=> Make demo snap variable names more obvious

src/game/client/components/chat.cpp, src/game/client/components/chat.h, src/game/client/components/emoticon.cpp
See also https://github.com/teeworlds/teeworlds/pull/3239
=> Rename chat `Say()` to `SendChat()`

src/game/client/components/camera.cpp, src/game/client/components/camera.h
Nice QoL change, why not
Closes #8335
=> Add `set_view_relative` (Closes #8335)

CMakeLists.txt, src/tools/map_create_pixelart.cpp
Fixes the issues mentioned in #8345, but the feature requests still remain unimplemented.
=> Fix issues with `map_create_pixelart`

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_settings.cpp, src/game/client/ui.cpp, src/game/client/ui_scrollregion.cpp, src/game/editor/editor.cpp
=> Fix inconsistent behavior of scrollbars, key readers, edit boxes, value selectors and editor sound seekbars

scripts/languages/copy_fix.py
See https://github.com/ddnet/ddnet/pull/8371#discussion_r1606048742
=> Fix performance regression in `copy_fix.py`

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/server/server.cpp, src/engine/server/server.h, src/game/client/components/console.cpp
=> Show percentage of loaded rcon commands (closed #7769)

src/game/server/ddracechat.cpp, src/game/server/entities/character.cpp, src/game/server/entities/character.h, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/player.cpp, src/game/server/player.h, src/game/server/save.cpp, src/game/server/save.h, src/game/server/teams.cpp
=> Add `/rescuemode` support

src/game/client/components/menus.cpp
=> Make map download progress and speed label translatable

data/languages/russian.txt
=> Small changes in `russian.txt`

data/languages/brazilian_portuguese.txt
=> Fix invalid format string in Brazilian Portuguese translation

src/game/client/components/scoreboard.cpp
With some languages the buffers for the scoreboard recording notification were not large enough when recording all 4 types of demos at the same time.
Reduce duplicate code. Avoid unnecessary, slow `str_format` for concatenation. Use UI functions for drawing the background and text.
Screenshots:
- Before: 
- After:
=> Fix truncated scoreboard recording notification, refactoring

src/game/client/components/controls.cpp, src/game/client/components/controls.h
=> Minor refactoring of `CControls`

data/languages/ukrainian.txt
I remade the Ukrainian translation, because its quality was "meh".
Thanks to everyone who helped me on the way (especially @BlaiZephyr, @heinrich5991 and @Robyt3 ❤️)
=> Remake of Ukrainian l10n

src/engine/client/text.cpp
Seems to have been just a small typo, it's very understandable given how we mix meanings of the word "character" throughout that code.
=> Fix console search highlighting. Close #8451

src/engine/shared/config_variables.h, src/game/client/components/hud.cpp
=> Add cl_showhud_time_cp_diff

data/languages/ukrainian.txt
Updating Ukrainian translation for 18.3
=> Update Ukrainian l10n (18.3)

data/languages/russian.txt
=> last Update russian.txt

src/game/client/components/menus.h
Pull request for #8417.
First time contributing, tell me what I could of done better !
=> Server browser friend list: sort not case sensitive

data/languages/swedish.txt
=> Update Swedish translations for 18.3

data/languages/czech.txt, data/languages/slovak.txt
=> Update Czech and Slovak translations for 18.3

src/game/server/gamecontext.cpp
=> update practice help text

src/engine/client/serverbrowser.cpp, src/game/client/components/menus_browser.cpp
Closes #8411. I'm not sure the solution is the best one, if you want it to be implemented in a different way, lemme know.
=> Trim Strings on Search/Exclude Filter & Add Tooltip

src/engine/client/updater.cpp, src/engine/client/updater.h, src/engine/shared/http.cpp, src/engine/updater.h, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_start.cpp
=> Minor cleanup of updater and HTTP client

src/game/server/ddracechat.cpp, src/game/server/teams.cpp
=> Don't check `sv_max_team_size` for teams in practice

src/engine/server/upnp.cpp
See https://github.com/miniupnp/miniupnp/commit/c0a50ce33e3b99ce8a96fd43049bb5b53ffac62f
=> Support new UPNP API

src/engine/client/serverbrowser.cpp, src/engine/serverbrowser.h, src/game/client/components/menus_browser.cpp, src/game/client/components/menus_ingame.cpp
Fixes #8554.
Alternative to #8555.
=> Use `Client()->PlayerName()` for copied server info

src/engine/server/server.cpp, src/engine/shared/network.h, src/engine/shared/network_conn.cpp
This is still far from optimal, but it should at least help. Ideally this stuff would be more granularly updated by keeping track of whether players changed.
=> net_addr_str only once

src/engine/server/server.cpp, src/engine/shared/network.h
=> Make FillAntibot faster

src/game/gamecore.cpp, src/game/gamecore.h
=> Minor cleanup of `gamecore.cpp/h`

src/engine/shared/network_conn.cpp
=> Reset and regenerate m_aPeerAddrStr appropriately

src/game/client/components/spectator.cpp, src/game/client/components/spectator.h
=> Refactor spectator UI input handling

src/game/client/components/camera.cpp, src/game/client/components/camera.h
=> Extract `CCamera::ZoomAllowed` function to reduce duplicate code

src/game/client/components/menus_ingame.cpp
=> Show skin name as tooltip in ingame player list

data/languages/azerbaijanese.txt
=> Update Azerbaijanese translations

src/game/client/components/chat.cpp
=> Remove multi line chat support

data/languages/ukrainian.txt
Also found a typo I made while remaking the translation :^)
=> Update Ukrainian l10n (18.4)

data/languages/swedish.txt
=> Update Swedish translations for 18.4

src/game/client/components/hud.cpp, src/game/client/components/hud.h
=> Use text containers to render movement information

.github/workflows/build.yml
=> ci: Install Rust on macOS

src/engine/client/backend/vulkan/backend_vulkan.cpp
~Essentially reverts "For integrated and discrete GPUs always prefer what comes first in the list", commit 7ca20a5873d12edc981945f9f85c6ef4a2f8310b, which attempted to resolve issue #6200.~
~That commit caused the 'auto' GPU mechanism to correctly _identify_ the proper 'auto' GPU but eventually to effectively _use_ a weaker integrated GPU while falsely claiming to be using the 'auto' GPU in the Graphics menu in-game.~
The key precondition for the regression to manifest is that the Vulkan loader suggests to use the integrated GPU first and then the discrete GPU. (i.e. integrated GPU comes before the dedicated one in the enumeration array)
In such a circumstance the integrated GPU will be effectively used and in the game's Graphics menu 'auto(dedicated_gpu_name)' will be falsely shown as …
=> Fix  'auto' GPU identification on hybrid GPU systems

src/game/server/player.cpp, src/game/server/player.h, src/game/server/save.cpp, src/game/server/save.h, src/game/server/teams.cpp
This is completely untested as I couldn't get saves working locally for some reason :/
=> Try fix issue with savegames

src/game/client/components/menus_browser.cpp
=> Also trim search strings in highlights

src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser_http.cpp, src/engine/client/serverbrowser_http.h
=> Remove `servers_legacy` support

src/engine/gfx/image_manipulation.cpp
=> Minor refactoring of `DilateImage`, `ResizeImage` and related functions

src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/game/client/components/skins.cpp, src/game/client/gameclient.cpp
=> Refactor `IGraphics::CheckImageDivisibility` and `IsImageFormatRGBA` functions

src/engine/client/backend/opengl/backend_opengl.cpp, src/engine/client/backend/opengl/backend_opengl.h, src/engine/client/backend/opengl/backend_opengl3.cpp, src/engine/client/backend/opengl/backend_opengl3.h, src/engine/client/backend/vulkan/backend_vulkan.cpp, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h
=> Remove unused graphics functions, flags and command

src/game/server/teams.cpp
=> Fix practice finish time

src/engine/server/server.cpp
=> Only ban VPNs for a minute

src/engine/server.h, src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/econ.cpp, src/engine/shared/netban.cpp, src/engine/shared/netban.h
=> Don't show ban time for vpn bans

src/engine/server/server.cpp
=> More dnsbl printing

src/engine/client/client.cpp
Show warning and disconnect instead of falling back to connecting to `localhost` when the connect address cannot be resolved.
=> Show warning when connect address cannot be resolved

src/engine/server/server.cpp
Less risk of causing microlags then, I think once per second is often enough since it has to iterate through all players
This looked slightly suspicious in a `perf recording`
=> server: Handle dnsbl and other non-critical stuff only on new ticks

src/game/server/gamecontext.cpp
=> server: Disallow moving authed players to spec

src/game/server/player.cpp
https://github.com/user-attachments/assets/dda6f5b3-a87a-4d1e-8c13-54957441d22c
=> Spawn a confetti when connecting on your DDNet birthday

.github/CODEOWNERS
=> Add @Patiga as owner of src/game/editor/mapitems/map_io.cpp

src/game/client/components/ghost.cpp, src/game/client/components/race_demo.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/client/race.cpp, src/game/client/race.h, src/game/collision.cpp, src/game/collision.h
=> Refactor `CRaceHelper`, mark `CCollision` functions as `const` and add tile getters

src/game/server/ddracechat.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/player.cpp, src/game/server/player.h
Since it's easy to abuse and impossible to moderate
Partially solves https://github.com/ddnet/ddnet/issues/8364
=> Add option to disable whispers

datasrc/network.py, src/game/client/components/mapsounds.cpp, src/game/client/components/mapsounds.h, src/game/client/gameclient.cpp
This is sound part of solving #7296 
The reason you can see in #8380
=> Add support for server play map sound

src/engine/client/client.cpp
https://en.wikipedia.org/wiki/Kilobyte
https://en.wikipedia.org/wiki/Data-rate_units
=> Fix debug hud units

src/engine/shared/netban.cpp
This improves readability and makes it easier to navigate through a large list of bans using pagination.
The list is empty :
The list contains few entries only :
Invalid page is sent to the rcon command :
Last page, containing less lines than the max entries per page :
PS: Note that during the tests banned IPs are randomized.
=> Improve bans rcon command pagination

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/game/client/components/controls.cpp, src/game/client/components/players.cpp
Thanks to @fokkonaut for this F-Client commit
https://github.com/fokkonaut/F-Client/commit/8ecd8c7f0ab4b41f16d165bc5ec9b9e87578012c
Closed #8742
=> Fix hook coll on vanilla 0.7 servers

src/base/system.cpp, src/base/system.h, src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser_http.cpp, src/test/netaddr.cpp
#8712
https://github.com/user-attachments/assets/1bcf442c-42ce-4949-969d-853fef9f9df8
=> Hide address url for 0.6 ips (Closed #8712)

src/engine/client/client.cpp, src/engine/shared/demo.cpp, src/engine/shared/demo.h
=> Fix cutting 0.6 demos

src/game/client/components/scoreboard.cpp
Found by @fokkonaut in https://github.com/ddnet/ddnet/pull/8707
=> Fix race 0.7 check null pointer dereference

src/game/client/components/menus.h, src/game/client/components/menus_settings7.cpp, src/game/client/components/skins7.cpp, src/game/client/components/skins7.h
See #8750
https://github.com/user-attachments/assets/e451ebbe-9e0f-4b23-90d9-a3e68549b5e8
=> Implement 0.7 delete skin button

CMakeLists.txt, src/engine/shared/translation_context.cpp, src/engine/shared/translation_context.h, src/game/client/components/chat.cpp, src/game/client/components/menus_settings7.cpp, src/game/client/components/players.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/client/render.cpp, src/game/client/render.h, src/game/client/sixup_translate_game.cpp, src/game/client/sixup_translate_snapshot.cpp
I didn't test it ingame, because building DDNet is too slowly on my laptop.
Anyone could test it?
=> Fix client sixup translation context

src/game/client/components/menus_settings7.cpp
=> Add delete hotkey for 0.7 skins

src/base/system.cpp
On macOS, semaphore names are global and processes can open semaphores of other processes by using their name. It was possible that multiple client/server processes randomly tried to create semaphores with the same memory address, which would cause them to have the same name. In that case, `sem_open` would fail because `O_EXCL` prevents creating semaphores if the name is already used.
This is made more unlikely by also including the PID in the semaphore name. Additionally, the semaphore name is prefixed with `/` to more closely follow the construction rules for semaphore names. In particular, the behavior is implementation-defined if the name is not prefixed with a slash.
See https://pubs.opengroup.org/onlinepubs/9799919799/functions/sem_open.html
Closes #8773.
More details are added to …
=> Make macOS semaphore names more unique, improve assertion

src/game/client/components/menus.h, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings7.cpp, src/game/client/components/skins7.cpp, src/game/client/components/skins7.h, src/game/client/ui.cpp
=> Use HSLA scrollbar color picker for 0.7 tee settings, refactor HSLA scrollbar color picker rendering

src/game/server/ddracecommands.cpp, src/game/server/entities/dragger_beam.cpp, src/game/server/entities/dragger_beam.h, src/game/server/entity.h, src/game/server/gameworld.cpp, src/game/server/gameworld.h, src/game/server/save.cpp, src/game/server/save.h, src/game/server/score.cpp
Untested. @murpii Do you have a reproducer?
=> Disallow save with draggers

data/languages/russian.txt
fix names match in https://wiki.ddnet.org/wiki/Dummy/ru and https://wiki.ddnet.org/wiki/Common_Terminology/ru#Тии
=> Update russian.txt to match wiki

src/game/client/ui_rect.h
=> Add `CUIRect::TopLeft` and `Size` convenience functions

src/game/editor/editor.cpp
=> Improve "Proof borders" description

src/engine/server.h, src/engine/server/server.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
=> Use `CJsonWriter` for creating server info JSON

data/languages/belarusian.txt
=> Update belarusian translation for 18.4

scripts/android/README.md, scripts/android/files/build.gradle, scripts/compile_libs/gen_libs.sh
=> Minor improvements to Android building

src/engine/shared/config_variables.h, src/game/client/components/menus.h, src/game/client/components/menus_settings.cpp
https://github.com/user-attachments/assets/29937a4a-980f-4eea-b81d-51a72b942196
=> Add a popup for picking a map for background entities setting

src/game/client/components/console.cpp
=> Don't allow input in console while it is opening/closing

src/game/editor/editor.cpp
https://github.com/user-attachments/assets/b1e13409-610c-48b5-ae4b-3f8e765132a7
Closes #7902
=> Add button to collapse/expand all groups in editor

src/game/editor/editor.cpp
=> Transfer server settings while using append

src/engine/client/serverbrowser.h, src/engine/serverbrowser.h, src/game/client/components/menus.cpp
Closes #8264 
All info available:
No icon available:
No info available:
=> Show server info in password popup

src/game/server/gamecontext.cpp
https://github.com/user-attachments/assets/fd524a3f-9e1d-44d3-bdd6-40096dfcc26e
Closes #8639
=> Add support for directories with `add_map_votes`

src/game/client/gameclient.cpp
=> Add console chain for 0.7 tee

src/game/client/components/menus_settings7.cpp
=> Add 0.7 skins directory button

data/languages/simplified_chinese.txt, data/languages/traditional_chinese.txt
=> Update Chinese translations for 18.5

data/languages/turkish.txt
=> Update Turkish translations for 18.5

data/languages/azerbaijanese.txt
=> Update Azerbaijanese translations for 18.5

data/languages/ukrainian.txt
=> Update Ukrainian l10n (18.5)

src/engine/client/client.cpp
Following sequence of events was possible:
1. HTTP map download for map X is started (e.g. client initially connects to server).
2. Map change message for map Y arrives while downloading (e.g. vote for another map has passed on the server).
3. Client already has map Y and loads it directly without starting or resetting the map download.
4. HTTP map download task for map X finishes.
5. Map X is loaded, overriding the map Y that should be loaded. This is one cause for #2804.
This could potentially also happen with the map download from the game-server, if the final map data chunk for a downloaded map is received directly after another map change message for a map which does not need to be downloaded, though this seems more unlikely.
This is fixed by resetting the current map download …
=> Fix map downloading overriding more recent map change messages

data/languages/czech.txt, data/languages/slovak.txt
=> Update Czech and Slovak translations for 18.5

src/game/server/entities/character.cpp, src/game/server/entities/character.h
entities/character.cpp now has the same api as prediction/entities/character.cpp
=> Simplify character tuning code

src/game/editor/popups.cpp, src/game/editor/quick_actions.h
https://github.com/user-attachments/assets/f6cf0ea8-8f15-48ee-a760-b75ffab6d101
=> Add quick action "Load Current Map"

src/game/editor/popups.cpp, src/game/editor/quick_action.h, src/game/editor/quick_actions.h
https://github.com/user-attachments/assets/806375ee-0c6b-44fc-a392-822cf6aeba1a
=> Add quick actions for Show Info Off/Dec/Hex

CMakeLists.txt, src/game/editor/editor.h, src/game/editor/enums.h, src/game/editor/mapitems/layer_tiles.cpp, src/game/editor/mapitems/layer_tiles.h, src/game/editor/quick_actions.cpp, src/game/editor/quick_actions.h
https://github.com/user-attachments/assets/5e349b83-cf66-4010-b7d9-95f96a79893e
=> Add quick actions for game tiles

data/languages/swedish.txt
=> Update Swedish translations for 18.5

src/engine/client/sound.cpp
Fixes #8815 
> at least attempted to
Test needed from affected users. @headshot2017
=> Resample to the device playback rate

src/game/client/components/scoreboard.cpp
=> Put dead players at the bottom of the scoreboard

src/game/editor/editor.cpp, src/game/editor/quick_actions.h
https://github.com/user-attachments/assets/23e3690e-a0e4-4741-9543-863cf885b323
=> Add quick action "Pipette"

src/game/editor/editor.cpp, src/game/editor/quick_actions.h
https://github.com/user-attachments/assets/d19c5fba-703a-4cb3-ab82-90a972351482
=> Add quick actions Server settings and History

CMakeLists.txt, src/game/editor/quick_actions.h, src/test/editor.cpp
See https://github.com/ddnet/ddnet/issues/8870
=> Test tooltip description style

src/engine/client/client.cpp
=> Add console chain for browser filters

src/game/client/gameclient.cpp
=> Use player name function instead of config

src/game/server/entities/character.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
Closes #8894 
https://github.com/user-attachments/assets/ea469458-6b7e-4712-b884-bb7e0280507f
=> Add /lasttp to hot reload

scripts/android/files/AndroidManifest.xml
Specify `android:installLocation="auto"` so the app can be installed on and move to the external storage.
Specify optional features which the app may use (touchscreen, game controller, external mouse).
Specify `android:preferMinimalPostProcessing="true"` so lower latency HDMI mode is enabled when available. Specify `android:hardwareAccelerated="true"` for consistency (it is already the default setting).
Specify same `android:configChanges` and `android:alwaysRetainTaskState` values as SDL to avoid potential bugs due to inconsistency with what the `SDLActivity` expects.
See https://github.com/libsdl-org/SDL/blob/f5ed158d1f59d0d3bfe65f6c3603c5082c560797/android-project/app/src/main/AndroidManifest.xml
=> Adopt changes to `AndroidManifest.xml` from SDL sample project

src/engine/client/serverbrowser_http.cpp
=> Don't allow URLs without port from the masterserver

src/game/server/save.cpp
=> Fix crash while attached to dragger during `hot_reload`

src/game/editor/editor_actions.cpp
=> Fix undo/redo for adding layers

src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/client/sixup_translate_game.cpp
=> Fix 0.7 client team colors (Closed #8977)

src/engine/client/input.cpp, src/engine/client/input.h
=> Save the config file when the app is minimized on Android

src/game/client/components/menus_settings.cpp
=> Localize `Hz` unit of refresh rate settings

src/game/editor/editor.h, src/game/editor/popups.cpp, src/game/editor/quick_actions.cpp, src/game/editor/quick_actions.h
https://github.com/user-attachments/assets/563e6c87-e721-4226-9a01-30423f5fd2f0
=> Add quick action "Add quads layer"

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/quick_actions.cpp, src/game/editor/quick_actions.h
https://github.com/user-attachments/assets/382f1c8a-904c-4a7e-8de5-8622f1574b08
=> Add quick actions for adding quads and sounds

src/engine/client/sound.cpp, src/engine/client/sound.h, src/engine/sound.h, src/game/client/components/chat.cpp, src/game/client/components/mapsounds.cpp, src/game/client/components/mapsounds.h, src/game/client/components/players.cpp, src/game/client/components/sounds.cpp, src/game/client/components/sounds.h, src/game/client/components/voting.cpp, src/game/editor/editor.cpp
=> Add volume parameter to sound play functions, fix unused volume, refactoring

src/game/editor/editor.h, src/game/editor/popups.cpp, src/game/editor/quick_actions.cpp, src/game/editor/quick_actions.h
https://github.com/user-attachments/assets/607f1908-44ab-45a7-9b0e-457bd844e84b
=> Add quick actions for adding sound, switch, front, tune, speedup and tele layers

src/engine/shared/config_variables.h, src/game/editor/editor.cpp, src/game/editor/layer_selector.cpp, src/game/editor/popups.cpp
=> Add ``ed_layer_selector`` config to to toggle layer selector feature

src/engine/client/serverbrowser.cpp
=> Fix Leak IP check

.github/workflows/build.yml, .github/workflows/clang-sanitizer.yml, .github/workflows/clang-tidy.yml, .github/workflows/codeql-analysis.yml, .github/workflows/style.yml
```
[1/322] Building C object CMakeFiles/glew.dir/src/engine/external/glew/glew.c.o
FAILED: CMakeFiles/glew.dir/src/engine/external/glew/glew.c.o
/usr/bin/cc -DGLEW_STATIC -I/home/runner/work/ddnet/ddnet/src/engine/external/glew -g -fdiagnostics-color=always -fstack-protector-strong -fno-exceptions -fsigned-char -Wno-implicit-function-declaration -MD -MT CMakeFiles/glew.dir/src/engine/external/glew/glew.c.o -MF CMakeFiles/glew.dir/src/engine/external/glew/glew.c.o.d -o CMakeFiles/glew.dir/src/engine/external/glew/glew.c.o -c /home/runner/work/ddnet/ddnet/src/engine/external/glew/glew.c
In file included from /home/runner/work/ddnet/ddnet/src/engine/external/glew/glew.c:34:
/home/runner/work/ddnet/ddnet/src/engine/external/glew/GL/glew.h:1205:14: fatal error: GL/glu.h: No such file or …
```
=> Fix glew CI error

src/base/system.cpp, src/base/system.h, src/base/types.h
=> Minor improvement of I/O functions documentation, consistently order I/O functions declarations and definitions

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/popups.cpp
https://github.com/user-attachments/assets/1d781cb0-67eb-45fc-acf0-c21e838ee6d8
=> Add custom editor entities

data/languages/swedish.txt
=> Update Swedish translations for 18.6

data/languages/simplified_chinese.txt, data/languages/traditional_chinese.txt
=> Update Chinese translations for 18.6

data/languages/turkish.txt
=> Update Turkish translation for 18.6.txt

data/languages/azerbaijanese.txt
=> Update Azerbaijanese translation for 18.6.txt

data/languages/czech.txt, data/languages/slovak.txt
=> Update Czech and Slovak translations for 18.6

data/languages/polish.txt
=> Update Polish translations for 18.6

scripts/integration_test.sh
Closed #6951
If the client or server crashes during the integration test run the next write to its fifo file will be blocking and get stuck forever.
This is especially annoying for github actions because they just run 10 hours and then get terminated by github without ever reaching the end of the integration test script that would print the details about the crash.
I tested it by adding a crash bug to the server
```diff
diff --git a/src/game/server/gamecontext.cpp b/src/game/server/gamecontext.cpp
index 3b0356a8e..e1a6054d4 100644
--- a/src/game/server/gamecontext.cpp
+++ b/src/game/server/gamecontext.cpp
@@ -1661,6 +1661,8 @@ bool CGameContext::OnClientDataPersist(int ClientId, void *pData)
void CGameContext::OnClientConnected(int ClientId, void *pData)
{
+ …
```
=> Add timeout for fifo in integration tests

src/game/client/components/menus.cpp
Closed #9038
https://github.com/user-attachments/assets/3cea6a2a-d30e-45f7-b03f-a1e45dfa6517
=> Arrow left and right in browser (internet/lan/favorites)

src/engine/client/video.cpp
Use the new `avcodec_get_supported_config` function instead of the deprecated `sample_fmts` and `supported_samplerates` members with libavcodec 61.13.100 and newer.
See https://github.com/FFmpeg/FFmpeg/blob/76eb3e5ff3a35eff01dd71aca82efcda50c4441f/doc/APIchanges#L53-L56
Closes #9085.
=> Fix use of deprecated member variables in video recorder

src/game/editor/editor.cpp
=> Editor: fix click drag navigation selecting quads/sounds

data/languages/spanish.txt
=> Update spanish.txt for 18.6

src/game/client/components/menus.cpp, src/game/client/ui.cpp, src/game/client/ui.h, src/game/editor/editor.cpp
=> Show UI debug info inside editor

src/game/editor/editor_server_settings.cpp
=> Fix server settings command help text overwriting other tooltips

src/game/server/ddracechat.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
These were missing from practice mode.
=> Add practice commands /totele(cp), /(un)livefreeze, /(un)endless

src/engine/shared/network_server.cpp
Closed https://github.com/ddnet-insta/ddnet-insta/issues/175
=> Remove null pointer mem copy

CONTRIBUTING.md
Code style discussions:
- https://github.com/ddnet/ddnet/issues/3088
- https://github.com/ddnet/ddnet/issues/6436
- https://github.com/ddnet/ddnet/issues/4626
- https://github.com/ddnet/ddnet/issues/8319
- https://github.com/ddnet/ddnet/issues/7623
- https://github.com/ddnet/ddnet/pull/7136#discussion_r1324805630 (No Get prefix)
=> Add contribution guidelines (closed #8142)

src/game/client/components/camera.cpp
I don't like linear interpolation, I think it always looks bad.
Comparison:
(Sorry for the crunchy bitrate, github is limiting to 10mb now)
https://github.com/user-attachments/assets/75245d73-684a-4183-9c47-94000dc5195d
=> Apply exponential easing to smooth camera

src/game/client/components/menus_settings.cpp
https://github.com/user-attachments/assets/760a4b20-41e4-437d-ad3d-0797f4d17c1f
=> Add hook collisions preview

src/engine/shared/config_variables.h, src/game/server/scoreworker.cpp, src/game/server/scoreworker.h, src/test/score.cpp
=> Add regional rankings to /top5team

src/engine/client/favorites.cpp
=> Fix 0.7 server favorites

src/engine/shared/http.cpp
=> Ensure lock is held when modifying condition of condition variable

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/components/menus_settings.cpp
=> Add nameplates preview

src/game/client/components/background.cpp, src/game/client/components/menu_background.cpp, src/game/client/gameclient.cpp, src/game/layers.cpp, src/game/layers.h, src/game/server/gamecontext.cpp
=> Minor refactoring of `CLayers`

src/game/editor/mapitems/layer_group.cpp
=> Use `CLayer::IsEntitiesLayer` function to avoid duplicate code

data/languages/persian.txt
=> Update Persian language by ArAsH

src/game/client/components/chat.cpp
=> Fix chat command preview overlap

data/languages/ukrainian.txt
=> Update Ukrainian l10n (18.7)

data/languages/simplified_chinese.txt, data/languages/traditional_chinese.txt
=> Update Chinese translations for 18.7

data/languages/swedish.txt
=> Update Swedish translations for 18.7

src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/client/text.cpp, src/engine/graphics.h
=> More efficient glyph uploading, fix crash with very large glyphs and font sizes, refactoring

src/engine/client/client.cpp
=> Send password on reconnect

src/engine/shared/config_variables.h, src/game/client/components/menus_settings.cpp, src/game/client/components/players.cpp
=> Add cl_hook_coll_size_other & +hookcoll button in UI

src/engine/client.h, src/engine/client/client.cpp, src/engine/client/client.h, src/game/client/components/console.cpp
=> Auto rcon auth both main and dummy

cmake/FindMySQL.cmake
the FindMySQL.cmake file is completly broken if used with nix/NixOS and it's way of declaring packages and libraries within the /nix/store
this has been tested on NixOS and Arch-linux on x86_64-linux. AFAIK this has been broken on windows before, so this would require someone to actually test this please.
=> fix FindMySQL not finding mysql under NixOS

datasrc/network.py, datasrc/seven/network.py, src/game/client/components/controls.cpp, src/game/client/components/hud.cpp, src/game/client/components/players.cpp
=> Make the client able to have tee's without weapons

CONTRIBUTING.md
=> Document that using integers in boolean contexts is not recommended

src/game/client/components/chat.cpp
Fix a bug introduced by (my) #9236
| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/1b8438de-b93f-4a58-81d9-d78c32f7ea57) | ![image](https://github.com/user-attachments/assets/6b836b12-3a3f-41ea-ad3a-3806712ab6e5) |
=> Fix colors on repeated client msg

src/game/client/components/menus_browser.cpp
~~### Friends Tab~~
~~* Added padding between items in playerlist (consistency)~~
~~* Removed random background~~
~~* Added tooltips for sections~~
~~### Server Info~~
~~* Added alpha variation to playerlist (consistency)~~
~~* Added border to background~~
~~* Colored ping~~
~~https://github.com/user-attachments/assets/ec00e0ed-fbb3-4ce3-9f20-f67fa694f710~~
~~https://github.com/user-attachments/assets/d8379612-79ff-4290-8a76-3fbb9d8b3492~~
* Add 2px padding between items (consistency)
* Added descriptions when empty
* Online players -> Online friends
* Remove alpha variation (consistency)
* Fix background being weird
* Colored ping
* Consistent colors / alpha
* Permanent scroll bar
=> Visual changes to friends and server tab

src/game/client/components/menus_browser.cpp, src/game/client/gameclient.cpp
=> Fix jetpack strength always being set to 0

src/game/editor/editor_server_settings.cpp
=> Allow empty map settings

src/game/editor/editor.cpp, src/game/editor/editor.h
=> Show size of images in editor images list and file browser

src/engine/client/graphics_threaded.h, src/engine/graphics.h
=> Remove unused graphics functions

src/game/client/components/camera.cpp, src/game/client/gameclient.cpp, src/game/client/gameclient.h
Requested on tater client discord, thought it might be upstreamed
=> Allow float zoom levels

data/languages/simplified_chinese.txt, data/languages/traditional_chinese.txt
=> Update Simplified & Traditional Chinese translations for upcoming 18.8

data/languages/traditional_chinese.txt
=> Unite the word used in traditional_chinese.txt

data/languages/swedish.txt
=> Update Swedish translations for 18.8

data/languages/french.txt
=> French translation by Yubel

.github/workflows/build.yml
Fixes: https://github.com/ddnet/ddnet/issues/8550
=> CI: Add Android

data/languages/traditional_chinese.txt
https://github.com/ddnet/ddnet/pull/9329#discussion_r1867562135
:D
=> pr#9329 supplement

src/game/server/entities/character.cpp
=> Add death sounds/particles on spike in practice

src/game/client/prediction/entities/character.cpp, src/game/client/prediction/entities/dragger.cpp, src/game/client/prediction/entities/pickup.cpp, src/game/client/race.cpp, src/game/collision.cpp, src/game/collision.h, src/game/server/entities/character.cpp, src/game/server/entities/door.cpp, src/game/server/entities/dragger.cpp, src/game/server/entities/dragger_beam.cpp, src/game/server/entities/gun.cpp, src/game/server/entities/laser.cpp, src/game/server/entities/light.cpp, src/game/server/entities/pickup.cpp, src/game/server/entities/projectile.cpp, src/game/server/gamemodes/DDRace.cpp
=> Rename `CCollision` functions for readability (avoid abbreviations), combine `CCollision` functions

data/languages/russian.txt
=> russian.txt translations

data/languages/spanish.txt
=> Update spanish.txt for 18.8

src/game/client/components/chat.cpp
=> Don't merge diffrent colored client msgs

.gitignore
=> Remove obsolete `.gitignore` entries for bam

CONTRIBUTING.md, README.md
just a small addition because it's easy to miss CONTRIBUTING.md's existence.
=> extend CONTRIBUTING.md and README.md

src/engine/client/serverbrowser_http.cpp
=> Remove `skipped due to info` debug message

src/engine/client/graph.cpp, src/engine/shared/ringbuffer.cpp, src/engine/shared/ringbuffer.h
=> Fix tuning velramp graphs not being updated when tuning changed

src/game/editor/editor.cpp, src/game/editor/editor.h
=> Fix editor file dialog crash and minor issues

src/engine/client/client.cpp
=> Fix dummy swap+connect bind spamming the log

src/engine/console.h, src/engine/shared/console.cpp
=> Set a recursion limit for config files

src/game/version.h
=> Bump nightly version to 19.0

data/languages/simplified_chinese.txt, data/languages/traditional_chinese.txt
=> Update Chinese translations for 18.9

data/languages/polish.txt
=> Update Polish translations for 18.9

data/languages/swedish.txt
=> Update Swedish translations for 18.9

data/languages/ukrainian.txt
=>  Update Ukrainian l10n (18.9)

data/languages/spanish.txt
=> Update spanish.txt for 18.9

license.txt
No one cares, useless to bump every year
Just check the git log to see when last changes happened.
=> Remove year from copyright

src/game/client/components/chat.cpp, src/game/client/components/ghost.cpp, src/game/client/components/hud.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/nameplates.cpp, src/game/client/components/players.cpp, src/game/client/components/scoreboard.cpp, src/game/client/components/statboard.cpp, src/game/client/gameclient.cpp
=> Use `CGameClient::IsTeamPlay` function consistently

scripts/android/files/res/values-pt-rBR/strings.xml
=> Add Brazilian Portuguese translation for Android strings

scripts/android/cmake_android.sh, scripts/android/files/build.sh
Copy `res` folder recursively for Android. Adjust game name in all `strings.xml` files.
=> Support localizing Android-specific strings

data/languages/portuguese.txt
So many of my hours were spent in this community, so I wanted to add a contribution. I don't really have much use for these translations, but hopefully, it will help others.
I noticed the [translation status](https://ddnet.org/news/client-translations/) for my language was 41%, so now it will go to 99%. Unfortunately, it won't be 100% because the wiki URLs don't have a Portuguese translation.
---
I improved the translations that were already there, fixed some inconsistencies, and optimized all translations to fit in the space available while still making sense. Everything looks nice now. 👌
=> Add/Fix language translations for Portuguese

src/game/client/gameclient.cpp, src/game/client/gameclient.h, src/game/client/render.cpp, src/game/client/render.h, src/game/client/sixup_translate_game.cpp
=> Support rendering 0.7 bot skin decoration

scripts/android/files/res/values-zh-rCN/strings.xml, scripts/android/files/res/values-zh-rTW/strings.xml
=> Add Chinese translations for Android

src/game/client/components/binds.cpp, src/game/client/components/broadcast.cpp, src/game/client/components/chat.cpp, src/game/client/components/console.h, src/game/client/components/controls.cpp, src/game/client/components/hud.cpp, src/game/client/components/menus.cpp, src/game/client/components/menus_demo.cpp, src/game/client/components/menus_ingame.cpp, src/game/client/components/menus_settings.cpp, src/game/client/components/menus_settings7.cpp, src/game/client/components/menus_settings_assets.cpp, src/game/client/components/scoreboard.cpp, src/game/client/components/scoreboard.h, src/game/client/components/spectator.cpp, src/game/client/components/touch_controls.cpp, src/game/client/components/voting.cpp
=> Consistently name client component functions `IsActive`

src/game/client/components/maplayers.cpp
=> Simplify is entity layer check

CMakeLists.txt, src/mastersrv/src/config.rs
=> mastersrv: Add missing file for config

src/game/client/components/console.cpp
=> Fix console scrolling with touch input being too slow

CMakeLists.txt, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/client/serverbrowser.cpp, src/engine/shared/network.cpp, src/engine/shared/network.h, src/engine/shared/network_client.cpp, src/game/client/sixup_translate_connless.cpp
=> Show 0.7 servers in LAN serverbrowser

data/languages/persian.txt
=> Update Persian translations (by Fàłłéñ)

src/engine/shared/config_variables.h, src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/mapitems/layer_group.cpp, src/game/editor/popups.cpp
https://github.com/user-attachments/assets/851028c8-97a0-4e94-971f-fca39f0a7ef0
=> Add in-game entities to editor

CONTRIBUTING.md
=> Note which programming languages we use for development

datasrc/network.py
=> Add data to `Sv_TeamsState`

datasrc/network.py
This reverts commit 2aa7442595ec3f1f843057885cc6327af2a7f571.
Closed #9579
Opened #8205
=> Revert "Add data to `Sv_TeamsState`"

src/antibot/antibot_null.cpp
=> Match antibot_null.cpp arg to antibot_interface.h

src/engine/client/client.cpp
Fixes https://github.com/ddnet/ddnet/issues/9480
=> Fix dummy reconnect

src/engine/server/server.cpp
=> Escape only route part of custom map download URL

src/game/client/components/hud.cpp, src/game/client/components/hud.h
=> Show position of paused character currently spectating

README.md
Also remove the `-j$(nproc)` parameter, if the user wants to fast, they should use `ninja`.
=> README.md: Don't require the user to `mkdir`/`cd`

src/engine/client/client.cpp
=> Consistently use SDL hint constants from `SDL_hints.h`

src/game/editor/popups.cpp
See https://discord.com/channels/252358080522747904/757720336274948198/1332334328029646859
=> Fix a crash when delete a sound in editor

src/game/server/gamecontroller.h
this falls under #7777 and can be rejected because it does not bring any benefit to ddnet.
This would reduce git conflicts in my downstream so I try it anyways since it is a small change.
=> Mark DoWarmup as virtual

src/engine/input.h
Thanks to ForgottenCat for noticing.
=> Fix documentation of `CTouchFingerState` delta value

data/languages/romanian.txt
=> Update romanian translations 

CMakeLists.txt, src/test/gameworld.cpp, src/test/score.cpp
this allows writing tests for things like gameworld, gameserver, character, player and so on.
Needed for:
https://github.com/ddnet/ddnet/pull/9386#issuecomment-2565477627
=> Link the entire server into tests

data/languages/swedish.txt, src/game/client/components/menus_settings.cpp
=> show fps as button on graphic tab. added swedish translations :)

CMakeLists.txt
This seems to work
Fixes: #9645
=> Alternative fix for #9645

src/base/rust.rs
=> Minor rust warns fixes

src/base/color.h
=> Mark most color functions as `constexpr`

data/languages/dutch.txt
=> Update dutch translations

data/languages/swedish.txt, scripts/android/files/res/values-sv-rSE/strings.xml
=> Update Swedish and add Android translations

src/game/server/ddracechat.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/score.cpp, src/game/server/teams.cpp, src/game/server/teams.h
=> Address /unpractice review comments

data/languages/dutch.txt
=> Fix dutch translation credits

src/game/version.h
=> Bump version to 19.1

data/languages/romanian.txt
=> Update Romanian translation

data/languages/spanish.txt
=> Update spanish.txt for 19.0

data/languages/simplified_chinese.txt, data/languages/traditional_chinese.txt
=> Update Chinese translations for 19.0

data/languages/azerbaijani.txt, data/languages/turkish.txt
=> Update Turkish & Azerbaijani translations for 19.0

src/game/client/components/infomessages.cpp
Fix assertion error due to victim client IDs of team kill messages being uninitialized as the `CTeamsCore::Teams` function returns incorrect teams for inactive clients.
Do not render invalid tees for kill messages with inactive killer or victim. Ignore kill messages that have neither active killer nor active victim nor valid weapon.
Ignore race finish messages for inactive client IDs.
=> Improve info message validation, fix assertion error on team kill

scripts/android/files/res/values-tr-rTR/strings.xml
as i see from other PRs i think it's right, if there is something missing i can fix it
=> Add Turkish translations for Android

data/languages/danish.txt
Translations made by z0rba and Anthony (danishgoat29)
=> Update danish translations

src/engine/client/client.cpp
=> Fix localization

src/game/client/prediction/entities/character.h, src/game/client/prediction/entity.h, src/game/client/prediction/gameworld.cpp, src/game/client/prediction/gameworld.h, src/game/server/entities/character.h, src/game/server/entities/projectile.cpp, src/game/server/entities/projectile.h, src/game/server/entity.h, src/game/server/gameworld.cpp, src/game/server/gameworld.h, src/test/gameworld.cpp
Solves 16 year old todo comment
=> Add more general `IntersectEntity()`

data/languages/simplified_chinese.txt, data/languages/traditional_chinese.txt
=> Updated Chinese translation

src/game/server/ddracechat.cpp
=> Fix unpractice when locked

src/game/client/gameclient.cpp
It's brittle and a never-ending maintenance overhead.
=> Add a comment explaining that game type sniffing should not be extended

src/game/editor/quick_actions.cpp
=> Allow test map locally in subfolders

src/game/client/components/menus_settings.cpp, src/game/client/ui.cpp, src/game/client/ui.h
Don't know how useful it is but it follows the idea of `DoButton_CheckBoxAutoVMarginAndSet`
=> Add DoLabel_AutoLineSize

src/base/system.cpp, src/base/system.h, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/client/input.cpp, src/engine/client/sound.cpp, src/engine/shared/config.cpp, src/engine/shared/datafile.cpp, src/engine/shared/network_server.cpp
=> Add format args to dbg_assert

scripts/languages/copy_fix.py
=> fix language script

src/game/server/ddracechat.cpp
=> Fix keeping spec

src/engine/shared/datafile.cpp, src/engine/shared/datafile.h, src/tools/map_extract.cpp
See commit messages. Preparation for adding validation to the datafile reader.
=> Various minor refactoring of datafile reader and writer

CONTRIBUTING.md
=> Discourage use of `static` variables in contributing guide

cmake/FindMySQL.cmake
=> Replace deprecated exec_program with execute_process in mysql cmake

CMakeLists.txt, src/game/client/components/chat.h, src/game/client/components/players.cpp, src/game/client/components/skins.cpp, src/game/client/render.cpp, src/game/client/render.h, src/game/client/skin.cpp, src/game/client/skin.h
=> Refactor `skin.h`: use `class`es, move function definitions to source file

data/languages/simplified_chinese.txt, data/languages/traditional_chinese.txt
=> Update Chinese Translations for 19.1

data/languages/russian.txt
=> Update Russian translations for 19.1

data/languages/swedish.txt
=> Update Swedish translations for 19.1

data/languages/polish.txt
=> Update Polish translations for 19.1

.github/workflows/build.yml, .github/workflows/clang-sanitizer.yml, scripts/integration_test.py, src/engine/server/register.cpp, src/mastersrv/src/main.rs
=> Test mastersrv registering in integration tests

src/base/system.cpp
See https://github.com/ddnet/ddnet/pull/9935#discussion_r2011988081
=> Use permalink and add date for `str_valid_filename` references

src/game/server/ddracecommands.cpp, src/game/server/entities/character.cpp, src/game/server/entities/character.h, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
=> Remove `freezehammer` command

data/languages/romanian.txt
Deșteaptă-te, române! :D
Every Romanian translation is now up to date
=> Update Romanian translations

CMakeLists.txt
=> rename server-without-main to game-server-without-main

data/languages/spanish.txt
=> Update spanish.txt for 19.1

CONTRIBUTING.md
=> Update prefixes in CONTRIBUTING.md

src/game/editor/editor.cpp
When looking into more previews I noticed, that the `Number` and `Index` don't make sense. This just happened to align in memory and Number was always 0. This PR properly casts the CLayerTiles into CLayerSwitch in order to access CSwitchTiles properly.
followup of #9945
=> fix door preview tile type

src/game/client/prediction/entities/pickup.cpp
Not sure why this was commented out since the very first prediction pr
=> Fix heart pickup prediction

src/game/client/prediction/entities/character.cpp
This codebase is full of vulgarity and noodles. Lets make it a friendlier place and promote a healthier working environment
=> Remove comment

src/engine/client/discord.cpp
=> Fix MSYS2 warnings

src/game/client/components/maplayers.cpp, src/game/client/components/maplayers.h
Part 1 of #10004, just putting this duplicated code into it's own function. I'll follow up with the next refactor after this one gets merged
I checked if this impacts performance, and I can't tell if it does or not, which is good.
Before:
After:
=> Factor out GetLayerType function

src/game/client/components/players.cpp
=> Remove unused functions in players.cpp

src/game/client/components/maplayers.cpp, src/game/client/components/maplayers.h
Refactor part two of #10004 (doesn't close)
=> Refactor: Maplayer overlay count

src/game/client/components/maplayers.cpp
part 3 of #10004 (doesn't close), fixes everything outside of `OnRender` that angers me while reading 😠.
=> Refactor: Maplayer Border Checks

src/engine/shared/console.cpp
* Adds orange, lime, teal, purple and pink
* Turns named colors into a map
=> Add more named colors

src/engine/client/client.cpp
=> Remove game msg set team from system msg branch

src/game/client/components/skins.cpp
=> Fix favorite skins not shown in skin list unless loaded

src/engine/server/antibot.cpp
=> Print antibot versions on mismatch

src/game/client/components/hud.h
* Remove const qualifiers (`readability-avoid-const-params-in-decls`)
* Remove unused/unimplemented `RenderVoting()`
=> Cleanup hud.h

src/game/client/components/chat.cpp, src/game/client/components/chat.h
=> Clean chat

data/languages/belarusian.txt
=> Update belarusian 19.1

src/engine/shared/http.cpp, src/engine/shared/http.h
=> http clang tidy fixes

src/engine/client/serverbrowser.cpp, src/engine/client/serverbrowser.h
=> use ordered containers to sort excluded filters in config

src/game/client/components/spectator.cpp
=> Cleanup CSpectator::SpectateClosest

src/game/server/gamecontext.cpp
Fixes segfault on server start
```
./DDNet-Server dump_antibot
```
=>  Fix antibot config segfault

data/languages/simplified_chinese.txt
=> Update simplified Chinese translations for upcoming 19.2

data/languages/russian.txt
=> Update 19.2 Russian translations (by oxyzo)

src/engine/shared/config_variables.h
fixes issue pointed out in #10165 by @Kaffeine
=> fix dragger default color

data/languages/traditional_chinese.txt
=> Update traditional Chinese translations for upcoming 19.2

src/engine/client/video.cpp, src/engine/client/video.h
=> Minor refactoring of video rendering

src/game/client/sixup_translate_game.cpp
=> Fix 0.7 skininfo crash

data/languages/spanish.txt
=> Update spanish.txt for 19.2

data/languages/ukrainian.txt
=> Update ukrainian.txt for 19.2

.github/workflows/codeql-analysis.yml
`Error: CodeQL Action major versions v1 and v2 have been deprecated. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/`
Hopefully fixes the CI failures in our master branch:
` Error: Resource not accessible by integration`
=> Update CodeQL to v3.

src/base/system.cpp, src/base/system.h, src/engine/client/client.cpp
=> Improve base network error handling, use random ephemeral ports for client sockets unless port fixed

src/game/client/components/hud.cpp, src/game/client/components/hud.h
Cleanup stuff related to showing position information
This is definately not so that #10059 can be added to TClient without being as invasive or bulky and in defiance of #7777
=> Hud Info cleanup

src/game/client/components/menus.cpp, src/game/client/components/menus.h, src/game/client/ui.cpp, src/game/client/ui.h
See commits
Basically my IDE was complaining at me very loudly
Questions:
Should UI -> Ui? as it is now it's quite inconsistent
Should static const member be screaming case?
Why is `static CMenusKeyBinder m_Binder` static? (should be `ms_Binder` anyway)
~~- [ ] Tested the change ingame~~
=> menu.h/ui.h clean

data/languages/turkish.txt
=> Fix Turkish Translation

.gitignore
https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html
=> Add CMakeUserPresets.json to .gitignore

README.md, cmake/toolchains/Emscripten.toolchain, data/shader/primex.vert, other/emscripten/minimal.html, src/base/system.cpp, src/engine/client/backend/opengl/backend_opengl3.cpp, src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h, src/engine/client/client.cpp, src/engine/shared/engine.cpp
Mostly works except for socket networking. See commit messages.
=> Various fixes to make Emscripten client runnable again

src/game/client/components/hud.cpp, src/game/client/components/hud.h
See commits
Another day another doller
=> Hud info cleanup 2

CONTRIBUTING.md
Please push back on anything here
There's already issues on enumeration style, I added the things which were more definate
Still unclear what is meant to be done for flags
There are lots of small changes here aswell
=> Contributing.md changes, add enumerations section

src/engine/client.h, src/engine/client/backend_sdl.cpp, src/engine/client/client.cpp, src/engine/client/client.h, src/engine/client/graphics_threaded.cpp, src/engine/client/graphics_threaded.h, src/engine/graphics.h, src/game/client/components/menus_settings.cpp
=> Avoid unnecessary delegation of graphics functions, minor cleanup

CMakeLists.txt, src/game/client/prediction/entities/character.h, src/game/race_state.h, src/game/server/ddracechat.cpp, src/game/server/ddracecommands.cpp, src/game/server/entities/character.cpp, src/game/server/entities/character.h, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h, src/game/server/gamecontroller.cpp, src/game/server/gamemodes/DDRace.cpp, src/game/server/player.cpp, src/game/server/save.cpp, src/game/server/teams.cpp, src/game/server/teams.h
I've implemented race support for infclass and want to share some of refactoring. I'm not sure if you're interested in race abstraction/incapsulation and stopped on those few commits for now.
=> Refactor some race-related code

src/base/system.cpp
The `DeleteFileW` function only marks the file for deletion but the deletion may not take effect immediately, which can cause subsequent operations using this filename to fail until all handles are closed. The `MoveFileExW` function with the `MOVEFILE_WRITE_THROUGH` flag is guaranteed to wait for the file to be moved on disk, so we first rename the file to be deleted to a random temporary name and then mark that for deletion, to ensure that the filename is usable immediately.
References:
- https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-deletefilew
- https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-movefileexw
Closes #10241.
=> Fix removing open files on Windows by first renaming to temporary

src/engine/server/server.cpp
=> Fix `sv_shutdown_when_empty` not working while recording demo

src/base/system.cpp, src/engine/shared/websockets.cpp, src/engine/shared/websockets.h
Closes #5625.
- native client and server on Windows
- native client and server on Ubuntu
- Emscripten client and native server on Windows:
=> Various fixes and refactoring of websocket networking

src/engine/client.h, src/engine/shared/uuid_manager.cpp, src/game/client/components/debughud.cpp, src/game/client/components/debughud.h
=> Some small cleanup

src/engine/shared/config.cpp, src/engine/shared/console.cpp, src/engine/shared/console.h
=> Move console stuff to cpp

src/base/system.cpp, src/base/system.h, src/engine/client/client.cpp, src/engine/shared/network.h, src/engine/shared/network_client.cpp, src/engine/shared/network_console.cpp, src/engine/shared/network_console_conn.cpp, src/engine/shared/network_server.cpp
=> Improve network console error handling, various network refactoring, fix clients with same IP not being dropped from econ

src/base/system.cpp
=> Set thread name using SetThreadDescription

data/languages/turkish.txt
=> fix turkish translations

data/languages/simplified_chinese.txt
=> Update simplified Chinese translations for upcoming 19.3

src/game/client/components/menus.cpp
=> Fix FSAA samples button flags

src/engine/shared/netban.cpp
Fix incorrect additional page being shown when the total number of bans is divisible by the page size of 20.
Improve performance by breaking early after the end of the current page, instead of always looping over all bans.
=> Fix `bans` command page count, improve performance

src/game/editor/editor.cpp, src/game/editor/editor.h, src/game/editor/map_view.cpp, src/game/editor/map_view.h, src/game/editor/mapitems/image.cpp, src/game/editor/mapitems/layer_front.cpp, src/game/editor/mapitems/layer_game.cpp, src/game/editor/mapitems/layer_group.cpp, src/game/editor/mapitems/layer_quads.cpp, src/game/editor/mapitems/layer_sounds.cpp, src/game/editor/mapitems/layer_speedup.cpp, src/game/editor/mapitems/layer_switch.cpp, src/game/editor/mapitems/layer_tele.cpp, src/game/editor/mapitems/layer_tiles.cpp, src/game/editor/mapitems/layer_tune.cpp, src/game/editor/proof_mode.cpp
=> Fix incorrect asset usage check for sounds, various minor editor refactoring

scripts/integration_test.py
=> Attempt to fix occasional timeout in integration test

src/game/client/components/players.cpp, src/game/client/components/players.h
- Extract `CalculateHandAngle` and `CalculateHandPosition` functions to reduce duplicate code.
- Use `WithAlpha` function for colors.
- Unroll loop to improve readability.
=> Minor refactoring of tee hand rendering

src/game/server/ddracecommands.cpp, src/game/server/gamecontext.cpp
I don't use kill_pl instead using set_team, if kill_pl didn't leak my name and could provide a reason I would use it more
=> Improve kill pl

src/game/client/components/menus_settings7.cpp, src/game/client/ui_listbox.cpp, src/game/client/ui_listbox.h, src/game/client/ui_scrollregion.cpp, src/game/client/ui_scrollregion.h
=> Minor refactoring of `CListBox` and `CScrollRegion`

src/game/server/gamecontext.cpp
https://github.com/ddnet/ddnet/pull/10482#issuecomment-3065934623
=> `broadcastid` → `broadcast_pl`

src/engine/server/register.cpp
This will come in handy for the planned 128 player support and reduces the diff of the currently pending pr #9274
=> Double server info size in preperation for 128 slots

src/game/server/ddracechat.cpp, src/game/server/entities/character.cpp, src/game/server/entities/door.cpp, src/game/server/entities/dragger.cpp, src/game/server/entities/gun.cpp, src/game/server/entities/light.cpp, src/game/server/entities/pickup.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontroller.cpp, src/game/server/player.cpp, src/game/server/player.h, src/game/server/teams.cpp
This will come in handy for the planned 128 player support and reduces the diff of the currently pending pr #9274
=> Add ``CPlayer::SetSpectatorId(id)``

CONTRIBUTING.md
=> Function pointer style guide

src/engine/server/server.cpp, src/engine/server/server.h
=> Remove unused `CServer::CClient::m_Addr` variable

src/game/client/components/binds.cpp, src/game/client/components/binds.h
=> Make binds prints the original bind command

CONTRIBUTING.md
Add paragraph describing how to find issues to work on for new contributors.
Require approval from at least two maintainers for new features to avoid feature creep.
=> Add issue finding guide and new feature rule to `CONTRIBUTING.md`

src/engine/antibot.h, src/engine/client/input.h, src/engine/client/serverbrowser_http.h, src/engine/client/serverbrowser_ping_cache.h, src/engine/console.h, src/engine/demo.h, src/engine/editor.h, src/engine/favorites.h, src/engine/ghost.h, src/engine/graphics.h, src/engine/kernel.h, src/engine/server/databases/connection.h, src/engine/server/register.h, src/engine/shared/demo.h, src/engine/shared/netban.h, src/engine/shared/video.h, src/game/client/component.h, src/game/client/components/menu_background.h, src/game/client/components/menus.h, src/game/editor/mapitems/layer.h, src/game/localization.h, src/game/server/score.h, src/game/server/scoreworker.h
=> Fix clangs recommendation to use '= default' to define a trivial destructor

src/engine/client/backend_sdl.cpp, src/engine/client/backend_sdl.h, src/engine/client/graphics_threaded.h
=> Remove unused graphics commands `CMD_NOP` and `CMD_RUNBUFFER`

src/game/server/gamecontroller.cpp
This code is duplicated/moved to CanJoinTeam() itself and doesn't do anything here.
https://github.com/ddnet/ddnet/blob/350ed04f6715b6f745d90edfd479271a8fa04a2f/src/game/server/gamecontroller.cpp#L662-L679
https://github.com/ddnet/ddnet/blob/350ed04f6715b6f745d90edfd479271a8fa04a2f/src/game/server/gamecontroller.cpp#L693-L701
=> Remove unused code

src/game/editor/editor_trackers.cpp, src/game/editor/mapitems/layer_tiles.cpp, src/game/editor/popups.cpp, src/game/mapitems.cpp, src/game/mapitems.h
=> Refactor `PackColor` function and usage, add `UnpackColor` function

src/game/client/components/render_layer.cpp, src/game/client/render.cpp, src/game/client/render.h
Preperation for #10630
@Robyt3
=> Refactor: move MapScreenToGroup into render layers

src/game/client/components/render_layer.cpp
This PR implements a fixed lookup table for texture coordinates used for GPU uploading in map setup. Instead of recalculating the coordinates for every tile, they can be simply read with the tileflags and put directly into the buffer.
While it's hard for me to measure improvements, this actually feels a lot faster.
@Robyt3 can you do a profiling again? On dc you said that most of the time is spend in `AddTile`, this improves this hotpath (and it feels like by a lot)
closes  #10663  ~~, might even close it. I don't know when this should be closed~~
=> Optimization: Add tex coords lookup table in order to improve map loading times

src/game/editor/editor.cpp, src/game/editor/editor_actions.cpp, src/game/editor/popups.cpp, src/game/mapitems.cpp, src/game/mapitems.h
=> Add `CEnvPoint::ColorValue` and `SetColorValue` functions

src/engine/serverbrowser.h, src/engine/shared/serverinfo.cpp, src/engine/shared/serverinfo.h, src/game/client/components/menus.h, src/game/client/components/menus_browser.cpp
=> Render 0.7 skins in serverbrowser

src/game/client/components/render_layer.cpp, src/game/client/components/render_layer.h
Just the logical followup of #10671
=> Feature: memorize quads pointer

src/engine/server/server.cpp, src/engine/server/server.h, src/engine/shared/http.h
=> Use enum class for EDnsblState

src/engine/client/backend_sdl.cpp, src/engine/client/client.cpp
=> Show more details in popup when graphics failed to be initialized, fix crash after graphics failed to be initialized 

datasrc/compile.py, datasrc/datatypes.py, datasrc/network.py, datasrc/seven/compile.py, datasrc/seven/datatypes.py, src/engine/server.h, src/engine/shared/snapshot.h, src/game/client/gameclient.cpp, src/game/client/sixup_translate_game.cpp, src/game/client/sixup_translate_snapshot.cpp, src/game/server/gamecontext.h, src/game/server/player.cpp, src/tools/demo_extract_chat.cpp
The method CSnapShot::DebugDump() used to print just the raw snap items. Without item names or field names:
```
2024-04-07 09:10:01 I snapshot: data_size=356 num_items=10
2024-04-07 09:10:01 I snapshot:         type=0 id=32767
2024-04-07 09:10:01 I snapshot:                   0  -1824658838        933dea6a
2024-04-07 09:10:01 I snapshot:                   1   -629591830        da7930ea
2024-04-07 09:10:01 I snapshot:                   2  -1450210576        a98f8af0
2024-04-07 09:10:01 I snapshot:                   3    914991429        3689a945
2024-04-07 09:10:01 I snapshot:         type=0 id=32766
2024-04-07 09:10:01 I snapshot:                   0    583701389        22ca938d
2024-04-07 09:10:01 I snapshot:                   1    327171627        13803e2b
2024-04-07 09:10:01 I …
```
=> More details in snapshot debug dump

.github/workflows/build.yml
Format yml file, remove unused build-args, use double braces instead of quotes when applicable.
=> Cleanup build.yml

src/game/server/ddracechat.cpp, src/game/server/entities/character.cpp, src/game/server/save.cpp, src/game/server/save.h, src/game/server/teams.cpp
=> Fix rescue resets switches

src/game/server/ddracecommands.cpp, src/game/server/gamecontext.cpp, src/game/server/gamecontext.h
=> Fix chat messages being truncated in server log dump

src/game/editor/editor_server_settings.cpp
=> Fix server settings adding commands while input isnt active

.clangd
=> Help clangd to properly include the moved generated code

data/languages/polish.txt
=> Update Polish translations for 19.4

data/languages/ukrainian.txt
=> Update Ukrainian translations for 19.4

data/languages/spanish.txt
Improving the Spanish Translation
=> `spanish.txt` fixes ("Demo Playback" + "Touch Button Visibilities")

src/game/client/components/players.cpp
less naked floats and implicit float conversions
@ChillerDragon free pr as they say
part of #10828
=> Fix float notation in CPlayers::RenderPlayer

src/engine/client/serverbrowser.cpp
=> 0.7 address server community fix

src/game/client/components/menus_settings.cpp
Requested in https://github.com/ddnet/ddnet/pull/10605#issuecomment-3245587911
=> Add delayed update to refresh rate scrollbars

src/engine/shared/network.h, src/game/server/entities/character.cpp, src/game/server/entities/character.h, src/test/gameworld.cpp
=> Extract snapped emote into own method

src/game/server/ddracechat.cpp, src/game/server/teams.cpp, src/game/server/teams.h
https://github.com/ddnet/ddnet/pull/10467#pullrequestreview-3193954482
=> Refactor ddrace team join check

src/base/system.h, src/base/vmath.h, src/engine/shared/ringbuffer.h
=> Remove redundant const and type cast

src/game/client/components/menus.cpp
=> Fix demo rename not working if names only differ in capitalization

src/game/map/envelope_extrema.cpp
=> Fix: envelope extrema size check

src/game/client/components/console.cpp, src/game/client/components/console.h
=> Fix hidden input when searching in unauthed rcon

src/game/client/components/players.cpp
No behaviour change, just moving parts to with with rendering and calculating closer to eachother
=> Refactor  CPlayers::*

src/game/editor/popups.cpp
=> Fix editor sound removal check not considering correct sound

src/engine/graphics.h
=> More vec2 constructors

src/game/client/components/players.cpp
Currently the hook collision is rendered in line or quad segments one by one. This can be improved by rendering all at once.
- The code is bit cleaner
- You should have a small performance increase, please don't let me do benchmarks for this.
I invite @SollyBunny to take a look at this
Tested ingame:
=> Refactor: Improve hook collision line render logic

src/engine/client/backend/opengl/opengl_sl.cpp, src/engine/client/backend/opengl/opengl_sl_program.cpp, src/engine/client/backend/opengl/opengl_sl_program.h
[View the first commit ignoring whitespace](https://github.com/ddnet/ddnet/commit/6b71e56504b7e15f58647da013974be2a7de3ef5?w=1).
=> Improve OpenGL shader compiler/linker error handling, minor refactoring

src/base/str.cpp, src/base/str.h, src/base/system.cpp, src/base/system.h
=> Move more str functions to str.cpp

src/game/editor/auto_map.cpp
=> Minor improvement of automapper log messages

src/game/editor/editor.cpp, src/game/editor/mapitems/map.cpp, src/game/editor/mapitems/map.h
=> Minor cleanup of `CEditorMap::CreateDefault` function

src/game/client/components/items.cpp
* Remove `Angle`
* Float style
* Move rendering stuff together
* Remove unneeded extra team check
Picked both colored flags in CTF, works fine to me!
=> Refactor CItems::RenderFlag

.clang-format, src/engine/server/sql_string_helpers.h, src/engine/shared/protocol7.h, src/engine/textrender.h, src/test/mapitems.cpp
=> Remove comments terminating `namespace`s

src/engine/textrender.h, src/game/client/components/menus_browser.cpp
=> Add login required icon to server browser

src/mastersrv/src/config.rs, src/mastersrv/src/main.rs
Previously, "400 Bad Request" was used, which is inappropiate.
Also make sure to prefix the ban message with "banned: ".
=> mastersrv: Use "403 Forbidden" for responses to banned IP addresses

data/languages/ukrainian.txt
=> Update Ukrainian translations for 19.5
