- src/game/server/gamecontext.cpp
> Fix server crash when starting with `random(_unfinished)_map`

- .clang-tidy
- src/engine/client/serverbrowser.cpp
- src/game/client/components/race_demo.cpp
Introduces checks for more variable types.
And fixes false positives in newer clang versions.
> Improve clang variable naming checks

- src/game/editor/auto_map.cpp
Fix invalid logic for skipping empty tiles in automapper
Fix partial default rule search
Fix reading from wrong layer when proceeding
Fixes #8134. Fixes #8526.
I've tested with the provided rules from both issues and the fixes solves the issues mentioned. I also tested with some other rules that I had laying around and it seems like they did not break. However, I did not test with more large and complex automapper rules. There might be some "breaking" changes but now the logic is actually correct and does what it is supposed to do.
> [Editor] Fix various automapper issues

- src/game/client/components/scoreboard.cpp
- src/game/server/ddracechat.cpp
Add team size indicator:
- In scoreboard
- In chat when using `/team` with no arguments
Closes #8496.
Scoreboard having a lot of players:
Scoreboard having a few players:
> Add team size indicator

- src/game/server/ddracechat.cpp
- src/game/server/ddracecommands.cpp
- src/game/server/entities/character.cpp
- src/game/server/entities/character.h
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
When practicing maps sometimes it's nice to adjust the number of jumps, this can be used to imitate infinite jumps too by settings jumps to a incredibly high value.
rcon command is mainly because it seems every practice command has a rcon equivalent so I added that too
> add "/setjumps" practice command and "setjumps" rcon command

- CMakeLists.txt
Use the build folder as the working directory for the cargo build so rustup overrides of individual build folders are respected.
> Fix rustup toolchain overrides not working with MSVC

- src/tools/map_extract.cpp
> Improve `map_extract` tool: fix crash when opus file cannot be opened, improve logging, refactoring

- src/engine/server/server.cpp
> Fix multiple redirected clients not dropped in the same tick

- src/base/system.cpp
- src/base/system.h
- src/game/client/components/console.cpp
- src/game/client/components/console.h
- src/test/str.cpp
Shows help text of last command not of the entire input.
Fix console search with multiple commands.
Auto complete when chaining multiple commands.
https://github.com/ddnet/ddnet/assets/20344300/6df56d83-ce1e-42cb-9716-f91a54ec9764
> Show help text when chaining multiple commands

- src/game/client/components/scoreboard.cpp
When `GAMEFLAG_TEAMS` is not set, only the players of the red team are rendered in the scoreboard, but the size of the scoreboard was incorrectly calculated based on the size of the larger team (red or blue), which should only be done when `GAMEFLAG_TEAMS` is set.
Regression from #8545.
> Fix incorrect scoreboard size if blue team used without teams flag

- src/tools/demo_extract_chat.cpp
Using `CSnapshotStorage::CHolder`s in the `demo_extract_chat` tool is not necessary, as only the member variable `m_pAltSnap` is being used in this tool. The regular snapshot data was copied into `m_pSnap` but never read. The other member variables were initialized but never read.
> Cleanup snapshot member variables in `demo_extract_chat` tool

- src/engine/client.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/game/client/components/items.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/tools/demo_extract_chat.cpp
Let the `IClient::SnapGetItem` function return an `IClient::CSnapItem` directly instead of passing it as a pointer. Add the item data pointer as a member variable to `IClient::CSnapItem` instead of returning it separately. Therefore, the separate data pointer of the class `CSnapEntities` is also not necessary anymore.
Consistently mark the snapshot items and data as `const`. The C-style cast to `void *` in the `IClient::SnapGetItem` function was previously implicitly casting away the `const` of the snapshot pointers.
The item data size is already returned by the `IClient::SnapGetItem` function and getting only the size is not currently useful, so the additional `IClient::SnapItemSize` function is unnecessary.
> Simplify usage of `IClient::SnapGetItem` function, remove unnecessary `IClient::SnapGetItem` function 

- src/engine/server/main.cpp
- src/engine/server/server.cpp
- src/game/server/gamecontext.cpp
Use the real number of maximum clients returned by the `MaxClients()` function instead of the `MAX_CLIENTS` constant to calculate the debug dummy client IDs to fix a crash when `sv_max_clients` is below `MAX_CLIENTS`.
Ensure the `dbg_dummies` value does not exceed the maximum number of clients.
Changing the `sv_max_clients` config variable while the server is running does not change the maximum number of clients that can connect, as this is determined only once when the `CNetServer` is initialized. The reserved slot check and the calculation of the number of player slots for the `protocol7::CNetMsg_Sv_ServerSettings` message were using the `sv_max_clients` config variable directly, which was causing them to be out-of-sync with the real number of maximum clients.
Existing uses of the …
> Fix crashes with `dbg_dummies` and `sv_max_clients`, ensure that `sv_max_clients` can only be set when starting server

- scripts/android/files/java/org/ddnet/client/NativeMain.java
- src/android/android_main.cpp
- src/android/android_main.h
- src/engine/client/client.cpp
Restarting the client previously did not work, as the `shell_execute` function on Android uses `fork` which is not supported.
Now, the client is restarted by using an Android intent to restart the main activity. This is triggered by sending a user-defined message from the native code to the SDL main activity thread.
> Implement client restarting on Android

- src/game/client/components/scoreboard.cpp
- src/game/client/components/spectator.cpp
Support showing up to 128 players in the scoreboard and the spectator UI. The 128 players are rendered in 3 columns of 43 players in the scoreboard and in 4 columns of 32 players in the spectator UI. Other lists like the server info (ingame and in the server browser) and the voting list already support showing any number of players.
Screenshots:
- ![screenshot_2024-07-15_23-28-30](https://github.com/user-attachments/assets/30b3321f-8b9f-4e32-9c1b-28a275678ef6)
- ![screenshot_2024-07-14_20-52-40](https://github.com/user-attachments/assets/7ce9e14c-d84e-48b0-9d31-93cb16d11b10)
> Add basic support for 128 players in scoreboard and spectator UI

- src/game/client/components/scoreboard.cpp
Did not consider in #8591 that the team and size would also need this space.
Before: ![screenshot_2024-07-17_20-15-53](https://github.com/user-attachments/assets/be427ba0-f469-441c-93b2-2e2164572a23)
After: ![screenshot_2024-07-17_20-21-50](https://github.com/user-attachments/assets/fa73c7e5-7d52-46c1-a00c-885506494528)
> Slightly increase size for score in scoreboard again

- src/engine/client/video.cpp
The `in_channel_count` and `out_channel_count` properties of the `SwrContext` were already deprecated and have been removed in the most recent ffmpeg library version, hence rendering demos was causing an assertion error when these properties were set.
For newer ffmpeg versions, we now set the channel layout with the `in_chlayout` and `out_chlayout` properties instead of setting the number of channels.
> Fix assertion when rendering demo with updated ffmpeg library

- src/engine/client/client.cpp
- src/engine/client/input.cpp
- src/engine/client/input.h
- src/engine/input.h
- src/game/client/components/console.cpp
- src/game/client/components/console.h
- src/game/client/ui.cpp
- src/game/client/ui.h
- src/game/client/ui_scrollregion.cpp
- src/game/client/ui_scrollregion.h
Add support for touch input to the engine, UI and console. Ingame touch controls require more discussion and will be delivered separately based on this engine implementation.
Engine
------
The state of all currently pressed touch fingers is aggregated based on the SDL touch events and can be retrieved with the `IInput::TouchFingerStates` function. This design is less complex than an event-based system where the touch events are delivered to the individual client components, as each system would then have to keep track of the finger states individually. However, this means that only one component can handle touch fingers at any given time, which seems like a reasonable assumption for our use cases.
Obsolete code for relative mouse handling on Android is removed. Connecting a mouse to an …
> Support touch input in engine, UI and console

- src/game/client/gameclient.cpp
Only copy the server info with the `GetServerInfo` function once, as it should not change within a call of the `CGameClient::OnNewSnapshot` function.
> Avoid copies of server info in `CGameClient::OnNewSnapshot`

- src/engine/client/backend/vulkan/backend_vulkan.cpp
If I'm not mistaken, then GPUs were unconditionally added to the GPU list.
In practice that might not be the biggest deal since vk 1.1 seems like the standard, but safe is safer.
> Check API version before adding GPU to GPU list

- src/game/client/components/scoreboard.cpp
Fix team number and team size rendering outside of the scoreboard when the team is rendered on both sides.
Fix team number and team size alignment.
Fixes #8633.
> Fix team number and team size rendering

- src/game/client/components/console.cpp
- src/game/client/components/console.h
Fixes virtual keyboard on Android flashing rapidly when the console is closed.
> Fix text input rapidly activated/deactivated when closing console

- src/engine/server/server.cpp
Only ban DNSBL blacklisted players once when joining immediately after the DNSBL result is available, to prevent current players from having their runs ended when the `sv_dnsbl_ban` setting is enabled.
Note that enabling `sv_dnsbl` and `sv_dnsbl_ban` at the same time will still cause the players to be banned immediately. To prevent this, first enable `sv_dnsbl` for at least one tick, then enable `sv_dnsbl_ban`.
Closes #2640.
> Only apply DNSBL bans once when player joins

- src/game/client/components/hud.cpp
> Use same Red/Blue team colors for score HUD as for scoreboard

- src/game/client/components/chat.cpp
It is implementation-defined whether the file position returned by `ftell` denotes the beginning or the end of the file when opening in append-mode. This was causing the condition `io_tell(File) == 0` to always be true, so the CSV header was also written to `ddnet-saves.txt` every time that a new save code is written. Now, we check if the file already exists before appending and only write the CSV header once when the file does not exist yet.
> Fix CSV header being written multiple times to `ddnet-saves.txt`

- scripts/android/files/AndroidManifest.xml
Specify that Vulkan 1.1.0 is used if supported.
Remove explicit requirement of OpenGL ES 3.0 as OpenGL ES 1.0 is also supported as fallback and the client should pick the highest supported version.
> Update Vulkan and OpenGL ES versions specified in Android manifest

- src/game/editor/auto_map.cpp
- src/game/editor/component.cpp
- src/game/editor/editor.cpp
- src/game/editor/editor_object.cpp
- src/game/editor/editor_object.h
- src/game/editor/editor_server_settings.cpp
- src/game/editor/editor_server_settings.h
- src/game/editor/layer_selector.cpp
- src/game/editor/layer_selector.h
- src/game/editor/map_view.cpp
- src/game/editor/map_view.h
- src/game/editor/mapitems/image.cpp
- src/game/editor/mapitems/image.h
- src/game/editor/mapitems/sound.cpp
- src/game/editor/proof_mode.cpp
- src/game/editor/proof_mode.h
This matches the naming convention used for client components and the `GameServer()->OnInit()`
> Rename editor component `Init` to `OnInit`

- src/engine/client/client.cpp
- src/engine/client/input.cpp
- src/engine/client/input.h
- src/engine/input.h
Previously, IME composition strings were limited to at most 32 bytes, e.g. 10 Hiragana characters. Now, `SDL_TextEditingExtEvent` (`SDL_TEXTEDITING_EXT`) is supported, which uses heap-allocated composition strings of arbitrary length.
On the other hand, the buffer for input event text was larger than necessary, as SDL text events only contain at most 32 bytes (`SDL_TEXTINPUTEVENT_TEXT_SIZE` is not used directly to avoid the include). With the hint for extended IME handling enabled, long composition text will be sent as multiple text events (without breaking UTF-8).
> Support IME composition strings of arbitrary length

- src/engine/client.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/game/client/components/menus_ingame.cpp
Track whether the dummy is currently connecting separately so the dummy being disconnected due to errors can be detected. Show an error message as echo in the chat when the dummy could not be connected, e.g. when the server is full.
Use the global time for limiting the dummy connecting delay instead of using game ticks, so the delay also works correctly when having connection problems (i.e., when ticks do not advance). Handle the dummy connecting being delayed separately from the dummy currently connecting.
Add tooltips for the "Connect dummy"-button when it's disable due to dummy not being allow on the server or when connecting is delayed.
Add console error messages for `dummy_connect` command.
> Improve dummy connecting button and error handling

- src/engine/client/graphics_threaded.cpp
- src/game/client/components/menus_browser.cpp
- src/game/editor/editor.cpp
- src/game/editor/editor.h
The image data was not being freed when `IGraphics::LoadTextureRawMove` is used with images that are not in RGBA format as this falls back to using `IGraphics::LoadTextureRaw` which requires manually freeing the image data.
Also consistently clear all image info in `LoadTextureRawMove`. This makes it necessary to store the size of the preview image in the editor separately, as previously the width and height of the unloaded image info were being used to render the preview image.
> Fix memory leak of non-RGBA image data, clear all image info

- scripts/android/files/AndroidManifest.xml
Fix incorrect default value for Vulkan, which is not required.
> Add `required` attributes to Android manifest

- src/engine/client/client.cpp
- src/game/client/components/menus.cpp
Update global time also while rendering loading screens and shift the menu checker background based on the global time so it's smoother while loading.
The maximum width and height were swapped as the loop bounds, so the menu checker background did not have the correct width on very wide resolutions.
This was not noticed on common resolutions because twice as many quads as necessary were also being rendered for each row of the background. The bounds of the inner loop are adjusted and only every second x-value is iterated, which reduced the total number of quads for the checker background rendering by more than half.
> Smoother menu checker background scrolling on loading screens, fix menu checker background on wide resolutions and optimize it

- src/engine/client/client.cpp
- src/engine/client/client.h
The function is unused and because the message is not flushed it would also not have worked correctly. The `NETMSG_INPUT` message is already packed and flushed in the `CClient::SendInput` function.
Closes #8408.
> Remove unused `CClient::DirectInput` function

- src/game/client/components/damageind.cpp
- src/game/client/components/damageind.h
- src/game/client/components/effects.cpp
- src/game/client/components/effects.h
- src/game/client/components/menus_demo.cpp
- src/game/client/gameclient.cpp
> Refactor and optimize damage indicators, reset damage indicators when skipping in demo

- src/game/editor/mapitems/map_io.cpp
Only embedded images in RGBA format are loaded anymore, so the additional code for converting RGB to RGBA image data is not necessary.
> Remove unused code for saving embedded RGB map images

- src/game/server/ddracechat.cpp
- src/game/server/teams.cpp
Previously, swapping on forced solo servers was already impossible, as this would require two players to join the same team, so it would always fail with the error `Player is on a different team` (or earlier). The check `g_Config.m_SvTeam != 3` was never reached. Also, this check was not using the constant `SV_TEAM_FORCED_SOLO`. Now, an earlier check is added to show a more specific error message when trying to use `/swap` on a forced solo server.
> Add error message when trying to `/swap` on forced solo server, minor cleanup

- src/game/client/components/scoreboard.cpp
- src/game/client/components/scoreboard.h
> Fix invalid team count in scoreboard for split teams

- src/game/client/components/console.cpp
- src/game/client/lineinput.cpp
The `OnInput` function should return `true` exactly for events that were handled. In case of line inputs, the function returned `true` when then line input was changed instead. For the consoles, the function did not return `true` for some events that were handled.
> Consistently return `true` from `OnInput` function for used events

- src/game/client/components/menus_browser.cpp
- src/game/client/ui_listbox.cpp
Double-clicks could also be activated with other mouse buttons on some UI elements, which was unintentionally added by #8489.
> Only activate double-clicks with left mouse button again

- src/mastersrv/src/main.rs
Needs Rust 1.63.0, should be old enough at this point.
> Use `Ipv6::to_ipv4_mapped` in mastersrv

- src/game/server/scoreworker.cpp
- src/test/score.cpp
Before:
```
MariaDB [teeworlds]> SELECT Ranking, Time, PercentRank
-> FROM (
->   SELECT RANK() OVER w AS Ranking, PERCENT_RANK() OVER w as PercentRank, MIN(Time) AS Time, Name
->   FROM record_race
->   WHERE Map = 'Tutorial'
->   AND Server LIKE '%'
->   GROUP BY Name
->   WINDOW w AS (ORDER BY MIN(Time))
-> ) as a
-> WHERE Name = 'deen';
+---------+--------+--------------+
| Ranking | Time   | PercentRank  |
+---------+--------+--------------+
|   13674 | 191.54 | 0.0230672938 |
+---------+--------+--------------+
1 row in set (2.388 sec)
```
After:
```
MariaDB [teeworlds]> SELECT COUNT(DISTINCT Name) + 1, (SELECT MIN(Time)
->   FROM record_race
->   WHERE Map = 'Tutorial'
->   AND Name = 'deen'
->   AND Server LIKE '%'
->   GROUP BY Name
->   LIMIT 1) as minTime
-> FROM record_race
-> …
```
> Faster /rank, fixes test result

- src/game/client/components/binds.cpp
Closes #8699. Regression from #8685.
> Fix binds not being repeated when key held down

- .clang-tidy
- src/engine/client.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/engine/client/graphics_threaded.cpp
- src/engine/shared/network_server.cpp
- src/game/client/components/binds.cpp
- src/game/client/components/binds.h
- src/game/client/components/hud.cpp
- src/game/client/components/hud.h
- src/game/client/components/menu_background.cpp
- src/game/client/components/menu_background.h
- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_browser.cpp
- src/game/client/components/menus_start.cpp
- src/game/client/components/particles.cpp
- src/game/client/components/particles.h
- src/game/client/components/players.cpp
- src/game/client/components/players.h
- src/game/editor/editor.cpp
- src/game/editor/popups.cpp
- Remove `readability-identifier-naming.StaticVariableIgnoredRegexp`.
- Mark `static` variables as `const` and use `UPPER_CASE` for names when possible.
- Use local variables instead of `static` variables when possible.
- Use member variables with correct name instead of `static` variables.
- Pass output buffer for `static` function `GetKeyBindModifiersName` by argument instead of returning pointer to `static` buffer.
> Remove clang-tidy `static` variable name exceptions

- src/engine/client/client.cpp
We already sent the legacy is ddnet message and so far the ddnet protocol over 0.7 seems to work fine.
But for completeness and correctness it is now also sending the new ddnet version net message.
> Send the new is ddnet message in 0.7 connections

- src/base/system.cpp
Previously, the `net_udp_create` function returned whether the IPv6 socket in particular was created successfully. If an IPv4 socket or Websocket was created successfully before this, it was not used and also not closed properly, if the IPv6 socket could not be created.
Now, the `net_udp_create` function succeeds if the socket for at least one network type (IPv4, IPv6 or Websocket) could be created successfully.
Avoid reusing local variables and remove redundant comments. Also apply the same refactoring to `net_tcp_create`, which already has the behavior of succeeding if the socket for any network type (IPv4 or IPv6) was created successfully.
AFAICT this closes #5555. According to the log message `failed to bind socket with domain 23 and type 2`, the IPv6 (type `2`) socket was not created …
> Fix UDP socket creation/cleanup if opening IPv6 socket fails

- src/game/client/components/skins.cpp
- src/game/client/components/skins7.cpp
- src/game/client/components/skins7.h
- Only log successful log messages when `debug` is enabled, consistent with logging for regular skins.
- Use `IsImageFormatRgba` to check for RGBA image format, so this also shows a warning popup.
- Remove redundant logic for non-RGBA image data.
- Use `CheckImageDivisibility` instead of enforcing exact size of xmas hat and bot decoration images to allow higher resolution images.
- Fix image data not being freed if it has the wrong format or ratio.
- Fix potential integer overflow when calculating skin part blood color (same as for regular skins).
- Extract `LoadXmasHat` and `LoadBotDecoration` functions for readability.
> Various refactoring of 0.7 skin loading

- src/game/client/components/menus_ingame.cpp
Regressed in https://github.com/ddnet/ddnet/pull/8350, many people on Steam complained
> Show game menu buttons again, even in 5:4, when not on a red/blue-team server

- datasrc/network.py
- src/game/client/components/effects.cpp
- src/game/client/components/effects.h
- src/game/client/gameclient.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/player.cpp
- src/game/server/teams.cpp
This allows us to give birthdays a different effect in the future if we want to.
> Distinguish birthday from finish events

- src/game/client/components/scoreboard.cpp
It's quite strange that you have no access for spectators' clan information being actually in-game (scoreboard) and forced to use `Player Info` tab in in-game overlay menu. This PR aims to make access for spectators' clan field easier
> Scoreboard spectator clans

- src/game/client/components/menus_ingame.cpp
Not sure if this single string helps to understand anything for how much space it takes. See screenshots:
old:
new:
> Remove "Player Options"

- src/engine/server/server.cpp
#8722
This if statement did no longer call ``m_pRegister->OnPacket(&Packet)``
```C++
if(ResponseToken == NET_SECURITY_TOKEN_UNKNOWN && m_pRegister->OnPacket(&Packet))
```
I assume I introduced that bug in https://github.com/ddnet/ddnet/pull/5949
> Fix 0.6 master server register (closed #8722)

- src/tools/demo_extract_chat.cpp
This makes it easier to find the times of specific chat messages and broadcasts in demos.
> Print chat/broadcast times in `demo_extract_chat` tool

- src/engine/server/server.cpp
Not sure why it was on debug level before.
> Complain on higher log level that 0.7 support was disabled

- src/game/client/gameclient.cpp
> Fix asset images not being freed if they fail ratio/format check

- src/game/client/components/chat.cpp
Closed #8731
Thanks @Bamcane for the clear bug report. I was able to cleanly reproduce and verify its fixed now.
> Fix old 0.7 skins overwriting 0.6 skins in chat

- src/engine/client/client.cpp
A snapshot crc error should not happen.
If it does happen it will cause lags and it means something is really wrong.
> Use error log level for snap crc errors

- src/game/client/components/hud.cpp
- src/game/client/components/hud.h
https://github.com/user-attachments/assets/acb54e53-6bd7-47b7-88d1-e98b7b64f125
<details>
<summary>Outdated colors preview</summary>
https://github.com/user-attachments/assets/5faf0ebf-4799-4b79-81ae-7e81e45b13e6
</details>
Sometimes the Y velocity is marked green when walking on the floor this is caused by the server bug described in https://github.com/ddnet/ddnet/pull/8743
> Color speed in hud based on increase or decrease

- src/game/client/components/menus_settings7.cpp
- Fix value `0` being used for sound volume, so the tee sound was not audible.
- Use `DoButtonLogic` to trigger sound to ensure it does not play while other UI elements are active.
- Remove unnecessay `MousePosition` variable by using `MousePos` function instead.
> Improve interactive tee in 0.7 tee settings

- src/engine/client/input.cpp
- src/engine/client/input.h
- src/engine/input.h
- src/game/client/lineinput.cpp
- src/game/editor/editor.cpp
Simplify clipboard handling by returning an `std::string` and freeing the string returned by SDL immediately, so the clipboard data does not stay in memory unnecessarily after the clipboard has been used until the clipboard data is requested again.
Fix possible TOCTOU when pasting from the clipboard into a lineinput, due to the clipboard data being requested twice.
> Use `std::string` for `IInput::GetClipboardText`

- src/engine/server.h
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/engine/shared/econ.cpp
- src/engine/shared/netban.cpp
- src/engine/shared/netban.h
Players are supposed to turn of their VPN or complain to the admins if they get banned for using a VPN. Calling this "banned" seems to be confusing, as players ask for an unban even after they turned off the VPN.
> Don't show "you've been banned" for VPN bans

- src/game/editor/editor_props.cpp
> Fix editor properties not being clamped on + and - button click

- src/game/server/entities/character.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/gamecontroller.cpp
- src/game/server/gamemodes/DDRace.cpp
- src/game/server/teams.cpp
- src/game/server/teams.h
I verified with a official teeworlds client with [debug prints](https://github.com/ddnet/ddnet/issues/2523#issuecomment-2302115123) that only one sound is being played. I verified that the sounds is played only once for actions triggered by the own tee, by other tees, by other tees while being spectator in free view and by other tees while following them as spectator.
Closed #2523
> Fix sixup sounds

- src/engine/client/input.cpp
- src/engine/client/input.h
This reverts commit 91848f0be635ef495b18600abd3a95afe3b7beeb.
This was prone to accidental usage. The user interface is now usable with touch input, so this additional method to quickly and cleanly quit the game is not necessary anymore.
> Revert "Quit if Android back-button is pressed 3 times within 1 second"

- src/game/client/components/chat.cpp
Closed #8790
There are two possible save code messages sent by the server. Only one of them was covered. Now both are covered.
https://github.com/ddnet/ddnet/blob/0013615da1c51c6665d2b75bced12a7129ff97ce/src/game/server/score.cpp#L323-L330
> Fix save code not being censored in streamer mode

- src/game/server/entities/character.cpp
This allowed players to start with a teammates time and in a started state. Which would would've made it possible to exploit to skip maps like shown in this theoretical map below.
https://github.com/user-attachments/assets/8f115171-cc05-43f7-adb6-d533a4de03f8
Closes  #8779
> Don't keep `m_DDRaceState` and `m_StartTime` of teammate in team0mode after death

- src/game/client/components/menus_ingame.cpp
The additional margin left of the Spectate and Join game buttons is unnecessary.
Avoid reusing `s_SpectateButton` variable for different buttons.
Use `TEAM_RED` instead of `0` when joining game in non-team server.
Screenshots:
- Before: 
- After:
> Fix inconsistent margin in ingame menu, minor refactoring

- src/game/client/components/emoticon.cpp
- src/game/client/components/emoticon.h
- src/game/client/components/spectator.cpp
- src/game/client/components/spectator.h
- src/game/client/gameclient.cpp
Support using emoticon selector and spectator menu with touch inputs. Touching in the emoticon selector activates the selected (eye) emote and closes the emoticon selector. The spectator menu is kept open when using it for more convenience. The emoticon selector and spectator menu can be closed by touching anywhere outside of them.
Additionally, the emoticon selector and specator menu can now be closed by pressing the Escape key (i.e. the back button on Android). This made it necessary to change the order of the components for input handling, so the ingame menu will handle the Escape key after the emoticon selector and spectator menu. This also means that the Escape key can now be used to close the selector/menu when they are stuck open, which was previously delayed until ingame menu or …
> Add touch support to emoticon selector and spectator menu, minor refactoring

- .github/workflows/style.yml
- data/languages/arabic.txt
- data/languages/belarusian.txt
- data/languages/hungarian.txt
- data/languages/italian.txt
- data/languages/korean.txt
- scripts/languages/twlang.py
- scripts/languages/validate.py
Adds checks for enforcing usage of `…` instead of `...`. `twlang` already supported checking non-matching formatters, but seems to have been broken. I have moved  that logic from `twlang.py` to `validate.py` and fixed it.  It does not support validating strings that change the order of the formatters.
I've deleted the strings that I was unable to fix as they seem to have been translated wrong.
```
$ python3 scripts/languages/validate.py
Invalid: ﻪﻣﺍﺪﺨﺘﺳﺍ ﺪﻳﺮﺗ ﺖﻟﺯﺎﻣ ﻞﻫ '%s' ﻞﻤﻌﺘﺴﻣ ﻚﻤﺳﺍ
- Non-matching formatting in data/languages/arabic.txt:1029
Invalid: % сек.
- Non-matching formatting in data/languages/belarusian.txt:1623
Invalid: Загрузка каманд...
- Usage of ... instead of the … character in data/languages/belarusian.txt:1767
Invalid: Націсніце клавішу...
- Usage of ... instead of the … …
```
> Validate language files for `…` and non-matching formatters in CI

- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_settings.cpp
This check never really made sense to me, as if you're editing your background entities map, you'd have to pick a different map and re-pick your previous one to see the changes you made in game. Now that it's a reload button, and not an input box, it should especially reload the map when clicked.
> Allow reloading current background entities map

- src/engine/server.h
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/game/editor/editor.cpp
- src/game/server/entities/character.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/save.cpp
- src/game/server/save.h
Add `hot_reload` to reload map while preserving the state of tees, teams and switches. The editor will now also run this command on save instead of `reload`. Closes #585
https://github.com/user-attachments/assets/199963f8-c57e-41ca-8073-568ead3139f5
> Add `hot_reload` to reload map while preserving state

- src/game/client/components/menus_demo.cpp
Fix for https://github.com/ddnet/ddnet/issues/8797
Preview:
https://github.com/user-attachments/assets/6233e6e0-deb9-4a2a-96b4-54347b0a721c
> speedup demo with mouse scroll only if menu is active

- src/game/client/ui.cpp
Motivation: It's annoying how hard it is to grab the sliders when we have so much extra space between them.
> Adjust slider handle size

- src/game/server/gamecontext.cpp
- src/game/server/scoreworker.cpp
- src/test/score.cpp
Previously, when you voted a random unfinished map, but you already finished every map in that category, only the voter would be informed in chat: "You have no more unfinished maps on this server!"
This may lead to confusion for other players on the server, so with this change, it'll show everyone the reason the map wasn't changed after a successful vote.
> Send result of `random_unfinished_map` to all clients

- src/engine/shared/config_variables.h
- src/game/client/components/menus.h
- src/game/client/components/menus_ingame.cpp
Closes #7386 
Default config values (ascending by time):
Date descending:
Name ascending:
> Add ghost list sorting

- src/engine/server/server.cpp
- src/game/server/ddracechat.cpp
- src/game/server/score.cpp
`g_Config.m_SvMap` will contain the path to the map while `GetMapName()` strips that off.
> Use `GetMapName()` when getting the map name

- src/game/server/entities/character.cpp
Slight oversight when copy pasting ;D
> Fix `double free or corruption` crash with `hot_reload`

- scripts/android/cmake_android.sh
- scripts/android/files/AndroidManifest.xml
- scripts/android/files/build.sh
- scripts/android/files/java/org/ddnet/client/NativeMain.java
- scripts/android/files/res/values/strings.xml
- scripts/android/files/res/xml/shortcuts.xml
Define shortcuts to launch the client with either Vulkan or OpenGL graphics backend, which can be accessed by long-pressing the app icon on the home screen. This feature is available for Android 7.1 and newer.
> Add Android shortcuts for launching with Vulkan/OpenGL

- src/game/server/gamecontext.cpp
Set `m_VoteCreator` when using `force_vote`. Set `m_VoteCreator` when calling `random_unfinished_map`. This allows `random_unfinished_map` to be called from rcon and when called with `force_vote`, previously it would use the previous voters id.
> Set `m_VoteCreator` when possible

- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_settings7.cpp
- src/game/client/components/skins7.cpp
> Implement 0.7 skin save button

- scripts/android/cmake_android.sh
- scripts/android/files/build.gradle
- scripts/android/files/build.sh
Gradle can determine the NDK version automatically and this property is only required if multiple NDK versions are installed. The NDK version previously determined from the filename could not be parsed by Gradle anyway.
> Remove unnecessary `ndkVersion` from Gradle build

- src/engine/shared/storage.cpp
Otherwise skin saving will fail because the folder doesn't exist.
> Create 0.7 skin folder

- src/engine/client/backend_sdl.cpp
**How to reproduce**
Ensure that you're using a Wayland compositor and DDNet is linked against SDL2.30+, regardless of having XWayland enabled or not, do:
```(unset DISPLAY && ./DDNet)```
the game will complain that `x11 not available`.
This doesn't happen with SDL2 versions before the 2.30 series.
**What is the motivation for the changes of this pull request?**
If you try to run DDNet on SDL2.30+ on a Wayland-only machine (that is, one without XWayland support) then SDL will arbitrarily force X11 causing the game to fail to load.
The cause of the trouble lies in this SDL commit https://github.com/libsdl-org/SDL/commit/bd2f1e9ea635b232d5aa39fb9f0326b1f134b99e which was introduced in response to https://github.com/libsdl-org/SDL/issues/8812.
_TLDR;_ We link against GLEW for OpenGL, GLEW …
> Fix game launch on Wayland-only systems with SDL2.30+

- src/engine/client/backend_sdl.cpp
**What is the motivation for the changes of this pull request?**
The way I understand it, vanilla GLEW comes into two flavors defined at build time, one has support for GLX extensions and the other ones supports EGL extensions.
If GLEW GLX is linked into DDNet, and SDL2 is using the `wayland` video driver, `glewInit()` will return the `GLEW_ERROR_NO_GLX_DISPLAY` error code and we bail out.
Among the first things `glewInit()` does is to call `glewContextInit()` and only after that call has succeeded it errors out when looking up GLX extensions.
This means that GLEW is actually setup enough to work with DDNet needs.
This can be seen here: `https://github.com/nigels-com/glew/blob/master/auto/src/glew_init_tail.c#L42
This patch allows the aforementioned error code to be accepted only when …
> Workaround GLEW error code on init with Wayland

- scripts/languages/twlang.py
The script didn't set the correct end line for strings with context. This caused the ending line to be on the next strings context line, which it would delete and then the next line would have no context and therefore be considered unused.
Closes #6971
> Set correct end line in `twlang.py` for strings with context

- src/engine/shared/protocolglue.cpp
- src/engine/shared/protocolglue.h
- src/game/server/gamecontext.cpp
- src/game/server/gamecontroller.cpp
- src/game/server/gamemodes/DDRace.cpp
https://github.com/ddnet/ddnet/blob/5cf0e5e99788c0d883e4c7d18bed2ff6c5e6a424/datasrc/network.py#L8 https://github.com/ddnet/ddnet/blob/5cf0e5e99788c0d883e4c7d18bed2ff6c5e6a424/datasrc/seven/network.py#L10
0.6 game flags:
```python
GameFlags = ["TEAMS", "FLAGS"]
```
0.7 game flags:
```python
GameFlags = Flags("GAMEFLAG", ["TEAMS", "FLAGS", "SURVIVAL", "RACE"])
```
The 0.7 protocol extended the game flags without changing the old 0.6 flags. So flag teams and flag flags are the same in both versions and 0.7 just has additional flags.
The server is now sending the same m_GameFlags from the gamemode controller to 0.6 and 0.7 connections. It clamps away the unsupported flags for 0.6.
Before this commit the ddnet server would always send the hardcodet race flag to 0.7 connections while ignoring …
> Share gameflags for 0.6/0.7 instead of hardcoding it

- src/game/server/entities/laser.cpp
- src/game/server/entities/projectile.cpp
The grenade and hammer already triggered TakeDamage now all weapons hitting a tee call the method again
> Call TakeDamage on projectile and laser hit (gun, shotgun and laser)

- src/game/server/entities/character.cpp
- src/game/server/gamecontroller.h
- src/game/server/gamemodes/DDRace.cpp
- src/game/server/gamemodes/DDRace.h
Only mess with the characters armor in ddrace controllers. This allows other game modes to use the armor as actual armor.
> Only do armor progress hack in ddrace controller

- CMakeLists.txt
- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/popups.cpp
- src/game/editor/prompt.cpp
- src/game/editor/prompt.h
- src/game/editor/quick_action.h
- src/game/editor/quick_actions.cpp
- src/game/editor/quick_actions.h
closes https://github.com/ddnet/ddnet/issues/7933
follow up to https://github.com/ddnet/ddnet/pull/8358
I only added a few actions for now because I don't think the prompt and all the actions belong together in one pr. I will contribute more actions as soon as the prompt it self is merged.
https://github.com/user-attachments/assets/03def380-34dc-40fb-985c-91e9d7789a3b
<details>
<summary>Outdated video with old look</summary>
https://github.com/user-attachments/assets/dc4e184f-d955-4e8a-9d5e-0d350155644e
</details>
> Add ctrl+p editor prompt (quick actions)

- src/game/editor/prompt.cpp
- src/game/editor/prompt.h
The editor prompt always has as a first entry the last action that ran. But this entry should not show up if that action is currently disabled.
https://github.com/user-attachments/assets/f0a4a576-9a18-4e61-9b8e-d9ae69ade8ed
> Fix editor prompt suggesting disabled last action

- src/game/server/entities/character.cpp
Most but not all sound creations in CCharacter::FireWeapon have this NOLINT comment.
Somehow clang does not get tripped on all of those. But sooner or later it might. I currently got a new error in my [downstream fork](https://github.com/ddnet-insta/ddnet-insta/actions/runs/10646283934/job/29512955949) when tweaking FireWeapon a bit. So I applied the NOLINT comment to ALL occurences in FireWeapon not only the ones that clangd finds at the moment.
> Consistently apply the NOLINT comment for all sounds in FireWeapon

- src/engine/console.h
- src/engine/shared/config.cpp
- src/engine/shared/console.cpp
- src/engine/shared/console.h
- src/rust-bridge/cpp/console.cpp
Closes #8594
Integer in console :
Float with multiple arguments:
/tpxy 3.2 4 - works with ints
/tpxy 3.2 -32 - works with negative numbers
Color validation:
Old validation checks preserved:
> Add validation for chat and console command arguments

- src/game/editor/editor.cpp
- src/game/editor/quick_actions.h
https://github.com/user-attachments/assets/ebcd18a0-cb05-4af4-823d-6ef6a4cb75ae
The "searching" in the clip does not make much sense since "Toggle Grid" will be the first entry.
Which made me realize that there should probably be some smart default ordering of those actions.
> Add quick action "Toggle Grid"

- src/game/editor/quick_actions.h
I used empty as a placeholder in an earlier pr and forgot to fill it.
The text from the button is not the best but I can not come up with anything better.
> Use same descriptions for game tile actions as the button

- src/game/editor/quick_actions.h
closes #8870
keep the style across all tooltip's - every key combination is Uppercase (e.g [Ctrl+Alt+L] in square brackets and ends with a period.
addition: i found 2 lines to not be formatted like the others so i changed this in here as well.
> fix inconsistent quickaction tooltips

- src/game/editor/prompt.cpp
Closed #8867
Take enough space for the label on wide screens.
Shrink label on small screens to make sure descriptions are still readable.
> Grow prompt label if there is space and fix margins

- src/game/client/components/menus.cpp
> make reconnect screen count down from 5-1 instead of 4-0

- src/game/editor/editor.cpp
- src/game/editor/quick_actions.h
https://github.com/user-attachments/assets/ca5c871c-1660-4ba6-9ff4-51e9f4fd5364
Intentionally ordered the actions so "Reset Zoom" shows up before "Refocus" and "Server settings"
Renamed NumPad to Numpad to pass the style test.
> Add quick actions for zooming the view

- src/base/system.h
- src/engine/client/client.cpp
- src/engine/shared/netban.cpp
- src/game/client/components/hud.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/components/menus_start.cpp
- src/game/editor/editor_actions.cpp
It will now also assert if you use `str_format` with no arguments. Advising you to use `str_copy` instead.
```
[build] /home/user/Development/ddnet-pr/src/base/system.h:1239:16: error: static assertion failed due to requirement 'sizeof...(args) > 0': Use str_copy instead of str_format without format arguments
[build]  1239 |         static_assert(sizeof...(args) > 0, "Use str_copy instead of str_format without format arguments");
[build]       |                       ^~~~~~~~~~~~~~~~~~~
[build] /home/user/Development/ddnet-pr/src/engine/shared/netban.cpp:493:3: note: in instantiation of function template specialization 'str_format_opt<>' requested here
[build]   493 |                 str_format(aMsg, sizeof(aMsg), "The ban list is empty.");
[build]       |                 ^
```
Closes …
> Use `str_copy` instead of `str_format` where possible

- src/game/client/components/scoreboard.cpp
If the game is paused and a player joins a server (sv_tournament_mode 0) The scoreboard will be forced open. Unless the client configured cl_scoreboard_on_death 0.
This can be quite annoying. Especially in the brand new 0.7 feature where users can pause the game. Oy realized that this is a problem 12 year ago:
https://github.com/teeworlds/teeworlds/commit/aec468a3c455872c208d999c65a38fc996567bbf#diff-e0ff7a1d6079610adb64fc89fbfff23a381ed92f268d8fe188731a9e0c323b0aR389-R390
For ddnet servers this would mostly affect tournaments where paused games are used to give everyone enough time to download the map.
A open scoreboard also blocks broadcasts. So new users might miss the admin announcements explaining why the game is paused.
Here a screenshot of a ddnet-insta server in paused game state. …
> Do not force scoreboard open when the game is paused

- src/engine/shared/config_variables.h
- src/game/editor/editor.cpp
- src/game/editor/popups.cpp
Add option to disable auto map reload feature (hot_reload) in editor. Currently you need to log out of rcon to avoid it which seems inconvenient to me. On larger maps it may be preferable to reload manually anyway as it takes a long time. (see #8824)
> Add `ed_auto_map_reload` setting

- src/engine/client/serverbrowser.cpp
- src/engine/serverbrowser.h
- src/game/client/components/menus_browser.cpp
Closes #8880 
Instead of doing nothing to the non-community servers, it'll keep them when selecting a single flag to avoid confusion. With no filter flags, clicking will enable both the flag and the 'none' flag. When one flag and the 'none' flag are enabled, clicking on the flag will disable all flags
https://github.com/user-attachments/assets/262d2385-0b8c-4da3-ad8c-d64f0c416fb5
> Change country and types filter behavior

- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
It would otherwise not use the person who started the vote to find the map. Bug from #8833
> Fix `random_unfinished_map` not working with `vote yes`

- src/game/server/gamecontext.cpp
It would previously crash if you were in `super` and doing `hot_reload`. It will now instead put you back into your actual team if you were in `super`.
> Fix crash with `hot_reload` while in `super`

- src/engine/client/client.cpp
- src/engine/client/client.h
Do not reset the active map download's information before using the fallback map download.
Remove redundant calls of `ResetMapDownload` before disconnecting, as this already resets the map download.
Closes #8885. Regression from #8848.
> Fix map download fallback from game server

- src/engine/textrender.h
- src/game/client/components/console.h
- src/game/client/components/menus_start.cpp
Add a button with the "terminal" icon in the bottom right of the start menu to open the local console to ensure that the local console is usable also when no physical keyboard (with F-keys) is available.
> Add icon button to open console in bottom right of start menu

- src/engine/client/video.cpp
The `delete ms_pCurrentVideo` deletes the current video instance (`this`) so the subsequent write to `m_Stopped` was invalid.
Closes #8899.
> Fix heap-use-after-free in `CVideo::Stop`

- src/engine/client/backend/vulkan/backend_vulkan.cpp
fixes #8912
Only tested by removing the `if`, since I don't have a pitch that isn't equal to the width
> Add another row to do the copying for presented images in when pitch is bigger than width

- src/base/detect.h
The macro `__ARM_ARCH` is defined both for 32-bit and 64-bit ARM so it cannot be used to identify ARM64. Now `__ARM_ARCH_ISA_A64` is used instead, which should only be defined for ARM64. This caused a warning due to the macro `CONF_ARCH_STRING` being redefined when compiling for Android. Furthermore, support for detecting big-endian ARM64 with the `__ARM_BIG_ENDIAN` macro is added.
See https://developer.arm.com/documentation/dui0774/g/chr1383660321827
> Fix redefinition of `CONF_ARCH_STRING` for ARM architectures

- src/engine/shared/console.cpp
- src/game/client/ui.cpp
> Use operator `!=` instead of `mem_comp` for colors

- src/engine/client/graphics_threaded.cpp
- src/engine/graphics.h
- src/game/editor/editor.cpp
- src/game/editor/mapitems/map_io.cpp
Convert mapres to RGBA immediately when loading them, so the image data is always in RGBA format internally, instead of only converting when the map is saved (which was erroneously removed in #8670).
This means the `cl_editor_dilate` setting will now also be applied to converted RGB images.
> Fix editor crash when saving maps with RGB mapres

- src/engine/shared/econ.cpp
Fixes a bug where econ was exposed publicly when `ec_bindaddr` was set to `localhost`. Also implements the original intention of 85f5e9c that is to disable econ if `ec_binaddr` is invalid.
I've tested the following values and they behave as expected now:
```
ec_bindaddr "localhost" # listens on ::1 on my system
ec_bindaddr "127.0.0.1"
ec_bindaddr "0.0.0.0"
ec_bindaddr "[::1]"
ec_bindaddr "[::]"
ec_bindaddr "nonsense" # prints error and disables econ
```
Explanation: The old code first parses `ec_bindaddr` using `net_host_lookup` which returns a `NETADDR` struct. Then it overwrites the `type` field of the `NETADDR` which was either `NETTYPE_IPV4` or `NETTYPE_IPV6` and sets it to `NETTYPE_ALL` (this is the problem). Later `net_tcp_create` interprets the same 16 bytes as ipv6 and ipv4 (only …
> Fixes a bug where econ was exposed publicly when ec_bindaddr was set to localhost

- src/engine/client/client.cpp
Avoid Vulkan crash if the backend is destroyed immediately after being created.
Slightly decreases time of initial black screen before loading menu is rendered.
> Initialize client networking before graphics

- src/game/client/components/menus_demo.cpp
- src/game/client/components/menus_ingame.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/components/menus_settings7.cpp
- src/game/client/components/menus_settings_assets.cpp
- src/game/client/ui.cpp
- src/game/client/ui.h
Reduce duplicate and inconsistent code for rendering quick search for the demo browser, ingame vote list, player flag, skin, skin 0.7 and asset search.
The quick search and exclude in the server browser are not refactored, as they have additional labels and different alignment, which would make a general function complicated.
> Extract `CUi::DoEditBox_Search` function for quick search

- src/engine/shared/config_variables.h
- src/game/client/gameclient.cpp
> Add client setting to restore old freeze stars

- src/game/client/components/menus.h
- src/game/client/components/menus_settings7.cpp
- src/game/client/components/skins7.cpp
- src/game/client/components/skins7.h
- Show Player/Dummy tabs at the top instead of using checkbox for dummy settings like in regular skin settings.
- Show Basic/Custom tabs instead of using button to toggle custom skin settings.
- Move Skin directory and Refresh icon buttons to right side like in regular skin settings. Refreshing 0.7 skins and parts is not implemented yet though.
- Render 0.7 skin entries like entries of the regular skin list, i.e. with more space and with only four skins per row.
- Move the Random skin button next to the Custom colors checkbox and make it an icon button like in the regular skin settings.
- Move skin preview to the right side of the Player/Dummy/Basic/Custom tabs to reduce unused empty space.
- Remove most overlapping and unnecessarily dark backgrounds.
- Improve layout of skin part tabs by …
> Rework 0.7 tee settings layout and code

- scripts/check_config_variables.py
- src/game/client/components/menus_settings7.cpp
- src/game/client/components/skins7.cpp
- src/game/client/components/skins7.h
The dummy 0.7 skin name was not being updated and used, causing the wrong skin to be selected when switching between player and dummy settings.
Unused config variables were not detected if they were the prefix of a longer config variable which is used.
> Fix dummy 0.7 tee skin name not being used, fix some unused config variables not being detected

- src/game/server/gamecontext.cpp
Previously the path was formatted like `%s/%s`, so if the directory is empty string, the map name would be `/ctf1.map`
Fixes #8909
> Don't add `/` if the directory is empty

- src/game/client/components/chat.cpp
- src/game/client/components/chat.h
- src/game/client/components/ghost.cpp
- src/game/client/components/menus_browser.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/components/players.cpp
- src/game/client/gameclient.cpp
- src/game/client/render.h
Avoid code to convert from `CTeeRenderInfo` to chat-internal representation and back to `CTeeRenderInfo`.
Add function to apply information of `CSkin` to a `CTeeRenderInfo` to reduce duplicate code.
> Store `CTeeRenderInfo` instead of members for chat lines, extract `CTeeRenderInfo::Apply(const CSkin *)` function

- src/game/client/components/statboard.cpp
Fixes #8927
Reverts the change done in this commit e2fde4d7303a1b935663ea094d40223ebe4c669a, which doesn't seem to be correct.
> Fix captures not being counted for certain names

- src/engine/server/databases/connection.h
- src/engine/server/databases/mysql.cpp
- src/engine/server/databases/sqlite.cpp
Comes in handy in my downstream project
The mysql docs state that setting the type to MYSQL_TYPE_NULL is enough there is no need to set is_null or anything else.
https://dev.mysql.com/doc/c-api/8.0/en/c-api-prepared-statement-data-structures.html
I tested the change in game with sqlite3 and mariadb. The NULL value was correctly written in both cases.
> Add BindNull to SQL api

- src/game/client/ui.cpp
Scrollbars are now also set as the hot item when the rail is hovered and the rail clicking function is now only enabled for the scrollbar that is the hot item.
Closes #8954.
> Fix scrollbar rail clicking being active while popups open

- src/game/client/components/hud.cpp
- src/game/client/components/hud.h
The way to reproduce this is have some speed and disconnect. After joining the tee will have old speed values.
Fixes #8814
> Fix colored speed values after connecting to a server

- src/game/client/components/binds.cpp
- src/game/client/gameclient.cpp
- src/game/editor/editor.cpp
Events with flag `FLAG_RELEASE` must always be forwarded to all components so keys being released can be handled in all components also after some components have been disabled.
Closes #8901.
> Fix composite binds that open chat, console or menus

- CMakeLists.txt
- src/engine/client/graphics_threaded.cpp
- src/engine/client/graphics_threaded.h
- src/engine/gfx/image.cpp
- src/engine/gfx/image_loader.cpp
- src/engine/gfx/image_loader.h
- src/engine/gfx/image_manipulation.cpp
- src/engine/gfx/image_manipulation.h
- src/engine/graphics.h
- src/engine/image.h
- src/game/client/components/mapimages.cpp
- src/game/client/components/menus.cpp
- src/game/client/components/menus_browser.cpp
- src/game/client/components/skins.cpp
- src/game/client/components/skins7.cpp
- src/game/editor/editor.cpp
- src/game/editor/mapitems/image.cpp
- src/game/editor/mapitems/image.h
- src/game/editor/mapitems/map_io.cpp
- src/game/editor/tileart.cpp
- src/tools/dilate.cpp
- src/tools/map_convert_07.cpp
- src/tools/map_create_pixelart.cpp
- src/tools/map_extract.cpp
- src/tools/map_replace_image.cpp
Move `CImageInfo` from `engine/graphics.h` to own file `engine/image.h`. Also add 2-component image format to `CImageInfo::EImageFormat` for completeness, to replace the separate `EImageFormat` in `image_loader.h` with `CImageInfo::EImageFormat`.
Move `SetPixelColor`/`GetPixelColor` functions from editor to `CImageInfo` as member functions.
Replace `IGraphics::CopyTextureBufferSub` and `IGraphics::CopyTextureFromTextureBufferSub` functions with more versatile `CImageInfo::CopyRectFrom` function.
Make `IGraphics::LoadSpriteTexture` function more efficient by avoiding a copy of the image data by using the `LoadTextureRawMove` function. Remove unnecessary delegate function `CGraphics_Threaded::LoadSpriteTextureImpl` and temporary buffer `m_vSpriteHelper`.
Move `CEditorImage::DataEquals` …
> Refactor image loading, saving and manipulation

- src/game/server/ddracecommands.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
Seems a bit inconvenient that you would need to restart the server or `reload` to apply changes.
> Add `reload_censorlist` to reread `censorlist.txt`

- src/game/client/components/chat.cpp
https://github.com/user-attachments/assets/48686450-79a1-4e5a-a59d-7d5fd402e37b
> Add autocompletion hint for chat commands

- src/game/server/scoreworker.cpp
- src/test/score.cpp
It was mainly the `/times` one that looked out of place but I slightly changed the other ones as well.
Before:
After:
> Better alignment of upper and lower separators

- src/game/client/sixup_translate_game.cpp
Closed https://github.com/ddnet-insta/ddnet-insta/issues/127
> Fix 0.7 client flag sounds being duplicated when dummy is connected

- CMakeLists.txt
- data/autoexec_server.cfg
- src/engine/server.h
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/engine/shared/config_variables.h
- src/game/server/ddracecommands.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- Add `reload_announcement`  to reread the announcements file
- Add Conchain for `sv_announcement_filename`
- Improve the grammar of the config description, use 120 minutes as default interval instead of 300.
- Ship an empty `annoucement.txt`
- Print an error if it fails to read the file
- Fix bug where the first displayed announcement will never be line one
Closes #8970
> Various improvements to announcements

- src/game/client/components/menus.h
- src/game/client/components/menus_settings.cpp
- src/game/client/components/skins.cpp
- src/game/client/components/skins.h
This function is independent from the menus and this also makes it consistent with the `CSkins7::RandomizeSkin` function.
> Move `CMenus::RandomSkin` function to `CSkins::RandomizeSkin`

- src/game/editor/editor.cpp
> Editor: allow non-conflicting keybinds while line input is active

- src/engine/client/serverbrowser.cpp
Actually moving to those new paths shouldn't be done until we get a breaking change of this JSON, as it would otherwise unnecessarily break old clients.
Once a new endpoint is created, the backward compatibility can be removed.
> info: "finishes" shouldn't be under "icon" either

- src/game/client/components/menus_browser.cpp
Add colors to the following gametypes:
LMS, LTS -> Same as vanilla
gCTF gDM etc -> Red as instagib
FreeZe/iFreeze -> Red as instagib
Other vanilla mods (CTF*, CTF+ etc) -> Dark green
> Add more gametype colors

- src/engine/shared/config_variables.h
- src/game/client/components/spectator.cpp
Closes #8590 
Left-click to spectate the closest player, right-click for free-view. When spectating a player, left-clicking again will switch to the closest player who is not currently being spectated
https://github.com/user-attachments/assets/ecc91ce2-8716-4014-b9a4-1f18812780d7
> Add mouse click functionality in spectator mode

- src/engine/client/discord.cpp
Closed #8440
ddnet-libs already has a mac arm64 discord library and it is even included in main releases but it was not being used
> Enable mac arm64 Discord RPC

- src/game/client/components/players.cpp
- src/game/client/render.cpp
- src/game/client/render.h
The `sx` and `sy` parameters are unnecessary, as they are always set to zero.
The checks in the `SelectSprite` functions are changed to assertions, as passing a wrong sprite ID is a programming error.
> Remove unused parameters of `SelectSprite` functions

- src/game/client/components/menus_browser.cpp
Brings DM+ closer to DM instead of using a dark green.
> Change color of non standard vanilla gametypes

- src/game/editor/prompt.cpp
- src/game/editor/quick_action.h
Add separate UI element IDs for the quick action buttons in the prompt dialog, to ensure that the UI element IDs are different from the IDs used for the regular menu buttons. Otherwise, some buttons could not be activated with clicks because the menu button with the same ID was rendered first.
Closes #8998.
> Fix some editor quick actions not being clickable, small refactoring

- src/engine/shared/config.cpp
> Fix `toggle` command always setting value to `1`

- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/mapitems/map_io.cpp
- src/game/editor/popups.cpp
> Fix editor crashes when images/sounds cannot be loaded, fix editor crashes with external RGB images

- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/popups.cpp
- src/game/editor/quick_actions.cpp
- src/game/editor/quick_actions.h
I am not too sure about this one. This would be the first destructive quick action. Meaning one little typo or miss scroll could delete an entire layer by accident. The way the prompt is designed to be used this can happen way more likely than clicking the delete button. I am not sure how mature the undo feature is. Is it stable? Is it on by default? If we can rely on the undo feature to avoid data loss then this should be fine.
The other option would be introducing a "are you sure?" popup but that would then be in the way of "batch deletion"
https://github.com/user-attachments/assets/054766d5-7166-4d6c-87a1-0ff7e836dc74
> Add quick action "Delete layer"

- src/game/editor/editor.cpp
- src/game/editor/popups.cpp
Add quad popup button for centering the pivot of a quad. Ported from vanilla, https://github.com/teeworlds/teeworlds/pull/970/commits/082f8767862e0811bd953c3c6ad8dc07cab05eff.
https://github.com/user-attachments/assets/dc46b2ff-91e7-4f99-897f-f8e3ae74b664
> Add "center pivot" for quads

- scripts/android/files/java/org/ddnet/client/NativeMain.java
- scripts/android/files/res/values/strings.xml
- scripts/android/files/res/xml/shortcuts.xml
- src/engine/shared/config_variables.h
As Vulkan crashes immediately on launch on a lot of Android devices (for around 15% of users that commented on the Android beta on Discord).
The previous usage of the OpenGL backend in the shortcuts was incorrect, as this backend is not strictly available on Android and the GLES backend should be used instead, as this is also what is displayed in the graphics settings.
> Use OpenGL ES graphics backend per default on Android

- src/game/client/components/nameplates.cpp
Previously with cl_show_others_alpha 20:
Updated:
> Make cl_show_direction change alpha with cl_show_others_alpha

- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
The code isn't needed any more as the zoom is always reset on render on mods that don't allow zoom.
https://github.com/user-attachments/assets/9004790b-ddb3-45eb-87c8-78cfa48c3f1b
> Don't reset zoom on team switch

- src/game/client/components/menus.h
- src/game/client/components/menus_browser.cpp
Similarly to the Player tab ingame, you can hover your mouse over tees in the severinfo and friendslist to see the skin they're using.
> Show skin name as tooltip in friendlist and serverinfo

- src/game/server/score.cpp
- src/game/server/scoreworker.cpp
- src/game/server/scoreworker.h
- src/test/score.cpp
There are two interfaces for score worker data:
There is ``ISqlResult`` and every class inheriting from it should have the suffix ``Result``
Then there is ``ISqlData`` and every class inheriting from it should have the suffix ``Data`` if it is data that should be written in an INSERT statement. Or ``Request`` if it is used to perform a read operation and will be used in a SELECT statament.
The convention was mostly established alreay. In this commit the last three classes that broke this convention got fixed.
> Cleanup sql worker request/result naming convention

- src/engine/shared/config_variables.h
- src/game/client/components/camera.cpp
- src/game/client/components/camera.h
Closes #2513 
The camera is only smooth in spectator mode. It snaps back to the player when exiting spectator mode to avoid affecting gameplay.
https://github.com/user-attachments/assets/feb1e45c-5e0e-4af4-a4ad-f7cf113e0fee
> Add smooth spectating

- src/game/editor/editor.cpp
Right-clicking on the eye icon will toggle that layer/group visible and rest invisible. Shift + right-click will do the same but will also select that layer. Left-click stays the same as before
https://github.com/user-attachments/assets/df92ad21-4eb6-4c26-a953-5d4a8f6cdec9
> Add right-click to solo editor layer

- src/game/server/entities/character.cpp
Currently `sv_rescue_delay` doesnt seem to have the intended effect. The description states that it should set the "Number of seconds between two rescues". However, it only restricts rescue x seconds after spawning.
This seems to be the case because #2242 removed the line for updating `m_LastRescue`, which i believe was not intended.
This PR reintroduces this line. I tested the change ingame. Now the server option does what you'd expect: Restricting rescue usage for x seconds after each rescue.
> Add actually setting `m_LastRescue` variable

- src/game/client/components/menus_browser.cpp
Spaces are more portable if alignment matters
> Fix tabs being used in ascii art browser comment

- src/game/editor/editor.cpp
Happened when you started the rotation above the quad.
> Fix context menu showing up after canceling quad rotation

- src/game/server/player.cpp
It is compared to 0 in gamecontext.cpp but it is never explicitly set to 0.
```C++
if(pPlayer->GetTeam() == pMsg->m_Team || (g_Config.m_SvSpamprotection && pPlayer->m_LastSetTeam && pPlayer->m_LastSetTeam + Server()->TickSpeed() * g_Config.m_SvTeamChangeDelay > Server()->Tick()))
return;
```
> Explicitly set m_LastSetTeam to zero

- src/game/client/components/maplayers.cpp
Closes #8124
Now both in-game and in the editor, the number is at the top and the delay is at the bottom
> Fix switch overlay text order

- src/engine/client/backend/vulkan/backend_vulkan.cpp
fixes #8680
Fixes the missing text issue by simply add a minimal deny logic
> Block AMD drivers from after 19.12.1 & before 22.4.1

- src/game/client/components/mapsounds.cpp
- src/game/client/components/mapsounds.h
- src/game/client/gameclient.cpp
The whole idea behind custom sounds was to use them as replacement for built-in sounds (depending on the gameplay). We have to use the same channels instead of the MAP (aka 'ambient') channel to have the same volume for both sets of messages.
I see it is weird to use something different from `CSounds::CHN_MAPSOUND` in `CMapSounds`. Another solution would be a big refactor of the sounds (probably merging of `CSounds` and `CMapSounds`).
Otherwise we have situation of **players reporting 'no sound' because they have `snd_ambient_volume 0` in the configs**.
- `NETMSGTYPE_SV_MAPSOUNDGLOBAL` is `NETMSGTYPE_SV_SOUNDGLOBAL` which uses map assets as the sounds container. Use the same `CSounds::CHN_GLOBAL` to make the sound messages equivalent.
- `NETEVENTTYPE_MAPSOUNDWORLD` is …
> Use CHN_WORLD for MAPSOUNDWORLD and CHN_GLOBAL for MAPSOUNDGLOBAL

- src/engine/client/backend/vulkan/backend_vulkan.cpp
I doubt it's useful to notify the user that vulkan creation failed, because no capable GPU was found. This also isn't an edge case (e.g. if a GPU only supports vulkan 1.0), like the other warnings we emit.
> Don't emit a warning if no capable vulkan GPU was found

- src/engine/shared/datafile.cpp
- src/tools/dummy_map.cpp
When the datafile is closed, only the `CDataFileReader::Open` and `CDataFileReader::Close` functions may be called. All other functions will now assert instead of returning some default-values if no file is open. The `CDataFileReader::Open` function will now assert if the file is already open instead of implicitly closing the previous one.
> Add assertions to `CDataFileReader` checking if file open/closed

- memcheck.supp
This now shows 0 errors or warnings:
```
valgrind --tool=memcheck --gen-suppressions=all --suppressions=../memcheck.supp --leak-check=full --show-leak-kinds=all ./DDNet-Server
```
Closed #8943
> Whitelist logger valgrind errors

- src/game/server/ddracechat.cpp
Provide help message to `/(un)endless` and such commands that are not registered as rcon command but only chat command. Also improved message readability when invalid argument is provided.
> Fix /help not printing help for several chat commands

- src/engine/serverbrowser.h
- src/engine/shared/protocol.h
- src/engine/shared/serverinfo.h
- src/game/client/components/ghost.cpp
- src/game/client/components/menus.h
- src/game/client/components/skins.cpp
- src/game/client/components/skins.h
- src/game/client/gameclient.h
- src/game/client/skin.h
- src/game/server/teeinfo.h
Add constant to replace the magic number `24` used for the size of skin names. Skin names in the server info/browser were sized `24 + 1` but the additional byte was unnecessary.
> Add `MAX_SKIN_LENGTH` constant

- src/engine/shared/console.cpp
> Fix color validation in some commands

- src/game/client/components/console.cpp
This makes it behave as you would expect from other programs.
- `ctrl+f` to start search
- `esc` to cancel search
- dont clear last searched string
> Adjust console search behaviour

- src/engine/server/server.cpp
> Fix `CFGFLAG_STORE` commands not getting stored when executed from reset file

- src/engine/server/databases/mysql.cpp
If the sql statement does not contain placeholders ``NumParameters`` can be empty.
In that case accessing the first element will cause an asan error:
```
runtime error: reference binding to null pointer of type 'st_mysql_bind'
```
> Fix empty vector element access in mysql prepare

- src/engine/server/databases/mysql.cpp
Fixes https://clang.llvm.org/extra/clang-tidy/checks/readability/container-data-pointer.html
> Use .data() in mysql code for better readability

- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/mapitems/layer_tele.cpp
- src/game/editor/mapitems/layer_tele.h
- src/game/editor/mapitems/layer_tiles.cpp
- src/game/editor/popups.cpp
Closes #7896
Now, each teleport number is separate. I also fixed inconsistencies with the number when switching it in the Tele popup. The number next to the brush now always matches the one being placed
> Change editor teleport number behavior

- src/game/client/components/menus_settings.cpp
- src/game/client/render.h
- src/game/client/render_map.cpp
> Render hookable and unhookable tiles for hook collision preview

- src/game/client/components/ghost.cpp
- src/game/client/components/menus_browser.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/components/players.cpp
- src/game/client/gameclient.cpp
- src/game/client/render.h
- Add `CTeeRenderInfo::ApplyColors` function to reduce duplicate code.
- Use `CTeeRenderInfo::Apply` function in more cases.
- Use `CSkins::Find` function instead of implementing default skin handling manually with the `FindOrNullptr` function for chat settings preview.
- Remove redundant initialization of `CTeeRenderInfo::m_CustomColoredSkin` member.
- Replace empty client skin with `default` instead of checking for empty skin names later.
- Remove unnecessary check for empty skin name for ghost rendering. The `CSkins::Find` function will return the default skin for an empty skin name, which is more correct than invalidating the ghost skin render info.
> Refactor `CTeeRenderInfo` usage

- src/game/server/entities/character.cpp
It wasn't a problem before because it didn't work, but now that #9058 fixed it. The delay should be excluded from practice.
> Don't check `sv_rescue_delay` in practice

- scripts/android/cmake_android.sh
The argument `x64` is an alias for `x86_64` but the name of the build folder always contains `x86_64`, so the `data` folder and certificate were not being found when using the `x64` argument, unless another architecture was previously built.
> Fix Android build when first building `x64` architecture

- src/engine/shared/config.cpp
There’s no reason why `toggle` has arguments coded as integers when it can accept any type, as it has internal validation. This restores how the command worked before 18.6 by fixing cases where colors or strings without quotes were incorrectly detected as integers
Similar to #8897
> Fix toggle arg validation

- src/engine/shared/http.cpp
- src/engine/shared/http.h
Use a condition variable instead of busy waiting until HTTP requests are done.
Also set the state `EHttpState::RUNNING` which was previously unused.
Closes #7811.
> Avoid busy waiting in `CHttpRequest::Wait` function

- src/game/client/components/maplayers.cpp
- src/game/client/components/maplayers.h
- src/game/client/components/menus_demo.cpp
The additional code to evaluate envelopes during demo playback is obsolete, as client ticks are already properly synchronized with the demo playback.
From teeworlds/teeworlds#2750 and teeworlds/teeworlds#2768.
> Cleanup envelope updating during demo playback

- src/engine/shared/http.cpp
- src/engine/shared/http.h
- src/engine/shared/storage.cpp
- src/engine/storage.h
- src/game/client/components/menus_settings.cpp
- src/game/client/components/skins.cpp
- src/game/client/components/skins.h
- src/game/client/gameclient.cpp
Previously, skins not found in the `skins` folder were downloaded from the configured URL and saved to the `downloadedskins` folder, but the saved files were never used, leading to wasted downloads and write operations.
Now, if a skin to be downloaded already exists in the `downloadedskins` folder, the modified time of the skin file is determined and included in the HTTP GET request as `If-Modified-Since` header. If the file was not modified on the server since that time, the server will answer with status 304 Not Modified and an empty response body, in which case the existing skin file is loaded. If the skin file was modified, then it will be downloaded like usual. The download will also be retried without including the `If-Modified-Since` header, if the local file is more recent but it …
> Improve skin downloading: load from `downloadedskins` if possible

- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/popups.cpp
Show popup to select the envelope curve type from a list when right clicking the curve type button, as selecting the curve type by pressing the button multiple times is inconvenient.
Switch to previous curve type on shift+left clicking the curve type button.
> Add popup to select envelope curve type, support shift+left click

- src/engine/client.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/game/client/components/ghost.cpp
- src/game/client/components/ghost.h
- src/game/client/components/menus.cpp
- src/game/client/components/menus_browser.cpp
- src/game/client/components/menus_ingame.cpp
- src/game/client/components/menus_start.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
Store and update the last race tick directly in `CGameClient` instead of in `CGhost`, as the value is also used in the gameclient.
Move current race time calculation from `CClient` to `CGameClient`, as this function is not used in the engine and this allows removing unnecessary virtual functions.
Closes #1720.
> Move last race tick and current race time handling to `CGameClient`

- src/game/client/components/menus.h
- src/game/client/components/menus_settings.cpp
Scroll to reveal the selected skin when entering a skin name and when switching between the player and dummy tabs.
> Scroll to selected skin when entering name and switching tabs

- src/engine/client/backend/vulkan/backend_vulkan.cpp
Reported by meep on discord. He apparently uses a driver from around 2020 that also worked without problems.
Not tested/confirmed by me
> Don't block drivers before & equal to 2.0.137.

- src/game/server/scoreworker.cpp
It was possible for the race record to be saved at the very last millisecond, causing the timerace to have a different timestamp. Now, the query matches the one from the website: https://github.com/ddnet/ddnet-scripts/blob/182df7c68408f3af443852429720133692c623d6/servers/scripts/maps.py#L37
Tested with many maps on https://db.ddstats.org/ It was rarely off by 1-3 records, likely because the database isn't up to date. It would be best if someone could check with the updated database.
> Fix top5team sql

- src/game/client/components/mapimages.cpp
- src/game/client/components/menus_settings_assets.cpp
It's not necessary to create a new `CTextureHandle` object after unloading the handle and it's also not necessary to check if the texture handle is valid when unloading it.
> Avoid redundant overwriting of texture handles after unloading

- src/engine/console.h
- src/engine/server/server.cpp
- src/engine/shared/console.cpp
- src/engine/shared/console.h
The `IConsole::Format` function was previously used to format the log and rcon output, but it has become obsolete when the logging was refactored.
The function was still being used to format the output of the `show_ips` command in the rcon, which was causing this particular rcon line to have the old log format (e.g. `[12:34:56][server]: Value: 0`). Now, `IConsole::Print` is used directly, as this causes the output to be sent with the correct format and only to the rcon command user.
The `IConsole::FPrintCallback` function pointer typedef is also obsolete and unused.
> Remove obsolete `IConsole::Format` function, fix `show_ips` output

- src/base/system.cpp
Use the flag `MOVEFILE_WRITE_THROUGH` with the `MoveFileExW` function on Windows to ensure that the file is renamed/moved on the disk before the function returns. Otherwise, if the function returns before the file is moved, subsequent loading of the file with this name may fail sporadically.
See https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-movefileexw
> Ensure file is moved when `fs_rename` function returns on Windows

- src/base/log.h
- src/engine/console.h
Add `log_error_color`, `log_warn_color`, `log_info_color`, `log_debug_color` and `log_trace_color` macros to wrap `log_log_color` function with specific log levels.
Add comment to mark the `IConsole::Print` function as deprecated in favor of the `log_*` functions, which should be preferred for the following reasons:
- They support `printf`-formatting without a separate buffer.
- They support all five log levels.
- They do not require a pointer to `IConsole` to be used.
- Consistency of logging code.
> Add `log_*_color` macros, deprecate `IConsole::Print`

- src/mastersrv/src/addr.rs
- src/mastersrv/src/main.rs
This allows DDPer to continue using our mastersrv while not showing up in the DDNet client.
> mastersrv: Add DDPer support

- src/game/client/gameclient.cpp
On the current master everything looks good in game. But demos with vanilla tuned weapons are broken.
ddrace demos displayed the tunings correctly.
https://github.com/user-attachments/assets/fc8572b1-d02e-4514-84b6-e5a1dc6b4238
vanilla demos had a broken shotgun.
https://github.com/user-attachments/assets/d4cda237-b0bf-407f-8f8a-b98c338d4331
ddrace demos still work fine. And in game as well. Tested with ``cl_antiping 0`` and ``cl_antiping 1`` with tune zones and crazy shotgun.
https://github.com/user-attachments/assets/2eb966ff-ed99-451a-83c1-745afb98f81a
and vanilla shotgun is fixed in demos now.
https://github.com/user-attachments/assets/e8c6fdcd-1698-4110-9d7d-da86a0135af5
> Fix vanilla demo tuning

- src/engine/console.h
- src/engine/shared/console.cpp
- src/engine/shared/console.h
Simplify the code by replacing the usage of a linked list and heap with an `std::vector`.
The assignment operators are replaced with copy constructors to use `std::vector`.
> Use `std::vector` for console execution queue, fix console result client ID sometimes being uninitialized

- src/engine/client/ghost.cpp
- src/engine/client/ghost.h
- src/engine/ghost.h
- src/game/client/components/ghost.cpp
Fix out-of-bounds reads in ghost loader when current chunk does not contain enough data for expected number of items.
Improve validation of ghost header information. Ensure strings (owner and map name) are null-terminated and valid UTF-8 to avoid crashes. Avoid duplicate code for validating header.
Remove `static` buffers for compression and decompression of ghost data, which would prevent parallelizing ghost recording and loading. Switch between the main buffer and only one temporary buffer instead of using two temporary buffers.
Automatically delete the ghost file when the recording is stopped with the number of ticks or time being invalid, i.e. when ghost recording will be restarted. This should ensure that invalid ghost files are not left behind if recording is not immediately …
> Improve ghost file validation

- src/game/editor/editor.cpp
- src/game/editor/mapitems/layer_tele.cpp
- src/game/editor/mapitems/layer_tiles.cpp
Fixed inconsistencies between the number displayed next to the brush and the placed number. It now always matches the brush. Also, now it'll show a number when selecting a brush from the tile picker instead of no number at all - only visual
> Fix editor tele layer brush number

- src/game/client/components/chat.cpp
- src/game/client/components/chat.h
Add a command to clear all lines of chat messages, same as the `clear_local_console`/`clear_remote_console` commands for the consoles. This is useful for example when taking screenshots or recording videos with initially empty chat.
> Add `clear_chat` command

- src/engine/client/text.cpp
- src/engine/textrender.h
- src/game/client/gameclient.cpp
Log more detailed error messages when fonts could not be loaded and when the font index is malformed. Show warning popup on client launch if any font failed to load, although this warning won't be readable if all fonts failed to be loaded.
> Improve error handling on invalid fonts and font index

- src/game/client/components/menus_settings.cpp
The maximum value of the config variable is only `20`. Regression from #9138.
> Fix upper bound of hook collision line width scrollbar

- src/game/client/ui.cpp
- src/game/client/ui.h
Pass the popup menu positions and sizes as `float`s instead of truncating them to `int`s.
> Fix alignment of dropdown popup menu with some button widths

- src/game/client/components/binds.cpp
People seem to be always confused whenever the map supports going invisible on /spec and I've seen multiple times people asking about it on the discord server, as it's not explained anywhere. /spec and /pause work the same, and the P key is already bound to /pause. This changes the default bind, so it will mostly affect fresh installs - new players
> Change default Q bind to /spec

- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
The change info message was being resent too fast/slow because `m_aCheckInfo` was decremented every frame whereas it was intended to be decremented every tick. As `m_aCheckInfo` is set to `Client()->GameTickSpeed()` after sending the info, it's likely that this was intended as one second delay. With debug messages is can be confirmed that the change info message was previously resent more than 10 times per second with high FPS on a local server.
Also fix the info resending delay not being reset when reconnecting a dummy on 0.7 servers.
> Fix player info being resent too fast/slow depending on FPS

- src/game/client/components/menus_settings7.cpp
- src/game/client/components/skins7.cpp
- src/game/client/components/skins7.h
- src/game/client/sixup_translate_game.cpp
- Combine `CSkins7::FindSkinPart` and `CSkins7::GetSkinPart` functions into `CSkins7::FindSkinPart` function to simplify the usage.
- Replace `CSkins7::Num` and `CSkins7::Get` functions with `CSkins7::GetSkins` function to return all skins to improve readability using for-each loops.
- Replace `CSkins7::NumSkinPart` and `CSkins7::GetSkinPart` functions with `CSkins7::GetSkinParts` function to return all skin parts to improve readability using for-each loops.
- Add `CSkins7::FindSkinPartOrNullptr` function to find a skin by name or return `nullptr` if it's not found. Let the `CSkins7::FindSkinPart` function return the desired part, then the default part, and lastly the placeholder part.
- Add `CSkins7::FindDefaultSkinPart` function to find the default skin part or placeholder skin part …
> Refactor `CSkins7` accessor functions and 0.7 skin json parsing

- src/engine/shared/netban.cpp
- src/engine/shared/netban.h
This rcon command simplifies searching for all ban records for a specific IP if the ban list has too many records.
The motivation behind comes from Blockworlds as we have around 900 ban records and searching for a ban record without having access to the bans.cfg can be quite annoying.
I guess the way to search for records and print the index can be optimized but didn't find how for now. I'm open to suggestions.
The corresponding issue for this pull request is #9202.
> Implement bans_find command.

- src/game/client/components/mapsounds.cpp
- src/game/client/components/mapsounds.h
- Add check for map sound data being loaded from map to avoid null pointer access.
- Add check for size of sound source data to avoid out-of-bounds reads.
- Avoid iterating over all groups and layers and then performing a linear search on the sound queue entries every frame to update the sounds. Instead, store a pointer to the respective `CMapItemGroup` for every queue entry, so iterating over the queue once is enough to update all sound queue entries.
- Move check for sound layer index outside of loop as the value does not change.
- Avoid creating source queue entries for sounds that could not be loaded.
- Mark pointers as `const` when possible.
> Improve map sound validation and performance

- src/game/client/components/mapimages.cpp
- src/game/client/components/mapimages.h
- src/game/client/components/maplayers.cpp
- Add check for map image data being loaded from map to avoid null pointer access.
- Add check for size of map image data to avoid out-of-bounds reads.
- Add check for map layer item not being found to avoid null pointer access.
- Fix inconsistent handling of layers with invalid images. In some cases only `-1` was considered non-textured whereas all invalid values should be.
- Ensure correct texture is always used for game layers instead of considering the image property of game layers which cannot be set via the map editor.
- Skip loading images which are not used by any quads or tiles layers.
- Replace member variable `m_aTextureUsedByTileOrQuadLayerFlag` with local variable.
- Mark pointers as `const` when possible.
- Avoid C-style casts.
> Improve map image validation

- src/game/client/gameclient.cpp
Fixed a bug where entering a different tune zone would incorrectly apply the current zone's settings to tune zone 0, causing prediction issues for players in other zones (red weapon color in the video)
Bug introduced in 386d456484350a14f6c01a0773e05ed4ed9a4693 with this fix vanilla demos work fine as well
https://github.com/user-attachments/assets/84f8c87f-f2f5-4951-a5a2-eb4b1afbe230
> Fix invalid prediction tuning in tune zone 0

- src/game/client/components/background.cpp
- src/game/client/components/menu_background.cpp
Load the map images for the menu and entities background maps before the respective map layers. Otherwise, the total number of images is `0` when loading the layers, which causes the images of tiles and quads layers to be considered invalid during the initialization, which results in the wrong tile/quad memory layout being used.
Regression from #9213.
> Fix incorrect rendering of menu and entities background maps

- src/engine/server/databases/connection_pool.cpp
- src/engine/shared/config_variables.h
The default option is on. So nothing in the logging output changes. But users now have the option to set ``dbg_sql 0`` which hides all the sql logging unless there is an error.
> Add ``dbg_sql`` config to hide non error sql logs

- src/game/editor/editor.cpp
The confirmation popup was not shown for the Save As dialog anymore, due to the label being changed to `Save As` for the respective quick action. This check based on string comparison is rather brittle and can be replaced with comparison of the storage type with `IStorage::TYPE_SAVE`.
When the file dialog is used to open files, prevent opening files with an empty filename if enter is pressed while no file is selected (i.e. when the filter excludes all entries).
> Fix editor `Save As` confirmation, prevent opening empty filename

- scripts/integration_test.sh
Fixes running tests locally with custom sqliterc such as
.mode table
Which would create a different output format for the select statements
> Ignore ~/.sqliterc in integration tests

- src/engine/shared/packer.h
- src/game/server/teehistorian.cpp
- src/test/teehistorian.cpp
Save/Load code are up to 65536 bytes long. However, Packer only has a buffer of 2048 bytes. Writing SAVE_SUCCESS and LOAD_SUCCESS chunks likely for saves with 3 or more tees.
This increases the buffer size for all packing including networking packets and is therefore probably not the optimal solution. An alternative would be to create an additional packer CLargePacker or make the size a template argument.
The suggested change is the simplest fix adding not much complexity, but increases the chance of ~~stack overflows~~. I'm open to take another approach. (edit: Not stack overflows, but reaching the max stack size?)
> Fix incomplete Teehistorian chunks being written

- cmake/FindMySQL.cmake
i forgot to remove the test ENV variables i didnt intend to push - i also added a small comment to explain the usecase for explicitly looking through the /nix/store. Thanks for noticing @heinrich5991
i didnt find a proper upstream issue about pkg-config not finding mysql on nixOS, so i'll keep digging
(also sorry for the messup there)
> Remove ENV-vars from FindMySQL.cmake

- src/game/editor/popups.cpp
Previously if you were to set an envelope point time or bezier in-tangent, the popup would go insano style and set it 1000x
Fixes #8615
> Fix envelope point popup

- src/game/client/components/maplayers.cpp
- src/game/client/components/maplayers.h
Use width and height of `STileLayerVisuals` instead of passing `CMapItemLayerTilemap *` separately.
Remove unused `CMapItemGroup *` parameters.
> Remove unused parameters of `CMapLayers` functions

- src/engine/shared/datafile.cpp
- src/engine/shared/datafile.h
Use an `std::map` to sparsely store only the used `CItemTypeInfo`s on the heap instead of using an `std::array` to store all 65536 entries (`MAX_ITEM_TYPES`) on the stack. This reduces the (stack) memory usage of `CDataFileWriter`s from 786512 to 128 bytes.
> Substantially reduce stack memory usage of `CDataFileWriter`

- src/engine/client/text.cpp
Previously, when rendering text with a maximum width that is too small for a single glyph then the text rendering would loop indefinitely trying to advance the cursor to the next line where the glyph will also not fit.
> Fix client hanging when rendering text with small maximum width

- src/engine/client/client.cpp
Do not reset the local time after the dummy is connected, as the local time is supposed to run continuously while on the same server. Resetting the local time caused damage indicators to become stuck, as the `s_LastLocalTime` value is in the future after resetting the local time. This also affected other effects like pickup location and bullet rotation, where this was not noticeable.
Closes #4967.
> Fix damage indicators being stuck after connecting dummy

- src/engine/client/ghost.cpp
- src/engine/client/ghost.h
Use `uint32_t` consistently instead of `int32_t` for the ghost data to ensure integer wrapping in the ghost-specific `DiffItem`/`UndiffItem` functions. Same as 65cb2ed7de102f155cde64b4e75839d15b6fe35a but only using `uint32_t` pointers consistently instead of casting specifically for the addition/subtraction simplifies the code.
> Ensure integer wrapping for ghost data to prevent over/underflow

- src/engine/server.h
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/game/server/gamecontext.cpp
- src/game/server/player.cpp
The variable `CServer::CClient::m_Authed` and the function `IServer::GetAuthedState` may only be used when the client slot is not empty, as the authed state is uninitialized before a client slot has been used for the first time. When compiling the server with MSVC the variable is not zero-initialized like with other compilers currently. This was causing the server compiled with MSVC to crash on start when Teehistorian is enabled, as empty clients were incorrectly considered as authenticated for recording the initial auth state to the Teehistorian file. For these uninitialized clients, the `IServer::GetAuthName` function was returning `nullptr` which was then causing the `CPacker::AddString` function to crash when trying to pack the `nullptr` string.
Add check to only record the initial …
> Fix Teehistorian server crash with MSVC due to uninitialized memory

- src/engine/client/client.cpp
- src/engine/client/client.h
Use separate graphs for the main and dummy gametimes to prevent the graph from using an incorrect time scale due to values for both main and dummy connection being added to it.
> Fix gametime debug graph when dummy is connected

- src/engine/client/client.cpp
`Con_DemoSpeed` already reads float value. I couldn't think of a good reason for the command to be limited to integers. Enables ultra-slowmo that are lower than 0.1x speed which is the lowest the UI gives.
> Allow decimal value for demo_speed command

- src/engine/shared/packer.cpp
- src/engine/shared/packer.h
- src/game/server/teehistorian.cpp
- src/test/packer.cpp
Revert buffer size for regular `CPacker` to 2 KiB to avoid stack overflows on systems with only 1 MiB of stack memory (e.g. Windows with MSVC and Android).
Add separate `CTeehistorianPacker` with a larger buffer to be used only for Teehistorian chunks.
To avoid duplicate code the existing `CPacker` is renamed to `CAbstractPacker` and the buffer and its size are supplied by the concrete subclasses `CPacker` and `CTeehistorianPacker`.
CC #9226.
> Use separate packer with larger buffer only for Teehistorian

- src/mastersrv/src/main.rs
If possible, I would like the increase in the size of the accepted content to be added as soon as possible, as I don't know when #9274 will be merged. Closes issue #9266.
> Increase register content limit to 32 KiB

- src/engine/server.h
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/game/server/ddracecommands.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
Move `reload_announcement` command handling from `CGameContext` to `CServer`. This is consistent with the conchain for `sv_announcement_filename` also being registered in `CServer`. Furthermore, this allows making the `ReadAnnouncementsFile` function non-`virtual` as it does not need to be exposed to the gameserver anymore.
Remove unnecessary filename argument of `ReadAnnouncementsFile` function, which is always set to the config variable.
Log number of loaded announcements on success. Use error log level on error.
> Minor refactoring of server announcement loading

- src/game/client/components/camera.cpp
- src/game/client/components/camera.h
- src/game/client/components/controls.cpp
- src/game/client/gameclient.cpp
DDNet's zoom made smooth dyncam (which was only made for default zoom value) very hard to use due to the cursor drifting unpredictably.
This PR addresses that by fixing the cursor in world place by doing some calculation when setting `CControls::m_aTargetPos`.
This requires a bit refactoring and now `CControls` has a coupling with `CCamera`.
I'm pretty sure this *only* affect control when using Smooth Dyncam AND Zoom at the same time, which is provable:
> The only terms added to `CControls::m_aTargetPos`  is `- DyncamOffsetDelta + DyncamOffsetDelta / Zoom` 
> 1. If Smooth Dyncam is off (with either normal Dyncam or no Dyncam) `DyncamOffsetDelta` will be 0.
> 2. If Zoom is default, the value `Zoom` is 1.
> 3. If either 1 OR 2 is true, the terms results in 0.
Video comparisons:
* Before: …
> Fix cursor drifting when using smooth dyncam and zoom at the same time

- src/game/client/lineinput.cpp
For example when pasting multiple lines of text containing Windows line endings, the `\r` characters were not being removed from lines except the first one.
> Fix clipboard not being sanitized when pasting multiple lines

- scripts/android/cmake_android.sh
Every build itself already uses all cores. By running 4 builds at once my system gets overloaded and goes OoM
> android build: Don't parallelize twice

- src/game/client/components/spectator.cpp
- src/game/client/gameclient.cpp
Simple change, prevents multi-view auto selecting yourself in game too.
This eliminates all possibilities of a player accidentally spectating themselves (without using console) during a pause and become confused wondering why they can't move the camera after pausing.
If someone **really** *really* want to spectate themselves for some reason, `spectate` and `spectate_multiview` still works on yourself, and of course modded server can just send a SpectatorId to force it.
Note that left-clicking on yourself in freeview is already disabled previously.
> Remove self from spectator menu unless in demo

- CMakeLists.txt
- data/touch_controls.json
- src/engine/client/input.cpp
- src/engine/client/input.h
- src/engine/input.h
- src/engine/shared/config_variables.h
- src/game/client/component.h
- src/game/client/components/controls.h
- src/game/client/components/menus.h
- src/game/client/components/menus_ingame.cpp
- src/game/client/components/touch_controls.cpp
- src/game/client/components/touch_controls.h
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
Add new client component `CTouchControls` for playing the game with touch inputs. The touch controls can be enabled/disabled with the config variable `cl_touch_controls`, which defaults to `1` on Android and `0` on other platforms. The touch controls consist of various on-screen touch buttons. The different buttons are only shown when they are usable depending on the context. The touch button configuration is stored in `touch_controls.json`. Closes #8359.
Default touch button configuration
----------------------------------
Movement buttons for left, right and jump actions are arranged in a `⊥`-pattern similar to WASD controls.
For the fire and hook action, two modes are implemented:
1. Direct touch input: the mouse is moved exactly where the player touches on the screen.
2. Virtual …
> Add ingame touch controls

- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_settings.cpp
- src/game/client/components/menus_settings7.cpp
- src/game/client/components/skins7.cpp
- src/game/client/components/skins7.h
The skin list in the menus was initially empty because `s_SkinLastRefreshTime` is initialized to the current refresh time, which prevents the list from being updated unless the user already has favorite skins, as adding these also cause the list to be updated.
The static `s_SkinLastRefreshTime` variable is replaced with a member variable `m_SkinListNeedsUpdate` and an empty optional is used as initial value to always refresh the list.
The separate `m_SkinListNeedsUpdate` and `m_SkinFavoritesChanged` variables are removed and instead the `m_SkinListLastRefreshTime` variable is used to handle all updates of the skin list.
Separate refresh time variables `m_SkinList7LastRefreshTime` and `m_SkinPartsList7LastRefreshTime` are added for the 0.7 skin menu to avoid interference with 0.6 skins.
> Fix menus skin list initially being empty, refactor skin refreshing

- src/game/client/components/spectator.cpp
- src/game/client/components/spectator.h
Demo spectator menu have several problems:
* You can not left-click yourself to spectate.
* Follow mode spectator change relies on whether the recording is spectating or not.
This PR enforces the following rule in demo player.
1. You can not change SpectatorId when in follow mode, the recording itself always decides where to look at.
2. As long as you are not in follow mode, you can change SpectatorId freely, including to yourself.
Also includes a tiny refactoring that changes `CanChangeSpectator` to `CanChangeSpectatorId` because you are the "spectator", you can't change yourself (~~but you can always improve and be a better person to allow you to be more confident~~)
> Make demo spectator id changes consistent

- src/game/server/entities/character.cpp
Spikes freeze instead of kill in practice
Temporary solution, but its simple and easy
I'm not sure how to hide the freeze bar
> Spikes freeze instead of kill in practice

- src/game/client/components/players.cpp
The mouse pos sent to server during spectating does not apply to characters, so I see no obvious reason to keep this visual.
Basically this PR stops this from happening:
https://github.com/user-attachments/assets/716b96d4-dedd-4336-b568-1deb539f5fd6
This is visual only. If you are positive this angle movement is actually used in any scenario, let me know.
> Use remote tee angle when spectating

- datasrc/network.py
- src/game/client/components/camera.h
- src/game/client/components/controls.cpp
- src/game/server/player.cpp
- src/game/server/player.h
Fixes #8810. Also prevents character flashing when switching to free view, especially in high ping servers.
Added a new `PLAYERFLAG_SPEC_CAM` to hint server which camera type the client is currently using to make sure:
* only apply input to character when input is not in spec cam.
* only change `m_ViewPos` to input when input is in spec cam. 
This is the first time that a new player flag has been added since hookcollision (there is no previous example for adding this), so please review more carefully and decides whether this is worth it to take up a precious bit of player flag (we only got 8, and this is the 6th one)
Compatibility detection (see `m_CanUseSpectatingPlayerFlag`) is done by sending the flag as active on first tick after join, this does mean the player character can not move …
> Send camera type flag to prevent unexpected viewpos and target update

- datasrc/network.py
- src/game/client/components/camera.cpp
- src/game/client/components/controls.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/server/ddracechat.cpp
- src/game/server/ddracecommands.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/player.cpp
- src/game/server/player.h
Closes #9294, closes #8452, closes #8666, closes #9296
As previously stated in #9298 and #9296. Dyncam (off-character camera) and Zoom combination introduces some extra math that needs to be done to correctly calculate player's actual cursor position.
We also do not want to touch any dyncam implementation (e.g. adjust the camera position after zoom) since that could kill some player habit.
There is also player concerns about the shifted target precision when we scaled the target position by zoom, that does have some destructive impact that breaks both dyncam zoom and player input.
Since the actual cursor position is rarely used (currently only `tele` and `telecursor`), after some discussion on discord we think it would be better to unscale input target to restore aiming consistency that …
> Fix Tele Commands during Dyncam Zoom and Make Aiming Consistent across Zoom Levels

- src/game/client/components/spectator.cpp
- src/game/client/components/spectator.h
- src/game/client/gameclient.cpp
> @sjrc6 :
> you don't get prediction when spectating yourself everyone is smooth
> I use it all the time when I'm the one being dragged through a freeze part and I don't need to do anything
> @Pioooooo :
> for showing im afk while watching myself
This reverts the menu changes, also 180'd on the left click to make sure it is possible to click on yourself to spectate for consistency.
As for solving the confusion problem where player accidentally triggering self-spec and wondering why they cant move camera when pausing, let's come up with other ways to do it.
> Revert self spec from the list and allow left clicking yourself

- data/languages/azerbaijani.txt
- data/languages/turkish.txt
As a Turkish localization "aim" can be "hedef" but it might get out of its meaning and be confusing for players so it is left as "aim". I'm waiting for a friend's check for Azerbaijani translation, I'll edit it and send it after he returns.
> Update Turkish & Azerbaijani translation for 18.8

- scripts/android/cmake_android.sh
MAKEFLAGS are not used by ninja anyway.
> android build: Allow specifying parallelism via BUILD_FLAGS

- src/game/client/components/spectator.cpp
This reverts spec behavior to how it was pre 18.8 in game. We should keep this in 18.8 while exploring other ways to avoid player confusion before we fully commit to a consistent spec behavior.
So the player confusion issue is still unsolved after a round of changes.
> Don't allow SpectateClosest / left-clicking to select self

- src/game/editor/editor_server_settings.cpp
Fixes #8694
Done by considering all commands valid if unknown commands are allowed.
Also removed all error suppression related to unknown commands. I think the error messages are still helpful even if you allows unknown command.
0 arguments commands and duplicates are still not allowed due to being unrelated to the issue.
> Allow invalid commands too if unknown commands are allowed

- scripts/android/README.md
- scripts/android/cmake_android.sh
Support user-defined `ANDROID_HOME` variable in the `cmake_android.sh` script to specify different location for the Android SDK installation. See https://developer.android.com/tools/variables#envar for details.
Make generation of data integrity index file in the `cmake_android.sh` script faster by factor >100 in MSYS2 by avoiding the loop over piped output.
Locally prepend `/usr/bin/` to the `PATH` variable in the `cmake_android.sh` script to ensure that the MSYS2 binaries are used instead of Windows-native tools with the same names which work differently like `find` and `sort`.
Update ddnet-libs reference to include the Android libs (latest ddnet-libs master) which cannot currently be build on Windows.
Update README with steps for building the Android version on Windows with MSYS2.
> Support building Android version on Windows with MSYS2

- src/game/client/components/hud.cpp
- src/game/client/components/menus.cpp
Trying to fix a color bug during initialization for MilkeeyCat
> Reset color in RenderLoading

- src/engine/client.h
- src/engine/client/client.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
Graphic errors (asset loading errors) during init are not translated ever, due to them being localized before localization files are load.
I can only find this happening with `graphics_threaded.cpp`, we could delay the localization but this just feels easier and doesn't seem to break things.
> Load localization early

- src/engine/client.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/engine/client/graphics_threaded.cpp
- src/engine/client/graphics_threaded.h
- src/engine/client/warning.cpp
- src/engine/graphics.h
- src/engine/warning.h
- src/game/client/components/menus.cpp
- src/game/client/gameclient.cpp
Add mutex for client/graphics warnings. Return an optional copy of the current warning and remove it from the vector immediately instead of returning a pointer to it and removing it later.
Use atomic for `m_WarnPngliteIncompatibleImages` as this variable is also used in multiple threads.
Do not use `CLock` as the thread-safety annotations would otherwise have to be added to a lot of client/graphics functions.
Use `client` instead of the warning title as the log system, as the warning title is usually too long.
Closes #9354.
> Make client/graphics warnings thread-safe, improve log format

- scripts/languages/twlang.py
submitted as draft because i'm under the impression that we either prefers to use single quote to make it work or this script shouldn't be touched. if that's not the case then tell me to undraft.
also found a missing line in `graphics_threaded.cpp` that is using double quotes.
test cases:
https://regex101.com/r/c3IWM0/1
> Add double quote support in twlang.py

- src/tools/demo_extract_chat.cpp
Don't store `CSnapshotDelta` object on the stack, as it's currently 524560 bytes large.
See #9234, which almost doubled the size of `CSnapshotDelta` due to the type being changed from `int` to `uint64_t`.
> Fix stack-overflow in `demo_extract_chat` tool

- src/engine/gfx/image_manipulation.cpp
The code is confusing, as the sum and counter are not used. Establishing a different dilate algorithm would be a hassle. The difference is minor and probably not noticeable.
> Implementation note for dilate: Unused sum&counter

- src/game/client/components/nameplates.cpp
New nameplates didn't display held direction for frozen dummy
> Fix dummy directions nameplate when frozen

- src/game/client/prediction/entities/character.cpp
- src/game/server/entities/character.cpp
Rescue was not considered previously after the change to spike behavior in practice mode, making auto rescue set in spikes. This PR fixes it.
> Disable auto rescue in spike

- src/game/server/gamecontext.cpp
- src/game/server/score.cpp
Reset the vote creator client ID `CGameContext::m_VoteCreator` to `-1` when the player that started the vote leaves instead of keeping the invalid client ID around. Previously, this was causing the server to crash due an assertion in the `IServer::GetAuthedState` function when a ban vote was aborted due to rcon authentication change being handled in the `CGameContext::OnSetAuthed` function after the vote creator has already left the server. It was possible to cause this situation as the target of a vote by executing `rcon_auth "<password>"; rcon "kick <vote creator>"; rcon "logout"` (`ban` works for the same effect). This also caused existing votes to use the wrong vote creator if the same client ID was reused by a new client while a vote from a client that left is still running.
Ban …
> Fix server handling when vote creator leaves

- src/game/client/components/menus_settings.cpp
Reset the selected map when reloading the map list to fix the wrong selection being shown for one frame when navigating directories in the map selection popup.
Increase scrolling speed for consistency with other listboxes (scroll 3 entries instead of 1).
> Minor improvement of entities background map settings

- src/game/client/components/background.cpp
- src/game/client/components/background.h
- src/game/client/components/maplayers.cpp
- src/game/client/components/maplayers.h
- src/game/client/components/menu_background.cpp
- src/game/client/components/menu_background.h
- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_demo.cpp
- src/game/client/components/menus_ingame.cpp
- src/game/client/components/menus_settings_assets.cpp
- src/game/client/components/race_demo.cpp
- src/game/client/gameclient.cpp
Fix loading screen rendering without progress bar for the entities background map during the initial loading.
Remove the `bool RenderLoadingBar` parameter of the `CMenus::RenderLoading` function. The progress bar is now rendered as long as the loading total is set. Add the `CMenus::FinishLoading` function to reset the loading total at the end of the loading process.
Remove the `bool RenderMenuBackgroundMap` parameter of the `CMenus::RenderLoading` function. The `RenderLoading` function will now check internally if the menu background map can be rendered.
> Improve entities/menu background map loading

- src/game/client/components/console.cpp
- src/game/client/components/console.h
Ensure all pasted lines are added to the console history instead of only the last one.
Ensure the prompt `> [command]` is printed for all pasted lines instead of only for the last one.
Fix commands being executed when pasting multiple lines while the console is in searching-mode. Now, newline characters will be replaced with spaces while the input is used for searching.
> Fix console behavior when pasting multiple lines of text

- src/game/client/components/players.cpp
Rendering the angle used by the hookcoll will be change when spectating other tees.Btw,this is visual only.
Before:
https://github.com/user-attachments/assets/1a13e0be-abf1-4603-990f-1c61105daccf
after:
https://github.com/user-attachments/assets/b75e93fd-6902-4afc-8043-af9cc646d5bb
> Make Rendering the angle used by the hookcoll be fixed when spectating

- src/engine/client/client.cpp
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/engine/shared/config_variables.h
- src/engine/shared/http.h
- src/game/client/components/skins.cpp
Allow custom servers to provide their own map download URLs without patching the code.
// I use a [similar](https://github.com/infclass/teeworlds-infclassR/commit/d93ff6cd650e00a555bdb0d6c7d67f218290d005) (5x more complicated) patch for Infclass, works ok. Thanks @heinrich5991 for suggesting `caddy`.
I don't need this in DDNet but as @ChillerDragon [asks](https://github.com/ddnet/ddnet/issues/9359) and considering @heinrich5991 help — here you are.
> Add 'sv_maps_base_url' to support map download https urls

- src/game/server/gamecontext.cpp
The ``sizeof()`` macro is evaluated at compile time. The string passed to it does not end up in the final binary and there is also no counting happening at runtime.
The ``sizeof()`` operator counts the null terminator too. So ``sizeof("foo")`` is 4 and not 3.
But this comes in handy because we want to skip over the length of the command and the slash character in front of it.
> Replace magic numbers with compile time string length

- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_start.cpp
- Also prevent main menu hotkey activating when Alt-modifier is pressed.
- Prevent repeated hotkey activating by using `IInput::KeyPress` instead of `IInput::KeyIsPressed` in `CMenus::CheckHotKey`.
- Remove unnecessary code for preventing editor hotkey from being activated quickly, which is made obsolete by using `IInput::KeyPress`.
- Remove unnecessary check for fullscreen popup which is currently always true and also an unnecessary restriction for hotkeys.
> Refactor main menu hotkey handling

- datasrc/network.py
- src/base/math.h
- src/engine/shared/config_variables.h
- src/engine/textrender.h
- src/game/client/components/camera.cpp
- src/game/client/components/camera.h
- src/game/client/components/hud.cpp
- src/game/client/components/menus_demo.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/components/spectator.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/server/player.cpp
- src/game/server/player.h
Another branch for #8836
Depends on #9301. I'll rebase accordingly.
This is a interpolation only method using existing info from `DDNetCharacter NetObj`.
Added settings: `cl_spec_cursor`, ~~`cl_spec_cursor_interpolate`, `cl_spec_cursor_demo`~~.
* The interpolation is using a cubic interpolation using 3 crafted samples. 
* The cursor guarantees to pass through the sample point but everything in between is fake.
* Note that a polynomial_mix function accepting variable sample sizes is used to test different sampling windows, I settled on the 3 sample one.
* Interpolation settings are hardcoded instead configurable to avoid player thinking interp can affect network latency.
* Downside, if you look close enough or use a 0.1x playback speed in demo, hook collision line will mismatch the cursor …
> Add spectator cursor: third time's the charm

- src/game/server/scoreworker.cpp
- src/test/score.cpp
This pr updates map vote behavior so that the case is ignored if the map name is matched. `/map reflect` currently changes map to `reflects` while map `Reflect` exists. After this change, it should select `Reflect`. However, I don't know how to setup a test environment, so this pr is not tested.
> Ignore case when map voting with full match

- src/engine/client/input.cpp
- src/engine/client/input.h
- src/engine/input.h
Remove the `CInput::UpdateMouseState` and `CInput::UpdateJoystickState` functions and the usages of the `SDL_PumpEvents` and `SDL_GetKeyboardState` functions. Instead of unnecessarily clearing and then restoring the key state at the beginning of every input update we now update the key states consistently when handling each key press/release event (keyboard, mouse click, mouse wheel, joystick button, joystick axis, joystick hat).
Fixes binds for joystick axes and hats not working consistently as calling `SDL_PumpEvents` seems to cause most joystick events to be consumed already. Closes #9381.
Replace the `CInput::KeyState` function with the `IInput::KeyIsPressed` function which was previously wrapping it.
Remove the unused parameter `bool CheckCount = false` of the `IInput::KeyPress` …
> Refactor key event handling, fix controller input, fix swapped mouse wheel left/right keys

- scripts/android/files/proguard-rules.pro
ProGuard optimizes out methods it considers unused in release build, but methods only called from native code appear unused.
The ProGuard rule was broken from renaming the main activity and also did not consider the server service yet.
> Fix Android crash in release build due to ProGuard

- src/engine/server/server.cpp
- src/game/server/gamecontext.cpp
Prevent use of uninitialized memory if the functions are used for a player that is not yet ingame. The check for the ingame state is also unnecessarily restrictive, as the client address should be available immediately.
Compare client addresses directly to determine the distinct client count excluding spectators. This is consistent with the `IServer::DistinctClientCount` function though this does not check for spectators.
> Add assertions to `CServer::GetClientAddr` functions, avoid string-based address comparison for `sv_vote_kick_min`

- src/engine/shared/console.cpp
**Fix 'all' and 'me' not passing parameter validation in rcon** -> https://github.com/ddnet/ddnet/issues/9278#issue-2686044523
**After this pr:**
fix #9278 
_I can assure there won't be any problems this time ;)_
> Fix 'all' and 'me' not passing parameter validation in rcon

- CMakeLists.txt
- src/base/system.cpp
- src/base/system.h
- src/engine/client/client.h
- src/engine/gfx/image_loader.cpp
- src/engine/shared/demo.cpp
- src/engine/shared/demo.h
- src/engine/shared/storage.cpp
- src/test/io.cpp
Use `int64_t` for file sizes and offsets of `io_seek`, `io_tell`, `io_skip` and `io_length` functions to support reading larger files, in particular Teehistorian demos larger than 2 GiB. Implement the `io_seek` function using the `_fseeki64` function on Windows and the `fseeko` function on non-Windows. Implement the `io_tell` function using the `_ftelli64` function on Windows and the `ftello` function on non-Windows. Define `_FILE_OFFSET_BITS=64` to ensure that `off_t` is a 64 bit type for the `fseeko` and `ftello` functions.
Change `io_read_all`, `io_read_all_str`, `IStorage::ReadFile` and `IStorage::ReadFileStr` functions to fail when loading files larger than 1 GiB. We should never load files that large into memory and this avoids issues with the file size exceeding `unsigned` limits. …
> Support reading demo files larger than 2 GiB

- src/game/client/components/menus_settings.cpp
- src/game/client/components/skins.cpp
- src/game/client/components/skins.h
- src/game/client/components/skins7.cpp
- src/game/client/gameclient.cpp
Fix client hanging when creating random skin while only special skins are loaded.
Scroll to reveal new skin in list after creating random skin.
Extract `CSkins::IsSpecialSkin` function.
> Minor improvements to random skin generation

- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/mapitems/layer_tele.cpp
- src/game/editor/mapitems/layer_tele.h
- src/game/editor/mapitems/layer_tiles.cpp
- src/game/editor/popups.cpp
Since an additional setting was deemed evil in #9249, this completely reverts the popup while keeping the bugfix to always show the correct number next to the brush
> Revert Tele popup

- src/game/client/components/menus_ingame.cpp
> Add button to open Touch controls wiki page to controls editor

- src/game/server/entities/character.cpp
Fix spike kills instead of freezes in force-solo servers in team 0
> Fix spike kills instead of freezes in force-solo servers in team 0

- src/engine/client/sound.cpp
- src/engine/client/sound.h
- src/engine/sound.h
Lock the sound lock when accessing any of the sound samples, voices and channels.
Add assertions to ensure that sound sample IDs are within range and that samples are loaded.
Rename parameter `FromEditor` to `ForceLoad` to make usage clearer.
Closes #8262.
> Improve sound sample thread-safety and add assertions

- src/engine/client/client.cpp
The address of the current server's info was not set before the community and rank information is updated based on that address, causing the community information to always be unset.
> Fix current server's community information not being set

- src/engine/shared/console.cpp
This reverts commit 52beb0855c76516a0b29a33f78e71bf4fc9735de.
Just making sure we don't forget about it
See https://github.com/ddnet/ddnet/pull/9415#issuecomment-2558084274
> Revert "Fix 'all' and 'me' not passing parameter validation in rcon"

- src/engine/client/sound.cpp
Conditionally stop the sample in the `UnloadSample` function instead of calling the separate `Stop` function which is not supposed to be used for samples which are not loaded. The `UnloadSample` function also needs to handle samples which are not (fully) loaded to free the sample index when the sound failed to be loaded.
Regression from #9431.
> Fix assertion when sound fails to be loaded

- .pylintrc
Fixed this pylint 3.3.3 error:
```
************* Module seven.content
datasrc/seven/content.py:34:1: R0917: Too many positional arguments (7/5) (too-many-positional-arguments)
************* Module content
datasrc/content.py:34:1: R0917: Too many positional arguments (7/5) (too-many-positional-arguments)
------------------------------------------------------------------
Your code has been rated at 9.99/10 (previous run: 9.99/10, +0.00)
```
Could also refactor the code to take a struct instead of many arguments.
```python
class Sprite(Struct):
def __init__(self, name="", Set=None, x=0, y=0, w=0, h=0):
```
But I do not think adding a huge diff in 16 year old code just for that is worth it.
Closed #9428
> Disable pylints too many arguments lint

- .clang-tidy
- src/engine/client/backend/vulkan/backend_vulkan.cpp
Closed #8319
Class member is not to be confused with regular members. The class member only refers to static variables. And for those we want UPPER_CASE without prefix. My local clangd kept tripping on it. Seems like the clang in the CI did not care yet but it is a correct fix either way.
> Fix clang tidy for static member variables

- scripts/languages/twlang.py
Only compute the result once.
This brings down the time spent from 3.5 seconds to 700 milliseconds on my device.
> Don't re-scan the source tree in scripts/languages/update_all.py

- scripts/android/files/java/org/ddnet/client/ServerService.java
- src/android/android_main.cpp
Only request the notification permission on Android 13 and newer, as on older Android versions it was not a permission but a part of the notification system. The `SDLActivity` does not use the recommended `ContextCompat` and `ActivityCompat` for permissions so requesting the unknown permission fails.
> Fix server not starting on Android 12 and older versions, refactoring

- src/game/client/components/menus.cpp
- src/game/client/components/scoreboard.cpp
- src/game/client/components/scoreboard.h
- src/game/client/gameclient.cpp
Load the only 0.7 image that exists in `CScoreboard` directly where it's used instead of looping over all 0.7 images and incorrectly incrementing the loading progress.
The incorrect loading progress was especially noticeable when the client is very slow, e.g. on Android emulators and when running with ASan.
See #9151. This does not address that too much unnecessary code is being generated yet.
> Fix incorrect loading progress due to 0.7 images

- src/game/client/components/camera.cpp
- src/game/client/gameclient.cpp
There was a mis-config on my original PR that didn't check whether player camera setting is available.
Also addressed a issue where spectating yourself uses spec zoom, which might not be preferred.
> Fix auto spec cam unexpectedly being available for players without camera info & make self spec always use user zoom.

- src/game/client/components/players.cpp
This reverts commit e14123164bed7fe61d3cb8d0a25398aacda2d17d.
Fixes inconsistent hookcoll indicator under our new-old cursor position reported by Skeith
We rolled back to a unscaled pointer for preserving aiming consistency in #9301.
This commit is no longer needed.
I don't have a bind handy, should also make 45 aim (or any obviously quantized angle) angle matches actually input now.
@l-ouis reported this particular visual inconsistency, he can probably test.
- [] Provided screenshots if it is a visual change
> Revert "Scale angles using MousePos with zoom"

- src/game/client/components/camera.cpp
Fixes this reported by Skeith
This happens where `m_AutoSpecCameraZooming` may not reset properly in some cases and zooming will cause cursor to use camera zoom when camera zoom does not match `m_SpecInfo.m_Zoom` since AUTO is off.
> Fix unexpected cursor jumps

- src/game/client/components/camera.cpp
- src/game/client/components/camera.h
People think juggling between different zoom values is tiring
Now any manually adjusted zoom will stay
Also fixed a issue where going in and out of spectating does not smooth camera movement but smooth zoom. Now it is both instant.
demo:
https://streamable.com/f17hnd
> Remove spec zoom value and use user zoom always

- src/game/client/components/camera.cpp
- src/game/client/gameclient.cpp
Fixed two demo related issues.
1. cursor doesn't work properl in follow mode if player's client id isn't 0
2. auto zoom will instant snap in follow mode for recorded local player
Reference demos: (demo provided by always (@alw5) on discord
[demos.zip](https://github.com/user-attachments/files/18300815/demos.zip)
> Fix cursor and auto spec cam in demo

- data/languages/simplified_chinese.txt
"开黑啦" as a service has renamed themselves a few years ago, and their software is getting worse and the user base is consistently smaller than the tencent ones, we've been updating the url redirect since. We didn't change the button before because the phrase is actually not bad for indicating what it was for (translated to "let's play together")
I finally started hosting the join page myself instead of just using a DNS providers redirect. so it finally supports https now.
Rename the button to "join community" instead.
And I feel like we shouldn't just have a backbox url that one person secretly controls. So the page is now opensource here: 
https://github.com/TeeworldsCN/join
You can check the current join page for CHN here: https://chat.teeworlds.cn
> update community info

- scripts/android/files/java/org/ddnet/client/ClientActivity.java
- scripts/android/files/java/org/ddnet/client/ServerService.java
- src/android/android_main.cpp
- src/android/android_main.h
- src/engine/server/main.cpp
- src/game/client/components/menus_start.cpp
Currently no arguments are passed when launching the server though. This is for supporting #9092.
> Support passing launch arguments to Android server

- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/editor_actions.cpp
- src/game/editor/popups.cpp
Accidentally deleting an image/sound that is used in many layers is a destructive action and is not undo-able, you have to go back and replace all the layer images/sounds
> Editor: confirm deletion of images/sounds that are used in map layers, fix crash when nonexistent image is added thru history/redo

- src/game/client/components/players.cpp
Currently the hookline ignores hook teleports, I think it would make sense for it to pass through the teleport and actually show where the hook will go.
This should solve issue #8735
> teleport hookline (only when there is 1 possible exit)

- src/base/log.cpp
- src/base/logger.h
- src/engine/client/client.cpp
- src/engine/server/main.cpp
- src/engine/shared/storage.cpp
- src/engine/storage.h
- src/tools/dummy_map.cpp
- src/tools/map_convert_07.cpp
- src/tools/map_optimize.cpp
- src/tools/map_replace_image.cpp
- src/tools/map_resave.cpp
Add checks to ensure that:
- The first storage path, i.e. the path of the designated user directory, is added to the storage successfully.
- The folder of the user directory is created successfully (or already exists).
- The default folders inside the user directory are created successfully (or already exist).
On failure, the client/server will quit immediately on launch. The client will quit with an error message popup showing the log messages of the failed storage initialization. Closes https://github.com/ddnet/ddnet/issues/3758, which presumably was caused by the user directory not being accessible. Closes https://github.com/ddnet/ddnet/issues/9165.
Refactoring:
- Consistently use the `log_` functions for logging.
- Extract functions in `CStorage` to improve readability.
- Add `enum …
> Improve storage initialization and error handling, refactoring

- src/engine/client/client.cpp
Previously, the redirect message `NETMSG_REDIRECT` would always cause the main connection to be redirected and the dummy to be disconnected no matter on which connection it is received. Now, if the redirect message is received on the dummy connection with the destination port being idential to the current port then the dummy only will be reconnected. Redirecting the dummy connection to a different port is not allowed, as the dummy should not be connected to a different server than the main, as the client assumes that main and dummy use the same map.
Closes #9480.
> Support reconnecting dummy by redirecting to same port

- src/game/client/components/scoreboard.cpp
- src/game/client/components/skins7.cpp
- src/game/client/components/skins7.h
- src/game/client/render.cpp
> Fix incorrect default 0.7 skin parts being used, various minor refactoring

- datasrc/compile.py
- datasrc/network.py
- src/game/client/prediction/entities/character.h
- src/game/server/player.h
~~This would be the third enums.h file I created.~~
~~There is one for the [editor](https://github.com/ddnet/ddnet/blob/e55cf2967faffa9ab79fc95fa53b870dd4fbc764/src/game/editor/enums.h) and one for [the client](https://github.com/ddnet/ddnet/blob/master/src/engine/client/enums.h) and this new one is then for the server. Maybe one day I will also propose to add src/game/enums.h for server and client shared and then it should be enough to cover all cases.~~
~~The goal here is to make including cleaner and dependency management easier. Also WEAPON_ specifically does not belong into the player class it is used all over the server code. Including player.h to get access to that enum is a bit weird and often overkill.~~
~~It is similar to the file src/base/types.h but specifically for enums …
> Move special weapon enums to protocol.h

- src/game/client/components/menus.cpp
Do not increment loading progress for individual menu images because the total number of images in the `menuimages` folder might be different than expected. Eventually, menu image loading could be moved to a background job like community icon loading.
Closes #9497.
> Fix incorrect loading progress when menu images are added/removed

- data/languages/brazilian_portuguese.txt
I was translating `data/languages/portuguese.txt` when I noticed someone would likely fall into a lazy translation mistake. It's pretty obvious because it's one of the titles in the settings.
A word like `"Assets"` has a context in both finance and digital media. Most online translators choose to use the financial context, for some reason. This file translates it to the financial context, which is `"Ativos"`. The actual translation should have been `"Recursos"`.
> Fix language translations for Brazilian Portuguese

- src/game/client/components/hud.cpp
Knowing position infomation in freeview helps navigating long-range flights when you don't know the destination coordinates. I came up with two designs and chose the current as the corner location is less distracting. The other design is listed for comparison.
Before:
After:
The other design:
> Show position in freeview

- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/editor_props.cpp
- src/game/editor/editor_server_settings.cpp
- src/game/editor/explanations.cpp
- src/game/editor/layer_selector.cpp
- src/game/editor/map_grid.cpp
- src/game/editor/mapitems/layer_tiles.cpp
- src/game/editor/popups.cpp
- src/game/editor/quick_actions.h
- Use English sentence case for all tooltips and labels, i.e. only capitalize the first word of every sentence.
- End all tooltips with a period.
- Consistently format hotkey descriptions in square brackets at the beginning of tooltips with title case capitalization.
- Change verb form of tooltips to fit the sentence "Clicking this button will [tooltip]", e.g. use "Rotate X" instead of "Rotates X".
- Improve clarity, consistency and readability of various tooltips.
- Remove unnecessary `grabbing` debug message when grabbing a brush.
- Remove unnecessary temporary variable `m_aMenuBackgroundTooltip`.
> Improve editor labels and tooltips

- src/game/server/ddracechat.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/player.cpp
- src/game/server/player.h
Implements chat command `/afk`, closes #9270.
> Add chat command /afk

- src/game/server/ddracechat.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/player.cpp
- src/game/server/player.h
This reverts commit 4bac7d6c4182300d035377744954754fde79c099.
It was merged without even referencing the discussion about whether it should be included or not.
> Revert "Add chat command afk"

- src/engine/shared/memheap.cpp
- src/engine/shared/memheap.h
The client previously crashed when loading a localization file with a replacement line (plus zero terminator) longer than the size of a `CHeap` chunk (65600 bytes) due to the line data being written outside the heap chunk.
This is fixed by allowing `CHeap` to allocate chunks as large as necessary to contain at least one item.
As an alternative the `CHeap` functions could be changed to return `nullptr` if the wanted allocation is too large, which would have to be handled explicitly when loading localization files.
> Fix crash when loading very long localization lines

- src/mastersrv/Cargo.lock
- src/mastersrv/Cargo.toml
- src/mastersrv/src/locations.rs
- src/mastersrv/src/main.rs
This allows to add bans and port forward exceptions without restarting the mastersrv itself.
It also allows reloading the locations database (with the important caveat that it is mmap-ed, and as such must be removed before being overridden in the file system).
> mastersrv: Add config file and hot-reloading of it

- src/engine/client/backend/vulkan/backend_vulkan.cpp
- src/engine/client/graphics_threaded.cpp
This fixes #9534 .
Additionally this code changes handles the result of `vkMapMemory` now to make the code safer.
The Vulkan backend intentionally does not support such huge buffers, to reuse buffers in the case of streamed buffers such as during text rendering.
The actual fix for a text limit must be handled in the text rendering engine
> Handle `vkMapMemory` result. Fail if memory exceeds max buffer size for stream buffers.

- src/game/client/components/menus_ingame.cpp
Show the current server's community icon with its name as a tooltip.
Show score limit and time limit like in the scoreboard only when they are set instead of showing the default value `0`. Also show the current and total number of rounds if set.
Improve consistency of text margins. Remove empty lines in game info.
Use all addresses of the current server info for checking, adding and removing server favorite instead of only considering the address we are connected to.
Refactor layout using UI rects and labels instead of using absolute positioning.
Use `SERVER_FLAG_PASSWORD` constant instead of the magic number `1`.
Screenshots:
- Before:
- After:
> Improve ingame server info, refactoring

- src/game/editor/editor.cpp
When loading a map from the `downloadedmaps` folder with the editor file browser it was already correctly ensured that the map cannot be saved again to this folder, but this was not checked when the current map is loaded directly from the `downloadedmaps` folder with the "Load current map" function.
Closes #9529.
> Fix editor saving to `downloadedmaps` when loading current map

- src/base/system.cpp
- src/base/system.h
- src/engine/client/client.cpp
- src/engine/client/serverbrowser.cpp
- src/test/netaddr.cpp
- src/tools/stun.cpp
Replace mostly unused `bool` return value with assertion to ensure the address has a valid type instead of outputting `unknown type` as the address.
Also test the assertion failure by changing the existing test case to death tests. See https://google.github.io/googletest/advanced.html#death-tests for details. The death test names must end with `DeathTest` so GoogleTest runs these test cases before all other tests.
Fix assertion failure in client due to previous server address being invalid when connecting to the first server by comparing addresses directly instead of converting the invalid address to a string first.
Use `bool` instead of `int` for the `add_port` parameter.
Minor improvement of doxygen comment.
> Minor refactoring of `net_addr_str` function

- src/game/server/ddracecommands.cpp
> Fix assert when using `save_dry` server command

- src/engine/client/serverbrowser_ping_cache.cpp
Depends on #8992 which adds support for 0.7 server info which is used to determine the ping that will be saved to the cache.
With #8992 the ping is saved correctly to the database, but the lookup in the `std::unordered_map` fails because `NETTYPE_TW7` is not ignored.
Closes #9176.
> Fix ping cache for 0.7 servers

- src/game/client/components/hud.cpp
Not resetting the value was causing incorrect rendering of speed value in demo viewer after opening the same demo 2 times
> Reset player speed value

- src/game/editor/editor.cpp
Checkpoint tiles used the wrong teleport number when being placed
Video of the bug:
https://github.com/user-attachments/assets/461c444b-2ed0-43ee-9793-51f383b5814d
> Fix editor tele cp bug

- src/game/server/entities/character.cpp
- src/game/server/entities/character.h
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/save.cpp
- src/game/server/save.h
Fixes #9156 for both super and /invincible
Fixed a crash when in super with an empty previous team and when players were on a different teams during hot reload
> Preserve super on hot reload, fix hot reload crashes

- src/game/client/components/menus.h
- src/game/client/components/menus_ingame.cpp
Refactored `CMenus::RenderServerControlServer`, removed unneeded comparison with `m_pClient->m_Voting.m_NumVoteOptions`, scroll to selected option when search parameter is changed
> Remember selected server settings option during search

- data/languages/german.txt
- src/game/client/components/menus_settings.cpp
Show credits for the selected language file in the language settings.
The credits are retrieved from the respective language file like a regular localization string. The string `"English translation by the DDNet Team"` with context `"Translation credits: Add your own name here when you update translations"` should be translated to the credits for the respective language. All language authors should be listed (without duplicates) in the order in which they first contributed to the language file. Old author comments should be removed from the file and integrated into this string.
Credits for the German translation are provided as an example.
Closes #6949.
Screenshots:
- English: 
- German:
> Add translation credits to language settings

- datasrc/network.py
- src/game/client/components/hud.cpp
- src/game/client/prediction/entities/character.cpp
- src/game/server/entities/character.cpp
As mentioned in #8923 some of the prediction flags are too generic. If IsDDRace overwrites InfiniteAmmo then the InfiniteAmmo flag becomes a bit useless and the IsDDrace a bit hard to understand.
In ddnet-insta I had to turn off DDRace prediction to fix a ammo glitch with antiping.
https://github.com/ddnet-insta/ddnet-insta/commit/4c51004ffc11847df0c62c22d9ed676ae343a0db
This then comes with other side effects and breaks all the other predictions that are activated by IsDDRace.
As of right now InfiniteAmmo is set to true by default. And it is automatically set to false if the snapped player has some ammo.
https://github.com/ddnet/ddnet/blob/b453784dcafbf95af88b674c9afd7eb0facaf037/src/game/client/gameclient.cpp#L644 https://github.com/ddnet/ddnet/blob/b453784dcafbf95af88b674c9afd7eb0facaf0 …
> Do not force infinite ammo for ddrace gametypes

- src/engine/shared/config_variables.h
- src/game/server/teams.h
Might be useful for trashmap servers or servers where owners want to allow /invincible, /telecursor, in team 0 by default instead of making players go into a team first.
Not sure if it would be used beyond trashmap servers, that can be something to discuss.
> Add sv_practice_by_default command

- src/game/client/components/menus_settings.cpp
This pull request gives #9292 a compatibility for players who don't like spectator cursor
Now the spectator cursor is disabled as default.
If anyone like it, the spectator cursor could be enabled in HUD settings.
> Add button in settings to enable/disable spectator cursor

- src/engine/gfx/image_loader.cpp
Set the error and warning handling functions as early as possible to also get more detailed errors and warnings when the `png_create_read_struct` function fails, e.g. due to libpng version mismatch.
> Also print errors/warnings for `png_create_read_struct` function

- src/game/server/ddracechat.cpp
- src/game/server/entities/character.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/teams.cpp
- src/game/server/teams.h
Toxic players may take advantage of someone's request to swap, for example by committing suicide and then accepting the request at the start, or by intentionally dying in a place where they cannot be saved and then accepting the request.
> Cancel swap command

- src/game/client/components/hud.cpp
Solve #9571 
Since we have had a ninja bar in DDNet, I used it as 0.7 ninja bar which is displayed at the right of health.
Maybe we need a vote to decide which ninja bar should be used in 0.7 servers: 0.7 style or DDNet style?
> Display ninja bar in 0.7 servers (DDNet style)

- src/engine/server.h
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/engine/shared/network.h
- src/engine/shared/network_conn.cpp
- src/engine/shared/network_server.cpp
- src/game/server/ddracecommands.cpp
- src/game/server/gamecontext.cpp
Generate unique local addresses (IPv6 addresses) for debug dummies so address-based functions work with debug dummies. Every debug dummy's ULA has a randomly generated global ID such that debug dummy addresses are most likely unique. The ULA's subnet ID is set to a constant value. The ULA's interface ID is set to the dummy's client ID. See https://en.wikipedia.org/wiki/Unique_local_address for details about the format. The port is generated randomly in the same way that normal clients select their port.
Change the `const char (*::CNetServer::ClientAddrString(int ClientID) const)[NETADDR_MAXSTRSIZE]` function signature to `const std::array<char, NETADDR_MAXSTRSIZE> &ClientAddrString(int ClientId, bool IncludePort) const` and change the `const char (*CNetConnection::PeerAddressString() …
> Refactor server's client address functions, handle debug dummies

- src/game/client/components/chat.cpp
- src/game/client/components/emoticon.cpp
- src/game/client/components/nameplates.cpp
- src/game/client/components/players.cpp
- src/game/client/components/scoreboard.cpp
- src/game/client/gameclient.cpp
The dummy is considered connected by the engine client (`IClient::DummyConnected` function returns `true`) after receiving `NETMSG_CON_READY`, which also causes `cl_dummy` to be set to `1`. However, the game client does not have the dummy's client ID until a snapshot is received, which means `m_aLocalIds[1]` (i.e. `m_aLocalIds[g_Config.m_ClDummy]`) is still set to `-1` (or an old value from when the dummy was last connected on the server) for a moment when connecting the dummy.
This was noticeable by connecting the dummy and quickly opening the emoticon HUD, which would briefly render invalid skins for the eye emote preview based on out-of-bounds `CTeeRenderInfo`.
In the other cases, the use of invalid local IDs could be confirmed by adding assertions. For example the hammer direction …
> Fix out-of-bounds reads during dummy connecting

- datasrc/network.py
- src/engine/shared/protocol.h
- src/game/client/components/debughud.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/client/prediction/entities/character.cpp
- src/game/client/prediction/entities/character.h
- src/game/server/gamecontext.h
> On the client side the per-character tuning as-is works acceptable as long as AntiPing is off (infclass uses per-player tuning for many years). Turning on the AntiPing ruins the UX in some cases.
> (c) https://github.com/ddnet/ddnet/issues/7288 
This PR allow mods override client-side tunezone (which is currently determined by the player's location on the map).
Example: now i can define some tune zones in map file and force use them for specific characters.
Before (please note that there are no tune zone tiles on the map):
https://github.com/user-attachments/assets/e352d462-2bdb-4266-afd8-9e2f35dac3d2
After:
https://github.com/user-attachments/assets/3bb02d4c-1062-4165-8420-b67b3fc8962d
> Allow custom mods override client prediction tune zone (per-player)

- src/engine/client.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/engine/shared/config_variables.h
- src/game/client/components/items.cpp
- src/game/client/gameclient.cpp
Partial antping, adds cl_antiping_percent.
If you ever played on higher ping servers and you use antiping you can see how much players jump, but without antiping your actions have a lot of delay. With this PR you can go somewhere inbetween the 2 extremes.
cl_antiping_percent 50, only predicts 50% ahead, etc.
Draft atm because I haven't properly tested it but I wanna hear peoples opinion about this.
> Partial antiping

- src/game/client/components/chat.cpp
- src/game/client/components/chat.h
- src/game/client/components/menus_settings.cpp
> Adds a button that opens the ddnet-saves.txt

- src/engine/server/server.cpp
In the `CServer::DistinctClientCount` function a check for the address being `nullptr` was missing in the inner loop. Before #9591 this was comparing addresses from uninitialized memory instead. Duplicate checks of the client state are avoided by first fetching the addesses of all clients which are ingame.
Closes #9597.
> Fix crash with `sv_dnsbl_vote 1` and debug dummies

- README.md
I completley missed that there was an aur package the first time I read it ages ago and just now. Make it more obvious it exists and isn't just for mac
(Yeah yay sucks but everyone will recognise it)
> Clearer arch linux clang format

- src/engine/client/discord.cpp
Happens only on win32 msvc build with -DDISCORD=ON
> Fix win32 msvc build with discord

- src/engine/client/client.cpp
- src/engine/client/client.h
- src/engine/shared/http.cpp
- src/engine/shared/http.h
- src/game/client/components/skins.cpp
HTTP downloads to files now automatically have `If-Modified-Since` support, you can opt out using `SkipByFileTime(false)`.
Downloaded maps are now downloaded to a filename like `name.map.123.tmp.123.tmp` which isn't really what one wants, but also doesn't hurt.
> Make it easier to download a file and have `If-Modified-Since` support

- src/engine/client/client.cpp
- src/game/client/gameclient.cpp
This issue: fixes https://github.com/ddnet/ddnet/issues/9618
Was caused by this pr: https://github.com/ddnet/ddnet/pull/8375
This specifically happens when your client predicts ahead very little, it wouldn't meet the requirements for copying over the world, thus everything would either be frozen when your prediction becomes small enough or you just wouldn't see anything besides your own player to begin with.
I fixed that and then reread my original pr and realized that it caused you to see all antiping related stuff 1 tick later, so I changed that as well.
> Fix Issue 9618 and improve responsiveness for projectiles to pre pr 8375 levels

- src/engine/shared/config_variables.h
Change the `comma separated` in the descriptive text of `src/engine/shared/config_variables.h` to `comma-separated` for consistency in #9583.
> Unify the description in `config_variables`

- src/game/server/gamecontroller.cpp
- src/game/server/gamecontroller.h
- src/game/server/gameworld.cpp
Newer teeworlds also does not send any chat messages from the gameworld anymore. Which to me sound the wrong place to do it anyways.
In ddnet there are no teams so they can also never be balanced. Also ddnet forks can just implement it on tick there is no need to access the gameworld for it. Also the method was not virtual so not too interesting for custom controllers.
I intentionally kept ``bool IGameController::CanBeMovedOnBalance(int ClientId)`` because it is still used in modern teeworlds.
And it can be used in ddnet forks to implement team balancing.
This commit does NOT fall under #7777 because it is a cleanup that benefits ddnet.
The motivation behind this commit is to cleanup gameworld to make it easier to link in tests.
Which is need for: …
> Remove ``IsForceBalanced()``

- .github/workflows/build.yml
Ubuntu 20.04 runners will fully stop working April 1 with some brownouts in March.
See https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/
> Switch from Ubuntu 20.04 to 22.04 in CI

- src/engine/shared/map.cpp
- src/game/client/components/mapsounds.cpp
- src/game/client/render_map.cpp
- src/game/editor/mapitems/layer_tiles.cpp
- src/game/editor/mapitems/map_io.cpp
- src/game/mapitems.h
- src/game/mapitems_ex.h
- src/test/datafile.cpp
- src/tools/map_convert_07.cpp
- src/tools/map_diff.cpp
- src/tools/map_extract.cpp
- src/tools/map_optimize.cpp
- src/tools/map_replace_image.cpp
Use the numerical version values for mapitem versions directly instead of constants except for compatiblity with upstream Teeworlds mapitems. See https://github.com/ddnet/ddnet/pull/8349#issuecomment-2106080227
Add documentation for upstream Teeworlds mapitem versions.
> Remove mapitems' `CURRENT_VERSION` constants

- src/game/client/components/menus.h
- src/game/client/components/menus_settings.cpp
The translation credits were not supposed to be shown in the first launch language popup as this information is not relevant on first launch and the popup is also not large enough.
> Do not show translation credits in first launch language popup

- src/game/client/components/menus.cpp
Show tooltip with the community name for the community icon in the password popup. Always show the `Name` label instead of only showing it when no community icon is available, which is only the case if the icon could not be loaded.
Cleanup layout code of the password popup to avoid unnecessary layout and make labels adjust their font size for longer localizations instead of overlapping.
Screenshots:
- Before: 
- After:
> Add community name tooltip to password popup, refactoring

- src/game/client/components/touch_controls.cpp
It's checked that all corner is acted correctly. And it's complexity is o(n²), n is the amount of button that currently visiable, not related to the amount of visibilities.
Checked ingame using a big touch control(1MB) with 999 extra menus. Didn't see FPS drop.
> Fix touch control button's corner bug

- .github/workflows/build.yml
CC #9645
We use 3.13.4 for compiling releases: https://github.com/ddnet/ddnet/issues/9645#issuecomment-2633524242.
> Use CMake 3.13.4 on old Linux CI

- data/touch_controls.json
- src/game/client/components/touch_controls.cpp
- src/game/client/components/touch_controls.h
Add properties to the root object of the touch controls configuration to adjust the background color of all touch buttons:
- `"background-color-inactive"`: specifies the background color of inactive touch buttons.
- `"background-color-active"`: specifies the background color of active touch buttons.
For backwards compatibility these properties are allowed to be unset in which case the previous default values will be used.
Colors are specified as hexadecimal strings in the formats `RRGGBBAA`, `RRGGBB`, `RGBA` and `RGB` without any prefix like `#`, e.g. `"A526C440"`. If the alpha value is omitted then it is set to full opacity by default.
> Support changing touch button background color

- .github/workflows/clang-sanitizer.yml
- .github/workflows/style.yml
Follow-up for #9640. Ubuntu 20.04 runners will be deprecated in April. Download clang-format-10 from https://github.com/muttleyxd/clang-tools-static-binaries/releases as it's not available from the package manager after Ubuntu 20.04.
> Switch style check and ASan/UBSan CI from Ubuntu 20.04 to latest

- src/engine/shared/fifo.cpp
Carriage return `\r` characters were not properly ignored in Windows' FIFO implementation (named pipes), leading to incorrect commands being executed (including a trailing `\r`) which was causing some commands like rcon authentication and map changes to fail due to incorrect password/filename unless the arguments were escaped with quotes.
> Fix FIFO on Windows not working with Windows linebreaks

- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/client/prediction/gameworld.cpp
- src/game/client/prediction/gameworld.h
- src/game/mapbugs.cpp
- src/game/mapbugs.h
- src/game/server/gamecontext.cpp
- src/test/mapbugs.cpp
Store and update `CMapBugs` on client-side for currently loaded map. Register console chain for the `mapbug` map setting to update mapbugs based on map settings.
Prediction is not adjusted for `BUG_GRENADE_DOUBLEEXPLOSION`, as this seems to work better without additional prediction, causing prediction errors otherwise.
> Add support for checking mapbugs in client prediction, refactoring

- src/antibot/antibot_null.cpp
Now antibot_null.cpp can be copied into a external repo and compiled with
```
clang++ unedited_antibot_null_copy.cpp -I../ddnet/src -I../ddnet/build/src/ -fvisibility=hidden -fPIC -shared -o libantibot.so -Og -g
```
Which seems to be the recommended way as far as I understood
> Absolute antibot include to make it template ready

- src/game/client/components/maplayers.h
- src/game/client/render.h
- src/game/editor/editor_trackers.h
- src/game/editor/mapitems/map_io.cpp
- src/game/layers.h
- src/game/mapitems.h
- src/game/mapitems_ex.h
> Consistently use `class`es instead of `struct`s for all mapitems

- CMakeLists.txt
- src/base/system.cpp
- src/base/system.h
- src/game/client/components/menus.h
- src/game/client/components/menus_start.cpp
- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/popups.cpp
- src/game/editor/quick_actions.cpp
- src/game/editor/quick_actions.h
- src/test/shell_execute.cpp
Closes #6733
Closes #9009
Alternative to #9060
Runs a local server with the currently opened map (if it's saved to `maps/`) and automatically authenticates with a new custom rcon password
https://github.com/user-attachments/assets/6fda8098-9a85-48a9-a2d9-fd84e770f361
> Add test map locally

- src/game/client/components/camera.cpp
Randomly caught by UBSan in the CI:
```
/home/runner/work/ddnet/ddnet/src/game/client/components/camera.cpp:271:5: runtime error: load of value 190, which is not a valid value for type 'bool'
0 0x561f7a6063ab in CCamera::UpdateCamera() /home/runner/work/ddnet/ddnet/src/game/client/components/camera.cpp:271:5
1 0x561f7ae91b0f in CGameClient::OnRender() /home/runner/work/ddnet/ddnet/src/game/client/gameclient.cpp:801:11
2 0x561f7a154053 in CClient::Render() /home/runner/work/ddnet/ddnet/src/engine/client/client.cpp:1056:16
3 0x561f7a1a2de6 in CClient::Run() /home/runner/work/ddnet/ddnet/src/engine/client/client.cpp:3292:6
4 0x561f7a1f88f0 in main /home/runner/work/ddnet/ddnet/src/engine/client/client.cpp:4945:11
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior …
```
> Fix uninitialized `CCamera::m_IsSpectatingPlayer` variable

- src/game/editor/layer_selector.cpp
> Fix editor ctrl+right click selecting hidden layers/groups

- src/game/client/components/skins.cpp
Fix leak of skin textures if skin body size check fails and add missing error log message for this case. Fix leak of skin image data if local skin fails to be loaded. The image data is now freed outside the `LoadSkin(const char *pName, CImageInfo &Info)` function.
Add variables for image data offsets to avoid duplicate calculations.
Minor improvements of code format.
> Fix leaks when loading skin fails, minor refactoring

- src/game/server/ddracechat.cpp
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/teams.cpp
- src/game/server/teams.h
Closes #8613 
Closes #7679 (easier way to disable practice mode without causing that bug)
Adds `/unpractice`, which kills the team and disables practice mode. Compatible with `sv_solo_server`
For `sv_practice_by_default`, this resolves the following comment: https://github.com/ddnet/ddnet/pull/9251#discussion_r1885000742
Each team is treated individually, and practice mode can be turned off for them. Team 0 is always forced into practice mode.
> Add /unpractice and rework sv_practice_by_default

- src/engine/server.h
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/game/server/player.cpp
Adds `hide_auth_status ?i[hide]` to hide auth status to other players. The auth status is still shown for authed players. It can be used like this: `rcon_auth 1;rcon "hide_auth_status 1"` to log in "silently"
A player could still find out if someone is authed or not by trying to kick them which would yield the error `You can't kick authorized players`. Not sure if that's a problem though.
Closes #9492
> Add `hide_auth_status ?i[hide]` to rcon

- src/game/server/player.cpp
Remove the `This server uses an experimental translation from Teeworlds 0.7 to 0.6. Please report bugs on ddnet.org/discord` broadcast for 0.7 clients. The translation layer has been in use for years now and should be considered stable.
Closes #9611
> Remove `0.6<->0.7 translation` broadcast

- .github/workflows/build.yml
Builds the programs in their respective `src` directory instead of creating a new one. Explicitly exclude `ubuntu-22.04` instead of only building on `latest` as requested in #9696
> Simplify rust CI, explicitly exclude `ubuntu-22.04`

- .github/workflows/build.yml
- .github/workflows/clang-sanitizer.yml
- .github/workflows/clang-tidy.yml
- .github/workflows/rust.yml
- .github/workflows/style.yml
Reorder and group steps of style CI to avoid unnecessary work when checks fail and to improve readability. First only install the necessary Linux dependencies and code formatters. Then perform various code format checks with ClangFormat, Shellcheck, shfmt and Pylint. Next perform additional code checks using custom scripts for headers files, includes, config variables and error messages. Last check languages, images, maps. Compile the dilate and twmap tools in separate steps directly before they are being used to avoid unnecessary work when previous checks fail.
Consistently name CI steps.
Consistently cache Rust dependencies in every CI run.
> Improve order of CI style checks, minor refactoring

- datasrc/network.py
- src/engine/shared/config_variables.h
- src/game/client/components/hud.cpp
- src/game/client/components/hud.h
- src/game/client/components/menus_settings.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/server/player.cpp
[Feature requested on discord ](https://discord.com/channels/252358080522747904/1326126761683058688)
Adds an icon with a spectator count. This icon appears when someone is spectating you or when your tee is near the center of a freeview spectator
Notes:
- The feature is optional, the HUD icon can be turned off in settings
- If decided, It can be disabled for rcon authed players
- The range of being counted as spectated is yet to be decided
https://github.com/user-attachments/assets/1fa546bf-07ad-4166-aba4-c3fc8559c713
> Add spectator count to HUD

- src/game/client/component.h
- src/game/client/components/chat.cpp
- src/game/client/components/chat.h
- src/game/client/components/effects.cpp
- src/game/client/components/ghost.cpp
- src/game/client/components/ghost.h
- src/game/client/components/infomessages.cpp
- src/game/client/components/infomessages.h
- src/game/client/components/menus_settings.cpp
- src/game/client/components/menus_settings7.cpp
- src/game/client/components/players.cpp
- src/game/client/components/skins.cpp
- src/game/client/components/skins.h
- src/game/client/components/skins7.cpp
- src/game/client/components/skins7.h
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/client/render.cpp
- src/game/client/render.h
- src/game/client/sixup_translate_game.cpp
Skin loading and refreshing
---------------------------
Add `CSkinDescriptor` class to describe the information related to the skin textures of a `CTeeRenderInfo` so the skin textures can be refreshed independently from the other attributes. Add `CManagedTeeRenderInfo` class as wrapper for a `CTeeRenderInfo` and a corresponding `CSkinDescriptor`. Instances of `CManagedTeeRenderInfo` are managed as `std::shared_ptr`s by the gameclient. This allows skin textures of all `CManagedTeeRenderInfo`s to be refreshed dynamically when the underlying skin is refreshed. This replaces the existing `CComponent::OnRefreshSkin` callback function in which all skins had to be refreshed. This allows dynamically loading and unloading individual skins, to support lazy loading and unloading of skins in the …
> Overhaul skin loading and refreshing, improvements for 0.7 skins

- src/game/client/components/mapimages.cpp
- src/game/client/components/mapimages.h
- src/game/editor/editor.cpp
"Show ingame entities" option will now only render weapon shields for DDNet and custom entities, as F-DDrace uses different tiles instead of shields
> Fix editor weapon shield preview for custom entities

- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/mapitems/layer_front.cpp
- src/game/editor/mapitems/layer_game.cpp
- src/game/editor/mapitems/layer_speedup.cpp
- src/game/editor/mapitems/layer_switch.cpp
- src/game/editor/mapitems/layer_tele.cpp
- src/game/editor/mapitems/layer_tiles.cpp
- src/game/editor/mapitems/layer_tune.cpp
- src/game/editor/popups.cpp
Closes #9705 
- fixed the issue where the shortcut caused the button hiding to fail
- replaced the integer flag for `m_AllowPlaceUnusedTiles` with an enum class
-  All integer flags in `m_AllowPlaceUnusedTiles` have been replaced with the corresponding enum values from `EUnusedEntities`. 
-  Parts that previously relied on implicitly converting -1 and 1 to true have been replaced with `isAllowPlaceUnusedTiles()`.
> fix issue where 'allow unused' shortcut caused button hiding to fail

- datasrc/network.py
Reported by @MilkeeyCat and thanks to @furo321 for helping me
Fixes this client issue on servers that are running on commits between spectator cursor and spectator count
> Fix DDNetSpectatorInfo unpack error

- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/mapitems/layer_front.cpp
- src/game/editor/mapitems/layer_game.cpp
- src/game/editor/mapitems/layer_speedup.cpp
- src/game/editor/mapitems/layer_switch.cpp
- src/game/editor/mapitems/layer_tele.cpp
- src/game/editor/mapitems/layer_tiles.cpp
- src/game/editor/mapitems/layer_tune.cpp
use upper camel case for `isAllowPlaceUnusedTiles` method
> refactor: use upper camel case for `isAllowPlaceUnusedTiles`

- src/game/client/components/menus_ingame.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
> Remove unused argument of `CGameClient::SendKill` function

- src/game/client/components/touch_controls.cpp
When no "label-type" is given on buttons with "bind" or "bind-toggle", the client will give them a default "label-type" as "plain". This is more convenient when people need to write their touch controls manually.
> Support importing touch controls with no "label-type"

- .clang-tidy
Reduces spam with modern clang.
iirc heinrich once said he never wanted to fix the issue so lets silence it.
I would also be cool with fixing it but the diff would be huge.
```
/home/chiller/Desktop/git/ddnet-insta/src/game/collision.cpp:995:18: error: '*' has higher precedence than '+'; add parentheses to explicitly specify the order of operations [readability-math-missing-parentheses,-warnings-as-errors]
995 |         return m_pTiles[Ny * m_Width + Nx].m_Index;
|                         ^~~~~~~~~~~~
|                         (           )
/home/chiller/Desktop/git/ddnet-insta/src/game/collision.cpp:1008:30: error: '*' has higher precedence than '+'; add parentheses to explicitly specify the order of operations [readability-math-missing-parentheses,-warnings-as-errors]
1008 | …
```
> Silence readability-math-missing-parentheses

- src/game/client/gameclient.cpp
> Use `HasExtendedDisplayInfo` instead of `HasExtendedData` for spectator cursor

- src/engine/client/client.cpp
> Fix `player_default_eyes` not working if `cl_run_on_join` ends with `;`

- src/game/editor/mapitems/layer_speedup.cpp
- src/game/editor/mapitems/layer_switch.cpp
- src/game/editor/mapitems/layer_tele.cpp
- src/game/editor/mapitems/layer_tune.cpp
Use auxiliary variables in `BrushDraw()` to replace expressions in array indices, similar to `FillSelection()`, for improved readability.
The `BrushDraw()` and `FillSelection()` functions in `layer_xxx.cpp` have quite a few similarities. In `FillSelection()`, the part where the index is calculated is placed in auxiliary variables for better readability. I think it would make sense to unify this approach.
Except for the `TgtIndex` variable already existing in `layer_tele.cpp` (which is only used in a few lines), which needs to be removed, everything else works well.
> Editor: Use auxiliary variables in `BrushDraw()` to replace expressions in array indices for readability

- src/game/editor/mapitems/layer_speedup.cpp
- src/game/editor/mapitems/layer_switch.cpp
- src/game/editor/mapitems/layer_tele.cpp
- src/game/editor/mapitems/layer_tune.cpp
fix #9531
this is an example from `layer_tele`. I'm pretty sure there were some cases missing after the `if(pLt->m_Tele && m_pTiles[TgtIndex].m_Index > 0)` statement. if `m_pTiles[TgtIndex].m_Index` is 0, it just does nothing.
https://github.com/ddnet/ddnet/blob/c70dcd9b57464aa1239b3223222af777c6860cf9/src/game/editor/mapitems/layer_tele.cpp#L268-L286
and this fix covers them. but I'm not sure if using `else` to handle them is appropriate.
before:
[Screencast from 2025-02-24 10-44-18.webm](https://github.com/user-attachments/assets/69695808-73e7-4133-a977-cf3fccebd393)
after:
[Screencast from 2025-02-24 10-44-47.webm](https://github.com/user-attachments/assets/d5f6a174-43fa-4771-a29f-ccf11b1c2501)
> Fix `FillSelection()` not resetting target tile properties when 'allow unused' is enabled and using empty tiles

- src/game/client/components/menus.h
- src/game/client/components/menus_browser.cpp
Also create the grayscale versions of community icons in the background jobs.
> Reduce FPS impact of community icon loading

- src/game/editor/popups.cpp
The selected value of the automap reference popup was previously always reset to "None" whenever opening the popup.
> Fix editor automap reference popup initial selection

- src/engine/client/client.h
- src/engine/server/authmanager.cpp
- src/engine/server/authmanager.h
- src/engine/server/server.cpp
- src/game/client/components/console.h
Previously, rcon keys could be added with usernames longer than 63 non-null characters, which would be truncated and could not be used.
Use same maximum length for the rcon username on the client side as on the server side, to allow authenticating with usernames of the maximum length.
> Add error message to `auth_add`/`auth_add_p` when username too long, increase length of rcon username to 64 bytes on client side

- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_browser.cpp
- src/game/client/components/menus_demo.cpp
- src/game/client/components/menus_ingame.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/components/menus_settings7.cpp
- src/game/client/components/menus_start.cpp
- src/game/client/ui.cpp
- src/game/client/ui.h
- src/game/client/ui_listbox.cpp
- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/editor_props.cpp
- src/game/editor/editor_server_settings.cpp
- src/game/editor/map_grid.cpp
- src/game/editor/mapitems/layer_tiles.cpp
- src/game/editor/popups.cpp
Closes #9772
Adds flags so that buttons can specify which mouse buttons they react to (LMB, RMB, MMB). This is how imgui does it for it's buttons. Buttons still return 1 to 3 for mouse clicks, just specyfying LMB makes it so the button won't react to other clicks at all
Hopefully, I didn’t miss anything, the editor's code is a big mess
> Add flags to button logic

- src/game/client/components/menus_settings.cpp
> add a slider to change prediction margin in the DDNet tab

- src/game/editor/mapitems/layer_tiles.cpp
Introduced by #9499, which wasn't a proper fix because `LAYERTYPE_GAME` is a layer type ID, not a group ID
Fixes #9765
Also fixes part 1 of #9507. Part 2 might be intentional, as teles and death tiles are on different layers. However, undo functionality for non-game layers is still broken
> Fix automapper seed crash

- src/engine/client/client.cpp
- src/engine/client/client.h
- src/engine/shared/config_variables.h
- src/game/client/gameclient.cpp
Render the graphs when `dbg_graphs` is enabled regardless of the `debug` option instead of only rendering them when both options are enabled, to also allow rendering only the graphs.
Move the alternative between the gameclient and editor rendering to the `CClient::Render` function. Move the `IGraphics::Clear` call to the beginning of the `CGameClient::OnRender` function, consistently with the `Clear` call in the `CEditor::OnRender` function.
> Support using `dbg_graphs` without `debug`, refactoring

- src/game/editor/mapitems/layer_tiles.cpp
- src/game/editor/popups.cpp
Fixes #9279
Closes #9507 (Part 1 was fixed in #9781, Part 2 is intentional as they are different layers, undo functionality has been fixed)
The tiles were being placed on the game/tele layer, which belongs to the game group.  `m_SelectedGroup` usually is the selected tile's group instead, so undo didn't work with it
Fixes #9770
Simply return when the popup's layer is deleted, as the popups would still reference the now deleted layer's data. Also fixed the same issue for the tele and switch layers
> Fix automapper undo and popup crashes

- src/engine/server/server.cpp
- src/game/server/player.cpp
Closes #9783
Adds so `hide_auth_status` also won't count you towards spectator counter
> Disable spectator count for hide_auth_status

- src/base/math.h
Remove redundant 'inline' specifier on a constexpr function. Change in_range function to return boolean.
> Refactor math.h

- src/game/server/gamecontroller.cpp
- src/game/server/gamecontroller.h
- src/game/server/player.h
Makes ddnet code base cleaner as these variables are unused. Also makes my downstream cleaner which implements team balancing.
> Remove unused team balance variables

- src/engine/client/input.cpp
- src/engine/client/input.h
- src/engine/input.h
Regression from #9659 which made `KEY_JOY_HAT*_RIGHT` the last joystick hat key, causing the loop to skip the left and right joystick hat keys.
> Fix left and right joystick hat keys

- src/game/client/gameclient.cpp
- src/game/server/entities/character.cpp
- src/game/server/gamecontext.cpp
Fixes #9753
I don’t know why fake tuning was always sent instead of the real one, since the very first jetpack prediction commit: https://github.com/ddnet/ddnet/commit/38b16ee5c096e7702413fa587db144ac97689432 Now it matches other fake tunings and seems to work correctly
Also partially reverted #9276 because it broke vanilla servers. I moved the code before the client receives tunings, since DDNet compatible servers send the jetpack strength tune. I've tested this on vanilla, servers both before and after this patch, and everything works well.
Fixing tune zone override, related: #8959
`SnapNewItem` that initializes `pDDNetCharacter` calls mem_zero, even though the default value should be -1. This caused every player's global tune to be considered overriden, which could be checked with …
> Fix jetpack tuning and incorrect tune zone override

- src/game/client/prediction/entities/character.cpp
- src/game/server/entities/character.cpp
As discussed in #9670, speedtiles can give so much speed, that they actually slow you down again (with ramp values). This PR introduces the `speed_boost_max_speed` tuning parameter, at which the speedtiles stop giving you extra speed.
`118` is the magic number, that has the highest default speed. It is depending on velramp values, but not easily calculable.
`0` simply deactivates this behavior and makes default behave like previously
@Jupeyy @Patiga @KebsCS
> fix new speedtiles: add speeder limit

- src/engine/shared/config_variables.h
- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_settings.cpp
- src/game/client/components/nameplates.cpp
- src/game/client/components/nameplates.h
* Id can be put onto new line with cl_nameplates_ids_line and sized with cl_nameplates_id_size
* Offset can be customized with cl_nameplates_offset
* cl_nameplates_own in ui
* Lots of checkboxes merged into sets of buttons
* No more flicker of nameplates in game
* Added dummy nameplate preview
* Its modular now
These show how the values change things, the UI part isnt completley accurate
> Rewrite nameplates again

- .clangd
The auto include of clangd saves a lot of time. But sadly it uses the wrong style for the includes. There is a option for clangd to force angled includes for everything. But that also does not match the ddnet style. Luckily [clangd 20 released 40 minutes ago](https://github.com/llvm/llvm-project/releases/tag/llvmorg-20.1.0) with the brand new config to specify which includes are angled.
https://github.com/user-attachments/assets/b284aebb-9e4d-457a-9901-5d6941853d7a
> Tell clangd to use angled headers

- src/game/client/components/nameplates.cpp
- src/game/client/components/nameplates.h
`m_pNamePlates` is now inited in constructer instead of OnInit so it can handle resize's before OnInit
Should close #9808 @Zwelf 
Also renamed `m_aNamePlates` to `m_pNamePlates`
> Trivial name plate changes to fix #9808

- src/game/client/prediction/entities/character.cpp
- src/game/server/entities/character.cpp
Makes it easier to reason about what the offset means and where it comes from.
At the cost of a longer line of code and slower compile time. Runtime should be unaffected.
This will make debugging easier if tune zones ever shift in value. Which they shouldn't because it is protocol breaking.
I debug printed the value and made sure it really is 38. Also did test setting the grenade fire delay in game and everything works as expected.
Relevant commits for context: 2b32b4a18a9637d7ae5a8d64b755c969b67c3127, bc1d293e3098cb04cb5a25bae131a633e87b83c8
> Get rid of magic number 38 to find weapon delay tune

- src/game/client/components/menus_ingame.cpp
The problem when are you playing vanilla/fng or any other gamemode with team the camera button overlap the "record demo button"
Fix #9587
provided 4:3 scratched screenshot:
> fix camera button overlap the "record demo button" in vanilla

- src/game/client/components/nameplates.cpp
(If you're looking for images for release notes goto #9601 )
Thanks to @Pioooooo for reporting this
Before:
* Transparency isn't applied to other players
* Directions are actually meant to be at the bottom
After:
> Name plate move direction to bottom again and fix direction transparency

- src/game/client/render_map.cpp
I've pushed this fix to #9835 too slow and it didn't get included in the merge queue 
Before:
After:
> Auto-resize tune tile text to fit inside the tile

- src/game/client/components/menus.h
- src/game/client/components/menus_demo.cpp
> Add size to demo list

- src/base/system.cpp
- src/base/system.h
- src/game/client/components/menus.h
- src/game/client/components/menus_start.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/editor/editor.cpp
- src/game/editor/quick_actions.cpp
- src/test/netaddr.cpp
Fixes #9746, Closes #9815 
Saves rcon password when starting a server and auths when joining a local ip server
Also, refactor the IsLocalAddress check, as it would have been repeated for the third time now
> Always automatically rcon auth on local server

- src/engine/client/input.cpp
It would go away after clicking anywhere, but it's confusing when that happens. This fix will clear all held keys when alt-tabbing. It’s still possible to keep holding hook by alt-tabbing, though I’m not sure why. But I guess that’s the desired behavior if anyone ever used it
> Clear key states on alt tab

- src/engine/client/backend_sdl.cpp
- src/engine/client/backend_sdl.h
- src/engine/client/graphics_threaded.h
- src/game/client/components/menus_settings.cpp
I got another bug (next PR which I'm not 100% how to fix correctly), which caused my client to calculate a DPI scale slightly lower than 1.
It then rounded that down to 0, and caused the crash with a division by 0.
My current understanding, which might be incorrect, is that:
- CanvasSize = GfxScreenSize = dpi-scaled window size
- ScreenSize = non-dpi-scaled window size
The first commit is changes that the displayed aspect ratio is calculated with the non-dpi-scaled window size. Scaled resolutions might get rounded, which in turn would produce non-standard aspect ratios.
This calculation is also done like 50 lines above the modified occurence. There, however, I'm unusure how to access the non-dpi-scaled window size.
The second commit passes around the dpi scale as a float instead of an …
> Improve High-DPI handling in 

- src/engine/client/backend_sdl.cpp
Followup to #9847 
`p(Width|Height)` = `g_Config.GfxScreen(Width|Height)`
`pCurrent(Width|Height)` = `m_Screen(Width|Height)`
I'm confused because before, m_Screen-size was initialized with a potentially scaled window size.
Afaik that was incorrect, but I might also be wrong.
This missing initialization caused the DpiScale to be calculated with an outdated GfxScreen-size, causing the crash.
With this pull request individually also fixes the crash.
Once again, I don't have a high-dpi monitor to test all of this.
> Initialize GfxScreen(Width|Height) on window init

- src/game/editor/editor.cpp
- src/game/editor/mapitems/layer_tiles.cpp
Adds the ability to change the speedup's angle (arrow direction) using Shift + Scroll. This is very useful for #9795, as it requires a lot of angle adjustments for smooth slides.
Also, when selecting a speedup or switch from the tile picker (holding spacebar), the tile's numbers and arrow direction will now be displayed. This is only visual, to match behavior with tele and tune layers
> Add shift+scroll to speedup layer, fix BrushGrab for speedup and switch

- CMakeLists.txt
This fixes client-only builds (regression after https://github.com/ddnet/ddnet/pull/9638).
> CMake: Fix build with SERVER=OFF and DOWNLOAD_GTEST=ON

- src/engine/client/sound.cpp
From #9857. The sound sample slot is supposed to be unloaded and unused when allocated.
> Fix crash due to changed sound sample assertion

- src/game/editor/editor_server_settings.cpp
Makes this button always clickable when settings are invalid, except for duplicates.
Before it was impossible to add a command with arguments that differed from the expected format. For example if a setting expected an integer but a string was input, or if the tune_zones command contained an unknown setting. This pr fixes that, unless there was a reason on why it worked like that
> Make "Allow all unknown settings" allow all settings

- src/game/editor/editor_actions.cpp
- src/game/editor/mapitems.h
- src/game/editor/popups.cpp
Previously if you were to change seed property of a layer, 10th element of [s_apNames](https://github.com/ddnet/ddnet/blob/94791b2d5007cd931703aee4d0d79613b443657e/src/game/editor/editor_actions.cpp#L849) array would be accessed.
> Add missing tile layer property

- src/game/client/ui.h
Initialize the field to fix valgrind warning:
```
==130041== Conditional jump or move depends on uninitialised value(s)
==130041==    at 0x7A0C5A: CEditor::DoColorPickerButton(void const*, CUIRect const*, ColorRGBA, std::function<void (ColorRGBA)> const&) (editor.cpp:3793)
==130041==    by 0x791D55: CEditor::DoToolbarLayers(CUIRect) (editor.cpp:1311)
==130041==    by 0x7BBDD3: CEditor::Render() (editor.cpp:8062)
==130041==    by 0x7C0D5A: CEditor::OnRender() (editor.cpp:9020)
==130041==    by 0x5002B9: CClient::Render() (client.cpp:1050)
==130041==    by 0x509E8D: CClient::Run() (client.cpp:3292)
==130041==    by 0x51275C: main (client.cpp:4940)
```
> Initialize color picker popup state field

- src/engine/client/backend_sdl.cpp
- src/engine/client/graphics_threaded.cpp
- src/engine/client/graphics_threaded.h
- src/engine/shared/config_variables.h
- src/game/client/components/menus_settings.cpp
Followup of #9848.
I still kinda hope this fixes #8691 and it was just bad dpi handling, if @def- or @edg-l is interested in testing this change on apple silicon with moltenvk.
I never could test dpi before, but now that wayland support is good enough i can test it. (`SDL_setenv("SDL_VIDEODRIVER", "wayland", 1);` before initializing the video sub module)
Fullscreen under wayland is broken, and I am certain SDL reports the wrong values here. (SDL3 will probably fix it, i looked into their video mode struct and they directly add the DPI value there).
I removed the gfx_highdpi config variable. Disabling it makes no sense to me ever. @Learath2, since you originally added it, if you disagree, go ahead.
> Fix some DPI handling

- src/engine/server/server.cpp
- src/engine/shared/network.h
- src/engine/shared/network_server.cpp
Remove `CNetServer::SendConnlessSixup` and use `CNetBase::SendPacketConnlessWithToken7` instead.
> Remove `CNetServer::SendConnlessSixup` method

- src/game/server/player.cpp
Usually when trying to vote an AFK to spectator on a server with `sv_pausable`, they will be force paused for `sv_vote_pause_time` (10s) and then they reappear automatically. This PR makes it so that the player has to explicitly exit spectator.
> Don't unpause when force pause timer is over

- src/game/server/ddracecommands.cpp
I use binds for `rcon left` `rcon right` `rcon up` and `rcon down` a lot and i found it quite annoying that i cant always reach some high spots with those binds due to gravity
I think those commands should resets the players velocity just like `telecursor` does
Before:
https://github.com/user-attachments/assets/739e21a9-0973-453d-8718-3d42a6396f04
After:
https://github.com/user-attachments/assets/27fa3d6a-efa3-4f57-877e-9c59e5d859a7
> Reset velocity when using move commands

- src/engine/shared/storage.cpp
- src/engine/storage.h
- src/test/datafile.cpp
- src/test/gameworld.cpp
- src/test/serverbrowser.cpp
- src/test/test.cpp
- src/test/test.h
- src/tools/config_common.h
- src/tools/demo_extract_chat.cpp
- src/tools/dummy_map.cpp
- src/tools/map_convert_07.cpp
- src/tools/map_create_pixelart.cpp
- src/tools/map_diff.cpp
- src/tools/map_extract.cpp
- src/tools/map_find_env.cpp
- src/tools/map_optimize.cpp
- src/tools/map_replace_area.cpp
- src/tools/map_replace_image.cpp
- src/tools/map_resave.cpp
Fix leak sanitizer warnings due to storage not being deleted in tools.
Improve error handling in tools when storage could not be initialized.
> Use `std::unique_ptr` for `IStorage` uses in tools and tests

- src/engine/client/client.cpp
- src/engine/client/client.h
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/engine/shared/fifo.cpp
- src/engine/shared/fifo.h
This pr makes `cl_input_fifo` and `sv_input_fifo` usable not only at startup of client/server.
Motivation:
I remember someone was setting up their servers and wanted to do something with fifo, but to use it they would have to restart the server where the players were playing. I thought it would be nice if it was possible to use fifo without restarting client/server.
> Make fifo commands usable from console

- .github/workflows/style.yml
This allows us to upgrade twmap without being bound by its upgrade schedule. It also fixes the current CI breakage.
> CI: Pin a specific twmap revision

- src/game/client/components/nameplates.cpp
> Change nameplate text outlines to have 0.5 opacity again

- src/game/client/components/nameplates.cpp
Strong/Weak hook id was equal to client id
> fix strong/weak hook id equals client id

- src/game/client/components/hud.cpp
- src/game/client/components/menus_settings.cpp
I also attempted to clean up the cursor code, I tested everything I could think off.
The only bug I found was with smooth dyncam not being exactly correct, but that isn't a regression
Just to make sure, @TsFreddie please check :)
For some reason, "DDNet Hud" shows on the left pane, that has been fixed
> Move DDRace HUD title to correct pane, Refactor in game cursor rendering

- src/game/editor/editor.cpp
Fixes #6021 (2nd bug doesn't happen and comment has already been fixed, as it already has check that only 1 quad can be selected)
The `PopupLayer` function uses `pEditor->GetSelectedLayer(0)` to determine which layer's info to display. Which returned the first selected layer when multiple layers were selected, rather than the one that was right-clicked. This fix simply puts the right-clicked layer to the first index
> Fix wrong popup opened with multiple layers selected

- src/game/client/gameclient.cpp
This reverts commit 386d456484350a14f6c01a0773e05ed4ed9a4693.
Fixes #9703. Reopens #8895.
> Revert "Fix vanilla demo tuning"

- src/game/editor/editor.cpp
- src/game/editor/mapitems/layer_speedup.cpp
- src/game/editor/popups.cpp
This adds so it's now possible to flip and rotate the speedup arrow (R,T and N,M keybinds)
https://github.com/user-attachments/assets/2db22663-ef34-459e-959f-56571d9697c5
> Add flip and rotate to speedup arrow angle

- src/game/editor/mapitems/layer_game.cpp
Fixes #9907
Just adds the front layer creation to undo history
> Fix undo for hookthrough's front layer

- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_settings.cpp
- src/game/client/components/skins.cpp
- src/game/client/components/skins.h
Move list for displaying skins in user interface and favorite skin handling to `CSkins` to simplify the usage.
Simplify skin list sorting by considering the favorite state within the comparison function instead of using two lists.
> Move skin favorite and UI list handling to `CSkins`

- src/engine/shared/config_variables.h
- src/game/client/components/maplayers.cpp
- src/game/client/render.h
- src/game/client/render_map.cpp
- src/game/editor/mapitems/layer_tiles.cpp
Currently you can either turn text entities on or off. This PR allows to do this for the editor individually
`cl_text_entities` does not affect the editor anymore.
In the editor only `cl_text_entities_editor` works
Here _some_ old screenshots:
Teleports On/Off:
Speedtiles On/Off: (Note, the arrows stay deliberately)
Switches On/Off:
Editor Text Entities On/Off:
This is part of #9698 but does not close it.
closes #6505, #7893
An UI Option for this might be a followup
> Add more options to show and hide text overlays for entities

- datasrc/datatypes.py
- datasrc/network.py
This makes it more obvious at the call site what the parameter is for.
> network.py: Make `default` an explicit keyword argument

- src/base/system.cpp
- src/base/system.h
- src/engine/client/client.cpp
- src/game/client/skin.cpp
- src/test/str.cpp
Add `str_valid_filename` function to check for valid filenames of skins and maps before attempting to load them to reduce cross-platform incompatibility.
Closes #6892. This issue was seemingly already resolved on the server-side, but this change will additionally ensure that skins with leading, trailing or multiple consecutive spaces will not be loaded. Checked with the names of all skins in the official database to ensure they are all considered valid.
See also #3529.
Implementation references:
- https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations
- https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file
> Add `str_valid_filename` function: improve skin and map name validation, improve tests

- src/game/client/components/items.cpp
- src/game/client/components/items.h
- src/game/client/components/menus.cpp
Decouples Laser-Rendering from Laser object and introduces various optimizations. Some variables are moved into their context and the decoupling creates a lower complexity.
The door-twitch-fixing is removed by setting a fixed tick, since the state of the door is indicated differently anyway.
Also allows a followup for #9057
> Fix switch door twitching (and refactor)

- src/engine/client.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/engine/client/discord.cpp
- src/engine/discord.h
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- It will now display the server name, map name, and the number of players
- You can join and invite others to your server. However, joining without Steam sometimes does not automatically open the game, I'm not sure why. When game is open it will automatically connect
> Update Discord Rich Presence

- src/game/editor/editor.cpp
Ensure that the sound preview is updated when replacing/re-importing sounds.
> Fix editor crash when replacing/re-importing sound

- src/engine/shared/map.cpp
close #9630 
~~Use PRIzu is better than zu. Because using zu can be unexpected on older compilers such as MINGW32~~
> Used (int) cast for sizeof(CTile) instead of %ld to print it correctly

- src/antibot/antibot_data.h
- src/antibot/antibot_interface.h
- src/antibot/antibot_null.cpp
- src/engine/antibot.h
- src/engine/server/antibot.cpp
- src/engine/server/antibot.h
- src/engine/server/server.cpp
- src/game/server/entities/character.cpp
- src/game/server/gamecontext.cpp
Currently there is a limited amount of variables you can analyze in your antibot. This PR adds all of the inputs instead of just the aim position.
This also passes the SixUp, DNSBL and authed state to the antibot to be able to make special cases with those.
Reopen of the PR #9096
> Pass more data to the antibot

- src/engine/client/discord.cpp
Fixes #9954
It should fix it, but could you test it @def- I can't build 32 bit because of rust
> Fix Win32 build fail with Discord

- src/game/client/components/items.cpp
- src/game/client/components/items.h
- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/mapitems/layer_group.cpp
Doors are not intuitive to map, since you set an origin (door) tile and a length tile next to it. This is worse with 45° doors. This PR introduces door-entities to the editor preview. It only applies to doors (not grabber or freeze doors) and only for fixed length. Feel free to do a follow up for more switch tiles.
follow up of #9057
Screenshots:
Test map:
[switch_test.zip](https://github.com/user-attachments/files/19471923/switch_test.zip)
> add doors to editor preview

- src/engine/client/client.cpp
Fixed crash when local server was running and opening a demo, the state would still be `STATE_LOADING` instead of `STATE_DEMOPLAYBACK`, which caused crash trying to Rcon auth.
Should be included in 19.1 as this feature is being released in it
> Fix auto rcon auth crash when opening demo

- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
Make sure other `shared_ptr`s to the skin info of client data that is being reset will not use the refresh callback that refers to the reset client data by also unsetting the refresh callback.
> Fix client crash when skin download finishes while player leaves

- src/game/client/components/nameplates.cpp
- src/game/client/components/nameplates.h
Nameplate not major refactoring
* Use RAII
* Use array for nameplates instead of raw ptr
* Use vec2 everywhere instead of X and Y
* Rename CNamePlateData to CNamePlateRenderData
* Few other things
> Nameplate not major refactoring

- src/base/system.cpp
- src/engine/client/backend_sdl.cpp
closes #9961
no idea how to approach furo's suggestion, so i left it out.
From what i could tell it would be a redefinition of dbg_assert to enforce using format specifiers? - i could basically copy the style of `str_format_opt` for it i assume, not sure if i should do that here.
> let dbg_assert format the string

- src/engine/shared/translation_context.h
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
> Remove unused `m_SkinColor` variables from client data

- src/game/client/components/console.cpp
- src/game/client/components/console.h
A friend of mine asked me if there was a way to get to the newest/latest line in console on a 60% keyboard, so I thought of making peoples lives easier who cant afford the other 40% of their keyboard and make this simple thing
Btw I have no clue how pr's work
> Add Console commands to go to the latest/newest Line

- src/game/client/components/menus_settings.cpp
I think there might be some issues with the design here. @SollyBunny 
1. When in main character mode (g_Config.m_ClDummy == 0):
- Checking this box shows the dummy's nameplate (as expected)
2. But when in dummy mode (g_Config.m_ClDummy == 1):
- Checking this box instead displays the main character's nameplate (which contradicts the text description)
This appears to be an intentional design choice, but nowhere else in the menu settings are there similar configurations. Instead, each setting requires manual selection to change between dummy and main character options.
> Dynamic nameplate preview description

- src/game/client/components/nameplates.cpp
- src/game/client/components/nameplates.h
* Fix directions adding padding when invsibible after being visible (great explanation), closes #9986 
* Fix color not updating on strong weak id, supercedes #9936 (thanks @Hoco4ekc)
* Rename `HOOKSTRONGWEAK_UNKNOWN` TO `HOOKSTRONGWEAK_NEUTRAL`
To reproduce:
```
connect 45.141.57.22:8300 # any server with strong/weak
cl_show_direction 3 # or have yours previously enabled
dummy_connect
cl_show_direction 0
```
| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/079b4cd1-3113-41a4-804b-425478247aa0) | ![image](https://github.com/user-attachments/assets/9fbbe921-be82-405b-9c89-2e504791f327) |
> Name plate fixes

- src/engine/client/favorites.cpp
Add check so it doesn't add a dummy favorite server entry that I didn't figure out how to remove in game when using `end_favorite_group` before adding any favorite server.
I don't know what is a favorite group and what it's used for btw...
> Don't allow empty favorite group

- src/engine/shared/config_variables.h
- src/game/client/components/items.cpp
- src/game/client/components/menus.cpp
- src/game/client/components/menus_settings.cpp
Use a custom color for grabbers as well, make them different from doors. Previously doors and grabbers shared the same color.
Requested by @SollyBunny
Also reworks the settings page laser a bit
Screenshots:
> make grabber color customizable

- src/game/client/components/players.cpp
fix #9977 
Since the number of spectators is usually small, this modification will not have a noticeable impact on game performance.
> Fix spec-char not visible sometimes

- src/game/client/components/camera.cpp
Clamping the dyncam when auto-sync is enabled so tees stay on screen.
Fix the camera glitching out when a client/server send weird cursor position while having dyncam on.
(The glitch currently is known to show up when spectating taterclient with improve precision and dyncam on)
The offset limit is arbitrarily selected by eyeballing the tees position.
Video shows a modded server sending `Target * 1000.0f`. (top left regular player, bottom right spectator)
https://github.com/user-attachments/assets/6d0576af-6397-4daf-8ed0-eaa4f667639f
> Limit dyncam offset for auto-sync camera

- src/base/system.h
- src/base/types.h
- src/engine/client.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/engine/shared/network.h
- src/engine/shared/network_conn.cpp
- src/game/client/components/hud.cpp
- src/game/client/components/hud.h
- src/game/client/components/items.cpp
Improve layout of debug information to improve readability. Also render frametime in addition to FPS.
See commit messages for refactorings.
Screenshots:
- Before: 
- After: ![image](https://github.com/user-attachments/assets/a4561dfa-c98c-49bc-938f-41c35f410e3b)
> Improve layout of debug rendering, refactoring

- src/game/editor/editor.cpp
- src/game/editor/editor_actions.cpp
- src/game/editor/editor_trackers.cpp
- src/game/editor/mapitems/layer_front.cpp
- src/game/editor/mapitems/layer_game.cpp
- src/game/editor/mapitems/layer_group.cpp
- src/game/editor/mapitems/layer_speedup.cpp
- src/game/editor/mapitems/layer_switch.cpp
- src/game/editor/mapitems/layer_tele.cpp
- src/game/editor/mapitems/layer_tiles.cpp
- src/game/editor/mapitems/layer_tiles.h
- src/game/editor/mapitems/layer_tune.cpp
- src/game/editor/mapitems/map_io.cpp
- src/game/editor/popups.cpp
close #9921
I rename `m_Tele`, `m_Speedup`, `m_Front`, `m_Switch`, `m_Tune` and `m_Game` and change their types to `bool`.
I change `pLayer->m_Tele <= pBrushLayer->m_Tele` to `!pLayer->m_Tele || pBrushLayer->m_Tele`
For `m_Game`, I think it has similar logic as other variables, so I change it too.
The only suspicious assignment is here. Other than that, `m_Game` is used as a `bool` variable:
``` cpp
pTiles->m_Game = pTilemapItem->m_Flags & TILESLAYERFLAG_GAME;
```
But I think it can still be regarded as a `bool`.
Almost all variables were renamed using the IDE, except for these two parts, which were manually modified:
one `static_pointer_cast` 
```cpp
const bool HasTeleTiles = std::any_of(m_pBrush->m_vpLayers.begin(), m_pBrush->m_vpLayers.end(), [](auto pLayer) {
return pLayer->m_Type == …
```
> refactor(editor): change some variable names and types in CLayerTiles

- src/game/client/components/skins.h
Fix favorite skins being ordered randomly in the config file due to use of `std::unordered_set`.
> Consistently order favorite skins in config file

- src/game/client/components/nameplates.cpp
- src/game/client/components/nameplates.h
* Remove unused headers in `nameplates.h`
* Use a class enum for hook strong/weak state
* Rename `m_HookStrongWeak` to `m_HookStrongWeakState`
* Remove default `UpdateNeeded` method for text parts (prevent mistakenly updating every frame)
* Use previous name plate size calculation if no update occurs (reduces iteration through name plate parts by 25%)
* Rename local var `Size` to `LineSize` in name plate `Render` and `Update` functions
* Don't update preview name plate twice before render
> Minor name plate changes

- src/game/server/entities/character.cpp
> Fix border not killing when overlapped with death tile in practice mode

- src/game/client/components/camera.cpp
Fixes multi-view not zooming at all, both in game and demo. The if is executed only when stopping spectating player, or zooming in multiview, in which `m_UserZoomTarget` was overwriting the correct zoom.
> Fix multi-view zoom

- src/engine/gfx/image_manipulation.cpp
- src/game/client/components/skins.cpp
The first change fixes #9545. The second change is to use luma when converting images to grayscale, which preserves the perceived brightness of colors and results in more natural looking gray shades. This affects mainly skins, but also some minor assets that use the grayscale function as well.
> Improvements to recoloring of skins

- src/engine/server/databases/connection.h
- src/engine/server/databases/connection_pool.cpp
- src/engine/server/databases/mysql.cpp
- src/engine/server/databases/sqlite.cpp
- src/game/server/scoreworker.cpp
- src/test/score.cpp
Tested it in game and it works so far so good.
Fixed the [ddnet code style](https://github.com/ddnet/ddnet/blob/c0d34923d04a15d119eb48d6d3e984108334576d/CONTRIBUTING.md#use-true-for-success) violation of using false for success.
Closed https://github.com/ddnet/ddnet/issues/9890
This will be annoying for downstreams that make use of the sql code from ddnet. So the entire diff in scoreworker.cpp was generated with a ruby script which can be run by downstreams after the merge too so they do not have to manually rewrite their entire sql code.
https://github.com/ddnet-community/src-upgrade-scripts/blob/master/sql_true_for_success.rb
It worked flawlessly for the ddnet code base.
I tested the ruby script in the following ruby versions:
- 2.6.10 shipped by macOS by default
- 2.7 shipped by …
> Use true for success in sql code

- src/engine/client/serverbrowser.cpp
Do not return early when encountering first 0.7 address in `ServerBrowserFormatAddresses` function to correctly handle 0.7 servers with multiple addresses (e.g. IPv4 and IPv6).
Use `str_append` function instead of moving the buffer position manually to improve readability.
> Fix 0.7 connect string for servers with multiple addresses

- src/engine/client/serverbrowser.cpp
> Fix incorrect connect address for local servers

- README.md
Due to https://gitlab.kitware.com/cmake/cmake/-/issues/16395 the CMake Ninja generator will incorrectly escape dollar signs which breaks the required build option `-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[\\$autoResumeAudioContext,\\$dynCall]` specified in `Emscripten.toolchain`.
> Switch back to Makefiles for Emscripten in README again

- src/engine/shared/network_server.cpp
Spam bots are not normal clients, they just use random ports, getting past the connlimit.
Maybe we can also look into improving this connlimit algorithm later, currently it has a limit of 16 ips, `Connlimit` happens way before DNSBL, so one could use proxies to push their legit ip out of the list.
> Ignore port when limiting connections

- src/engine/server/server.cpp
- src/engine/server/server.h
Fixes server crashing when the 0.7 server info is requested containing more than 38 players with names and clans of maximum length.
Only pack as many clients into the 0.7 server info as will fit into a packet. The client count in the server info must be equal to the included number of client entries, so the entire server info is repacked with a reduced number of clients to ensure that 0.7 clients will still accept it. The real number of players is appended to the server name like for the existing `SERVERINFO_VANILLA` when not all clients could be included.
Closes #10064. Supersedes #10065.
> Fix 0.7 server info too large with many player and long names

- src/game/client/components/players.cpp
- src/game/client/components/players.h
The function `GetPlayerTargetAngle` gets the current angle a player is looking at for rendering the tee and for hud
Currently in `players.cpp` a check is done for local client to just use the current input data
However in `hud.cpp` this check is not present so the angle shown is not the angle that is rendered, which I feel was the intention and what it should be
This puts that check into the `GetPlayerTargetAngle` function
> Players cpp outline direct input

- src/base/color.h
- src/engine/client/client.cpp
- src/engine/console.h
- src/engine/shared/demo.cpp
- src/game/client/components/binds.cpp
- src/game/client/components/console.cpp
- src/game/client/components/console.h
- src/game/client/components/menus_browser.cpp
- src/game/client/components/nameplates.cpp
- src/game/editor/editor.h
- src/game/editor/editor_props.cpp
- src/game/editor/editor_server_settings.cpp
- src/game/editor/editor_server_settings.h
Refactored `color4_base` to use a member initializer list instead of assignments, and changed `const` to `constexpr` where appropriate.
Since ddnet uses C++17, `constexpr` constructors can't have assignment bodies unless all members are trivial, which broke usage in `constexpr` contexts. This can be seen in [#10072](https://github.com/ddnet/ddnet/pull/10072/files#diff-759f13e95473ef7d2ce66a299c2b04f1024e2c55a1c20a5f03ee8c2b92c44239R18-R45) where `ColorRGBA` had to be declared as functions instead of values.
> Fix color constexpr constructor

- src/game/client/components/maplayers.cpp
- src/game/client/components/maplayers.h
Part 4 of #10004, and finally touch OnRender. This PR does a lot of things:
- Moves GameLayer to the Entitiy Render logic
- Introduces generalized tilelayer rendering with and without buffer
- Call generalized tilelayer rendering also for non entities
- Early exit if we don't want to render anything
This will probably be the most controversial refactoring yet
Sorry for the bigger PR, i already broke this down a lot with the previous ones
> Refactor: Maplayers tidy up OnRender

- src/game/client/prediction/entities/character.cpp
- src/game/client/prediction/entities/character.h
Fixes the global jetpack tune. The `m_LastJetpackStrength` logic was incorrect.
When `CNetObj_DDNetCharacter` was available, it always incorrectly used the default value of 400.f for the global tune. Now, when it's unavailable, it will also correctly handle `jetpack_strength`'s negative values 
Before:
https://github.com/user-attachments/assets/5e45e77a-15ee-4b34-8cb3-b5bedb67539c
After:
https://github.com/user-attachments/assets/11faedf7-3f7d-4e1f-b057-faea22fdfc41
> Fix global jetpack tune

- CMakeLists.txt
- src/game/client/prediction/entities/door.cpp
- src/game/client/prediction/entities/door.h
- src/game/client/prediction/entity.h
- src/game/client/prediction/gameworld.cpp
- src/game/server/entities/door.cpp
Fixes #1279
No more laggy, unpredicted doors
https://github.com/user-attachments/assets/2fe62706-a228-4476-9211-6a44a36aed4c
> Add laser door prediction

- src/game/client/components/maplayers.cpp
closes #10076 
Tilelayers were skipped before counted. This was a tilelayer-counting issue. One of my planned optimizations is doing this in OnMapInit preventing issues like that in the future.
> Fix only show entities

- src/engine/client/backend_sdl.cpp
- Use `log_*` functions instead of `dbg_msg`.
- Log more details when unable to get screen modes.
- Log if OpenGL ES is being used instead of OpenGL to aid debugging.
- Log `SDL_GetError` before calling `SDL_DestroyWindow`, as this may override the previous error.
- Replace unreachable debug messages with assertions.
- Remove unnecessary log messages when render surface is destroyed and created on Android. These happen every time the app is paused and resumed.
> Improve graphics log messages and assertions

- src/game/client/components/maplayers.cpp
- src/game/client/components/maplayers.h
There are multiple ways that maplayers can be optimized, this PR implements 2 obvious ways:
- pre-calculate Tilelayer and Quadlayer indices
- calculate start and end indices for foreground and background (foreground benefits most)
- optimize `RenderTileLayer`, because it's a hot path for rendering
|           |   #frames old |   FT old avg. (µs) |   FT old min (µs) |   FT old max (µs) |   #frames new |   FT new avg. (µs) |   FT new min (µs) |   FT new max (µs) |   Improvement avg. (%) |   Improvement min (%) |   Improvement max (%) |
|:----------|--------------:|-------------------:|------------------:|------------------:|--------------:|-------------------:|------------------:|------------------:|-----------------------:|----------------------:|----------------------:|
| dm1       | …
> Refactor: Optimize maplayers

- src/game/client/ui_listbox.cpp
fix #10077
The original code incorrectly added the offset `1` to the base index `0` and did not handle EDGE CASE separately.
> fix listbox navigation index

- src/base/system.cpp
- src/base/system.h
- src/base/unicode/tolower.cpp
- src/engine/client/backend_sdl.cpp
- src/engine/client/client.cpp
- src/engine/engine.h
- src/engine/server/main.cpp
- src/engine/shared/config_variables.h
- src/engine/shared/engine.cpp
- src/engine/textrender.h
- src/game/client/component.h
- src/game/client/components/menus_settings.cpp
- src/game/client/components/skins.cpp
- src/game/client/components/skins.h
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/test/gameworld.cpp
- src/test/str.cpp
https://github.com/user-attachments/assets/75699008-1bc1-48e2-a410-de00ff476f4e
Skin Loading and Unloading
--------------------------
Instead of loading all skins from the `skins` folder immediately, only scan the folder to determine which skins are available and lazily load skins when they are being used. Skins not present in the `skins` folder are loaded from `downloadedskins` or downloaded.
Load all skin data (image data, image data in grayscale, metrics, blood color) is background jobs, so in the main thread we only need to upload the skin data to the GPU and add the skin to the map.
Start background jobs to load vanilla skins (including special skins) immediately so this base set of skins is available directly. All other skins are only loaded on demand.
Load the `default` skin …
> Dynamic skin loading and unloading, improve skin list UI

- src/game/client/components/menus.cpp
- src/game/client/components/menus_demo.cpp
- src/game/editor/editor.cpp
- src/game/editor/popups.cpp
Show error message when using an invalid filename in the following dialogs:
- Editor save file dialogs
- Editor new folder dialog
- Slice demo dialog
- Rename demo dialog
- Render demo dialog
- Save 0.7 skin dialog
To prevent invalid filenames from being used in the future.
> Show error message when saving files with invalid filename

- src/game/editor/mapitems/layer_speedup.cpp
This PR properly resets speedtiles if erased. This may have caused various issues in the past
closes #10087
> fix editor from placing invalid speedtiles on erase

- CMakeLists.txt
- other/versioninfo/versioninfo.rc.in
See https://learn.microsoft.com/en-us/windows/win32/menurc/versioninfo-resource for details about the format.
Closes #6203.
Screenshots:
- Settings app: 
- Client properties:
- Server properties:
> Add version info to client and server executable on Windows

- src/engine/client/input.cpp
fix #10090 
but this will allow key release events to be received while the IME is open, and I haven't found this to cause any other issues.
> Allow key release events during IME composition

- CMakeLists.txt
- cmake/toolchains/Emscripten.toolchain
Specify `--preload-file data` linker flag to preload data directory into the filesystem in the `CMakeLists.txt` file as an additional target link option instead of specifying it in the `Emscripten.toolchain` file, as the latter caused the CMake configuration steps to fail due to the `data` folder being missing during this phase:
```
error: data does not exist
em++: error: '/emsdk/upstream/emscripten/tools/file_packager cmTC_83f35.data --from-emcc --preload data' failed (returned 1)
```
This was causing the CMake configuration phase to take longer, but building seemed to work anyway because it eventually falls back to some working defaults.
> Fix Emscripten CMake configuration due to `--preload-file`

- src/engine/shared/config_variables.h
- src/game/client/components/menus_settings.cpp
- src/game/client/components/nameplates.cpp
- src/game/client/components/nameplates.h
* Reduce max distance from 100 to 50 as it can give a large advantage in pvp modes (requested by jupy)
* Don't check actual size as it's quite expensive to compute for little gain
* Remove offset to directions as it causes inconistent spacing (and people don't like it)
* Fix offset changing and being incorrect in preview depending on size of nameplate (thanks :melon:)
* Remove `Size()` caching as it's unused (also now const)
* Add `s_DefaultPadding = 5.0f`
* Seperate out Update()
* Add `dbg_assert`s when trying to Render or get Size of uninited nameplates
* `Pos` -> `Position`
* Move position from `Data.m_Position` to an argument
* Remove `Offset()`/`m_Offset` as it's unused
> Nameplate fixes

- src/game/editor/editor.h
Fixes invalid comparator crash when sorting by `Time modified` in editor's `Load` map
> Fix crash when sorting in editor load

- src/game/client/components/maplayers.cpp
- src/game/client/render_map.cpp
Correcting behaviour added in #10088. Some game modes use a speedup layer for custom (non boost) tiles, but rendering these tiles in-game can cause visual arrows trash. Therefore, PR skips all unsupported tiles during rendering.
> Hide unsupported speedup tiles from game

- src/base/system.h
Should only change comments in system.h
Use jsdoc everywhere
Fill in some etxra comments
Have a consistent style for jsdocs
```
/**
* @todo DOCUMENT
*
* @ingroup Network-General
*/
int net_socket_read_wait(NETSOCKET sock, int time);
```
I'm not really sure what this does
> Cleanup documentation in system.h

- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
Fixes #6138
Global tunes are set with the `tune` command, not `tune_zone` so they weren't loaded from the map settings. In game they were handled by `NETMSGTYPE_SV_TUNEPARAMS` putting them to world tunes, but it's not implemented in demos. See #9798 for more info (tune and tune_zone currently have split implementation, even though they work the same)
> Fix incorrect global tunes in demo player

- src/game/client/gameclient.cpp
Should not change any viewable behaviour (Changing the magic numbers to floats may reduce multiplication precision, but not by much)
* Better variables names
* Use {} when other clauses have {}
* Always use floats for float operations
* Random small stuff
> Clean multiview in gameclient.cpp

- src/game/editor/auto_map.cpp
- src/game/editor/auto_map.h
- src/game/editor/popups.cpp
Show "(unknown)" instead of nothing if a map uses an automapper rule index for which no rule is available locally.
Reduce unnecessary margin at bottom of popup.
Fix popup scrollbar being too wide.
Screenshots:
- Unknown rule:
- Before: 
- After: 
- Scrollbar and spacing:
- Before: 
- After:
> Minor improvements to editor automap rule popup

- src/game/client/components/menus_settings7.cpp
- src/game/client/gameclient.cpp
- src/game/client/render.cpp
> Fix 0.7 skin offset being based on 0.6 skin data, fix assertion error due to 0.6 skin info used on 0.7 servers

- src/engine/demo.h
- src/engine/server/server.cpp
- src/engine/shared/demo.cpp
- src/engine/shared/demo.h
- src/game/client/components/menus.cpp
- src/game/client/components/menus_demo.cpp
- src/game/client/gameclient.cpp
Separated from #10128. See commit messages.
> Ensure demo playback starts at time 00:00, fix unsmooth server demo recording on empty servers, various refactoring

- src/base/system.h
Introduced by 9febf58. According to https://stackoverflow.com/a/7297011 the macro `__USE_GNU` should never be defined in user code but instead `_GNU_SOURCE` should be defined to enable desired features. However, neither definition are required for compilation anymore.
> Remove unnecessary and incorrect definition of `__USE_GNU`

- src/game/client/components/chat.cpp
*Might close* #10145
Adds more fixes, which are this time, hopefully fixes
(original issue was `CurrentLine = m_aLines[m_CurrentLine];` is a copy!!!)
> Fix #10141 (cleanup chat)

- src/engine/shared/config_variables.h
- src/game/client/components/items.cpp
- src/game/client/components/menus_settings.cpp
As reported by @Jupeyy the dragger defaults are currently very saturated. This PR introduces a lighter color which matches other entities more.
(also some renaming duh)
New color:
> Dragger followup, make draggers lighter

- src/engine/shared/config_variables.h
The config variables `cl_kill_message_normal_color` and `cl_kill_message_highlight_color` were declared with `CFGFLAG_COLALPHA` to indicate the values include alpha components, but the default color values would be have been considered transparent instead of white. However, the values were always used without alpha when rendering the kill messages, so this only had the effect of the color value being displayed incorrectly in the console.
> Remove incorrect alpha flag for kill message config variables

- README.md
I don't know about CentOs/RedHat/Alma Linux but fedora doesn't support python2 anymore
> readme.md remove python2 dependency

- src/android/android_main.cpp
When unpacking the assets from the APK, also delete unused files from the `data` directory instead of only adding new files.
> Delete unused `data` files on Android when unpacking assets

- .github/workflows/style.yml
- scripts/export_settings_commands_table.py
Rewrite scripts from https://github.com/ddnet/ddnet-scripts/tree/master/client for exporting the HTML tables of the settings, commands and tunings in Python to significantly improve the readability, extensibility and performance.
Fix duplicate table rows for game commands, as they are also registered on the client side for prediction.
Fix constants `SERVER_MAX_CLIENT` and `SERVER_TICK_SPEED` not being replaced with their numeric values anymore.
Fix description strings containing quotes being truncated or entirely missing.
Order all settings, commands and tunings alphabetically instead of arbitrary based on the order in which the files are enumerated.
Add preview for default values of color settings.
Add strict error handling instead of ignoring errors and silently omitting or mangling …
> Rewrite and improve settings & commands export script

- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/mapitems/layer_switch.cpp
- src/game/editor/mapitems/layer_switch.h
- src/game/editor/mapitems/layer_tele.cpp
- src/game/editor/mapitems/layer_tele.h
- src/game/editor/mapitems/layer_tune.cpp
- src/game/editor/mapitems/layer_tune.h
- src/game/editor/popups.cpp
> Move editor `FindNextFree*Number` functions to layers' classes, remove unnecessary `virtual` of editor layer functions

- src/engine/shared/filecollection.cpp
Fix by @Filoqcus from https://github.com/DDNetPP/DDNetPP/pull/443
> Fix invalid buffer size passed to str_timestamp_ex

- src/engine/client/backend_sdl.cpp
- src/engine/client/backend_sdl.h
- src/engine/client/graphics_threaded.cpp
- src/engine/client/graphics_threaded.h
- src/engine/client/input.cpp
- src/engine/client/input.h
- src/engine/graphics.h
- src/engine/input.h
- src/game/client/components/console.cpp
- src/game/client/ui.cpp
Open the screen keyboard again after it was closed when selecting a text input. Otherwise the console needs to be closed and reopened to reveal the screen keyboard again.
> Reveal screen keyboard after selecting text input if closed

- src/game/client/components/ghost.cpp
> Fix client crash due to invalid ghost skin data

- src/engine/client/input.cpp
> Fix moving a temporary object prevents copy elision [-Wpessimizing-move]GCC

- src/game/editor/mapitems/layer_tele.cpp
Fixes #10183
The function that searches for a tele with given number will ignore all teles that don't use numbers - `IsTeleTileNumberUsedAny`
> Fix view in tele popup for checkpoint teleports

- src/game/client/components/camera.cpp
>  Fix CCamera::SetView clamping y pos with map width instead of map height

- src/game/editor/mapitems/layer_tiles.cpp
Followup of #10175 : Tune, Switch and Tele-tiles do not contain all tile data in the brush. This could cause future rendering problems, as their indices are 0
> Fix editor brush not containing all tile data

- src/test/test.cpp
Before those changes `TestDeleteTestStorageFiles()` failed to remove a subdir with a file because it tried to remove parent dir before the subdir (due to a bug in `CTestInfoPath` comparison operator).
Added a simple test to validate the issue and the fix (the test fails without the change in `CTestInfoPath`).
> Tests: Fix temp files cleanup

- src/test/fs.cpp
- src/test/io.cpp
- Test that opening multiple shared file handles works.
- Test `fs_is_file` and `fs_is_dir` functions.
- Test `fs_remove` and `fs_rename` functions in various cases, in particular using open file handles.
> Add more tests for IO and filesystem functions

- src/tools/map_diff.cpp
The tool printed `apTile[0][Pos].m_Flags` twice. It should use `apTile[1]` for the counterpart Flags value.
The fix is in commit 3246b54. The other two commits are optional.
> map_diff: Fix misleading 'flags' in the diff output

- src/android/android_main.cpp
- src/base/system.cpp
- src/engine/client/client.cpp
- src/engine/shared/storage.cpp
- src/game/editor/editor.cpp
- src/test/fs.cpp
Change `fs_remove` and `fs_removedir` functions to succeed also when the file or folder to be removed does not exist in the first place, to avoid checking separately whether the file or folder exists.
Add more detailed OS-specific error messages for filesystem functions and remove less detailed error messages from storage wrapper functions.
> Allow removing nonexistent files/folders, improve error handling

- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_demo.cpp
Also show the play/pause and speed HUD when using the `demo_play` and `demo_speed` commands instead of only when using the hard-coded space and arrow hotkeys.
> Show demo play/speed HUD for `demo_play`/`demo_speed` commands

- src/game/client/components/touch_controls.cpp
- src/game/client/components/touch_controls.h
Previously, when a command executed by a touch button caused a touch button to become invisible, the direct touch input was incorrectly activated by the still pressed finger of the invisible button. For example, when touching a bind behavior button with command `dummy_disconnect` and visibility `dummy-connected`, the button would become invisible due to the dummy being disconnected, but the direct touch action, e.g. fire, would incorrectly be activated as well. This is prevented by storing the touch fingers of touch buttons that became invisible until the fingers are released.
> Prevent direct touch when active touch button becomes invisible

- src/game/client/prediction/entities/character.cpp
- src/game/client/prediction/entities/character.h
- src/game/server/entities/character.cpp
#237
The client can't predict the random tele out, that's why only 1 exit
Thanks to this, the game feels much more responsive, especially with high ping
> Add teleport prediction when 1 exit

- CMakeLists.txt
- src/game/client/prediction/entities/plasma.cpp
- src/game/client/prediction/entities/plasma.h
- src/game/client/prediction/gameworld.cpp
- src/game/server/entities/plasma.cpp
Updated the plasma snap to now send the target's ID instead of always sending -1, allowing the client to predict it.
On old servers, where the snap will still be -1 it will simply be not predicted, because -1 is not a valid client id.
https://github.com/user-attachments/assets/641ff445-3ada-4f54-a5d8-1e2b7791c4e4
> Add turret prediction

- src/engine/shared/datafile.cpp
Instead of failing to load maps with data of size `0`, only warn when loading the map and fail to load the individual data.
Closes #10257.
> Allow loading maps with data size `0`, fail loading data instead

- src/game/client/components/players.cpp
- src/game/client/prediction/entities/character.cpp
Also predicts the ninja powerup skin. I recorded it and checked frame by frame, the skin correctly disappears on the same tick as the freeze bar
Before:
https://github.com/user-attachments/assets/6ed4f291-7c57-4d39-9ea7-ffd62dbccf9f
After:
https://github.com/user-attachments/assets/48ce39e5-ea86-47a8-a1df-5cecc9385857
> Predict ninja skin in freeze

- src/game/client/components/nameplates.cpp
Big 0.7 names could be cutoff in the nameplate
> Use protocol7 sizes for clan and name to prevent cutoff

- CMakeLists.txt
> Add `advapi32` Windows library to fix Rust test linking in release

- src/engine/client.h
- src/engine/client/client.cpp
- src/engine/client/client.h
- src/game/client/components/menus.cpp
Show error message if the points for the initially chosen player name could not be determined, e.g. because no internet connection is available. Previously, the popup did not indicate errors and incorrectly showed yes and no buttons also while the points are being checked, now a cancel button is shown instead.
> Add error handling for checking points on first launch

- src/game/client/components/menus.cpp
The server browser is always refreshed on client start when the menus are first rendered. The additional use of the `SetMenuPage` function to initialize the menu page was causing the server browser to be refreshed unnecessarily.
> Fix server browser being refreshed multiple times on client start

- data/languages/azerbaijani.txt
- data/languages/belarusian.txt
- data/languages/brazilian_portuguese.txt
- data/languages/czech.txt
- data/languages/danish.txt
- data/languages/dutch.txt
- data/languages/estonian.txt
- data/languages/finnish.txt
- data/languages/french.txt
- data/languages/german.txt
- data/languages/korean.txt
- data/languages/persian.txt
- data/languages/polish.txt
- data/languages/portuguese.txt
- data/languages/romanian.txt
- data/languages/russian.txt
- data/languages/simplified_chinese.txt
- data/languages/slovak.txt
- data/languages/spanish.txt
- data/languages/swedish.txt
- data/languages/traditional_chinese.txt
- data/languages/turkish.txt
- data/languages/ukrainian.txt
- src/game/client/components/menus.h
- src/game/client/components/menus_demo.cpp
Tick back and forth exists, but that's too short
Translations have been changed to use %s instead of %d, procedurally formating numbers how is shown is bit of a pain
> More precise interval for demo l/r

- src/game/client/components/nameplates.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
> Store the StrongWeakId of the local player and use the stored data when the snap unavailable

- src/engine/shared/config_variables.h
- src/game/client/components/effects.cpp
- src/game/client/components/effects.h
- src/game/client/components/items.cpp
- src/game/client/components/menus.cpp
- src/game/client/components/menus_settings.cpp
- src/game/client/components/players.cpp
- src/game/client/components/players.h
- src/game/client/components/sounds.cpp
- src/game/client/gameclient.cpp
~~`snd_game_volume_others` has been added which is meant to control the volume of players in other teams~~
~~Unfortunatley, as per #10301, only skid sounds have all information to do this, this is why it hasn't been added to UI yet~~
See commits
> Sound refactoring and additions

- src/engine/shared/datafile.cpp
Regression from #9886.
Closes #10218.
> Fix incorrect datafile swaplen handling on big-endian systems

- src/game/server/gamecontroller.cpp
- src/game/server/teehistorian.cpp
- src/test/teehistorian.cpp
Previously if multiple spawn types (default,red,blue) were used. Only one of them would be considered for spawning.
Now tees are distributed across all spawn points even if different types are used in the map.
@def- looks like you introduced that. Any hard feelings here? Do you remember the reason why you did that?
72f3b774b87922a2738ecdc1ce48da58b4295874 CC #3837
I realized that while trying to fix https://github.com/ddnet-insta/ddnet-insta/issues/280. I can smoothly fix it in the downstream without introducing any problems. But I thought it would be nice for ddnet too.
https://github.com/user-attachments/assets/3de42c35-9a0b-40f2-b176-44aa9cc3b2d5
https://github.com/user-attachments/assets/f914c182-bbdd-462d-a111-5b40d30ff53e
> Distribute tees across all spawn types

- src/game/client/components/items.cpp
Reported by @l-ouis on discord:
laser heads are currently not predicted and may look a bit choppy. This is most obvious for the new rotating draggers. This PR aims to fix that by adding predicted/intra tick times to the laser head tick
> Add laser head prediction

- src/base/system.cpp
- src/base/system.h
- src/engine/client/client.cpp
- src/engine/server/server.cpp
- src/test/net.cpp
- src/tools/stun.cpp
Remove the function overload accepting the milliseconds as an `int` and instead only use `std::chrono` types and conversions.
Do not allow waiting for sockets indefinitely when time argument is negative, as this functionality is never used and may lead to issues on some systems. Waiting indefinitely should be avoided with the Emscripten client as it blocks the browser's main thread. It should also be avoided on Windows as it may lead to undefined behavior in the presence of asynchronous procedure calls.
Add doxygen documentation.
> Refactor `net_socket_read_wait` function

- src/game/client/gameclient.cpp
- src/game/client/prediction/gameworld.h
Fixes https://github.com/ddnet/ddnet/pull/10281#issuecomment-2945298554
Simply, if a player kills and their StrongWeakId was higher than ours, then we update our Id by 1
However, if a player disconnects instead of being killed, this still causes an incorrect update. I'm not sure if that's fixable. Of course, it goes back to normal once we stop spectating, this whole bug only occurs when we don't see our own character while in spectator mode.
> Fix preserved LocalStrongWeakId when player kills

- CMakeLists.txt
- src/game/client/components/background.cpp
- src/game/client/components/background.h
- src/game/client/components/maplayers.cpp
- src/game/client/components/maplayers.h
- src/game/client/components/mapsounds.cpp
- src/game/client/components/menu_background.cpp
- src/game/client/components/menu_background.h
- src/game/client/components/render_layer.cpp
- src/game/client/components/render_layer.h
Maplayers is currently doing a layer count for each tilelayer and quadlayer, does a lot of skip checks which are only needed in exceptions and is in not well generalized. This PR introduces objects to handle most of the exceptions and special functions for each layer, reducing most of the switch statements into polymorphism. From some crude testing on dm1, this slightly improves FPS and cleans up the code. The idea is, to create a render-list for a given maplayer type (foreground/background) and just iterating over it in order to render the layers
~~**WIP**!
Current State: Working with all backends, tidy up needed~~
If you have an idea how to split this PR up into smaller chunks, go ahead! I am also unhappy about it's size.
~~Currently contains a bug, where tune layers (and other entity …
> Refactor: build render pipeline for maplayers

- src/game/client/components/render_layer.cpp
- src/game/client/components/render_layer.h
After the pipeline merge the rendering initialization didn't swap after gpu uploads anymore. This PR reintroduces this.
@Jupeyy can you double check if this is right?
> Fix: move render loading into each layer

- src/game/client/components/menu_background.cpp
The `CMenuBackground::Render` function is called in the `CMenus::RenderLoading` function, where it should always cause the background to be rendered, and in the `CMenus::Render` function, where the client state is already checked before, so the client state should be not checked in the `CMenuBackground::Render` function, as this prevented the menu background from being rendered when loading the map for demo playback.
> Fix menu background theme not rendered when loading demo map

- src/game/client/components/menus_demo.cpp
Reported by @Robyt3
Don't know how I didn't see this
> Fix demo SKIP_DURATIONS_STRINGS

- src/game/client/components/nameplates.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/client/prediction/gameworld.h
This reverts commit d83bb21cd5d8ffb31d293ac2a929c19fbac6c77c.
It was not a proper fix as explained in https://github.com/ddnet/ddnet/pull/10281#issuecomment-2958490610 and it seems to cause more issues (#10361).
> Revert "Store StrongWeakId and uses when snap unavailable"

- src/game/client/prediction/entities/character.cpp
- src/game/client/prediction/entities/character.h
- src/game/server/entities/character.cpp
Reverts ddnet/ddnet#10254
1. #10275
2. We own this code, nobody can tell me we have to introduce inconsistent behavior for 1 tele exit, vs many tele exits.
The reverted PR has no linked issue that `accepted` that we merge inconsistent behavior.
Either we are consequent about this or we leave it be.
> Revert "Add teleport prediction when 1 exit"

- cmake/BuildVulkanShaders.cmake
- data/shader/quad.frag
- data/shader/quad.vert
- data/shader/vulkan/quad.frag
- data/shader/vulkan/quad.vert
- src/engine/client/backend/opengl/backend_opengl.cpp
- src/engine/client/backend/opengl/backend_opengl.h
- src/engine/client/backend/opengl/backend_opengl3.cpp
- src/engine/client/backend/opengl/backend_opengl3.h
- src/engine/client/backend/vulkan/backend_vulkan.cpp
- src/engine/client/graphics_threaded.cpp
- src/engine/client/graphics_threaded.h
- src/engine/graphics.h
- src/game/client/components/render_layer.cpp
- src/game/client/components/render_layer.h
With the pipeline in place we now after setup, if any quads in a quadlayer are animated or not. If none of them are animated, we can optimize their rendering by pushing their location and color.
This only applies to vulkan and OpenGL 3.3, falls back to default rendering in OpenGL 3 and 1
Before ~160 FPS:
After >1300 FPS (depends on zoom level):
Before ~36 FPS (no screenshot)
After ~ 1100 FPS:
@Jupeyy
> Optimize quad rendering by grouping quads

- src/game/server/entities/character.cpp
Fixes https://github.com/ddnet/ddnet/pull/10281#issuecomment-2958490610
Also fixes bugs related to incorrect predictions when being dragged into the tune zone while not looking, etc
This shouldn't break anything, because `/showall` works similarly but applies to all players, so the game already knows how to correctly handle players outside the player's view.
> Always snap the local player, even if he's not in view

- src/game/client/components/nameplates.cpp
Fixes #10361
Characters in spec char will have weak on everyone, if they don't have a snap StrongWeak id
> Fix StrongWeak indicator for spec char

- src/game/client/components/menus.h
- src/game/client/components/menus_settings.cpp
The names are wrong, now they aren't
No behaviour change
> Fix button container names in CMenus

- src/engine/client/backend/vulkan/backend_vulkan.cpp
Lately there was some find about invalid semaphore usage by lot (if not most) vk apps 
(
include vulkan tutorials, godot and even source engine
source: https://www.github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9802
)
I removed the whole in-flight concept that the tutorial suggest. I thought about the new, simpler concept for a bit now, it passes all validation tests. The in-flight concept never really made sense in my head (even tho I didn't know about this semaphore problem as well).
I'll think about it a few more days, just to be certain it's correct now
> Refactor swapchain sync object handling. Remove in-flight concept.

- src/engine/server/databases/mysql.cpp
The union `UParameterExtra` did not contain the largest expected type `int64_t`.
Closes #10378.
> Fix undefined behavior in `CMysqlConnection::BindInt64` function

- scripts/integration_test.py
The `data` folder inside the specified build folder should be used by the client instead of the `data` folder in the project root, as the latter does not contain the compiled Vulkan shaders.
> Fix incorrect `data` directory being used in integration test

- src/game/editor/editor.cpp
- src/game/editor/editor.h
Closes #8528
Holding a button locks the mouse to a single axis, based on the direction you moved it by at least 1 tile. 
The button is still undecided, since `Alt` and `Shift` are already used for other functions in editor. I’ve asked for suggestions for this in the mapping channel on Discord
https://github.com/user-attachments/assets/317ac48d-482d-4717-ac1c-780f1329c526
> Add button to lock mouse to a single axis in editor

- src/engine/editor.h
- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/editor_server_settings.cpp
- src/game/editor/prompt.cpp
- src/game/editor/quadart.cpp
- src/game/editor/tileart.cpp
Ensure resources of editor dialogs are properly freed by always using the `OnDialogClose` function to close dialogs.
> Consistently use `OnDialogClose` function for editor dialogs

- src/game/client/ui_rect.cpp
- src/game/client/ui_rect.h
- src/game/editor/editor.cpp
- src/game/editor/map_view.cpp
- src/game/editor/mapitems/layer_quads.cpp
- src/game/editor/mapitems/layer_sounds.cpp
- src/game/editor/proof_mode.cpp
Avoid duplicate code for rendering various selection rectangles in the editor.
Use `std::size` for line and vertex arrays and avoid redundant array sizes.
> Add `CUIRect::DrawOutline` function to draw rectangle outline

- src/game/client/components/players.cpp
While the skin prediction sounds good on paper, it has a lot of false positives. Most common on gores, if a player changed direction near a freeze, they would be incorrectly frozen for a frame. Changed it to only predict the skin for the local player, since we have all the player's inputs and this issue won't happen
> Predict freeze skin only for local player

- src/engine/server/server.cpp
> Fix server crash on vanilla info request with invalid token

- src/game/editor/editor.cpp
> Fix assertion due to incorrect envelope line batch usage

- src/game/client/lineinput.cpp
> Fix `CLineInput::m_WasCursorChanged` being uninitialized

- src/game/server/teams.cpp
`sv_save_worse_scores 0` hides chat messages from global chat. This is an unintended **undocumented** side effect and should only be done by `sv_hide_scores`.
closes #10446
> fix sv_save_worse_scores hiding global chat

- src/engine/server/server.cpp
- src/engine/server/server.h
See https://github.com/teeworlds/teeworlds/pull/3279#discussion_r2181098193
> Cleanup `CServer::GetServerInfoSixup`, allow negative token again

- src/engine/client/backend/opengl/backend_opengl.cpp
- src/engine/client/backend/opengl/backend_opengl3.cpp
- src/engine/client/backend/vulkan/backend_vulkan.cpp
- src/engine/client/input.cpp
- src/game/client/components/console.cpp
- src/game/client/components/infomessages.cpp
- src/game/client/components/menus.cpp
- src/game/client/components/menus_browser.cpp
- src/game/client/components/skins.cpp
- src/game/client/components/touch_controls.cpp
- src/game/editor/editor.cpp
- src/game/localization.cpp
- Used `reserve` and `resize` on vectors where it made sense
- Replaced invalid string `find` to remove `\n` logic with `std::remove`
- Replaced few vector `find` with `contains`
- Replaced old string `rfind` with `starts_with`
> Cleanup some vector resizing and lookups

- .github/workflows/build.yml
- CMakeLists.txt
Adds a MinGW GCC Windows build to CI actions, since most maintainers seem to build with it, and you have to wait for them to compile manually to test non-standard PRs
Bumped the GTest version in CMakeLists to [one version behind before they upgraded to CMake 3.16](https://github.com/google/googletest/commits/main/?since=2025-02-06&until=2025-02-07) because of this [GCC C++20 bug](https://github.com/google/googletest/issues/4108)
> Add MinGW build to github actions

- src/engine/shared/network.cpp
- src/engine/shared/network.h
- src/engine/shared/network_server.cpp
- src/engine/shared/protocolglue.cpp
- src/engine/shared/protocolglue.h
Connection-oriented 0.7 packets were first also incorrectly unpacked as 0.6 packets to determine that they are connection-oriented and subsequently unpacked correctly as 0.7 packets by considering the sixup-state of the current connection. Now, the packet size and flags are unpacked early, so the current connection slot and sixup state for connection-oriented packets can be determined based on the connless-flag before unpacking the remainder of the packet.
> Fix connection-oriented 0.7 packets being unpacked twice, move control packet size check, refactoring

- .github/workflows/build.yml
- .github/workflows/rust.yml
Fixes https://github.com/ddnet/ddnet/issues/9938
The issue was that by default `Swatinem/rust-cache@v2` caches `target` only in the root directory workspace, but `src/mastersrv` and `src/masterping` have their own separate workspaces.
Tested this change in my own repo.
Build times _benchmark_ (before and after):
mastersrv:  32.40s -> 13.58s
masterping: 13.07s -> 0.97s
total:      45.47s -> 14.55s
> Fix dependency cache for mastersrv and masterping in the CI

- src/engine/shared/console.cpp
> Fix handling of empty commands separated by semicolons

- src/game/editor/editor.cpp
> Fix editor crash with quad popup undo

- scripts/integration_test.py
- src/game/editor/editor.cpp
- src/game/editor/editor_server_settings.cpp
> Add basic integration test to open and close editor, fix use of uninitialized value when parsing map commands

- src/game/client/ui.cpp
- src/game/editor/editor.cpp
- Avoid unnecessary color conversion for editor color pickers.
- Adjust names of constants.
- Make assertion error more detailed.
> Minor cleanup of UI color picker

- src/engine/shared/network.cpp
- src/engine/shared/network.h
Internally determine whether to compress the packet in the `CNetBase::SendPacket` function, i.e. only try to compress non-control packets.
> Remove unnecessary `NoCompress` parameter of `SendPacket` function

- CMakeLists.txt
- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/mapitems/layer_group.cpp
- src/game/editor/mapitems/map.cpp
- src/game/editor/mapitems/map.h
- src/game/editor/mapitems/map_io.cpp
Move the `CEditorMap` and `CDataFileWriterFinishJob` classes to a separate header file and move the function definitions to source files.
Add an explicit constructor for the `CEditorMap` class to ensure that the editor pointer is always initialized.
Add a getter `Editor()` for the editor pointer of the `CEditorMap` class, to make the member variable private.
This is preparation for moving various functions and members from the `CEditor` to the `CEditorMap` class and eventually supporting multiple maps at the same time.
> Move editor map to separate source and header files

- src/engine/shared/network.h
- src/engine/shared/network_client.cpp
- src/engine/shared/network_conn.cpp
- src/engine/shared/network_console.cpp
- src/engine/shared/network_console_conn.cpp
- src/engine/shared/network_server.cpp
Add separate enums to reduce coupling and because the console connection uses less states.
Rename state `TOKEN` to `WANT_TOKEN` because it would collide with the type `TOKEN`.
> Add enums `EState` for `CNetConnection`/`CConsoleNetConnection`

- src/engine/shared/network.cpp
- src/engine/shared/network_server.cpp
Ensure token request buffer is zero-initialized in the `CNetBase::SendControlMsgWithToken7` function, to avoid uninitialized memory being sent over the network by the client in 0.7 token requests.
Use constant `NET_TOKENREQUEST_DATASIZE` instead of `512` and constant `NET_CTRLMSG_TOKEN` instead of `5` for 0.7 token requests.
Fix parameter `Ack` of `CNetBase::SendControlMsgWithToken7` function not being forwarded to `CNetBase::SendControlMsg` function call, though the value was always `0`.
> Fix uninitialized memory sent in 0.7 token message, refactoring

- src/game/client/components/maplayers.cpp
- src/game/client/components/maplayers.h
- src/game/client/components/render_layer.cpp
- src/game/client/components/render_layer.h
Expand the render params. This is a step towards a possible editor integration, because the editor (for now) doesn't use a buffered backend and we also need to be able to turn off borders. This also generalizes the overlay render flags.
Tested different render-param-configurations manually:
`cl_text_entities` is also working and tested
ctf5 cut off on top with `Params.m_RenderBorders = false`
> expand render parameters

- src/game/editor/editor.cpp
- src/game/editor/editor.h
To replace `UndoLastAction` and `RedoLastAction` functions and reduce duplicate code.
> Add `CEditor::ActiveHistory` function

- src/engine/client/client.cpp
- src/engine/client/graph.cpp
- src/engine/client/graph.h
- src/game/client/components/debughud.cpp
Add label to debug graphs showing the average, minimum and maximum of the currently shown range of values. The existing minimum and maximum values describe the axis values used for rendering instead of the actual minimum and maximum values.
Reduce overall background opacity of debug graphs. Add separate header and footer with darker background, to avoid graph data lines overlapping the labels.
Hide unnecessary decimal places for values in the FPS graph.
Move graph description label to the top left corner of graphs.
Make the center grid line of graphs the same color as the other grid lines, as the highlighted center line is not useful for most graphs.
Align graphs and their sizes with whole numbers to avoid graph data lines sometimes going beyond the background.
Screenshots with …
> Improve debug graphs: add avg./min./max. values, add header/footer

- src/engine/client.h
- src/engine/client/client.cpp
- src/game/client/components/camera.cpp
- src/game/client/components/camera.h
- src/game/client/components/hud.cpp
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
- src/game/client/projectile_data.cpp
- src/game/client/projectile_data.h
Reported by Aoe, who found out when playing demo in follow mode, Auto Sync Camera would reset to default zoom whenever the camera is recorded to be in freeview. This PR fixes that along with the following changes:
- Recorder now always record the local camera setting instead of following server feedback
- Disabled auto sync camera in non follow auto sync camera (previously it only records the recording PoV's camera setting making them mostly unavailable/unusable anyway)
- Removed the bottom right AUTO indicator when playing demo, player should only refer to the camera setting button in the demo control panel
Previously recorded demo will behave roughly the same, only when spectating other players (while in follow mode) would show the spectatee's PoV.
Newly recorded demo will always follow …
> Make demo recorder always record local camera setting

- src/game/editor/mapitems/layer_front.cpp
- src/game/editor/mapitems/layer_front.h
- src/game/editor/mapitems/layer_game.cpp
- src/game/editor/mapitems/layer_game.h
- src/game/editor/mapitems/layer_speedup.cpp
- src/game/editor/mapitems/layer_speedup.h
- src/game/editor/mapitems/layer_switch.cpp
- src/game/editor/mapitems/layer_switch.h
- src/game/editor/mapitems/layer_tele.cpp
- src/game/editor/mapitems/layer_tele.h
- src/game/editor/mapitems/layer_tiles.cpp
- src/game/editor/mapitems/layer_tiles.h
- src/game/editor/mapitems/layer_tune.cpp
- src/game/editor/mapitems/layer_tune.h
Fix inconsistent behavior when drawing with a non-destructive brush with unused tiles enabled. Previously, tile index `0` was not considered empty for speedup, switch, tele and tune layers when drawing a brush in non-destructive mode, but only for game, front and regular tile layers. Now, tile index `0` is consistently considered empty for all types of tiles and entities layers.
Make the `CLayerTiles::IsEmpty` function a real member function acting on `this` layer instead of acting on a pointer being passed as an argument.
Mark the `CLayerTiles::IsEmpty` function as `const` and `[[nodiscard]]`.
Move implementation for game and front layers from `CLayerTiles` class to subclasses `CLayerGame` and `CLayerFront`, consistently with the implementation for the other entities layers.
> Fix non-destructive brush with unused tiles, refactoring

- src/engine/shared/network.cpp
- src/engine/shared/network.h
- src/engine/shared/network_conn.cpp
- src/engine/shared/network_server.cpp
Flush the connection when the maximum number of chunks per packet has been reached, which is 255 due to the value being packed into 1 byte in the chunk header. Otherwise, the number of chunks would be truncated when sending a packet with more chunks. This should have been unlikely to happen in practice, but it could be forced to occur by having the server send a lot of small messages like empty snapshots or rcon lines.
Discard any non-control, non-resend packets that specify zero chunks in their header and discard any control packets that do not specify zero chunks in their header.
Add assertions to the `CNetBase::SendPacket` and `CNetServer::SendMsgs` functions to ensure that the number of chunks per packet is valid when the header is packed.
> Add checks for maximum number of chunks per packet

- src/engine/server.h
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/game/server/entities/character.cpp
- src/game/server/entities/character.h
- src/game/server/entity.h
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/gameworld.cpp
- src/game/server/gameworld.h
Motivation: @Learath2 told me to do this
Moved high bandwidth mode guard into the snapshot loop.
Removed `OnPostSnap` and `OnPreSnap` to prevent future utilization creating missing/mismatched state between snapshot since snapshots are processed at different rate now, these two hooks have 0 usage in 0.6 and only one usage for sixup and has been handled by special case.
Introduced the `GlobalSnap` concept to make sure state dependent information are processed at the correct rate (e.g. Events)
`force_high_bandwidth_on_spectate` rcon command will enable high bandwidth mode only for the caller player, no client shall receive exclusive high bandwidth snapshots when playing.
Requires heavy testing please.
> Allow GameServer to adjust high bandwidth mode for individual clients

- src/game/client/components/effects.cpp
Should be a trivial change
`FUpdateClock` -> `UpdateClock` (variable name not a type)
> Fix lambda variable name in CEffects::OnRender 

- src/game/collision.cpp
Only call the active switch callback if the switch number is valid, thereby ignore switch tiles with invalid number for the movement restriction calculation.
Closes #10574.
> Fix client crash with out-of-bounds switch numbers

- src/game/editor/editor.cpp
Makes the "Add sound source" button bigger so that the font size wouldn't be scaled down.
Fixes #10606.
https://github.com/user-attachments/assets/e3f8444b-5c81-48f6-86cb-41546325b6f5
> Fix "Add sound source" button's size (fixes #10606)

- src/game/client/render.h
- src/game/client/render_map.cpp
- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/mapitems/envelope.cpp
- src/game/editor/mapitems/envelope.h
Implement correct preview of envelope color in envelope editor color bar for envelope curve types besides linear, by evaluating sections between envelope points in multiple steps. Only use one step for linear and step curve types to improve performance.
Draw highlighting border around the color bar. Remove inconsistent margin on left and right sides when zoomed in.
Screenshots:
- Before: <img src="https://github.com/user-attachments/assets/06970a23-3487-4db4-80fc-eb713857642f" />
- After:  <img src="https://github.com/user-attachments/assets/18d336d8-d0a4-4a5c-a934-188c259d7b04" />
> Improve envelope editor color bar: support non-linear, add border

- src/base/system.cpp
The temporary filename to remove files on Windows does not need to be cryptographically secure. This avoids having to initialize the secure random functions to use filesystem functions, which was causing the `config_retrieve` tool to crash.
> Avoid need for secure random to be initialized for `fs_*` functions

- src/game/client/component.h
- src/game/client/components/mapimages.cpp
- src/game/client/components/mapimages.h
- src/game/client/components/maplayers.cpp
- src/game/client/components/maplayers.h
- src/game/client/components/render_layer.cpp
- src/game/client/components/render_layer.h
This PR clears graphic buffer container cleanly on map switch (or background map switch)
You can test this by monitoring the Texture memory and the Buffer memory with STRG+SHIFT+D and switching between ctf1 and ctf5 for example. The textures are cleared properly, but the buffer memory always seems to hit a max value.
> Properly clean buffer memory on map switch

- src/engine/shared/network.cpp
- src/engine/shared/network.h
Add assertions to ensure that data sizes do not exceed the maximum for connless packets.
Add constant `NET_CONNLESS_EXTRA_SIZE` for the size of the extra data of extended connless packets.
Use constants instead of magic numbers for sizes and offsets.
> Add sizes checks when sending connless packets

- src/game/editor/editor.cpp
Doing undo/redo while actively editing or moving something breaks history and in certain cases causes crashes.
> Only allow editor undo/redo when there is no active item

- CMakeLists.txt
Fixes #10668
Explicitly set `Embedded` for builds other than `Debug`
> Fix missing debug symbols on MSVC

- src/game/client/components/render_layer.cpp
- src/game/editor/mapitems/layer_group.cpp
This PR makes group clipping more stable by comparing clip region before normalizing and introducing the ceil and floor function for the clip.
The clipping cuts off the bottom of the church mosaics here due to floating imprecision with minimal zoom out
Cut out:
Editor was also in the mud (and the clipping even has 1 extra pixel in every direction):
Clipping doesn't cut of anymore at any zoom neither in editor nor ingame, and I tried!
[clip-test.zip](https://github.com/user-attachments/files/21605058/clip-test.zip)
> implement more precise group clipping

- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- src/game/server/teams.cpp
I have `sv_practice_by_default` enabled on my server for testing purposes. Sometimes, I need to disable it and have to remember to reload the server when testing team related features or spectating, since practice mode forces the spec char. 
This change adds an option to disable it without a server reload by calling `SetPractice` on all teams. Note that `sv_practice_by_default` only works with `sv_test_cmds`, which is restricted to the initial config and isn't enabled on offical DDNet servers, but is on test servers
> Add ability to disable sv_practice_by_default without server restart

- src/game/client/ui.cpp
- src/game/client/ui.h
- src/game/editor/editor.cpp
- src/game/editor/popups.cpp
- src/game/editor/prompt.cpp
- src/game/editor/quick_actions.h
Disable the file popup menu button, quick action and hotkeys to load the current ingame map when neither ingame nor in the demo player.
Fix the tooltip of this action incorrectly describing the hotkey as Ctrl+Alt+L.
> Disable `Load current map` action when not usable, fix tooltip, close popup menus when opening editor prompt

- src/game/client/components/menus_settings.cpp
The range was way too big and the scale was logarithmic making it impossible to select the desired value past half-way point anyways. `GfxRefreshRate` scrollbar is done this way already.
> Settings: adjust `ClRefreshRate` scrollbar range

- src/game/client/components/menus_settings.cpp
- src/game/client/components/skins.cpp
- src/game/client/components/skins.h
- src/game/client/gameclient.cpp
Adapt `CSkins::FindContainerOrNullptr` function to consider skin prefix instead of only considering it in the `FindOrNullptr` function.
Refresh skins when changing skin prefix config variable.
When loading a skin whose name begins with the configured skin prefix, also correctly reload skins that have the unprefixed name.
Closes #10655.
> Fix skin prefix setting not working correctly anymore

- src/game/editor/component.cpp
- src/game/editor/component.h
- src/game/editor/editor_object.cpp
- src/game/editor/editor_object.h
- src/game/editor/prompt.cpp
Remove unnecessary, mostly unused functions for hot/active editor object handling.
Move component lifecycle callbacks consistently to `CEditorComponent`, making `CEditorObject` only the owner of editor interface pointers.
Add separate `const` interface getter functions to `CEditorObject`.
Properly handle key-release events in subcomponents like in regular components.
> Cleanup editor object and component classes

- src/game/map/render_layer.cpp
Border tiles upload was always hard to read and felt very unoptimized.
part of #10663
> Clean Up: Rewrite tiles upload for borders

- src/game/client/components/maplayers.cpp
- src/game/map/render_layer.cpp
- src/game/map/render_layer.h
This code is duplicated. The tiles render layer also doesn't get a texture and this is already handled by the `Init` function, see https://github.com/ddnet/ddnet/blob/c781c6d2d2ad1d0aeb1125122ff004045b464de0/src/game/map/render_layer.cpp#L948
> Clean up: remove duplicated dead render code for quads

- src/game/map/render_layer.cpp
- src/game/map/render_layer.h
Split up quad clipping. This makes reading and handling and maintaining this feature easier and prevents deeply nested code
> Refactor: split up quad clipping into multiple functions

- src/game/map/render_layer.cpp
> fix automatic quad clipping for quads without position envelopes

- src/game/server/scoreworker.cpp
I get pinged for these regularly and just run move-sqlite.sh manually. So I switched it to be hourly instead.
> sql: Make it clear ranks will be auto-inserted regularly

- src/engine/server/authmanager.cpp
I was reading authmanager.cpp code and this just happend ... idk
> Go full c++ on the default slot count

- src/game/editor/editor.cpp
- src/game/editor/editor_trackers.cpp
- src/game/editor/editor_trackers.h
**CEditor::UiDoValueSelector**
Do not set `EEditState::START` until we scroll (the value changes).
**CQuadEditTracker** and **CSoundSourceOperationTracker**
Check if initial positions have changed before recording the action.
**CPropTracker**
Remove redundant `StartChecker` function completely and `EndChecker` function state checks.
Stop tracking on `EEditState::END` instead of that *AND* value change. Previously when original value didnt change:
\- prop A was saved as the start of an edit.
\- prop B was saved as the end of an edit.
\- prop A value != prop B value resulted in incorrect history.
Closes #8413
> Fixes to editor trackers

- src/game/server/entities/character.cpp
How does this bug still exist in 2025??????
https://github.com/user-attachments/assets/05e25023-8c2f-4eec-8428-1815167a5968
https://github.com/user-attachments/assets/11e42b4f-cb3d-4c50-a4d9-88e9004e1e84
> Fix death effect not being contained in solo part

- CMakeLists.txt
- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/editor_actions.cpp
- src/game/editor/editor_actions.h
- src/game/editor/editor_trackers.cpp
- src/game/editor/editor_trackers.h
- src/game/editor/mapitems/envelope.cpp
- src/game/editor/mapitems/envelope.h
- src/game/editor/popups.cpp
- src/game/map/render_map.cpp
- src/game/map/render_map.h
- src/game/mapitems.h
- src/test/mapitems.cpp
Represent fixed-point times in map items and the editor using `CFixedTime` class to replace `fxt2f` and `f2fxt` functions.
Round fixed-point time to integer when converting, to ensure that the conversion round-trips. Add test to confirm round-trip behavior.
Add check for zero and negative time delta when evaluating envelope. Return the value of the first point in this case instead of dividing by zero or negative time.
Add separate `CEditorActionEnvelopeEditPointTime` editor action to use `CFixedTime` type for times.
> Add `CFixedTime` for envelope point and bezier tangent times

- src/engine/shared/config_variables.h
- src/game/client/components/maplayers.cpp
- src/game/map/render_layer.cpp
- src/game/map/render_layer.h
- src/game/map/render_map.cpp
- src/game/map/render_map.h
This PR adds a debug option for rendering as discussed in #10737, this option can be iterated and advanced upon in the future.
The setting is not saved in the config and only for debugging purposes
closes #10737. It could be argued, that it doesn't close it and is only part of it, but then it should be more specified what debugging options should be added in order to close the issue.
> Feature: add debug render option

- src/game/map/render_layer.cpp
- src/game/map/render_layer.h
- src/game/map/render_map.cpp
- src/game/map/render_map.h
When I started this PR this was meant to be a cleanup of the `DoRender` logic as many render skips are still part of the Render routine for quads.
Then I noticed 2 bugs:
1. `m_ClShowQuads` also hides quads in the foreground. This is not was this option is supposed to do, it should only hide quads in the background in order to increase performance with the cost of design. This can hide gameplay relevant map parts.
2. the opacity of quads doesn't decrease in vulkan, if you increase overlay entities (only in ogl1)
only hiding background, the organ is in the foreground and has a hitbox:
The tooltip of the option says, that it should hide quads in the background (translates to "Quads are shown as background decoration"):
I don't believe this bug was necessarily caused by me, since the logic …
> fix & cleanup: Quad opacity is different between vulkan and ogl1

- src/engine/server/server.cpp
- src/engine/shared/demo.cpp
This should mostly prevent platform-specific issues with map and demo file names not being accepted on all platforms.
Closes #3529.
> Prevent loading server maps and recording demos with invalid names

- src/engine/demo.h
- src/engine/shared/demo.cpp
- src/engine/shared/demo.h
- src/game/client/components/menus_demo.cpp
Check if more ticks are still being written to the demo 1 second after starting playback to detect a live demo. For live demos, each tick incrementally scan for new tickmarkers and keyframes after the last keyframe to properly update the total time while playing the demo. Detect if the demo stopped being recorded by checking if no more tickmarkers have been written within 2 seconds.
Prevent seeking closer than 2 seconds to the end of live demos to avoid demo playback errors due to incomplete reads of the last demo chunk data which may still be written to by a demo recorder. Also reset the demo player speed to the default when fast-forwarding to the end of a live demo to prevent playback errors.
Show a red/grey dot indicator next to the demo seekbar for live demos. The indicator is red to …
> Support live playback of demos while they are being recorded

- CMakeLists.txt
- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_ingame.cpp
- src/game/client/components/menus_ingame_touch_controls.cpp
- src/game/client/components/menus_ingame_touch_controls.h
- src/game/client/components/touch_controls.cpp
- src/game/client/components/touch_controls.h
Supports editing touch controls ingame. General features:
1. Edit everything that can be changed by editing touch_controls.json
2. Move & zoom buttons on screen directly
3. Automatically avoid selected button being overlapped
4. Preview button layout under different visibilities
5. Browse & search for buttons by label, command or position
Other edits:
Use `m_JoystickCount` to support multi joysticks on screen so `swap-action` can act correctly
Previews:
> Touch controls editor

- src/engine/client/backend/vulkan/backend_vulkan.cpp
Less invasive version of #8691.
I am still sure it's a bug in mvk, but I am ok with this small workaround.
> Always force dynamic state for macos

- src/game/editor/editor.cpp
The `R` key now correctly types text in the map details screen instead of enabling quad rotation (reported by @texonik on discord)
Also brush rotation is now disabled when any popup is open, to prevent unwanted behavior, because the brush is invisible with popups open
> Prevent editor rotate keybinds from working while popups are open

- src/game/editor/editor.cpp
> Fix quad point context menu showing when cancelling rotation

- src/game/client/components/players.cpp
Not having it like this suggests that theres code after each if statement (and else or just flat) but there isn;t
part of #10828 
In the future someone should untangle line 193, it has been left as is here
> Never nest in CPlayers::RenderHookCollLine

- src/engine/client/backend/vulkan/backend_vulkan.cpp
Sadly I cannot remember if setting this to true made sense for e.g. windows, but generally vulkan always knows if it has to resize by itself.
Btw regardless this is IMO a bug in moltenvk:
https://www.github.com/KhronosGroup/MoltenVK/issues/2609
> Fix fullscreen on macos with vulkan

- src/game/client/components/items.cpp
- src/game/client/components/items.h
- src/game/client/gameclient.cpp
- src/game/client/gameclient.h
Cache the current and previous `CNetObj_Flag` snap objects in the `CSnapState`, instead of iterating over all snap items in the current snapshot each time that items including flags are being rendered.
Also cache the previous `CNetObj_GameData` snap object in the `CSnapState` in addition to the current one, to avoid searching for this snap item multiple times. Thereby, the `m_GameDataSnapId` member is not necessary anymore.
On the map dm1 with 64 players at zoom 0, this decreases the average frametime from 1431 µs to 1180 µs. The CPU time spent in the `CItems::OnRender` function in this scenario is reduced from 9.14% to 1.02% of the total CPU time.
Frametime comparison:
- <img src="https://github.com/user-attachments/assets/20597997-ee94-4754-a3b4-d6d0d0e03445" />
- <img …
> Improve flag rendering performance, also without flags

- src/game/editor/editor.cpp
- src/game/editor/editor.h
- src/game/editor/popups.cpp
- src/game/editor/quick_actions.h
This editor feature to preview and edit the position envelope points of quads directly is quite useful, but it was previously combined with the `Show info` setting, making it hard to discover. Add a separate setting `Preview quad envelopes` as well as a quick action to toggle the feature independently instead.
> Add separate setting and quick action for quad envelope preview

- src/game/server/gamecontroller.cpp
- src/game/server/teehistorian.cpp
- src/test/teehistorian.cpp
Reported by @psj_3 on discord
https://github.com/user-attachments/assets/a2079c23-548f-48cc-bcca-152565a415a0
> Fix spawn position when tees are standing on spawn tiles on other teams

- src/game/client/components/players.cpp
https://github.com/user-attachments/assets/5bfcf458-6868-41d5-beac-3a0d120fcbf0
Eyes go in the Hadoken direction, this was an unintended change... by someone
> Fix HadokenAngle affecting eyes

- src/README.md
- src/mastersrv/README.md
The `@mainpage` and `@page` commands already set the top-most page title for Doxygen. The `@page mastersrv mastersrv` was not correctly transformed while inside the `#`-headline with the older Doxygen version 1.9.8 that is used on the server.
The other `##`-headers are changed to `#` so their header level is directly below the page itself, otherwise they are not shown in the navigation menu.
Screenshots (with Doxygen 1.9.8):
- Before: <img src="https://github.com/user-attachments/assets/0f161c86-d500-4923-abcf-f906c06a8cc3" />
- After: <img src="https://github.com/user-attachments/assets/c4ed485d-1558-418e-a5d1-18f390890f10" />
> Fix doxygen navigation structure

- CMakeLists.txt
- src/base/fs.cpp
- src/base/fs.h
- src/base/system.cpp
- src/base/system.h
This is the start of a bigger move. Moving all `fs_` prefixed functions into their own file.
Cousin pr #10855
Helps with #10093
Replaced #10185
> Extract some functions into base/fs.cpp

- src/engine/shared/console.cpp
- src/engine/shared/console.h
Helps with #10836 which is needed for #10681
Allows to swap out `Next()` with a virtual method with a small git diff.
> Make `CCommand::m_Next` private

- src/engine/server/server.cpp
Before this change the code was non obvious to me. All the code does is not update the client if nothing changed.
The access levels in general are a bit confusing. Because lower access levels have more power. So reading 4 comparisons with greater and less than and these access levels is quite complex.
Also it does nothing if the command was not sent to the client yet. This check relies on the reader to know that if `m_pRconCmdToSend` is not `nullptr` the client is currently receiving rcon commands. And that these commands are sent in alphabetical order. And that on every send step their access level is checked. So the `str_comp() >= 0` checks if the changed command was already sent or not. Because if it was not sent yet we do not need to inform the client now since it will happen later …
> Easier to read rcon command update code

- src/game/client/components/touch_controls.cpp
When long press to select a button, it will call `UpdatePosition` if the button is overlapping with others, but `m_UnsavedChanges` is not set in this progress.
Also there're many `*(m_ShownRect).` thing, now set them to `m_ShownRect->`
> Fix unsaved changes not correctly updated, also `*().` to `->`

- src/game/editor/editor.cpp
If any quad envelope point in the quad envelope preview had a non-zero (non-default) rotation, then that rotation was incorrectly being applied to the following quad envelope points with zero rotation in the preview, due to the `pPoints` variable being reused over loop iterations but not being set when the rotation is zero.
Screenshots (only the top-right quad envelope point has a non-zero rotation value):
- Before: <img src="https://github.com/user-attachments/assets/baa9bc85-d7c5-465f-8851-eacb816c4315" />
- After: <img src="https://github.com/user-attachments/assets/d70e6030-616a-486e-a1ae-dd7ecb9ab1a9" />
I confirmed by playing the animation slowly, that the rotation and position of the animated quad now matches the positions and rotations of the quads being previewed for the …
> Fix quad envelope preview rotation affecting multiple quads

- src/engine/console.h
- src/engine/server/server.cpp
- src/engine/server/server.h
- src/engine/shared/console.cpp
- src/engine/shared/console.h
- src/game/server/ddracechat.cpp
- src/game/server/gamecontext.cpp
The AUTHED_ and ACCESS_LEVEL_ enums were easy to confuse. They represent the same thing but in a different numerical order. Now there is at least a bit of type safety instead of passing both around as integers.
> Use enum class for console access levels

- src/game/client/components/players.cpp
Reverse the check of hook state to never nest, then move the check for active hook to the top, I feel this reads better: "don't do anything unless there's an active hook"
~~Make copies of char const and move init to decleration (RAII or something)~~
> Nevernest some more in CPlayers::RenderHook

- .github/workflows/clang-tidy.yml
- CMakeLists.txt
- src/engine/client/video.cpp
- src/engine/shared/datafile.cpp
- src/game/client/components/censor.cpp
- src/game/client/components/menus_ingame_touch_controls.cpp
- src/game/server/save.cpp
See commit messages. #9961 and #10806 should have been caught if the warnings were enabled correctly.
> Fix string format warnings not being enabled in debug mode anymore, use clang-20 for configuring clang-tidy project

- src/engine/graphics.h
- src/game/editor/editor.cpp
Allows to write cleaner code on the call site.
> Add vec2 constructor for line items

- .clang-format
- src/engine/server/sql_string_helpers.h
- src/engine/shared/protocol7.h
- src/engine/shared/protocolglue.cpp
- src/engine/textrender.h
- src/game/editor/editor_ui.h
- src/test/mapitems.cpp
The only question I have viewing this is whether the protocol7.h should be changed like this, since it was probably more or less a direct copy before.
CC https://github.com/ddnet/ddnet/pull/10876#discussion_r2362341503
> Indent `namespace`s so migrated `enum`s look nicer

- src/game/map/envelope_extrema.cpp
Yet another kog map crashed on map loading, because the map contains invalid map data. This PR just adds more validation checks
> Fix: Add more envelope validations

- .clang-tidy
- src/engine/client/backend/vulkan/backend_vulkan.cpp
> Fix clang-tidy class member variable name exceptions

- src/game/client/components/players.cpp
Remove this vector reserve, as it may create issues with jank physics and cause huge allocations.
Reported by @SollyBunny
> Fix: Remove hook line reserve

- src/game/client/components/skins.cpp
Skins were only supposed to be updated every 25 milliseconds or slower depending on the FPS. However, due to the incorrect type `std::chrono::microseconds` being used and the `IClient::RenderFrameTime` function actually returning the average frame time in seconds, the update duration was reduced to only 25 microseconds.
Adjusting the skin updating to a more realistic frequency reduces average frametimes from 895 us to 622 us (1117 to 1607 FPS). Profiling shows that the CPU time spent in the `CSkins::OnUpdate` function is reduced from 22.81% to 0.87%.
Profiling:
- Before: <img src="https://github.com/user-attachments/assets/36c97d69-c8e1-4ae3-85a1-449a8a21859e" />
- After: <img src="https://github.com/user-attachments/assets/5996fc91-acf0-44e5-877b-81da44b5e7b3" />
> Fix performance regression due to very frequent skin updating

- src/engine/server.h
- src/game/server/gamecontext.cpp
- src/game/server/gamecontext.h
- Change argument to pointer to `CJsonWriter` instead of pointer to specific implementation `CJsonStringWriter`, as the function should not depend on the concrete implementation of the JSON writer.
- Rename argument `pJSonWriter` to `pJsonWriter`.
- Rename argument `Id` to `ClientId`.
- Improve doxygen documentation.
> Minor refactoring of `OnUpdatePlayerServerInfo` function

- src/game/client/components/ghost.cpp
- src/game/client/components/players.cpp
- src/game/client/components/players.h
Improves the hook collision line algorithm. Instead of creating a line segment for every simulated hook tick, it combines the segments to one.
This PR also adds a calculation limit, as with the right tuning values, e.g. `hook_length 9999` and `hook_fire_speed 1` it will calculate thousands of hook ticks each frame, which is certainly undesirable.
This PR introduces an unknown state, for hook teleporters with multiple exists and if the calculation limit is exceeded.
closes #10943
closes #10486
[TEST OUTDATED, now it's blue and skipped] Test extreme `tune hook_length 99999`, fps are still bad but waaaay better:
Test endless hook teleportation shenanigans:
Test teleport destination unclear, look it's blue:
[Hook-Tele output start is outdated] Test normal use case
Test no teleport destination …
> Refactor: Improve hook collision line logic

- src/engine/console.h
- src/engine/server/server.cpp
- src/engine/shared/console.cpp
- src/engine/shared/console.h
- src/game/server/ddracechat.cpp
- src/game/server/gamecontext.cpp
Needed for #10681
The method to get the first entry is already defined in the `CConsole` but the next was on the command it self. Which is proper linked list styled code. And it also worked because the command stores the access level so while iterating it has all the information it needs.
But when access levels become more complex this will no longer work. Because it is planned to no longer store that information on the command. Because there will be multiple different roles that can access a command and they are not strictly ordered by access level. So a simple integer comparison will not work.
The alternative would be moving all that context onto the command. That works by passing one callback and one callback context to every command on registration. I tried that approach too. It …
> Move linked list iterator `NextCommandInfo` to `CConsole`

- src/game/client/components/skins.cpp
Previously, you could only see favorite skins that could be loaded successfully. Now, all favorite skins are shown in the list, with question marks if they could not be loaded, e.g. if you favorite a skin that does not exists, or if you favorite a non-vanilla skin and enable vanilla-only.
> Also show favorite skins that were not found in list

- src/game/editor/editor.cpp
Previously, the currently select image/sound was kept when adding another one. Now, the newly added image/sound will automatically be selected. This is consistent with the behavior when adding new groups and layers, which are also selected automatically.
> Select editor images and sounds after adding them

- CMakeLists.txt
- scripts/generate_community_token.py
- src/engine/server/register.cpp
- src/engine/server/server.cpp
- src/engine/shared/config_variables.h
- src/mastersrv/Cargo.lock
- src/mastersrv/Cargo.toml
- src/mastersrv/src/community_token.rs
- src/mastersrv/src/config.rs
- src/mastersrv/src/main.rs
This will allow us to automate community handling.
My plan is to split https://info.ddnet.org/info into three parts. The finish information, to be served under a different URL, e.g.
https://finishes.ddnet.org/finishes?name=nameless%20tee, the static info without any DB acess, maybe https://info.ddnet.org/info2, and the community metadata and server info data, into https://master1.ddnet.org/ddnet/15/servers.json. There will be a
`communities` key in the top level with the static community information like name, icon, etc. The servers will get a new `community` key that is only set when the masterserver recognizes the community API token sent by the server (configured in the masterserver config). Other per-server community information like flag or server type is moved into the server info …
> Add community support to mastersrv

- src/mastersrv/src/addr.rs
It's not a valid port number, this catches it very early in the registration process.
> mastersrv: Disallow port 0

- src/game/client/components/countryflags.cpp
Isn't required for any country flag related rendering in DDNet but RenderQuadContainerEx doesn't reset rotation
Functions using this don't reset rotation either (eg `void CMenus::RenderServerbrowserCountriesFilter(CUIRect View)` and `void CMenus::RenderSettingsPlayer(CUIRect MainView)`)
> Add reset quad rotation to countryflag render

- src/game/client/ui_scrollregion.cpp
The current render frame time can be larger than the remaining `m_AnimTime` for smooth scrolling of scrollregions, resulting in the time becoming negative and the animation progress being incorrect for one frame.
> Fix potentially negative animation time for scrollregions

- src/game/map/render_layer.cpp
fixes an integer overflow in quad rotation clipping
closes #11018
> Fix: Quad rotation clipping integer overflow

- src/game/client/components/menus_start.cpp
This would be useful especially for the standalone Android version, which can only be compiled with `CONF_INFORM_UPDATE` but not with `CONF_AUTOUPDATE`.
Also change the label alignment and color with `CONF_INFORM_UPDATE` to be consistent with the label with `CONF_AUTOUPDATE`.
Screenshots:
- Before: <img src="https://github.com/user-attachments/assets/85c2ef1d-7e9a-4dc9-9646-f9ba47bf8198" />
- After: <img src="https://github.com/user-attachments/assets/a7cf7bd1-169e-4457-ac28-43741acb79a9" />
> Add button to open downloads page with `CONF_INFORM_UPDATE` option

- src/game/editor/editor.cpp
- src/game/editor/editor_actions.cpp
- src/game/editor/editor_actions.h
- src/game/editor/mapitems/map.cpp
Fully implement the editor action to add a new envelope using `CEditorActionEnvelopeAdd` to improve encapsulation.
Automatically select the newly added envelope in the envelope editor for convenience. Also restore the previously selected envelope when undoing the change.
> Move editor envelope creation into action, select after adding

- src/base/color.h
- src/engine/client/backend/opengl/backend_opengl3.cpp
- src/engine/client/backend/vulkan/backend_vulkan.cpp
- src/engine/graphics.h
- src/game/client/components/skins.cpp
- src/game/client/components/skins7.cpp
- src/game/client/ui_rect.h
Colors should not be implicitly converted to numeric vectors and vice versa.
Avoid including `vmath.h` in `color.h`. Add `vmath.h` include in other files where it was previously only included through `color.h`.
> Remove use of `vec3`/`vec4` math from color classes

- src/game/client/components/menus.cpp
- src/game/client/components/menus.h
- src/game/client/components/menus_demo.cpp
This reduces the number of clicks to get from server to demo, it also lets you look at what demos are available (eg replays) without leaving.
When this happens it will always ask whether you want to disconnect to avoid confusion and mistakes, this may be replaced with disconnect warning time later
screen is to thin to have all the buttons
screen is barely wide enough to have all the buttons
> Allow demo player everywhere
